### PR TITLE
relocate request tests and modernize API usage

### PR DESCRIPTION
**Pull request by garlick**
This PR relocates request test modules and programs from `src/test/request` to `t/request` (co-located with their sharness drivers) and modernizes their use of the Flux API.   It also fixes up API usage in a couple of other tests and fixes a buglet in `flux-module` error reporting.

### CODE REVIEW

**Comment by grondo** [comment]
Are some of the compat functions now unused? I guess they might still be used in flux-sched but according to coverage testing for flux-core `flux_json_response_decode` and `flux_json_request_decode` are no longer being called. (could also be a testing issue if you believe they still should be used from `make check`). Sorry, I know it isn't a priority but the drop in coverage % caught my eye, and sometimes that can indicate some tests were skipped.

**Comment by garlick** [comment]
Oh right, let me have a look, maybe we can drop a portion of libcompat.  As I recall @lipari updated all the deprecated usage in sched.

**Comment by garlick** [comment]
Rebased on current master and dropped some libcompat functions that are no longer used.

**Comment by garlick** [comment]
Pushed one more rebase after last log pr was merged.

**Pull request merged**
