### PR TITLE
libkvs: revert pr#1871 flux_kvs_watch_once() rework

### PR DESCRIPTION
**Pull request by garlick**
Problem: The changes to flux_kvs_watch_once() merged in
pr #1871 do not accurately reproduce the old KVS watch
behavior.

Rather than work on an accurate reproduction, revert
these changes.

Specifically this reverts the merge commit for that PR,
  2159faa1aeb436159728a30866443dd933063298
reversing changes made to
  3ead6b3760ee85e63598bb4b129a7f1bf7eca95e.

### CODE REVIEW

**Comment by chu11** [comment]
I'll merge once travis passes

**Comment by garlick** [comment]
Actually please don't merge - I'll do @SteVwonder 's first since he's travelling and might not be able to rebase easily.

**Comment by garlick** [comment]
Oh darn, I wasn't fast enough :-)

**Comment by chu11** [comment]
doh!  you literally commented a second after I hit the button :P

**Pull request merged**
