### PR TITLE
update python/lua KVS bindings to not use kvs classic functions

### PR DESCRIPTION
**Pull request by chu11**
Also fix random trivial things I found along the way.

### CODE REVIEW

**Comment by chu11** [comment]
it appears the trivial cleanups I did are not actually covered by any tests, thus the low diff coverage.  Should I just remove the trivial cleanups?

**Comment by SteVwonder** [comment]
Looks like pylint is not happy with some of the changes.

> Should I just remove the trivial cleanups?

It seems wrong to me to not include cleanups to appease the coverage tool.  I'm OK with the coverage drop, but I'll defer to others on this.

**Comment by chu11** [comment]
fixed up pylint issues, already squashed patch since it was simple.  Also rebased.

**Comment by garlick** [comment]
LGTM

**Comment by chu11** [comment]
hmmm i guess pylint conventions / warnings also have to be corrected

**Comment by chu11** [comment]
fixed warnings / convention complaints.  Considered using a property decorator for ```aux_txn``` in the flux handle, but it became complicated when trying to load the kvs bindings as well as the core bindings in ```handle.py``` so just removed the underscore prefix to ```aux_txn```.

**Comment by chu11** [comment]
oops, pushed the wrong tree, trying again

**Comment by garlick** [comment]
Maybe an ack from @SteVwonder on the python changes and then this can go in?

**Pull request merged**
