### PR TITLE
kvs: remove rootdir from setroot events

### PR DESCRIPTION
**Pull request by chu11**
Problem: Every setroot event includes the current rootdir tree object
in the event.  This allows all event receivers to "prime" their KVS
cache with the newest root directory object.  However, there is never
a guarantee that this new rootdir will ever be used.  For example, a
subsequent setroot event will overwrite the prior setroot event's
data before it is used.

During testing, it was determined that the cost of sending the rootdir
object on each setroot event and the processing of this event might
have a negative performance impact.  It appears it is a net win for
KVS clients to lookup root objects as they are needed.  Upon code
review, this makes sense, as treeobj_validate() and several blobref
functions are regularly called.  These are known to be relatively
slow iterating functions over data/strings.

Solution: Remove the 'rootdir' field from all setroot events.  As a
result, the `event_includes_rootdir` flag is no longer necessary and
has also been removed.  All code surrounding the rootdir processing
is also removed.

### CODE REVIEW

**Comment by chu11** [comment]
extra info: I used @grondo's throughput benchmark, which only runs `/bin/true`, so it may not be a perfect representative benchmark for this experiment.  But I made the decision to go with this change based on code review.  `treeobj_validate()`, `blobref_hash()`, and functions like these are iterative and relatively slow.  Doing it more times than necessary does "feel" bad.

**Comment by chu11** [comment]
> >  For example, a subsequent setroot event will overwrite the prior setroot event's data before it is used.
> Doesn't the prior setroot event land in the cache that is expired temporally?

Correct.  Perhaps what I said about is confusing.  What I was meaning to say was, lets say the order of things that happens is:

- setroot event received & processed
- setroot event received & processed
- kvs lookup

the second setroot event sets the root for the lookup to be done on.  So the processing of the first setroot event is sort of wasted and does nothing.  I'm imagining this may happen a lot.

>> Upon code review, this makes sense, as treeobj_validate() and several blobref functions are regularly called. These are known to be relatively slow iterating functions over data/strings.
> Isn't the cost of iterating and validating only incurred upon lookup? I would think we could prime the cache without doing this.

Take a skim at `prime_cache_with_rootdir()` and I think you'll see what I'm talking about.  It effectively does some work, which is less than doing a true lookup of the kvs root, but it is some nice chunk of processing.

Of course, we could take an alternate approach to try and "speed up" these "prime the cache" paths.

FWIW, I mostly went down this path after your comment of removing the `event_includes_rootdir` flag.  I was just going to assume the "true" path and was sort of surprised at the result after some testing.  I would have thought it would be a clear "win" to prime the cache.

**Comment by garlick** [comment]
That seems significant!  How many nodes on fluke?

**Comment by chu11** [comment]
> Just to be clear, by default the throughput benchmark doesn't run anything at all, you have to use the -x, --exec option to actually execute jobs via the job-shell. (I'm assuming you did that in your test.)

Whoops, I thought it was default.  But I always run `throughput.py -sxn NUMBER`.

**Comment by chu11** [comment]
> That seems significant! How many nodes on fluke?

32 nodes, 256 brokers.  Via `srun -N32 -n256 --pty src/cmd/flux start`

When I got to 16384 jobs was when the difference was more noticeable and consistent.  At lower job counts, results weren't as consistent and a clear winner was not obvious.  As an example, doing multiple throughput test of 1024 jobs.

w/ rootdir

w/ send rootdir = true

-``
throughput:     42.6 job/s (script:  41.2 job/s)
throughput:     40.3 job/s (script:  39.1 job/s)
throughput:     40.2 job/s (script:  38.8 job/s)
throughput:     39.0 job/s (script:  37.7 job/s)
throughput:     37.5 job/s (script:  36.5 job/s)
```

w/o rootdir

```
throughput:     42.9 job/s (script:  41.4 job/s)
throughput:     39.8 job/s (script:  38.6 job/s)
throughput:     39.3 job/s (script:  38.1 job/s)
throughput:     39.1 job/s (script:  37.8 job/s)
throughput:     38.2 job/s (script:  37.0 job/s)
```

the average here was actually higher w/ rootdir being sent, but no clear indication of a winner.

**Comment by grondo** [comment]
We still have that uncharacterized slowdown with increasing numbers of inactive jobs. I wonder if whatever is causing that effect makes your changes here more of a win as the number of jobs that have been run increases? (Just a wild guess). 

It might be interesting to run 16K jobs, then compare two runs with 1K jobs or similar and see if the difference is more pronounced.

**Comment by chu11** [comment]
> We still have that uncharacterized slowdown with increasing numbers of inactive jobs. I wonder if whatever is causing that effect makes your changes here more of a win as the number of jobs that have been run increases? (Just a wild guess).

I had just assumed the performance improvement was minor and simply more noticeable with larger job counts.  But now that you mention it, the "first run" is always faster with rootdir removed.  The inconsistency is with the later runs.  Here's another set of runs with 8192 jobs.

w/ rootdir

---
throughput:     34.4 job/s (script:  34.3 job/s)
throughput:     34.5 job/s (script:  34.3 job/s)
---

w/o rootdir

---
throughput:     34.6 job/s (script:  34.4 job/s)
throughput:     34.3 job/s (script:  34.1 job/s)
---

let me play around some more with this.  I didn't run the 16384 case two times just b/c it ran so long.  But let me try that.

**Comment by chu11** [comment]
Ugh, I just got these results for 16384 jobs ... I'm wondering if my initial runs were lucky?  Maybe will have to do a ton more and average em out.

w/ rootdir (master)
```
throughput:     29.0 job/s (script:  28.9 job/s)
throughput:     23.8 job/s (script:  23.8 job/s)
throughput:     19.7 job/s (script:  19.6 job/s)
```

this PR branch
```
throughput:     28.8 job/s (script:  28.7 job/s)
throughput:     23.4 job/s (script:  23.4 job/s)
throughput:     19.5 job/s (script:  19.5 job/s)
```

**Comment by garlick** [comment]
While the impact on job throughput might not support removal of this optimization, I still think it's a good idea.

I would re-state the commit message something like this:
```
Problem: The KVS publishes a setroot event for every update.  As an optimization,
the event payload currently includes the latest root directory, since this is likely to
be required for any lookup against the new root.  However, the optimization incurs a
processing overhead on every broker, even those quietly running user work, and only
helps performance if there is a lookup against the updated snapshot.
This code adds complexity for a dubious benefit, and potentially causes harm by
increasing "system noise".

Solution: Remove the 'rootdir' field from all setroot events. As a
result, the event_includes_rootdir flag is no longer necessary and
has also been removed. All code surrounding the rootdir processing
is also removed.
```

**Review by garlick — APPROVED** [review]
I think this could go in with just a commit message fixup as noted in my comment.  Feel free to force push that and set MWP if you're ready.

**Comment by chu11** [comment]
doing some more benchmarking, it appears that on average throughput on "no rootdir" leans a tad better.  Its not a slam dunk, but at the worst its a draw.

**Comment by chu11** [comment]
> I think this could go in with just a commit message fixup as noted in my comment. Feel free to force push that and set MWP if you're ready.

Sounds good. thanks

**Pull request merged**
