### PR TITLE
event loop back end rework + switch to libev

### PR DESCRIPTION
**Pull request by garlick**
This PR switches the reactor implementations from zloop to libev, embeds a current libev release, and reworks the interface between the generic handle code and the reactor implementations.

These changes remove some malloc/free and linear list search activity from critical paths.  The putmsg queue is now implemented as a zlist, so both handles drop a set of PAIR zmq sockets, and the API implementation no longer needs a zmq context.

In addition, there is a fix for a fairly egregious design issue with kvs watch (and more generally requests that get multiple replies) versus the putmsg queue and matchtags documented in #146.  The fix is to add another reactor back-end operation called "purge" which removes any queued out of order messages for matchtags that are being retired.

I did not add any new reactor tests other than the ones that directly test the new aggregate libev watchers. This is because I would rather wait until we have settled any changes to the public reactor interfaces before creating new tests that use them.  I have run the existing regression tests quite a lot on various platforms and they are quite stable for me.

### CODE REVIEW

**Comment by grondo** [comment]
Nice job, this seems to represent a major rework for the better!

I'm trying to review the changes, and since CI tests all pass I'm mainly interested in any changes to the flux and/or module APIs. I thought it might be more efficient if you could quickly summarize any API changes. If there are none, maybe that is why I'm having trouble finding them ;-)

Also, sorry for the `zio` bug

**Comment by garlick** [comment]
Sorry, should have said up front that this does not alter the public interfaces, except that the "handle implementor" interface happens to be public, and some of that changed.  I'm not sure we should continue to publish that as I wonder if it is useful to have handle implementations outside of flux-core.

**Comment by grondo** [comment]
Ok, thanks.

**Comment by trws** [comment]
This closes #138 doesn't it?

**Pull request merged**
