### PR TITLE
libflux: drop flux_sec_t class from public API

### PR DESCRIPTION
**Pull request by garlick**
As suggested in #1843, the `flux_sec_t` code is only used by the broker and `flux-keygen` and doesn't have an out of tree use case that I can think of.  It's also old code in need of a makeover.

Hence, move it to `libutil/zecurity.[ch]` and re-namespace from `flux_sec_*` to `zsecurity_*`

### CODE REVIEW

**Comment by SteVwonder** [comment]
`sec.py` should be removed from `fluxpy_PYTHON` in `src/bindings/python/flux/Makefile.am`.

In `t/valgrind/valgrind.supp` there is a reference to `fun:flux_sec_comms_init` that should change to `fun:zsecurity_comms_init`.

Otherwise, LGMT!  Thanks @garlick!

**Comment by garlick** [comment]
Crud, still looks like it's failing something in python land.  I went ahead and rebased.

**Comment by SteVwonder** [comment]
Looks like pylint is unhappy because `flux/__init__.py` still lists `sec` under `__all__`: https://github.com/flux-framework/flux-core/blob/master/src/bindings/python/flux/__init__.py#L15  Removing it from the list should fix that.  The binding tests still work because none of them leverage `__all__` like via a wildcard import (`from flux import *`), which is bad form anyway.

Pylint error message:
```
************* Module flux
E: 15,11: Undefined variable name 'sec' in __all__ (undefined-all-variable)
```

I'm not sure why the first builder (with no configure flags) failed.  All I found was:
```
       t2202-job-manager.t:  PASS: N=30  PASS=30  FAIL=0 SKIP=0 XPASS=0 XFAIL=0
ERROR: t2202-job-manager.t - exited with status 137 (terminated by signal 9?)
```
Maybe just a transient error?  Restarting that builder just to see what happens.

**Comment by garlick** [comment]
This might be OK to merge despite the so-so coverage, since it's for the most part a straightforward move,  coverage problems are pre-existing, and code needs to be reworked at some point.

**Comment by grondo** [comment]
Merging so we can move other PRs along

**Comment by garlick** [comment]
Thanks!

**Pull request merged**
