### PR TITLE
job-info: module & test cleanup

### PR DESCRIPTION
**Pull request by chu11**
Splicing out a few cleanups + test enhancements from #2926

- remove dead code
- add some missing tests
- refactor a little code in job-info
- add "failed job" and "cancelled job" tests to t2204-job-info and t2800-jobs-cmd

### CODE REVIEW

**Comment by chu11** [comment]
ugh, found an old bug I need to fixup .. hold up until that's fixed too

**Comment by chu11** [comment]
ok, also added a bug fix & test to ensure that all data from the KVS is read correctly when the module is reloaded.

**Comment by grondo** [comment]
Looks like the ASan builder hung, so I restarted it.

**Comment by chu11** [comment]
@grondo thanks!

**Pull request merged**
