### PR TITLE
NEWS.md: add release notes for v0.52.0

### PR DESCRIPTION
**Pull request by garlick**
Replease notes for 0.52. Change as needed!

This assumes the PRs added to the 0.52 milestone are going to be merged first.

### CODE REVIEW

**Comment by chu11** [comment]
pushed a fixup, i think one of the features is really a fix.

optionally, dunno what people's opinions are here ..  this feature

> python: support "original" option in job kvslookup module (#5311)

adds a feature to the new addition ...

>  python: support convenience API for `job-info.lookup` RPC / "flux job info" (#5265)

So it's sort of a feature on top of a new feature ... we could just remove the first one, it maybe isn't necessary?

**Comment by grondo** [comment]
> So it's sort of a feature on top of a new feature ... we could just remove the first one, it maybe isn't nece

I'll sometimes combine those when I spot them in the NEWS, e.g. 
```
 * python: support convenience API for `job-info.lookup` RPC / "flux job
   info" (#5265, #5311)
```

**Comment by grondo** [comment]
I'll go ahead and make that change, squash the fixups, and force push the result.

**Review by grondo — APPROVED** [review]
LGTM!

**Comment by grondo** [comment]
Thanks @garlick for doing this! I'll give it an hour or so then set MWP.

**Comment by garlick** [comment]
Could we get #5309 and #5298 merged first? They need a quick review.

**Comment by grondo** [comment]
Sure, sorry I missed those. Both PRs are approved now.

**Comment by garlick** [comment]
Thanks!

**Comment by grondo** [comment]
Ok, setting MWP.

**Comment by garlick** [comment]
Just checking in and I see the other PRs are merged, so I'll set mwp here.

**Pull request merged**
