### PR TITLE
KVS: refactor kvs lookup replays

### PR DESCRIPTION
**Pull request by chu11**
Per discussion in #1318, refactor replays of lookups to use flux msg aux instead of rpc ```arg``` parameter.

This cleans up the code a bit and IMO makes it more clear, but the big win is the removal of the ```msg_cb_handler``` mini-library in the KVS module.

This PR follows #1694 and should be merged after it.

### CODE REVIEW

**Comment by chu11** [comment]
rebased on master after the #1694 merge

**Comment by grondo** [comment]
Nice cleanup!

**Comment by grondo** [comment]
Hm, your build hit the same hangs as @SteVwonder saw in #1699 at

```
 python/t0008-jsc.py:  PASS: N=4   PASS=4   FAIL=0 SKIP=0 XPASS=0 XFAIL=0
```

I'll try restarting builders for now, but we may have to reopen #1699 and follow up (now that we know it can be reproduced in a PR I guess)

**Comment by chu11** [comment]
It seems to have hung again:

```
       python/t0008-jsc.py:  PASS: N=4   PASS=4   FAIL=0 SKIP=0 XPASS=0 XFAIL=0

No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
The build has been terminated
```

Time to re-open #1699?

**Comment by garlick** [comment]
This looks great @chu11!

**Comment by chu11** [comment]
stephen seems to have his debug logs, so restarting the builder hoping it'll pass this time

**Comment by chu11** [comment]
looks like it passed this time

**Pull request merged**
