### PR TITLE
github: fixes for workflow scripts

### PR DESCRIPTION
**Pull request by grondo**
Mistakes were made.

This fixes use of an incorrect environment variable in `docker-deploy.sh` and a bug in `checks_run.sh` that was causing `make recheck` to be run on every non-distcheck build.

### CODE REVIEW

**Review by garlick — APPROVED** [review]
Take heart - perfection is the enemy of progress.

**Comment by grondo** [comment]
Thanks! I've set MWP -- we'll now see if mergify config is correct.

**Comment by grondo** [comment]
Arrgh, one typo in `.mergify.yml` (for some reason took me awhile to spot it)

Pushed a fix, but this will have to be merged by hand due to mergify config changes. Sorry!

**Comment by grondo** [comment]
I'm actually considering adding `make recheck` to normal builds as well. This works around the `"Killed by signal 9(?)"` errors by re-running those failing tests once per CI build. What do people think of that? A warning would still be issued when `make recheck` is triggered, and recheck can't be used for `distcheck` builds...

Also, I think I have an improvement to the script that generates the build matrix (generate the whole docker-run-checks.sh commandline in the script not just pieces of the arguments). I'll push that here after I ensure that it works.

**Comment by grondo** [comment]
One of the builds hit a failure:
```
Error: ERROR: t2314-resource-monitor.t - exited with status 137 (terminated by signal 9?)
```

So I went ahead and added the `--recheck` option to all builds (except `distcheck`, with which it is not compatible)

**Comment by garlick** [comment]
LGTM Thanks!

**Comment by grondo** [comment]
Thanks!!

**Pull request merged**
