### PR TITLE
librouter: move sendfd, recvfd out of public API

### PR DESCRIPTION
**Pull request by garlick**
Another bit peeled off of #2303 (librouter).  This one removes some specialized functions for sending and receiving flux messages over file descriptors from the main API, renaming it and relocating to the private librouter library (which this PR creates).  Convert users, add inline documentation, and enhance unit testing.

### CODE REVIEW

**Comment by garlick** [comment]
Rebased on current master, and noting missing coverage of bad args, added some to the unit tests and discovered a segfault, which was fixed.

**Comment by garlick** [comment]
Restarted a clang builder that failed here (I assume just a spurious timeout)
```
ERROR: t1003-kvs-stress.t - exited with status 137 (terminated by signal 9?)
```

**Comment by garlick** [comment]
Hmm, builds finished successfully, but travis-ci completion didn't seem to get picked up by github.  I went ahead and restarted the whole travis-ci build.

**Comment by grondo** [comment]
LGTM! My only comment is that the naming of `sendfd` `recvfd` and `iobuf_*` are pretty generic, and don't necessarily look like they'd be something in the "librouter" convenience library. However, I don't really have a better suggestion at this time and I don't feel strongly enough at this time to hold up the PR.

**Comment by garlick** [comment]
Yeah, I wasn't sure about that, but I also didn't have a great alternate name on the tip of my tongue.  It isn't published, and it won't have broad usage within flux-core, so could be renamed later if we found a problem.  This is prob OK to go in if you think it looks OK.

**Comment by garlick** [comment]
Thanks!

**Pull request merged**
