### PR TITLE
rfc: subcommand support for optparse_t

### PR DESCRIPTION
**Pull request by grondo**
I was playing with an enhancement to `libutil/optparse.c` to allow option parsing object to handle subcommands and I thought I'd better post here for review before I get too much farther.

This PR so far implements the enhancements to `optparse.c` (with tests) and then converts `flux-event.c` and `flux content` from `flux.c` to the new scheme as a demonstration.

Next on the list would be to attempt to convert `flux.c` itself, and use the new methods to make creating new builtin commands in `flux.c` a bit simpler.

The basic enhancement here is to allow registration of named "child" parsers to a top-level `optparse_t` object to allow easy implementation of subcommands for flux utilities. A subcommand option parser is also an `optparse_t` object, so registering options, modifying usage, etc. work the same as for normal top-level `optparse_t`.

Subcommands are registered either via a call to create a new optparse_t as a child of an existing `optparse_t` object `p` with `optparse_add_subcommand()` or a convenience function `optparse_reg_subcommand()` can be utilized which registers a subcommand, a callback,  its `usage` string, a short `doc` string, and any options table all in one go:
```C
typedef int (*optparse_subcmd_f) (optparse_t *p, int ac, char **av);

/*
 *   Create a subcommand optparse object as a child of [p].
 *    [name] is subcommand name for subcmd callback [cb].
 *
 *   Returns an optparse object for the subcommand, which can be used
 *    to register subcommand options, set usage, etc.
 */
optparse_t *optparse_add_subcommand (optparse_t *p,
                                     const char *name,
                                     optparse_subcmd_f cb);

/*
 *   Convenience function like optparse_add_subcommand, additionally
 *    registering with usage string [usage], documentation blurb [doc] and
 *    any options from optparse_option table [opts]. Use
 *    optparse_get_subcommand() to get subcommand optparse handle.
 *
 *   Returns OPTPARSE_SUCCESS on successful registration, or an optparse_err_t
 *    on failure.
 */
optparse_err_t optparse_reg_subcommand (optparse_t *p,
                                     const char *name,
                                     optparse_subcmd_f cb,
                                     const char *usage,
                                     const char *doc,
                                     struct optparse_option const opts[]);
```

Subcommands can be run after an initial call to `optparse_parse_args()` using
the following call
```C
int optparse_run_subcommand (optparse_t *p, int argc, char *argv[]);
```

Or, for a simple command made up entirely subcommands, a `parse_deeply` call is provided which basically calls `optparse_parse_args()` followed immediately by `optparse_run_subcommand()`
```C
int optparse_parse_deeply (optparse_t *p, int argc, char *argv[]);
```

The subcommand callback is passed the optparse object *for the subcommand* and `argc` `argv` adjusted to the first non-option argument from the parent's `optparse_parse_args` (i.e. `argv[0]` shall equal the subcommands `"name"`)

When `optparse_print_usage (p)` is called for an `optparse_t` object `p`, and the parent optparse object does not have an overriding usage message registered, each registered subcommand's usage string is output separated by `"or"` along with the any options registered for the *parent* e.g. for `flux-content`:
```
Usage: flux-content dropcache [OPTIONS]
   or: flux-content flush [OPTIONS]
   or: flux-content load [OPTIONS] BLOBREF
   or: flux-content store [OPTIONS]
Access content store
  -h, --help             Display this message.                  
```

Similarly, `command subcommand --help` should automatically invoke the usage message for the subcommand:

```
 $ ./flux content store --help
Usage: flux-content store [OPTIONS]
Store blob from stdin, print BLOBREF on stdout
  -b, --bypass-cache     Store directly to rank 0 content service
  -d, --dry-run          Compute SHA1 but don't actually store value
  -h, --help             Display this message.
```

### CODE REVIEW

**Comment by garlick** [comment]
That works out pretty nicely!

Looks like the subcommand `optparse_t` is destroyed when the parent is destroyed.  Is there a missing destroy in `flux-event`?

**Comment by grondo** [comment]
> Looks like the subcommand optparse_t is destroyed when the parent is destroyed. Is there a missing destroy in flux-event?

Yes, good catch!

**Comment by grondo** [comment]
Ran `valgrind` on `flux-event` just to check and found a couple other errors that I don't quite understand yet -- not sure if these were already there or not but I may try to run this down, too.
```
==804934== Invalid read of size 4
==804934==    at 0x405CB7: optparse_parse_args (optparse.c:1003)
==804934==    by 0x402461: main (flux-event.c:57)
==804934==  Address 0x6e947b0 is 0 bytes inside a block of size 2 alloc'd
==804934==    at 0x4C2AB80: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==804934==    by 0x406121: optparse_parse_args (optparse.c:978)
==804934==    by 0x402461: main (flux-event.c:57)
==804934==
```

**Comment by grondo** [comment]
btw, I also wasn't thrilled with the function name `optparse_parse_deeply`, any other suggestions? This function should really be something like `parse_and_run_subcommand` but that was getting too long.

**Comment by garlick** [comment]
Maybe an `optparse_set()` flag could change the behavior of `optparse_parse_args()` to call the subcommand callback, and then you wouldn't need `optparse_parse_deeply()`?

**Comment by grondo** [comment]
> Maybe an optparse_set() flag could change the behavior of optparse_parse_args() to call the subcommand callback, and then you wouldn't need optparse_parse_deeply()?

That is a great idea, but I couldn't decide how to change the return type for `optparse_parse_args()` to handle that case.

Would it be too confusing if `optparse_run_subcommand()` automatically called `optparse_parse_args()` internally if initial argument parsing wasn't completed yet? Either way, I removed `optparse_parse_deeply` for now (it was literally a 3 line function)

**Comment by garlick** [comment]
Sure, that seems ok to me.

**Comment by grondo** [comment]
OK, another update for this PR:
 * If `optparse_run_subcommand (p, argc, argv)` is called before `optparse_parse_args ()` then the function automatically calls `optparse_parse_args ()`.
 * Changed the prototype for `fatalerr` function to `int fatalerr_fn (void *arg, int code)`. This function is meant to handle fatal error *after* any message has been printed. Thus the default is `exit (code)`. On a fatal error, optparse logs the error with `LOG_FN` then returns the return code of `FATALERR_FN`. By default, error message is written to stderr and exit() is called.
 * Added convenience function `optparse_fatal_usage (optparse_t *p, int code, char *fmt, ...)` to print an optional error message, display usage, and exit.

I still plan to convert `flux.c` and implement a more canned scheme for adding builtins. Most likely builtins will each move to separate source files under `src/cmd/builtin/*.c` and automatically wired in as subcommands of `flux(1)` somehow...

**Comment by grondo** [comment]
This build is still failing in Travis, but since their log display seems to be down today I'm not yet sure why. However, here's the rundown on the latest changes in the PR for comment:

 * Changed the `fatalerr` prototype for optparse_t. Now `fatalerr` is just the handler for fatal conditions, by default `exit (code)`. Any fatal error will be logged via the `log_fn` before calling `fatalerr_fn`
 * Added `optparse_fatal_usage()` to print usage and exit for convenience
 * Added an option to disable the auto-print of registered subcommands (required for `flux(1)` usage)
 * Addition of a `struct optparse_subcommand` struct and `optparse_reg_subcommands` to register a table of these in one go (do we still need `optparse_reg_subcommand()` then?)
 * Changed `flux(1)` to use optparse, and moved all "builtin" subcommands into individual files in `src/cmd/builtin/*.c`. The description of how this currently works is in 86bc86a :
 ```
All internal flux(1) subcommands are now registered as optparse
subcommands. In order to ease the addition of new builtins, builtin
subcommands are grouped separately in src/cmd/builtin/*.c and compiled
into flux.c.

Each builtin module now exports a single "registration" function
named `subcommand_<name>_register`, where <name> is replaced with
the basename of the C source file. The registration function is
responsible for registering one or more new subcommands with flux.c
optparse_t object which is passed to the function.

A new script `builtin-cmds-list.sh` automatically generates a table of
these functions in builtin-cmds.c for use during flux.c initialization.
```

In this system, to add a new builtin, just drop a new `cmd.c` into `src/cmd/builtin` and add the file to `flux_SOURCES`. A function to register one or more subcommands should be added to `cmd.c` and called `subcommand_cmd_register (optparse_t *p)`.

This still needs a bit more testing and refinement, and some comments on the general approach.

**Comment by dongahn** [comment]
> but since their log display seems to be down today

Off topic, but is this why I was getting only blank log for sched? I thought I did something silly. Bummer.

**Comment by garlick** [comment]
Having the flux.c subcommands split out into separate files is a great cleanup, and the generated table makes adding new subcommands to flux.c fairly painless.  I like it.

I don't think I have further comments on the optparse interface.  It seems reasonable to me.

**Comment by grondo** [comment]
> Off topic, but is this why I was getting only blank log for sched? I thought I did something silly. Bummer.

Yeah: https://www.traviscistatus.com/incidents/fcllblkclgmb

**Comment by grondo** [comment]
Oh, and I guess the last change I made finally let the build/test succeed.

Open questions:
 * I was thinking if `flux.c:main()` has to `flux_open()` then the handle could be pushed into the `optparse_t` object for use in subcommands. In some cases `flux_open` is called twice from the same program I think.
 * Now that `optparse_get (p, OPTPARSE_DATA, ...)` is used frequently it feels a bit clunky. Even though it does cut down on the number of API functions, perhaps an `optparse_setctx/getctx` would be easier to use?
 * Still need to investigate #519 and see if we need a fix for that crash here.
 * Consider moving other small flux-CMD.c commands into builtin/*.c?

**Comment by grondo** [comment]
Ok, I just pushed a fix for #519 and extra testing and small enhancement for error generation for `optparse_parse_args`.

I'll see about `optparse_get (p, OPTPARSE_DATA, ...)` a bit after lunch, I think I want to convert that to its own get/set functions...

**Comment by grondo** [comment]
Ok, that was a painful rebase. Basically `optparse_get_data/set_data` are swapped in for `optparse_get/set (p, OPTPARSE_DATA, ...)`. The result seems a bit more user-friendly.

I also squashed a lot of intermediate commits out of existence, and cleaned up a lot of others.

The final commit here I'm not so sure about -- I added support for builtins to reuse `flux.c`'s handle if it has to open one -- doesn't seem like it is all that great of an improvement, and in the case of `exec`ing a subcommand has to be special-cased, so I'd be willing to back that one out if it is deemed unnecessary...

**Comment by garlick** [comment]
That's probably OK.  My only concern would be if maybe `flux help` now bombs out if the handle can't be open (I didn't check if this is the case or not).

I'm inclined to merge, any objections?

**Comment by grondo** [comment]
> My only concern would be if maybe flux help now bombs out if the handle can't be open (I didn't check if this is the case or not).

`flux.c` only opportunistically pushes the flux_t into the optparse_t object if it called `flux_open` anyway, so there shouldn't be any change there. I added a new call `builtin_get_flux_handle` that first checks for already open `flux_t` and calls `flux_incref (h)` if so, otherwise `flux_open` is called -- does that sound ok?

The main change I'm worried about is that the handle is no longer immediately closed after reading config. Before calling exec() the handle is explicitly closed, to avoid potentially leaking across exec().

**Comment by garlick** [comment]
FWIW the local connector does set SOCK_CLOEXEC on the broker socket.

**Comment by grondo** [comment]
I saw that but wasn't sure if it would be guaranteed for all connectors?

**Comment by garlick** [comment]
Not guaranteed but we can always address it if it becomes a problem.  Let's merge!  (say OK)

**Comment by grondo** [comment]
Ok, hopefully no big issues here (don't feel like I checked things out fully), but I think we can merge this one...

**Pull request merged**
