### PR TITLE
Add an error print if dlopen fails

### PR DESCRIPTION
**Pull request by trws**
Originally from #236.

I'm not sure this is the best way to handle it, but otherwise the error for a
module dependency being unavailable is "invalid argument" in the broker.  This
has to be more debuggable, but I'm open to suggestions for better handling
here.

### CODE REVIEW

**Comment by grondo** [comment]
Hm, yeah, this error really needs to be propagated back to the caller (ideally all the way back to the client using `flux-module insmod` (?)).

There is a similar error in `flux_modname_cmp` which should probably be fixed in this same PR (not sure if that one causes an error in practice though)

Ideally `flux_modname` would somehow be able to send a useful error back to caller, but maybe in general the interface should support grabbing a `modinfo` handle that stores module name and service  or error information if `path` can't be opened:

e.g.
```C
flux_modinfo_t *mi = flux_modinfo_get (path);
if (!mi)
    /* out of memory */
if (flux_modinfo_errmsg (mi))
   /* return errmsg somehow */
service = flux_modinfo_service (mi);
name = flux_modinfo_name (mi);

out_cleanup:
flux_modinfo_destroy (mi);
```

Not sure if this is the best way, just thinking aloud. I though Jim had a pretty good design for the loadable module support, so perhaps propagating these errors is covered somewhere.

**Comment by garlick** [comment]
Merging, maybe a better way can come later.

**Comment by garlick** [comment]
Oops actually @trws perhaps you could squash the two commits and rebase on current master first?

**Comment by trws** [comment]
No problem, should be all set now @garlick.

**Pull request merged**
