### PR TITLE
Broker cleanup 2

### PR DESCRIPTION
**Pull request by morrone**
Additional broker clean up along the path to supporting multiple bootstrap methods.

### CODE REVIEW

**Comment by garlick** [comment]
@morrone could you please open the issue I requested on monday describing the feature you're working on and (briefly) outline how you plan to get there?

**Comment by morrone** [comment]
@garlick, sure, as soon as I have a plan. :)  I'm just unwinding intertwined bits so I can see the forest for the trees.  I'll open a place holder issue if that makes you feel better.

**Comment by morrone** [comment]
Issue #1236 is now open.

**Comment by morrone** [comment]
Rebased.

You know, I really think we should revisit this requirement that all landings have to be rebased.  Especially since travis is so incredibly unreliable these days, it would make sense to allow obviously non-conflicting PRs to merge without a rebase.

**Comment by garlick** [comment]
OK this all looks fine and I'll merge once travis turns green again.

**Pull request merged**
