### PR TITLE
replace resource-hwloc module with enhanced flux-hwloc command

### PR DESCRIPTION
**Pull request by grondo**
The work here is not quite done, but I wanted to post a functional PR early since I'm sure there will be many comments...

This PR is an alternative approach to #1931. The resource-hwloc module itself is removed in favor of an enhanced `flux-hwloc` command. To make this possible, the following changes were made to `flux-hwloc`:

 * hwloc xml is fetched directly the kvs. This obviates the need for the `resource-hwloc.topo` service.
 * hwloc xml is loaded directly into the kvs by `flux hwloc reload`:
   - in the case a *directory* argument is supplied to `reload`, the `flux-hwloc reload` command just puts the XML strings directly under a single transaction.
   - in the case of system topology reload, a new plumbing command `flux-hwloc aggregate-load` is executed across the session to load local topology and insert it into the kvs (under a `kvs_fence`)
 * As in #1931, an aggregation is done by `flux-hwloc aggregate-load`, executed by `flux-hwloc reload` across the session.
 * Due to this work, `flux hwloc topology` and `flux hwloc info` now have `--local` and `--rank` options to allow operating on the local topology or a subset of ranks (default is `--rank-"all"`)
 * The `flux hwloc reload` command should work the same as before.
 * the `resource.hwloc.xml` directories are now populated in `rc1` by simple `flux hwloc reload`

This approach removes the possible deadlocks introduced in #1931 since modules can be loaded/unloaded from any rank at any time. Doing the hwloc reload from a command interface was just much easier to reason about.

In this PR the `aggregate_*` functions were split off into a new convenience library under `src/common/libaggregate`. This just kept the complexity of `src/cmd/builtin/hwloc.c` down.

Still TODO:
 * test updates
 * doc updates

### CODE REVIEW

**Comment by grondo** [comment]
It occurred to me that `flux-hwloc reload` should just `exec(2)` `flux-exec` in order to execute `flux hwloc aggregate-load` across the session instead of attempting to re-implement most of `flux-exec` internally.

**Comment by grondo** [comment]
Ok, I've added a few tests (and add `jq(1)` to our `testenv` docker images).

I just have to update documentation and run some scale tests and then this PR is probably ready for another look.

**Comment by grondo** [comment]
In scale testing this PR fails for any instance >1024 brokers due to #1974. Once that fix is in I can resume some testing.

**Comment by grondo** [comment]
Rebased and pushed. Also added `flux hwloc reload -v` to get some debug out of the reload process (handy while seeing how the new method scales)

I was able to do some testing at about 2K brokers on opal (across 32 real nodes), and sadly a `flux hwloc reload` in that environment now takes ~20s on average. This seems to be due to a combination of `flux-exec` overhead plus a larger than expected time in `kvs_fence`. However, perhaps for now it is ok. There is lots of room for future optimization (e.g. at some point we could reduce the XML, or generate an **R** from global XML instead of storing N XMLs in the kvs).

You can see below the difference between reloading local XML from all ranks vs just one
```
$ time flux hwloc reload -v
flux-hwloc: 0.013s: starting HWLOC reload on 2048 ranks (all)
flux-hwloc: 0.013s: executing aggregate-load across all ranks
flux-hwloc: Running flux exec -n -r all flux hwloc aggregate-load --rank=all --verbose --timeout=34.000 --unpack=resource.hwloc.by_rank --key=resource.hwloc.reload:0-46354
flux-hwloc aggregate-load: 0.006s: starting
flux-hwloc aggregate-load: 0.006s: pushing local xml
flux-hwloc aggregate-load: 3.445s: starting kvs fence
flux-hwloc aggregate-load: 7.096s: kvs fence complete
flux-hwloc aggregate-load: 7.096s: starting aggregate
flux-hwloc aggregate-load: 7.098s: aggregate push complete
flux-hwloc aggregate-load: 8.369s: aggregate_wait complete
flux-hwloc aggregate-load: 8.369s: done.

real	0m18.948s
user	0m13.035s
sys	0m0.432s

$ time flux hwloc reload -v -r 0
flux-hwloc: 0.004s: starting HWLOC reload on 1 ranks (0)
flux-hwloc: 0.004s: executing aggregate-load across all ranks
flux-hwloc: Running flux exec -n -r all flux hwloc aggregate-load --rank=0 --verbose --timeout=34.000 --unpack=resource.hwloc.by_rank --key=resource.hwloc.reload:0-47380
flux-hwloc aggregate-load: 0.173s: starting
flux-hwloc aggregate-load: 0.174s: pushing local xml
flux-hwloc aggregate-load: 0.322s: starting kvs fence
flux-hwloc aggregate-load: 0.561s: kvs fence complete
flux-hwloc aggregate-load: 0.561s: starting aggregate
flux-hwloc aggregate-load: 1.090s: aggregate push complete
flux-hwloc aggregate-load: 3.929s: aggregate_wait complete
flux-hwloc aggregate-load: 3.930s: done.

real	0m5.736s
user	0m1.863s
sys	0m0.372s
```

Also, I'm not sure if reloading XML from a directory  via a single transaction in `flux hwloc reload` was the best idea, but since the reload from a directory is for testing only, for now  perhaps we can leave it as is:

```
t$ flux hwloc reload -v ./t/hwloc-data/sierra2
flux-hwloc: 0.012s: starting HWLOC reload on 2048 ranks (all)
flux-hwloc: 0.012s: starting load of XML from /g/g0/grondo/git/flux-core.git/t/hwloc-data/sierra2
flux-hwloc: 25.150s: XML load complete
flux-hwloc: 25.150s: executing aggregate-load across all ranks
flux-hwloc: Running flux exec -n -r all flux hwloc aggregate-load --verbose --timeout=34.000 --unpack=resource.hwloc.by_rank --key=resource.hwloc.reload:0-49889
flux-hwloc aggregate-load: 0.189s: starting
flux-hwloc aggregate-load: 0.358s: starting aggregate
flux-hwloc aggregate-load: 0.777s: aggregate push complete
flux-hwloc aggregate-load: 3.914s: aggregate_wait complete
flux-hwloc aggregate-load: 3.914s: done.

$ flux kvs get resource.hwloc.by_rank
{"[0-2047]": {"NUMANode": 6, "Package": 2, "Core": 44, "PU": 176, "GPU": 4}}
```

**Comment by grondo** [comment]
For comparison, the timing for `flux hwloc reload` on the branch for #1931 (where the `resource-hwloc` handles the reload via an event) is about 5x faster:
```
$ flux getattr size
2048
$ time flux hwloc reload

real	0m5.739s
user	0m0.014s
sys	0m0.012s

$ time flux hwloc reload -r 0

real	0m1.387s
user	0m0.012s
sys	0m0.016s
```

**Comment by dongahn** [comment]
Cool!

**Comment by grondo** [comment]
> Cool!

Actually, not so cool. I might have not been clear in my benchmarks, but the preferred approach in *this* PR (replacing the resource-hwloc module with `flux hwloc` + `flux exec`) is 5x slower at global HWLOC reload than the approach in #1931 which keeps the resource-hwloc module.

**Comment by grondo** [comment]
I think the weird timing of `flux hwloc reload` at medium scale is probably due to the effect described in #1983.

**Comment by garlick** [comment]
Nice, thanks!

**Pull request merged**
