### PR TITLE
expose optparse API publicly

### PR DESCRIPTION
**Pull request by garlick**
This PR moves optparse from a static library internal to flux-core to a public shared library, installed as `${libdir}/libflux-optparse.so` and `${includedir}/flux/optparse.h`.

This allows flux subcommands built outside of the core source tree to use the same option handling code, which should promote a more uniform user interface across framework components.

### CODE REVIEW

**Comment by grondo** [comment]
Hm, does that mean we should do manpages for libflux-optparse? :fearful:

**Comment by garlick** [comment]
Maybe someday.  IMHO not in this PR.

**Comment by grondo** [comment]
Looks like mpich.org is back up so I restarted the Travis build for this PR

**Comment by garlick** [comment]
Thanks!

Still no progress on travis-ci/apt-package-whitelist#406 it seems.

**Comment by garlick** [comment]
Just rebased on current master and squashed the one incremental commit.

**Comment by grondo** [comment]
The coverage test got stuck between the two cron tests :-(. There was no information I could glean from the travis logs so I just restarted it.

Since everything else looked fine, is this ready to merge?

**Comment by garlick** [comment]
Yep

**Pull request merged**
