### PR TITLE
flux-mini: support special urgency values "default", "hold", "expedite"

### PR DESCRIPTION
**Pull request by chu11**
per #3490

### CODE REVIEW

**Review by garlick — APPROVED** [review]
LGTM!  I gave it a quick sanity check, although your tests are already doing that.

Probably should update flux-mini(1) though.  About urgency it currently says:
> **--urgency=N**
   Specify job urgency, which affects queue order. Numerically higher urgency
   jobs are considered by the scheduler first. Guests may submit jobs with
   urgency in the range of 0 to 16, while instance owners may submit jobs
   with urgency in the range of 0 to 31 (default 16).

Perhaps we could tack on something like:
> In addition to numerical values, the special names `hold` (0), `default` (16), and `expedite` (31)  are also accepted.

**Comment by chu11** [comment]
> Probably should update flux-mini(1) though. About urgency it currently says:

Doh!  manpage slipped my mind.

**Comment by chu11** [comment]
rebased & re-pushed with a manpage update.  already squashed since its so tiny.

```
--- a/doc/man1/flux-mini.rst
+++ b/doc/man1/flux-mini.rst
@@ -267,7 +267,9 @@ OTHER OPTIONS
    Specify job urgency, which affects queue order. Numerically higher urgency
    jobs are considered by the scheduler first. Guests may submit jobs with
    urgency in the range of 0 to 16, while instance owners may submit jobs
-   with urgency in the range of 0 to 31 (default 16).
+   with urgency in the range of 0 to 31 (default 16).  In addition to
+   numerical values, the special names ``hold`` (0), ``default`` (16),
+   and ``expedite`` (31) are also accepted.
```

**Review by grondo — APPROVED** [review]
LGTM! Thanks!

**Comment by chu11** [comment]
thanks, setting MWP

**Pull request merged**
