### PR TITLE
broker: add config file boot method

### PR DESCRIPTION
**Pull request by garlick**
I'm putting this PR up early to get any feedback since I'm about to go offline for the rest of the day.  It's not ready for merging yet (needs some hand testing on a cluster, as well as a sharness test).

This adds a new boot method for brokers where size, rank, session-id, and overlay endpoints are taken from a TOML config file rather than exchanged with PMI.  The idea is to allow a multi-node system instance to bootstrap via systemd.  Such a system instance still has many hurdles to overcome to be useful.   As of now, it will not function unless all nodes listed in the config file are up, and it has no ability to recover its state if something goes wrong, or even survive an orderly shutdown.

Other than pulling boot_pmi.c out of broker.c and creating another boot method example, I didn't tackle any of the refactoring proposed as necessary in #1236.  That problem to me seems co-mingled with the challenge of supporting multiple overlay topologies, since much of the current boot code is specific to TBON.  Anyway maybe having this second example method on hand will help.

This pulls in the TOML config file support from `flux-security`.  Since that still may undergo some change, I didn't try to introduce a general flux config file.  Instead, this is just a config file for the boot process, and it does not contain any shortcuts that would make configuring a cluster easier.  I would expect it to evolve:
```toml
session-id = "hype"

# if commented out, TBON is used for event distribution
# mcast-endpoint = "eth0;230.0.0.1:8500"

# TBON endpoints array is indexed by rank
tbon-endpoints = [
    "tcp://192.168.1.1:8500",  # rank 0
    "tcp://192.168.1.2:8500", # rank 1
    "tcp://192.168.1.3:8500", # rank 2
]
```

Each node is expected to have an identical config file, and finds its own endpoint address and that of its parent from the tbon-endpoints array.

The systemd unit file will need to be modified to run the broker something like this:
```
flux broker -Sboot.method=config -Sboot.config_file=/etc/flux/flux.conf
```
(I haven't tried that yet and maybe we will actually want systemd to start the broker with `flux start`)

Feedback welcome.

### CODE REVIEW

**Comment by morrone** [comment]
>  I didn't tackle any of the refactoring proposed as necessary in #1236. That problem to me seems co-mingled with the challenge of supporting multiple overlay topologies, since much of the current boot code is specific to TBON.

This does in fact complete #1236.  I am not at all clear on what you think was "proposed as necessary in #1236".  You seem to be assuming intentions that are nowhere present in the work statement.

I think it is necessary to point out too that you did not open a detailed ticket explaining your approach to solving the problem before creating this code and making a pull request.  But you did demand that of me.

I am not suggesting that you should be doing anything different in this work.  I am just pointing out that if you had allowed me to work the same way that you are working, then the work would already have been complete and you wouldn't have needed to spend your own time on this current coding effort.

**Comment by garlick** [comment]
Towards the top of #1236 you mentioned modularization that was independent of the bootstrap method.  I kept that to a minimum in this PR.

I tried to add enough of a high level description of the bootstrap method in #1236 before starting so you would have an idea of high level plan and scope and could comment.  A new issue wasn't necessary.

**Comment by grondo** [comment]
@garlick, I see what might be a problem in Travis here. The sharness --chain-lint tests are not compatible in Travis with sending processes into the background for some reason. You might try the following patch and see if this fixes the current failure?

```diff
diff --git a/t/t0013-config-file.t b/t/t0013-config-file.t
index cebca9f..764db08 100755
--- a/t/t0013-config-file.t
+++ b/t/t0013-config-file.t
@@ -80,7 +80,7 @@ test_expect_success 'start size=1 with private config file' '
 # size=2 boot from config file
 #
 
-test_expect_success 'start size=2 with private config files' '
+test_expect_success NO_CHAIN_LINT 'start size=2 with private config files' '
        flux broker -Sboot.method=config \
                -Sboot.config_file=${TCONFDIR}/priv2.1.conf &
        run_timeout 5 flux broker -Sboot.method=config \
```

**Comment by garlick** [comment]
Thanks!  Trying it on my test branch.

**Comment by garlick** [comment]
That was it!  Thanks.

**Comment by grondo** [comment]
There's a bit of libtomlc99 unicode support code that is not covered by testing (also notice this in flux-security). I wonder if we should just remove that code or at least make sure it works...?

I'm running through this PR on my desktop now.
Just curious, what is the difference between `overlay_bind()` and `overlay_connect()` (there is some duplicate code in these functions that could be moved into its own static helper function.)

Otherwise, so far seems to check out ok.

**Comment by garlick** [comment]
Rebased on current master and resynced the libtomlc99 stuff from flux-security, after flux-framework/flux-security#54 improved test coverage there.

On `overlay_bind()` vs `overlay_connect()`:   The former calls `zmq_bind()` on endpoints that will be operating in passive mode, and the latter calls `zmq_connect()` on endpoints that need to actively connect somewhere.

`overlay_bind()` also configures zmq security in the "server role", while `overlay_connect()` configures itt in the "client role".  The server role runs the ZAP actor that checks authentication.  (Every broker actually runs one of those and has sockets operating in both roles).

Finally, `overlay_bind()` translates wildcard ports in endpoint URI's into actual ports.  `boot_pmi.c` must call  `overlay_bind()` part way through so it can obtain concrete URI's to share via the PMI KVS.  `boot_config.c` doesn't need to do that becuse it uses a configured port number and has no mechanism to share a random one.

The overlay module does need some refactoring in general, and also to support multiple overlay topologies, but that's a topic for another PR I think.

**Comment by grondo** [comment]
Thanks. To be clear, regarding refactoring I was only talking about this block of code, duplicated between `overlay_bind()` and `overlay_connect()`, seems like the `sec_initialized` should be handled in a separate function:

```C
    if (!ov->sec_initialized) {
        if (flux_sec_comms_init (ov->sec) < 0) {
            log_msg ("flux_sec_comms_init: %s", flux_sec_errstr (ov->sec));
            goto done;
        }
        ov->sec_initialized = true;
    }
```

E.g. move this block to `overlay_sec_init (overlay_t *ov)` and reduce code in each function to

```C
    if (overlay_sec_init (ov) < 0)
        goto done;
```

I only noticed this because of the duplicated error handling code that is not covered by tests.

**Comment by garlick** [comment]
Ah, OK that makes sense!  I'll fix.

**Comment by grondo** [comment]
Thanks, looks good to me. After travis reports back is this ready for merging?

**Comment by garlick** [comment]
Yes.  At the doctor but will check back on Travis when I get done

**Comment by grondo** [comment]
Looks good!

**Comment by garlick** [comment]
OK to merge IMHO.

**Pull request merged**
