### PR TITLE
minor fixes for installed flux-core

### PR DESCRIPTION
**Pull request by garlick**
Fix a few problems encountered building a module against installed flux-core.

I've not completed my testing so possibly there is more to add here.

### CODE REVIEW

**Comment by grondo** [comment]
Hmm, looks like there may be an intermittent failure in tests (looks like at the very least a scripting error in the `kvs-watch-until` lua script, sorry!)
```
/usr/bin/lua: ...x-core/flux-core-0.1.0/t/scripts/kvs-watch-until.lua:54: pcall: ...x-core/flux-core-0.1.0/t/scripts/kvs-watch-until.lua:63: [string "callback"]:1: attempt to index local 'v' (a nil value)
stack traceback:
	[C]: in function 'kvswatcher'
	...x-core/flux-core-0.1.0/t/scripts/kvs-watch-until.lua:54: in main chunk
	[C]: ?
FATAL: Unexpected exit with code 1
FATAL: Unexpected exit with code 1
flux-start: 3 (pid 45217) exited with rc=1
flux-start: 0 (pid 45211) exited with rc=1
flux-start: 2 (pid 45214) exited with rc=1
flux-start: 1 (pid 45212) exited with rc=1
FAIL: t0010-generic-utils.t
```

I'm going to try rebuilding to see if it is reproducible.

**Comment by grondo** [comment]
Hm, travis-ci rebuild button doesn't seem to be working today :disappointed:

**Comment by garlick** [comment]
I think I'm done with this PR:
* Get rid of json.h includes (and json_object usage) in installed header files
* Drop json and lua from flux-core pkgconfig
* Add module API libs to flux-core pkgconfig
* Relocate mrpc.h and modctl.h to flux/core and include from flux/core.h (they weren't intended to be special)

**Comment by garlick** [comment]
OK, just removed outdated spec files.  Now IMHO this is ready to merge once travis passes.

**Comment by grondo** [comment]
OK, this is ready to go? Thanks! BTW

**Comment by garlick** [comment]
Yep.

**Pull request merged**
