### PR TITLE
Pre-commit extensions and multi-version setup

### PR DESCRIPTION
**Pull request by trws**
Following on to #4636 this will do the following:

* Enable flake8, fix associated issues
* Allow running pre-commit with any compatible version of python, due to version range constraints I think the limit is 3.6 to 3.9 due to dependency compatibility
* Add a vermin check to ensure that python 3.6 keeps working without actually having to *use* 3.6, and add a comment to ignore the one issue we had where the analysis fails
* Update versions of *everything* other than what @vsoch added, because some of our tools are old enough they can't run on newer versions of python and are much more likely to miss things or give us false positives.  I think these versions were chosen to support python 2, we need to fix them.  Also solving associated issues (though I've found very few).

### CODE REVIEW

**Comment by trws** [comment]
Next thing after this will be to add in the c/c++ linters and just have it run everywhere, trick there will be excluding all the external projects we don't want it to process.  Is there a central list of those somewhere?

**Comment by grondo** [comment]
> Next thing after this will be to add in the c/c++ linters and just have it run everywhere, trick there will be excluding all the external projects we don't want it to process. Is there a central list of those somewhere?

You can reference the code coverage ignore list I think:

https://github.com/flux-framework/flux-core/blob/7fec12d79f7dd7f38a82f0ab800a5fa1dd9a6bed/Makefile.am#L17-L32

**Review by grondo — APPROVED** [review]
This is working for me!

**Comment by trws** [comment]
Sweet! Then if this manages to pass, I can work the other tools in with the vscode PR I had started (it needs some of the stuff anyway, doing it there will cut the duplication down a good bit).  I'm good with MWP here if you are @grondo.

Also thanks for the coverage ignore list idea, I completely forgot about that but that's perfect.

**Pull request merged**
