### PR TITLE
license: make all installed libraries LGPLv2.1+

### PR DESCRIPTION
**Pull request by garlick**
As discussed in #1646, this changes the license boiler plate on all original flux source in `src/common` to LGPLv2.1+ (except tests).  It also converts the liblsd copyright headers with permission from the author as discussed in #1667.  Finally, it ensures there is boiler plate in all installed header files.

If this goes in after #1786 then I think the installed libraries will be LGPL clean.

### CODE REVIEW

**Comment by SteVwonder** [comment]
Thanks @garlick for putting this together!

As a sanity check, I wrote a [quick script](https://gist.github.com/SteVwonder/a66ea4a9760321d12e1d2997d265b5ba) to parse the files that changed in this PR to LGPL and look at the header they include to ensure they are LGPL as well.  After hand checking a few files in the script output, it appears that some headers included by the files in this PR aren't LGPL.  For example, `dirwalk.c` was changed to LGPL but it's header `dirwalk.h` stayed GPL.  I don't know if this matters since my license understanding is weak at best, but I figured I would bring it up just in case.

**Comment by garlick** [comment]
I didn't add license boilerplate to non-installed headers that didn't already have one, but I did miss that libutil/cleanup.h and libutil/dirwalk.h had GPL headers already.  Will fix.

Any others like that?

**Comment by garlick** [comment]
I went ahead and squashed that change and rebased on current master.

**Comment by SteVwonder** [comment]
> Any others like that?

I tweaked the script a bit to grep the included headers not affected by this PR for the existence of "GNU General Public License" and non-existence of "GNU Lesser".  The only header that pops up is `./src/common/libev/ev.h`, which is dual-licensed.  So I think we are all good, given your previous caveat:

> I didn't add license boilerplate to non-installed headers that didn't already have one

**Comment by garlick** [comment]
I was unaware of SPDX.  Interesting and useful!

https://spdx.org/about

Their stance on recommended notices (e.g. the FSF boilerplate) is to follow the "upstream" recommendation, e.g. FSF's.  So I'm not sure of the wisdom of dropping that.

https://spdx.org/ids-how

Interestingly, the linux kernel has adopted SPDX, and here's a long commit message from Greg K-H that's fairly interesting

torvalds/linux@b24413180f5600bcb3bb70fbed5cf186b60864bd

At minimum it seems like our sources (including the .h files I left unadorned) ought to include:
```c
/* SPDX-License-Identifier: LGPL-3.0-or-later */
```

**Comment by garlick** [comment]
Is it useful to get this PR merged or should I withdraw pending the v3 approval so we can just change it once?

I guess it depends on how long we think that's going to take.

(Or I could drop the Flux original code changes and just include the GPL->LGPL changes approved by @dun to his work that we pilfered?)

**Comment by trws** [comment]
I'd say lets just do it.  It's all more correct regardless of anything else.  If you'd prefer to trim it back to the fixes for base64 et. al. that's fine with me too, but it doesn't hurt to touch the comments twice.

**Comment by SteVwonder** [comment]
I also vote for merging this.  That way if the conversation with IPO grinds to a halt (or really any other delay comes up), we can at least have collaborators link against LGPL libflux in the meantime.

**Comment by dongahn** [comment]
I agree!

**Comment by garlick** [comment]
I'm fine with it if someone wants to push the button then.

**Comment by trws** [comment]
Thanks @garlick!

**Pull request merged**
