### PR TITLE
broker: rework shutdown handshake

### PR DESCRIPTION
**Pull request by garlick**
This PR changes the protocol for shutting down a flux instance.

First, rc3 is no longer included in the "shutdown grace" timeout.  This was necessary to allow an arbitrarily large content cache to be written out to disk during rc3 without encountering timeouts, which might corrupt the data needed to restart.  (Being able to restart an instance is part of our next system instance deliverable)

Second, instead of sending an event and waiting for a fixed timeout to elapse so that tearing down the TBON wouldn't prevent the event from being distributed to all brokers, now the following protocol is executed once rc3 completes:

1) send shutdown event
2) upon receipt of event, start timer (all ranks)
3) each broker waits for downstream peers (if any) to disconnect
4) once all downstream peers have disconnected, disconnect upstream peer (if any)
5) exit reactor and cleanup

So the TBON is torn down from the leaves to the root.  If the timeout expires (perhaps one rank has died), the upstream ranks simply exit.  But in most cases, the brokers will exit as quickly as possible without waiting around.

Some other noteworthy changes in this PR:
- failures in rc3 are now reflected as instance failures
- no attempt at a "normal" shutdown is made on receipt of a fatal signal (just exit)
- no attempt at resuming the shutdown protocol is made when it times out
- module threads are never canceled (as that can result in hangs, see f4e2bbd)

### CODE REVIEW

**Comment by garlick** [comment]
Hmm, looks like some hangs are occurring in travis.  Just pushed a change to make the "goodbye" message fire and forget, rather than wait for a response before calling the shutdown callback, however my confidence is low that this will help.  Since the shutdown protocol runs under a timeout, we should never hang unless we get stuck in a blocking call somewhere.

Maybe an alarm(2) timeout would be more effective than a reactor timeout for the grace period?  That would just be making the error handling more robust though (hang promoted to hard error).  The timeout shouldn't be expiring under "normal" circumstances.

**Comment by garlick** [comment]
I caught a hang on my laptop - looks like we're getting stuck in `zmq_ctx_term()`
```
(gdb) bt
#0  0x00007f5144b07bf9 in __GI___poll (fds=0x7fffeb8b86e0, nfds=1, timeout=-1)
    at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007f51456afbf7 in ?? () from /usr/lib/x86_64-linux-gnu/libzmq.so.5
#2  0x00007f514568d2ec in ?? () from /usr/lib/x86_64-linux-gnu/libzmq.so.5
#3  0x00007f514567b3da in ?? () from /usr/lib/x86_64-linux-gnu/libzmq.so.5
#4  0x00007f51456d2a0a in zmq_ctx_term ()
   from /usr/lib/x86_64-linux-gnu/libzmq.so.5
#5  0x00007f514593619c in zsys_shutdown ()
   from /usr/lib/x86_64-linux-gnu/libczmq.so.4
#6  0x00007f5144a36041 in __run_exit_handlers (status=0,
    listp=0x7f5144dde718 <__exit_funcs>,
    run_list_atexit=run_list_atexit@entry=true, run_dtors=run_dtors@entry=true)
    at exit.c:108
#7  0x00007f5144a3613a in __GI_exit (status=<optimized out>) at exit.c:139
#8  0x00007f5144a14b9e in __libc_start_main (main=0x55e76dacf910 <main>,
    argc=6, argv=0x7fffeb8b8a28, init=<optimized out>, fini=<optimized out>,
    rtld_fini=<optimized out>, stack_end=0x7fffeb8b8a18)
    at ../csu/libc-start.c:344
#9  0x000055e76dad132a in _start ()
```

**Comment by garlick** [comment]
Hrm, that approach seems to be fraught with peril, resulting in frequent hangs especially in travis.

I still don't have a complete understanding of why it the hangs, but I suspect that it's possible to get stuck in `zmq_ctx_term()` when a socket that has a "block on mute" semantic (like DEALER) has messages pending that can't be pushed upstream.  Maybe the goodbye messages can't be pushed out if zeromq is shutdown too quickly, or if the upstream peer hits the grace timeout before the goodbye can be accepted?

Just pushed a second try, using `zmq_socket_monitor()` instead of the "goodbye" messages to determine when a downstream peer has disconnected.  This is where connect/disconnect events on one socket can generate notifications on another "monitor socket".  Instead of synchronizing on goodbye, we synchronize on disconnect.

This doesn't eliminate the possibility of a dealer message being sent and holding everything up, but at least the shutdown protocol isn't generating more of them.

**Comment by garlick** [comment]
The second approach of synchronizing on disconnect instead of messages seems to be working at least in the limited testing I've been able to do (thus far only on single system).  The CI failure in sched is actually a hang resulting from moving rc3 out of the grace period timeout, not related to the new shutdown protocol.  I opened a PR to address that in sched.  That will need to be merged before this PR can pass CI.

**Comment by garlick** [comment]
I'll do some testing on fluke when I get in but I think this PR Is finally stable.  The source of the intermittent hangs in `zmq_ctx_term()` seems to have been the `pthread_cancel()` sometimes used to avoid getting the broker stuck in `pthread_join()`.  Since zmq sockets are not thread-safe, that can cause some problems if the thread is canceled while in a libzmq socket call.

This PR eliminates that workaround, and makes the `pthread_join()` hang less likely by
- eliminating the timeout on rc3 when modules are unloaded
- unloading `connector-local` before the broker reactor exits

This PR has grown large, so I'll see if some parts can be split out to separate ones.

**Comment by garlick** [comment]
A chunk of this PR was peeled off to PR #2761.

Testing on fluke seemed to go OK, so I'm removing the WIP prefix and I also updated the initial description.

This is probably ready for review.

**Comment by grondo** [comment]
For clarity, should #2761 go in first, or are the two PRs now independent?

**Comment by garlick** [comment]
Probably this one first, although they are for the most part independent.

This one first only because I think it has the more critical change, and the other one probably has worse test coverage which I might be able to improve if it's too low (neither have reported in since the split yet though).

**Comment by garlick** [comment]
Hmm, the ASAN builder seemed to get stuck and gave up at 50m.   There's not a lot to go on since it didn't complete, although one of the tests appear to fail with
```
      t3100-flux-in-flux.t:  PASS: N=3   PASS=3   FAIL=0 SKIP=0 XPASS=0 XFAIL=0
ERROR: t3100-flux-in-flux.t - missing test plan
ERROR: t3100-flux-in-flux.t - exited with status 143 (terminated by signal 15?)
```
(oh duh, I should have looked at the raw output before restarting...)

**Comment by grondo** [comment]
I say we go ahead and merge this as I'm having a better time fixing #2749 on this branch than current master. I'll set merge-when-passing.

**Comment by garlick** [comment]
Thanks!!

**Pull request merged**
