### PR TITLE
clean up PMI-1 wire protocol implementation

### PR DESCRIPTION
**Pull request by garlick**
The PMI-1 wire protocol implementation was pretty tied to the exact dialog captured from hydra/mpich a while back, and was fragile with respect to any deviation from that.  Further, it would go completely off the rails if it ever received a spawn request, as the protocol behaves quite differently for that one operation.

Now that the protocol has been documented in [RFC13](https://github.com/flux-framework/rfc/blob/master/spec_13.adoc), update the implementation to behave the way it ought.

I think the standalone pmi tests should get a serious makeover in this PR, so do not merge until those get added.

### CODE REVIEW

**Comment by grondo** [comment]
Could the `dgetline/dputline` be moved under `common/libpmi-client.c` and used directly from `libpmi-client.la by the couple users? It definitely seems good to separate them, but it would be cleaner to keep them in libpmi-client since all the dgetline/putline users have to link in libpmi-client anyway.

Another probably stupid idea: if you put libpmi-client and libpmi-server together under common/libpmi, then keyval class could also move out of libutil to common/libpmi.

Functionality-wise, it doesn't matter that much to me, but what I worry about it is making it difficult for future developers to find the *right* libutil functions to reuse if libutil is filled with a lot of these special case kinds of utility functions.

**Comment by garlick** [comment]
True, and I would hate for some future developer to think that dputline/dgetline is a good idea just because it's sitting there :-)

I do like the idea of combining all the PMI-1 stuff into one library that is LGPL and that might  be separable one day into a standalone project.  Maybe we could just make  `src/common/libpmi` by combining
```
src/lib/libpmi
src/common/libpmi-client
src/common/libpmi-server
src/common/libutil/keyval.[ch]
src/common/libutil/dgetline.[ch]
t/pmi/simple.c
```

**Comment by garlick** [comment]
Some cleanup in progress here.  libpmi-client and libpmi-server were combined into libpmi, and the keyval and dgetline stuff moved there as well.  keyval and simple wire proto test was moved from sharness area and enhanced.

I haven't done anything to the installed pmi library (yet)

**Comment by garlick** [comment]
With this last update all PMI code is located in src/common/libpmi, with tests.
This includes the externally installed libpmi.so, which is now a PMI wire proto client.

libpmi is completely standalone, depending on no other code, and is licensed LGPL.

I still need to add back tracing to the client code.

**Comment by garlick** [comment]
For some reason I get singleton brokers when I run under slurm on TOSS 2 (RHEL 6).  It seems that dlopen ("libpmi.so") is not finding slurm's PMI library in`/usr/lib64/libpmi.so`.  Hrm....

**Comment by grondo** [comment]
Do you perhaps have the `/opt` version of `flux-core` loaded in your environment, and `dlopen` is finding the older flux based `libpmi.so`? (just grasping at straws, but I tested on hype and things seem to be working for me)

**Comment by garlick** [comment]
Good thought but that doesn't seem to be the case.  I added some printf debugging and found that it's dlopening the libpmi.so in the source tree (and logic to protect PMI_Init() from infinite regress kicks in.  I guess this is because libpmi.so is built in the same directory as libflux-core.so, so probably the libtool wrappers have set LD_LIBRARY_PATH to include that directory.

Hmm, how is it working for you @grondo, or maybe did one of my forced updates on this branch leave you with an out of date copy?

**Comment by garlick** [comment]
I wish there was some way to tell dlopen() to close the current dso and go open the next one in the path.

**Comment by grondo** [comment]
I don't know why it is working for me. I did a `git reset --hard garlick/keyval2`, but perhaps I need to start from scratch?

```
 grondo@hype349:~/git/flux-core.git$ git branch --contains
* keyval2
 grondo@hype349:~/git/flux-core.git$ git describe
0.3.0-230-g3f781fc
 grondo@hype349:~/git/flux-core.git$ echo $LD_LIBRARY_PATH
/opt/python-2.7/lib
 grondo@hype349:~/git/flux-core.git$ srun -N2 src/cmd/flux start flux up 
ok:     [0-1]
slow:   
fail:   
unknown:
```

**Comment by grondo** [comment]
Ok, I checked out a fresh clone and now it is failing for me. Sorry for the confusion.

**Comment by grondo** [comment]
> I wish there was some way to tell dlopen() to close the current dso and go open the next one in the path.

Well you can pass an absolute filename to `dlopen()`, so as a last resort you could do the path walk yourself. Then you could try each and every `libpmi.so` found on the system.. ;-)

**Comment by garlick** [comment]
Would that be a heinous thing to do?   My conscience says _no!_ but it would be somewhat practical to search LD_LIBRARY_PATH and `ldconfig -p | grep libpmi.so` and open each libpmi.so until one works.

**Comment by grondo** [comment]
I don't know, it doesn't feel too much different from searching PATH for the right binary, so I don't have too much of a problem with it.

**Comment by garlick** [comment]
I've verified that we can launch flux under srun with these changes on both toss2 and toss3.  I'd like to propose we merge if it looks OK

 There is room for increasing test coverage and maybe scrutinizing the PMI_process_mapping encode/decode a bit more than is currently done in the tests.  However, I think I would like to defer that work to another PR after we've tackled other high priority work.

**Comment by garlick** [comment]
Oh wait, I"m noticing a kvs error here when running flux under wreck.  Don't merge for now.

**Comment by garlick** [comment]
Different (serious) issue #729 which I reproduced on master.  It seems that PMI debug output on stderr from flux launching flux causes kz/kvs problems.

Not related to this PR so I guess I'd still like to put this forward for merging.

**Comment by garlick** [comment]
Rebased, and probably ready now that the problem uncovered just as it was becoming ready before has been solved.

**Comment by grondo** [comment]
Ok, this seems good to me. I do wonder why coverage is reported as dropped by .5% though.
Probably not, but are we getting less PMI test coverage now?

**Comment by garlick** [comment]
The coverage drop surprised me too, as I thought it should have increased in this PR.

**Comment by grondo** [comment]
Could be a coveralls bug as I've seen that before. However, let me investigate in case we're not testing what we think we're testing (e.g. sometimes this means a test was accidentally skipped)

**Comment by grondo** [comment]
Ok, looks like the coverage decreased on this branch between build [1421](https://travis-ci.org/flux-framework/flux-core/jobs/141662339) (commit [2e0c01](https://github.com/flux-framework/flux-core/commit/2e0c0153ad34365715e2dfe4d0543fa87b67b7cd))
```
common/libpmi/client.c                    |84.4%     96|81.8%    22|    -      0
common/libpmi/client_dlopen.c             |81.3%    107|75.0%    20|    -      0
common/libpmi/dgetline.c                  |87.5%     16| 100%     2|    -      0
common/libpmi/keyval.c                    | 100%     48| 100%     6|    -      0
common/libpmi/pmi_strerror.c              | 0.0%      5| 0.0%     1|    -      0
common/libpmi/simple_client.c             |83.9%    155|77.3%    22|    -      0
common/libpmi/simple_server.c             |53.3%    150|42.9%    14|    -      0
lib/libpmi/pmi.c                          |59.7%    253|44.4%    36|    -      0
...
                                    Total:|75.3%  25830|81.8%  2347|    -      0
```

and build [1427](https://travis-ci.org/flux-framework/flux-core/jobs/142915927)

```
common/libpmi/clique.c                    |55.8%    120|50.0%     8|    -      0
common/libpmi/dgetline.c                  |87.5%     16| 100%     2|    -      0
common/libpmi/keyval.c                    | 100%     48| 100%     6|    -      0
common/libpmi/pmi.c                       |41.3%    269|42.4%    33|    -      0
common/libpmi/pmi_strerror.c              | 0.0%      5| 0.0%     1|    -      0
common/libpmi/simple_client.c             |84.0%    156|77.3%    22|    -      0
common/libpmi/simple_server.c             |47.1%    172|42.9%    14|    -      0
common/libpmi/single.c                    |83.8%     80|77.3%    22|    -      0
common/libpmi/wrap.c                      |17.1%     82| 8.3%    24|    -      0
...
                                    Total:|74.7%  25944|81.0%  2356|    -      0
```


It is difficult to tell if this is due to code added to libpmi, or even if the perceived coverage changes are related to pmi. Probably at this point it doesn't matter too much, as I'm pretty sure we didn't accidentally skip tests etc.

**Comment by garlick** [comment]
​Hmm, so it did coincide with the reorganization of client.c and
client_dlopen.c into pmi.c, wrap.c, and single.c.
I can't quite explain why coverage decreased as a result, but the change is
mostly structural.
In other words it didn't exactly introduce a lot of new code.

**Comment by grondo** [comment]
Ok, that seems reasonable. With the code reorg approx 245 new lines were added, but the amount of lines covered in testing didn't go up so the coverage of `*pmi*` related code dropped from 66.5% to 56.6%.

I think we understand now that we didn't accidentally drop old tests so this is good to go.

**Pull request merged**
