### PR TITLE
NEWS.md: prepare for 0.21.0 release

### PR DESCRIPTION
**Pull request by garlick**
Here's a start on 0.21.0 release notes which we'll try to get tagged on Wed AM.   Feel free to push directly to this PR if you have changes.

### CODE REVIEW

**Comment by chu11** [comment]
FYI: `* flux-job: Output key options for job info (#3210)` not in yet :P

**Comment by garlick** [comment]
> FYI: * flux-job: Output key options for job info (#3210) not in yet :P

I was being optimistic on that one.  Shall I give it a review?  I was holding off b/c I wasn't sure i was the most qualified, but right now I've got some extra cycles.

**Comment by chu11** [comment]
@garlick yeah, give it a stab.

**Comment by grondo** [comment]
Rebased and pushed an update adding an entry for #3301.

**Review by grondo — APPROVED** [review]
Looks good!

**Comment by grondo** [comment]
I've set MWP and will tag 0.21 after this goes in.

**Pull request merged**
