### PR TITLE
add a PMI client library

### PR DESCRIPTION
**Pull request by garlick**
This PR implements the client end of the simple v1 wire protocol discussed in #398, as determined by spelunking mpich code and watching how mpiexec.hydra behaves.   The protocol engine I wrote may be overly locked into Hydra's formatting of protocol responses, but that could be addressed later if it matters.

A new internal library, `libpmi-client` was created to abstract the two ways we can now access PMI when Flux is being launched (wire protocol and dlopen `libpmi.so`).  Then I reworked the broker to use this library.  Now as a result, Hydra can launch Flux.

I added a new PMI client test program and reworked the old tpmikvs test to use the above library, and relocated these C programs to `t/pmi`.  A sharness driver was added to test assumptions about Hydra's operation and wire protocol interpretation, and show that it can launch Flux (if mpiexec.hydra is in the path).  Travis now pulls in mpich instead of openmpi so this test should run in travis.

 I also updated the license on our PMI server implementation to designate it as LGPL, and pulled in the MPICH pmi.h, pmi2.h header files.  By spelunking MPICH code, a `pmi_deprecated.h` header was also added for older PMI functions, some of which we already implement.

As discussed in #340, I started to add a sharness test that Flux can run MPI programs, but didn't get too far.  I moved our `mpi_hello.c` test to `t/mpi` and stubbed out a sharness driver for launching it. Unfortunately I then got a bit stuck trying to configure MPICH to dlopen a libpmi.so.  It appears to only do that when configured `--with-pm=slurm`, and then insists on a slurm-specific path at configure time.  Ideally we would configure it so it can use either the v1 wire protocol or dlopen a library and then demonstrate that Flux can launch it both ways (that is, once it implements the server side of the wire protocol).  Anyway, I felt that moving the test and stubbing out the driver was not a bad move by itself, so I went ahead and left it in,.

### CODE REVIEW

**Comment by garlick** [comment]
This needs to be tested to make sure Slurm can still launch Flux across multiple nodes, and that it can also do so with `--enable-epgm`, (where the reworked broker pmi code is a bit complicated setting up event relays).  So not yet ready for merge.

**Comment by grondo** [comment]
Sorry about the failed checks being reported. The coveralls "check" failed because coverage dropped more than 1%, but at this point that is probably ok. Other travis tests succeeded. (Though, boy that mpich builds takes a little while -- should be cached now for this PR at least...)

**Comment by grondo** [comment]
On ipa I'm getting the following error from `t3000-mpi-basic.t`: (I'm not sure from your comments above if this is expected at this point)
```
 grondo@ipa15:~/git/f/t$ ./t3000-mpi-basic.t  -d -v
Attempting to load /g/g0/grondo/git/f/t/sharness.d/flux-sharness.sh
[1444083019.875147] broker.info[0]: nodeset: [0-32] (complete)
[1444083019.875206] broker.info[0]: starting initial program
Attempting to load /g/g0/grondo/git/f/t/sharness.d/flux-sharness.sh
# ./t3000-mpi-basic.t: flux session size will be 33
expecting success: 
	run_program 5 1 1 ${FLUX_BUILD_DIR}/t/mpi/hello

[1444083020.010915] job.info[0]: got request job.create
[1444083020.011719] job.info[0]: Setting job 1 to reserved
[1444083020.067939] lwj.1.info[0]: lwj 1: node0: nprocs=1, nnodes=1, cmdline=[ "\/g\/g0\/grondo\/git\/f\/t\/mpi\/hello" ]
0: PMGR_COLLECTIVE ERROR: rank 0 on ipa15: Missing required environment variable: MPIRUN_ID @ pmgr_collective_common.c:115
[1444083020.089611] lwj.1.info[0]: job complete. exiting...
wreckrun: task 0: exited with exit code 1
[1444083020.092647] job.info[0]: got request job.disconnect
not ok 1 - mpi hello world runs as a singleton
#	
#		run_program 5 1 1 ${FLUX_BUILD_DIR}/t/mpi/hello
#	

# failed 1 among 1 test(s)
1..1
```

**Comment by grondo** [comment]
Also, running `flux-broker` under srun I'm getting:
```
 grondo@ipa15:~/git/f$ srun --pty -N4 -p pall src/cmd/flux broker
srun: error: slurm_receive_msg: Zero Bytes were transmitted or received
                                                                       srun: error: slurm_receive_msg[192.168.80.1]: Zero Bytes were transmitted or received
                                                                            /g/g0/grondo/git/f/src/broker/.libs/lt-flux-broker: symbol lookup error: /usr/lib64/slurm/auth_munge.so: undefined symbol: slurm_auth_get_arg_desc
```
[sic]

I'm not at all sure what that is about. (Sorry if you were already looking at this stuff)

**Comment by garlick** [comment]
OK, it sounds like my assumption that a singleton mpi program works without support from the PM in all cases is not correct.  (It is true with openmpi and modern mpich).  Maybe I need to back out that sharness mpi test until we figure out how to write tests that work with whatever mpi is available.  It's not really testing anything in Flux as it is now.

On the error launching Flux from Slurm,  another change I made was fixing the dlopen flags on libpmi.so to be RTLD_LOCAL instead of RTLD_GLOBAL.  Apparently this exposes a problem with the way SLURM links libpmi.so.  See [this openmpi discussion](http://www.open-mpi.org/community/lists/devel/att-16394/attachment).  I guess I should flip it back.

Thanks for doing that testing.

**Comment by garlick** [comment]
Just rebased on current master and pushed a couple changes:
* don't run MPI tests unless `TEST_MPI=t` is set in the environment.
* dlopen libpmi.so using RTLD_GLOBAL so its internal dlopen() can work
* add couple broker attributes for visibility into event wire-up
* fix a broker option parsing bug

I've retested slurm-launching-flux on ipa (including with EPGM) and no problems found.

This might be close to mergeable?

**Comment by grondo** [comment]
I tested this out as well and it all seems to be working great!

Strangely, `MPI_Init` times were much slower on ipa, but I double checked against older code and vs `hype` (which seems to be fine) so I think that is just environmental.

Otherwise this looks great.

One comment is we have a lot of tests that set the `LONGTEST` prereq, we might want to promote that into `sharness.d/flux-sharness.sh` in the future (I want to check what git and sharness do upstream first though). Also, `t3000-mpi-basic.t` sets the LONGTEST prereq but doesn't use it.

Also, in `t3000-mpi-basic.t` all tests depend on `MPI` prereq, so we might want to skip all before `test_under_flux` is run so we don't spawn a flux session then skip all tests.

The idiom for doing this in sharness is something like (from sharness.sh source):
```
#   # Skip all remaining tests if prerequisite is not set.
#   if ! test_have_prereq PERL; then
#       skip_all='skipping perl interface tests, perl not available'
#       test_done
#   fi

```
I actually haven't tried `skip_all` yet so hopefully it works as advertised.

**Comment by grondo** [comment]
Upstream sharness automatically sets `EXPENSIVE` prereq if `---long` is passed to tests or `TEST_LONG` is set in environment. I say we leave the `LONGTEST` stuff alone for now and I'll rework it when we sync sharness.sh with upstream.

**Comment by grondo** [comment]
Ok to press the button @garlick?

**Comment by garlick** [comment]
Hang on, I was going to clean up those sharness tests as suggested...

**Comment by garlick** [comment]
OK, I dropped LONGTEST from a couple tests that set it but didn't use it.

I used skip_all instead of a prereq in both the hydra and mpi tests, and squashed down the incremental changes to those tests.

Thanks for pointing that out - this is better.

**Comment by grondo** [comment]
Excellent, thanks! Ready to go?

**Comment by garlick** [comment]
Yep.

**Pull request merged**
