### PR TITLE
wreck: enable optional cpu affinity for jobs based on cores assigned in R_lite

### PR DESCRIPTION
**Pull request by grondo**
This PR, along with some related cleanup, enables `wrexecd` to optionally set its cpu affinity mask to the cores assigned in `R_lite`. The cpu affinity support is not enabled by default, but will only be active if the `cpu-affinity` option is enabled for the job (or globally)., e.g.

```
flux wreckrun -n4 -o cpu-affinity ...
```

The "related cleanup" here was to allow global wreck "job options" to be set in the KVS at the `lwj.options` level, and to make the `options` kvs entry a single JSON object instead of a directory (to avoid several back-to-back kvs queries when there are multiple job options set).

In order to allow per-job options to override globally *set* options, these options are now disabled if they are set to `0` or `false` or `no`, e.g.

```
flux wreckrun -n4 -o cpu-affinity=no ...
```

For cpu affinity, this means you can enable cpu affinity for all jobs by
```
$ flux kvs put --json lwj.options='{"cpu-affinity":1}'
```

And disable for a single job with `-o cpu-affinity=no`

Fortunately @trws was very thorough and the `resource-hwloc` module already supports restricting the topology to the current cpumask, so sub-instances will inherit these settings in their hwloc configuration:
```console
$ src/cmd/flux start -s 4
flux-start: warning: setting --bootstrap=selfpmi due to --size option
$ flux hwloc info
4 Machines, 64 Cores, 128 PUs
$ flux wreckrun -n4 flux start flux hwloc info
4 Machines, 64 Cores, 128 PUs
$ flux wreckrun -n4 -o cpu-affinity flux start flux hwloc info
4 Machines, 4 Cores, 4 PUs
```

One thing I now notice is that the straight use of `sched_setaffinity` here is literally restricting jobs to the cores in the cores list from `R_lite`, but should we also be including thread siblings by default?
Before merging let me check if hwloc has an easy way to create a cpumask that includes thread siblings, unless someone notifies me that we don't want to include siblings by default in the cpu affinity mask.

### CODE REVIEW

**Comment by grondo** [comment]
Ok, @trws came and set me straight. I'll switch cpu affinity to use the hwloc interface which should automatically pick up the physical cores including any PUs (hyperthread sibling).

**Comment by garlick** [comment]
This looks good to me and I'm happy to merge if you think it's ready.

**Comment by grondo** [comment]
> This looks good to me and I'm happy to merge if you think it's ready.

Thanks, but use of `sched_setaffinity` is too simplistic for the use case. I'll have to rework to use some libhwloc magic that will translate a physical cores list to a cpumask that includes the cores and any threads shared with the same physical core.

**Comment by dongahn** [comment]
> Fortunately @trws was very thorough and the resource-hwloc module already supports restricting the topology to the current cpumask, so sub-instances will inherit these settings in their hwloc configuration:

BTW, this is very nice!

**Comment by grondo** [comment]
Ok, I pushed a fix for test failures when cpu `thread_siblibgs_list` used a different format then the output of the `cpus-allowed` script (e.g. `0-1` vs `0,1`), and also squashed incremental commits.

If this passes Travis I think it is read to merge.

**Comment by trws** [comment]
Unfortunately at the C level that's about what it amounts to.  Using the distribute call might shorten it slightly, but not a great deal since r lite doesn't actually have a cpuset equivalent but a core list.

**Comment by grondo** [comment]
This is rebased, but I added `flux wreck getopt/setopt` commands to more easily manipulate the global `lwj.options` JSON object. The cpu-affinity tests were updated to use `flux wreck setopt`.

**Comment by grondo** [comment]
We'll, Travis is useless today. Will try restarting builders later tonight (getting apt-get errors)

**Comment by garlick** [comment]
Thanks!

**Pull request merged**
