### PR TITLE
bindings/python: tests now emit valid TAP

### LINKED ISSUE #278: tap-driver.sh gets confused by TAP output of python tests
Getting `AFTER_LATE_PLAN` errors from the python tests when run in a recent autoconf environment that makes use of `tap-driver.sh`:
```
PASS: test_commands/test_runner.t 1 test.wrapper.TestWrapper.test_automatic_unwrapping
PASS: test_commands/test_runner.t 2 test.wrapper.TestWrapper.test_call_insufficient_arguments
PASS: test_commands/test_runner.t 3 test.wrapper.TestWrapper.test_call_invalid_argument_type
PASS: test_commands/test_runner.t 4 test.wrapper.TestWrapper.test_call_non_existant
PASS: test_commands/test_runner.t 5 test.wrapper.TestWrapper.test_masked_function
PASS: test_commands/test_runner.t 6 test.wrapper.TestWrapper.test_read_basic_value
PASS: test_commands/test_runner.t 7 test.wrapper.TestWrapper.test_set_pimpl_handle
ERROR: test_commands/test_runner.t 1 test.json_t.TestJsonCInterface.test_create_empty # AFTER LATE PLAN
ERROR: test_commands/test_runner.t 2 test.json_t.TestJsonCInterface.test_with_data # AFTER LATE PLAN
ERROR: test_commands/test_runner.t - multiple test plans
ERROR: test_commands/test_runner.t 1 test.kvs.TestKVS.test_bad_init # AFTER LATE PLAN
```

Apparently `tap-driver.sh` isn't written to understand more than one set of TAP output per invocation. (i.e. it expects to be the driver of each individual test, not running a driver that runs other tests).

We could probably either try to fix the `tap-driver.sh` script to reset itself each time it gets a new TAP header, or we could just remove `tap-driver.sh` as the `LOG_DRIVER` for the python tests.

### PR DESCRIPTION
**Pull request by trws**
The test_runner now runs all python unit tests and doctests to emit results
into a single pycotap `TAPTestResult` instance, aggregating all the results
into a single valid TAP output stream.  This appears to make prove
significantly happier.

fixes #278

### CODE REVIEW

**Comment by grondo** [comment]
@trws :+1:

I'll just verify things look ok in the ubuntu 14.04 vm (which actually uses `tap-driver.sh`). Then will merge it. Nice quick turnaround! Felt kind of bad that our choice of TAP caused you extra work here...

**Comment by trws** [comment]
No worries.  Having everything standardized is a good thing, and with pycotap to wrap around `unittest` it was pretty straightforward.  The big trick is just getting a flux instance to use and running everything as `./<test>` at the same time. There are tools that could do this almost entirely automatically, with standard python, and tap output.  They just weren't options as things were initially.  Now that I'm thinking about it though, the new flux attach and sideflux capabilities might make these usable now... Hmm... I might actually be able to get rid of `test_runner` entirely except for the doctests.

**Comment by grondo** [comment]
BTW in this PR you could also add a
```
git revert 1d5e896b8f8866a941a91855cfe2ff8ec581e995
```
Since we could conceivably run under `tap-driver.sh` now (and get individual test output and a summary)

**Comment by grondo** [comment]
Oh, I did check under ubuntu 14.04 and works great with following output in case you are interested
```
PASS: test_commands/test_runner.t 1 test.wrapper.TestWrapper.test_automatic_unwrapping
PASS: test_commands/test_runner.t 2 test.wrapper.TestWrapper.test_call_insufficient_arguments
PASS: test_commands/test_runner.t 3 test.wrapper.TestWrapper.test_call_invalid_argument_type
PASS: test_commands/test_runner.t 4 test.wrapper.TestWrapper.test_call_non_existant
PASS: test_commands/test_runner.t 5 test.wrapper.TestWrapper.test_masked_function
PASS: test_commands/test_runner.t 6 test.wrapper.TestWrapper.test_read_basic_value
PASS: test_commands/test_runner.t 7 test.wrapper.TestWrapper.test_set_pimpl_handle
PASS: test_commands/test_runner.t 8 test.json_t.TestJsonCInterface.test_create_empty
PASS: test_commands/test_runner.t 9 test.json_t.TestJsonCInterface.test_with_data
PASS: test_commands/test_runner.t 10 test.kvs.TestKVS.test_bad_init
PASS: test_commands/test_runner.t 11 test.kvs.TestKVS.test_exists_dir
PASS: test_commands/test_runner.t 12 test.kvs.TestKVS.test_exists_false
PASS: test_commands/test_runner.t 13 test.kvs.TestKVS.test_exists_true
PASS: test_commands/test_runner.t 14 test.kvs.TestKVS.test_fill
PASS: test_commands/test_runner.t 15 test.kvs.TestKVS.test_iterator
PASS: test_commands/test_runner.t 16 test.kvs.TestKVS.test_key_at
PASS: test_commands/test_runner.t 17 test.kvs.TestKVS.test_kvs_dir_open
PASS: test_commands/test_runner.t 18 test.kvs.TestKVS.test_read_non_existent
PASS: test_commands/test_runner.t 19 test.kvs.TestKVS.test_read_non_existent_basedir
PASS: test_commands/test_runner.t 20 test.kvs.TestKVS.test_remove
PASS: test_commands/test_runner.t 21 test.kvs.TestKVS.test_set_deep
PASS: test_commands/test_runner.t 22 test.kvs.TestKVS.test_set_dict
PASS: test_commands/test_runner.t 23 test.kvs.TestKVS.test_set_float
PASS: test_commands/test_runner.t 24 test.kvs.TestKVS.test_set_int
PASS: test_commands/test_runner.t 25 test.kvs.TestKVS.test_set_list
PASS: test_commands/test_runner.t 26 test.kvs.TestKVS.test_set_none
PASS: test_commands/test_runner.t 27 test.kvs.TestKVS.test_set_string
PASS: test_commands/test_runner.t 28 test.kvs.TestKVS.test_walk
PASS: test_commands/test_runner.t 29 test.kvs.TestKVS.test_walk_with_no_handle
PASS: test_commands/test_runner.t 30 test.handle.TestHandle.test_create_handle
PASS: test_commands/test_runner.t 31 test.handle.TestHandle.test_log
PASS: test_commands/test_runner.t 32 test.handle.TestHandle.test_rpc_ping
PASS: test_commands/test_runner.t 33 test.request.TestRequestMethods.test_no_topic_invalid
PASS: test_commands/test_runner.t 34 test.request.TestRequestMethods.test_null_payload
PASS: test_commands/test_runner.t 35 test.event.TestEvent.test_full_event
PASS: test_commands/test_runner.t 36 test.event.TestEvent.test_t1_0_sub
PASS: test_commands/test_runner.t 37 test.event.TestEvent.test_t1_1_unsub
PASS: test_commands/test_runner.t 38 test.watchers.TestTimer.test_s1_0_timer_add
PASS: test_commands/test_runner.t 39 test.watchers.TestTimer.test_s1_1_timer_remove
PASS: test_commands/test_runner.t 40 test.watchers.TestTimer.test_timer_add_negative
PASS: test_commands/test_runner.t 41 test.watchers.TestTimer.test_timer_with_reactor
PASS: test_commands/test_runner.t 42 test.barrier.TestBarrier.test_eight
PASS: test_commands/test_runner.t 43 test.barrier.TestBarrier.test_single
```

**Comment by garlick** [comment]
@grondo and @trws that revert is still in PR #277 which isn't merged yet, so I'll just drop it there and rebase.

Actually I was holding off rebasing as I wasn't sure if you guys still were working with it  If you're OK with me doing a force push please ACK.

**Comment by grondo** [comment]
@garlick, yeah, just realized that sorry... (and thanks)

You can force push a rebase there as far as I'm concerned.

**Pull request merged**
