### PR TITLE
add flux queue command, drop flux job undrain

### PR DESCRIPTION
**Pull request by garlick**
This PR first changes `flux job drain` so that it doesn't disable job submissions, and removes `flux job undrain`.  It doesn't seem like disabling job submission should be coupled with waiting for there to be no more active jobs, as none of our use cases in testing require it, and it doesn't seem like a workflow use case would require it.

Then this PR adds a new `flux queue` command to replace the queue control aspect of drain/undrain:

```console
$ flux queue
Usage: flux-queue [OPTIONS] COMMAND ARGS
  -h, --help             Display this message.

Common commands from flux-queue:
   enable          Enable job submission
   disable         Disable job submission
   status          Get queue status
$ flux queue status
flux-queue: Job submission is enabled
$ flux queue disable System is fubar
flux-queue: Job submission is disabled, reason: System is fubar
$ flux mini run hostname
flux-mini: ERROR: [Errno 22] job submission is disabled: System is fubar
$ flux queue enable
flux-queue: Job submission is enabled
```

Edit: updated to reflect where we finally landed after some discussion below.

### CODE REVIEW

**Comment by grondo** [comment]
Now that I see this, I'm wondering how many potential future subcommands would fall under `flux-admin` -- potentially cutting across multiple flux services. This might make the command unwieldy, exacerbated by the fact that in every non-system instance the user *is* the admin, so some of these commands might enter common usage.

Maybe it would be ok to split "admin" tools into multiple commands, instead of fitting them all under flux-admin? Perhaps high level commands still make sense under a `flux-admin` moniker, but for manipulating the "queue" maybe `flux queue start/stop/status` is slightly more user-friendly, and additionally collects related code naturally under one `.c` file.

Now that I say this, I even feel like `flux shutdown` might be acceptable instead of `flux admin shutdown` :man_shrugging: 

I realize this goes against what I said before, I'm more musing aloud.. sorry!

**Comment by garlick** [comment]
Great point.  Maybe this PR ought to add a `flux queue` command for the enable/disable functionality, and just expand `flux job raise` and `flux job cancel` with multi-job capability?  Or add `flux job cancelall` and `flux job raiseall` since these use different RPCs and have different output?

**Comment by grondo** [comment]
> Maybe this PR ought to add a flux queue command for the enable/disable functionality, and just expand flux job raise and flux job cancel with multi-job capability? Or add flux job cancelall and flux job raiseall since these use different RPCs and have different output?

I kind of like the idea of `cancelall` `raiseall` -- like the `killall(1)` command.

Might be a good starting point, though I hate to speak in absolutes since I'm not too sure if I have any of the answers ;-)

**Comment by garlick** [comment]
OK, I'll look at going that way tomorrow.  Easy to change later when we have more insight also or maybe  even (judiciously) provide more than one interface to the same thing, packaged for different kinds of users - thinking mainly of our sys admins who probably don't want to have to dig through a lot of different commands to find what they need.   Maybe that's a co-design item, after we get stuff working.

Thanks for the feedback!

**Comment by garlick** [comment]
Rebased on #2670, and moved
- `flux admin cancel` to `flux job cancelall`
- `flux admin raise` to `flux job raiseall`

The commands changed a bit to make more sense for non-admin use.  For example, the default user target is the user running the command, not everyone.  And the services now are open to guests, not just instance owner (with appropriate limits).

Maybe I should rename `flux admin submit` to something that doesn't sound like an alternate job submission interface?  `flux admin queue` was suggested earlier, how would that be?

I'm open to reworking this until we get the right interfaces.  I don't have a great insight on how these should be presented myself.

**Comment by grondo** [comment]
> Maybe I should rename flux admin submit to something that doesn't sound like an alternate job submission interface? flux admin queue was suggested earlier, how would that be?

I was actually suggesting `flux queue` for controlling the job-manager queue, like `flux queue stop` `flux queue start` or `enable` `disable`, then reserve `admin` for things like `shutdown` that are more general instance administration utilities. Though I'm not opposed to `flux shutdown` either.

My only argument here, besides keeping command names shorter, would be to keep similar code together in the source, instead of grouping a ton of stuff under one C or Python file. This point could be ameliorated with some utility code that allowed sub-subcommands to be broken up.

(As an example, I assume `flux module` will not be renamed to `flux admin module`. I would argue the tools to manipulate the queue also should fall under their own hierarchy, even if there are only a couple commands at first)

:man_shrugging:

**Comment by garlick** [comment]
OK, I changed
- `flux admin submit enable` -> `flux queue enable`
- `flux admin submit disable reason ...` -> `flux queue disable reason ...`
- `flux admin submit` -> `flux queue status`

This seems like it's heading in a good direction to me.

**Comment by garlick** [comment]
Thinking about release notes, it may be a good idea for this PR to focus on the change to "drain" and addition of `flux queue`.  I'll go ahead and split the `flux job killall/raiseall/cancelall` commands off to another PR.

**Comment by garlick** [comment]
OK, dropped `flux job <cmd>all` and updated the PR description and title.

Also rebased on current master and dropped #2670 from this PR as it no longer needs to go in first.

I'll tentatively drop the WIP prefix.

**Comment by garlick** [comment]
Last coveralls run must've run against one of my errant intermediate force pushes, as the report calls out uncovered code paths that are no longer in this PR.  Hopefully it'll rerun.

**Comment by grondo** [comment]
LGTM, feel free to set `merge-when-passing` when you're ready.

**Comment by garlick** [comment]
Thanks!

**Comment by garlick** [comment]
Er, mergify says
> No oauth valid tokens
err-code: E17F5

**Comment by grondo** [comment]
That's a new one!

**Comment by grondo** [comment]
I tried `Re-run checks` and got the same error. Maybe temporary problem with GitHub/Mergify OAuth?

I'll try this:

@Mergifyio rebase

Then press the button manually.

**Comment by grondo** [comment]
I guess it makes sense that didn't work if mergify can't authenticate with GitHub...

**Comment by grondo** [comment]
The oauth issue might go away on its own, but I sent an email asking for help to mergify.io anyway.

**Comment by garlick** [comment]
Thanks!

**Pull request merged**
