### PR TITLE
add systemd unit file, add mini auth protocol to local connector

### PR DESCRIPTION
**Pull request by garlick**
This work was peeled off of #980.  It adds a prototype systemd unit file and build logic for configuring its install location, which gets us part way to #967.  With this it's possible to
```
$ sudo useradd -u 9999 flux
$ ./configure  --with-systemdsystemunitdir=/etc/systemd/system --localstatedir=/var
$ make
$ sudo make install DESTDIR=/
$ sudo systemctl start flux
```
Then flux commands like `sudo -u flux flux dmesg` work (as instance owner) but trying that as another user gets you something like
```
$ flux dmesg
flux: flux_open: Operation not permitted
```

There's a small tweak to the local connector here to return a single byte response on the wire indicating success or failure of authentication so the client, which probably sends a request first thing, gets a sensible error instead of EPIPE for the unceremonious broker side close.

Finally, ensure that the local connector socket is mode 777 so anyone can _attempt_ to connect.

### CODE REVIEW

**Comment by grondo** [comment]
It isn't clear from the new autoconf macro if systemd is enabled by default and the (verbose) `--with-systemdsystemunitdir` is only needed to override the unitdir path found in `pkg-config`, or if one could use `--wihtout-systemdsystemunitdir` to disable systemd unit file installation. It would seem preferable to have a simple `--with-systemd` and `--without-systemd`, but maybe that isn't useful in practice?

BTW, not that I'm suggest we switch to it, but a quick search turned up [this](https://bitbucket.org/mgorny/systemd-m4/src/ba79ccb50b5351d97d69cccefa27fda985fb0d25/m4/systemd.m4?at=master&fileviewer=file-view-default) alternate implementation of a `systemd.m4`, which to me looks a bit more complete.

Sorry if you already researched this topic and arrived at the current macro as the best choice.

**Comment by garlick** [comment]
Ah, that one does look well thought out and complete.  I'll go ahead and switch - the one I proposed is just one I have used before on other projects, and I think I used it because Fedora packaging guidelines led me there (by what route I don't recall).

**Comment by grondo** [comment]
Oh, ok, perhaps the long name is required by some RPM macros or something. Sorry about the diversion.

**Comment by garlick** [comment]
The long name mirrors the name of a directory in systemd.pc
```
systemdsystemunitdir=/lib/systemd/system
```

On ubuntu 16.04 LTS, [daemon(7)](http://manpages.ubuntu.com/manpages/xenial/man7/daemon.7.html), under _Installing Systemd Service Files_ recommends similar m4:

>  Packages using autoconf(1) are recommended to use a configure script excerpt like the following to determine the unit installation path during source configuration:
````m4sh
   PKG_PROG_PKG_CONFIG
   AC_ARG_WITH([systemdsystemunitdir],
        [AS_HELP_STRING([--with-systemdsystemunitdir=DIR], [Directory for systemd service files])],,
        [with_systemdsystemunitdir=auto])
   AS_IF([test "x$with_systemdsystemunitdir" = "xyes" -o "x$with_systemdsystemunitdir" = "xauto"], [
        def_systemdsystemunitdir=$($PKG_CONFIG --variable=systemdsystemunitdir systemd)

        AS_IF([test "x$def_systemdsystemunitdir" = "x"],
      [AS_IF([test "x$with_systemdsystemunitdir" = "xyes"],
       [AC_MSG_ERROR([systemd support requested but pkg-config unable to query systemd package])])
       with_systemdsystemunitdir=no],
      [with_systemdsystemunitdir="$def_systemdsystemunitdir"])])
   AS_IF([test "x$with_systemdsystemunitdir" != "xno"],
         [AC_SUBST([systemdsystemunitdir], [$with_systemdsystemunitdir])])
   AM_CONDITIONAL([HAVE_SYSTEMD], [test "x$with_systemdsystemunitdir" != "xno"])
````
 > This snippet allows automatic installation of the unit files on systemd machines, and optionally allows their installation even on machines lacking systemd. (Modification of this snippet for the user unit directory is left as an exercise for the reader.)

I'm thinking maybe it is OK as proposed after all?

**Comment by grondo** [comment]
Yes sorry about that

**Comment by garlick** [comment]
I added some cleanup in the connector-local module, and a test to make sure the local connector auth failure returns EPERM to the user.

To make that work without requiring the ability to sudo to another user, I added a way to get/set an integer's worth of debug flags in modules (the need for something along these lines was discussed briefly in #813).  There's a command `flux-debug` that can be used within tests to get/set debug flags per comms module, and then there's a builtin method for all modules that allows a debug mask stored in the handle under `flux::debug_flags` to be manipulated.

So to test the auth failure, the test calls
```
$ flux debug --set 1 connector-local    # enable one shot failure
$ flux comms info   # fails with EPERM
flux-comms: flux_open: Operation not permitted
```

In the auth code there's a check that looks like this:
```C
    int *debug_flags = flux_aux_get (h, "flux::debug_flags");
    if (debug_flags && (*debug_flags & 1)) {
        flux_log (h, LOG_ERR, "connect by uid=%d pid=%d denied by debug flag",
                  c->ucred.uid, (int)c->ucred.pid);
        *debug_flags &= ~1; // one shot
        errno = EPERM;
        goto error;
    }
```

I'm not sure if this will be useful in all cases but it seemed like a fairly unobtrusive way to implement this test and establish a simple way for similar tests to be added in other places.

**Comment by grondo** [comment]
That's nice!

Did you consider making `flux debug` a subcommand of `flux module`, or otherwise pick a more esoteric name? The only reason I think of this is because `flux debug` seems like prime command name real estate, and I could imagine a future someone would want a `flux debug` user or sysadmin tool, and then we'd have to change a bunch of  test scripts...

**Comment by garlick** [comment]
Hmm, flux-module might be a better fit.  Good idea.

**Comment by garlick** [comment]
Rebased with flux-debug folded into flux-module as `flux module debug`

I also converted flux-module to use liboptparse, and folded in flux-comms-stats as `flux module stats`.

Still todo: update flux-module(1) and add test coverage for `flux module stats` (there never was any).

**Comment by garlick** [comment]
I think this might be ready for merge.  Just added coverage for `flux module stats` and squashed down some incremental change.

I feel OK about the level of testing here - I was dinged by coveralls on having no test coverage for the changes to connector-local to handle ENOMEM, but that's a hard case...

**Comment by garlick** [comment]
Oh except I need a flux-module(1) update.  Stand by.

**Comment by grondo** [comment]
>  I was dinged by coveralls on having no test coverage for the changes to connector-local to handle ENOMEM, but that's a hard case...

Yeah, we don't have a viable way to test error conditions so I usually take that into account when reviewing code coverage results. I'll take a more detailed peek at this but looks good to me so far.

**Comment by grondo** [comment]
This looks good to me, is it ready now?

**Comment by garlick** [comment]
Sure.

**Pull request merged**
