### PR TITLE
NEWS.md: add v0.19.0 release notes

### PR DESCRIPTION
**Pull request by garlick**
Here's a first cut on release notes for next week's v0.19.0, based on what's been landed since v0.18.0.

Please add any outstanding issues that we need to get into this release to the `flux core 0.19.0` milestone.

Fee free to push/force push to this PR as changes need to be made.

### CODE REVIEW

**Comment by grondo** [comment]
Thanks @garlick! I force-pushed an update to add the recently merged Python API PR and also mention new `--debug` option to `flux-mini(1)`.

Also tried out a "highlights" preamble. It is kind of arbitrary so we can remove it before the tag if it doesn't makes sense for this release.

**Comment by garlick** [comment]
I think we're done here.  @chu11 want to give this a quick skim and approve if all is well?

**Comment by garlick** [comment]
Right! Good enough, I'll set MWP.

**Comment by grondo** [comment]
Thanks! Once this goes in I'll push a tag.

**Pull request merged**
