### PR TITLE
python: split flux.job module into multiple files

### PR DESCRIPTION
**Pull request by grondo**
At this point, this work is  a request for comments. I don't know if there are drawbacks to splitting a single python module  into multiple files -- will this slow down `import flux.job` significantly?

This does prepare the way for an easier addition of the `flux.job.JobInfo` class (and related functions) to the bindings though.

### CODE REVIEW

**Comment by grondo** [comment]
Ok, sorry for the noise. It took me a few tries to get the Makefile right. The recursive `Makefile.am` files under `src/bindings/python/flux` are now collapsed into a single `Makefile.am` using `nobase_fluxpy_PYTHON`, obviating the need for definition of "extra" automake dirs like `fluxpycoredir` `fluxpyjobdir`. Also, all python sources can now go under the same rule. Hopefully this simplifies future efforts as well.

**Comment by grondo** [comment]
Restarted two builders that hit an error in the initial clone from github.

**Comment by garlick** [comment]
I had not encountered `nobase` before.  Nice cleanup!

**Comment by grondo** [comment]
Ok, I think this is largely working. No code changes, just reorganization, is probably a good place to stop for this PR, so probably one of the resident Python experts should review this. (@SteVwonder and/or @bertjwregeer 

I'm a little worried this change could have an adverse performance impact.

**Comment by SteVwonder** [comment]
Awesome!  This looks great to me!  `job.py` was getting unwieldy, and this really cleans things up.

In terms of performance, there will be an added cost since the python interpreter will need to find and import 9 more files than it used to, but my guess is that will be completely in the noise except in pathological cases (i.e., having a Spack environment loaded and running across 1000s of nodes).  For all of the other imports that are now duplicated across the new files (e.g., `import json`, `import yaml`, `import flux`), python caches imported modules, so they should essentially be free.

For the pathological cases, I suspect Spindle will be more than enough to handle those cases.

**Comment by grondo** [comment]
> My only thought is that the wrapper file, or the RAW in it might be good to be renamed as _RAW or _wrapper.py or both.

Great suggestion! I was wondering exactly how I should do that. I'm fine renaming both.

**Comment by trws** [comment]
> In terms of performance, there will be an added cost since the python interpreter will need to find and import 9 more files than it used to, but my guess is that will be completely in the noise except in pathological cases

Yeah, this should be right.  One thing I mentioned as an aside above but found really, really helped when doing some of the initial mummi stuff was setting up the big directory of modules in a zip file: [import modules from zip archives](https://www.python.org/dev/peps/pep-0273/).

The interpreter can treat a zip as a directory, and it caches the whole file along with its internal directory listing on initial load then does lookups in it rather than loading all from disk. So if it became an issue a bit of packaging rework could probably squash it without too much trouble.

**Comment by grondo** [comment]
Thanks @trws and @SteVwonder! I've force-pushed a change to rename `flux.job.wrapper` to `flux.job._wrapper` and also `RAW` to `_RAW`. The previous users of `RAW` now use `from flux.job._wrapper import _RAW as RAW`.

**Comment by bertjwregeer** [comment]
Hey,

I am going to assume that I was tagged on accident? Unless you want me to review it, in which case I am sure I could give it my best :P

Cheers,
Bert

**Comment by grondo** [comment]
Hahaha, yeah that was a strange GitHub autocorrect snafu

**Comment by grondo** [comment]
It looks like this one was approved so I'm setting MWP since I have other work requiring this PR.

**Comment by grondo** [comment]
Actually this won't pass travis until #3169 is merged.

**Pull request merged**
