### PR TITLE
Cleanup broker request/event dispatch and handlers

### PR DESCRIPTION
**Pull request by garlick**
This PR addresses #934 by converting all message handlers in the broker to the `flux_msg_handler_f` prototype, registered against the reactor embedded in the broker's internal`flux_t` handle.  With those conversions complete, functions that build on the "destroy on send" idiom of the deprecated handler prototype are converted to look like the rest of Flux.  As a bonus some event message handling functions that used the same idiom were converted.  Getting away from that vestigial idiom was the main point of this PR.

Some code was factored out of broker.c to try to untangle the builtin services from the broker itself, with a thought to eventually allowing some services to be loaded other ways, e.g. after #930.   However I didn't take this too far as it seemed slightly off topic for this PR (I only did that in cases where I was reworking message handlers anyway).  Along the same lines, I started dropping the "cmb." prefix from builtin-services as this hardwires the way they are loaded in an unnecessary way.  However, that also was a bit off topic so it was only done where I happened to be anyway.  I did open flux-framework/rfc#69 against RFC 3 to drop the _requirement_ that there be a "cmb." prefix on broker resident services and I will open two more issues to track the unfinished refactoring and renaming.

### CODE REVIEW

**Comment by garlick** [comment]
I'll see about adding some tests to get coverage over the limit.

**Comment by garlick** [comment]
Rebased on current master and a sharness test in generic-utils to minimally poke at the heaptrace service, so at least the RPC paths and the command line gets exercised.  Test coverage is still under par but I think most of this is error paths...

**Comment by grondo** [comment]
Since this is basically just shuffling code around I don't think an attempt to increase code coverage is work great effort here, unless you've already proceeded down that path, @garlick?

**Comment by grondo** [comment]
Ok, ready to merge then?

**Comment by garlick** [comment]
Sure.

**Pull request merged**
