### PR TITLE
libschedutil: add resource acquire support, make asynchronous

### PR DESCRIPTION
**Pull request by garlick**
This PR reworks libschedutil to add support for the `resource.acquire` RPC, and to perform initialization asynchronously.

The scheduler registers callbacks then calls `schedutil_init()` and enters the reactor.   Resource acquisition, and then the job manager initial handshake occur in the reactor.  This allows `flux module load` to return before resource acquisition has completed, which avoids a deadlock situation described in the "phased bringup" PR #3057.

Since several new callbacks needed to be added, it seemed like a good idea to create an "operations struct" to hold all the callbacks rather than adding new function pointer arguments to `schedutil_create()`.   That looks something like this:
```c
static const struct schedutil_ops ops = {
    .res_acquire = res_acquire_cb,
    .res_up = res_up_cb,
    .res_down = res_down_cb,
    .hello = hello_cb,
    .ready = ready_cb,
    .alloc = alloc_cb,
    .free = free_cb,
    .cancel = cancel_cb,
};

int mod_main ()
{
    schedutil_t *su;
...
    if (!(su = schedutil_create (h, &ops, ctx)))
        goto error;
    if (schedutil_init (su) < 0)
        goto error;
    if (flux_reactor_run (r, 0) < 0)
        goto error;
    schedutil_destroy (su);
    ...
}
```

The hello, alloc, free, and cancel callbacks work exactly as before.

The new resource callbacks are prototyped like this:
```c
static void res_acquire_cb (flux_t *h, const char *by_rank, void *arg);
static void res_down_cb (flux_t *h, const char *idset, void *arg);
static void res_up_cb (flux_t *h, const char *idset, void *arg)
```
Finally, a new ready callback is called once the job manager hello protocol has completed.  This gives the scheduler a chance to call `schedutil_ready()` to indicate that alloc/free/cancel requests can begin:
```c
static int ready_cb (flux_t *h, void *arg)
{
    struct myctx *ctx = arg;
    if (schedutil_ready (ctx->su, "single", NULL) < 0)
        return -1;
    return 0;
}
```

I see flux-framework/flux-sched#694 is pending (and my review was requested - oops just noticed that).  I'm hoping this PR will be able to reduce the complexity of those changes a little bit.  One suggestion on how to proceed with that would be for me to put up a fluxion PR to conform to this API change with `res_acquire()`, `res_up()`, and `res_down()` callbacks stubbed, then 694 could be rebased on top of it, and rather than implementing the RPC it would just need to fill in the callbacks.

Sorry for not figuring out this work was needed _before_ 694 was proposed.

### CODE REVIEW

**Comment by grondo** [comment]
Nice improvement for scheduler authors!

Just a few quick suggestions/questions before a more complete review. These are pretty minor, and made without looking at implementation, so please ignore if they make no sense.

 * There doesn't seem to be compelling reason to shorten `resource` to `res` in the resource module callbacks. I think it would be clearer and less likely to conflict with other scheduler internals to just use `resource_acquire`, `resource_up` and `resource_down`. However, that is just a minor suggestion, feel free to ignore.
 * Would it perhaps be wiser to combine the callbacks for `up` and `down` into a single `resource_update` or similar callback? Otherwise, once other resource updates are supported (e.g. unexclude) the API will need to be changed again?

**Comment by garlick** [comment]
Aw I knew in the back of my mind that `res` was a bad idea.  Will change.

I thought maybe separate up and down callbacks would make their function more obvious to a casual reader?  If we have one callback that handles up, down, exclude, unexclude (or shrink, grow) is that going to be a complicated callback?  It's not too big of a deal to tack new callbacks onto the operations structure, especially if they can have some reasonable default behavior if NULL.

**Comment by grondo** [comment]
> It's not too big of a deal to tack new callbacks onto the operations structure, especially if they can have some reasonable default behavior if NULL.

As long as there is a plan to extend to allow future resource operations of `unexclude` `exclude` and `grow` `shrink` etc without introducing ABI breaking changes that will require concerted PRs between flux-core and flux-sched then I am satisfied.

**Comment by garlick** [comment]
Maybe I should go ahead and add the "unexeclude" ("include"?) callback now to prepare for that acse.

**Comment by dongahn** [comment]
One big question for me is if this will work with two module architecture of Fluxion. `qmanager` is the user of schedutil and `sched-fluxion-resource` is the user of `resource.acquire`.

**Comment by dongahn** [comment]
> As long as there is a plan to extend to allow future resource operations of unexclude exclude and grow shrink etc without introducing ABI breaking changes that will require concerted PRs between flux-core and flux-sched then I am satisfied.

@garlick: I don't know if you have a chance, but it would be great if you can review my comments at https://github.com/flux-framework/rfc/pull/253.

But before deciding what gets more to schedutil, it would be wise to get my above question answered... Overall, completing the work at flux-framework/flux-sched#694 was fairly involved in terms of how to make fluxion resource and fluxion qmanager synchronize over resource.acquire interface.

**Comment by garlick** [comment]
> One big question for me is if this will work with two module architecture of Fluxion. qmanager is the user of schedutil and sched-fluxion-resource is the user of resource.acquire.

Oops, when I was looking at your PR I missed that the resource RPC was happening in a separate module.

I think I can make a small change that will allow that split, depending on which callbacks you populate in the operations structure.   Let me ponder that a bit - thank you for speaking up quickly!

**Comment by dongahn** [comment]
> I think I can make a small change that will allow that split, depending on which callbacks you populate in the operations structure. Let me ponder that a bit - thank you for speaking up quickly!

The split is one issue and allowing for the user of schedutil and resource.acquire to be sync is another issue. 

I wonder if we really want to provide a higher level convenience library? Is this to hide the churn you will introduce?

**Comment by garlick** [comment]
The problem is that the scheduler (fluxion-resource in this case I guess) needs to enter the reactor before receiving the first `resource.acquire` response so that rc1 doesn't get deadlocked once we make the changes in #3057.  It can't block waiting for that first response before entering the reactor.  The same for the job manager hello protocol in fluxion-qmanager.  Since this increases the code complexity on the scheduler end I thought it would be helpful to hide the details and just provide a callback registration mechanism.

For qmanager, we can make similar changes to what this PR does in `sched-simple`, but leave the resource callbacks set to NULL.  If the callbacks are NULL, the resource protocol is not executed.

For resource, we have options:
1) Ignore libschedutil and make sure the resource.acquire RPC responses are all handled asynchronously so deadlock is avoided
2) Use libschedutil in resource, but let me make a small change so the job manager protocols are not executed if their callbacks are NULL

I'm not sure I understand the qmanager/resource synchronization issue you mentioned so I will go read your PR and see if I can find it there.

**Comment by garlick** [comment]
OK, I see - the qmanager is waiting for notification from the fluxion-resource module before it begins the job manager HELLO handshake.  What would need to be changed here (besides the API changes proposed in this PR) is that request for notification would need to be split as follows:
1) send the `fluxion-resource.notify` request
2) set up a continuation for future
3) enter the reactor
4) in the continuation, call `schedutil_init()` to kick off HELLO protocol

Since resource callbacks would not be populated in the ops struct, resource acquisition would not be started in qmanager.  I don't know if entering the reactor creates any complications for other activities in qmanager.

In fluxion-resource, as mentioned above, you could make the resource.acquire request in a similar manner:
1) send request
2) set up continuation
3) enter the reactor
4) upon receipt of first acquire response, notify qmanager

Or you could call `schedutil_init()` to kick off the resource protocol and notify qmanager from the `resource_acquire` schedutil callback.

The end goal:  both modules have to enter the reactor and let `flux module load` complete _before_ the resource.acquire response is received.

**Comment by garlick** [comment]
> Maybe I should go ahead and add the "exclude" and "unexeclude" ("include"?) callback now to prepare for that case?

I think it would probably be best for this PR to stay focused on making initialization asynchronous to avoid the deadlock.  (I started going down this path but it seems topically distinct and more than a small change)

**Comment by garlick** [comment]
Just pushed two changes:
- rename `res` to `resource`
- execute only the resource acquire protocol if the `ops->hello` is NULL (for fluxion-resource)

**Comment by garlick** [comment]
Rebased on current master and change `ops->ready()` prototype to include a `flux_t *` like all the other callbacks.

**Comment by garlick** [comment]
I was going to suggest we expedite getting this PR reviewed and merged so we can make headway on the #3047, but actually, given the apparent difficulty in changing fluxion's startup, we might want to consider one of @grondo's ideas instead:

Right now `flux module load` returns once the module state transitions from INIT to RUNNING or SLEEPING.  The state is communicated to the broker with prep (SLEEPING) / check (RUNNING) watchers, so that transition occurs as soon as `flux_reactor_run()` is invoked.  The crux of _this_ PR is to allow the scheduler initialization to occur _after_ the reactor has been started so `flux module load` can move on and not deadlock.  However, instead we could provide an API interface, say
```c
/* Set module state to READY so `flux module load` can return success
 * before module enters reactor.
 */
int flux_module_set_running (flux_t *h);
```

If the scheduler modules call this, then I _think_ none of these changes are neeeded and we can dump this PR.

I plan to give this a try.  Meanwhile we should decide if anything in this PR is salvageable/useful if this alternate approach is successful.

**Comment by garlick** [comment]
Let's close this for now - it looks like the other approach will be fine.

**Pull request closed without merging**
