### PR TITLE
broker: use flux reactor not zloop

### LINKED ISSUE #320: stop using zloop in the flux broker
The broker is still using the zloop reactor from czmq, while the rest of the code base has migrated to libev.

Possibly the flux reactor could be used here?  If so this opens the possibility of using the `flux_reduce_t` stuff on native broker services like `cmb.log`, use of coproc mode, etc..

### PR DESCRIPTION
**Pull request by garlick**
Transform the broker's zloop into a flux reactor loop.

In the process, fix some typedefs that were at odds with our newer RFC 7 policy on abstract types and drop the dumb `endpt_t` class.

Also, add an SM_FLUX option to `subprocess_manager_set()`  so that it can call `zio_flux_attach()` rather than `zio_zloop_attach()`.  @grondo I'm not sure if you wanted to do this another way but this was an easy step to get things working.

Fixes #320.

### CODE REVIEW

**Comment by grondo** [comment]
`SM_FLUX` option is fine for now. I wanted to clean up the event interfaces for subprocess and zio so that they're more event-loop agnostic, but I didn't even figure out exactly how to do that cleanly at this point.

**Comment by grondo** [comment]
Wow quick work.

I put a couple comments on specific commits that seemed like they could use some extra description to give people viewing history a bit more context. Don't feel obligated to make those changes though, they were just my suggestions...

**Comment by garlick** [comment]
Just pushed an update with some expanded commit messages per your suggestions.  Thanks!

**Comment by grondo** [comment]
Nice, thanks. This obviously should go in.

**Pull request merged**
