### PR TITLE
shell: misc environment-related fixes

### PR DESCRIPTION
**Pull request by garlick**
Environment-related fixes peeled off of #3661, since these are not directly related to that PR.

### CODE REVIEW

**Review by chu11 — APPROVED** [review]
LGTM!

**Comment by garlick** [comment]
Thanks @chu11!

Repushed after changing a commit message to note the following consequence:
> Note: if environment is not provided, task environment starts
empty rather than from a copy of the shell's environment.

I don't think this is consequential.  When our tools build an empty environment, it is provided as an empty object which has the same effect, e.g. `flux mini run --dry-run --env=-* hostname` produces 
```json
  "attributes": {
    "system": {
      "duration": 0,
      "cwd": "/home/garlick/proj/flux-core/src/cmd",
      "environment": {}
    }
  },
```

Coverage is low but it is mostly caused by unlikely error paths (e.g. ENOMEM).

If this is OK with the above caveats, I'll set MWP.

**Comment by grondo** [comment]
> Note: if environment is not provided, task environment starts
> empty rather than from a copy of the shell's environment.

This seems fine to me. I bet the only place this change really has an effect is when running the shell in standalone mode. It clearly didn't break any tests, so this seems fine to me.

Note: can we prefix the PR title with `shell: ` to indicate this applies to the job shell not other general Flux environment? (This could be helpful in release notes)

**Comment by garlick** [comment]
Thanks!  I went ahead and changed the PR title as suggested since most of the changes are shell related (and shell uses libsubprocess).   Setting MWP.

**Pull request merged**
