### PR TITLE
fix various typos

### PR DESCRIPTION
**Pull request by garlick**
The obligatory typo fix PR.  Feel free to push here.

### CODE REVIEW

**Comment by chu11** [comment]
since the typo checker missed some of these, maybe time to update version?  mentioned these in upstream crate-ci to get em there eventually.  https://github.com/crate-ci/typos/issues/943

**Comment by grondo** [comment]
Pushed some more fixes here and rebased on current master.

**Comment by grondo** [comment]
Ok, additionally updated the typos checker version as suggested by @chu11 (and added one more file to the exclusions)

**Comment by garlick** [comment]
I would add an approval but as the originator of this PR I'm not allowed :-(

**Review by grondo — COMMENTED** [review]
LGTM! :slightly_smiling_face:

**Review by grondo — APPROVED** [review]

**Pull request merged**
