### PR TITLE
build: add --disable-docs configure option

### PR DESCRIPTION
**Pull request by garlick**
This may help address LLNL/spack#2109

### CODE REVIEW

**Comment by grondo** [comment]
This seems fine to me! 
One Q -- what happens to `flux help COMMAND` when the manpages aren't available?

**Comment by garlick** [comment]
> One Q -- what happens to flux help COMMAND when the manpages aren't available?

Nothing special.  Maybe we need a message indicating that flux wasn't built with documentation?

```
$ flux help flux_open
No manual entry for flux_open
```

**Comment by grondo** [comment]
> Maybe we need a message indicating that flux wasn't built with documentation?

Yeah, building a real installation without some kind of builtin help kind of bothers me, but I could get over it. I think for now it is fine until someone complains. (?)

**Comment by chu11** [comment]
IMO, it sounds inevitable that someone will file a bug/issue saying ```flux help FOO``` doesn't work.  I like the idea of just saying "no documentation built" to remove that possibility.

**Comment by grondo** [comment]
Ok, @chu11, thanks for volunteering! :smile_cat:

**Comment by grondo** [comment]
There may be another issue too. I think `flux-help` is just execing `man` and relying on MANPATH set correctly to find the right man pages. In a case where there is system flux-core installed in default MANPATH, and a user runs a `flux start` from a non-standard flux of a different version, and that version is built without manpages, `flux help` will currently return the *wrong* man page, which could cause confusion.

Definitely `flux help` needs to ensure that it is going to find the right manpages before execing man, and "no documentation built" error is better than displaying man pages for the incorrect version.

I'm not sure @garlick or @chu11 if you had good ideas on how to handle this, but certainly a check before calling out to `man` is required.

There is also the idea to just install the asciidoc source somplace where it can be displayed with `$PAGER` when manpages were not built.

**Comment by chu11** [comment]
Don't know code here that well, but perhaps ```INTREE_MAN_PATH``` is just not being loaded/pre-fixed properly?  I can take a look more closely.  Do you want to merge this one since it fixes the stated problem?

**Comment by grondo** [comment]
Oops, I clicked "Update branch" accidentally, @garlick will have to rebase on current master anyway.

> Don't know code here that well, but perhaps INTREE_MAN_PATH is just not being loaded/pre-fixed properly? I can take a look more closely. Do you want to merge this one since it fixes the stated problem?

It's true, this PR makes things no worse than they were, just allows build of flux-core at least on systems with broken a2x, so yeah we should probably merge this and I'll open an issue for `flux help`

**Comment by grondo** [comment]
Opened #874 for `flux help` enhancements being discussed here.

**Comment by garlick** [comment]
OK, rebased.

**Comment by grondo** [comment]
Great. I'll merge once Travis passes

**Comment by garlick** [comment]
Not really related but on some systems (Ubuntu) setting manpath disables
system man pages....

**Pull request merged**
