### PR TITLE
testsuite: cleanup job-manager tests

### PR DESCRIPTION
**Pull request by chu11**
Built on top of #3473.  

After working on #3473, I felt that the job-manager tests really needed a cleanup (#3417).  The file names were all over the place as job-manager features / bugs / tests grew.  A non-trivial amount of duplicate tests emerged as early cut and paste went amok (largely my fault).

Basically this PR

- renames many of the files to be a bit more organized (i.e. the "job-manager-limited" test and "job-manager-unlimited" test files should be numbered right next to each other.)
- remove a number of duplicate tests
- simplify "test setup" by moving config/setup into `rc1-job` (i.e. no longer manually unloading modules in the files)

### CODE REVIEW

**Review by grondo — COMMENTED** [review]
Since you're updating tests anyway, uses of `flux jobspec srun` should be removed.

I don't think I caught all the cases, but in general serial submission of jobs could be replaced with `flux mini submit --cc` or `flux mini bulksubmit` to speed up tests.

I gave a few examples inline.

**Comment by chu11** [comment]
rebased on #3473 and adjusted code for new default limit.  Re-pushed w/ a commit on top that removed `flux jobspec srun ...` and replaced `flux job submit` with `flux mini submit` in all of the job manager tests.

I didn't replace the serial job submissions with `flux mini bulksubmit` though.  The tests currently do things like `$(cat job1.id)` to get the job id of a job.  Using `id_byname()` to get the job id (which is `flux jobs` and `grep` underneath) actually slowed down the tests.

There's probably other solutions to get around this, but I figure it wasn't much of a win by that point.  We're only bulksubmitting 5 jobs, not like a thousand.

**Comment by grondo** [comment]
> There's probably other solutions to get around this, but I figure it wasn't much of a win by that point. We're only bulksubmitting 5 jobs, not like a thousand.

```
 split -d -l 1 -a 1 jobids.out  jobid.
```

The problem is that all the serial `flux-mini submit` used in the testsuite add up:

```
ƒ(s=1,d=0,builddir) grondo@asp:~/git/f.git$ time for i in {1..5}; do flux mini submit -n1 hostname; done
ƒ9eHUUPWo
ƒ9ePnfL7y
ƒ9eVo4RM1
ƒ9ebuPThR
ƒ9ehunYvT

real	0m1.365s
user	0m1.008s
sys	0m0.126s
ƒ(s=1,d=0,builddir) grondo@asp:~/git/f.git$ time flux mini submit --cc=1-5 -n1 hostname
ƒ9odxXbK5
ƒ9odxXbK6
ƒ9odz1abR
ƒ9odz1abS
ƒ9odz1abT

real	0m0.410s
user	0m0.196s
sys	0m0.036s
```

**Comment by chu11** [comment]
> The problem is that all the serial flux-mini submit used in the testsuite add up:

Ahh i get what you're saying now.  I was thinking about when I run `make -j16 check`, but of course in the CI it may be serial at times (appears to be `-j2` in most cases).

**Comment by grondo** [comment]
> Ahh i get what you're saying now. I was thinking about when I run make -j16 check, but of course in the CI it may be serial at times (appears to be -j2 in most cases).

Yeah,  but you are probably right in terms of this PR there is not that much benefit

**Comment by chu11** [comment]
rebased & re-pushed with an extra commit on top to bulk-submit jobs in the job-manager tests instead of serially submitting them.

To create the files with job ids in them I originally did:

`split --numeric-suffixes=1 --additional-suffix=.id -l 1 -a 1 jobids.out job`

I think this line is long and perhaps non-obvious, mainly b/c I was trying to make sure to not create new file names and require a search and replace everywhere.

I could do a simpler:

`split --numeric-suffixes=1 -l 1 -a 1 jobids.out job`

but I'd have to change file names everywhere.

I could a far more simpler & portable:

`split -l 1 -a 1 jobids.out job`

but I'd have to change the file names everywhere and re-number the jobs from 0-4 instead of 1-5.

I think there awk/sed ways of doing this.

Going back and forth on things, I eventually settled on doing things a simpler (i.e. a far stupider) way.

```
+        flux mini submit --cc="1-5" --flags=debug -n1 \
+           hostname > jobids.out &&
+        head -n 1 jobids.out > job1.id &&
+        head -n 2 jobids.out | tail -n 1 > job2.id &&
+        head -n 3 jobids.out | tail -n 1 > job3.id &&
+        head -n 4 jobids.out | tail -n 1 > job4.id &&
+        tail -n 1 jobids.out > job5.id
```

maybe wasn't the right choice.

**Comment by grondo** [comment]
Instead of `split` you could also keep the jobids in a single file and print the Nth line to get the nth job (e.g. `awk {NR==$n}` or similar)

Or, I did a quick hack to add a `--results` option to `flux mini submit/bulksubmit` that will write the "results" (jobid and/or per job output) to separate files, with a `$CC` suffix if `--cc/--bcc` is used, e.g.:

```console
$ flux mini submit  --results=jobid. --cc=0-5  hostname 
$ ls -ltrs jobid.*
4 -rw-rw-r-- 1 grondo grondo 12 Feb  1 13:23 jobid.5
4 -rw-rw-r-- 1 grondo grondo 12 Feb  1 13:23 jobid.4
4 -rw-rw-r-- 1 grondo grondo 12 Feb  1 13:23 jobid.3
4 -rw-rw-r-- 1 grondo grondo 12 Feb  1 13:23 jobid.2
4 -rw-rw-r-- 1 grondo grondo 12 Feb  1 13:23 jobid.1
4 -rw-rw-r-- 1 grondo grondo 12 Feb  1 13:23 jobid.0
```

```console
$ flux mini bulksubmit --dry-run --results=jobids.{}. --cc=0-5  hostname  ::: a b c
flux-mini: submit --results=jobids.a. hostname
flux-mini: submit --results=jobids.b. hostname
flux-mini: submit --results=jobids.c. hostname
```

This might actually be useful for testing with `--watch` since you can run several jobs simultaneously _and_ capture their output into files, so I'll keep working on it in the background.

(The option `--results` is taken from GNU parallel, but  I will keep thinking of a better name)

**Comment by chu11** [comment]
> Instead of split you could also keep the jobids in a single file and print the Nth line to get the nth job (e.g. awk {NR==$n} or similar)

The goal was to not change the filenames or the `$(cat job1.id)` calls, otherwise we could just stick with `split`.

> (The option --results is taken from GNU parallel, but I will keep thinking of a better name)

I like this option.  If you're serious about adding it, we can go with this plan once it's in.  Or go with any non-optimal approach I've proposed above and fix later.

**Comment by chu11** [comment]
I re-pushed replacing my stupid head/tails with the long `split`.  When `--result` (or whatever it is eventually called) we can adjust these calls afterwards.

**Comment by chu11** [comment]
rebased, fixing conflict

**Review by grondo — APPROVED** [review]
Nice work, this is some great cleanup. On my system the tests seem to run quite a bit faster as well.

I'll set MWP so you don't have to keep fixing up conflicts ;-)

**Pull request merged**
