### PR TITLE
Cross compilation fixes for Julia bindings

### PR DESCRIPTION
**Pull request by vchuravy**
One possible way of fixing https://github.com/flux-framework/flux-core/issues/3502

### CODE REVIEW

**Comment by garlick** [comment]
Hi @vchuravy - zeromq has for some time had an internal fallback curve implementation, so now you have to explicitly disable it to get rid of curve support.  As a result, I think it's not as important now to have a configure time test in flux for it.

If you like, just drop `x_ac_zeromq.m4` and replace the `X_AC_ZEROMQ` call in configure.ac with
```
PKG_CHECK_MODULES([ZMQ], [libczmq >= 3.0.0 libzmq >= 4.0.4])
```

Our rule of thumb is that a PR short description line should roughly translate to a high level release notes entry.  Would you mind combining your changes related to the julia bindings into one PR so we have them topically grouped?

Also please include in each commit a description of the problem. We've found that using a "problem/solution" format sometimes helps them be concise.

For example for this commit maybe:
```
build: drop check for libzmq curve support

Problem: autoconf check for curve encryption fails
in a cross compilation environment needed for julia bindings.

Since zeromq now includes an internal fallback curve implementation,
this check is no longer needed.  Drop it.

Fixes #3502
```

Thanks!

**Comment by vchuravy** [comment]
This should be ready for review.

**Review by grondo — APPROVED** [review]
LGTM, Thanks!

**Comment by grondo** [comment]
Thanks @vchuravy! I've set MWP label so this should get auto-merged.

**Pull request merged**
