### PR TITLE
shell/pmi: add improved key exchange mechanism

### PR DESCRIPTION
**Pull request by garlick**
This implements a new PMI key exchange mechanism based on shells forming a virtual tree and fully exchanging keys during the barrier operation.  The shells communicate with virtual "peers" by using shell-rank-addressed RPCs over the existing TBON.  It seems to perform equivalently or somewhat faster than the KVS on my laptop (heh) at 128 broker scale.  It's reasonably simple (around 300 LOC).

I've optimistically made this the default mechanism for PMI because it keeps PMI keys out of the Flux KVS, and thus avoids contributing unnecessarily to persistent content growth.

The old and new mechanisms can be compared.  To use the old one, set the `pmi.kvs` shell option:
```console
$  flux mini run -o pmi.kvs -N128 -n128 src/common/libpmi/test_kvstest
0.201s: flux-shell[0]:  WARN: pmi: using Flux KVS
0: put phase: 37.861 msec
0: get phase: 74.631 msec
$ flux mini run -N128 -n128 src/common/libpmi/test_kvstest
0: put phase: 5.001 msec
0: get phase: 46.278 msec
```
By default, the virtual tree is binary.  You can tune that with the `pmi.k=N` shell option:
```console
$ flux mini run -o pmi.k=16 -N128 -n128 src/common/libpmi/test_kvstest
0: put phase: 18.169 msec
0: get phase: 45.923 msec
```

I think the performance characteristics of this algorithm are probably similar to the KVS.   In the old:
* Puts are local (to the shell).  They build a KVS transaction.
* Barrier is a KVS fence operation.
* Gets are direct KVS requests.

In the new:
* Puts are local (to the shell).
* Barrier is a full exchange (fence-like commit to shell 0, with global key set carried in response).
* Gets are local (to the shell).

I claim "similar" because in the old implementation, the entire KVS fence operation is likely represented in one content blob.  As individual keys from the blob are looked up, the blob propagates through the hierarchical content cache. Once that gets going, lookups are answered from the local KVS instance.  So really the KVS is doing the full propagation of keys to every rank anyway, via a pull.

One plus for the new: since PMI-1 implements `PMI_KVS_Get()` as a synchronous request to the shell, the latencies add up back to back.  If the shell has to go out to the KVS to get every key, that approximately doubles the latency compared to the new, even in the best case where the content cache is hot. 

A minus: there are more larger messages that might be taking a tortured route over the TBON.

WIP for now - need to try it on fluke.  I don't put much stock in these numbers from my laptop.

### CODE REVIEW

**Comment by garlick** [comment]
I did some testing on a 48 node allocation on fluke using `src/common/libpmi/test_kvstest`.   All tests were with 192 tasks.  At this scale the minimum speedup for the various tests was **2.1x** (22.3ms vs 10.3ms) over 48 shells, each task doing:
* put one key / barrier / get one key / barrier.

The maximum speedup was **8.3x** (3276ms vs 393ms) over 48 shells, each task doing:
* put 16 keys / barrier / get 3072 keys / barrier.

I ran the workload in two configurations.  First configuration was a size=48 instance, 4 cores per broker.  Second configuration was size=192 instance, 1 core per broker.  The workload consisted of six trials each, with each of 192 tasks doing:
* put one key / barrier / get one key / barrier
* put 16 keys / barrier / get 16 keys / barrier
* put 16 keys / barrier / get 3072 keys / barrier

This result combined with intuition about how performance is likely to compare with the KVS boosted my confidence that this is a reasonable change, especially with the ability to fall back  to the old way with a shell option.  I'll go ahead and clean some things up and force a push.

**Comment by grondo** [comment]
Wow, nice improvement!

Just curious, did you try with equivalent of `--k-ary=256` as would be used with the system instance?

Also, are these results directly applicable to flux launching any MPI app you think? Kudos if so!

(I was going to try it for fun, but thought I'd ask first)

**Comment by garlick** [comment]
I hope these speedups would apply across the board.  At least the kvstest program is intended to simulate roughly what an MPI client does, although YMMV depending which MPI and how it's configured I think.  I didn't do any testing with MPI.

Good thought on testing with Flux configured with a flat TBON.  I may give that a shot.

About to force push some cleanup...

**Comment by garlick** [comment]
OK, push complete.  The options have changed since the description:
* To select old kvs implementation use `-o pmi.kvs=native` (default kvs is "exchange")
* To configure exchange fanout use `-o pmi.exchange.k=N` (default 2)

**Comment by garlick** [comment]
Quick test, 3 trials each, with a 48 broker config with `--k-ary=256` (flat TBON). I only ran with 48 shells and I only ran the nastiest test `kvstest -N16 -n`.

The speed up is about 7x, compared to 8.3x before.

**Comment by garlick** [comment]
Here is the [raw performance data](https://docs.google.com/spreadsheets/d/1hDshMnilbyg-qt3YUCsSKpXeJzHLdkKyj9DGyNZ1b8M) collected the above experiment, for the record.

**Comment by garlick** [comment]
Fixed a couple of typos in comments and commit messages, added the new shell options to the `flux-mini(1)` man page, and rebased on current master.

**Comment by grondo** [comment]
I ran this branch through a bit of testing on fluke without any incident (well some incidents, but I don't think those were related to this PR)

One question though -- I was trying to check on the enhanced "boot" report from the broker when run with `-v`, however, I got this for a 208 broker run:

```
$ time flux mini alloc --broker-opts=-v -n208 flux resource list
lt-flux-broker: boot: rank=0 size=208 time 0.0s
```

Maybe the verbose logging could be modified here to display more precision?

```diff
diff --git a/src/broker/broker.c b/src/broker/broker.c
index aff0bbb..f1f0f9e 100644
--- a/src/broker/broker.c
+++ b/src/broker/broker.c
@@ -426,7 +426,7 @@ int main (int argc, char *argv[])
     }
 
     if (ctx.verbose) {
-        log_msg ("boot: rank=%d size=%d time %.1fs",
+        log_msg ("boot: rank=%d size=%d time %.3fs",
                   ctx.rank,
                   ctx.size,
                   boot_elapsed_sec);
```

Then I get

```
$ time flux mini alloc --broker-opts=-v -n208 flux resource list
lt-flux-broker: boot: rank=0 size=208 time 0.016s
```

(Does that time seem reasonable?)

**Comment by garlick** [comment]
Yes, reasonable!  I'll go ahead and make that change and force a push.  Thanks for the extra testing!

**Review by grondo — APPROVED** [review]
LGTM! Great improvement, nice work!

**Comment by garlick** [comment]
Thanks! I'll go ahead and set MWP.

**Pull request merged**
