### PR TITLE
abstract wreckrun io and status code, add flux-wreck(1) command and file output

### PR DESCRIPTION
**Pull request by grondo**
Opening this PR for comments for now, there are still a couple items TODO.

This PR abstracts the status and stdout/err handling code from `flux-wreckrun` into `wreck.lua` module to enable multiple users of these interfaces (originally done for file output for wreckrun jobs). 

A new `wreck.io` module is used by an `output.lua` plugin for wrexecd which optionally sends output to one or more files per job. The `output.lua` plugin reads an output config block from either `lwj.<id>.output` (for job `id`), or from `lwj.output` as a default for all jobs. The config keys include:
 * `output.labelio`: Label lines of output with source task id
 * `output.files.stdout=FILE`: Copy stdout/err to `FILE`, where `FILE` may be a [mustache](http://mustache.github.io) template with keys `id` for jobid, `cmd` for `argv[0]`, and `taskid` if per-task output is desired. (e.g. `flux-{{id}}.out`) (Actually a `wreck` object is passed in to the template so you can even include data from kvs with `{{kvsdir.<key>}}` but I can't imagine how that is useful)
 * `output.files.stderr=FILE`: Separate stderr from stdout into `FILE`

So for instance to save output from every job to a file within an instance you could run something like
```
flux kvs put lwj.output.files.stdout="flux-{{idj}}.out"
```
in the initial program, or before running any jobs.

Furthermore the following other enhancements were made along the way:
 * As a convenience `-O, --output` and `-E, --error` are added to `flux-wreckrun(1)`.
 * A `--detach` option for `flux-wreckrun(1)` which detaches the command immediately after starting the job (useful in tests and with `--output`)
 * New `flux-wreck` command which exercises job output and status abstractions with `attach`, `status`, and `kill` subcommands:
```
Usage: flux-wreck COMMAND [OPTIONS]...
Supported commands: 
 attach       Attach to running or completed job output
 help         Display this help or help for a command
 kill         Kill a running job
 status       Return status of jobs
```

Still TODO:
 * Tests for `flux-wreck`
 * Update `flux-wreckrun` manpage

### CODE REVIEW

**Comment by garlick** [comment]
This sound pretty neat and I will check it out and play with it when I get to work this morning.

One thought: do we want to proliferate the use of the "wreck" naming in user facing commands?  It seems like that should only be used in the bits that will be replaced.  I think it could be argued that at least `flux-wreckrun` has a usage that is close to what it would be for the replacement service, so why not make it `flux-run` or similar?

**Comment by grondo** [comment]
Hm, I wasn't thinking too much about replacement commands, since in this work I was simply extending wreck prototype to handle (one of) the last major missing features requested, which is output to files. I should say a lot more work went on here than I was expecting, but that is because I was playing a bit with the code, which I didn't feel too bad about since that seems like the purpose of a prototype.

I don't think `flux-wreckrun` has usage that is too close to what will be in `flux run`, since that command will eventually take job spec syntax instead of `-n, -N, -t`, which are the majority of the flux-wreckrun options. It will be easier to throw this command away or keep it there on the side while we develop the real `flux-run` than to change the interface as we go along, or try to keep backwards compatibility

I should mention that there is more work in this PR than I was planning. However, a lot of this is playing with possible interfaces (for extending wrexecd or the eventual replacement shell, for sharing code between commands that might be written in Lua, etc.) So I don't feel completely bad since it seems like a good use of the prototype.

One interesting thing that came out of this work (and the timeout work) is that having a process (wrexecd in this case) load plugins or modules that have access to the internal flux_reactor_t of the process is pretty powerful, and makes the system very extensible. Instead of just having specific hooks which are called as callbacks (e.g. spank plugins), plugins can register their own watchers into the reactor and actually extend wrexecd (or whatever) with full reactive programs as is done with both the IO and timeout modules. (when we design the replacement to this thing we might want to think about gotchas like protecting the main reactor callbacks from being overridden by plugins, generating local events and ways to consume them (like node.js), etc.)

Check out the [output.lua](https://github.com/grondo/flux-core/blob/stdio-to-files/src/modules/wreck/lua.d/output.lua) for example

**Comment by garlick** [comment]
That mustache link didn't work for me.  Maybe [this one](http://mustache.github.io/mustache.5.html) is better?

**Comment by grondo** [comment]
Thanks I fixed the link above (markdown was proccessing the link without `http://` as a relative path)

**Comment by grondo** [comment]
BTW, I'm not set on using the mustache templates, but of those I quickly perused it seemed the simplest, had good model/view separation, allows dot notation to select subfields (e.g. `{{table.key}}`), and seemed like it might be useful down the line for serving up other content.

I'd be fine with doing something simpler too (like slurm's "%j") if you'd prefer.

**Comment by garlick** [comment]
Kicking the tires a bit, all of this seems to work as advertised.

As we briefly discussed in your office, perhaps it makes sense to kill the undocumented and poorly named `flux zio` command since `flux attach` has subsumed most of its useful functionality.  If need be we can resurrect it as a test program when tests are written for libkz, if libkz survives beyond the program execution rewrite that is.

I kind of like the use of mustache here.

**Comment by grondo** [comment]
Ok. Agreed on `flux zio` -- if resurrected perhaps `flux kz` is a better name?
It could have subcommands `cat` and `tee` ( or `write`?).

Do you want to kill it in this PR or in one to be submitted?

**Comment by garlick** [comment]
Should there be a way for a wrexecd plugin to add options to wreckrun without having to hardwire them there?

I was thinking that the ability to extend wrexecd's reactor from a plugin would be useful for implementing the PMI wire protocol discussed in #398, and maybe a wreckrun option would be needed to give hints to the plugin about which MPI environment is needed.

**Comment by garlick** [comment]
Actually, why don't you leave `flux-zio` for now.  I'll submit another PR that updates it, strips it down, and move it to a test directory.  Sorry for the noise in this PR.

**Comment by grondo** [comment]
> Should there be a way for a wrexecd plugin to add options to wreckrun without having to hardwire them there?

Yes, this is a good point that I was going to mention above, as I was thinking the same thing while developing this stuff. I didn't want to go there at this point, but thought it was a great idea for the replacement. (I particularly don't like that options are exported from `flux-wreckrun` that require plugins run in `wrexecd` to activate.)

If this will be useful sooner, it should not be too difficult to implement. And hopefully the groundwork could be reused in the future, so it would not be time wasted on wreck.

The general idea I had is that plugins/extensions would export an option table with all options they want to register with `flux wreckrun` and `flux submit` (very similar to spank plugins here). Additionally each plugin would have a namespace in the kvs which would be handed to them as a kvsdir object in both wrexecd and wreckrun context. Then option code, when activated, could use this option namespace to transparently communicate state to backend code (in wrexecd or elsewhere).

**Comment by garlick** [comment]
I noticed `flux wreck` doesn't handle a failed `flux_open`.  When run without a session I get
```
$ ./flux wreck attach 4
lua: ...me/garlick/proj/flux-core/src/bindings/lua/wreck.lua:237: attempt to index local 'f' (a nil value)
stack traceback:
        ...me/garlick/proj/flux-core/src/bindings/lua/wreck.lua:237: in function 'ioattach'
        /home/garlick/proj/flux-core/src/cmd/flux-wreck:130: in function 'handler'
        /home/garlick/proj/flux-core/src/cmd/flux-wreck:105: in function 'run'
        /home/garlick/proj/flux-core/src/cmd/flux-wreck:263: in main chunk
        [C]: ?
```
whereas wreckrun handles it:
```
$ ./flux wreckrun hostname
wreckrun: Connecting to flux failed: Invalid argument
```

**Comment by grondo** [comment]
@garlick, thanks I'll fix the `flux wreck` error checking.

I also added `flux wreck ls` to list jobs because I needed it (and it was easy)

**Comment by grondo** [comment]
OK, pushed a fix for `flux wreck` error checking on `flux_open` failure.

Keep the bug reports coming. I'll write some minor tests for `flux wreck` commands (don't want to waste too much time on these short-lived utilities though), then rebase and probably this will be ready for merging..

Alternately, if you'd like I could rework the `wrexecd` plugins into something better which allows options exporting and gives each plugin a namespace in the kvs.

**Comment by garlick** [comment]
I'd be fine with deferring the plugin rework to a future PR if you like.

I was wondering if a `flux wreck ls -l` option might be useful, to include say program size, runtime, and whatever else is interesting and easy to grab?

**Comment by garlick** [comment]
Error handling for status on a nonexistent job also might need some attention:
```
$ ./flux wreck status 4
lua: /home/garlick/proj/flux-core/src/cmd/flux-wreck:35: bad argument #2 to 'format' (number expected, got nil)
stack traceback:
        [C]: in function 'format'
        /home/garlick/proj/flux-core/src/cmd/flux-wreck:35: in function 'eprintf'
        /home/garlick/proj/flux-core/src/cmd/flux-wreck:43: in function 'die'
        /home/garlick/proj/flux-core/src/cmd/flux-wreck:186: in function 'handler'
        /home/garlick/proj/flux-core/src/cmd/flux-wreck:105: in function 'run'
        /home/garlick/proj/flux-core/src/cmd/flux-wreck:263: in main chunk
        [C]: ?
```

**Comment by grondo** [comment]
> I was wondering if a flux wreck ls -l option might be useful, to include say program size, runtime, and whatever else is interesting and easy to grab?

Good point, that should be simple.. Runtime is a bit challenging with the stupid way wreck reports times, but for now I'll include size, start and endtime maybe command... It would be cool if mustache supported format specifiers then I could just allow a mustache template, but it doesn't seem viable...

**Comment by grondo** [comment]
> Error handling for status on a nonexistent job also might need some attention: 
Fixed, thanks! That was a typo in the arguments to `die()`

**Comment by garlick** [comment]
Maybe `flux wreck ls -l` could list the set of broker ranks that ran the job in compressed form?

**Comment by grondo** [comment]
> Maybe flux wreck ls -l could list the set of broker ranks that ran the job in compressed form?

Ok, I can try. ;-)

 For now would something like:
```
IDS          STATE   START  END  NTASKS RANKS  COMMAND
```

Actually maybe I should allow lines to be defined by a mustache template, with each key preformatted to take up a defined width. This way we could support any of the above keys
(and maybe a few more you think of)

**Comment by garlick** [comment]
Works for me, with or without template.  I don't want to delay getting this in but tacking on too much work.

I guess you wouldn't really want to compress `IDS` in the long output since at least the start and end times are likely to be different for every job (I say that because it was plural in your example).

**Comment by grondo** [comment]
I used IDS because I was thinking in terms of collecting identical lines of output wherever possible (start and end times currently only have second resolution so though unlikely, there *could* be identical likes), but for this little throwaway utility you're right it probably doesn't make sense to try too hard to compress output.

Is the `ls` short output even all that useful? Should we just have an `ls` that prints one job per line with (at least) fields above?

**Comment by garlick** [comment]
Sure, that works for me.

**Comment by grondo** [comment]
OK, something like this?
```
$ flux wreck ls
    ID NTASKS  STATE      START                 RUNTIME  RANKS    COMMAND
     1 32      complete   2015-10-05T16:21:08   1.024s   [0-3]    sleep
     2 24      complete   2015-10-05T17:17:18   0.046s   [0-3]    hostname
     3 2       complete   2015-10-05T17:17:30   0.015s   [0-1]    hostname

```
RUNTIME probably needs a tiny bit of work to output other times than seconds, but maybe this is ok for now?

**Comment by grondo** [comment]
I pushed up the above changes to `flux-wreck ls`, but keep in mind they're pretty well untested...

**Comment by garlick** [comment]
I like the long output, very nice.

**Comment by grondo** [comment]
Ok, I fixed some issues with the duration handling and tweaked the output in `flux-wreck ls` a little more, squashed all the little fixup commits together and forced an update.

**Comment by grondo** [comment]
Ok, basic tests for `flux wreck `*`cmd`* added and if there aren't any more bugs found or functionality changes requested this is probably ready to go in. (Maybe someone kick the tires a bit more just to make sure)

**Comment by garlick** [comment]
Just pulled this down and played around a bit and looks good to me.  Lets merge.

**Pull request merged**
