### PR TITLE
job-info: Add job-info.list-id and wait mechanism to work around eventual consistency

### PR DESCRIPTION
**Pull request by chu11**
Per discussion in #2592. This PR is on top of PR #2706 to wait for an ID to be seen by the `job-info` module so that eventual consistency raciness will not surprise potential callers.

The general strategy of this work:

- instead of returning EINVAL if the jobid passed in by the user is just unknown, lookup `job.<JOBID>` in the KVS and see if the job id is legal.  If it isn't, return EINVAL.

- If the ID is legal, but not yet seen by the job-info module job state transition events, create a hash of waiting IDs, when the jobid is finally seen and has reached FLUX_JOB_DEPEND, return the job information to the user.

- In addition, if the jobid passed to the user is legal and is in state FLUX_JOB_NEW, similarly wait for the state to become FLUX_JOB_DEPEND and then return a response back to the user

In order to test this all, add a `job-info.job-state-pause` and `job-info.job-state-unpause` RPC to the job info module.  When paused, the job-info module will *not* process any job state transitions, instead putting those messages onto a list.  When an unpause is done, process those transitions.

Question: Should I close #2706?  This PR isn't quite as big as I originally imagined it.  It's certainly not small, but it's not as gigantic as I had expected.

Side note: We'll see what the coverage looks like, I think the general "job id legal but job-info doesn't know about the job id" race is handled.  But the "job id legal and job in state FLUX_JOB_NEW" is harder to cover.

### CODE REVIEW

**Comment by garlick** [comment]
Two quick thoughts, just reading your description:
* Can use use the `flux module debug` hook instead of pause/unpause?  (might be simpler)
* Instead of a new hash, would it make sense to instantiate the real job hash entry, and then attach requests to a list hanging off the entry, so that it's one stop shopping when the job info gets filled in later?

**Comment by chu11** [comment]
> Can use use the flux module debug hook instead of pause/unpause? (might be simpler)

I was actually not aware of this.  It seems it could work.  I did a similar pause/unpause in the KVS for setroot, it might be worthwhile to look into using the debug in there as well.

> Instead of a new hash, would it make sense to instantiate the real job hash entry, and then attach requests to a list hanging off the entry, so that it's one stop shopping when the job info gets filled in later?

Hmmm.  I had not considered that.  While I did want to logically separate out the "wait" logic, now that I think about it, adding it to the main job hash entry won't be anywhere near as complex as I might have thought.  I'll look into trying this tomorrow.

**Comment by garlick** [comment]
> Hmmm. I had not considered that. While I did want to logically separate out the "wait" logic, now that I think about it, adding it to the main job hash entry won't be anywhere near as complex as I might have thought. I'll look into trying this tomorrow.

I meant that to be more of a "food for thought" idea, so if it's not a good one, feel free to nix it.

**Comment by chu11** [comment]
> I meant that to be more of a "food for thought" idea, so if it's not a good one, feel free to nix it.

Thinking about this more, it wouldn't be that complex to add.  However, I dislike the idea of a non-state transition (in this case list-id lookup) adding a job data structure to the main job hash.  It removes some abstraction that I'd like to keep.

I'll use the module debug flags though, since I was unaware of them existing.  Can use em in the KVS too (that's for another PR).

**Comment by chu11** [comment]
Hmmm, the address sanitizer builder failed with:

```
expecting success: 
        jobid=`flux mini submit hostname` &&
        echo $jobid > taskcount1.id &&
        flux job wait-event $jobid clean >/dev/null &&
        obj=$(flux job list -s inactive | grep $jobid) &&
        echo $obj | jq -e ".ntasks == 1"

flux-mini: ERROR: [Errno 71] Unrecoverable error: validator unexpectedly exited
not ok 42 - flux job list outputs ntasks correctly (1 task)
```

Which I think is #2718, which @grondo is handling in #2721.  Restarting, b/c I want to get coverage info on the code.

**Comment by chu11** [comment]
> I'll use the module debug flags though, since I was unaware of them existing. Can use em in the KVS too (that's for another PR).

No more than 60 seconds into working on a change, I realized there's an issue with using the debug bits here.  AFAICT, I can't "trigger" a pause/unpause with debug bits.  The debug bits are set and presumably are seen during normal operations.  This makes sense for "pausing", but I need the "unpause" to happen when I want it to happen.

So I think I'll leave that pause/unpause code in place for now.

**Comment by chu11** [comment]
rebased, I guess if I'm not rebased on master I can't get code coverage analysis

**Comment by grondo** [comment]
> rebased, I guess if I'm not rebased on master I can't get code coverage analysis

That shouldn't be true. However, sometimes the latest build on master fails (for many of the same reasons we see PRs fail) so master gets a "code coverage missing error"

You can always
```
$ ./configure --enable-code-coverage
$ make clean && make -j N check-code-coverage
```

To view the `lcov` output locally, i use the handy-dandy builtin python webserver:
```
$ python3 -m http.server
Serving HTTP on 0.0.0.0 port 8000 (http://0.0.0.0:8000/) ...
```

Then browse into the `flux-core-*coverage` directory

**Comment by grondo** [comment]
Ha, looks like codecov finally reported something here.

**Comment by chu11** [comment]
yeah, dunno why it took so long

**Comment by chu11** [comment]
argh, all the racy handling wasn't covered.   The background process in the tests races with the `unpause`.  For example, the sleep I put in below makes sure the race is hit.

```
test_expect_success HAVE_JQ,NO_CHAIN_LINT 'flux job list-ids waits for job ids (one id)' '                                                                   
        ${RPC} job-info.job-state-pause 0 </dev/null                                                                                                         
        jobid=`flux mini submit hostname`                                                                                                                    
        flux job wait-event $jobid clean >/dev/null                                                                                                          
        flux job list-ids ${jobid} > list_id_wait1.out &                                                                                                     
        pid=$!                                                                                                                                               
sleep 3                                                                                                                                                      
        ${RPC} job-info.job-state-unpause 0 </dev/null &&                                                                                                    
        wait $pid &&                                                                                                                                         
        cat list_id_wait1.out | jq -e ".id == ${jobid}"                                                                                                      
'        
```

I'll have to think about how to handle this.  Maybe I'll need some stat to be output from job-info so we can sychronize on it.

**Comment by chu11** [comment]
re-pushed, added some stats to avoid some of the racyness between the background process and unpause.

**Comment by chu11** [comment]
covered the racy bits I was hoping to get covered, so that's good.  Coverage isn't that great b/c there are two other racy paths that are hard to cover outside of very specific instrumentation:

1) the job id is not known to the job-info module, a KVS lookup is done to see if the job ID is legal, and by the time that returns the job id is known to the job-info module and we can return to the caller with valid job data.

2) the job id is legal / known to the job-info module, but the KVS lookup of FLUX_JOB_DEPEND data (userid, priority, etc.) has not yet completed.

At the moment I've decided that covering these two paths is probably not worth it.

**Comment by grondo** [comment]
Playing with this branch and it seems to work great!
Even survived this torture test: (immediately fetch info a series of jobs as soon as a jobid is available)
```python
import flux
from flux import job

attrs = ["state", "name", "t_submit"]
jobspec = job.JobspecV1.from_command(["sleep", "0"],
                                     num_tasks=1,
                                     cores_per_task=1)
def list_cb(f, arg):
    print(f.get())

def submit_cb(f, arg):
    jobid = job.submit_get_id(f)
    h.rpc("job-info.list-id", dict(id=jobid, attrs=attrs)).then(list_cb)
h = flux.Flux()
for i in range(100):
    job.submit_async(h, jobspec).then(submit_cb)

if h.reactor_run(h.get_reactor(), 0) < 0:
    h.fatal_error("reactor_run failed")
```

However, I am having one strange issue that I don't understand. I can't get `t2204-job-info.t` to complete under `FLUX_TEST_VALGRIND=t`, even if I extend the gracetime up to 5 minutes.
It appears that `rc3` is stuck in the call `flux queue idle`.

In the instance, 3 jobs seem to be stuck in CLEANUP:

```
$ flux jobs
             JOBID USER     NAME       STATE    NTASKS NNODES  RUNTIME RANKS
     2336629981184 grondo   hostname   CLEANUP       1      1   0.841s 2
     2320356081664 grondo   hostname   CLEANUP       1      1   1.664s 1
     2314450501632 grondo   hostname   CLEANUP       1      1   2.324s 0
```

I'm actually unsure if this is related to this PR, so I'll try again on master.

**Comment by grondo** [comment]
Ok, the second issue above is reproducible on master so I'll open an issue.

**Comment by chu11** [comment]
Awesome, actually, we should add your stress test into this PR.  I'll add an extra commit on top of this tree (the test will be `LONGTEST` of course)

**Comment by grondo** [comment]
> Ok, the second issue above is reproducible on master so I'll open an issue. 

I spoke too soon. The test on master works fine. (still had the gracetime set to 5 minutes, so the "hang" was really just the timer running down)

**Comment by chu11** [comment]
> I spoke too soon. The test on master works fine. (still had the gracetime set to 5 minutes, so the "hang" was really just the timer running down)

Let me look into this.

**Comment by grondo** [comment]
> Let me look into this.

Thanks. I can't really think of how job-info module changes could cause this hang in `flux queue idle`, so it may just be related to a new workload generated by added tests... If we can make a reproducer that fails on master that will be good.

Also should try rebasing this branch just to be sure.

**Comment by chu11** [comment]
> Awesome, actually, we should add your stress test into this PR. I'll add an extra commit on top of this tree (the test will be LONGTEST of course)

Woo hoo!  Your stress test actually hit an `assert()`, logic error in another racy path.

**Comment by grondo** [comment]
Ah, I think I see the problem I'm seeing in my local copy of this branch.

I don't think it is specific to this PR, but some combination of the workload introduced in `t2204-job-info.t` as a result of this PR, plus running under valgrind, is tickling an existing race condition in test cleanup with `test_under_flux job`.

Currently, `rc1-job` doesn't load `sched-simple` and `job-exec` modules, instead this is left to the sharness test, if scheduler and job execution are needed. Therefore, tests like `t2204-job-info.t` need to unload `job-exec` and `sched-simple` at test end to avoid the "module list of shame" when `test_under_flux` returns.

Thus when `rc3-job` tries to run `flux job cancelall -f --states RUN`, this will always fail since there is no `job-exec` module to receive the exception and kill the job. Therefore, the jobs will stay in CLEANUP forever.

To fix in this test, try adding 
```sh
flux job cancelall -f &&
flux queue idle
```

Before removing the job-exec module.

**Comment by chu11** [comment]
> To fix in this test, try adding

Was just about to add this to `t2204-job-info`, but `flux module remove` is in a bunch of tests:

```
t2201-job-cmd.t:        flux module remove job-exec &&
t2204-job-info.t:        flux module remove job-exec
t2205-job-info-security.t:        flux module remove job-exec
t2400-job-exec-test.t:  flux module remove job-exec
t2402-job-exec-dummy.t: flux module remove job-exec &&
t2602-job-shell.t:        flux module remove job-exec &&
t2606-job-shell-output-redirection.t:        flux module remove job-exec &&
t2607-job-shell-input.t:        flux module remove job-exec &&
t2800-jobs-cmd.t:        flux module remove job-exec
```

perhaps we should open and issue and do a follow up PR instead?

**Comment by grondo** [comment]
> perhaps we should open and issue and do a follow up PR instead?

Yeah, that's fine, I was in the midst of opening #2739 and I actually prefer the first solution proposed there.

**Comment by grondo** [comment]
Now that #2744 is proposed, I don't think there are any other outstanding issues I found with this PR when testing. Is it ready for a final review?

**Comment by chu11** [comment]
i was going through issues and forgot that I can close #2591 in this PR as well.  Added "Fixes #2591" to a commit message and rebased.  No code changes.

**Comment by chu11** [comment]
> Now that #2744 is proposed, I don't think there are any other outstanding issues I found with this PR when testing. Is it ready for a final review?

Yup, I think it's ready for final review.

**Pull request merged**
