### PR TITLE
libpmi: move some complexity to broker

### LINKED ISSUE #1789: libpmi: support multiple PMI sessions per rank
As noted in #1620, Flux's PMI library cannot support multiple sessions per rank.  This is required when parts of the application other than MPI (such as libpami.so in the aforementioned issue)  want to use PMI independently.

The Flux PMI server (embedded in `wrexecd`) creates a socketpair per rank, and passes the client end to the MPI task using `PMI_FD`.  This is a robust and low-overhead way to offer PMI service since it bypasses the need for per-client `accept(2)` in the server, does not need authentication, and allows MPI to avoid problems opening the correct `libpmi.so` if it speaks PMI-1 wire protocol, as MPICH-derived MPI's do.

The flux `libpmi.so` uses PMI_FD if set to connect when `PMI_Init()` is called.  This means only one task/thread per rank can call `PMI_Init()` when linked against our `libpmi.so`.  If another task tries it, likely the both PMI sessions will get confused and protocol errors will result.

The FLUX PMI server could offer a UNIX domain socket that `PMI_Init()` could connect to.   It could use SO_PEERCRED authentication to ensure the user running `wrexecd` is the same as the client.  The client would need to announce its rank if the socket is shared across multiple ranks per node (See MPICH hydra - I think there's an unused PMI-1 wire protocol message for this, and another environment variable to communicate the socket path).

Since there is no "handle" associated with `PMI_Init()`, each client session would need to be in a different process or thread (check that all state is thread-local though).

### PR DESCRIPTION
**Pull request by garlick**
(This needs some more tests but wanted to park it publicly since I'll be out until June 10)

This is a refactoring of the Flux PMI-1 code after the realization that it would be easier to reason about our `libpmi.so` if it was only used by jobs launched by Flux, not by the Flux broker.   The Flux broker needs to not only bootstrap under Flux, but under SLURM, potentially other resource managers, and standalone.  Jobs launched by Flux, however, just need to use Flux's preferred method (PMI-1 wire protocol).

As such, `libpmi.so` is now only a simple PMI-1 wire protocol client.  If PMI_FD, PMI_RANK, and PMI_SIZE are not set, this fails.  The code formerly in `libpmi.so` to also try dlopening() SLURM's `libpmi.so` or falling back to singleton operation is now in the broker.  Since it doesn't need to be a faithful PMI-1 ABI, it is quite a bit simpler.

Edit: removing this, see comment below:
> Finally, `libpmi.so` is now thread safe, in the coarsest way possible - by spinlock.  This, in combination with a usecount incremented by `PMI_Init()` and decremented by `PMI_Finalize()`,  should allow e.g. a PAMI thread and an OpenMPI thread in one process to independently make PMI-1 calls without scrambling the wire protocol.  Fixes #1789.

I have a client implementation of the PMI_PORT (TCP) connection method that I didn't add to this PR.  It had a ways to go on the server side, and I think the changes proposed above ought to be sufficient for the spectrum use case described.   (We might have other uses for PMI_PORT but it may not need to be in this PR).

### CODE REVIEW

**Comment by garlick** [comment]
Just thought of a couple of problems that this lock won't fix.

If thread 1 calls `PMI_Init()` ... `PMI_Finalize()` then thread 2 tries to call `PMI_Init()`, the finalize will already have decremented the usecount to zero and closed the file descriptor.  OK, we could just leave the file descriptor open indefinitely since we didn't open it, but is that reasonable?

If both threads attempt barriers, since the barriers are "anonymous" (unnamed), the barrier entries from the two threads could be co-mingled, causing a premature barrier exit.  This is a more serious problem, and we know that it will happen in the PAMI use case.

I think the PMI_PORT solution is required in order to solve #1789 after all.  I'll go ahead and back out the lock and usecount on the global PMI context.  Sigh.

**Comment by garlick** [comment]
> If both threads attempt barriers, since the barriers are "anonymous" (unnamed), the barrier entries from the two threads could be co-mingled, causing a premature barrier exit. This is a more serious problem, and we know that it will happen in the PAMI use case.

Argh.  PMI_PORT won't fix this.  Barriers are still anonymous.  There may not be a way to map that PMIx usage onto PMI-1.

**Comment by garlick** [comment]
I'll try to get a little more test coverage going this evening (when I get to my hotel) and then try to wrap this up as general PMI cleanup.  As evidenced by issues like #2170, anything that makes what's happening easier to understand (in code and/or behavior) is probably useful.

**Comment by garlick** [comment]
I think this might be close to ready now that the coverage is decent.

I did try to test it on ipa before I left town, but due to lack of free nodes, was only able to check that an instance did dlopen the slurm ibpmi.so (in singleton mode), not that an instance could be launched under slurm.  If someone had a chance to give that a quick try I'd appreciate it.

Some squashing is needed before this can be merged.

**Comment by grondo** [comment]
I can try it on fluke, unless there is something special about api vs our dedicated test cluster? (If so we should get that fixed)

**Comment by garlick** [comment]
I didn't try - sorry, was hurrying up to leave and thought of ipa first.

Hmm, I wonder if it would be feasible to add a conditionally run sharness test for this and then bring up a slurm instance in one of our docker containers for travis?

**Comment by grondo** [comment]
> Hmm, I wonder if it would be feasible to add a conditionally run sharness test for this and then bring up a slurm instance in one of our docker containers for travis?

That is a great idea. I can look into that.

**Comment by dongahn** [comment]
> Hmm, I wonder if it would be feasible to add a conditionally run sharness test for this and then bring up a slurm instance in one of our docker containers for travis?

Being able to bring up a slurmy instance in the Travis CI can help our debugging tools tested better as well. This can be a multi-purpose item. We have a long standing issue https://github.com/LLNL/LaunchMON/issues/25. Tagging @lee218llnl.

**Comment by grondo** [comment]
@garlick, what am I looking for in testing with Slurm? I can launch a Flux instance under Slurm on your branch. With `FLUX_PMI_DEBUG` set, the brokers report `lt-flux-broker: using PMI-1 wire protocol`.
Is that sufficient?

fluke is running slurm 18.08.6-2

**Comment by garlick** [comment]
Good enough. Thanks!

**Comment by garlick** [comment]
Squashed.  I'd  be OK if this went in, if it looks OK.

**Comment by grondo** [comment]
This looks great! Further testing showed some leaks in the test pmi server thread. Not at all critical, but this patch closes the leaks:
```diff
diff --git a/src/common/libpmi/test/server_thread.c b/src/common/libpmi/test/server_thread.c
index 8485e3f..2a10cd1 100644
--- a/src/common/libpmi/test/server_thread.c
+++ b/src/common/libpmi/test/server_thread.c
@@ -147,6 +147,7 @@ static void *server_thread (void *arg)
         BAIL_OUT ("flux_reactor_run failed");
     for (i = 0; i < ctx->size; i++)
         flux_watcher_destroy (w[i]);
+    free (w);
     flux_reactor_destroy (reactor);
     return NULL;
 }
@@ -205,6 +206,7 @@ void pmi_server_destroy (struct pmi_server_context *ctx)
     pmi_simple_server_destroy (ctx->pmi);
     zhashx_destroy (&ctx->kvs);
     ctx->magic = ~MAGIC_VALUE;
+    free (ctx->sfd);
     free (ctx);
 }
 
```

**Comment by garlick** [comment]
Good catch! If you want to push that to my branch and then merge that
would be great!

**Comment by garlick** [comment]
(or I will incorporate that this evening when I get back to my laptop)

**Comment by garlick** [comment]
Pulled in @grondo's fix, rebased on current master, and squashed.

**Comment by grondo** [comment]
Great! Merging.

**Comment by garlick** [comment]
Thanks!

**Pull request merged**
