### PR TITLE
Ats fixes

### PR DESCRIPTION
**Pull request by trws**
This is an aggregation of small single-file commits with fixes required for the ATS backend to behave properly.  The LRU cache item only comes up when the cache size is exceeded, so it may be worth adding a test for that.

### CODE REVIEW

**Comment by grondo** [comment]
Thanks @trws! and sorry about that lame lru bug! I'll create a test (thought I had already, duh!) and push it here. 

Meanwhile, I hate to do this to you but the commit messages here should be fixed up to our commit message style (See [RFC1: Patch Requirements](https://github.com/flux-framework/rfc/blob/master/spec_1.adoc#patch-requirements))

**Comment by trws** [comment]
No problem, I kinda threw them in last night to get it going through travis.  I'll fix them up and rebake the other PR as soon as I get back to my desktop.




On November 22, 2016 at 9:31:44 AM PST, Mark Grondona <notifications@github.com> wrote:

Thanks @trws<https://github.com/trws>! and sorry about that lame lru bug! I'll create a test (thought I had already, duh!) and push it here.

Meanwhile, I hate to do this to you but the commit messages here should be fixed up to our commit message style (See RFC1: Patch Requirements<https://github.com/flux-framework/rfc/blob/master/spec_1.adoc#patch-requirements>)

-

**Comment by grondo** [comment]
@trws, I'm probably missing something simple, but if you have a chance can you give me more details on the reproducer for the move-to-front lru bug? The current test case is pretty simple, but it does create a cache of size 5 and adds 10 items, so the cache size is exceeded. It then continually touches the first item added so it *should* be continually moved back to the front of the list.

I assume I'm missing some corner case still.

**Comment by trws** [comment]
@grondo unfortunately I don't have a small reproducer for the issue, just using sched to run 256+ jobs did it consistently.  The result of the issue was that the count would be full, but the actual list would be empty.  I think the pattern was a mix of using the most recent and cycling through all of the rest as they were accessed for state updates, but haven't dug in far enough to create a good reproducer.

@garlick, I don't think there was an actual problem with the old code... that's the especially odd part.  It only comes up when using an allocator other than the default linux malloc, and it looks like what happens when the default malloc is used to get a piece of memory that's then passed to the free of tcmalloc or jemalloc or what have you.  Why it appeared there, and only there, and not somewhere else that shortjson is used I can't say.

Truth be told, I'm not sure I hit the root cause of the issue, but the failure was always in that Jput, and it completely disappeared after the change.

**Comment by trws** [comment]
Rebased with each commit reworded.

**Comment by grondo** [comment]
> The result of the issue was that the count would be full, but the actual list would be empty. 

Thanks @trws that is a good hint, and again I apologize for sloppy code.

**Comment by grondo** [comment]
> > The result of the issue was that the count would be full, but the actual list would be empty.
>
> Thanks @trws that is a good hint, and again I apologize for sloppy code.

I verified that `test/lru_cache.c` *is* reproducing this issue, however, there is no mechanism in place to ensure the lru queue/list doesn't get out of sync with `lru->count`, so the corruption goes uncaught.

I did find that the real error here was that this line was missing from the end of `lru_entry_remove`. Without it there are dangling links back into the list. Oops, total rookie mistake.

```C
    /* Re-initialized prev/next pointers to NULL */
    l->prev = l->next = NULL;
```

Your changes make the code clearer I think so they could stay in but we should add this fix on top as well, otherwise the internal list gets corrupted.

I'm still working on a test that fails under the lru_cache unit test -- might have to add a `lru_cache_verify()` or other sanity check function to actually walk the list

**Comment by garlick** [comment]
@trws if you don't mind, please update the unsubscribe handler in the local connector as well and drop the shortjson.h include.

**Comment by trws** [comment]
Sure, I'll make those changes as soon as I am get back to flux.




On November 22, 2016 at 3:18:31 PM PST, Jim Garlick <notifications@github.com> wrote:

@trws<https://github.com/trws> if you don't mind, please update the unsubscribe handler in the local connector as well and drop the shortjson.h include.

-

**Comment by grondo** [comment]
@trws, hope you don't mind I pushed some test additions and extra fixes to lru_cache here directly onto your PR. If you'd like them split off, go ahead and rebase without them.

In order to write a failing case for this issue, I had to add a `lru_cache_selfcheck()` function to check for corruption in the LRU list, compare number of items in the list vs `lru->count` etc. I then added a very specific reproducer for the corruption you encountered.

Even with your fix the selfcheck fails, so the missing reset of a removed item before re-insertion is required and should have always been there.

Finally, a small optimization to do nothing when an entry at the front of the list is "requeued" was added.

**Comment by trws** [comment]
Not at all. I'm glad you found the root cause, and more so for the tests. Thanks @grondo!




On November 22, 2016 at 10:09:14 PM PST, Mark Grondona <notifications@github.com> wrote:

@trws<https://github.com/trws>, hope you don't mind I pushed some test additions and extra fixes to lru_cache here directly onto your PR. If you'd like them split off, go ahead and rebase without them.

In order to write a failing case for this issue, I had to add a lru_cache_selfcheck() function to check for corruption in the LRU list, compare number of items in the list vs lru->count etc. I then added a very specific reproducer for the corruption you encountered.

Even with your fix the selfcheck fails, so the missing reset of a removed item before re-insertion is required and should have always been there.

Finally, a small optimization to do nothing when an entry at the front of the list is "requeued" was added.

-

**Comment by trws** [comment]
Rebased. Also popped in something that's been bugging me for a bit, added the intermediate xml files from doc building into the gitignore for in-tree builds.

**Comment by grondo** [comment]
I probably should not be eligible to merge this one, @chu11, @morrone, @lipari, or @dongahn want to do a quick review of this and merge if OK? I think @garlick is not available today.

**Comment by chu11** [comment]
everything looks good to me, hitting the big button

**Pull request merged**
