### PR TITLE
add dlopen RTLD_DEEPBIND flag

### PR DESCRIPTION
**Pull request by garlick**
This is an attempt to solve flux-framework/flux-sched#211

Not sure if this is the right approach, discussion continues in the issue.

### CODE REVIEW

**Comment by garlick** [comment]
Probably shouldn't have posted this in fact.  I'm getting some test failures, e.g.
```
jimbo:~/proj/flux-core/src/broker > ./test_shutdown.t
1..11
ok 1 - shutdown_encode works
ok 2 - shutdown_decode works
not ok 3 - opened loop connector
#   Failed test 'opened loop connector'
#   at test/shutdown.c line 59.
Bail out!  can't continue without loop handle
```

**Comment by grondo** [comment]
Does this need to be rebased on current master?

**Comment by garlick** [comment]
Yes it does.  Wow, what was I doing yesterday.

**Comment by garlick** [comment]
The test failure above was actually due to my running the broker unit tests from within a running instance that had since been removed.  The test would try to load the loop module from the other instance's lib directory.

I rebased and fixed a problem in the "live" module that cropped up.  This is passing tests on my desktop.  Let's see how it does in travis.

**Comment by grondo** [comment]
This works in my environment as well. Nice work, and sorry about the optparse shortcoming!

This also allows *most* flux-sched tests to pass after removing `.la` files after install and setting `LD_LIBRARY_PATH` appropriately (I wonder if we should do this in the `flux` command driver, like we do for `PATH`?)

I'm now only getting a failure here:
```
expecting success: 
    diff -u ${expected_order} ./actual

--- /home/ubuntu/flux-sched/t/data/emulator-data/easy_expected  2016-08-12 17:05:26.000000000 +0000
+++ ./actual    2016-10-13 17:19:05.533150759 +0000
@@ -1,12 +1,12 @@
 1
 2
 3
+4
+5
 6
 7
 8
 9
 10
 11
-4
-5
 12
not ok 5 - jobs scheduled in correct order
#
#           diff -u ${expected_order} ./actual
#

```

**Comment by garlick** [comment]
Just submitted flux-framework/flux-sched#212 which adds RTLD_DEEPBIND to sched's module loading code.  I wonder if that might have something to do with the above failure?

**Comment by grondo** [comment]
> Just submitted flux-framework/flux-sched#212 which adds RTLD_DEEPBIND to sched's module loading code. I wonder if that might have something to do with the above failure?

I tried again using your flux-sched `deepbind` branch and still get the same failure.

**Comment by garlick** [comment]
Rebased and added post-install hook to remove .la files.  Just need to find where to place LD_LIBRARY_PATH setting in sched test scripts, and see what's up with the above easy_exected test failure.

**Comment by garlick** [comment]
Just pushed a commit to flux-framework/flux-sched#212 which sets LD_LIBRARY_PATH in `.travis.yml` is that a reasonable place to do it?

**Comment by grondo** [comment]
> Just pushed a commit to flux-framework/flux-sched#212 which sets LD_LIBRARY_PATH in .travis.yml is that a reasonable place to do it?

Fine with me!

**Comment by garlick** [comment]
OK, I backed that last commit out since it broke distcheck.

**Comment by garlick** [comment]
I think with sched's travis.yml setting LD_LIBRARY_PATH and removing the installed flux-core .la files, we are OK, modulo the failing test.  Want to merge this and sort out the test separately?

**Comment by grondo** [comment]
Ok, looks good now.

**Comment by garlick** [comment]
Thanks!

**Pull request merged**
