### PR TITLE
Globally rename "administrative priority" to "urgency"

### PR DESCRIPTION
**Pull request by chu11**
Per RFC21 update (https://github.com/flux-framework/rfc/pull/277) the "administrative priority" has been renamed to "urgency".

Globally update flux-core for this change.  This is built on top of the cleanup PR #3392.

Needless to say from looking at the commit list below, I did this slowly, so I would not mess up too much along the way.  I could merge some of the smaller neighboring commits to reduce the total number.  Or could do 1 giant change?

Ultimately, this change is what it is.  A list of the changes:

- `FLUX_JOB_ADMIN_PRIORITY` ->  `FLUX_JOB_URGENCY`
- Rename `flux job submit --priority` option to `--urgency`
- Rename `flux job priority` to `flux job urgency`
- Rename `flux mini submit --priority` option to `--urgency`
- Rename  `job-manager.priority` target to `urgency` and rename files and such.
- Rename `admin-priority` event to `urgency`
- Rename `priority` parameters in job submit and scheduler protocols to `urgency`
- Rename all `priority` context fields in `submit` events to `urgency`
- Rename all job listing of `priority` to `urgency` in job-info, job-manager, and `flux-jobs`
- Generally speaking update comments & variable names throughout

and hopefully I got everything :P

a `flux-sched` equivalent coming as well

### CODE REVIEW

**Comment by garlick** [comment]
I'll hold off reviewing this one until #3392 and #3371 go in and this gets rebased, if that makes sense.

**Comment by chu11** [comment]
rebased & re-pushed, fixing up a few "admin priority" -> "urgency" and "queue priority" -> "priority" that occurred upstream.

I'm contemplating just making this one giant commit.  Would that be easier / better?

**Comment by chu11** [comment]
re-pushed, previously made a mistake, sched protocol (RFC27) did not change "priority" -> "urgency". I was confusing it with the future priority plugin.

**Comment by garlick** [comment]
I'm fine either way - small commits or large commits.

One thing I wanted to point out was we had discussed renaming `flux job priority` (the command) to `flux job update` and in #3391.  Should we go ahead and do that here rather than rename to `flux job urgency` and then again laster?

**Comment by chu11** [comment]
> One thing I wanted to point out was we had discussed renaming flux job priority (the command) to flux job update and in #3391. Should we go ahead and do that here rather than rename to flux job urgency and then again later?

It seemed that #3391 was also considering a style change, `flux job update` would allow the user to configure multiple fields vs just the urgency.  So I figure that should be for a future PR.

I'll go ahead and squash everything into one giant commit.

**Comment by grondo** [comment]
I agree that two separate PRs: 
 * rename priority to urgency 
 * replace `flux job priority` with `flux job update`

Makes sense for the strategy of doing one thing in a PR, and for the release notes.

**Comment by grondo** [comment]
This PR will have to be manually merged since it breaks flux-sched, unless you want to keep a `flux job priority` command for backwards compatibility, then update flux-sched, then remove compat command (probably not worth it at this early stage in development, but a process we may have to use in the future)

**Comment by chu11** [comment]
re-pushed 1 giant commit

**Review by garlick — APPROVED** [review]
OK then!  Looks good to me - not much to argue about, which i guess was the goal!

**Comment by garlick** [comment]
I'm OK with a manual merge here if you're ready @chu11.  I assume we'll be able to follow on shortly with the sched one.

**Comment by chu11** [comment]
> I'm OK with a manual merge here if you're ready @chu11. I assume we'll be able to follow on shortly with the sched one.

yup, the sched one is all ready to go.

**Comment by garlick** [comment]
Hmm, that check is required and merge button is grayed out.  Might need a hint from @grondo on how to get this merged.

**Comment by grondo** [comment]
Oh, sorry, that is because of Github "branch protections". You have to go in and manually remove the required status check, merge, then re-enable it. I can do that now.

**Comment by grondo** [comment]
Ok, done. Thanks @chu11!

**Comment by garlick** [comment]
Thanks!

**Pull request merged**
