### PR TITLE
kvs: Rename internal "commit" API to "kvstxn" API

### PR DESCRIPTION
**Pull request by chu11**
Per discussion in #1344.  I originally was going to do a lot more work before sending in a PR, but there were more "mini cleanups" to do a long the way than I realized, so I think it's a good stopping point for a PR.  Per discussion in the issue, this PR handles the first bullet point I listed.

> the "internal commit API" should be renamed to "transactions".

I chose to name the api ```kvstxn```, as I wanted to differentiate this as not the normal "txn" API, as special things like merges and what not can occur.

### CODE REVIEW

**Comment by chu11** [comment]
Since this hasn't been merged yet, I went ahead and pushed my changes to the "fence" data structure.  This handles bullet #2.

> the "internal fence API" should be renamed to something TBD

The TBD I chose was "treq", standing for transaction request.  I chose this instead of "txnreq" b/c with the "kvstxn" API, I thought have the word "txn" all over the place was a bit confusing.

Just like renaming the "commit" API, there were all these side cleanups I had to do as well.

**Comment by chu11** [comment]
Oops, noticed one place I forgot to rename a variable.  Went ahead and squashed it into the PR & repushed.

**Comment by chu11** [comment]
restarted a builder, hit #731

**Comment by garlick** [comment]
Looks straightforward.  I'll go ahead and merge.  Thanks!

**Pull request merged**
