### PR TITLE
doc/man1/flux-module.adoc: Document -x option

### PR DESCRIPTION
**Pull request by chu11**

### CODE REVIEW

**Comment by chu11** [comment]
Technically ```all``` is supported by ```--exclude``` too.  But elected not to document since it's sort of a degenerate case.

**Comment by grondo** [comment]
@chu11, If you have more than 1 manpage fixup I wonder if it would make more sense to collect them all in one PR, instead of a single PR per fix.

**Comment by chu11** [comment]
@grondo You're probably referring to #854?  I had intended to fixup the "rank=all" across everything in a different PR.  This one seemed a bit independent of that one.

**Comment by chu11** [comment]
hmm, jstat unit tests are failing in travis. Is this a known issue in the travis build?

**Comment by garlick** [comment]
There is #512.  is that the failure you are seeing?

**Comment by chu11** [comment]
@garlick yup, that's the one.  Lets give it one more run, third times a charm :-)

**Comment by grondo** [comment]
> You're probably referring to #854? I had intended to fixup the "rank=all" across everything in a different PR. This one seemed a bit independent of that one.

I was more considering that as you're currently going through commands and manpages you might have more than one man page fix over time, and instead of 1 PR for each fix we could kind of stage them all in one PR to reduce master branch merge commit noise.

However, that being said I don't feel too strongly about it and if you are more comfortable with doing it this way it is fine with me

**Comment by chu11** [comment]
Actually, given my latest comment on #854, I'll just fold this into a bigger cleanup overall.  So I'll just nix this PR.

**Pull request closed without merging**
