### PR TITLE
doc: add flux-jobs(1) examples

### PR DESCRIPTION
**Pull request by chu11**
i elected not to cut & paste example output, as that can always change as we update things.  Figured the sample command line options were enough.

Could add more ... ???

### CODE REVIEW

**Review by grondo — APPROVED** [review]
Nice! I think this will be very helpful and it seems like a good starting list of examples that show the breadth of what could be done with flux-jobs.

I would just suggest that the commit titles be changed to be consistent. (Personally I don't feel with need to waste space with `doc/man1/flux-jobs.rst:` label since the commit itself explicitly tells you what files changed. Instead I'd tag each commit with simply `doc: ` and have the rest of the title reference the change to `flux-jobs(1)` manpage)

**Comment by chu11** [comment]
@grondo thanks!  i've re-pushed with tweaked commit titles

**Comment by chu11** [comment]
oh and i tweaked an example as the text did not perfectly match the example "all jobids for the user" should go with the `-a` option not `-A`.  (I could have instead tweaked the text to "all jobids of all users").

**Review by grondo — APPROVED** [review]
Great, LGTM!

**Pull request merged**
