### PR TITLE
t2204-job-info: Split up tests into new files

### PR DESCRIPTION
**Pull request by chu11**
Nothing too fancy, the test file had become the longest file in the testsuite, and there's bound to be more job-listing features in the future.

Note that I could have created a "helper" script to put some of the common helper functions in, but the helper code is small enough that it didn't quite seem worthwhile to do the "helper" script.

### CODE REVIEW

**Comment by grondo** [comment]
There's some whitespace issues in the new tests, though it hardly matters and maybe they were there before anyway. I'll leave it up to you if you'd like to fix.

It also would have been nice to update some of the test methodology, e.g. one spot where a job is launched to take up all resources so another job gets queued (could be updated to use `flux queue stop`), etc. However, that could all be done in the future as well (I realize the main intent here is to let a long test run in parallel)

**Comment by chu11** [comment]
> It also would have been nice to update some of the test methodology, e.g. one spot where a job is launched to take up all resources so another job gets queued (could be updated to use flux queue stop), etc. However, that could all be done in the future as well (I realize the main intent here is to let a long test run in parallel)


Good idea, let me make an issue so I don't forget.

**Comment by chu11** [comment]
hmmm one builder failed, seems to be new.  Possibly racy?  Or in one case some profiling extra krutt became an issue. Gonna restart builder since it's not related to this PR.

```
FAIL: t2602-job-shell.t 14 - job-shell: verify output of 1-task lptest job on stderr

FAIL: t2602-job-shell.t 16 - job-shell: verify output of 4-task lptest job on stderr
```

and

```
FAIL: t2606-job-shell-output-redirection.t 26 - job-shell: job attach exits cleanly if no kvs output (1-task)

FAIL: t2606-job-shell-output-redirection.t 27 - job-shell: job attach exits cleanly if no kvs output (2-task)
```

details

```
expecting success: 
        id=$(flux jobspec srun -n1 bash -c "${LPTEST} >&2" \
		| flux job submit) &&
	flux job attach -l $id 2>lptest.err &&
        sed -i -e "/stdin EOF could not be sent/d" lptest.err &&
	test_cmp lptest.exp lptest.err

profiling:/usr/src/src/common/libeventlog/.libs/libeventlog_la-eventlog.gcda:Merge mismatch for function 7
profiling:/usr/src/src/common/libeventlog/.libs/libeventlog_la-eventlog.gcda:Merge mismatch for function 7
profiling:/usr/src/src/common/libeventlog/.libs/libeventlog_la-eventlog.gcda:Merge mismatch for function 7
profiling:/usr/src/src/common/libeventlog/.libs/libeventlog_la-eventlog.gcda:Merge mismatch for function 7
profiling:/usr/src/src/common/libeventlog/.libs/libeventlog_la-eventlog.gcda:Merge mismatch for function 7
--- lptest.exp	2020-05-27 20:05:31.907141648 +0000
+++ lptest.err	2020-05-27 20:05:33.035144766 +0000
@@ -1,3 +1,6 @@
+0: profiling:/usr/src/src/common/libeventlog/.libs/libeventlog_la-eventlog.gcda:Merge mismatch for function 7
+0: profiling:/usr/src/src/common/libeventlog/.libs/libeventlog_la-eventlog.gcda:Merge mismatch for function 7
+0: profiling:/usr/src/src/common/libeventlog/.libs/libeventlog_la-eventlog.gcda:Merge mismatch for function 7
 0: !"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmno
 0: "#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnop
 0: #$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopq
@@ -198,3 +201,6 @@
 0: *+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwx
 0: +,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxy
 0: ,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz
+profiling:/usr/src/src/common/libeventlog/.libs/libeventlog_la-eventlog.gcda:Merge mismatch for function 7
+profiling:/usr/src/src/common/libeventlog/.libs/libeventlog_la-eventlog.gcda:Merge mismatch for function 7
+profiling:/usr/src/src/common/libeventlog/.libs/libeventlog_la-eventlog.gcda:Merge mismatch for function 7
not ok 14 - job-shell: verify output of 1-task lptest job on stderr



expecting success: 
        id=$(flux jobspec srun -N4 bash -c "${LPTEST} 1>&2" \
		| flux job submit) &&
	flux job attach -l $id 2>lptest4_raw.err &&
	sort -snk1 <lptest4_raw.err >lptest4.err &&
        sed -i -e "/stdin EOF could not be sent/d" lptest4.err &&
	test_cmp lptest4.exp lptest4.err

profiling:/usr/src/src/common/libeventlog/.libs/libeventlog_la-eventlog.gcda:Merge mismatch for function 7
profiling:/usr/src/src/common/libeventlog/.libs/libeventlog_la-eventlog.gcda:Merge mismatch for function 7
profiling:/usr/src/src/common/libeventlog/.libs/libeventlog_la-eventlog.gcda:Merge mismatch for function 7
profiling:/usr/src/src/common/libeventlog/.libs/libeventlog_la-eventlog.gcda:Merge mismatch for function 7
profiling:/usr/src/src/common/libeventlog/.libs/libeventlog_la-eventlog.gcda:Merge mismatch for function 7
--- lptest4.exp	2020-05-27 20:05:31.959141792 +0000
+++ lptest4.err	2020-05-27 20:05:35.067150349 +0000
@@ -1,3 +1,6 @@
+0: profiling:/usr/src/src/common/libeventlog/.libs/libeventlog_la-eventlog.gcda:Merge mismatch for function 7
+0: profiling:/usr/src/src/common/libeventlog/.libs/libeventlog_la-eventlog.gcda:Merge mismatch for function 7
+0: profiling:/usr/src/src/common/libeventlog/.libs/libeventlog_la-eventlog.gcda:Merge mismatch for function 7
 0: !"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmno
 0: "#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnop
 0: #$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopq
@@ -198,6 +201,12 @@
 0: *+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwx
 0: +,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxy
 0: ,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz
+profiling:/usr/src/src/common/libeventlog/.libs/libeventlog_la-eventlog.gcda:Merge mismatch for function 7
+profiling:/usr/src/src/common/libeventlog/.libs/libeventlog_la-eventlog.gcda:Merge mismatch for function 7
+profiling:/usr/src/src/common/libeventlog/.libs/libeventlog_la-eventlog.gcda:Merge mismatch for function 7
+1: profiling:/usr/src/src/common/libeventlog/.libs/libeventlog_la-eventlog.gcda:Merge mismatch for function 7
+1: profiling:/usr/src/src/common/libeventlog/.libs/libeventlog_la-eventlog.gcda:Merge mismatch for function 7
+1: profiling:/usr/src/src/common/libeventlog/.libs/libeventlog_la-eventlog.gcda:Merge mismatch for function 7
 1: !"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmno
 1: "#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnop
 1: #$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopq
@@ -398,6 +407,9 @@
 1: *+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwx
 1: +,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxy
 1: ,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz
+2: profiling:/usr/src/src/common/libeventlog/.libs/libeventlog_la-eventlog.gcda:Merge mismatch for function 7
+2: profiling:/usr/src/src/common/libeventlog/.libs/libeventlog_la-eventlog.gcda:Merge mismatch for function 7
+2: profiling:/usr/src/src/common/libeventlog/.libs/libeventlog_la-eventlog.gcda:Merge mismatch for function 7
 2: !"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmno
 2: "#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnop
 2: #$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopq
@@ -598,6 +610,9 @@
 2: *+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwx
 2: +,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxy
 2: ,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz
+3: profiling:/usr/src/src/common/libeventlog/.libs/libeventlog_la-eventlog.gcda:Merge mismatch for function 7
+3: profiling:/usr/src/src/common/libeventlog/.libs/libeventlog_la-eventlog.gcda:Merge mismatch for function 7
+3: profiling:/usr/src/src/common/libeventlog/.libs/libeventlog_la-eventlog.gcda:Merge mismatch for function 7
 3: !"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmno
 3: "#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnop
 3: #$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopq
not ok 16 - job-shell: verify output of 4-task lptest job on stderr
```

```
expecting success: 
        id=$(flux mini submit -n1 \
             --output=out25 --error=err25 \
             ${TEST_SUBPROCESS_DIR}/test_echo -P -O -E baz) &&
        flux job wait-event $id clean &&
        flux job attach -q ${id} > out25.attach 2> err25.attach &&
        grep stdout:baz out25 &&
        grep stderr:baz err25 &&
        ! test -s out25.attach &&
        sed -i -e "/stdin EOF could not be sent/d" err25.attach &&
        ! test -s err25.attach

profiling:/usr/src/src/common/libeventlog/.libs/libeventlog_la-eventlog.gcda:Merge mismatch for function 7
profiling:/usr/src/src/common/libeventlog/.libs/libeventlog_la-eventlog.gcda:Merge mismatch for function 7
profiling:/usr/src/src/common/libeventlog/.libs/libeventlog_la-eventlog.gcda:Merge mismatch for function 7
1590609957.643612 clean
profiling:/usr/src/src/common/libeventlog/.libs/libeventlog_la-eventlog.gcda:Merge mismatch for function 7
profiling:/usr/src/src/common/libeventlog/.libs/libeventlog_la-eventlog.gcda:Merge mismatch for function 7
profiling:/usr/src/src/common/libeventlog/.libs/libeventlog_la-eventlog.gcda:Merge mismatch for function 7
stdout:baz
stderr:baz
not ok 26 - job-shell: job attach exits cleanly if no kvs output (1-task)

expecting success: 
        id=$(flux mini submit -n2 \
             --output=out26 --error=err26 \
             ${TEST_SUBPROCESS_DIR}/test_echo -P -O -E baz) &&
        flux job wait-event $id clean &&
        flux job attach -q ${id} > out26.attach 2> err26.attach &&
        grep stdout:baz out26 &&
        grep stderr:baz err26 &&
        ! test -s out26.attach &&
        sed -i -e "/stdin EOF could not be sent/d" err26.attach &&
        ! test -s err26.attach

profiling:/usr/src/src/common/libeventlog/.libs/libeventlog_la-eventlog.gcda:Merge mismatch for function 7
profiling:/usr/src/src/common/libeventlog/.libs/libeventlog_la-eventlog.gcda:Merge mismatch for function 7
profiling:/usr/src/src/common/libeventlog/.libs/libeventlog_la-eventlog.gcda:Merge mismatch for function 7
1590609958.152675 clean
profiling:/usr/src/src/common/libeventlog/.libs/libeventlog_la-eventlog.gcda:Merge mismatch for function 7
profiling:/usr/src/src/common/libeventlog/.libs/libeventlog_la-eventlog.gcda:Merge mismatch for function 7
profiling:/usr/src/src/common/libeventlog/.libs/libeventlog_la-eventlog.gcda:Merge mismatch for function 7
stdout:baz
stdout:baz
stderr:baz
stderr:baz
not ok 27 - job-shell: job attach exits cleanly if no kvs output (2-task)
```

**Comment by grondo** [comment]
Asan builder hung too so I restarted it.

**Pull request merged**
