### PR TITLE
t/t2000-wreck.t: Fix invalid compare on per-task affinity test

### PR DESCRIPTION
**Pull request by chu11**
Found similar invalid compare just like #836

### CODE REVIEW

**Comment by garlick** [comment]
Looks like the test error you found was masking some other problem with the test.  Running the test with your fix and --verbose on my desktop:
```

--- expected_cpus2	2016-10-07 16:12:02.474234574 +0000
+++ output_cpus2	2016-10-07 16:12:02.474234574 +0000
@@ -1,2 +1,2 @@
 0: Cpus_allowed_list:	0
-1: Cpus_allowed_list:	0-11
+1: Cpus_allowed_list:	0-63
not ok 32 - wreckrun: supports per-task affinity assignment
#	
#		mask=$(cpus_allowed) &&
#		newmask=$(cpus_allowed first) &&
#		run_timeout 5 flux wreckrun -ln2 \
#		  --pre-launch-hook="lwj[\"0.cpumask\"] = \"$newmask\"" \
#		  grep ^Cpus_allowed_list /proc/self/status | sort > output_cpus2 &&
#		cat <<-EOF >expected_cpus2 &&
#		0: Cpus_allowed_list:	$newmask
#		1: Cpus_allowed_list:	$mask
#		EOF
#		test_cmp expected_cpus2 output_cpus2
#	
```

**Comment by grondo** [comment]
Hm, the problem above is that the apparent default cpus_allowed list in the script is only `0-11` but the wreckrunned task had a cpus_allowed list of `0-63` (unless I misinterpret diff output). What is the cpumask of the shell from which you are running the tests?

**Comment by garlick** [comment]
```
jimbo:~ > grep ^Cpus_allowed_list /proc/self/status
Cpus_allowed_list:	0-63
```

**Comment by grondo** [comment]
Hm, perhaps a bug in `scripts/cpus-allowed.lua` or the cpuset lua bindings then (or perhaps somewhere previous in the script we reset our own cpus allowed mask). In any event I'm taking a look at it.

**Comment by grondo** [comment]
Ok, I've noticed that `sched_getaffinity()` could return a different Cpus list than `Cpus_allowed`, which  appears can be a superset of actual available CPUs. On hype for instance I see:
```
$ grep Cpus_allowed_list /proc/self/status
Cpus_allowed_list:	0-239
$ t/scripts/cpus-allowed.lua 
0-31
```

Which is an additional failure mode for this test. I think the fix is to use the `cpus_allowed.lua` script for *both* expected and job output, e.g. something like:

```diff
diff --git a/t/t2000-wreck.t b/t/t2000-wreck.t
index fac8e14..e460762 100755
--- a/t/t2000-wreck.t
+++ b/t/t2000-wreck.t
@@ -200,32 +200,30 @@ test_expect_success 'wreckrun: -t1 -n${SIZE} sets nnodes i
        test "$n" = "${SIZE}"
 '
 
-cpus_allowed() {
-       ${SHARNESS_TEST_SRCDIR}/scripts/cpus-allowed.lua "$@"
-}
+cpus_allowed=${SHARNESS_TEST_SRCDIR}/scripts/cpus-allowed.lua
 test "$(cpus_allowed count)" = "0" || test_set_prereq MULTICORE
 
 test_expect_success MULTICORE 'wreckrun: supports affinity assignment' '
-       newmask=$(cpus_allowed last) &&
+       newmask=$($cpus_allowed last) &&
        run_timeout 5 flux wreckrun -n1 \
          --pre-launch-hook="lwj.rank[0].cpumask = \"$newmask\"" \
-         grep ^Cpus_allowed_list /proc/self/status > output_cpus &&
+         $cpus_allowed > output_cpus &&
        cat <<-EOF >expected_cpus &&
-       Cpus_allowed_list:      $newmask
+       $newmask
        EOF
        test_cmp expected_cpus output_cpus
 '
 test_expect_success MULTICORE 'wreckrun: supports per-task affinity assignment'
-       mask=$(cpus_allowed) &&
-       newmask=$(cpus_allowed first) &&
+       mask=$($cpus_allowed) &&
+       newmask=$($cpus_allowed first) &&
        run_timeout 5 flux wreckrun -ln2 \
          --pre-launch-hook="lwj[\"0.cpumask\"] = \"$newmask\"" \
-         grep ^Cpus_allowed_list /proc/self/status | sort > output_cpus2 &&
+         $cpus_allowed | sort > output_cpus2 &&
        cat <<-EOF >expected_cpus2 &&
-       0: Cpus_allowed_list:   $newmask
-       1: Cpus_allowed_list:   $mask
+       0: $newmask
+       1: $mask
        EOF
-       test_cmp expected_cpus output_cpus
+       test_cmp expected_cpus2 output_cpus2
 '
 test_expect_success 'wreckrun: top level environment' '
        flux kvs put lwj.environ="{ \"TEST_ENV_VAR\": \"foo\" }" &&
```

This works on hype, but I'm not sure about jimbo

**Comment by garlick** [comment]
Just verified the above does work on jimbo.

Minor but I think
```
test "$(cpus_allowed count)" = "0" || test_set_prereq MULTICORE
```
should be
```
test "$($cpus_allowed count)" = "0" || test_set_prereq MULTICORE
```

**Comment by grondo** [comment]
Yeah, good catch, I went a bit too fast. @chu11 want to append those changes to this PR?

**Comment by chu11** [comment]
@grondo  Sure, do you have a branch to pull from?

**Comment by grondo** [comment]
I didn't push the change anywhere, sorry. I can do that after lunch if you
still need it

**Comment by chu11** [comment]
@grondo Nah, just thought you had it somewhere and would be easier.  I can just integrate the patch.

**Comment by chu11** [comment]
Just merged.  Verified everything passes on atleast hype2 & apex

**Comment by garlick** [comment]
Looks good!  Thanks Al.

**Pull request merged**
