### PR TITLE
Subprocess io

### PR DESCRIPTION
**Pull request by grondo**
This PR contains very basic IO support for the subprocess code, plus support for output from `flux-exec` spawned processes (no stdin handling yet)

For now, subprocess code only supports tying to zloop-based reactors (to be fixed), and there is some weirdness with zio based callbacks calling subprocess-based callbacks which should probably be eventually fixed. 

However, for now I wanted to propose this basic support for discussion. Still todo is to have IO messages flow back through tree so lines of output could possibly be subject to reduction (same thing for process exit status too I suppose). In this PR output messages are simply sent as replies to the original request.

### CODE REVIEW

**Comment by garlick** [comment]
Quick initial feedback:

Just tried some commands like `flux exec -l cat /etc/passwd | dshbak -c` on 64 nodes of hype and got expected results!  Looks like remote command exit status is properly returned

One thing I noticed that may not be quite right:  I wrote a little program that calls abort().  When run under the shell I get:
```
bash-4.1$ ~/abort
Aborted (core dumped)
bash-4.1$ echo $?
134
```
when run under flux-exec I get
```
bash-4.1$ ./flux exec -r 42 ~/abort
bash-4.1$ echo $?
0
```
although a core was generated.  Should that look more like the shell?

Maybe not important right now but flux-exec(1) needs an update to reflect these changes.  Also add -l and rename "cmbd" to "flux-broker".

**Comment by garlick** [comment]
@grondo should there be a C interface for interacting with the broker's execution service in libflux-core?

**Comment by grondo** [comment]
@garlick -- yes signal exit code should be communicated back to `flux-exec` so this is a bug. I'll add some tests and a fix to this PR.

There should eventually be a C interface, but I wasn't sure yet what it might look like. I was actually thinking perhaps the existing API in `subprocess.c` could be used, but enhanced to allow `subprocess_fork/exec` to be targetted to any rank.

Also I was thinking perhaps we could take another look at the basic execution service and maybe develop an RFC for the json format of its messages. I wonder what you think about that.

**Comment by garlick** [comment]
A yes vote on the RFC.  [JSON content rules](https://tools.ietf.org/html/draft-newton-json-content-rules-04)  worked out pretty well in [RFC 5](https://github.com/flux-framework/rfc/blob/master/spec_5.adoc) IMHO.

The subprocess API looks well thought out, though kind of complicated for simple uses.

I don't think either an RFC or API design should hold up this PR though.

**Comment by garlick** [comment]
@grondo I'd be happy to merge this once the travis failure is resolved, if you think it's ready.

**Comment by grondo** [comment]
Yeah, this might take awhile to resolve as it appears to be an intermittent hang in the jsc tests (didn't happen when testing on my branch: https://travis-ci.org/grondo/flux-core)

I also think I'd better at least add `flux-exec(1)` manpage changes you noted.

I have mixed feelings if this PR as is should be merged. I think if there is a use case for it, it is probably functional enough to go in (e.g. to be used in tests). However, there are some key pieces missing, e.g.
 * process management (e.g. signal forwarding)
 * alternate IO/status message implementation that uses tree for reduction
 * library interface as suggested by @garlick

**Comment by garlick** [comment]
I think I,can enhance a number of tests with this capability.  I think if
it is solid it should go in.

Jim

**Comment by grondo** [comment]
FYI, I locally rebased this branch onto current master 3cf0f9afd50ceaf2112991004b8661a4dd7df549
and now wreckrun is spinning without exiting at the end of every run.

Quick inspection reveals that the reactor is waking up and trying to read from and eventfd, which fails with `EAGAIN`, and we do this in a loop *ad infinitum*.

Adding some printf debug reveals we're constantly trying to run `msglist.c:clear_event` without really making any progress.

I've no doubt I've somehow introduced a bug here, but I thought I'd ping @garlick to see if he had any quick tips. Meanwhile I'll keep poking.

**Comment by garlick** [comment]
@grondo could you maybe push your rebased branch here so I can grab it and have a look?

**Comment by grondo** [comment]
Ok, I've forced an update of my branch, though I'd hate to make you look for something that is clearly my bug. I'll keep poking, it is possible the msglist thing is a red herring.

**Comment by grondo** [comment]
@garlick, tracked the `flux-wreckrun` hanging issue down to eof not written to kz file in kvs. Probably broke wrexecd/zio interface with some of my recent changes.

The spinning inside the reactor is another issue, possibly a side effect of the kzio issue. Not sure at this point. I'm going to run down this wreck bug. Sorry.

**Comment by garlick** [comment]
I'm trying to run down the spinning handle.  Something is definitely not right there (should have told you it looked like my problem earlier)

**Comment by grondo** [comment]
Ok, I found that commit ff5ea1c broke wrexecd zio handling because callbacks can inadvertently return -1 (hurrah for `git bisect`).  I'll push a commit to revert the behaviour to always return 0 as it was before. (to be fixed later I suppose)

I can still recreate the spinning handle with `flux wreckrun sleep 1000`

**Comment by garlick** [comment]
I found it, an epoll problem in the local connector.  It would always spin after the first time it was ready, but generally only short lived utilities use that connector so it wasn't really noticeable in testing.  Sheesh!

PR coming shortly.

**Comment by grondo** [comment]
Strangely, travis didn't rebuild this PR with the most recent commit. However, the latest fix has introduced a **new** hang, this time in the forkzio code. I'll poke at that tomorrow.

**Comment by grondo** [comment]
Ah, found the other issue. Maybe the reactor changed to exit on error for any non-zero return code from a fdhandler? Before I thought it was  only `< 0`. (not sure though)

```C
static void fd_compat_cb (flux_t h, flux_fd_watcher_t *w,
                          int fd, int revents, void *arg)
{
    struct fd_compat *c = arg;
    if (c->fn (h, fd, events_to_libzmq (revents), c->arg) != 0)
        flux_reactor_stop_error (h);
}
```

I *think* this was the old fdhandler callback handler handler:
```C
static void fd_cb (struct ev_loop *loop, ev_io *w, int revents)
{
    afd_t *f = (afd_t *)((char *)w - offsetof (afd_t, w));
    ctx_t *c = w->data;
    assert (c->magic == CTX_MAGIC);

    if (f->cb (c->h, w->fd, etoz (revents), f->arg) < 0)
        op_reactor_stop (c, -1);
}
```

I think I inadvertently have zio read callbacks returning the number of bytes read in some cases with recent changes.

This is easy to fix on my end, there is no reason a callback should be returning `> 0` here, but for principle of lease surprise do you think the `!= 0` should be changed to `< 0`? (I don't have a strong feeling either way, but figured you might have a reason)

**Comment by garlick** [comment]
Oh sorry about that.  The libcompat interface should exactly mimic what was there before.  The new reactor callbacks return void, so to stop the reactor you would explicitly call `flux_reactor_stop()` or `flux_reactor_stop_error()`

**Comment by garlick** [comment]
pr #244 addresses the libcompat oversight.

**Comment by grondo** [comment]
Ok, I was getting a linker error, but only on libtool/binutils combination in travis gcc builder.

Got that sorted and now I've rebased onto current master f45d11, removed the hack to only return 0 or -1 from callbacks, so we'll see if travis can finally build clean.

still todo
 * clean up subprocesses when flux-exec detaches from session
 * doc update for flux-exec(1)

**Comment by grondo** [comment]
Ok, I've rebased against current master 5c7808547afed62b934862073a5f4276ba7edb20 and additionally added support for forwarding signals with `flux-exec` -- currently `SIGINT` and `SIGTERM` -- to all remote running processes along with tests. So you can now Ctrl-C out of `flux-exec`

I have experimental support for auto-kill of subprocesses belonging to given sender on receipt of `cmb.disconnect` message, but so far in my testing this message only makes it to rank 0? More testing needed...

**Comment by garlick** [comment]
The cmb.disconnect hack works like this:  the api module tracks the services a client is sending requests to.  When the api client disconnects, it walks through this list of services and sends a disconnect message to them.  So only the exact addresses that a client has sent requests to (directly) will get the disconnect messages.

We could think about changing how that works if it's not sufficient here.

**Comment by grondo** [comment]
By services you mean only the topic string? In order to target ranks on which to execute, 'flux-exec' targets nodeids directly. Would it be easy and/or recommended to also save target nodeid in disconnect notify hash?

**Comment by garlick** [comment]
Yeah it definitely should be added.  When I made that comment, I was just thinking of indirect vs direct communication (e.g. reduction, forwarding).  However, looking at the code, you are right the nodeid is missing and this should be fixed.

**Comment by grondo** [comment]
Ok, I can take a stab at this, but something tells me you're already on it.

**Comment by garlick** [comment]
I'm on it.   That was a bad oversight back when the protocol was redesigned for RFC 3.  I opened #261 to track.

**Comment by grondo** [comment]
Ok, I could push my current implementation which terminates all subprocesses matching uuid of disconnecting api user. However, I'm a bit worried this is a bit heavy-handed as every subprocess currently running has to be checked on every disconnect from the `cmb` service (which might be very often). If you have other ideas on how to do this more subtly, let me know.

**Comment by grondo** [comment]
Ok, I just pushed my current implementation of subprocess "cleanup" on disconnect for review in this PR.

**Comment by grondo** [comment]
Rebased on current master 163f37d90878d683517a7ef22642a589bd9ad998

I did a quick test of the `terminate_subprocess_by_uuid()` functionality with the fix for #261 (works now!), but still need to add a good test.

**Comment by grondo** [comment]
Another update:
 * rebased against master 76197e60763ed3e99304769684fbed4dceb7fa19
 * Add new service `cmb.processes` to query local subprocess managed by a broker
 * Add `flux-ps` utility as frontend for `cmb.processes` process listing
 * Expand `t0005-exec.t` tests with tests for `flux-ps` and use use `flux-ps` to ensure disconnect terminates all subprocesses with `flux-exec`

I'm not so sure about the `flux-ps` name, since it is such a low-level command. If anyone has another idea I'm willing to change it (though, probably higher level program listing commands will lend themselves to a different name anyway)

 I'm also a little worried about adding more overhead to the broker main thread, though the longer term plan is to make subprocess management into a distributed service, in which case request and query tools will likely communicate through a purpose-built module.

**Comment by grondo** [comment]
example of `flux-ps` -- nothing to shout about:
```
 grondo@hype356:~/git/f$ src/cmd/flux start --size=4
lt-flux-broker: [1436664999.179584] broker.info[0] nodeset: [0-3] (complete)
lt-flux-broker: [1436664999.179683] broker.info[0] starting shell
(flux-194357-0) grondo@hype356:~/git/f$ src/cmd/flux exec sleep 100 &
[1] 194549
(flux-194357-0) grondo@hype356:~/git/f$ src/cmd/flux ps
OWNER                                RANK       PID  COMMAND
local                                   0    194522  /bin/bash
BC6C5E8461F04BF0847E5D3D46C7E042        0    194564  sleep
BC6C5E8461F04BF0847E5D3D46C7E042        3    194565  sleep
BC6C5E8461F04BF0847E5D3D46C7E042        2    194566  sleep
BC6C5E8461F04BF0847E5D3D46C7E042        1    194567  sleep
(flux-194357-0) grondo@hype356:~/git/f$ killall -9 flux-exec
[1]+  Killed                  src/cmd/flux exec sleep 100
(flux-194357-0) grondo@hype356:~/git/f$ src/cmd/flux ps
OWNER                                RANK       PID  COMMAND
local                                   0    194522  /bin/bash
```

Notes: `flux-ps` shows broker-local instantiated subprocesses, but maybe it shouldn't?
I didn't worry about it too much since the command is really only for testing at this point.

**Comment by garlick** [comment]
That looks pretty neat.  So how are you feeling about merging this?

**Comment by grondo** [comment]
This could probably be merged now, if there are no objections to the `flux-ps` and `cmb.processes` names?

**Comment by garlick** [comment]
I'm OK with those names.

On the flux-ps "OWNER" column, would "initial-program" or "init" be clearer than "local"?  

In other places we've abbreviated UUID's to the first 5 characters.  That would open up some space for more columns later on.

**Comment by grondo** [comment]
Good feedback, thanks. There might be other broker initiated subprocesses
in the future so "init" might not work in general. We could skip processes
without an associated sender or use "none" or something? (Open to anything
here)

I'll shorten uuids to 5 chars.

**Comment by dongahn** [comment]
+1 on flux-ps. and +1 on merging. 

Commands like this are something that users often ask for debugging and monitoring. As an example, merge-by column feature would be extremely useful for quick diagnostics at scale. merge-by command first and then stat will identify outliners very easily at large scale, for instance. 

command stat rank ...
mympi      R    0-63, 127
mympi      Z    64 

Other examples:  merge-by command followed by memory usage (/proc/pid/status) or function name (/proc/pid/stat + addr2line --function -- although accessing shared file system by addr2line would be non-scalable...) would also be useful. 

BTW, there are  folks out there who look at creating  parallel tools using MRNet like parallel top. 
http://ftp.cs.wisc.edu/par-distr-sys/papers/Brim09GroupFile.pdf
http://www.researchgate.net/publication/254003598_FINAL_flexible_and_scalable_composition_of_file_system_name_spaces

**Comment by garlick** [comment]
"none" sounds perhaps better than "local".

I like @dongahn's idea about reduced output, but I hate to delay this PR any longer as it will be very cool to have for building tests.  Could that be an enhancement issue for later?

**Comment by dongahn** [comment]
Sorry, this was just an random idea and didn't mean to delay the PR at all!

**Comment by garlick** [comment]
I thought it was a good idea.  I opened #267 to make sure we remember.

**Comment by grondo** [comment]
Yes, I think support for this will naturally fall out of moving subprocess
management to a distributed mechanism and using reduction to collect
responses to process listing back to rank0. (Though it is pretty easy to
hack something up is `flux-ps` as it is by hashing results as they arrive
[akin to dshbak], but I didn't worry about it too much since `flux-ps` is
designed as debug tool not scalable tool)

**Comment by grondo** [comment]
Ok @garlick, I've updated `flux-ps` as you suggested.
```
(flux-208161-0) grondo@hype356:~/git/f$ src/cmd/flux ps 
OWNER     RANK       PID  COMMAND
none         0    208326  /bin/bash
9CA74        0    208421  sleep
9CA74        3    208422  sleep
9CA74        2    208423  sleep
9CA74        1    208424  sleep
```

i.e. OWNER is "none" for subprocesses not instantiated by `cmb.exec`, and sender uuid truncated to 5 chars by default.

`flux-ps` is currently only a debug/test tool. I can think of many other improvements that could be made before we merge this PR, but for now I'm trying to focus on basic functionality for our test framework.

I think if we turn `exec` into a distributed service some of the features discussed above will naturally fall out of that work.

**Comment by garlick** [comment]
This is looking really good to me.  Big step forward.  I'm going to merge this.

**Pull request merged**
