### PR TITLE
Docker travis

### PR DESCRIPTION
**Pull request by trws**
We have a docker hub organization and two images with GCC 8 and clang 6 respectively set up with all of our dependencies for use on travis.  Running on my loft laptop, there are issues with a couple of the sharness tests, but they look like race conditions caused by a slow laptop, so this may or may not work out of the box, but I need to see what travis does with it to debug further.

The change in the basic test is because if the inner flux gets killed in just the right timing it can return non-zero even if the full run succeeded.

### CODE REVIEW

**Comment by grondo** [comment]
That change in the t0001-basic.t test will unfortunately cause a failure in the `--chain-lint` tests. Maybe there is another workaround?

Travis was slower than any laptop I've ever seen :stuck_out_tongue_winking_eye:, so if we find some race conditions in the tests we can fix them here.

Also I guess you didn't catch discussion in #1648 where I had created a `fluxframework` organization on Docker Hub. However, I'm fine with the more concise `fluxrm`. Thanks for doing this!

**Comment by trws** [comment]
There almost certainly is another solution, but I was having trouble parsing through the issue to find it.  All of the tests using `test_under_flux` were working perfectly, but the test for `test_under_flux` was failing.  

The main one giving me grief was the flux cron event min-interval test, which was failing non-deterministically on my local machine.  Now on travis I seem to be hitting #997 every time, with both compilers.  Since the test doesn't print the value on failure, I don't know what the result actually is, but the print just before it implies it should be succeeding. 😕 

I did miss that, sorry 🙈.

**Comment by trws** [comment]
By the way, if you would be willing to take a crack at working out some of the actual test issues, that would be immensely helpful.  I have all of the deps in the image, but only installed one version of lua for now, and I don't think I included a valgrind.  If you'd like I can add those, or we can add a target that uses our `--enable-sanitizer` flag to run all the tests for one of the recent gcc or clang builds with address sanitizer.

**Comment by trws** [comment]
Ok, I added valgrind and tweaked things a bit so now it seems to be down to some test issues.  Particularly #997 seems to deterministically break on travis now, though it doesn't in the exact same image on my laptop.  Will be leaving this alone probably for the rest of the US workday for a poster session etc.

**Comment by grondo** [comment]
> Heh, LOFT laptop running a docker image in a hyperkit VM while doing other work is... it's a pretty low bar. 

Ha! Yeah I guess so! :laughing: 

> By the way, if you would be willing to take a crack at working out some of the actual test issues, that would be immensely helpful. I have all of the deps in the image, but only installed one version of lua for now, and I don't think I included a valgrind. If you'd like I can add those, or we can add a target that uses our --enable-sanitizer flag to run all the tests for one of the recent gcc or clang builds with address sanitizer.

Yeah, I'm totally willing to help.

We'll need images with flux-security built in as well. I was wondering if we should tackle that project first, and then upload a docker image with flux-security support as the "base" image for flux-core.

We'll also need to add a version of Caliper to an image to be able to test with `--enable-caliper`.

> If you'd like I can add those, or we can add a target that uses our --enable-sanitizer flag to run all the tests for one of the recent gcc or clang builds with address sanitizer.

I'm not that familiar with address sanitizer, if it can give us the same or more feedback than valgrind, I'm all for it, but for static analysis tools, I've usually found in the past that all the false positives make those kinds of tools a huge effort.

> but only installed one version of lua for now

This is a tricky one. For travis I found `hererocks` to be very helpful in having two versions of Lua installed, however for "official" Docker images going with Lua 5.2 is the right approach. I'm actually wondering if we should just stop testing 5.1 until/if we start updating the Lua bindings again (I think the real world, long term usefulness of the Lua bindings given that nobody wants to use them is questionable, except perhaps in specific embedding cases which we have not implemented yet.)

**Comment by dongahn** [comment]
> I'm not that familiar with address sanitizer, if it can give us the same or more feedback than valgrind, I'm all for it, but for static analysis tools, I've usually found in the past that all the false positives make those kinds of tools a huge effort.

@grondo: ASan is a dynamic analysis tool so this shouldn't have lots of false positives. In terms of the future of code-correctness checkers, Sanitizers are more and more viable on future systems and valgrinds are less and less. We don't have Valgrind on Sierra but Sanitizer. I can tell you the behind story offline.

**Comment by trws** [comment]
The only false positives I’ve ever gotten from asanwere  actually from lsan, spurious complaints of leaks for known memory regions not freed before program exit. Main thing is it would let us memory check all of our tests rather than a small subset since the built code runs much faster that way than under valgrind.

As to Lua, Debian and Ubuntu allow installs of 5.1,2,3 simultaneously without any additional fiddling if we want that, I just didn’t know that until after I built the original base image.

Does the flux security stuff have different requirements from flux core?




On September 11, 2018 at 5:10:34 PM GMT+1, Dong H. Ahn <notifications@github.com> wrote:

I'm not that familiar with address sanitizer, if it can give us the same or more feedback than valgrind, I'm all for it, but for static analysis tools, I've usually found in the past that all the false positives make those kinds of tools a huge effort.

@grondo<https://github.com/grondo>: ASan is a dynamic analysis tool so this shouldn't have lots of false positives. In terms of the future of code-correctness checkers, Sanitizers are more and more viable on future systems and valgrinds are less and less. We don't have Valgrind on Sierra but Sanitizer. I can tell you the behind story offline.

**Comment by grondo** [comment]
> Does the flux security stuff have different requirements from flux core?

None I can think of (except maybe `munge`, `libmunge-dev` at least is required for flux-core).

**Comment by grondo** [comment]
Just as a note: also missing in the docker image is PMIx library for builds with `--with-pmix`

**Comment by trws** [comment]
Aha, that’s a good one. I think I got munge as a rep for libmunge-dev, but I’ll put PMIx on the list.




On September 11, 2018 at 5:47:33 PM GMT+1, Mark Grondona <notifications@github.com> wrote:

Just as a note: also missing in the docker image is PMIx library for builds with --with-pmix

**Comment by trws** [comment]
Docker images have been updated, the new version has the munge utility, pmix, and the pmi1 and pmi2 compatibility libraries built against pmix.  The lua 5.1 listing is apparently non-real, we're a bit stuck with 5.2 unless we want to build a 5.1.

**Comment by grondo** [comment]
> The lua 5.1 listing is apparently non-real, we're a bit stuck with 5.2 unless we want to build a 5.1.

Well, we could do what we were doing before and use the `hererocks` utility to install both Lua 5.1 and 5.2. Like I said I'm not sure if we need to test with 5.1 anymore. We were also talking about creating a Centos 7 docker image to test building with something closer to TOSS 3, and we'd get Lua 5.1 sanity check that way as way.

**Comment by trws** [comment]
That makes sense. I can throw together a base for that too if you want. Are any of the rpms we use on toss3 for flux reps available somewhere? It would be great to just install those and have something right on.




On September 12, 2018 at 5:45:26 PM GMT+1, Mark Grondona <notifications@github.com> wrote:

The lua 5.1 listing is apparently non-real, we're a bit stuck with 5.2 unless we want to build a 5.1.

Well, we could do what we were doing before and use the hererocks utility to install both Lua 5.1 and 5.2. Like I said I'm not sure if we need to test with 5.1 anymore. We were also talking about creating a Centos 7 docker image to test building with something closer to TOSS 3, and we'd get Lua 5.1 sanity check that way as way.

**Comment by grondo** [comment]
> That makes sense. I can throw together a base for that too if you want. Are any of the rpms we use on  toss3 for flux reps available somewhere? It would be great to just install those and have something 
 right on.

Yes, they should be available under `/repo/toss` on any production cluster.

**Comment by grondo** [comment]
@trws: here's some changes I'm working with on your original Dockerfile to reduce size and get some of the deps for flux-security package. Still todo (unless I missed it in your recent changes) would be to build and install Caliper.

I removed ninja-build since it didn't seem to be required, and let the yaml-cpp pull in its own requirements instead of all of libboost, which seemed to reduce the amount of packages required greatly.
`uuid-dev` and `libsodium-dev` are required for the flux-security build. Ideally, we'll eventually have a flux-security docker image, but for now, the Dockerfile builds and installs flux-security to `prefix=/usr`.

```diff
diff --git a/src/test/docker/bionic-base/Dockerfile b/src/test/docker/bionic-base/Dockerfile
index cd312cd4..158e10c2 100644
--- a/src/test/docker/bionic-base/Dockerfile
+++ b/src/test/docker/bionic-base/Dockerfile
@@ -12,12 +12,11 @@ RUN apt-get update \
             sudo \
             git \
             vim \
+            pkg-config \
             dh-autoreconf \
-            ninja-build \
             autotools-dev \
             autoconf \
             libtool \
-            libboost-all-dev \
             libyaml-cpp-dev \
             libmunge-dev \
             munge \
@@ -39,6 +38,8 @@ RUN apt-get update \
             clang-tidy \
             ccache \
             valgrind \
+            libsodium-dev \
+            uuid-dev \
  && rm -rf /var/lib/apt/lists/*
 
 RUN luarocks install luaposix
@@ -59,6 +60,14 @@ RUN apt-get update \
 RUN rm /usr/lib/x86_64-linux-gnu/pmix/lib/libpmix.so \
  && ln -s /usr/lib/x86_64-linux-gnu/pmix/lib/libpmix.so.2 /usr/lib/x86_64-linux-gnu/pmix/lib/libpmix.so 
 
+# Install flux-security by hand for now:
+RUN wget https://github.com/flux-framework/flux-security/releases/download/v0.2.0/flux-security-0.2.0.tar.gz \
+ && tar xvfz flux-security-0.2.0.tar.gz \
+ && cd flux-security-0.2.0 \
+ && ./configure --prefix=/usr \
+ && make -j 4 \
+ && sudo make install
+
 RUN useradd -ms /bin/bash flux \
  && printf "flux:flux" | chpasswd \
  && adduser flux sudo \

```

**Comment by trws** [comment]
Cool, I’ll integrate that. The ninja thing was an accidental holdover from the raja original, with a cmake build it can be a good deal faster than the male backend. If we’re going to maintain a separate image for sched we can pull boost out, it was mainly in there for that.

I think the most recent update just about solved it, all but two of the Travis builds pass.

On Sep 13, 2018, at 3:59 PM, Mark Grondona <notifications@github.com<mailto:notifications@github.com>> wrote:


@trws<https://github.com/trws>: here's some changes I'm working with on your original Dockerfile to reduce size and get some of the deps for flux-security package. Still todo (unless I missed it in your recent changes) would be to build and install Caliper.

I removed ninja-build since it didn't seem to be required, and let the yaml-cpp pull in its own requirements instead of all of libboost, which seemed to reduce the amount of packages required greatly.
uuid-dev and libsodium-dev are required for the flux-security build. Ideally, we'll eventually have a flux-security docker image, but for now, the Dockerfile builds and installs flux-security to prefix=/usr.

diff --git a/src/test/docker/bionic-base/Dockerfile b/src/test/docker/bionic-base/Dockerfile
index cd312cd4..158e10c2 100644
--- a/src/test/docker/bionic-base/Dockerfile
+++ b/src/test/docker/bionic-base/Dockerfile
@@ -12,12 +12,11 @@ RUN apt-get update \
             sudo \
             git \
             vim \
+            pkg-config \
             dh-autoreconf \
-            ninja-build \
             autotools-dev \
             autoconf \
             libtool \
-            libboost-all-dev \
             libyaml-cpp-dev \
             libmunge-dev \
             munge \
@@ -39,6 +38,8 @@ RUN apt-get update \
             clang-tidy \
             ccache \
             valgrind \
+            libsodium-dev \
+            uuid-dev \
  && rm -rf /var/lib/apt/lists/*

 RUN luarocks install luaposix
@@ -59,6 +60,14 @@ RUN apt-get update \
 RUN rm /usr/lib/x86_64-linux-gnu/pmix/lib/libpmix.so \
  && ln -s /usr/lib/x86_64-linux-gnu/pmix/lib/libpmix.so.2 /usr/lib/x86_64-linux-gnu/pmix/lib/libpmix.so

+# Install flux-security by hand for now:
+RUN wget https://github.com/flux-framework/flux-security/releases/download/v0.2.0/flux-security-0.2.0.tar.gz \
+ && tar xvfz flux-security-0.2.0.tar.gz \
+ && cd flux-security-0.2.0 \
+ && ./configure --prefix=/usr \
+ && make -j 4 \
+ && sudo make install
+
 RUN useradd -ms /bin/bash flux \
  && printf "flux:flux" | chpasswd \
  && adduser flux sudo \

**Comment by grondo** [comment]
At least the one valgrind error I see is probably a new false positive for suppression. Strange that I don't see it in my build environment.

Exporting the LUA_VERSION should not be required anymore.

I also noticed the coverage tester isn't working, I haven't had time to look, but it appears `make check-code-coverage` isn't run. I can look into it after our meeting today.

**Comment by trws** [comment]
That would be great. It’s also possible there’s an issue with make running in the container and the coverage processing running out of it. In the raja one I think we have our codecov stuff in the script in the container, so that may be a simple fix but I haven’t played with it yet.


One thing on the valgrind error, I don’t see anywhere that the flux security object in the overlay gets destroyed. It may be just a false positive, but the object holding the zactor it’s talking about seems to be left unfreed on my local vm.

On September 13, 2018 at 4:50:43 PM GMT+1, Mark Grondona <notifications@github.com> wrote:

At least the one valgrind error I see is probably a new false positive for suppression. Strange that I don't see it in my build environment.

Exporting the LUA_VERSION should not be required anymore.

I also noticed the coverage tester isn't working, I haven't had time to look, but it appears make check-code-coverage isn't run. I can look into it after our meeting today.

**Comment by grondo** [comment]
Ok, here's a list of other things I was going to work on related to the PR. @trws, let me know if you are already tackling some of these

 * Install the dummy `<flux/core.h>` into the docker image itself (either manually with `docker run`) so we continue to ensure no built sources inadvertently reference installed includes.
 * Remove Coverity build for now. It can't work as-is since travis VM won't have Flux dependencies, and I"m not sure if it would work inside of docker since it is a Travis "add-on". Get rid of the encrypted scan token as well (This has the benefit of simplifying a lot of the logic that avoiding building more than once for Coverity runs)
 * Now that @trws has thankfully moved the build commands from `.travis.yml` to a `travis_run.sh` script, take an opportunity to clean up the script so it actually makes sense (this might allow many of the environment variables passed into docker to be dropped as unnecessary)
 * Re-evaluate the build matrix -- we really just want to test with
     - gcc8: ./configure with no args
     - gcc8: coverage: ./configure --with-flux-security --with-pmix --enable-caliper --enable-pylint --enable-code-coverage
     - clang6: (probably just need one build here with all --with options enabled) +sanitizer?
     - gcc8: TEST_INSTALLED 
     - cppcheck (we could just add this as a step to one of the other builders?)
     - chain_lint (bundle with one of the other builders?)
 * Verify that automated release uploads still works


Finally, it would be really nice if we could keep some Docker images up to date on Docker Hub, e.g.
`fluxrm/core:latest`, `fluxrm/core:0.10`, etc.. Then the travis tests for projects that use flux-core could just pull `fluxrm/core` to test against master, or optionally use a tag. We could also explore doing something similar for `flux-security` since in the near future that software may be a quickly moving target...Just an idea

**Comment by trws** [comment]
That all sounds good, and I haven't directly worked on any of it.  I did look into how we could build a docker image with the built flux, but it will likely take a bit of refactoring to get there.

As to adding cppcheck and chain_lint on one of the existing ones by the way, I think that's a good idea, keeping the number of builders per push down may help our test throughput.

**Comment by grondo** [comment]
> What all do we want to get done before popping this in and moving improvements to subsequent PRs?

See above. The code coverage builder is not working, and in my local testing coverage seems to be broken with gcc8 because some .gcda files are placed under .libs/ so gcov/lcov can't find them (also the ignore rules don't seem to be working). I haven't figured out how to deal cleanly with this yet.

`lcov` is missing in the image for `make check-code-coverage`

Coverity stuff should be removed from `.travis.yml` since it is broken.

I'd like to get the dummy `/usr/include/flux/core.h` installed in the test image (right now it is only installed in the travis host environment)

Was Caliper dependency ever added to the image?

stat watcher test is still being skipped, is that still necessary?

So this isn't quite ready to replace the current testing. However, if you'd like we could pare down this PR to just add the Dockerfiles, which will be useful to others immediately. We could merge that now and then work on getting travis up to full functionality after.

I'd be happy to continue working on this if you want to push just the Dockerfiles (and perhaps the other test improvements as separate commits)

**Comment by grondo** [comment]
> By the way, did the version format change? I noticed a bunch of the tests were failing on a different reported version format.

Sorry, I'm not sure what version format you mean.

I have code coverage working in my local repo on top of your docker work, but unfortunately I'm not sure if I'm going to be able to integrate that with your latest changes here. I was volunteering to work on the last bits and didn't know you were still iterating, sorry.

**Comment by trws** [comment]
Sorry about that @grondo, I didn't realize we were conflicting, I thought you meant something different.  I'm trying to get to a stable spot to stop pretty quickly here, it's about midnight where I am, so I can leave it.  After tonight, and maybe a bit tomorrow if something comes up, I'll need to be pretty hands-off for a week, so I was trying to get things at least in the best state I could before that. Sorry it conflicts with what you were working on. =/ 

> Sorry, I'm not sure what version format you mean.
Ah, I'm sorry I wasn't very clear.  There's a test in the utils test that checks to ensure that `flux version` returns a sane string with a \d+.\d+.\d+ format, but for some reason after I did a rebase on master I was getting some versions that had a partial sha apended on the end and it was killing that test.  Wasn't sure if that was intentional or something I accidentally screwed up somewhere.

**Comment by grondo** [comment]
>  I'm trying to get to a stable spot to stop pretty quickly here, it's about midnight where I am, so I can leave it. 


Sorry, @trws, I should have been more direct that I was willing to take the rest of the issues off your plate, but I also didn't want to steal it from you if you were interested in finishing it up.

If it is OK with you, I'd like to pause this PR and I'll try to basically rebase your work here into a new PR (preserving your authorship of course), with some minor additions and changes for coverage testing. 

Your work here has been very helfpul!

I was also going to reorg the travis builders and try to get our number of builds down to make room for a centos7 target, so I hope you don't mind if a redo a little bit of your work!

**Comment by trws** [comment]
That sounds like a good plan, thanks @grondo.  Let me add in the centos dockerfile I was working on and then that sounds great to me.

The current issue I was trying to iron out was getting env variables passed through was not working as intended, so some of the targets that should have been doing coverage or an install check were doing a distcheck regardless.  I think (read: hope) that I squashed it with the switch to an env list file, but I'm not sure.

**Comment by grondo** [comment]
BTW, @trws, besides caching during iterative development, is there any reason not to squash the 2 separate `apt update; apt install` stanzas in the `bionic-base` docker file? I assume you did it just to reuse the cache from the first, but wanted to check to make sure.

**Comment by trws** [comment]
Thanks for asking that @grondo, I should probably have added a note for it, but something funky seems to happen with the alternatives registration of openmpi and mpich if you install them in the same command.  I have no idea why, but having mpich off by itself after openmpi fixed it.  The others have no reason to be separate other than iteration speed.

**Comment by trws** [comment]
Ok, the centos7 dockerfile is in, also built and pushed to the hub.  I haven't test built flux in it, but caliper and flux security built fine, so there's some hope.  This is probably where I should leave off.  Thanks for offering to carry this forward @grondo!

**Comment by grondo** [comment]
Thank you, @trws!

**Comment by trws** [comment]
Just remembered two things I'm not sure I documented or mentioned others may want/need to know.  The centos7 image is using EPEL rather than toss packages because I realized the toss packages are marked 'rhel' rather than centos and I wasn't sure if that either tied them to the licensing system or otherwise encumbered them, so I went with open packages.  If someone knows or can verify they're unencumbered that's probably a better way to go.

The other thing is that I accidentally said the bionic-base image was using gcc 8, it's actually using 7.2, the compiler bionic uses by default and rhel 8 is currently planning to use.

**Pull request closed without merging**
