### PR TITLE
RFC: flux.c usage(): dynamically generate command list

### PR DESCRIPTION
**Pull request by grondo**
This PR is an RFC for now -- the approach taken here may not be acceptable.

I wanted to fix `flux(1)`  command list output (because it was incorrect) and have it somehow dynamically generated, possibly from `doc/man1` asciidoc sources so things stay better in sync.

However, since we are building a framework, we might eventually want other framework projects to have the ability to extend `flux` command list, and it was that thinking that got me to this current solution, which looking back, now seems a bit overly complicated.

The basic idea here consists of the following components:

 * A script `etc/gen-cmdhelp.pl` processes a list of asciidoc files (presumably manpages) with optional `flux-help-*` tags and emits a JSON array with a "category" "command" and "description" for each file.
 * Only files with at least one `flux-help-*` tag (in comments) are included in output. This means commands have to be explicitly included.
 * The `flux` utility reads in a list of files containing JSON arrays from `confdir/help.d/*.json`, and uses the data therein to generate a list of `Common commands for flux-<category>:` in output.
 * commands aren't sorted, the order is preserved from the JSON array.

The idea is that newly installed flux-framework projects can drop a JSON array of command information into `help.d/project.json` and get their commands listed on `flux` or `flux help` output.

The files are JSON instead of just plain txt so that the information is extensible, and to allow flux-core to control formatting.

Current output from this branch looks like:
```
$ ./flux
Usage: flux [OPTIONS] COMMAND ARGS
    -x,--exec-path PATH   prepend PATH to command search path
    -M,--module-path PATH prepend PATH to module search path
    -O,--connector-path PATH   prepend PATH to connector search path
    -L,--lua-path PATH    prepend PATH to LUA_PATH
    -P,--python-path PATH prepend PATH to PYTHONPATH
    -C,--lua-cpath PATH   prepend PATH to LUA_CPATH
    -t,--trace-handle     set FLUX_HANDLE_TRACE=1 before executing COMMAND
    -B,--broker-path FILE override path to flux broker
    -c,--config DIR       set path to config directory
    -F,--file-config      force use of config file, even if FLUX_URI is set
    -S,--secdir DIR       set the directory where CURVE keys will be stored
    -u,--uri URI          override default URI to flux broker
    -v,--verbose          show FLUX_* environment and command search

Common commands from flux-core:
   broker             Invoke Flux comms message broker daemon
   config             manipulate the Flux configuration
   dmesg              manipulate broker log ring buffer
   env                Print or run inside a Flux environment
   exec               Execute processes across flux ranks
   get,set,lsattr     Access, modify, and list broker attributes
   keygen             generate keys for Flux security
   kvs                Flux key-value store utility
   list-instances     List local flux instances
   logger             create a Flux log entry
   module             manage Flux extension modules
   ping               measure round-trip latency to Flux services
   ps                 List subprocesses managed by brokers
   snoop              watch Flux comms message broker traffic
   start              bootstrap a local Flux instance
   submit             submit job requests to a scheduler
   topo               generate graphviz topology for Flux comms session
   wreck              Flux wreck convenience utilities
   wreckrun           Flux utility for remote execution
```

### CODE REVIEW

**Comment by garlick** [comment]
Looks great to me and doesn't seem too complicated.  It's a good usability improvement IMHO!

**Comment by grondo** [comment]
Ok, I suppose I could complete this work then.

Still todo is to ensure the `help.d/*.json` file generated is installed in `make install` and packaged with the rpm. Also, need to fix the use of `$(shell ...)` in `etc/Makefile.am` to generate the list of all man1 `.adoc` files.

**Comment by grondo** [comment]
Oh, I also meant to ask if anyone had a better idea for the directory name than `help.d`, which is a bit too generic?

**Comment by grondo** [comment]
Ok, I just forced an update that moves `help.d/*.json` to `$datadir`, which seems more like where this kind of stuff belongs. Unfortunately, that complicated finding the files intree vs out-of-tree slightly more complicated. The current solution keeps the `help.d` dir relative to `confdir` for in-tree, but under `$datadir/flux` for out-of-tree.

For testing purposes, I was lazy and added and environment variable `FLUX_CMDHELP_PATTERN` to override the default pattern generation.

Also, I verified the code seems to still work after `make install`, and added `%{_datadir}/flux/help.d/*.json` to RPM. (Though I noticed there are other things missing from the specfile currently (needs python bindings, man3 pages packaged still)

**Comment by grondo** [comment]
One more addition here is to fix `make install` for the Lua bindings, which was woefully incorrect. At least the target of a `make install` kind of works now.

**Comment by grondo** [comment]
That commit actually broke `make distcheck` so I've pulled it and will work on it further.

**Comment by grondo** [comment]
Ok, I fixed (and tested) install paths for Lua modules.
Also fixed up the spec file somewhat -- though on LC TOSS2 systems the RPM won't build due to requirement for python 2.7 from `/opt`. Should we redo the RPM as an `/opt` RPM?

**Comment by garlick** [comment]
Maybe we should find out if there is any hope of having a flux /opt RPM accepted into TOSS2, or if we should just focus on TOSS3/RHEL7?

**Comment by garlick** [comment]
BTW, I have no problem with the spec file reworked for `/opt` and environment-modules, whether for RHEL6/TOSS2 or RHEL7/TOSS3.

**Comment by grondo** [comment]
Yeah, I'm not sure where to direct energy here. For RHEL7 we would probably create an out-of-tree `.spec` for koji build, correct? The current `flux-core.spec.in` is probably more a starting point than anything useful, but I could make it install into `/opt` on `%chaos` systems, which might be useful if we need it, but I'm not sure if that is useful energy right now. (As seen in #490, there are problems with an installed flux-core no matter where you install it, at least for me)

**Comment by grondo** [comment]
Ok, this is probably ready to go. I could optionally back

**Comment by garlick** [comment]
I think fixing the spec incrementally is OK.  Let's merge this.  Thanks!

**Pull request merged**
