### PR TITLE
job-info: Support `nnodes` and `ranks` attribute in job listing service

### PR DESCRIPTION
**Pull request by chu11**
This is built on top of PR #2655, wanted to separate out the specific fix for #2590.

I was going to add `ncores` too, but saw that a good chunk of cpu string parsing was added in the `job-shell` and wasn't sure if cutting and pasting yet more code into the job info module was a good idea.  So I'll leave that for another day ... or if we decide to, can add to this PR.

### CODE REVIEW

**Comment by grondo** [comment]
>  was going to add ncores too, but saw that a good chunk of cpu string parsing was added in the job-shell and wasn't sure if cutting and pasting yet more code into the job info module was a good idea.

That makes sense. Probably ntasks + nnodes gives users the general gist. Did you also happen to capture rank list for optional display in `flux jobs` output?

**Comment by chu11** [comment]
> That makes sense. Probably ntasks + nnodes gives users the general gist. Did you also happen to capture rank list for optional display in flux jobs output?

Not yet, only did `nnodes` just so my re-factor of `job-info` has something worthwhile in it.  But since I build up the idset for `nnodes` anyways, it's trivial to add.

**Comment by chu11** [comment]
re-pushed, also adding support for a `ranklist` attribute.  In `flux-jobs` there are similar `{ranklist}` and `{ranklist_hyphen}` formatting options. 

For discussion, should `ranklist` output with brackets by default or not?

```
>flux jobs -A --format "{id},{name},{ntasks},{ranklist}"
282729644032,hostname,1,0
248336351232,hostname,10,0
208540794880,hostname,70,[0-2]
155239579648,hostname,30,[0-1]
```

I could see no brackets to be consistent for the single rank case.  I just did brackets b/c we tend to do that more often I think.  I could go either way.

**Comment by chu11** [comment]
rebased now that #2655 is in master

**Comment by grondo** [comment]
Nice! Seems to work great!

My one early comment is for us poor users using `--format`, maybe just `ranks` instead of `ranklist`? Not a big deal though.

**Comment by chu11** [comment]
> My one early comment is for us poor users using --format, maybe just ranks instead of ranklist? Not a big deal though.

Sounds good, in hindsight, I don't know what I didn't chose `ranks` in the first place.

Rebased and re-pushed.  Basically just did `s/ranklist/ranks/g` everywhere.  Bonus points, I don't have to add `ranklist` to the spelling whitelist :P

**Comment by chu11** [comment]
restarted a builder that hit a spurious valgrind fail

**Comment by grondo** [comment]
Thanks! Merging.

**Pull request merged**
