### PR TITLE
kvs: cleanup / re-organize sharness tests

### PR DESCRIPTION
**Pull request by chu11**
Due to various changes in the KVS and flux-kvs the past few months, the kvs sharness tests have gotten a little disorganized, so I thought it'd be a good idea to go through them before we move onto the next big work.

A number of tests were eliminated because they were deemed unnecessary, most notably legacy tests related to all KVS objects being stored as json (everything is stored raw text now) and tests for now-gone functions.

There were a decent chunk of duplicate (or near duplicate) tests lingering, got rid of the duplicates.

Re-organized the KVS tests into four files

- t1000-kvs - basic/core tests

- t1001-kvs-internals - "non obvious" tests that are really to test KVS server internals (e.g. kvs server turns large values into valrefs).  This is for stuff that would generally be regarded as non-obvious to users.

- t1002-kvs-watch - kvs watch tests.  These are sort of a unique beast by themselves, so split them off.

- t1003-kvs-stress - running programs written to stress test the KVS

To accomodate the naming of these files, some other test files were re-numbered.

Admit that tests could be split up other ways.  I went back and forth on a few different ideas, but this is what I settled on.  Minimally its far more organized compared to what was there before.

### CODE REVIEW

**Comment by grondo** [comment]
Maybe update the (grossly outdated) `t/README.md` to indicate that `t10[00-99]*.t` are reserved for kvs tests? not sure what other ranges we've reserved by accident...

**Comment by chu11** [comment]
oh, wasn't even aware of the ```t/README.md```, will adjust.

**Comment by garlick** [comment]
Ah really nice to have this split up and organized!

**Comment by garlick** [comment]
It looks like a nice break down.  My only comment would be that it might be good to move the five watch tests that are in the stress script over to the watch script.  They get done pretty fast.

**Comment by chu11** [comment]
oh boy the README is way out of date

```
 - 0 - basic tests. Verify testsuite and basic command functionality.
 - 1 - kvs tests
 - 2 - TBD
 - 3 - ...
```

I'm not entirely sure what pattern the tests may be following at this point.  Especially when including the ones in ```t/lua```.  I'm thinking maybe we should open another issue, because the naming probably has to be cleaned up across many areas.

**Comment by garlick** [comment]
> I'm thinking maybe we should open another issue, because the naming probably has to be cleaned up across many areas

Sounds good to me.

**Comment by chu11** [comment]
huh ... 3 builds failed with

```
FAIL: t0001-basic.t 46 - flux-help command can display manpages for api calls
```

I'm a bit at a loss what I could have done to cause this.  Double checked and didn't accidentally introduce some random typo into that file.

**Comment by chu11** [comment]
> My only comment would be that it might be good to move the five watch tests that are in the stress script over to the watch script.

I went back and forth on this.  Could go either way.  I'll move em in there.

**Comment by chu11** [comment]
had to rebase on master, so went ahead and squashed my dinky chain-lint fix and the move of the watch tests from t1003-kvs-stress to t1002-kvs-watch.

**Comment by garlick** [comment]
Whee!  Awesome.

**Pull request merged**
