### PR TITLE
add malloc configurability, heap profiling, and cleanup

### PR DESCRIPTION
**Pull request by garlick**
Allow flux-core to be configured with tcmalloc or jemalloc.

If tcmalloc, enable heap tracing in the broker via message handlers to start/stop/dump.  Provide a builtin `flux-heaptrace` util for controlling this.  Make it an option to dump heap trace after every job during soak test.

Then some cleanup:
* fix rc3 command ordering
* remove functions in jsonutil that have identical counterparts in shortjson
* drop and rename other parts of jsonutil until nothing is left

### CODE REVIEW

**Comment by grondo** [comment]
Builds with `--with-tcmalloc` (and I imagine `--with-jemalloc` too) fail for me on hype on this branch.

The failures are due to missing `-lm`. It appears `-lm` should be in `LIBS`, but apparently `--with-tcmalloc` overwrites `LIBS` so after `./configure --with-tcmalloc` I see `LIBS = -ltcmalloc`.

It seems like [[`AC_CHECK_LIB`](http://www.gnu.org/software/autoconf/manual/autoconf.html#Libraries) is supposed to prepend to `LIBS` not overwrite it so maybe a bug in the autotools on hype?

I'll poke at this a bit more, also could be something in my environment.

**Comment by grondo** [comment]
I haven't solved the build failures with `--with-tcmalloc` yet -- would it be too difficult to move the critical kvs fixes into their own PR so they can be merged earlier?

**Comment by garlick** [comment]
OK, just split off the kvs watch fix.

**Comment by garlick** [comment]
It's failing for me too on hype:
```
$ ./configure --with-tcmalloc --disable-python
[snip]
checking for tc_cfree in -ltcmalloc... yes
checking gperftools/heap-profiler.h usability... yes
checking gperftools/heap-profiler.h presence... yes
checking for gperftools/heap-profiler.h... yes
checking google/heap-profiler.h usability... yes
checking google/heap-profiler.h presence... yes
checking for google/heap-profiler.h... yes
[snip]
...
$ make
[snip]
make[3]: Entering directory `/g/g0/garlick/flux-core/src/common'
  CCLD   libflux-internal.la
  CCLD   libflux-core.la
./.libs/libflux-internal.a(ev.o): In function `periodic_recalc':
/g/g0/garlick/flux-core/src/common/libev/ev.c:3163: undefined reference to `floor'
./libflux/.libs/libflux.a(reduce.o): In function `flux_reduce_create':
/g/g0/garlick/flux-core/src/common/libflux/reduce.c:106: undefined reference to `log'
/g/g0/garlick/flux-core/src/common/libflux/reduce.c:106: undefined reference to `log'
/g/g0/garlick/flux-core/src/common/libflux/reduce.c:106: undefined reference to `floor'
/g/g0/garlick/flux-core/src/common/libflux/reduce.c:107: undefined reference to `log'
/g/g0/garlick/flux-core/src/common/libflux/reduce.c:107: undefined reference to `log'
/g/g0/garlick/flux-core/src/common/libflux/reduce.c:107: undefined reference to `floor'
./.libs/libflux-internal.a(tstat.o): In function `tstat_stddev':
/g/g0/garlick/flux-core/src/common/libutil/tstat.c:76: undefined reference to `sqrt'
collect2: ld returned 1 exit status
make[3]: *** [libflux-core.la] Error 1
make[3]: Leaving directory `/g/g0/garlick/flux-core/src/common'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/g/g0/garlick/flux-core/src/common'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/g/g0/garlick/flux-core/src'
make: *** [all-recursive] Error 1
```

**Comment by garlick** [comment]
This change fixes it though
```diff
diff --git a/configure.ac b/configure.ac
index 78d65bd..937d2e9 100644
--- a/configure.ac
+++ b/configure.ac
@@ -66,6 +66,7 @@ X_AC_CHECK_COND_LIB(util, forkpty)
 X_AC_CHECK_COND_LIB(rt, clock_gettime)
 X_AC_CHECK_COND_LIB(dl, dlerror)
 X_AC_MALLOC
+AC_CHECK_LIB(m, floor)
 
 AC_MSG_CHECKING(--enable-python argument)
 AC_ARG_ENABLE(python,
```
Think it's reasonable to just add that?

**Comment by grondo** [comment]
Yeah, I think the `-lm` was previously leaking in via the Lua autoconf checks and that must have something to do with why it disappears with the second `AC_CHECK_LIB` from tcmalloc check.

Either that fix would work, or explicitly including `-lm` for the build products that require it?

**Comment by garlick** [comment]
OK, just pushed that fix and one other cleanup one that I happened to notice while there.

**Comment by grondo** [comment]
Nice, thanks! Looks great.

**Pull request merged**
