### PR TITLE
modules/kvs: Cleanup content_load_completion()

### PR DESCRIPTION
**Pull request by chu11**
Remove unnecessary cache_entry_create() call, as it is impossible
to reach.

### CODE REVIEW

**Comment by chu11** [comment]
Hmmm, on one travis build

```
PASS: t1006-apidisconnect.t 1 - kvs watcher gets disconnected on client exit
PASS: t1006-apidisconnect.t 2 - multi-node kvs watcher gets disconnected on client exit
ERROR: t1006-apidisconnect.t - exited with status 137 (terminated by signal 9?)
```

both tests pass, but get an error, presumably when t1006 is torn down.  Wonder if there is a corner case I'm not seeing that this code cleanup is bad.

**Comment by chu11** [comment]
Hmm, sort of perplexed by this.  Both tests in t1006-apidisconnect.t pass.  So the error appears to come outside of those tests.  Presumably on teardown of the tests.  But there's nothing in sharness or tap that appears to kill anything (such as if its hung).  So I have no idea where the signal 9 came from.

**Comment by garlick** [comment]
`flux-start` will send a SIGKILL (9) to brokers that fail to terminate within 2s after the first broker terminates.  Not sure why its happening here but that's the likely source of the signal.

**Comment by chu11** [comment]
@garlick Ahh, I didn't think of the kill coming from within flux.  The question is if this was a racy/bug hang or unlucky/slow scheduling.  I'm thinking the latter, as if my patch was a real bug it would have asserted with SIGABRT and that would have been returned instead SIGKILL.  Lets see if travis hits it regularly.  Restarting.

**Comment by chu11** [comment]
api-disconnect didn't appear this time.  But did hit #1063.

```
FAIL: t2008-althash.t 5 - Attempt to start instance with invalid hash fails hard
```

Lets give travis another shot at a perfect run.

**Comment by garlick** [comment]
This seems good, and hard to imagine how it could be linked to the spurious travis problems.  Merging.

**Pull request merged**
