### PR TITLE
python: install kz bindings file

### PR DESCRIPTION
**Pull request by trws**
The kz bindings have been getting built, but their native interface file
was not being installed.  This fixes that issue.

Fixes flux-framework/capacitor#6

### CODE REVIEW

**Comment by grondo** [comment]
@trws, this PR failed in travis with 
```
make[4]: *** No rule to make target `kz.py', needed by `distdir'.  Stop.
make[4]: Leaving directory `/home/travis/build/flux-framework/flux-core/src/bindings/python/flux'
make[3]: *** [distdir] Error 1
make[3]: Leaving directory `/home/travis/build/flux-framework/flux-core/src/bindings/python'
make[2]: *** [distdir] Error 1
make[2]: Leaving directory `/home/travis/build/flux-framework/flux-core/src/bindings'
make[1]: *** [distdir] Error 1
make[1]: Leaving directory `/home/travis/build/flux-framework/flux-core/src'
make: *** [distdir] Error 1
```

I can try to diagnose further if you like (maybe a builddir v srcdir thing?) We also need to rebase on master. We probably want to get this in and tag v0.5.1, since I assume capacitor wouldn't work right now against our 0.5.0 package?

**Comment by grondo** [comment]
One or more python tests are now failing here, sorry I'm not much help beyond cut-and-paste though:

```
Traceback (most recent call last):
  File "../../src/bindings/python/test_commands/test_runner.t", line 54, in <module>
    run_under_dir(result_set, '../flux', 'flux')
  File "../../src/bindings/python/test_commands/test_runner.t", line 29, in run_under_dir
    (mod_prefix, m.group(1))))
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/travis/build/flux-framework/flux-core/flux-core-0.5.0-116-g1919937/_build/src/bindings/python/flux/kz.py", line 4, in <module>
    import flux.json_c as json_c
ImportError: No module named json_c
FAIL: ../t/t9990-python-tests.t

```

**Comment by trws** [comment]
I'm looking into what's going on here, but it's quite strange, the 
changes in this branch don't actually introduce anything to that test 
other than a module that shouldn't be loaded at that point.  It's taking 
me a bit to track down why this is happening.

**Comment by grondo** [comment]
> It's taking me a bit to track down why this is happening.

Ah, my apologies. Let me know if you need any assistance.

**Comment by grondo** [comment]
@trws, looks good now! Ready to merge?

**Comment by trws** [comment]
Good to go. 👍

**Pull request merged**
