### PR TITLE
add PRIORITY state to prepare for fair share priority plugin

### PR DESCRIPTION
**Pull request by chu11**
Per #3327 and RFC21 updates, add initial PRIORITY state into job state FSM.  Hopefully I got all the job state machine uses.

Notes:

- Obviously we don't have a priority plugin infrastructure yet, so the job-manager simply uses the administrative priority set in `submit`.                                                                                                                                 

- I made tons of "tiny" commits, but could do fewer big ones.  Its my style :P  Because of this in commit  a39fcee4492c8c5b32c819b7cf71d8bcd8ff7b80 reviewers may notice I added this to `event.c`:

```
+        case FLUX_JOB_PRIORITY:
+            break;
```

by adding `FLUX_JOB_PRIORITY` to the job state enum there was a compile error on a switch statement in `job-manager/event.c`.
                                                                                                                                            
If I were to add `FLUX_JOB_PRIORITY` "for real" to job-manager in that commit, then I would also have to add FLUX_JOB_PRIORITY to `job-info` for real, otherwise tests would break.  Leading to way more changes in 1 commit than I wanted.  So I did the above hack, just sticking `FLUX_JOB_PRIORITY` into the switch statement, but did not implement anything until a later commit.  If we merge a bunch of tiny commits into a big one, that'll correct this issue.

- For consideration (I did not do this yet):

  - "FLUX_JOB_PRIORITY" was the previous prefix for some priority enums (e.g. `FLUX_JOB_PRIORITY_MIN`), but it's now `FLUX_JOB_ADMIN_PRIORITY` (via PR #3339).

  - The new job state enum is `FLUX_JOB_PRIORITY`.  Maybe the enum is a tad confusing given it was the prefix for some enums before.

  - Should we prefix job states from `FLUX_JOB` to `FLUX_JOB_STATE`?  Virtual states as well, e.g. FLUX_JOB_STATE_DEPEND`, `FLUX_JOB_STATE_PENDING`.

I think it's a good idea, but its not entirely necessary.  I could go either way on it.  Figure I'd bring it up before doing it.

### CODE REVIEW

**Comment by garlick** [comment]
> the job-manager simply uses the administrative priority set in submit

Good as long as we are breaking ties in the zlistx_t comparator with the FLUID job ID so we still get submit order for jobs of equal priority.

> I did the above hack, just sticking FLUX_JOB_PRIORITY into the switch statement, but did not implement anything until a later commit.

That's probably what I would have done.  Sounds fine to me.

> The new job state enum is FLUX_JOB_PRIORITY

Shall we make it FLUX_JOB_QUEUE_PRIORITY?

> Should we prefix job states from FLUX_JOB to FLUX_JOB_STATE? Virtual states as well

I'd be fine with that.  Not sure if that's likely to cause a problem for workflow users, but we're 0.x still so maybe not a big deal.

**Comment by chu11** [comment]
> Good as long as we are breaking ties in the zlistx_t comparator with the FLUID job ID so we still get submit order for jobs of equal priority.

Totally forgot about this, and I wasn't 100% sure if that was decided yet.  I'll add this into the PR as well.

> Shall we make it FLUX_JOB_QUEUE_PRIORITY?
> I'd be fine with that. Not sure if that's likely to cause a problem for workflow users, but we're 0.x still so maybe not a big deal.

So with both changes it should be `FLUX_JOB_STATE_QUEUE_PRIORITY`?   Seems wrong b/c in RFC21 we call the state "priority".  Thinking we should go with "queue priority" as the state name?

**Comment by garlick** [comment]
I think I must've been confused about what you were proposing.

For the state enum:  FLUX_JOB_PRIORITY is fine.  Changing all the states to FLUX_JOB_STATE_name would also be fine IMHO.

I was thinking you were talking about an enum analgous to the admin priority one, only for queue priority in the other question.  So FLUX_QUEUE_PRIORITY_MAX or similar to me would be preferable to FLUX_PRIORITY_MAX (since we had that before).

Sorry!

**Comment by chu11** [comment]
> I was thinking you were talking about an enum analgous to the admin priority one, only for queue priority in the other question. So FLUX_QUEUE_PRIORITY_MAX or similar to me would be preferable to FLUX_PRIORITY_MAX (since we had that before).

Yup, I figure we'll have a `FLUX_QUEUE_PRIORITY_MIN/MAX` at some point.  Didn't add it yet as we wouldn't use it anywhere at the moment.  There are little cleanups to be done as we work our way through all of these priority plugin related issues.

**Comment by chu11** [comment]
re-pushed, adjusting the job comparators in `job-info` and `job-manager` to sort by job id second instead of `t_submit`.  Since it maintains the same sorting order as before, no other adjustments to tests had to be done.

Also did the `FLUX_JOB` -> `FLUX_JOB_STATE` adjustment as discussed above.

Fixed a few comment errors too.

**Review by garlick — APPROVED** [review]
Looks good to me!

I'd probably change the PR title to something nicer for release notes, like "add PRIORITY state to prepare for fair share priority plugin".

Up to you, but some commit messages could be reworked to use the "problem" format, and might come out more concise.  Example:

> libjob: Rename job states enumeration
> 
> For consistency to other parts of libjob, rename the prefix of fields in
> the flux job states enumeration from FLUX_JOB to FLUX_JOB_STATE.  For
> example, FLUX_JOB_DEPEND is now FLUX_JOB_STATE_DEPEND.
> 
> Update globally as needed.

Could become 

> libjob: rename API job state constants
>
> Problem: API job state constants have ambiguous "namespace" prefixes.
>
> Change the prefix from FLUX_JOB_ to FLUX_JOB_STATE_ to make it clear that they are job states, as opposed to some other aspect of a job.

(I find that format makes concise commit messages easier to write)

**Comment by chu11** [comment]
rebased and re-pushed with a few commit messages, i'll let folks take a quick skim if they'd like.  i'll set MWP later today.

**Comment by grondo** [comment]
> I'd probably change the PR title to something nicer for release notes, like "add PRIORITY state to prepare for fair share priority plugin".

I was going to mention this suggestion as well.

I also usually think of what will be a good line for the release notes when I title a PR (though it isn't always easy). Since a PR is more broad than a commit, the same strong suggestion of `subsys: message` do not apply (a commit is supposed to just do one thing, while a PR adds an entire feature, improvement, or bugfix)

**Comment by garlick** [comment]
Thanks for that - already approved so I'll go ahead and set MWP.

**Pull request merged**
