### PR TITLE
job-info: re-load job state from KVS

### PR DESCRIPTION
**Pull request by chu11**
nothing too extraordinary in this PR, it's about what you expect.  Copied a decent amount of code from `job-manager`.  Perhaps could make a convenience lib?

### CODE REVIEW

**Comment by grondo** [comment]
Just one comment, the DEBUG log message
```
 job-info.debug[0]: job_state_init_from_kvs: read 0 jobs
```

Always returns `0 jobs`. This seems to be because `depthfirst_map_one()` returns `0` on success.

**Comment by chu11** [comment]
> Always returns 0 jobs. This seems to be because depthfirst_map_one() returns 0 on success.

Doh!  Thanks for the catch.  Fixed, rebased, and re-pushed

**Comment by grondo** [comment]
One thing from the codecov report -- it doesn't look like `job_running_cmp()`, which appears to be added in this PR, is covered by any tests. Is that expected?

**Comment by chu11** [comment]
> LGTM! Did you want to squash that fixup?

Oops, I thought I did that.

**Comment by chu11** [comment]
> One thing from the codecov report -- it doesn't look like job_running_cmp(), which appears to be added in this PR, is covered by any tests. Is that expected?

Yeah, there is some missed coverage due to #2503, so reloading running jobs from the KVS won't work right now.

**Pull request merged**
