### PR TITLE
conf_environment refactor

### PR DESCRIPTION
**Pull request by trws**
Some gcc versions don't like the vec.h/vec.c implementations of a vector, this removes the dependency on that, and reimplements conf_env functions in terms of argz instead of usa.

### CODE REVIEW

**Comment by trws** [comment]
Huh... the install tests seem displeased. I'll check I on this tomorrow, but it strikes me as odd that this is only failing there. May mean we've had an environment bug lurking that was hidden by unintended behavior before.

**Comment by trws** [comment]
@grondo, am I reading the test output right for the gcc+install tests?

```
The command "if test "$T_INSTALL" = "t" ; then ARGS="--prefix=/tmp/flux"; MAKECMDS="make && make install && /tmp/flux/bin/flux keygen && FLUX_TEST_INSTALLED_PATH=/tmp/flux/bin make check"; fi" exited with 0.
0.00s$ export FLUX_TESTS_LOGFILE=t
The command "export FLUX_TESTS_LOGFILE=t" exited with 0.
106.75s$ if test "$COVERITY_SCAN_BRANCH" != "1" ; then ./autogen.sh && ./configure ${ARGS} && eval ${MAKECMDS}; fi
Running aclocal ... 
Running libtoolize ... 
Running autoheader ... 
```

This looks like it's running the coverity_scan_branch test instead of the T_INSTALL test, and failing in the coverage test for some reason...  It's actually failing due to the ~/.flux directory being missing, which made me think that keygen isn't being run, but I'm trying to make sure it's running the right test first.

**Comment by grondo** [comment]
It is running the correct thing I think. That `if test "$COVERITY_SCAN_BRANCH" != "1"` would skip that command if `COVERITY_SCAN_BRANCH` is set.

It is strange that `flux-keygen` test succeeded, which ensures keys have been generated, but then subsequent tests fail. I have a fix for generating logfiles for tests that don't use `test_under_flux` which might help diagnose here. I'll create a PR shortly.

**Comment by grondo** [comment]
Ah, I remember now. The `flux keygen` test in `t0001-basic.t` generates a key in a tmpdir, so that isn't what creates the keys for the installed flux.

Instead there is a line in the "install" builder commands that should be creating the `$HOME/.flux` directory:
```
MAKECMDS="make && make install && /tmp/flux/bin/flux keygen && ...
```

Let me look carefully in the logs to see if that keygen failed...

**Comment by grondo** [comment]
Hm, I see no output from `flux keygen` in the log (can you check as well, maybe I missed it?), but for example in my most recent succeeding [build](https://travis-ci.org/grondo/flux-core/jobs/113184519), we see in the output
```
Saving /home/travis/.flux/curve/client
Saving /home/travis/.flux/curve/client_private
Saving /home/travis/.flux/curve/server
Saving /home/travis/.flux/curve/server_private
```

**Comment by grondo** [comment]
Nevermind! Now I've found it just after posting the above:
```
2326: Saving /home/travis/.flux/curve/client
2327: Saving /home/travis/.flux/curve/client_private
2328: Saving /home/travis/.flux/curve/server
2329: Saving /home/travis/.flux/curve/server_private
```

Now I'm really confused why the `/home/travis/.flux` directory appears not to exist later...

**Comment by trws** [comment]
I'm seeing those lines starting at line 2323, in the middle of the 
install phase.  Something fishy is definitely happening with an 
installed version.  Let me do some poking at this and see what I come up 
with.

**Comment by grondo** [comment]
FWIW, I get the same problem when running `make install` on this branch and trying to run with the installed flux. `flux-broker: /home/ubuntu/.flux: No such file or directory` even though that dir does exist. My guess is that the error message is misleading.

**Comment by trws** [comment]
I found that out about the same time you did @grondo.  It turns out the error message was actually due to the configuration file not being found, which was only being checked for due to an environment variable that failed to be unset.  I'm including a patch that clarifies that message, and demotes it to a warning for an environment-variable-based configuration file to be missing.

**Comment by grondo** [comment]
Great!

Ah, looks like you hit the waitfile.lua test issue (hopefully) resolved in #589. I restarted the failing test.

**Comment by trws** [comment]
Looks like it got one of the tests in the push build too.  Glad to hear you tracked that one down @grondo.

**Comment by grondo** [comment]
Ah, are you pushing a branch to the flux-framework/flux-core repo instead of or in addition to trws/flux-core? I was wondering what the 'push' build was...

**Comment by trws** [comment]
That happened by mistake... I had a misconfigured macro that accidentally did "push upstream <branch>" instead of "push origin <branch>."  The unnecessary branch has already been removed, but I guess it still got tested.

**Comment by grondo** [comment]
Ah, yeah, I did the same thing on flux-sched. :smile:

I think for this PR we just need to clean up the commits, perhaps
 * squash the fixup commit 5421a23 into the main commit
 * keep the local conf warning commit on its own, but fix up the commit message to our best practices (present tense, add "broker: " tag to the shortlog message, and add a body that explains the change)

**Comment by trws** [comment]
Thanks @grondo.  This should take care of the commit refactoring.

**Comment by grondo** [comment]
This looks good. Restarted travis build because waitfile testing bug hit you again. I'm inclined to merge though since that was the only failing test. Then I can rebase #589 and get that one merged.

**Pull request merged**
