### PR TITLE
avoid use of xzmalloc and oom in libflux API sources

### PR DESCRIPTION
**Pull request by grondo**
This was a result of a quick pass through the libflux source files removing the use of functions that call `oom()`. There might be more work needed here, and I'm not sure in the end if this actually accomplishes very much because other functions in libutil that are called from libflux might end up calling `oom()` as well.

There may be some better solutions for error handling is some cases as well, but I'm just throwing up this PR for feedback.

(This was part of the dirwalk PR and I've just split it out, so it might not even pass travis at this point)

### CODE REVIEW

**Comment by garlick** [comment]
Ooops, I meant that last comment to be a targetted review comment on the reactor changes, not the entire review, sorry.

**Comment by garlick** [comment]
Just wondering if maybe the log functions should call FLUX_FATAL(h) internally on ENOMEM or other I/O error?  (see examples in handle.c - functions by default return errors directly, but they can call the user's noreturn error function before returning if the user registered one and the handle is unlikely to be usable afterwards).

```c
typedef void (*flux_fatal_f)(const char *msg, void *arg);

/* Register a handler for fatal handle errors.
 * A fatal error is ENOMEM or a handle send/recv error after which
 * it is inadvisable to continue using the handle.
 */
void flux_fatal_set (flux_t *h, flux_fatal_f fun, void *arg);

/* Set the fatality bit and call the user's fatal error handler, if any.
 * The fatal error handler will only be called once.
 */
void flux_fatal_error (flux_t *h, const char *fun, const char *msg);
#define FLUX_FATAL(h) do { \
    flux_fatal_error((h),__FUNCTION__,(strerror (errno))); \
} while (0)

/* Return true if the handle 'h' has encountered a fatal error.
 */
bool flux_fatality (flux_t *h);
```

**Comment by grondo** [comment]
Rebased on master.

Great suggestions. I might not get back to this until Monday, but feel free to push to this PR if you have any desire to clean it up a bit in the meantime. ;-)

**Comment by garlick** [comment]
Pushed one commit that reworks flux_watcher_create for one malloc instead of two.  See what you think?

**Comment by garlick** [comment]
I added a few more commits.  In the logging module, I changed the vasnprintf that was the subject of two earlier commits to a vsnprintf on the stack.

I went ahead and removed the reparent module, updated the flux-comms command accordingly, and then dropped the broker code associated with dynamic parent overlay connections.  I apologize for not doing this when we got rid of the live module (the main user), since you then had to sort it out in your cleanup.

All done for now.  Feel free to squash down when you're happy and I'll press the button.

**Comment by grondo** [comment]
Thanks for the extraq cleanup, looks great!

I added a couple minor leak cleanups, please check those out.

Do you think this needs squashing? I'll check back in after lunch.

**Comment by garlick** [comment]
Good catch on the flux_msg_t leak!  OK, since we have multiple authors here, maybe the small amount of incremental development is no big deal.  Merging.

**Pull request merged**
