### PR TITLE
Add missing include of config.h

### LINKED ISSUE #5167: some source files do not include config.h
Problem: some (especially test) .c files do not include `config.h` which could result in unexpected results.

Here is a list of files generated with the following scriptlet, then hand edited to remove obvious vendored code
```
find . -name \*.c | (while read name; do grep -q HAVE_CONFIG_H $name ||echo $name; done)
```

```
./src/common/libzmqutil/test/reactor.c
./src/common/libutil/test/fsd.c
./src/common/libutil/test/aux.c
./src/common/libutil/test/grudgeset.c
./src/common/libutil/test/fdwalk.c
./src/common/libutil/test/unlink.c
./src/common/libutil/test/environment.c
./src/common/libutil/test/popen2.c
./src/common/libutil/test/kary.c
./src/common/libutil/test/wallclock.c
./src/common/libutil/test/stdlog.c
./src/common/libutil/test/strstrip.c
./src/common/libutil/test/cronodate.c
./src/common/libutil/test/ipaddr.c
./src/common/libutil/test/hola.c
./src/common/libutil/test/intree.c
./src/common/libutil/test/veb.c
./src/common/libutil/test/fdutils.c
./src/common/libutil/test/blobref.c
./src/common/libpmi/test/keyval.c
./src/common/libpmi/test/kvstest2.c
./src/common/libpmi/test/pmi2_info.c
./src/common/libpmi/test/kvstest.c
./src/common/libpmi/test/pmi_info.c
./src/common/libflux/ev_flux.c
./src/common/libflux/test/panic.c
./src/common/libflux/test/version.c
./src/common/libflux/test/plugin_foo.c
./src/common/libflux/test/msg_handler.c
./src/common/libflux/test/rpc_security.c
./src/common/libflux/test/reactor.c
./src/common/libflux/test/response.c
./src/common/libflux/test/tagpool.c
./src/common/libflux/test/plugin.c
./src/common/libflux/test/plugin_bar.c
./src/common/libflux/test/buffer.c
./src/common/libflux/test/request.c
./src/common/libflux/ev_buffer_write.c
./src/common/libflux/ev_buffer_read.c
./src/common/liboptparse/test/optparse.c
./src/common/libioencode/test/ioencode.c
./src/common/libkvs/test/treeobj.c
./src/common/libterminus/terminus.c
./src/common/libsubprocess/test/subprocess.c
./src/common/libsubprocess/test/test_fork_sleep.c
./src/common/libsubprocess/test/test_echo.c
./src/common/libsubprocess/test/test_multi_echo.c
./src/common/libsubprocess/test/cmd.c
./src/common/libeventlog/test/eventlog.c
./src/common/libsdprocess/test/test_env.c
./src/common/libsdprocess/test/test_echo.c
./src/common/librlist/test/rlist.c
./src/common/librlist/test/rnode.c
./src/common/librlist/test/match.c
./src/common/librlist/test/rhwloc.c
./src/modules/kvs/test/waitqueue.c
./src/modules/job-exec/rset.c
./src/modules/job-exec/test/rset.c
./src/modules/job-exec/test/bulk-exec.c
./src/modules/cron/types.c
./src/modules/job-manager/plugins/alloc-bypass.c
./src/modules/job-manager/plugins/perilog.c
./src/modules/job-manager/plugins/begin-time.c
./t/stats/stats-basic.c
./t/stats/stats-immediate.c
./t/kvs/waitcreate_cancel.c
./t/kvs/issue1876.c
./t/sched-simple/jj-reader.c
./t/reactor/reactorcat.c
./t/loop/logstderr.c
./t/loop/issue2337.c
./t/loop/issue2711.c
./t/hwloc/hwloc-version.c
./t/hwloc/hwloc-convert.c
```

Edit: dropped man page examples and jobtap test plugins from the list per @grondo
Edit: dropped fdwalk.c, test/sha1.c test/sha256.c (vendored)

### PR DESCRIPTION
**Pull request by chu11**
Problem: A number of C files did not include config.h.

Globally add it when it is missing and the file is not a vendored file.  Update some formatting in some locations. Most notably move include of system headers before local code headers.

Fixes #5167

Edit: I re-read the PR title and didn't like it, adjusted it and the commit message.

### CODE REVIEW

**Comment by chu11** [comment]
> I feel like some of these are questionable. E.g. in unit tests of libflux interfaces, do we really need to include config.h when we're testing public interfaces? Users of the API will not have our config.h available so this might invalidate the unit test?

I admit I dumbly did this without much thinking about it too much.  My first thought was "we load config.h in most unit tests, but not all, we should make it consistent".  Perhaps the opposite should be done, we should audit and remove config.h from unit tests that really shouldn't include it?

**Comment by chu11** [comment]
oh yeah, and we sometimes include private headers to unit test things that aren't public ... those unit tests should include config.h?

**Comment by garlick** [comment]
> E.g. in unit tests of libflux interfaces, do we really need to include config.h when we're testing public interfaces? Users of the API will not have our config.h available so this might invalidate the unit test?

Good point.  Maybe we could leave a comment instead in those cases, so that well meaning cleaner-uppers don't fix it later (except of course those man page examples where that would harm readability).
```c
/* The project config.h is purposefully not included in this source module.
 * (optional reason...)
 */
```

**Comment by chu11** [comment]
ok, lemme give it another pass.

**Comment by grondo** [comment]
One other check would be to do a find of all files that do not `#include "config.h"` but have `#ifdef/ifndef SOMETHING`. Maybe that could even turn into a test done in CI.

**Comment by chu11** [comment]
any strong opinions on if plugin files should include config.h?  `job-manager/plugins/*` is inconsistent on it at the moment.  

I can see arguments both directions.

**Comment by garlick** [comment]
Yeah _GNU_SOURCE was on my mind.  I could swear I've been stuck for a long time on a problem with the way something in glibc was behaving and eventually ran it down to _GNU_SOURCE not being defined due to missing config.h, but I cannot seem to recall the details.

**Comment by chu11** [comment]
Re-pushed with some obvious fixes and cleanup, but doesn't include the big big fix.

As I began to audit, IMO, if a file includes internal helper library code (`read_all`, `log`, `ccan`, `xzmalloc`, etc. etc.) I think we should probably include config.h.  So that leads to (I think) most test files needing config.h.  Then number that don't include something local is super rare.

**Pull request merged**
