### PR TITLE
libsubprocess,popen2: after fork(), loop through fds to close then intead of fdwalk()

### PR DESCRIPTION
**Pull request by chu11**
Per discussion in #2472, `fdwalk()` calls `opendir()` which calls `malloc()`, which can be unsafe/bad for ASan.  Instead, manually loop through fds from 3 to `_SC_OPEN_MAX`.

Remove `fdwalk` convenience library as it is no longer used.

### CODE REVIEW

**Comment by chu11** [comment]
tons of travis failures, not sure why.  Perhaps `_SC_OPEN_MAX` isn't that safe/portable?

**Comment by chu11** [comment]
I'm wondering if this is the issue in travis:

```
time(seconds)        unlimited
file(blocks)         unlimited
data(kbytes)         unlimited
stack(kbytes)        8192
coredump(blocks)     unlimited
memory(kbytes)       unlimited
locked memory(kbytes) 64
process              unlimited
nofiles              524288
vmemory(kbytes)      unlimited
locks                unlimited
rtprio               0
```

looping 500K file descriptors on a single core slow travis?

**Comment by grondo** [comment]
Maybe we should try switching `fdwalk` to `getdents64()` instead of going back to the for i=1,_SC_OPEN_MAX loop.

See [safe_fdwalk()](https://github.com/GNOME/glib/blob/master/glib/gspawn.c#L1189) in glib for example.

**Comment by chu11** [comment]
closing, #2479 will be the likely solution to #2472

**Pull request closed without merging**
