### PR TITLE
modules/kvs: Support namespace timeout

### PR DESCRIPTION
**Pull request by chu11**
If a namespace has not been touched/modified on a follower node
for a long period of time, and no one is watching a key on it,
and no unfinished fences are lingering, remove the namespace from the node.

The namespace still lives on in the rank 0 leader node, but data/info
is not replicated on follower nodes.

### CODE REVIEW

**Comment by chu11** [comment]
oops, i made an obvious mistake.  ignore for now

**Comment by chu11** [comment]
Fixed the issue.  Testing was done by hand by hand lowering the timeout & watching for a hand added log message.

**Comment by garlick** [comment]
Looks good, just needs a rebase.

**Comment by chu11** [comment]
re-based

**Pull request merged**
