### PR TITLE
Add hierarchical lwj directory support in kvs

### PR DESCRIPTION
**Pull request by grondo**
This PR is an experiment in changing just the `lwj-active.` kvs directory for wreck jobs to a tree of directories, with parameters as suggested by @dongahn in #798.

This implementation uses a configurable number of prefix directory "levels" (parent dirs) and adjustable number of bits to use for parent directories (i.e. adjustable number of entries per dir in powers of 2).
The numbers can be adjusted *at flux start time only* by the new broker attributes:
```
wreck.lwj-bits-per-dir                  7
wreck.lwj-dir-levels                    2
```

The default is 2 levels and 7 bits per directory as determined in @dongahn's experiments. To get the old behavior set `wreck.lwj-dir-levels` to `0`, e.g.
```
flux start -o,-Swreck.lwj-dir-levels=0 ...
```

The top-level `lwj-active.` directory always uses all remaining high-order bits, (i.e bits `64 - (levels+1)*bits_per_dir`). This means this top-level directory can grow to allow the maximum lwj id to be stored, however, it doesn't necessarily adhere to `lw-bits-per-dir`.

Because `lwj-active.` directory is now stored in a hierarchy by default, the "archive" of jobs seemed no longer necessary. Instead `lwj.<id>` is kept as a link to `lwj-active.x.y.<id>`, and `lwj-complete.<hb>.<id>` is also linked back to `lwj-active.`. (i.e. we no longer use `kvs_move()`) Perhaps that was a gratuitous change at this point, and could easily be backed out.

Actually `lwj-active` is a misnomer now, and probably should be renamed to `lwj-store.` or something, but since this PR is just for testing purposes at this stage I didn't make that change yet.

I didn't see a real improvement with job throughput using this change. Possibly it will only affect performance of pure `flux submit`. I tried the soak test and unfortunately I'm seeing very high standard deviation of job runtimes both on this branch and current master. I may have botched the tests.

@dongahn, hopefully you'll be able to give early feedback on this change and your job throughput testing.

### CODE REVIEW

**Comment by dongahn** [comment]
Thanks @grondo! I will cherry pick this and experiment with it soon.

**Comment by dongahn** [comment]
@grondo: as you may recall, I have been using the purge-keep change for my testing and this PR has conflicts with the cherry-picked change.  Could you please take a quick look at it and suggest the right merge for me? 

```
<<<<<<< HEAD
                    table.insert (r, id)
                    if self.opt.R then
                        local t, target = f:kvs_type ("lwj."..id)
                        if t == "symlink" then
                            f:kvs_unlink (target)
                        end
                        f:kvs_unlink ("lwj."..id)
                        f:kvs_unlink ("lwj-complete."..hb.."."..id)
=======
                    if keep (id) then
                        hb_unlink = false
                    else
                        table.insert (r, id)
                        if self.opt.R then
                            f:kvs_unlink ("lwj."..id)
                            f:kvs_unlink ("lwj-complete."..hb.."."..id)
                        end
                        n = n - 1
                        if n == 0 then return end
>>>>>>> ed7f0ad... cmd/flux-wreck: add --keep option to purge
                    end
                end
                if self.opt.R and hb_unlink then
                    f:kvs_unlink ("lwj-complete."..hb)
                end
            end
        end)()

        -- gather ids to remove in hostlist for condensed output:
        --
        local hl = require 'flux.hostlist' .new (table.concat (r, ",")):uniq ()
<<<<<<< HEAD
        local idstring = tostring (hl):match ("%[?([^]]+)%]?")
=======
>>>>>>> ed7f0ad... cmd/flux-wreck: add --keep option to purge


```

**Comment by grondo** [comment]
Ah, sorry @dongahn I forgot about that one, let me see if I can merge that for you!

**Comment by dongahn** [comment]
@grondo: thanks! I could have tried it but I know you are the perfect :-)

**Comment by grondo** [comment]
I didn't have time to test right now, but I pushed a fixed up commit on top here. It may not work, but I'll check back in after dinner.

**Comment by dongahn** [comment]
My tests seem to run better w/ this. I ran the 2CN case twice and there are some degradation towards the end (w/ all of the scheduler optimizations in it) but not like before where I had steep degradation at 3000 and afterwards. 

First run:
```
cat MOAB.SLURM.00000002.00002Nx01B.half.usleep.FCFS.QD16.DELAYtrue.00010000.10800.in.stats.old
job-group-id,used-nodes,job-count,JEPS
0,1,1000,23.33541049600628450607
1,1,1000,18.87337644138335054899
2,1,1000,17.20563164411596217204
3,1,1000,16.29070648428112989473
4,1,1000,15.08969700688164123029
5,1,1000,14.74500170983039827193
6,1,1000,14.00075354855749046125
7,1,1000,13.03554329895838839492
8,1,1000,4.52034726284068150888
9,1,1000,3.98137040345909741902
```

Second run:
```
cat MOAB.SLURM.00000002.00002Nx01B.half.usleep.FCFS.QD16.DELAYtrue.00010000.10800.in.stats
job-group-id,used-nodes,job-count,JEPS
0,1,1000,23.46239928794433649003
1,1,1000,19.21635622451022408154
2,1,1000,17.40877003697204945371
3,1,1000,15.97285713220096531323
4,1,1000,15.23304401872927134973
5,1,1000,14.57901979622408344144
6,1,1000,14.25902668397180169104
7,1,1000,13.40933134449706653444
8,1,1000,2.70363351257125777594
9,1,1000,9.81802853555012897845
```

Also, the version of flux-core seems generally a bit slower than the version I used for my tests before. I can reestablished the baseline  for the flux-core performance by using the version right before this PR -- making sure the hierarchical lwj doesn't hurt general performance much.

**Comment by dongahn** [comment]
> I didn't see a real improvement with job throughput using this change

Did you use wreckrun as well as purge along with the change? If so, I'm wondering if the active lwj won't grow much if there is logic within wreckrun to block, natural throttling. Also wondering what happens if we don't use purge.

**Comment by grondo** [comment]
> Did you use wreckrun as well as purge along with the change? 

I didn't use purge. I was expecting "job insertion" to go a bit faster for anything over 128 jobs, perhaps that expectation was a bit premature. 

> if so, I'm wondering if the active lwj won't grow much if there is logic within wreckrun to block, natural throttling.

I was running with `-d`, so wreckrun shouldn't be blocking. However, this runs jobs overlapping and could slow down the machine itself, so perhaps a better test on my end would have `flux submit`.

As a side note, on this branch the `lwj-active` directory is a misnomer, as `kvs_move` is no longer used at job completion to move the lwj directory from `lwj-active.<id>` back to `lwj.id`, `lwj.id` remains a link (until purge of course)

**Comment by dongahn** [comment]
> I didn't use purge. I was expecting "job insertion" to go a bit faster for anything over 128 jobs, perhaps that expectation was a bit premature

Interesting. Let`s continue to peel this. There still one time overhead of creating a link into lwj, which could eclipse other benefits... I also have to understan degradation after 
8000 jobs as well...

> I was running with -d, so wreckrun shouldn't be blocking. However, this runs jobs overlapping and could slow down the machine itself, so perhaps a better test on my end would have flux submit.

Yeah. I once tested mine with `wteckrun -d` and I noticed it naturally throttled more than slux submit.

**Comment by grondo** [comment]
Ok, I've switched this PR over a scheme that removes the lwj-active directory completely and adds the lwj hierarchy directly under `lwj.`. This required removing all instances where `lwj.<id>` was used for the kvs path to job `id`, passing the kvs path to `wrexecd`, etc. I haven't tackled libjsc yet, so this branch will not pass travis, however all other wreck interfaces should pretty much work.

I ran a 8K job soak test real quick, and got the following (with no purge)

soak-45980

**Comment by grondo** [comment]
Also, in this current branch the `wrexec` module was removed and the equivalent code was moved into the `job` module (which already ran on every rank). The fork/exec of `wrexecd` was also greatly simplified, double fork removed (I don't think it served a purpose), and the "parent-fd" shenanigans removed.

**Comment by grondo** [comment]
Ok, here's another soak test up to 10K jobs, after a couple of leak fixes, also with the y axes scaled down a bit. Still looks like perhaps I've got a slow leak to find

soak-23817

**Comment by dongahn** [comment]
Great results @grondo! This is major in particular looking at the flat runtime overheads in the absence of purge! Feel free to delegate JSC work to me. If nothing else, this will reveal good understanding about the scheduler throughput as well!

**Comment by grondo** [comment]
@dongahn, I felt bad about pushing a PR that couldn't pass tests, so I took a stab at updating jsc in these most recent commits.

It isn't perfect, but the approach taken here is to add a new hash to jsc ctx to store a mapping between lwj id and kvs path. The hash is updated whenever a new lookup via `job.kvspath` service is performed, or using the new `kvs_path` member of wrexec state events. Instead of direct `xasprintf` to construct kvs keys assuming `lwj.%d`, a `ljw_key()` function is used to construct keys based on the real base path for the job id.

One problem is that the hash only grows, it doesn't purge old entries, so if libjsc is used in long running processes this will need to be addressed, but I consider the current approach an interim solution so you can move on to your testing more quickly.

There are also some other minor test and leak fixes here -- we'll see if travis tests now pass.

**Comment by garlick** [comment]
Here's a 10K job soak test on master, for comparison (not scaled like @grondo's though)

soak-8312

This was on my desktop so the spikes may be due to other things going on.

**Comment by dongahn** [comment]
Thanks @garlick. It seems, over 4x improvement in sqlite db memory overhead tells a lot about the cause of the large kvs directory perf issue...

**Comment by garlick** [comment]
Is this ready to go in?  Seems like it helps quite a bit!

**Comment by grondo** [comment]
I just rebased on current master and cleaned up some transitional code, and added tests for the new broker attrs used to construct the `lwj.x.y.z` paths in kvs.

I'd like to run some valgrind tests before merging, then I think it is ready if the general approach is ok.

**Comment by grondo** [comment]
Oh, wait, I spoke too soon. I haven't even tested yet what changes will be necessary in flux-sched to support this. Also, this may break capacitor as well. I think for now this has to stay as an experimental branch.

**Comment by dongahn** [comment]
@grondo: I can quickly run this through PerfExplore for sched compatibility and performance improvements on this experimental branch. Is this good time to do this?

**Comment by grondo** [comment]
@dongahn, let me just check to ensure this branch even works with flux-sched.

**Comment by dongahn** [comment]
Got it.

**Comment by grondo** [comment]
Ok, I've rebased this branch on current master and squashed some of the latest incremental work.

**Comment by grondo** [comment]
Interesting, the `cppcheck` in travis is hanging on this branch. Something to look into...

**Comment by grondo** [comment]
Ok, I guess the cppcheck failures were just intermittent

**Comment by grondo** [comment]
Rebased on current master

**Comment by garlick** [comment]
I'll go ahead and merge - great work here @grondo.

**Pull request merged**
