### PR TITLE
libjsc [WIP]: avoid stalling sched thread on synchronous RPC

### PR DESCRIPTION
**Pull request by garlick**
I'm going to be out quite a lot this week so I wanted to park this work here in case it duplicates @dongahn or @grondo's work.

The main idea here was to break up the pattern of
* jsc invokes callback in sched on job state change
* sched calls jsc_query_jcb() which makes synchronous KVS RPC's to fetch data

This pattern blocks the sched thread waiting for back to back RTT's to the KVS module.  Instead:
* jsc internally gets callback on state change and begins async KVS fetches
* upon completion of KVS fetches, jsc invokes callback in sched
* sched calls jsc_query_jcb() to retrieve state that is already in memory

Other than eliminiting the RPC to fetch the KVS path from the job module, this hasn't been achieved yet.  Mostly what is here is cleanup and groundwork for those changes.

Any comments would be much appreciated, though it may be wise not to invest too much effort in a review at this time since this is not too far along.  I have not yet had a chance to test with the sched module.

### CODE REVIEW

**Comment by grondo** [comment]
Thanks @garlick! This seems like good work toward a valuable goal.

I'm initially concerned with the move of the `lwj.` hierarchy configuration parameters from being owned by the job module to owned by a library. For single use callers, we turn 1 RPC into either 2 or 4 to fetch/set the initial broker attributes. (probably the `job` module or some other initialization routine should be responsible for setting the defaults, or else a random third party caller of the library could accidentally set default values, or race with proper initialization).

I did think about making the jobid-to-kvs-path into a library call when I implemented support for it, but discounted that due to the correctness issues above. I apologize if I made the wrong choice.

BTW, I don't think there are any other users of the `lru_cache` code I added for this purpose so that could be removed in this PR as well.

**Comment by grondo** [comment]
Re-read my comment above and realized it comes across as more negative than I meant.

I was mainly trying to defend my previous work, and perhaps give arguments for keeping tunables like this out of libraries in the future. However, for the current target of reducing the synchronous RPCs of the scheduler, the changes here seem perfectly appropriate.

I did have one other thought on the subject though. This work was already vectoring toward turning the jsc callbacks into composite futures that fetch multiple items from the kvs in the background before returning from the reactor. Could the RPC to fetch the kvspath for any job identifier just be tacked on to the front of this composite as another async fetch? (Just an idea and probably not worth pursuing for now)

**Comment by garlick** [comment]
Thanks!

On the race, it does seem less than satisfying having multiple writers in different users of that new library call, but I'm not sure it introduces a new race per se, since the racing users would all be attempting to write the same default values.

We could hide the fetch of the path prefix with the other fetches, although the path fetch has to be complete before the other fetches can start, since it's used to derive the keys.

I'll keep thinking about it - maybe there is a better solution to this problem that dovetails with our new execution system design with the private namespaces.

**Comment by grondo** [comment]
I meant racing with another out-of-band writer writing something other than
the default... (maybe allowing tunables was the mistake?)

I think the new execution service should probably implement a more
traditional get-jobinfo RPC which would have most of the common job data
returned to the caller, hiding the kvs-path, namespace, or even the fact
that the data is kept in the kvs from most callers.

**Comment by grondo** [comment]
> We could hide the fetch of the path prefix with the other fetches, although the path fetch has to be complete before the other fetches can start, since it's used to derive the keys.

Isn't this the point of event based programming? In the callback that sets the kvs-path, you issue the kvs fetches, which when complete can generate or wait for other events. (in fact you wouldn't even have to store the kvs-path anywhere it can just be used in the callback itself).

**Comment by garlick** [comment]
Yeah, I was just pointing out that the latency from the submit to the scheduler getting a callback would be RTT of path fetch + RTT of parallel KVS fetches, instead of just the latter if the path can be computed. 

But you are absolutely right, we don't care if that takes an extra millisecond!  The scheduler won't be blocked since this is all happening via continuations.

I probably should back that part out of this PR then.  No need to go crazy with changes that have low impact and won't carry forward to the new design.

**Comment by dongahn** [comment]
> I think the new execution service should probably implement a more
traditional get-jobinfo RPC which would have most of the common job data
returned to the caller, hiding the kvs-path, namespace, or even the fact
that the data is kept in the kvs from most callers.

Is this the role of the execution service though? When we envision this, we wanted to have `job-ingest` module to suck in a jobspec and store it to either content or kvs. Job-info RPC can be services out of that module. Our sketch is documented in the confluence WIKI in case you have access to our internal confluence wiki. 

https://lc.llnl.gov/confluence/display/FJSI/%28Phase+1+Task+1+Deliverable%29+Scheduler+Functional+Design+in+Support+of+S4

**Comment by grondo** [comment]
Good point @dongahn, I think I was just not being careful with terminology

**Comment by garlick** [comment]
I'll plan to rebase and rework this after #1389 goes in.

**Comment by garlick** [comment]
This is going to need to be seriously reworked so I'll close this PR and try again later.

**Pull request closed without merging**
