### PR TITLE
kvs: support removal of a KVS namespace

### PR DESCRIPTION
**Pull request by chu11**
This PR adds the ability to remove a KVS namespace.  The primary trickiness was determining how the removal of a namespace could affect asynchronous rpcs.  e.g. what to do if a lookup began when a namespace was legal, but the namespace is removed before the lookup can complete.

Ultimately, I decided to return ENOTSUP in this situation.  It is the same error code that would be returned if the user had specified an illegal namespace.  So to rpc client, they can view this as a simple error that a namespace was illegal.  The user wouldn't know (and it shouldn't matter for them to know) if when the namespace became illegal.

### CODE REVIEW

**Comment by chu11** [comment]
hit a #731, restart builder

**Comment by chu11** [comment]
Hmmm, haven't seen this build failure before

```
PASS: t0015-cron.t 17 - flux-cron event --min-interval works

No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
```

Presumably the test ```flux-cron can set timeout on tasks``` is the one that failed.  It has a short 0.1s timeout, perhaps that was hit?

**Comment by chu11** [comment]
diff coverage is unsurprisingly not that great.  Lots of error paths that aren't coverable.

I considered writing a stress test to try and catch several of the "the namespace disappeared on me" cases.  But it's just be a ton of "create-namespace, do something that you know isn't cached, remove a namespace" over and over again trying to hopefully hit the race.  But since there is no guarantee of hitting it in any particular run, I elected not to.

**Comment by garlick** [comment]
Just a quick general comment on the semantics of remove:

It's hard to make any guarantees about when a namespace is "gone" in our design.  In this PR, removal from ranks > 0 is based on an open loop event.  Down the road we had talked about namespaces being kept in a temporal cache on ranks > 0.  In other words, even after the remove RPC has finished, one may still be able to perform operations on the namespace for a brief time.

IMHO this is OK, and we just need to document it.  For the use case we are planning for (jobs have their own namespace), we just need to ensure that namespace removal doesn't _start_ until there is no possibility of the job continuing to use it.

If we accept that removal is "eventually consistent" then there is no need to ensure that operations (other than commit) racing with remove get an error.

**Comment by garlick** [comment]
A watch on a namespace that is removed should get exactly one error response.

I didn't see offhand that responses were being generated for all the watchers in the watchlist upon namespace removal?  That should happen, but then we should make sure that a stalled watch request cannot send another response after the first one has been sent...

**Comment by chu11** [comment]
Doh!  I realized there's a huge mistake in my PR.  If a kvsroot is removed, the kvsroot object is freed.  So we can't use that pointer anymore, wherever it may be stored.

Not too hard to fix/deal with on lookups.  But the commit code is a little trickier.  B/c on remove the commit manager for the namespace is also destroyed.  Several ways to deal with this, but gotta figure out best way.  This is trickier than I had thought it would be.

**Comment by chu11** [comment]
And I also need to handle sending errors to commits that have been submitted, but have not yet begun processing b/c its in the commit queue.  Oh boy ... I didn't think this all through

**Comment by chu11** [comment]
Just re-pushed.  This is the new implementation of namespace remove.  Instead of removing a namespace after a user has requested a remove, a namespace is instead marked for removal.  In the background, cleanup occurs and the namespace is fully garbage collected in the heartbeat callback once the cleanup has finished.                                                                                                
                                                                                                                                       
The big patch is 445579c60390b5c67b0b8fce89973435922f70c8.  There's some code I wish to make better, but I think this is good for the time being.  For example, you can't call ```zhash_delete()``` while                                                                         
iterating through a hash.  I think this could be abstracted away in some ways later on.  I use a temporary "removelist" in several places to deal with this, which is sort of ugly.                                                                                              
                                                                                                                                       
A number of new tests in ```t1004-kvs-namespace.t``` are somewhat nuanced/detailed.  Hopefully the comments makes sense.  I know that I have a bajillion helper functions in t1004.  That should be cleaned up in some way in the future (should share code with ```t1002-kvs-watch.t``` too).

**Comment by chu11** [comment]
re-push, fixed a mem-leak and a logic bug in cleanup path travis found

**Comment by chu11** [comment]
hmmm, one stalled build.  Unsure.  Restarting.  Also restarting a build that hit #1025.

```
PASS: t0015-cron.t 21 - module load with sync

No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
```

**Comment by garlick** [comment]
I think this is OK to go in.  Do you concur @chu11?

**Comment by chu11** [comment]
yup, just let me squash.

**Comment by chu11** [comment]
hit a #731, restart build

**Comment by garlick** [comment]
Nice work @chu11 - merging.

**Pull request merged**
