### PR TITLE
cleanup files on exit

### LINKED ISSUE #71: cmbd leaves files in /tmp
cmbd makes no effort to remove $FLUX_TMPDIR, its pid file, its api socket, or its request socket on exit.  These things pile up after a while.

### PR DESCRIPTION
**Pull request by trws**
Added a utility API to clean up state on process exit.  Currently does files
and directories, cleaning up the API socket, broker pid file and directory on
exit from the broker.

It's probably overkill to set it up this way, but I have a feeling there will be more uses for this as time goes on.

fixes #71

### CODE REVIEW

**Comment by garlick** [comment]
This is useful!

Minor but [RFC 7](https://github.com/flux-framework/rfc/blob/master/spec_7.adoc) says function typedefs should be pointers and end in _f.

Had you converged on a session URI listing utility that should be part of this PR?

**Comment by trws** [comment]
I'll fix that up.  It occurred to me that I should change the signature around a bit anyway.

I have something for the session listing but it needs a fix to the infinite loop on open, and it should be converted into an actual command, plus have a sanctioned way to select one from the flux come end. I'll take a look at it after lunch and see how much that would actually take.



Sent with Good (www.good.com)

________________________________

**Comment by grondo** [comment]
I think `cleanup.h` needs to be added to `Makefile.am`.

Also very minor, but my preference would be for method names to match the module its coming from, so maybe `cleanup_add` or `cleanup_push` vs `add_cleanup`. However, I don't really care too much about that.

I do have one other question. `atexit()` will handle normal program termination case only. Why can't normal broker/modules exit path handle this particular cleanup?

**Comment by trws** [comment]
I added it to the make file as part of libutil, if that isn't in there it was a commit mistake.

Good point on naming, I'll address that when I go in to fix up the signatures.

I don't see why it can't, but atexit works on return from main or call to exit. It won't happen on a segfault or hard kill, but do we have something that will?  If we do I'll certainly use that machinery.



Sent with Good (www.good.com)

________________________________

**Comment by garlick** [comment]
@grondo I'm not sure we ever really use the normal broker exit path.  Instead we call exit from the shutdown timer handler.  That's a bug (#25) but it's the current state of affairs.

**Comment by trws** [comment]
Maybe I should wire it into both? It wouldn't be a problem if you point me to it.



Sent with Good (www.good.com)

________________________________

**Comment by garlick** [comment]
Unless I missed something I think atexit() covers the shutdown timer exit as well as the normal broker shutdown path and various other places where we encounter fatal errors and exit.

**Comment by grondo** [comment]
Yes, I was wondering if we a systemic problem with no well constructed exit path. If you guys are fine with `atexit()` cleanup that's fine with me too.

**Comment by garlick** [comment]
We do have a problem, but I think it's not a small job to fix #25.  There may be additional cleanup of the exit path required that's not been identified as well (some may get fixed as a natural consequence of converting the broker from zloop to libev).  I guess I am fine with deferring that for a bit more and solving this problem now, as proposed,

**Comment by garlick** [comment]
@trws said in #277 
> By the way, don't block anything on the file cleanup PR, there's a weird corner case I need to track down before that can be merged. You wouldn't happen to know of anywhere that we fork, then exec the parent instead of the child would you?

> I'm also trying to track down where the *-event and *-req files are created, it looks like zmq creates them but the standard cleanup procedure doesn't seem to be documented with those bind functions, which makes me wonder.

Yes those files are created by zeromq but I'm not sure if in the bind or connect path.  Zeromq's asynchronous connect (where server or client can go away and come back and this is hidden from the other end) may result in neither end claiming responsibility for cleaning up.  Anyway I'm not aware of a standard cleanup procedure.

**Comment by trws** [comment]
For now, the event file is cleaned up when rank 0 exits, and each rank cleans up its own req file on exit as well.  That's on the theory that if the process is dead, the file is probably not necessary.  At least for me, this now cleans up every file created by flux, a `make check` leaves nothing behind anymore.

**Comment by garlick** [comment]
I'm wondering if `flux-attach` is duplicating `flux --uri cmd`?  Also, would it be more useful to spawn a shell using the exec service in the instance that's being attached to?

**Comment by trws** [comment]
I was wondering the same thing while writing it honestly, I'll describe why I decided to implement this and we can discuss how to proceed from there.  The --uri option does what is needed in terms of targeting a uri, but lacks the option to find a local session by SID or just find an arbitrary one. Assuming that were added, it would be fine to use exec for non-interactive commands, but attach allows a user to interact with a flux session without having to give up a direct connection to the PTY.  If we added an option to exec to get a full pty, perhaps wiring up an ssh or similar connection piped over the overlay, or just to exec in the environment without wrapping, that would do the job.

**Comment by trws** [comment]
I forgot one reason, attach allows a user to run a local command that may connect to a remote flux, where exec would run the command under the remote flux.

**Comment by grondo** [comment]
I think I see your point, @trws, that there could be justification for both methods of interacting with an instance. I'm wondering if the `attach` name might be misleading, though. Really the current `attach` is a kind of convenience command that sets up some environment and runs a command (or perhaps shell), which allows a series of commands to interact with a flux instance without a lot of extra args. I don't have a better suggestion than `attach` at this point though.

I do think there is also a strong case that an interactive shell *within* the instance is also needed. (Think about the case where a flux instance is a container) I really like the idea of granting ssh access, but also `flux exec` (and the wreck replacement) should support ptys. It would also be nice if we could optionally start initial program under tmux and support remote attach.

**Comment by trws** [comment]
tmux would be a nice option.  If at all possible, I would really, really like to avoid us having to support a home-grown remote pty.  We should be able to set up any number of ways to get one without having to write one ourselves, but the main reason for this is that every one I've ever used, including the SLURM one, is broken in at least one if not many corner-cases that break my environment.  As it stands I frequently have to kill SLURM sessions because the pty gets confused by a control character it doesn't know how to support, and starts eating my keystrokes...

**Comment by grondo** [comment]
Good point. However, it might be tough to support under parallel launch case, which we must support because there are some parallel apps that need a pty on rank 0. However, that is a corner case that maybe we can special case, or perhaps I'm not thinking big enough...

**Comment by trws** [comment]
I think the challenge is if we need to provide both a PTY and a log of the PTY at the same time.  If we provide a facility for a PTY that a user can connect to, but that does not get logged, would that accomplish the goal?  We could get there with a screen or tmux session to which we could forward a connection over a well-established protocol like rsh or ssh and connect the user.  That way we don't actually have to maintain one.  If it has to go through the kvs... well, that would be more of an issue.  We might still be able to do an out-of-band logging out of it actually, but a user wouldn't be able to attach to the log channel and expect a correctly set-up PTY.

**Comment by garlick** [comment]
I think you missed the 'snoop' socket @trws.  A hook is need in `src/broker/snoop.c::snoop_bind()`.  This socket is only created on demand when you run `flux-snoop` so I can see how it would have been missed.

Rebase suggestion:
* one commit that adds util/cleanup (including Makefile.am and subsequent fixes)
* one (or more) commits that adds the hooks
* one commit for each util

I am OK with flux-attach for now, but I think we should contemplate incorporation of this into flux.c at some point.

**Comment by trws** [comment]
Agreed on all points @garlick.  I'll add these to my list of flux to-do items.

On this topic, I've done plenty of rebases, but not a great deal of per-file cherry picking.  Do you have a preferred method for splitting commits that way?

**Comment by garlick** [comment]
This is one part of the workflow that is not ingrained for me, so I try to avoid it in the first place, and generally have to look it up when I do need it.   Search for "SPLITTING COMMITS" in the [git manual](http://git-scm.com/docs/git-rebase)

**Comment by grondo** [comment]
@trws, I make heavy use of git interactive rebase, and split commits by marking them for "editing". If you get into a pickle you can always use the reflog to get back to some known state so I don't get too nervous if I mess up a few times first. :-)

**Comment by grondo** [comment]
> I am OK with flux-attach for now, but I think we should contemplate incorporation of this into flux.c at some point.

I'd argue just a bit more strongly against adding a new `flux` subcommand if we plan on getting rid of it later. At a certain point, once you add commands people will write scripts and tests using them and it will make it difficult to remove the command *ever*. I'm not opposed to a new subcommand here (though I'd prefer a different name than `attach`, which to me sounds more like you're actually attaching to a session), but if it is fairly easy to add this functionality to `flux.c`, why don't we do that now?

**Comment by trws** [comment]
So, all it really does is use some of the machinery from list-instances to find a session if one is available, set up the FLUX_URI environment variable, then invoke the command sent to it.  As it is, `flux.c` does the vast majority of the work, so having it all there would be fine or really moving the attachment behavior there would be preferable, but it appeals to me to have a sub-command for "run local process that is not itself a flux command in the specified flux environment/session."  That could be an argument on `exec`, or perhaps `run`, or even just a flag to `flux` I suppose, it just seemed wrong to run `flux /usr/bin/ls -l` or similar since without a `/` that would be a command error.

**Comment by grondo** [comment]
@trws -- good points. I understand the use case, and I definitely see your point that just using `flux /path/to/my/command` is odd enough that it would confuse people.

I think we have a bit of a gray area here between "run a process in the session" vs "run a process with an environment such that by default flux commands use this session." The second case should definitely be allowed, but I can see @garlick's point that since `flux.c` already does exactly this maybe it should just do the work. Should we have the ability to have some "builtins" commands directly in `flux.c` for this case? (Essentially in this case it would change the search path for "commands" to the current `PATH`?)

**Comment by grondo** [comment]
The gray area is also why naming the subcommand is a bit tricky -- `run` and `exec` both make sense in the context of "this is in a command driver", but in the context of the flux framework as a whole they (might) implicitly be understood to mean "run within the current or a named flux session" (to me at least). Since parallel workloads is our game we should weight the naming on that side of the scale I'd think.

**Comment by trws** [comment]
I completely agree.  What I had been kicking around for a while was calling it `env`, in an attempt to invoke the behavior of the standard utility of the same name.  Either print the flux environment to the terminal, or run the subsequent command with that environment in effect, but for a reason I can no longer seem to remember I thought that didn't work either.

**Comment by grondo** [comment]
@trws .. oh I kind of like that one. It could also have a mode to pass to `eval` (e.g. like `ssh-agent` or `luarocks path`)

**Comment by garlick** [comment]
You guys are onto something good here I think.

**Comment by trws** [comment]
Good point, it would be a pretty easy add-on as a builtin to `flux.c` as well if we want that. Just extend the `dump_environment` function a little bit and adjust the output formatting, invoke the command if there is one with the same machinery as a sub-command, etc.  Alternately it could be a re-work of attach that drops the arguments for locating a session and just does environment management.  The user-facing interface would be the same either way most likely, just a question of whether we want a standalone flux-env or not I suppose.

**Comment by grondo** [comment]
btw, many of the `git` subcommands are "builtins" that are semi-pluggable, e.g.

 https://github.com/git/git/blob/master/builtin/add.c

we could do something similar for `flux` command and make it easy to extend with more builtins in the future (if even more builtins make sense, I'm not sure about that)

**Comment by trws** [comment]
@garlick,@grondo: I find myself writing an environment handler for the env setup in the cmd driver, but it doesn't feel quite right.  What do you think of having the environment be a property of the flux config?  It seems like a reasonable fit there, but before I move things around like that I wanted to run it by you.

**Comment by garlick** [comment]
Is there a particular command usage you are considering that fits better in flux-config?  I liked the flux-env idea in the abstract at least.

**Comment by trws** [comment]
Ah, that came out wrong. I like having env as a command best by far of the options so far. What I meant is that the flux config struct and API seem like a sensible place to construct and hold the flux configured environment rather than holding it just in the driver.



Sent with Good (www.good.com)

________________________________

**Comment by grondo** [comment]
I think I kind of understand where you are going with this, but I'd stop short of holding *all* the environment there. The `flux` command driver is just modifying the current environment (at least in the current instatiation), and it makes sense for the additions and unsets to come from there... but you are suggesting to copy *all* the environment there (maybe under `global.environment`)?

I guess I can't think of an argument against that, and actually I've had thoughts of pushing the "instance environment" into the kvs, but I think this maybe needs a bit more thought before moving forward.

Interesting idea though (If I've got it right)....

**Comment by trws** [comment]
I was really just thinking of storing a hash of the environment variables that are adjusted by flux in some fashion. That way it can be re-used and we don't have to have things like the dump_environment function that have an out of band list of environment variables independent of the ones actually set and anything can check what the config system thinks the environment should be. It would probably include what the user had in some of those variables, but I wasn't planning on pulling in anything other than what flux sets or unsets.



Sent with Good (www.good.com)

________________________________

**Comment by grondo** [comment]
I may be missing something, but that seems reasonable to me! (and a good improvement)

**Comment by garlick** [comment]
Yeah go for it!

**Comment by trws** [comment]
Ok, this now contains an environment manager in config, an `env` command that does what the name implies but could easily be extended to generate eval-able results, and a complete file cleanup setup.  Assuming everything passes, I think this is pretty well good to go.

**Comment by grondo** [comment]
Oh, this looks nice.
I really like the `flux_conf_environment` changes. Huge improvement.
 
Some cleanup required before merging:

 * commit 015365d3314ef020461c91b48ed324230b6d120f which adds `flux env` shouldn't touch ancillary files like `.gitignore` and `INSTALL`. The `.gitignore` update is good though and should be in its own commit.
 * Also some python bindings changes ended up in that commit? I haven't reviewed the code to know if this is necessary, but it would be nice to split those out.
 * file cleanup commits could probably be squashed together. Or if you prefer them separately I'd like to see
    - commit adding cleanup list interface
    - One commit per subsystem adding support for cleanup (or all together as you prefer)
 * The transient `attach` command should be squashed out of the history ;-) (Unless I'm mistaken and `flux-attach` doesn't only exist in this PR)

Ideally for the `env` command it would be nice to see the commits separated such that
 1. a commit or set of commits that add the cool new `flux_config_environment` interface
 2. a commit that adds the `flux env` command
 3. users of `flux env` updated
 4. vestigial code (like flux-python) removed.

I know this is kind of big reordering, which is why I said "Ideally". I'd be willing to merge something more monolithic to save busywork, but in the future we should strive for logical sets of commits like the above (my opinion only)

There is also two things going on in this PR. The file cleanup stuff is sorely needed. Maybe we could isolate the file cleanup stuff in this PR and merge that now, then open a new PR for the `flux env` stuff?

**Comment by trws** [comment]
Much of that I can clean up.  The python binding rework is a direct result of the change in output formatting of the `verbose` option of the command driver, which in turn is a result of using the printing machinery that I put in for the env command, so that should stay tied in.

INSTALL was not an intentional change, it must have been replaced by an `autoreconf -i`.  It doesn't have to stay, but it is the updated version of the generic autotools file, *shrug*.

**Comment by trws** [comment]
Ok, I just finished a slightly crazy rebase.  Everything passes, so I think I got it, but this is the first time in quite a while it actually took `add --patch` to get everything split out the way I wanted it.  Anyway, I think I hit all the points, except that 3 and 4 from the env command list are together because the tests can't pass unless the python stuff is updated to parse the altered output from the command driver.

**Comment by garlick** [comment]
This looks good!  The only nit I have is that the local connector changes are mixed in with the libutil cleanup on exit commit df83159.  Those should be split out to a new commit with a comment explaining why connect retries logic need to change.

**Comment by grondo** [comment]
Nice work!

heh, I hate to add anything else to this PR but it would be nice if there was a test added for `flux env` and perhaps even `list-instances` (though that might be a bit tricky to implement).

We could also just open an issue to add those tests at a later date, but throwing in some basic smoke tests might be good for now.

**Comment by grondo** [comment]
@trws if you are busy on other stuff I could volunteer to try building some basic tests.

**Comment by trws** [comment]
Either of those should be relatively easy to test actually, but I am not terribly familiar with setting up the sharness tests, and would definitely appreciate the help if you have the time.  At least for list-instances I could add it to the python harness and have that run doctests, which would also document the command, but I have a feeling that adding it to the external scripted harness would be better.  The general frame, at least for that, would be to run a couple of flux instances with known tmpdir and sid settings and ensure that they are located.  Env is a bit more tricky I guess, since its output depends on the built in defaults, but ensuring that it prints an environment wouldn't be too hard, or having it run a flux command against a separately run instance in a known location would do the job too.

I'm trying to convince myself not to do it right now, because it's not immediately necessary, but after doing this I'm very very tempted to add a common config building/environment interpretation interface into config.  Most of my projects are set up so that usage docs are printed based on the argument specification, so they can't go out of sync, and automatically accept `<PREFIX>_<arg>` as environment variables in place of the command line argument to cause the same result, frequently also supporting the same in the config-file format, all generated off the same specification and using a common ingestion infrastructure.  Would be nice to build this into flux also, but it's a bit harder in C than C++, especially to make the argument specification decentralized.  I'm going to at least add a centralized environment variable interpreter that we can invoke to do sensible boolean/integer/string ingestion, since that's fast, but maybe when I get bored sometime I'll look at doing some of the rest.

**Comment by trws** [comment]
The local changes are now broken out, I also added a way to set the count by an environment variable, and did a bit of cleanup in `env.{c,h}` while at it.

**Comment by grondo** [comment]
Nice. The `env.c` changes should also be in their own commit instead of mixed with the local connector changes. I'd also prefer to split commits with fixes from commits with new features -- not exactly critical here but if we could vector toward that in the future (it makes things like cherry-picking, merges, etc much more sane, and also just makes the general flow of history much easier to follow)

I have a couple tests for `flux env` in  my branch (really just sanity checks). It appears executable perms are missing on `flux-list-instances` -- so it doesn't work out of the box on your branch.
When I do `chmod +x` the command, though, I get python errors (just a path issue?)

```
grondo@flux-core:~/workspace (file_cleanup) $ src/cmd/flux list-instances
flux: `list-instances' is not a flux command.  See 'flux --help'
grondo@flux-core:~/workspace (file_cleanup) $ chmod +x src/cmd/flux-list-instances  
grondo@flux-core:~/workspace (file_cleanup) $ src/cmd/flux list-instances
Traceback (most recent call last):
  File "/home/ubuntu/workspace/src/cmd/flux-list-instances", line 6, in <module>
    import sys, os, re, flux.command_helpers, argparse
ImportError: No module named flux.command_helpers
grondo@flux-core:~/workspace (file_cleanup) $ 
```

**Comment by trws** [comment]
Ok, I can split that out, and fix the exec permission, I'm not sure how 
that even happened.  The issue you're seeing is that I don't have it 
adding the build-tree path to the `PYTHONPATH` by default.  If you try 
it from an installed version, it should work.  Perhaps I should add some 
logic to the environment handling to add the build tree versions of 
paths if it appears to be running from the build tree?

**Comment by grondo** [comment]
> Perhaps I should add some logic to the environment handling to add the build tree versions of
paths if it appears to be running from the build tree?

This is done via the config for the Lua paths for example. In-tree Lua paths have the builddir embedded, but installed config does not. It would just be a matter of editing `etc/flux.conf.in` I think...

**Comment by grondo** [comment]
Ah, we probably want a `flux-env(1)` manpage too. I can also do that if you want (it will be very simple)

**Comment by trws** [comment]
Turns out there was a bit more to the PYTHONPATH issue.  I had the build system set up to copy the libraries and python files into place for a check, but not for a regular build, so that had to be re-worked a bit.  I think the rest is now dealt with, including a manpage for each of the two commands.

**Comment by grondo** [comment]
Oops looks like headers are swapped in the manpages. (flux-env says flux-list-instances and vice versa) :-)

Otherwise, I'd be inclined to commit this and then I'll add my simpleton tests in a new PR, plus some other very minor fixes. @garlick does that sound ok, or would you prefer I do a PR against Tom's branch?

**Comment by trws** [comment]
Doh! Quite right, retroactively fixed.

**Comment by garlick** [comment]
New PR is good with me.  Thanks.

**Comment by grondo** [comment]
Merged, Thanks!

**Pull request merged**
