### PR TITLE
drop compat.h from internal <flux/core.h>

### PR DESCRIPTION
**Pull request by garlick**
This PR contains drops compat.h from the internal `<flux/core.h>` and deals with the fallout
* add missing czmq.h and system include directives
* modernize API in remaining comms modules
* directly include compat.h in lua bindings and some tests that have yet to move forward

### CODE REVIEW

**Comment by grondo** [comment]
Nice gruntwork! As part of this do you want to go through and ensure `-I$(top_srcdir)/src/include` always occurs first on `*_CPPFLAGS`, or I could do that in a separate PR.  Another solution for this could be to add a link from `$(top_srcdir)/flux` to `$(top_srcdir)/src/include/flux` since `-I$(top_srcdir)` is always first due to `DEFAULT_INCLUDES`

**Comment by garlick** [comment]
Sure I could do that.

Also, looks like my `make check` before I pushed this was run from the src subdir so there's more test code to fix.

**Comment by garlick** [comment]
Here's an example of `make V=1` in modules/kvs in my c9.io environment

Original
```
$ make V=1                                                                    
depbase=`echo kvs.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\                                                                             
        /bin/bash ../../../libtool  --tag=CC   --mode=compile gcc -std=gnu99 -DHAVE_CONFIG_H \
        -I. -I../../../config  -I/usr/include/json-c   -I/home/ubuntu/local/include   \
        -I../../.. -I../../../src/include  \
        -Wall -Werror -Wno-strict-aliasing -Wno-error=deprecated-declarations  -g -O2 -MT kvs.lo -MD -MP -MF $depbase.Tpo -c -o kvs.lo kvs.c &&\                                                                                        
```
After moving `-I${top_srcdir}/src/include` to beginning of AM_CPPFLAGS
```
$ make V=1                                                                    
depbase=`echo kvs.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\                                                                             
        /bin/bash ../../../libtool  --tag=CC   --mode=compile gcc -std=gnu99 -DHAVE_CONFIG_H \
        -I. -I../../../config  -I../../../src/include -I/usr/include/json-c   -I/home/ubuntu/local/include  \
        -I../../.. \
        -Wall -Werror -Wno-strict-aliasing -Wno-error=deprecated-declarations  -g -O2 -MT kvs.lo -MD -MP -MF $depbase.Tpo -c -o kvs.lo
```

I'm not seeing evidence of the default `-I${top_srcdir}` at the beginning which would allow the symlink to work.  Or is that hidden by the libtool wrapper?

**Comment by garlick** [comment]
Oh, maybe because we're resetting AM_CPPFLAGS in that Makefile e.g.
```diff
diff --git a/src/modules/kvs/Makefile.am b/src/modules/kvs/Makefile.am                                                                  
index 3ce8c42..d3a2c0b 100644                                                                                                           
--- a/src/modules/kvs/Makefile.am                                                                                                       
+++ b/src/modules/kvs/Makefile.am                                                                                                       
@@ -6,8 +6,9 @@ AM_LDFLAGS = \                                                                                                          
        $(CODE_COVERAGE_LDFLAGS)                                                                                                        
                                                                                                                                        
 AM_CPPFLAGS = \                                                                                                                        
+       -I$(top_srcdir)/src/include \                                                                                                   
        $(JSON_CFLAGS) $(ZMQ_CFLAGS) \                                                                                                  
-       -I$(top_srcdir) -I$(top_srcdir)/src/include                                                                                     
+       -I$(top_srcdir)                                                                                                                 
                                                                                                                                        
 #                                                                                                                                      
 # Comms module     
```

**Comment by garlick** [comment]
Meh.  I guess I vote we defer the AM_CPPFLAGS_* changes to another PR.

**Comment by grondo** [comment]
Fine by me. Ready to merge this one?

**Comment by garlick** [comment]
Yep.

**Comment by grondo** [comment]
Hm, content flush timed out when master was [built](https://travis-ci.org/flux-framework/flux-core/jobs/108906084)-- is the timeout long enough for Travis?
```
expecting success: 
        run_timeout 10 flux content flush &&
        NDIRTY=`flux comms-stats --type int --parse dirty content` &&
        test $NDIRTY -eq 0
Alarm clock
not ok 21 - flush rank 0 cache
```

**Comment by garlick** [comment]
Yes we can always bump that one up.  Maybe the upper limit limit on instance size in test we discussed will help too.

**Pull request merged**
