### PR TITLE
Slc no rebase

### PR DESCRIPTION
**Pull request by trws**
This is a re-work of PR #192.  The git contortions necessary to make this thing work pulled it out of phase with that PR.  I think everything is now building in order, the biggest change is that zio and kz are now both under modules.  To keep re-defined symbols from being an issue, zio is currently built as an so, the other option is to build it as a convenience library with unresolved symbols until use.

### CODE REVIEW

**Comment by garlick** [comment]
Hurrah!  Looks good, thanks Tom.

Can we get this rebased onto the current master?  It'd be nice to eliminate the merge commit.  I will play with it if you're out of time for this, let me know (though first attempt failed miserably).

**Comment by trws** [comment]
I can do that, but that will eat what I can spend on flux until next 
Tuesday.  Originally started the merge as a rebase with squash actually, 
but it turned into a very complicated merge where some of the automatic 
resolution was wrong.  Give me a bit and I'll throw up a new version 
after another squash and rebase.

**Comment by grondo** [comment]
I should probably help with this since I messed things up by prematurely (and incorrectly)  moving zio into libutil.

It might work to just start from clean master and then diff -Nuar the two trees? Since the original commit is just one monolithic commit anyhow? (I'm probably missing something though...)

**Comment by trws** [comment]
The original commit is monolithic now, it wasn't in the other branch.  
If we squish the two commits in this one into one commit, then merge to 
a clean version of master, it should resolve a great deal easier, as 
long as no other changes in master depend on the forking commit.

**Comment by grondo** [comment]
Actually I was thinking something even more straightforward like the example below.
I would then be inclined to break up the resulting commit somewhat for historical purposes
(and it may make future merges easier)

```
 grondo@hype356:/tmp$ git clone https://github.com/flux-framework/flux-core upstream.git
Initialized empty Git repository in /tmp/upstream.git/.git/
remote: Counting objects: 16034, done.
remote: Total 16034 (delta 0), reused 0 (delta 0), pack-reused 16034
Receiving objects: 100% (16034/16034), 19.76 MiB | 1.03 MiB/s, done.
Resolving deltas: 100% (11454/11454), done.

 grondo@hype356:/tmp$ git clone --branch=slc-no-rebase https://github.com/trws/flux-core trws.git
Initialized empty Git repository in /tmp/trws.git/.git/
remote: Counting objects: 16235, done.
remote: Compressing objects: 100% (55/55), done.
remote: Total 16235 (delta 26), reused 0 (delta 0), pack-reused 16180
Receiving objects: 100% (16235/16235), 19.84 MiB | 3.87 MiB/s, done.
Resolving deltas: 100% (11589/11589), done.

 grondo@hype356:/tmp$ diff -Nur --exclude=.git upstream.git/ trws.git/ >patch
 grondo@hype356:/tmp$ (cd trws.git && git log -n1 --pretty="%s%n%n%b" HEAD~1) > msg

grondo@hype356:/tmp$ cd upstream.git
 grondo@hype356:/tmp/upstream.git$ git apply --whitespace=fix ../patch 
../patch:70: trailing whitespace.
lalarm_la_LIBADD = $(luamod_libadd) 
../patch:85: trailing whitespace.
tests_jsontest_la_LIBADD = $(luamod_libadd) 
../patch:107: trailing whitespace.
tests_zmsgtest_la_LIBADD = $(luamod_libadd) 
../patch:159: trailing whitespace.
	
../patch:465: trailing whitespace.
    if ((ctx->flags & FORKZIO_FLAG_PTY)) 

``` grondo@hype356:/tmp/upstream.git$  git commit -a -F ../msg --author="Thomas R. W. Scogland <scogland@llnl.gov>"        
[test a9bc48e] libflux-core.so is now stand-alone
 Author: Thomas R. W. Scogland <scogland@llnl.gov>
 23 files changed, 53 insertions(+), 2073 deletions(-)
 delete mode 100644 src/common/libutil/zio.c
 delete mode 100644 src/common/libutil/zio.h
 delete mode 100644 src/common/libzio/.gitignore
 delete mode 100644 src/common/libzio/Makefile.am
 delete mode 100644 src/common/libzio/flux-zio-test.c
 delete mode 100644 src/common/libzio/forkzio.c
 delete mode 100644 src/common/libzio/forkzio.h
 delete mode 100644 src/common/libzio/kz.c
 delete mode 100644 src/common/libzio/kz.h
```

**Comment by grondo** [comment]
Also, on this branch it seems `make check` before `make` or `make all` doesn't work. The build somehow goes down into `src/modules` before building `libflux-internal.la`. I have to look at it a bit more before I understand it fully

```
make[5]: Entering directory `/tmp/trws.git/src/modules/kvs'
  CC     libkvs.lo
  CC     conf.lo
  CC     proto.lo
  CCLD   libkvs.la
libtool: link: cannot find the library `../../../src/common/libflux-internal.la' or unhandled argument `../../../src/common/libflux-internal.la'
```

**Comment by grondo** [comment]
Ah, during `make check` we traverse into `src/modules/kvs` as part of checking libflux due to this rule:
```
test_module_t_DEPENDENCIES = $(top_builddir)/src/modules/kvs/kvs.la

$(test_module_t_DEPENDENCIES):
        @cd `dirname $@` && $(MAKE)
```

Perhaps `test/module.c` should be moved to system tests under `/t`?

**Comment by trws** [comment]
That is very possible, make check appears to have extra targets to build all the deps from any sub-directory.  While a good idea in principle, they cause parallel builds to go out of order in some really unexpected ways by running extra make processes out of band.

**Comment by trws** [comment]
Yeah, we should probably collect all the tests that depend on other trees that way.  This is the kind of thing that would be solved by switching to an include-based make system like you suggested before @grondo, we're getting to the point that it might actually be worth it.

**Comment by trws** [comment]
So, should I do this as a re-base or would you like to rework it as a patch @grondo?

**Comment by garlick** [comment]
That test just needs a dummy module.so to poke at, not specifically the kvs.  We should build one as a `check_LTLIBRARES`.  Don't move it, I'll fix that soon.

**Comment by grondo** [comment]
> So, should I do this as a re-base or would you like to rework it as a patch @grondo?

I would rather not waste your time on this @trws, but since it is your work you get to decide. 
I'm happy to do it -- the result should be almost exactly the same as a rebase + squash. Like I said, I might split the commit at some obvious places (like the `.travis.yml` change, first of all)

I'll push something to a branch and notify you here so you could check it out

**Comment by trws** [comment]
That sounds great if you would @grondo, having it broken into a set of logical but compiling (unlike most of the original patches...) commits sounds like an especially good idea.

**Comment by dongahn** [comment]
Please let me know when the churn is reasonably over. I would like to mold JSC into the new structure and create a PR. I have not been able to follow all the discussions because of the flurry of other activities.

**Comment by grondo** [comment]
Ok my first attempt is in my [trws-build-fixes-breakout](https://github.com/grondo/flux-core/commits/trws-build-fixes-breakout) branch. 

I still need to do a bit of testing, but this branch is reasonably the same as the branch in this PR. I tried to split the changes into logical, compiling chunks. I did ignore some whitespace-only changes, but @trws if you feel strongly about these we can add them on as a separate commit, separating whitespace fixups from actual changes.

@trws, since you are listed as author on all these commits, you should probably give the ok :wink:

**Comment by trws** [comment]
It looks good to me. Some rough edges remain on the check targets, and I probably missed some places where the convenience libraries under src/common are used directly, but I think it accomplishes the goal of the original issue.  Thanks for breaking this out @grondo!

**Comment by grondo** [comment]
OK if I create a new PR?

**Comment by trws** [comment]
Go for it. I'll close out the two vestigial ones once it goes in.

**Comment by trws** [comment]
addressed in #200

**Pull request closed without merging**
