### PR TITLE
use config file for access policy

### PR DESCRIPTION
**Pull request by garlick**
This PR configures access policy using a TOML config file read by `connector-local`.  In its absence, policy is instance owner only.

I opted to go really simple in this PR.  There are just two boolean options:
```toml
[access]
allow_guest_user = true
allow_root_owner = true
```
If `allow_guest_user` is set, then guests are allowed access with the `user` role.

If `allow_root_owner` is set, then root is allowed assigned the `owner` role.

The userdb and the `flux user` command are removed.

I've manually tested this on a system instance.  Still pondering what tests can be added to the test suite, but wanted to see if the simple approach was going to be acceptable before going too far down the road.

This is based upon PR #2866

### CODE REVIEW

**Comment by grondo** [comment]
FWIW, I like this simple approach. Seems like it could easily be extended in the future with new config keys, e.g. `allow-guest-groups`, etc.

I guess one very minor question is that we now have a mix of underscore and dash delimited config identifiers popping up. Is there a reason to use underscores, e.g. will the config keys be turned into identifiers in some higher level language? I would lean toward dashes for readability and consistency with broker attributes unless there's a reason to go with underscores. (and if so, we should update job-exec config parameters)

**Comment by garlick** [comment]
> I like this simple approach. Seems like it could easily be extended in the future with new config keys, e.g. allow-guest-groups, etc.

Sounds like we are on the same page then.  Thanks!

> Is there a reason to use underscores

That was unintentional.  Will change to hyphens.

**Comment by grondo** [comment]
Hey, I tried this out and it works great!

**Comment by garlick** [comment]
Rebased now that #2866 was merged.  Also changed the TOML keys to use hyphens instead of underscores.

**Comment by grondo** [comment]
Tested out on my system instance install and working as advertised.

Set merge-when-passing if you're ready. Thanks.

**Comment by garlick** [comment]
OK, thanks!

**Pull request merged**
