### PR TITLE
Add broker.pid attribute to broker, Fix broker corner case with scratch-directory-rank

### PR DESCRIPTION
**Pull request by chu11**
Per issue #839

### CODE REVIEW

**Comment by garlick** [comment]
This all looks good to me.  Want to throw in a fix for this error message typo (sort of related I guess)
```
lt-flux-broker: could not initialize ankdir: No such file or directory
```

**Comment by grondo** [comment]
Look great to me too, thanks!

Very minor, but if you are going to do a little more work on this one, perhaps fix the commit message typo in 42ef88e :

> cat /proc/$(flux getattr broker-pid)/status

Should be `"broker.pid"` not `"broker-pid"`  (I think?)

**Comment by chu11** [comment]
@garlick Ahh good eye.  Will fix up.
@grondo Thanks for the catch, I blindly copied from the issue tracker.

**Comment by grondo** [comment]
> @grondo Thanks for the catch, I blindly copied from the issue tracker.

Oops, sorry about that -- probably my fault then!

**Comment by chu11** [comment]
oops, found one other commit message typo.  Re-pushed.

**Comment by garlick** [comment]
Thanks!  Merging.

**Pull request merged**
