### PR TITLE
libflux: add flux_get_conf()

### PR DESCRIPTION
**Pull request by garlick**
As discussed in #1295, this adds some rudimentary support for configuring flux with a directory of TOML files.  Here's the proposed API:
```c
typedef struct flux_conf flux_conf_t;

typedef struct {
    char filename[80];  // if unused, will be set to empty string
    int lineno;         // if unused, will be set to -1
    char errbuf[160];
} flux_conf_error_t;

/* Parse Flux's config files (*.toml in cf_path).
 *
 * The builtin value for cf_path (intree|installed selected automatically) is
 * used unless overridden with the FLUX_CONF_DIR environment variable.
 * FLUX_CONF_DIR may be set to a directory path or may be set to the
 * special value "installed" to force use of the installed cf_path.
 *
 * On success, return the object, saving the result for reuse on future calls.
 * On failure, return NULL, set errno, and (if non-NULL) fill 'error' with
 * details about the failure.
 *
 * The config object is destroyed when the handle is destroyed.
 */
const flux_conf_t *flux_get_conf (flux_t *h, flux_conf_error_t *error);

/* Access config object.
 * If error is non-NULL, it is filled with error details on failure.
 */
int flux_conf_vunpack (const flux_conf_t *conf,
                       flux_conf_error_t *error,
                       const char *fmt,
                       va_list ap);

int flux_conf_unpack (const flux_conf_t *conf,
                      flux_conf_error_t *error,
                      const char *fmt, ...);
```

Edit:  Since the original post I pared down the exposed API and added unit tests against `conf_*` prefixed functions that are defined only in an uninstalled `conf_private.h` header.

### CODE REVIEW

**Comment by garlick** [comment]
Force pushed with changes to limit the exposed API, add tests, and pull in the `flux_open()` change to get `flux_uri` from config, originally proposed in #1295 since it uses the interfaces developed here.

**Comment by garlick** [comment]
The slightly below par coverage is mainly due to error paths that are hard to reach (ENOMEM and such).  I think maybe this is ready for review.

**Comment by garlick** [comment]
Made another couple tweaks to hopefully bump up coverage, rebased on master, and squashed the fixups.

**Comment by grondo** [comment]
LGTM on quick review.

One question about `FLUX_CONF_AUTO`. I see there are cases where INTREE vs INSTALLED is forced by callers, but is that really necessary? Couldn't the conf system *always* use AUTO mode and we could drop the conf flags? (I had considered that idea for the previous `flux_conf_*` implementation, but never got around to trying it). I'm sure there is a good reason, just curious.

Anyway, what you have is a big improvement over before, where every caller had to dynamically determine if they were intree or not. So nice work!

**Comment by garlick** [comment]
> Couldn't the conf system always use AUTO mode and we could drop the conf flags?

I'm not sure I know the answer to that.   There are a two conf attributes that only have a meaning in one or the other context
 * `rundir` - INSTALLED sets to /run path, INTREE sets to NULL
* `keydir` - INSTALLED sets to NULL, INTREE sets to home directory curve key dir

Maybe we could just return the same value for both contexts?

I had added the special FLUX_CONF_DIR=installed hack so that one could forcibly disable the "intree"  detection and parse the system isntalled config files, since I thought we might want to do that sometimes during development. I guess that could still be done without exposing the flags in the API. 

I didn't change anything in flux(1) in part because it's one place where an actual error is reported if `executable_is_intree()` fails.  AUTO just assumes "not intree" if it fails.  Would we be causing ourselves pain if we don't catch that somewhere?

**Comment by grondo** [comment]
Thanks! Your reasoning sounds logical to me! Feel free to set merge-when-passing, unless you'd like to get others' feedback before a merge.

**Comment by garlick** [comment]
Thanks, will do!

**Pull request merged**
