### PR TITLE
kvs: doc updates, consistency fixes, new convenience options

### PR DESCRIPTION
**Pull request by chu11**
Wanted to add a simple option to list kvs entries without the values since some entries are gigantic and flood stdout.  Sometimes just want to know what entries were there.  Lead to a lot of cleanup along the way.

The new ```-d``` option I added to several subcommands was chosen b/c I likened the option to the ```-d``` option of ```ls```.  I know that may just be my weird way of thinking about it and maybe most won't think of it that way.

The subcommand option parsing could be cleaned up, but I decided to leave it be, let the code have one more "strike" before cleanup.

### CODE REVIEW

**Comment by grondo** [comment]
Oh, nice idea!

I wonder if we should open an issue to re-evaluate the command line interface to kvs in `flux-kvs` at some point, perhaps after pending rework done by @garlick? e.g. no longopts as you notice, perhaps `dir` could keep its current behavior and `ls` could just list keys, consider use of `--at=treeobj` instead of separate `*at` commands to reduce duplication of option parsing, etc. Just ideas for now...
The `-d` option seems fine to me, but I do wonder what the corresponding longopt would be.

**Comment by grondo** [comment]
Oh, @garlick beat me to it with #897!

**Comment by garlick** [comment]
Sorry just getting ready to hit the road so I don't have time to review, but feel free to make these changes in my absence.  I like the general idea where @chu11 is headed here.  I would like to get the bigger problem in #897 solved (and this does contribute to the mess slightly) but as I've been putting it off for like a dozen subcommands I won't insist it be fixed in this PR :-)

**Comment by grondo** [comment]
Sounds good to me. Since @chu11 has a good use case and we can kick the cleanup can down the road, I see no reason not to merge this.

**Pull request merged**
