### PR TITLE
build/test: fix asciidoc build in travis and run_timeout() macro + misc test fixes

### PR DESCRIPTION
**Pull request by garlick**
This is an assortment of build/test bug fixes for things @grondo and I stumbled over this morning.

There is also a bit of gratuitous cleanup in `t/Makefile.am` to avoid listing test scripts twice.

### CODE REVIEW

**Comment by garlick** [comment]
Hey @chu11, how do you like this PR?  @grondo and I are at least nominally disqualified from pressing the button...

**Comment by garlick** [comment]
Rebased on current master.

**Comment by grondo** [comment]
Actually I have one other fix that could be pushed here if that is OK @garlick.

I noticed many sharness tests are missing this code to append `--logfile` to sharness when run with `FLUX_TESTS_LOGFILE` 

```sh
# Append --logfile option if FLUX_TESTS_LOGFILE is set in environment:
test -n "$FLUX_TESTS_LOGFILE" && set -- "$@" --logfile
```

We could update the missing tests here. This really only affects Travis which runs with `FLUX_TESTS_LOGFILE` and results in the verbose test output going to `$(basename $0).OUTPUT`, so the impact is pretty low if you'd rather skip it for now.

**Comment by garlick** [comment]
Makes sense to add that here IMHO.

**Comment by grondo** [comment]
hm, actually `test_under_flux` adds this option so maybe no problem here... ignore my previous comment.

**Comment by chu11** [comment]
everything lgtm

**Comment by garlick** [comment]
Thanks!

**Pull request merged**
