### PR TITLE
kvs: do not store NUL byte on json encoded strings in kvs server

### PR DESCRIPTION
**Pull request by chu11**
This is the server equivalent of PR #1262 / issue #1261.  Although not necessary, PR #1262 should probably be merged first.

### CODE REVIEW

**Comment by garlick** [comment]
Looks good.

**Comment by garlick** [comment]
One side thought (not necessarily for this PR):  on the server side, the only kind of JSON stored by the cache is RFC 11 objects.  Should the _json methods be renamed to _treeobj, and the functions for encoding/decoding/hashing moved from kvs_util to libkvs/treeobj?

There are already encode/decode functions in libkvs/treeobj although they use NULL terminated strings so we might need a variant that can work on unterminated buffers...

Anyway, that's much more change than is proposed in this PR so maybe something for later?

**Comment by chu11** [comment]
Good points. I actually started to program some of what you said above, but paused when I started to include calls to treeobj_validate(), as the function semantics sort of change by making them "treeobj" specific. I'll make a PR so we don't forget.

**Comment by chu11** [comment]
rebased and re-pushed

**Comment by chu11** [comment]
re-started a builder that was hung.

**Comment by garlick** [comment]
Great, thanks!

**Pull request merged**
