### PR TITLE
cron-o-date: cron expression support for flux-cron 

### PR DESCRIPTION
**Pull request by grondo**
This isn't quite ready yet, but I'm throwing it up here now because it may need more than usual review.

The main purpose of this work was to support cron-like date&time matching for flux-cron. Along the way a lot of other "improvements"(?)(remains to be seen) were developed to support the main goal of calculating the amount of time until the next scheduled wakeup for a datetime matching interface such as that cron expressions provide.

Furthermore, to ensure wakeup on the scheduled datetime, the [`ev_periodic`](http://pod.tst.eu/http://cvs.schmorp.de/libev/ev.pod#code_ev_periodic_code_to_cron_or_not) watcher is now exposed via a `flux_periodic_watcher`.

The kind of "date and time cron expression matching" interface is abstracted here into a small module called `cronodate`, which is simply a wrapper around an array of `nodeset_t`, one for each of the time units of interest: second, minute, hour, day-of-month, month, and day-of-week. The nodeset for each time unit can be populated with a `cronodate_set ()` using typical nodeset range expressions, or special "cron" expressions like `"*"`, `"*/2"`, etc. and for weekday and month entries, names of the days and months are accepted (like normal vixie-cron). `cronodate` then offers a `cronodate_next()` function to return the date and time of the next scheduled wakeup based on the set of times registered with the `cronodate` object.

The `cronodate` interface is then used in a new `datetime` cron entry type, and as a demonstration, a `flux-cron tab` subcommand has been added which can process crontab lines and register flux-cron jobs based on them.

e.g.
```
$ echo "25 17 * * * hostname -s # comments" | flux cron tab                                                                      
tab: cron-4 created: scheduled in 86074.583s at Sat Jun  4 17:25:00 2016
$ echo "25 17 * * Mon hostname -s # comments" | flux cron tab                                                 
tab: cron-5 created: scheduled in 258247.385s at Mon Jun  6 17:25:00 2016d
```

The `cronodate` code was placed into libutil, though I'm still not convinced that is the right choice. I'm not sure I can think of any other use cases for it, so perhaps it should go into `modules/cron` directly.

I also added a date parsing  based on `git/date.c` called [`approxidate`](https://github.com/thatguystone/approxidate). Currently it is only used for the `cronodate` tests. However, I was thinking of binding a Lua module to it and using that for a `flux cron at` interface that runs a job once at a specific time.

For `cronodate` I also needed to add one call to the `nodeset` interface. I required a way to get the next rank from a nodeset given a current rank (which may or may not be set in the nodeset), and added `nodeset_next_rank (n, r)` for this purpose.

Still TODO (at the very least) :
 - [x] man page for `flux cron tab`
 - [x] add `flux cron at`
 - [x] tests for `flux_periodic_watcher`, may need help from [faketime](https://github.com/wolfcw/libfaketime)
 - [x] tests for `flux cron tab`

### CODE REVIEW

**Comment by garlick** [comment]
Should top of approxidate.c point to git's license?

https://github.com/git/git/blob/master/COPYING

I don't see a problem dropping that in libutil

**Comment by grondo** [comment]
> Should top of approxidate.c point to git's license?

Yeah, I think that is right. I forgot to mention that I just copied it verbatim from the approxidate project

**Comment by grondo** [comment]
> I don't see a problem dropping that in libutil (approxidate that is, not git's COPYING)

Yeah, my only other thought was to have a libdatetime convenience library, as libutil is getting large and there won't be many users of approxidate or cronodate. However, I'm not sure it matters too much so I stuck them there for now.

**Comment by garlick** [comment]
Just scanned through everything and it seems good!  The at + tab subcommands will really complete the cron design.

General cron-related question (not so much specific to this PR):  if system time "jumps" (for example if the flux instance were checkpointed and restarted a week later), what will happened to cron jobs that were supposed to run while time was stopped?

**Comment by grondo** [comment]
> General cron-related question (not so much specific to this PR): if system time "jumps" (for example if the flux instance were checkpointed and restarted a week later), what will happened to cron jobs that were supposed to run while time was stopped?

As I understand it, the `ev_timer` based watcher triggers off of "relative" time, the actual time the loop is running. Thus for the `interval` type cron jobs, time would be "paused" while the job is checkpointed. Thus if an `interval` job has 10s left before triggering and the flux session is checkpointed, it will trigger (about?) 10s after the session is restarted.

The reason the `ev_periodic` based watcher was added in this PR is that `ev_periodic` is based on wall time or system time, so if you set the timeout to 24hrs, the periodic watcher will trigger when system time says it is tomorrow, same time, even if the system time jumps. Thus I *think* all `datetime` based cron jobs will trigger immediately when the job is restarted, if their wallclock trigger time has passed. I don't think libev will trigger multiple times in this case, though, even if multiple time periods have passed.

I could be missing some of the subtleties here, but this is documented pretty well in the `ev_periodic` description here:

 http://pod.tst.eu/http://cvs.schmorp.de/libev/ev.pod#code_ev_periodic_code_to_cron_or_not
  
I have to admit I don't really understand *how* libev accomplishes the `ev_periodic` watcher.

**Comment by garlick** [comment]
Thanks, that seems like what ought to happen.

**Comment by grondo** [comment]
Hm, latest Travis run hit this issue again, I can't remember if that was supposed to be fixed
```
Found ./t/t1005-cmddriver.output
expecting success: 
	flux comms info
flux-comms: flux_open: No such file or directory
not ok 1 - baseline works
```

**Comment by garlick** [comment]
I opened #677 for this.  Perhaps I should change the title to reflect the problem more than a proposed solution.

**Comment by grondo** [comment]
Sorry for the bit of noise. I'm experimenting with [libfaketime](https://github.com/wolfcw/libfaketime) for driving the date/time driven cron tests, and I was having good success on my test system. However, it does not seem to be working in Travis. (Though you can see the timestamps of flux-log messages go backwards/forwards, the cron module itself is not waking up)

Just FYI - the way I'm using libfaketime in testing is with this setup before the test session is started:
```sh
#  Check for libfaketimeMT:
LD_PRELOAD=libfaketimeMT.so.1 ldd /bin/date 2>/dev/null | grep -q libfaketime
if test $? -ne 0 ; then
    skip_all='libfaketime not found. Skipping all tests'
    test_done
fi

SIZE=1
export LD_PRELOAD=libfaketimeMT.so.1
export FAKETIME_NO_CACHE=1
export FAKETIME_TIMESTAMP_FILE=$(pwd)/faketimerc
test_under_flux ${SIZE} minimal
```

Once a session is running under libfaketime, time reported by system calls can be adjusted by writing a string of the form `"@YYYY-MM-DD HH:MM:SS"` to the `FAKETIME_TIMESTAMP_FILE`. This is shown to work in the tests by sending a flux-log message after adjusting time:

```
[1465103449.901541] broker.info[0]: nodeset: 0 (complete)
[1465103449.901582] broker.info[0]: Run level 1 starting
[1465103449.904693] broker.info[0]: Run level 1 Exited (rc=0)
[1465103449.904718] broker.info[0]: Run level 2 starting
[675993601.000734] user.notice[0]: libfaketime-test
```

On an interactive test system, this also works to force "wake up" a datetime cron job by forwarding time to the next scheduled event. However, in travis the jobs do not run, even though nominally libfaketime works otherwise.

**Comment by garlick** [comment]
That reminds me that it would be a little more useful to see those log time stamps in a more human readable format like ISO 8601 combined date and time format.

libfaketime sounds like a neat trick that could have other uses in test like simulating jobs exceeding their time limit.

**Comment by grondo** [comment]
I've backed out the faketime-driven tests for now while I continue to confuse myself as to why it doesn't work in Travis.

On this branch, I've instead added some very basic unit tests of periodic watcher functionality to `libflux/test/reactor.c`. As part of that work I realized that the libev driven "reschedule callback" needs a way to safely stop a watcher if necessary (you are not allowed to modify the loop or watcher in any way in this callback, save to add a new prepare watcher). 

So I added a `flux_watcher_stop_safe()` call, which schedules a `prepare` watcher that stops the provided watcher at a "safe" point. I'm not sure if this will be acceptable. The only place this is used for now is in the internal `reschedule` callback, which detects if if the user provided reschedule returns a time in the past (to avoid a libev assertion failure), so this call could be hidden from the API for now if that is more palatable.

For now, if user reschedule callback returns a time in the past, the watcher is silently stopped. Should the reactor return with error instead? (Perhaps `ERANGE`?)

**Comment by garlick** [comment]
The only thing that gives me pause about `flux_watcher_stop_safe()` is that it might not be safe or indeed work at all if called from a flux prepare watcher?  Maybe it would be a good idea to keep it out of the public api and just document in the header that the periodic watcher cannot be stopped from within the reschedule callback.

**Comment by grondo** [comment]
Yeah, I was thinking the same thing and I think you are correct. At first I was thinking I could make use of it in the datetime cron implementation, which is why I ended up exposing it, but I wasn't able to use it so I think it does more harm than good to expose it.

**Comment by grondo** [comment]
Ok, I *think* I figured out the problem in Travis with the libfaketime driven tests, so I've added those back. I've also taken a first stab at manpages for the new libflux interfaces.

Only thing left todo is to add the `flux cron at` interface, but that should be much easier (and testable) now.

**Comment by grondo** [comment]
Oh, I did also remove the silly `flux_watcher_stop_safe()`

**Comment by garlick** [comment]
Great!

**Comment by grondo** [comment]
Latest version of this PR includes a simple version of `flux cron at` and updated manpages and tests.

It turns out that `approxidate` doesn't work that well in its current form for `at` usage, because it seems to mainly deal with dates in the past. I chickened out for the current `flux cron at` and call out to `/bin/date`, which accepts lots of date strings to its `--date` option, including offsets like `"+1 day"` etc. At a later time we could find/write our own implementation, but for now I did not want to spend time on a feature that might not be used.

Now the only question is whether `approxidate.[ch]` should be removed from this PR. The only user of that interface now is the `cronodate.c` tests.

**Comment by garlick** [comment]
> Now the only question is whether approxidate.[ch] should be removed from this PR. The only user of that interface now is the cronodate.c tests.

I vote we keep it if testing is improved by having it around.  If you want we could build it as a check target but I don't think that really matters much.

Is this PR ready merging in your view?

**Comment by grondo** [comment]
> Is this PR ready merging in your view?

Yes, however just be sure to ACK the following changes I wasn't quite sure about:
 * Addition of `nodeset_next_rank (n, r)` -- I wasn't sure if this was safe, since there is a nodeset iterator type (and I didn't fully understand the veb tree implementation)
 * Addition of `flux_watcher_next_wakeup()` (can you think of a better name?) This function returns the absolute time of the next expected trigger for `timer` and `periodic` watchers, using the underlying `ev_periodic_at` or `ev_timer_remaining`, and returns `EINVAL` if called on any other watcher. Would it make more sense to split this into `flux_timer_watcher_remaining` and `flux_periodic_watcher_at`?
 * Assuming `flux_watcher_next_wakeup` is ok, I added doc for it to the `flux_watcher_start` manpage, since that is where generic watcher functions seemed to go.

**Comment by garlick** [comment]
> Addition of nodeset_next_rank (n, r)

This maps perfectly to the underlying veb interface for iteration.  Not much can go wrong there.

> Addition of `flux_watcher_next_wakeup()`

That looks good too.  I have to believe libev is a well thought out set of interfaces since I think at this point we've nearly reproduced them all in the flux API, in one form or another!

**Pull request merged**
