### PR TITLE
 miscellaneous cleanup

### PR DESCRIPTION
**Pull request by chu11**
My patch series in #898 was getting long so decided to split out a number of minor miscellaneous cleanups into this PR.  It also includes some misc cleanup I had sitting off in another branch.  Some whitespace & typo fixes included, so code coverage may fail.

### CODE REVIEW

**Comment by garlick** [comment]
This all looks good - thanks!  Will merge when travis passes.

**Comment by chu11** [comment]
Huh ... all the travis builds failed.  Is there any way to get to the config.log in travis?

---
checking for JANSSON... yes
checking json_int_t is 64 bits... no
configure: error: json_int_t must be 64 bits for flux to be built
```

**Comment by garlick** [comment]
Not that I know of.

**Comment by grondo** [comment]
> Huh ... all the travis builds failed. Is there any way to get to the config.log in travis?

Temporarily edit your .travis.yml file in this branch to echo the config.log to stdout when configure fails (in fact, that might be useful in general and a commit we could keep)

**Comment by grondo** [comment]
Instead of using `AC_TRY_COMPILE` to get sizeof `json_int_t` could you use [`AC_CHECK_SIZEOF](https://www.gnu.org/software/autoconf/manual/autoconf-2.60/html_node/Generic-Compiler-Characteristics.html)? Perhaps then we wouldn't need a new `X_AC_JANSSON` macro.

**Comment by chu11** [comment]
> Instead of using AC_TRY_COMPILE to get sizeof json_int_t could you use AC_CHECK_SIZEOF? Perhaps then we wouldn't need a new X_AC_JANSSON macro.

That seems like a good idea.  I did somewhat blindly copy from the previous check.  I am still curious how this check failed though.

**Comment by chu11** [comment]
Ends up the check can't find ```janson.h```, leading to error.  I suppose it's not installed in the normal location, probably just need to do some ```CFLAGS``` hacks.  With such hacks, maybe need to keep ```X_AC_JANSSON``` macro.

**Comment by chu11** [comment]
Just did a push and things seem to work now.  Per @grondo suggestion used size check macro instead of ```AC_TRY_COMPILE```.  Also added output of ```config.log``` into the travis output if a failure occurs.  Admittedly don't know much about travis, but I think I made the change in the right place :-)

**Comment by grondo** [comment]
Yeah, use of after_failure to display the config.log seems correct to me, thanks!

This looks good now. Thanks and merging.

**Pull request merged**
