### PR TITLE
doc: update flux admin guide URL

### PR DESCRIPTION
**Pull request by kkier**
Updates path to reflect current URL - https://flux-framework.readthedocs.io/projects/flux-core/en/latest/guide/admin.html

### CODE REVIEW

**Comment by garlick** [comment]
Whoops!  Thanks @kkier!

If you have a moment, it would probably be better to squash these into one commit.  Commits should have a title (use imperative voice) and a body, and we like the problem/solution form.  How about something like this:

```
doc: update flux admin guide URL

Problem: the flux admin guide path has changed but some docs have not been updated.

Update path.
```

**Comment by kkier** [comment]
Whoops, forgot to push after squashing...  Updated as above.

**Review by garlick — APPROVED** [review]
Looks good to me, thanks!

Usually for the problem/solution commit message form we state the problem, skip a space and then state the solution.  However in this case it's pretty obvious.  Next time.

Now If you want to set the merge-when-passing tag on the sidebar, mergify will rebase this if necessary and merge.  Or I can do it for you - let me know.

**Comment by grondo** [comment]
I think only project admins can set labels on PRs. (I could be wrong though)

**Comment by garlick** [comment]
Right, I'll do that then.  Thanks @kkier!

**Pull request merged**
