### PR TITLE
testsuite: don't assume /bin/true and /bin/false

### PR DESCRIPTION
**Pull request by garlick**
Problem: tests that hard code `/bin/true` or `/bin/false` fail on macos, where those programs are in `/usr/bin`.

When PATH is already being searched, don't specify a fully qualfied path.

### CODE REVIEW

**Comment by chu11** [comment]
Would going with `/usr/bin/true` work?  Appears to be ok for RHEL9 and my ubuntu box.  Without any context, just seeing `true` and `false`, it looks like it could be boolean.  Like

```
test_expect_success 'rc3 failure causes instance failure' '
	test_expect_code 1 flux start \
		-Sbroker.rc3_path=false \
		-Slog-stderr-level=6 \
		true 2>rc3_failure.log
'
```

like `false` could be a special option to `rc3_path`.

Maybe it's just me.

**Comment by garlick** [comment]
Oops, pushed a fix to the ASAN error - I inadvertently changed a string length in the broker runat test without changing another value that was supposed to be its length + 1.

> Without any context, just seeing true and false, it looks like it could be boolean

That would probably work although I think it's _pretty_ clear what's going on in these tests.   I'd be inclined to not continue to hard code a path - it feels slightly wrong.

**Comment by chu11** [comment]
> That would probably work although I think it's pretty clear what's going on in these tests. I'd be inclined to not continue to hard code a path - it feels slightly wrong.

By all means, it certainly livable.  Just something I noticed at first glance.

**Comment by garlick** [comment]
Maybe we ought to get @grondo's input on that one.

**Review by grondo — APPROVED** [review]
This approach seems fine to me. To be fair, we have some other paths we hard code in the testsuite including `/bin/sh`, `/bin/bash`, and `/bin/echo`. I'm guessing those are ok because they exist in those paths on macos?

**Comment by garlick** [comment]
These are all test changes, so I think the rule of "add a test when you fix something" probably doesn't apply or at least not as strongly.  And the person who finally gets macos/bsd to run all the tests may have to fix whatever pops up between now and then, but I think that'll be the least of their worries.

If we do it now, then at least they will have a lesser job, and the cut and pasters won't make the problem worse.

**Comment by garlick** [comment]
> This approach seems fine to me. To be fair, we have some other paths we hard code in the testsuite including /bin/sh, /bin/bash, and /bin/echo. I'm guessing those are ok because they exist in those paths on macos?

Yeah, the problem is "fails on macos" and I wanted to keep the solution focused on that.

I'm seeing thumbs up and this is approved so I'll go ahead and set MWP.  Thanks!

**Comment by grondo** [comment]
> Yeah, the problem is "fails on macos" and I wanted to keep the solution focused on that.

I figured. My point was it went against the "it's wrong to hard code a path" argument made previously in the comments.

**Pull request merged**
