### PR TITLE
NEWS.md: update for 0.25.0 release

### PR DESCRIPTION
**Pull request by garlick**
First try at some release notes for 0.25.0.  As always, feel free to push directly here.

### CODE REVIEW

**Comment by garlick** [comment]
Just added two things that happened since this was posted and set the release date to today.

**Review by grondo — APPROVED** [review]
LGTM, Thanks!

**Comment by grondo** [comment]
I'll go ahead and set MWP, then tag the new release.

**Comment by grondo** [comment]
Tests keep timing out this AM so I may end up manually merging this one...

**Comment by grondo** [comment]
centos7 builder timed out again (though it wasn't only the centos7 builder that was  timing out). Here's the test that was apparently hanging:
```
Error: Detected 1 missing missing tests:
t/t2004-hydra.t
t/t2004-hydra.log
  /usr/lib64/mpich/bin/mpiexec.hydra
t/t2004-hydra.output
  expecting success: 
  	mpiexec.hydra -n 4 ${PMI_INFO}
  
  ssh: connect to host fv-az189-703 port 22: Connection timed out
```

**Pull request merged**
