### PR TITLE
NEWS: add release notes for 0.32.0

### PR DESCRIPTION
**Pull request by garlick**
Here are draft notes for flux-core 0.32.0.  As always, feel free to push changes here.

### CODE REVIEW

**Review by grondo — APPROVED** [review]
LGTM!

**Comment by garlick** [comment]
Bionic builders are failing with
```
2021-12-03T23:39:39.8818771Z configure: error: could not find python module jsonschema, version 2.3.0+ required
```
Just remembered that we still need to revert 902534657d1324227ee9c068d650c224c4e4a137 to drop the install of ncurses from checks/Dockerfile, so I'll push a PR for that.

**Comment by grondo** [comment]
Something clearly went wrong with the bionic image I pushed up to Dockerhub. I'll have to investigate tomorrow :disappointed:

**Comment by grondo** [comment]
Ok, the problem is that `pip install jsonschema` picked up a version that is too _new_ (apparently it doesn't have the `.__version__` attribute anymore, which causes the configure check to fail) Gotta love pip!

I'll fix this in the morning by pinning jsonschema to the older version in the Dockerfile. I'll also see if there is a better way to check the version of python modules in autoconf??

**Comment by grondo** [comment]
I've pushed an update here to incorporate #3990 and #3991 assuming it can get merged.

**Comment by grondo** [comment]
The fedora34 failure will be fixed when #3991 is merged.

**Comment by garlick** [comment]
Setting MWP

**Comment by grondo** [comment]
@mergifyio rebase

**Pull request merged**
