### PR TITLE
job-archive: remove module

### PR DESCRIPTION
**Pull request by garlick**
[Not needed anymore](https://www.youtube.com/watch?v=mwyufwkIKXAurl)

### CODE REVIEW

**Comment by garlick** [comment]
oops - looks like there are still some flux-accounting tests that rely on this.

> 2024-10-17T00:00:13.5772402Z FAIL: t1011-job-archive-interface.t 7 - load job-archive module

**Comment by chu11** [comment]
How about adding to the commit message that this fixes ...  https://github.com/flux-framework/flux-core/issues/5288

**Review by grondo — APPROVED** [review]
LGTM!

**Comment by garlick** [comment]
Just force pushed after rebasing on current master and caching a couple of dangling man page references in the docs.  Will set MWP.

**Pull request merged**
