### PR TITLE
fix fatal error handling in flux_rpc_completed()

### PR DESCRIPTION
**Pull request by garlick**
This PR addresses a problem with `flux_rpc_completed()`, where it would remain false after a fatal handle error, causing the caller to loop forever when `flux_rpc_connected()` is a terminating condition for a `flux_rpc_get()` loop.   To fix this, `flux_fatality()` was added to test whether a fatal handle error has occurred, and this is then called from `flux_rpc_completed()`.  Fixes issue #517.

Also converted `flux-hwloc` to a builtin, and tidied up error handling.  Added a check that XML files exist before asking `resource-hwloc` to load them to avoid triggering #536.

Tests for #517 and for the #536 workaround were added.

### CODE REVIEW

**Comment by grondo** [comment]
Nice! Once travis passes this should go in.

**Comment by grondo** [comment]
Oops, looks like `multrpc.t` test needs to be updated:
```
# Looks like you planned 35 tests but ran 44.
```

**Comment by dongahn** [comment]
Nice enhancements across the board! Thanks @garlick.

**Comment by garlick** [comment]
Thanks!  Just forced a push with the test plan update in `t/loop/multrpc.c`.  I also updated some deprecated API usage in there.  Sorry about that.

**Pull request merged**
