### PR TITLE
misc RFC18 fixes / cleanups / refactorings

### PR DESCRIPTION
**Pull request by chu11**
Peeled off from #2117, just misc fixes before the bigger #2106 fixes.

### CODE REVIEW

**Comment by garlick** [comment]
Do we really want to drop `flux kvs eventlog --watch`?  That seems kind of useful.

**Comment by chu11** [comment]
> Do we really want to drop flux kvs eventlog --watch? That seems kind of useful.

It wasn't used anywhere so I wasn't sure of the need.  But if you think it still has promise, I'll revert it.

**Comment by garlick** [comment]
I vote we keep it for now.

**Comment by chu11** [comment]
ok, rebased & repushed with the `--watch` removal commit taken out.

**Comment by garlick** [comment]
LGTM - thanks!

**Pull request merged**
