### PR TITLE
implement broker log ring buffer, improve logging interfaces

### PR DESCRIPTION
**Pull request by garlick**
This PR implements an improved logging service in the broker with the following characteristics:
* All message _from the local rank_ are logged to an internal circular buffer
* `flux-dmesg` is used to read the buffer, clear it, and follow it
* Messages with log level <= a configured `log-level` are forwarded to rank zero
* Rank zero logs these messages to stderr or a file.

The new bits here are the circular buffer and the ability to filter what is forwarded to rank zero and emitted on stderr/file.  Since the default log-level is now LOG_INFO rather than LOG_DEBUG, you will see less output by default.

The size of the ring buffer and the logging level can be changed at runtime via the `log-buflimit` and `log-level` attributes.

`flux-dmesg` works similar to the kernel `dmesg` utility:
```
Usage: flux-dmesg [OPTIONS...]
Print or control log ring buffer
  -C, --clear            Clear the ring buffer
  -c, --read-clear       Clear the ring buffer contents after printing
  -f, --follow           Track new entries as are logged
  -h, --help             Display this message.
```

Apart from the forwarding to rank 0, this is not a distributed service.  However, the interfaces were designed so that comms modules could provide a distributed interface to it, keep attributes in sync with the KVS config, or bridge log entries to another storage/query mechanism.

Some new interfaces for logging convenience were added:
```C
/* Log a message at LOG_ERR level, appending a colon, space, and error string.
 * The system 'errno' is assumed to be valid and contain an error code
 * that can be decoded with zmq_strerror(3).
 */
int flux_log_verror (flux_t h, const char *fmt, va_list ap);
int flux_log_error (flux_t h, const char *fmt, ...)
                 __attribute__ ((format (printf, 2, 3)));

#define FLUX_LOG_ERROR(h) \
    (void)flux_log_error ((h), "%s::%d[%s]", __FILE__, __LINE__, __FUNCTION__)
```

Still todo:
* More test coverage (there is a sharness test for basic `flux-dmesg` but this probably needs more)
* Man page for `flux-dmesg(1)`
* Man page(3) for logging API

### CODE REVIEW

**Comment by garlick** [comment]
Couple of notes:
* FLUX_DMESG_NONBLOCK should be renamed to FLUX_DMESG_FOLLOW
* The "sequenced get" interface turns out to be fairly awkward for tapping into the log stream from another module.  A subscriber interface may be better or multiple-response-RPC/stream interface as discussed in #271

**Comment by garlick** [comment]
I've rebased this on the current master, squashed some commits, and added/updated man pages.

I did not rework the "sequenced get" protocol, but what is there does work for `flux dmesg --follow` and I think the code is now structured so that it can be reworked easily later.

I propose we merge this as a clear improvement over what was there, and get on with other things.

**Comment by grondo** [comment]
Strange. flux-setattr.adoc is missing from dist target, but I assume it wasn't part of this PR. If this is a travis-only issue I can look into it later this evening.

**Comment by garlick** [comment]
No that was my error (though not sure why only clang failed...).

I added the Makefile.am glue to support adoc files generating multiple .1 targets but forgot to update the ADOC_FILES and XML_FILES macros.

Just forced a push with a fix.

**Comment by grondo** [comment]
It's not ideal, but clang build is the only one that runs `make distcheck` and gcc build runs `make check-code-coverage` (which isn't compatible with `make distcheck`).

**Pull request merged**
