### PR TITLE
use jansson >= 2.6 and document JSON payload functions

### PR DESCRIPTION
**Pull request by garlick**
The jansson `json_pack()` and `json_unpack()` functions that were used to build `flux_rpcf()` and related functions have some ambiguities in accepted variable arguments depending on what version of jansson is used, and the capabilities of the underlying machine.  This PR is an attempt to address that by:
* Requiring flux to build against jansson >= 2.6, thereby reducing some API variability
* Documenting the format specifiers that work in 2.6
* Requring `json_int_t` to be 64 bits internally, and documenting the `%I` type as `int64_t` externally.

### CODE REVIEW

**Comment by grondo** [comment]
Nicely done this is great!

We should do the same in flux-sched, since it requires flux-core anyway, and we can remove some of the #ifdef'd code checking for `JANSSON_VERSION_HEX` of anything < 2.6.

**Comment by garlick** [comment]
> we can remove some of the #ifdef'd code checking for JANSSON_VERSION_HEX of anything < 2.6

Oh right I'll add that here.

**Comment by grondo** [comment]
Do you want me to clean up flux-sched libjansson stuff similarly, or are you already working on it?

**Comment by garlick** [comment]
Already submitted pr - thanks!

**Comment by grondo** [comment]
Hm travis failed with a new one for me:
```
not ok 71 - stat watcher invoked once for size chnage
#   Failed test 'stat watcher invoked once for size chnage'
#   at ../../../../src/common/libflux/test/reactor.c line 644.
```

My guess is that it is transient error somehow so I'll restart the build.

**Pull request merged**
