### PR TITLE
build: allow python 3.10.0 to satisfy version check

### PR DESCRIPTION
**Pull request by garlick**
This updates the `ax_python_devel.m4` to the latest from [autoconf-archive](https://www.gnu.org/software/autoconf-archive/ax_python_devel.html) and fixes a bug parsing python version 3.10.0 found by @andre-merzky.

### CODE REVIEW

**Comment by grondo** [comment]
Restarted CI since a builder timed out

**Review by grondo — APPROVED** [review]
LGTM! But not sure if you'd like an extra reviewer as well before merging.

**Comment by garlick** [comment]
@jameshcorbett  - would you mind giving this a quick review?  Maybe you could try it in the conda environment?

**Review by jameshcorbett — APPROVED** [review]
It worked! The version checking looked a little weird at first glance but it makes sense after trying out the code and reading about how hexversions are constructed.

**Comment by garlick** [comment]
Great, thanks very much!  I'll set MWP.

**Pull request merged**
