### PR TITLE
config: parse TOML once in broker, share with modules

### PR DESCRIPTION
**Pull request by garlick**
Instead of having each module separately parse TOML config and handle parse errors, parse it once in the broker and then share a copy of the config object with modules so they can call `flux_get_conf()` without error checking.

The broker builds the config object in one of the following ways (descending precedence):
* If broker `--config-path` is set, parse TOML at that location
* If `FLUX_CONF_DIR` is set in the environment, parse TOML at that location
* Construct empty config object

The config object is shared with modules by duplicating it and storing it in the module handle with `flux_set_conf()` when the module is being created.

There is no longer a compiled-in default config path.  The systemd unit file sets `--config-path` to point to `${sysconfdir}/flux/system` so that it's special configurations (e.g. for TBON bootstrap and multi-user exec) may be installed there without applying to other instances.

Refactor the `flux_conf` class and broker config handling code so that in the future we can handle config updates.   For example the broker can implement an RPC so that a utility can trigger a config reload (e.g. via systemd), and a streaming RPC can be implemented for distributing config object updates to flux_t handle users that are capable of dealing with them.

This will require an update to flux-sched since it changes the prototype of the `flux_get_conf()` function.

### CODE REVIEW

**Comment by grondo** [comment]
Just started playing with this, first issue is that system instance configuration appears to be required:
```
Mar 25 17:58:32 20ef726b3fcc systemd[1]: Started Flux message broker.
Mar 25 17:58:32 20ef726b3fcc flux[12277]: broker: Config file error: /etc/flux/system/*.toml: Read error: Invalid argument
Mar 25 17:58:32 20ef726b3fcc systemd[1]: flux.service: Main process exited, code=exited, status=1/FAILURE
Mar 25 17:58:32 20ef726b3fcc systemd[1]: flux.service: Failed with result 'exit-code'.
```

Hm, though if I create an empty directory that seems to work. It perhaps is not a good idea to treat a missing directory as "empty" configuration (e.g. to catch a typo on the command line), but maybe the error could be improved? (I know it isn't easy with `glob(3)` though... hmm.).

**Comment by garlick** [comment]
Let me see what I can do to improve the message.  I does seem to me like the user should be notified if the specified config directory doesn't exist.  Maybe if the directory is empty that should also be an error?

On the system instance, I figured a package might supply `%noreplace` or equivalent config files in the `system` location to support a basic "workstation" config out of the box.

**Comment by grondo** [comment]
If there are defaults, and therefore an empty config is allowed, then an empty config directory should probably be allowed?

Probably it would be sufficient to call `access()` on any supplied `--config-path` and return fatal error from that call.

The plan for package installed flux system instance sounds good, but probably we should plan for/allow other installation methods as well.

**Comment by grondo** [comment]
> On the system instance, I figured a package might supply %noreplace or equivalent config files in the system location to support a basic "workstation" config out of the box.

When the broker reads multiple config files, do subsequently loaded toml files override those previously read? I've been lamenting the fact that TOML doesn't allow overwriting keys (multiple definitions), nor "updating" a table (defining a table more than once).

If this is possible by just dropping a new *.toml file that will be read after another TOML file, though, then I'm happy. This would allow a `00-defaults.toml` to be dropped into that directory, and allow any site TOML to override those defaults. (Not that I'm saying we should do this now, just that at least if it is possible, that is a good thing)

If the above isn't how things work now, then it might be easy to get the config-dir into a bad state, since a site could drop arbitrary toml files into that directory which wouldn't necessarily behave well with a package provided %noreplace default.

**Comment by grondo** [comment]
Just an idle thought, nothing to act on, when I saw this:
```
broker --config-path=/etc/flux/system -Srundir=/run/flux -Slocal-uri=local:///run/flux/local -Slog-stderr-level=6 -Scontent.backing-path=/var/lib/flux/content.sqlite -Sbroker.rc2_none
```

It made me wonder if the setattr args could *also* be read from config.

**Comment by grondo** [comment]
```
broker --config-path=/etc/flux/system
```

Another question -- should the config-path actually be `/etc/flux/system/conf.d`. I'm not sure, but it matches what we did for flux-security, and it also would leave open the addition of some "other" non-TOML config or system-instance related files under `/etc/flux/system` (though not sure at this point what that would be)

**Comment by garlick** [comment]
> If this is possible by just dropping a new *.toml file that will be read after another TOML file, though, then I'm happy

I think so but I should add a test.  Each toml file is parsed separately and converted to JSON, and the json objects are merged with [`json_object_update()` ](https://jansson.readthedocs.io/en/2.11/apiref.html#c.json_object_update).

> It made me wonder if the setattr args could also be read from config

Yeah I had the same thought, although I didn't go there because I felt the ongoing role of "broker attributes" might be part of a larger discussion about how the config that's parsed from files relates to the runtime config that's actually used.  I.e. the broker attrs are like the broker's runtime config, and maybe we should have more than a haphazard mapping between attribute names and TOML tables and keys.  Topic for future PR maybe?

> should the config-path actually be /etc/flux/system/conf.d

I was a little worried about adding too much path depth arbitrarily, but it would take very little arm twisting to get me to agree to change it :-).

**Comment by grondo** [comment]
> I was a little worried about adding too much path depth arbitrarily, but it would take very little arm twisting to get me to agree to change it :-).

Well I can sympathize with that, however it does match "depth" of existing config dirs, and will separate the TOML config from anything else system-instance related. I leave the choice up to you.

**Comment by grondo** [comment]
So I think this seems ready for a merge (we'll have to manually change branch protection and merge since flux-sched can't pass on this branch), except for the default --conf-dir change (if you're amenable)

**Comment by garlick** [comment]
force pushed with systemd path change, rebase on current master, and better error when directory doesn't exist.

**Comment by garlick** [comment]
Hang on - just noticed a commit typo and leftover man page bits.  One more force push coming.

**Comment by garlick** [comment]
OK, done.  I also added a unit test to ensure an empty config directory is allowed as discussed.  I think this is OK to go in.

**Comment by grondo** [comment]
One more very minor commit type in 028ae18

> To se up a system instance

**Comment by garlick** [comment]
> One more very minor commit message typo 

Just pushed a fix.  Thanks!

**Comment by grondo** [comment]
One more thing, sorry!

The error when confdir doesn't exist is accumulating `strerror (errno)` twice somehow:
```
broker: Config file error: /etc/flux/system/conf.d: No such file or directory: No such file or directory
```

**Comment by garlick** [comment]
Oh because I'm printing the error with `log_err()`.  Good catch!  Hang on....

**Comment by garlick** [comment]
Fixed:
```
$ flux start -o,-c /etc/flux/system/conf.d
flux-broker: Config file error: /etc/flux/system/conf.d: No such file or directory
```

**Comment by grondo** [comment]
Great! Once travis passes I'll relax branch protections and merge, then re-run tests in flux-framework/fllux-sched#630

**Comment by garlick** [comment]
Thanks!

**Pull request merged**
