### PR TITLE
eliminate FLUX_TMPDIR, be careful with broker environment

### PR DESCRIPTION
**Pull request by garlick**
This PR is a first, rough attempt at addressing the issues being discussed in #381.  It does not yet address the idea of a "default program environment" cache in the broker though.

FLUX_TMPDIR is eliminated in favor of using FLUX_URI exclusively to select a particular broker to connect to, e.g. when `flux_open ()` is called with a NULL `uri` argument.

The broker copies FLUX_URI if set in its own environment, makes its value available via `flux_getattr (h, "parent-uri")`, then unsets it in the broker environment so nobody will use it accidentally.

The broker similarly makes its own local URI available via `flux_getattr (h, "local-uri")` and does not set this in its own environment.  FLUX_URI is set for child programs in three places: 1) when launching the initial program, 2) when launching via cmb.exec, and 3) when launching via wreck.  Other parts of the broker code (e.g. wreck and the connector-local module) now have to use flux_getattr rather than getenv to access this.

### CODE REVIEW

**Comment by grondo** [comment]
This looks like a great step to me.

Since there aren't really any other environment variables that need this kind of transition at this point, the default environment thing now seems like overkill.

**Comment by garlick** [comment]
Thanks for the comments @grondo.  I got rid of the extraneous include and the "I don't know what this does" comment in the lua env filter commit, and rebased

By the way @trws, I saw that FLUX_TMPDIR is referenced in `sideflux.py` but I left it alone because it looked like it was not going to be a problem and thought I might do more harm than good trying to remove it.  Any problem if we save that for later?

**Comment by trws** [comment]
I can rework that, it should be harmless if I transitioned it to using FLUX_URI as I intended. If not, the Python tests will all die horribly. Either way it's a 1-2 line fix.



Sent with Good (www.good.com)

________________________________

**Comment by garlick** [comment]
Probably best not to merge this yet.  I'm feeling bad about the FLUX_URI hack in the broker that still tries to make its own path a subdirectory of its parents', to avoid name collisions.  Let me see if I can find a way to avoid that.

**Comment by garlick** [comment]
Just pushed an update that changes the directory structure for sockets.  When launching directly with `flux-start`, all sockets are self contained in a unique directory created with `mkdtemp()`.  The naming and structure of the hierarchy is neater and more intuitive IMHO.  The hierarchy of instances is _not_ reflected in the hierarchy of directories however.

This makes the python tests sad.  I need to track down where the old flux-sid-rank scheme is hardwired.

**Comment by garlick** [comment]
This change breaks list-instances pretty badly.  While it's possible to find URI's for rank 0 of all locally launched instances with something like:
```
for path in `echo $TMPDIR:-/tmp/flux.??????/0`; do
    echo local://$path
done
```
we can't discern the instance hierarchy or the sid from the directory layout.

I'm on the fence what should be done here.  @trws or @grondo do you have an opinion on whether dumbing down `flux list-instances` is a bad move?

**Comment by trws** [comment]
I don't think that's a huge deal right now, as I think I'm the only regular user and I really only look at the outer level.  That said, it would be good to have a ticket to add a discovery interface to the connector protocol, so each connector can implement a way to find itself rather than relying on implementation details in the external tool.

One bit I'm not clear on though, why can't we discern sid? Is there a reason not to include it in the tmpdir prefix used to generate the directory?

**Comment by garlick** [comment]
My thinking was that the sid is not unique when we have flux launching flux, so without also knowing its position in the hierarchy, it might not be useful.

If it's useful we could add it though, either to the top level directory or maybe in a `sid` file inside it. directory.

**Comment by trws** [comment]
I would say its useful, if only to allow a user to find an instance for 
which they have specified an intentionally unique sid, although a 
similar result could be obtained with the PID I suppose.

**Comment by garlick** [comment]
OK, the sid is back in the name.  The names look like they did before except instead of flux-sid-rank it's now flux-sid-XXXXXX where XXXXXX is a unique string added by `mkdtemp()`.

**Comment by garlick** [comment]
@trws I might need a little help with sideflux.py.  It needs to create the top level directory then pass it in with `--socket-directory` to the broker like flux-start.

However, now might be a good time to pause and as @grondo and others if this seems like a reasonable direction?  I like the tidiness of it and ones less hierarchy to deal with can't hurt (TBON + instances is mind bending enough at times).

**Comment by trws** [comment]
FWIW, I like it better.  It makes the cleanup semantics rather cleaner.  We never ran into this, because we don't currently support it, but if you had managed to have a higher-level flux instance die before its children, the directory would not have been cleaned up.

Do I understand correctly that `--socket-dir` skips the whole tmpdir creation process and puts sockets directly in that directory?

**Comment by trws** [comment]
Actually, more to the point, is the URI `local://<socket-dir>` or does there need to be another path component included somewhere? Either way it's a pretty straightforward fix, just want to make sure I'm getting this right.

**Comment by garlick** [comment]
Correct, `--socket-directory` specifies an existing directory.  A directory for each rank will be created underneath it.  If the option is omitted, each rank creates its own unique directory independently.

**Comment by garlick** [comment]
The URI would be `local://socketdir/0` for rank 0, `local://socketdir/1` for rank 1, etc..

**Comment by trws** [comment]
Got it, thanks @garlick.

**Comment by grondo** [comment]
Sorry I somehow missed all this discussion. I don't think I exactly grok the changes fully, but as long as things won't break with polyinstantiated /tmp or namespaces/containers, I don't think the local socket paths are that crucial.

**Comment by garlick** [comment]
I think we should be OK with polyinstantiated /tmp, at least no worse off than before.  We do share ipc:// socket paths using PMI when running multiple tasks per node, because one node has to act as a PGM event relay for the other nodes.  If that breaks because ranks are launched with their own /tmp then we can always change to tcp://.

**Comment by garlick** [comment]
Thanks for that @trws, test are passing now.  I'll want to squash down some commits before this is ready to be considered for merge.

**Comment by garlick** [comment]
I think this is a merge candidate now.  Happy to continue to iterate if people have more comments.  I know a lot of energy has been directed in much more important areas recently, so feel free to park this for a while if it's not a priority.

**Comment by trws** [comment]
:+1:

**Comment by grondo** [comment]
This is good and I think might help @dongahn and @surajpkn so we should pull it in now.

**Pull request merged**
