### PR TITLE
kvs: Support namespace prefixes in symlinks

### PR DESCRIPTION
**Pull request by chu11**
This is the final big part to issue #1341, supporting namespace prefixes in symlinks.

There are a couple of small refactoring patches in this PR as setup.

Also, the documentation for namespace prefixes was added into a patch in this PR.

### CODE REVIEW

**Comment by garlick** [comment]
Nice!  I'll check out and kick the tires manually later this morning.

One quick thought - do we need the environment variable mechanism to select namespaces now that we have two other ways to do it?  There might be a use case, just trying to remember what it might be...

**Comment by garlick** [comment]
Some preliminary poking - no prob with symlinks, though some other results are a little strange.  Not sure if it's the tools or the KVS implementation.  I added notes with `###` prefix.
```
$ flux kvs namespace-create foo
$ flux kvs namespace-create foo   ### kvs.err log message should be removed
2018-04-06T16:01:53.751913Z kvs.err[0]: namespace_create_request_cb: namespace_create: File exists
flux-kvs: foo: File exists
$ flux kvs put ns
$ flux kvs put ns:foo/a=42
$ flux kvs --namespace=foo dir
a = 42
$ flux kvs dir ns:foo
flux-kvs: ns:foo: Invalid argument  ### should that work?
$ flux kvs dir ns:foo/
flux-kvs: ns:foo/: Invalid argument  ### seems like that should work
$ flux kvs dir ns:foo/.  ### seems like both double dots should not be displayed
ns:foo/..a = 42
$ flux kvs ls ns:foo/.  
ns:foo/: Invalid argument  ### that should work
$ flux kvs link  ns:foo/. linktofoo
$ flux kvs dir -R linktofoo
linktofoo.a = 42
```

**Comment by chu11** [comment]
> $ flux kvs dir ns:foo
> flux-kvs: ns:foo: Invalid argument  ### should that work?
> $ flux kvs dir ns:foo/
> flux-kvs: ns:foo/: Invalid argument  ### seems like that should work

So the way I parse things I assume if the user invalidly specifies a namespace or only specifies a namespace, it's an error.  So the correct input would be ```ns:foo/.``` (i.e. a period at the end, indicating the "root" dir).

> $ flux kvs dir ns:foo/.  ### seems like both double dots should not be displayed
> ns:foo/..a = 42

Dunno if this is #1391, will take a look.

> $ flux kvs ls ns:foo/.  
> ns:foo/: Invalid argument  ### that should work

Hmmm.  This should work.  Skimming code in ```flux-kvs``` it seems the ```ls``` command strips off trailing periods, leading to ```ns:foo/``` being the input to the server side.  The client side parsing of input keys wasn't something I thought of.  Hmmm.  May have to tweak the ```ls``` side.

**Comment by garlick** [comment]
Possibly flux kvs just needs some tweaking.  For example, cmd_dir() has this
```c
if (optindex == argc)
        key = ".";
```
I guess `ns:foo/` should be converted to `ns:foo/.`?

**Comment by chu11** [comment]
Hmmm.  What I do on the server side is detect if an namespace-prefix is present, then normalize the "key-suffix".  But I consider it an error if there is no suffix, like if the key is ```ns:foo/```` (no period).

So we'd be doing different behavior on the client side.

Hmmmm.

**Comment by garlick** [comment]
I think my comments thus far are a little off topic for this PR, so I opened some new issues for those.

**Comment by garlick** [comment]
Whee!  Passed this test with flying colors:
```
#!/bin/bash -e
max=20
flux kvs namespace-create foo
flux kvs namespace-create bar
flux kvs put a=42
prev=ns:primary/a
for i in $(seq 1 ${max}); do
        if test $((${i}%2)) -eq 0; then
                target=ns:foo/$i
        else
                target=ns:bar/$i
        fi
        flux kvs link  $prev $target
        prev=$target
done
```

This creates 20 levels of symlink, each hopping between namespaces.
```
$ ./script
$ flux kvs dir
a = 42
resource.
$ flux kvs --namespace bar dir
1 -> ns:primary/a
11 -> ns:foo/10
13 -> ns:foo/12
15 -> ns:foo/14
17 -> ns:foo/16
19 -> ns:foo/18
3 -> ns:foo/2
5 -> ns:foo/4
7 -> ns:foo/6
9 -> ns:foo/8
$ flux kvs --namespace foo dir
10 -> ns:bar/9
12 -> ns:bar/11
14 -> ns:bar/13
16 -> ns:bar/15
18 -> ns:bar/17
2 -> ns:bar/1
20 -> ns:bar/19
4 -> ns:bar/3
6 -> ns:bar/5
8 -> ns:bar/7
$ flux kvs --namespace foo get 20
$ flux-kvs: 20: Too many levels of symbolic links
flux kvs --namespace foo get 10
42
$ flux kvs --namespace bar get 11
flux-kvs: 11: Too many levels of symbolic links
```

**Comment by garlick** [comment]
Also, running `flux kvs --namespace foo get 10` in a tight loop after the above doesn't budge the `flux-broker-0` rss as reported by top.

**Comment by chu11** [comment]
Skimming through the code, I should find a way to fix:

```
$ flux kvs ls ns:foo/.
ns:foo/: Invalid argument
```

Its minimally inconsistent to the rest of the commands.  The other ones can probably be dealt later with the new issues that were created.

**Comment by chu11** [comment]
Added a simple fix for the ```flux kvs ls ns:foo/.``` case.  Will address deeper problems with #1434.

Also rebased on current master.

**Comment by garlick** [comment]
LGTM.  I'm heading out but I'll check in and push the button when it's green.

**Pull request merged**
