### PR TITLE
libjob: Add flux_job_kvs_key() utility function

### PR DESCRIPTION
**Pull request by chu11**
Minor cleanup peeled off from #2066, to remove duplicate code from `job-manager` and `libschedutil`.

### CODE REVIEW

**Comment by grondo** [comment]
Good cleanup!

Since you've split the "types" into `job_types.h`, shouldn't the `enum` definitions go in `job_types.h` as well?

I also think it would be slightly cleaner to just put `flux_job_kvs_key()` into `job.c` directly, but I can see the rationale for separate module for testing (and the git mv nicely preserved authorship). However, perhaps the prototype could just go into `job.h` to reduce the number of installed headers? (Just my opinion though)

PR title should be "libjob: Add flux_job_kvs_key" not "libjobutil"

**Comment by chu11** [comment]
> Since you've split the "types" into job_types.h, shouldn't the enum definitions go in job_types.h as well?

I suppose that could go in there too.  I sort of followed the pattern of what was done in `libflux/types.h`, putting that rare typedef that was needed to fix the circular header includes.

> I also think it would be slightly cleaner to just put flux_job_kvs_key() into job.c directly, 

Good point.  I did it mostly b/c I thought there could be future additions in `job_util`, but perhaps I'm jumping the gun??  Can go either way on this of course.

> (and the git mv nicely preserved authorship).

Heh, the code actually come from `job-manager`, git was the one that decided it was a `git mv`.  So even git knew the code was duplicated and should be cleaned up :-)

**Comment by garlick** [comment]
I'd vote for one installed header too, unless there is a practical reason to split it up.  We can always do so later if one arises.

**Comment by chu11** [comment]
re-pushed, everything is now in `job.[ch]`.  Since no new files, no need to create `job_types.h` (although this may be brought back when I finish up what's in #2066).

**Comment by garlick** [comment]
Thanks!  Couple minor nits
* commit message should drop the trailing "libjob"
* libjob.la should not need to be added to Makefile.am in job-manager since libjob.lais included in `libflux-core.la`

**Comment by chu11** [comment]
re-pushed with nit fixes

**Comment by garlick** [comment]
There's still an (unnecessary?) addition of libjob.la to test_ldadd in the job-manager Makefile.am...

**Comment by chu11** [comment]
doh! sorry, I forgot about the one for the tests.  Re-pushed.

**Comment by garlick** [comment]
Thanks!  LGTM!

**Pull request merged**
