### PR TITLE
test/kap: convert KAP tests to new flux event api

### PR DESCRIPTION
**Pull request by grondo**
Fix KAP tests compile on master (convert a couple calls to new API)

### CODE REVIEW

**Comment by grondo** [comment]
Ok, that was pretty straightforward so I added the change to this PR.

As an aside, I was wondering while copying the idiom
```C
    flux_match_t match = {
        .typemask = FLUX_MSGTYPE_EVENT,
        .matchtag = FLUX_MATCHTAG_NONE,
        .bsize = 0,
        .topic_glob = NULL,
    }
```

if you'd thought about making `flux_match_t` initilizers (akin to `PTHREAD_MUTEX_INITIALIZER`)
e.g.
```C
#define FLUX_MATCH_ANY \
    { FLUX_MSGTYPE_ANY, FLUX_MATCHTAG_NONE, 0, NULL }
#define FLUX_MATCH_EVENT \
    { FLUX_MSGTYPE_EVENT, FLUX_MATCHTAG_NONE, 0, NULL }
```

which would simplify call sites somewhat

```diff
@@ -369,12 +369,7 @@ enforce_c_consistency (kap_params_t *param)
     const char *tag = NULL;
     int v = 0;
     json_object *o = NULL;
-    flux_match_t match = {
-        .typemask = FLUX_MSGTYPE_EVENT,
-        .matchtag = FLUX_MATCHTAG_NONE,
-        .bsize = 0,
-        .topic_glob = NULL,
-    };
+    flux_match_t match = FLUX_MATCH_EVENT;
 
     zmsg_t * msg = flux_recvmsg_match (param->pers.handle, match, false);
     if ( ! msg ) {

```

**Comment by grondo** [comment]
Hrm, travis build failed on GCC. Sorry, I'll check that out a bit later.

**Comment by garlick** [comment]
Good idea on the initializers.  I'll add that to the current PR I'm working on (flux_msg_t)

**Comment by grondo** [comment]
Ok, mpi_test needed `-lrt` on link line. Let's see if this build passes.

**Comment by garlick** [comment]
Excellent.

**Pull request merged**
