### PR TITLE
shell: add support for debugger synchronization and MPIR_proctable gather

### PR DESCRIPTION
**Pull request by grondo**
Posting this PR early so I can more easily align with @dongahn 

This PR adds two new builtin shell plugins:

 * The `ptrace` plugin adds support for starting tasks in a stopped state using `PTRACE_TRACEME` when the `-o stop-tasks-in-exec` option is provided to the shell. Once all tasks have been verified as stopped, the `shell.start` event will be emitted with `{"sync":true}` set in the context.

 * The `mpir` plugin adds support for `flux-job attach` or another tool gathering `MPIR_proctable` information on demand via new shell `.proctable` service on the leader rank. Once the leader rank receives this request, it takes care of gathering the proctables from all other ranks and reducing the data before sending it back in the RPC response. In case shells have exited before they can respond (and thus we hit a hang since a response won't be forthcoming), there is a 5s timeout for these requests, after which the leader shell will abort the rpc and send `ECANCELLED` as a response.

The `MPIR_proctable` is encoded into JSON via a one-off semi-compressed encoding that seemed like a good idea at the time. The encoding was optimized not just for size, but also for ease of reduction in the leader shell. Not sure if it was a such a good idea now, but it does seem to be working and does reduce the size of the proctable JSON blob. For now, the encoded proctable is *not* stored in the KVS but is fetched on demand by a tool (e.g. `flux-job attach`).

Still need to add some tests for both of these new plugins.

I'd also like to get feedback from @dongahn. Right now the `proctable.h` interface is internal only, and is meant for use in `flux job attach` or another frontend tool in flux-core. If other tools may possibly want to request and build a `MPIR_PROCDESC *MPIR_proctable`, I'll have to think about the best way to export this shell interface publicly.

FYI - here's an example of a full `MPIR_proctable` object for 1488 tasks across 92 nodes of fluke (running 372 brokers. PIDs list would likely come out even smaller if brokers weren't sharing nodes)

```json
 {
 "hosts":[["fluke",[[4,-15],[3,-15],[1,-15],[1,-15],[1,-15],[1,-15],[1,-15],[1,-15],[1,-15],[1,-15],[1,-15],[2,-15],[1,-15],[1,-15],[1,-15],[1,-15],[1,-15],[2,-15],[1,-15],[1,-15],[1,-15],[1,-15],[1,-15],[1,-15],[1,-15],[1,-15],[1,-15],[1,-15],[1,-15],[1,-15],[1,-15],[1,-15],[1,-15],[1,-15],[1,-15],[1,-15],[1,-15],[1,-15],[1,-15],[1,-15],[1,-15],[1,-15],[1,-15],[1,-15],[1,-15],[1,-15],[1,-15],[1,-15],[1,-15],[1,-15],[1,-15],[1,-15],[1,-15],[2,-15],[1,-15],[1,-15],[1,-15],[1,-15],[1,-15],[1,-15],[1,-15],[1,-15],[1,-15],[1,-15],[1,-15],[1,-15],[1,-15],[1,-15],[1,-15],[1,-15],[2,-15],[1,-15],[1,-15],[1,-15],[1,-15],[1,-15],[1,-15],[1,-15],[1,-15],[1,-15],[1,-15],[1,-15],[2,-15],[1,-15],[1,-15],[1,-15],[1,-15],[1,-15],[1,-15],[1,-15],[1,-15],[1,-15],[1,-15]]]],
 "executables":[["sleep",[[-1,-1487]]]],
 "ids":[[0,1487]],
 "pids":[[5399,1],2,7,-15,3,[10,1],-12,5,2,3,-11,3,[6,1],-3207,4,3,3,-11,3,3,6,-14,6,3,2,-10,3,8,3,28942,3,2,6,-13,6,5,4,-14,2,7,2,-13,5,5,5,447,2,4,4,-13,6,4,2,-11,6,4,4,-13,2,4,6,-3623,[5,1],4,-15,3,6,4,-11,[4,1],7,-13,3,4,4,3180,5,4,5,-13,3,3,4,-9,6,4,3,-12,3,4,3,-493,4,4,3,-12,4,6,3,-15,4,4,2,-9,4,4,4,-64,5,4,3,-15,4,3,4,-9,4,4,4,-13,4,4,4,-50,5,4,5,-13,5,4,3,-11,2,4,4,-9,4,4,4,-3418,9,[5,1],-13,5,[5,1],-10,2,3,3,-10,3,2,4,-7096,4,6,4,-15,6,3,5,-12,2,4,5,-10,4,3,2,10345,7,5,3,-12,3,3,5,-13,4,5,3,-11,2,4,3,-9876,5,3,4,-11,3,7,3,-11,4,3,3,-11,4,3,6,-41,4,4,2,-7,2,4,3,-10,5,4,3,-13,5,7,2,9974,4,2,3,-10,4,7,4,-13,4,2,5,-10,6,3,2,-42,4,4,7,-13,3,5,3,-12,5,3,3,-9,4,4,3,-362,2,3,3,-9,4,3,3,-12,4,6,4,-13,6,6,2,-26526,5,3,4,-11,5,3,4,-11,2,6,4,-15,4,4,4,22958,5,[5,1],-12,3,4,3,-11,5,4,5,-11,3,4,5,-3388,4,4,3,-10,4,4,4,-14,4,4,3,-8,4,6,2,297,4,3,4,-8,6,3,3,-13,4,2,6,-13,4,5,3,8780,4,[6,1],-10,4,3,4,-10,5,[6,1],-15,4,3,3,-3022,3,5,4,-13,3,3,4,-12,4,5,5,-13,6,3,3,3280,4,4,7,-12,4,4,3,-13,5,4,2,-10,3,4,4,-3303,5,[3,1],-7,4,4,3,-10,4,4,3,-13,3,8,3,-9,5,3,4,-10,2,6,3,-14,4,3,3,-8,6,4,3,3026,3,6,4,-15,4,4,4,-11,5,3,4,-10,4,3,4,58,4,3,4,-8,7,[2,1],-15,3,5,3,-10,3,3,3,-96,6,5,3,-10,4,4,3,-14,2,6,4,-11,3,2,3,11,5,[3,1],-13,2,5,4,-12,4,2,3,-7,5,4,4,-6883,5,4,3,-13,4,4,4,-14,4,3,6,-12,4,4,2,-3416,5,3,4,-14,4,4,4,-11,5,3,6,-12,2,6,2,421,6,5,2,-10,4,2,3,-11,3,4,2,-8,3,[9,1],-3208,5,3,4,-11,3,3,3,-8,4,7,2,-12,6,2,3,-344,6,5,2,-12,7,[6,1],-12,2,4,3,-10,2,3,3,3381,3,3,6,-14,3,4,6,-14,7,4,2,-11,3,5,2,-3502,3,2,4,-7,4,5,2,-14,9,4,2,-13,3,3,3,-162,2,5,2,-12,7,4,3,-13,7,5,2,-13,2,2,3,-36,3,3,2,-13,2,2,5,-10,2,5,6,-14,5,4,3,3515,5,4,3,-10,5,4,3,-13,3,4,5,-10,3,4,5,-342,[5,1],6,-10,6,3,3,-13,3,3,3,-11,4,6,4,-2740,4,6,3,-15,4,3,4,-8,2,5,4,-13,[7,1],4,2768,5,2,5,-13,4,5,3,-13,4,4,3,-8,3,6,3,91,3,3,4,-9,4,3,4,-13,5,3,4,-9,7,[4,1],472,4,3,6,-12,4,3,4,-9,3,4,4,-12,7,2,4,9713,5,4,3,-10,2,4,2,-9,5,5,3,-15,4,4,6,-3021,4,4,4,-11,4,4,2,-12,3,[4,1],-9,5,7,3,2968,4,6,3,-14,4,3,6,-10,5,2,5,-13,4,3,3,137,5,5,2,-11,2,4,7,-15,5,5,4,-11,4,2,3,-92,5,2,3,-9,8,4,2,-13,2,2,5,-8,5,4,2,15,3,[3,1],-9,[12,2],-13,2,3,5,-12,5,3,3,-16,4,4,5,-11,4,4,5,-12,4,4,3,-13,4,4,3,-32077,10,3,4,-14,3,6,4,-14,2,5,5,-13,4,6,4,16905,4,5,2,-8,4,6,2,-13,3,7,2,-13,5,2,2,-13419,8,[3,1],-11,3,3,7,-15,4,2,4,-7,4,4,3,2817,4,2,4,-8,3,2,4,-8,6,[5,1],-14,7,[4,1],104,3,5,2,-9,3,2,5,-12,8,5,2,-12,3,4,4,-134,2,2,6,-12,8,2,4,-15,4,4,4,-10,4,4,4,4670,3,3,4,[-9,1],2,4,-10,7,2,6,-14,10,[2,1],-43,7,[4,1],-14,4,3,3,-7,3,2,4,-11,4,6,4,-20,5,3,4,-10,5,[3,1],-8,3,7,2,-14,3,5,5,-4555,7,3,3,-15,4,3,4,-10,4,3,5,-10,3,4,4,-3097,5,3,6,-13,3,3,3,-7,6,2,2,-11,4,6,3,3050,4,3,5,-10,3,5,3,-12,5,3,5,-11,5,3,4,-3435,9,[5,1],-14,3,3,4,-8,2,5,3,-11,4,2,4,3099,2,3,4,-12,6,5,4,-13,5,2,4,-12,3,6,4,-2970,7,4,2,-10,2,3,4,-11,3,5,6,-13,4,4,4,3409,7,4,2,-10,2,4,6,-13,2,4,4,-11,5,4,4,-336,2,3,4,-10,4,3,4,-9,6,5,2,-10,4,3,2,14922,4,2,4,-8,3,4,3,-13,4,5,5,-12,6,4,3,9069,4,5,3,-10,4,5,3,-13,6,3,3,-14,4,2,3,-22,4,4,4,-11,4,4,5,-12,4,5,2,-14,4,4,3,-74,3,4,3,-13,4,5,5,-12,6,4,3,-14,4,2,4,3,3,4,3,-11,5,4,4,-11,5,5,3,-12,3,4,4,25,4,4,3,-8,2,4,4,-12,5,4,4,-12,5,5,3,-32,6,2,2,-9,3,[7,1],-13,3,3,2,-9,5,6,4,-33,7,3,4,-15,6,4,4,-12,3,4,4,[-10,1],3,5,-3184,5,3,2,-11,3,5,5,-9,3,5,2,-12,3,5,5,3165,3,3,3,-8,4,[7,1],-14,5,4,2,-12,4,5,4,132,3,6,3,-14,4,4,4,-9,4,2,4,-12,5,4,5,-13843,4,2,4,-7,4,5,2,-12,3,3,3,-10,8,4,2,3264,6,[5,1],-13,4,2,2,-9,4,[7,1],-13,4,3,4,-1137,5,5,4,-11,4,5,3,-14,3,4,3,-9,4,3,4,-106,3,3,3,-10,3,[9,1],-14,[6,1],2,-10,4,7,2,10374,4,2,3,-8,4,3,4,-9,4,3,3,-11,9,[3,1],3239,3,5,2,-12,4,4,6,-13,5,3,6,-12,4,4,2,-192,8,[5,1],-13,3,5,3,-13,4,3,4,-8,3,2,4,-5,7,3,2,-13,4,3,5,-14,4,4,3,-10,4,2,5,19,5,4,3,-10,4,5,3,-15,4,5,5,-12,3,3,3,-3192,4,6,2,-13,4,3,5,-13,3,4,3,-11,5,5,2,3052,3,2,4,-11,4,4,6,-13,2,6,3,-13,7,4,3,3,6,4,3,-12,3,3,4,-12,4,5,4,-10,3,4,5,-260,3,4,4,-14,8,3,2,-12,3,3,2,-7,3,7,3]
}
```

### CODE REVIEW

**Comment by grondo** [comment]
Ok, pushed some more fixes and updates, as well as enhanced tests including some sharness tests to exercise `stop-tasks-in-exec` + mpir proctable gather.

@dongahn, the new test executable `t/shell/mpir.c` may be instructive.

Removing `WIP` now. This is ready for a review. The main open question is whether we need to export the interface to grab the proctable from the shell(s) and build `MPIR_proctable` publicly outside of flux-core.

**Comment by grondo** [comment]
Force-pushed some minor fixes, refactoring, and toned down the trace log messages.

**Comment by dongahn** [comment]
@grondo: I have been swamped with SC meetings and other tasks. I will try to get to this on my returning flight. I definitely want to provide a review before I turn into a pumpkin tomorrow. Thanks.

**Comment by grondo** [comment]
That seems fine. I was going to put the basic support for MPIR_proctable into `flux job attach`, but I got distracted with #2554. This can always be added in a future PR.

**Comment by garlick** [comment]
Great, nice work!

**Comment by grondo** [comment]
Thanks!

**Comment by dongahn** [comment]
Sorry I wasn't able to get to this before my vac. Things were pretty hectic. The only thing I was able to catch back then was:

```
Typo in the commit message:

reuqester -> requester.
```

**Comment by grondo** [comment]
Oh, oops. Sorry we didn't catch that! Now it will be in history permanently as a reminder of human fallibility!

**Pull request merged**
