### PR TITLE
kvs & kvs-watch: misc cleanup & bug fixes

### PR DESCRIPTION
**Pull request by chu11**
while working on #1838, misc cleanups and bug fixes.

### CODE REVIEW

**Comment by chu11** [comment]
one build had a valgrind error.  Maybe #1641?  but seems to run through job.c.

```
expecting success: 
	run_timeout 120 \
	libtool e flux ${VALGRIND} \
		--tool=memcheck \
		--leak-check=full \
		--gen-suppressions=all \
		--trace-children=no \
		--child-silent-after-fork=yes \
		--num-callers=30 \
		--leak-resolution=med \
		--error-exitcode=1 \
		--suppressions=$VALGRIND_SUPPRESSIONS \
		${BROKER} --shutdown-grace=4 ${VALGRIND_WORKLOAD} 10
==805== Memcheck, a memory error detector
==805== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==805== Using Valgrind-3.13.0 and LibVEX; rerun with -h for copyright info
==805== Command: /usr/src/src/broker/.libs/flux-broker --shutdown-grace=4 /usr/src/t/valgrind/valgrind-workload.sh 10
==805== 
hwloc x86 backend cannot work under Valgrind, disabling.
FLUX_URI=local:///tmp/flux-bpPEvV
==805== 
==805== HEAP SUMMARY:
==805==     in use at exit: 6,347,963 bytes in 182 blocks
==805==   total heap usage: 958,977 allocs, 958,795 frees, 223,721,477 bytes allocated
==805== 
==805== 6,311,130 (16 direct, 6,311,114 indirect) bytes in 1 blocks are definitely lost in loss record 98 of 98
==805==    at 0x4C2FA3F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==805==    by 0x4C31D84: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==805==    by 0x4E88299: ev_realloc (ev.c:1741)
==805==    by 0x4E8CE08: ev_idle_start (ev.c:4611)
==805==    by 0x4E61360: then_context_start (future.c:180)
==805==    by 0x4E61360: post_fulfill.isra.6 (future.c:346)
==805==    by 0x4E5E439: response_cb (rpc.c:170)
==805==    by 0x4E59466: call_handler (msg_handler.c:229)
==805==    by 0x4E59B78: dispatch_message (msg_handler.c:246)
==805==    by 0x4E59B78: handle_cb (msg_handler.c:322)
==805==    by 0x4E880C2: ev_invoke_pending (ev.c:3314)
==805==    by 0x4E8B688: ev_run (ev.c:3717)
==805==    by 0x4E58612: flux_reactor_run (reactor.c:140)
==805==    by 0xB7CD10F: mod_main (job.c:938)
==805==    by 0x11433B: module_thread (module.c:158)
==805==    by 0x55BB6DA: start_thread (pthread_create.c:463)
==805==    by 0x636288E: clone (clone.S:95)
==805== 
{
   <insert_a_suppression_name_here>
   Memcheck:Leak
   match-leak-kinds: definite
   fun:malloc
   fun:realloc
   fun:ev_realloc
   fun:ev_idle_start
   fun:then_context_start
   fun:post_fulfill.isra.6
   fun:response_cb
   fun:call_handler
   fun:dispatch_message
   fun:handle_cb
   fun:ev_invoke_pending
   fun:ev_run
   fun:flux_reactor_run
   fun:mod_main
   fun:module_thread
   fun:start_thread
   fun:clone
}
==805== LEAK SUMMARY:
==805==    definitely lost: 16 bytes in 1 blocks
==805==    indirectly lost: 6,311,106 bytes in 96 blocks
==805==      possibly lost: 0 bytes in 0 blocks
==805==    still reachable: 36,321 bytes in 83 blocks
==805==         suppressed: 520 bytes in 2 blocks
==805== Reachable blocks (those to which a pointer was found) are not shown.
==805== To see them, rerun with: --leak-check=full --show-leak-kinds=all
==805== 
==805== For counts of detected and suppressed errors, rerun with: -v
==805== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 1 from 1)
```

**Comment by chu11** [comment]
just saw there were some ';;' typos in some code, so just added that patch on top.

**Comment by chu11** [comment]
oh wait, i just realized one of the bug fixes isn't necessary ... ugh. let me remove it.

**Comment by garlick** [comment]
LGTM!  Thanks!

**Pull request merged**
