### PR TITLE
Issue998: Add missing manpages, minor manpage fixes

### PR DESCRIPTION
**Pull request by chu11**

### CODE REVIEW

**Comment by garlick** [comment]
Maybe a cut and paste error in doc/man3/Makefile/am:

```make
flux_request_encode_raw.3: flux_response_decode.3
```

the dependency should be on `flux_response_encode.3`?

**Comment by chu11** [comment]
@garlick - doh!  Thanks for the catch.

**Comment by chu11** [comment]
Hmmm, travis failure with #993 ```FAIL: t0015-cron.t 10 - cron entry exec failure is recorded```.  Obviously didn't tickle this since this is just manpage updates.  Trying again.

**Comment by grondo** [comment]
Sorry about that, I updated the issue, it is most likely that the `sleep 0.1` isn't quite long enough on rare occasions...

**Pull request merged**
