### PR TITLE
Flux buffer w/ initial buffer reactors

### PR DESCRIPTION
**Pull request by chu11**
Initial flux buffer + read/write buffer reactor implementation for #1052.  Not ready for commiting, but wanted to get initial comments.

### CODE REVIEW

**Comment by grondo** [comment]
Thanks! This is looking pretty good. I will try to make a high-level pass soon and report any comments along the way.

**Comment by chu11** [comment]
Updated push of my tree,  Reactors now handle many corner cases I didn't see at first.  Mini fixes to buffer API.

As an experiment (patch is not in this PR), I replaced the pmi zio read/write reactors in wrexecd with these reactors and everything passed.

**Comment by grondo** [comment]
Nice work!

**Comment by chu11** [comment]
restarted a builder that hit a "write error", haven't seen one of these in awhile

**Comment by chu11** [comment]
> Other flux watchers were first implemented using composite libev watcher, then wrapped in reactor.[ch].

**Comment by chu11** [comment]
>  Other flux watchers were first implemented using composite libev watcher, then wrapped in reactor.[ch].

The main reason was that I was only using a "native" libev io watcher.

**Comment by chu11** [comment]
>  Other flux watchers were first implemented using composite libev watcher, then wrapped in reactor.[ch].

The main reason was that I was only using a "native" libev io watcher, so I didn't initially see the need to do a composite one.

However, looking at your old ev_zlist, it gave me an alternate viewpoint on how to write this reactor.  I could do the prepare/check/idle pattern which would allow me to remove the while loops in the middle of the ```buffer_read_cb```.  Let me see if this can be done and/or would be better.

> That function converts libev flags to flux flags, so I think in this case you just want to pass the flux flags directly to the flux watcher callback.

Ahh I see what you're saying.  Yeah, that can be simplified.

**Comment by garlick** [comment]
> The main reason was that I was only using a "native" libev io watcher, so I didn't initially see the need to do a composite one.

Got it.  

It may be beneficial to let the reactor run in between iterations of that loop.  For example, maybe another pending event will have a higher priority (like say a ctrl-C to end the program) and spinning in the read handler starves it out.

> Ahh I see what you're saying. Yeah, that can be simplified.

I think right now the flux bits are the same as the EV ones but if they were different, that would set the wrong bits.

**Comment by chu11** [comment]
re-pushed with a new implementation.  The read reactors are now in a composite prepare/check/idle file ```ev_buffer_read```.  The write reactor is simple enough it doesn't need prepare/check/idle, but I placed it in a ```ev_buffer_write``` file for consistency.

A few minor fixes/tweaks along the way and some additional tests.

**Comment by garlick** [comment]
Just a thought, but could the read_line variant of the watcher be eliminated if a flags argument were added to the regular read watcher, e.g. to select line buffered?

**Comment by chu11** [comment]
yeah, it definitely could.  I went back and forth on whether I should do that.  I honestly can't remember why I settled on it the way I did, but could go either way.

**Comment by grondo** [comment]
Now that @garlick mentions it, it might be better for extensibility+simplicity if we use a flags argument to indicate if the buffering is normal, line, or fully unbuffered. The flags field could additionally be used for other tunables in the future.

**Comment by chu11** [comment]
Sounds good.  I just pushed a change that collapses the read watcher & read line watcher into one with a new flags argument.  I also added a flags argument to the write watcher for future support.  I went ahead and just squashed the changes b/c its pretty tiny.

**Comment by garlick** [comment]
@grondo and I thought we'd go ahead and merge this as is, and if there are any additional issues, we can address them in separate pull requests.  Nice work!

**Pull request merged**
