### PR TITLE
t/barrier: Remove tbarrier executable

### PR DESCRIPTION
**Pull request by chu11**
The executable seems to have been accidentally commited in

bd17941567518b644b6070f7df36dec216f27402

### CODE REVIEW

**Comment by garlick** [comment]
Sorry, that was sloppy!  It was 6e8a5936f6fcac33a85fc3d4e7d2cc46ee947960 FWIW, same PR.  Will merge once travis turns green.

**Comment by chu11** [comment]
oops, cut & pasted the wrong commit.  I'll change the message.

**Comment by grondo** [comment]
Thanks, I just kept blindly deleting it thinking it was a byproduct of switching branches. :confused:

**Comment by garlick** [comment]
Thanks, again sorry.  Sheesh!

**Pull request merged**
