### PR TITLE
Valgrind fixes

### PR DESCRIPTION
**Pull request by garlick**
These are some fairly minor (mostly single call per broker invocation) memory leak fixes that I found when running valgrind.sh.

Not significant, but at least it reduces the noise coming out of that test.

The remaining leaks are all in modules, but I haven't quite yet figured out how to make valgrind provide useful data.  The reports look like this
```==30194== 88 bytes in 1 blocks are definitely lost in loss record 28 of 77
==30194==    at 0x4C2DB8F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==30194==    by 0xFA644A8: ???
==30194==    by 0xFA644DD: ???
==30194==    by 0xFA66719: ???
==30194==    by 0xFA670A0: ???
==30194==    by 0x1086DEFF: ???
==30194==    by 0xF62E2FC: ???
==30194==    by 0xF6279C6: ???
==30194==    by 0xF3E078A: ???
==30194==    by 0xF3E12FB: ???
==30194==    by 0x40AFDB: module_thread (module.c:158)
==30194==    by 0x59B16B9: start_thread (pthread_create.c:333)
==30194==    by 0x5ED182C: clone (clone.S:109)
```
so basically the module main is called (module.c:158) and something was leaked but we don't know which module it was.

### CODE REVIEW

**Comment by grondo** [comment]
I was able to get valid stack trace from modules by temporarily commenting out the call to `dlclose()` in `module_destroy`

Apparently valgrind does stack trace analysis after the program exits, and for any leaks in `dlopen`'d code valgrind won't be able to find valid address if you've called `dlclose` on the plugin/module.

**Comment by grondo** [comment]
oops, here was one source of noise:

```diff
diff --git a/src/modules/aggregator/aggregator.c b/src/modules/aggregator/aggregator.c
index fced1b3..076bb25 100644
--- a/src/modules/aggregator/aggregator.c
+++ b/src/modules/aggregator/aggregator.c
@@ -546,6 +546,7 @@ int mod_main (flux_t *h, int argc, char **argv)
 done_delvec:
     flux_msg_handler_delvec (htab);
 done:
+    aggregator_destroy (ctx);
     return rc;
 }
```

**Comment by garlick** [comment]
Nice!  Thanks, that works.  I'll try to run down a few more then.

**Comment by grondo** [comment]
Cool, thanks!

**Comment by garlick** [comment]
I pushed a couple more minor incidental memory related fixes, but think I've reached the point of diminishing returns on what's left in the valgrind report.
```
==40137== 88 bytes in 1 blocks are definitely lost in loss record 35 of 92
==40137==    at 0x4C2DB8F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==40137==    by 0xFA644A8: lt__malloc (in /usr/lib/x86_64-linux-gnu/libltdl.so.7.3.1)
==40137==    by 0xFA644DD: lt__zalloc (in /usr/lib/x86_64-linux-gnu/libltdl.so.7.3.1)
==40137==    by 0xFA66719: ??? (in /usr/lib/x86_64-linux-gnu/libltdl.so.7.3.1)
==40137==    by 0xFA670A0: lt_dlopenadvise (in /usr/lib/x86_64-linux-gnu/libltdl.so.7.3.1)
==40137==    by 0x1086DEFF: ???
==40137==    by 0xF62E2FC: ??? (in /usr/lib/x86_64-linux-gnu/libhwloc.so.5.6.8)
==40137==    by 0xF6279C6: hwloc_topology_init (in /usr/lib/x86_64-linux-gnu/libhwloc.so.5.6.8)
==40137==    by 0xF3E079A: ctx_hwloc_init (resource.c:68)
==40137==    by 0xF3E130B: resource_hwloc_ctx_create (resource.c:140)
==40137==    by 0xF3E130B: mod_main (resource.c:547)
==40137==    by 0x40AFDB: module_thread (module.c:158)
==40137==    by 0x59B16B9: start_thread (pthread_create.c:333)
==40137==    by 0x5ED182C: clone (clone.S:109)
==40137==
==40137== 512 bytes in 1 blocks are possibly lost in loss record 70 of 92
==40137==    at 0x4C2DB8F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==40137==    by 0x1473D1AE: list_alloc_aux (list.c:786)
==40137==    by 0x1473D3F7: list_node_alloc (list.c:742)
==40137==    by 0x1473D3F7: list_node_create (list.c:669)
==40137==    by 0x1473DC20: list_append (list.c:306)
==40137==    by 0x1473AFB9: optparse_add_option (optparse.c:946)
==40137==    by 0x1473B106: optparse_create (optparse.c:707)
==40137==    by 0x144FC433: getctx (userdb.c:105)
==40137==    by 0x144FC433: mod_main (userdb.c:368)
==40137==    by 0x40AFDB: module_thread (module.c:158)
==40137==    by 0x59B16B9: start_thread (pthread_create.c:333)
==40137==    by 0x5ED182C: clone (clone.S:109)
==40137==
==40137== 7,239 (16 direct, 7,223 indirect) bytes in 1 blocks are definitely lost in loss record 90 of 92
==40137==    at 0x4C2DB8F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==40137==    by 0x4C2FDEF: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==40137==    by 0x4E66189: ev_realloc (ev.c:1741)
==40137==    by 0x4E6AC25: ev_idle_start (ev.c:4611)
==40137==    by 0x4E65FD2: ev_invoke_pending (ev.c:3314)
==40137==    by 0x4E69A8D: ev_run (ev.c:3606)
==40137==    by 0x4E485AC: flux_reactor_run (reactor.c:135)
==40137==    by 0xCEC5BA9: mod_main (kvs.c:1744)
==40137==    by 0x40AFDB: module_thread (module.c:158)
==40137==    by 0x59B16B9: start_thread (pthread_create.c:333)
==40137==    by 0x5ED182C: clone (clone.S:109)
```

**Comment by grondo** [comment]
Yeah, the list node pool and dlopen "leaks" are known issues. I wonder if we should figure out how to include a valgrind suppressions file for those. Then we'd be close to having a test we could add to automated testsuite?

**Comment by grondo** [comment]
I ran with `--gen-suppressions=all` on valgrind and added the known leaks we want suppress to the existing valgrind.supp file:
```diff
diff --git a/src/test/valgrind.sh b/src/test/valgrind.sh
index 51e7e2f..93fd31b 100755
--- a/src/test/valgrind.sh
+++ b/src/test/valgrind.sh
@@ -15,6 +15,7 @@ ${top_srcdir}/src/cmd/flux /usr/bin/valgrind \
     --child-silent-after-fork=yes \
     --num-callers=30 \
     --leak-resolution=med \
+    --gen-suppressions=all \
     --suppressions=valgrind.supp \
     ${top_srcdir}/src/broker/.libs/lt-flux-broker \
     ./valgrind-workload.sh ${NJOBS}
diff --git a/src/test/valgrind.supp b/src/test/valgrind.supp
index 0c4d23d..be98911 100644
--- a/src/test/valgrind.supp
+++ b/src/test/valgrind.supp
@@ -12,4 +12,54 @@
    fun:send
    ...
 }
-
+{
+   <libev_io_start_realloc>
+   Memcheck:Leak
+   match-leak-kinds: indirect
+   fun:malloc
+   fun:realloc
+   fun:ev_realloc
+   fun:fd_change
+   fun:ev_io_start
+   fun:ev_invoke_pending
+   fun:ev_run
+   ...
+}
+{
+   <libltdl_known_leak>
+   Memcheck:Leak
+   match-leak-kinds: definite
+   fun:malloc
+   fun:lt__malloc
+   fun:lt__zalloc
+   obj:*/libltdl.so.7.3.1
+   fun:lt_dlopenadvise
+   ...
+}
+{
+   <list_node_alloc>
+   Memcheck:Leak
+   match-leak-kinds: possible
+   fun:malloc
+   fun:list_alloc_aux
+   fun:list_node_alloc
+   fun:list_node_create
+   fun:list_append
+   ...
+}
+{
+   <ipaddr_getprimary>
+   Memcheck:Leak
+   match-leak-kinds: definite
+   fun:malloc
+   obj:*
+   obj:*
+   obj:*
+   obj:*
+   fun:gaih_inet.constprop.5
+   fun:getaddrinfo
+   fun:ipaddr_getprimary
+   fun:calc_endpoint.isra.8
+   fun:boot_pmi
+   fun:main
+}
```

However, I still see this one leak(?) that I'm not sure about (on this branch I think)
```
==12501== 7,239 (16 direct, 7,223 indirect) bytes in 1 blocks are definitely lost in loss record 88 of 89
==12501==    at 0x4C2EB55: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12501==    by 0x4E473E6: flux_reactor_create (reactor.c:88)
==12501==    by 0x4E474E6: flux_get_reactor (reactor.c:119)
==12501==    by 0x1156AF: modservice_register (modservice.c:226)
==12501==    by 0x113998: module_thread (module.c:144)
==12501==    by 0x578E6C9: start_thread (pthread_create.c:333)
==12501==    by 0x5CB10AE: clone (clone.S:105)
==12501== 
{
   <insert_a_suppression_name_here>
   Memcheck:Leak
   match-leak-kinds: definite{
   <insert_a_suppression_name_here>
   Memcheck:Leak
   match-leak-kinds: definite
   fun:calloc
   fun:flux_reactor_create
   fun:flux_get_reactor
   fun:modservice_register
   fun:module_thread
   fun:start_thread
   fun:clone
}

   fun:calloc
   fun:flux_reactor_create
   fun:flux_get_reactor
   fun:modservice_register
   fun:module_thread
   fun:start_thread
   fun:clone
}
```

If we get this one analyzed and either fixed or suppressed, we could run `valgrind` with `--error-exitcode=1` to get a pass/fail test for new leaks. (Oh, though we'd also have to figure out how to avoid dlclose at runtime only under valgrind)

**Comment by garlick** [comment]
That last one has the same number of bytes leaked as the last leak I posted above, which also seemed to be reactor-allocated storage.  The one above entered through the kvs.

 Maybe a watcher is not being destroyed when the module exits and is holding a refcount on the reactor so it's not freed?

**Comment by grondo** [comment]
That is what I assumed as well. However, there is not any good way to track down even the module to which it belongs.

**Comment by grondo** [comment]
Pushed some experimental fixes here:
 
 1. Add an intercept function for `dlclose` when running under valgrind, when `valgrind/valgrind.h` is available. When compiled this way, `dlclose` is avoided (the wrapped function does nothing) *only* when running under valgrind, so that valgrind can report stack traces for broker modules.
 2. Add a few known memory leaks to valgrind suppression file
 3. A *possible* fix for dispatch and reactor leakage when fastpath is activated for a dispatcher. Honestly, i didn't spend enough time to understand the fastpath code in `dispatch.c`, but I did track down the final leak reported by `valgrind.sh` to something holding a reference to the dispatcher which in turn held a reference to the reactor. I still don't understand why fastpath branch in `flux_msg_handler_destroy` calls `free_msg_handler` while the other branch just sets `w->destroyed`, but it did seem like a call to `dispatch_usecount_decr()` was missing here. In any case, @garlick can you review c8db59a?

**Comment by grondo** [comment]
BTW, on the current branch `valgrind.sh` runs "clean" (at least on my desktop). So we *could* turn this into an automated test (with possibly limited scope, but perhaps it would be helpful)

**Comment by garlick** [comment]
That does indeed look right!  Good catch.

To explain the other question:  The fastpath handlers aren't in the dispatcher's zlist_t that it walks in its `dispatch_message()` loop, so there is not a need to defer their removal.  Although I'm not entirely certain that this is even necessary.  I had been operating under the assumption that zlist was not remove-safe during traversal, but as discussed in #1066, they actually are.

**Comment by grondo** [comment]
> To explain the other question: The fastpath handlers aren't in the dispatcher's zlist_t that it walks in its dispatch_message() loop, so there is not a need to defer their removal.

Ah, ok, maybe I'll add a comment to this effect, perhaps with a FIXME or something to clean up normal handler removal in the future?

**Comment by garlick** [comment]
> Ah, ok, maybe I'll add a comment to this effect, perhaps with a FIXME or something to clean up normal handler removal in the future?

Sounds fine.

Wiring valgrind into make check will be really valuable going forward I think, and incidentally satisfies #161 which I closed as hopeless a while back :-)

**Comment by grondo** [comment]
Hm, I added `-j2` to make on this branch, as it speeds up `make check` considerably. However, now I've been seeing a lot of failures with `"write error"` in travis. I wonder if I should back out the change.

**Comment by garlick** [comment]
We had a failure in the clang builder and I'm having a hard time finding what happened.

The cooked output is truncated at the bottom, so I don't get the nice little "after_failure" rolled up output anymore - is that just me?  Having a bit of difficulty figuring out what went wrong even after downloading the raw text log and grepping for "FAIL:  "...  Will have another look later.

**Comment by grondo** [comment]
Yeah, this was the same write error during `distclean` that I've been seeing a lot on this branch:
```
make[4]: Leaving directory `/home/travis/build/flux-framework/flux-core/flux-core-0.7.0-239-g086abf3/_build/sub/src/common/liboptparse'
make[4]: write error
make[3]: *** [distclean-recursive] Error 1
make[3]: Leaving directory `/home/travis/build/flux-framework/flux-core/flux-core-0.7.0-239-g086abf3/_build/sub/src/common'
make[2]: *** [distclean-recursive] Error 1
```

(In the raw log if you search for "`exited with`" this usually takes you to where the build errored)

I'm not sure why but perhaps `make -j2` is causing this? I could revert that change and try again, though a restart of the build would also likely be successful. I don't want to destabilize future builds though.

**Comment by grondo** [comment]
Removal of `-j2`seems to have made the travis tests more reliable, so let's leave it at that.

**Comment by garlick** [comment]
Thanks for all this!  This should really keep us honest going forward.

**Pull request merged**
