### PR TITLE
Broker cleanup 1

### PR DESCRIPTION
**Pull request by morrone**
Minor code cleanup in the flux broker.

### CODE REVIEW

**Comment by morrone** [comment]
The reported code coverage changes probably aren't real?

**Comment by grondo** [comment]
Yeah, the overall change is minimal and probably just noise. The patch coverage is low probably due to error paths.

This just needs to be rebased on current master

**Comment by garlick** [comment]
@morrone I think you'll want to try again with a rebase not a merge to keep the merge commit out of the history.

**Comment by morrone** [comment]
@garlick, Ah, I was trying github's magic "update branch" button.  Apparently that isn't that useful. :)

**Comment by grondo** [comment]
> @garlick, Ah, I was trying github's magic "update branch" button. Apparently that isn't that useful. :)

Yeah, I really wish they had a "rebase branch" button, that would be awesome...

Looks good, I'll merge.

**Comment by morrone** [comment]
Part of the cleanup for issue #1236.

**Pull request merged**
