### PR TITLE
kvs: Return error that occurs in kvs.relayfence

### PR DESCRIPTION
**Pull request by chu11**
Note that this PR comes after #1308 (patches in #1308 are included here).  I will rebase after #1308 is merged in.

I originally had this patch mixed in with my remove namespace PR, but it seems independent of everything else, so I've now spliced it into its own PR.

The ```relayfence_request_cb()``` function presently does not return an error to the original rpc fence/commit request if an error occurs within this function.  An error could be returned to the user only within the ```commit_apply()``` path of the code if we reached that path and an error occurred within there.

This patch fixes the problem by effectively calling the error path from ```commit_apply()``` if an error occurs within this function.

Unfortunately, outside of some serious code instrumentation, this patch is basically untestable and I bet will have about 0% diff coverage.  The error paths are either "impossible" paths or extreme racey paths.

### CODE REVIEW

**Comment by chu11** [comment]
While driving home, it occurred to me that I implemented this backwards.

The original ```error_event_send()``` handles an array of names.  I wrote a new function  ```error_event_send_to_name()```, which converts a single ```name``` to an array with one ```name``` in it so it can call ```error_event_send()```.  I shouldn't have done that.  I should convert the original function to process only a single name and then write a function that handles an array.  That function would then call the singular name function.

**Comment by chu11** [comment]
Ugh ... never mind that prior comment.  I was confusing ```error_event_send()``` with ```error_event_cb()```.  What I did is the right thing.

**Comment by chu11** [comment]
rebased on master and pushed.  Expecting near 0% diff coverage.

**Comment by garlick** [comment]
Just checking:  does this new error path ensure that at most one event is generated per commit?

It does seem like you could shorten `error_event_send_to_name()` quite a bit by using `json_pack()` to create the single element array...

**Comment by chu11** [comment]
Yes.  Basically if we reach ```commit_mgr_process_fence_request()``` then the fence is now a "ready commit" and enters the codepath that would return an error via ```commit_apply() -> error_event_send()```.  This captures errors in which ```commit_mgr_process_fence_request()``` fails or is never reached, so an error event is only generated once.

Good point, ```json_pack()``` would be a lot better.  I'll cleanup, rebase, and re-push.

**Comment by chu11** [comment]
re-based and re-pushed

**Comment by garlick** [comment]
Great thanks!

**Pull request merged**
