### PR TITLE
shell: do not exit from shell initrc scripts when posix module not found

### LINKED ISSUE #2698: Do not include flux.posix Lua module in shell rc files
When the Lua posix module isn't in `LUA_PATH`/`LUA_CPATH` and you attempt to run a job, you get the very helpful error:
```
$ flux mini run -n2 -N2 hostname
flux-job: No job output found
flux-job: task(s) exited with exit code 1
```

(Thanks for reporting @rountree)

The logs show:
```
2020-01-31T02:07:43.135490Z job-exec.info[0]: 331115134976: 0: stderr: Required Lua 'posix' module not found. Please check LUA_PATH or install package
2020-01-31T02:07:43.135612Z job-exec.info[0]: 331115134976: 1: stderr: Required Lua 'posix' module not found. Please check LUA_PATH or install package
```

The problem is that the `mvapich.lua` rc script loads the `flux.posix` module, which does this:
```lua
 --
 -- flux-lua.posix: wrapper to check for existing of system 'posix'
 --  module and return user friendly error instead lua stack dump
 --
local status, rc = pcall (require, 'posix')
if not status then
    io.stderr:write ("Required Lua 'posix' module not found."..
                    " Please check LUA_PATH or install package\n")
    os.exit (1)
end
```

Obviously, exiting out from under the shell is bad. None of the shell rc scripts should therefore require `flux.posix` and I'm wondering if we even need this little hack anymore.

### PR DESCRIPTION
**Pull request by grondo**
This PR mainly fixes #2698, however some other deficiencies in the shell initrc were fixed along the way. While debugging this I found the lack of a logging interface from initrc.lua a bit frustrating, so that was added here as well.

Before, we see this if the posix module is not found:
```
$ flux mini run hostname
flux-job: No job output found
flux-job: task(s) exited with exit code 1
```

After, just a wee bit more detail.
```
$ flux mini run hostname
0.063s: flux-shell[0]: ERROR: /home/grondo/git/f.git/src/shell/lua.d/mvapich.lua:11: module 'posix' not found:
	no field package.preload['posix']
	no file '/home/grondo/git/f.git/src/bindings/lua/posix.lua'
	no file '/home/grondo/git/f.git/t/posix.lua'
	no file '/usr/local/share/lua/5.2/posix.lua'
	no file '/usr/local/share/lua/5.2/posix/init.lua'
	no file '/usr/local/lib/lua/5.2/posix.lua'
	no file '/usr/local/lib/lua/5.2/posix/init.lua'
	no file '/usr/share/lua/5.2/posix.lua'
	no file '/usr/share/lua/5.2/posix/init.lua'
	no file './posix.lua'
	no file '/home/grondo/git/f.git/src/bindings/lua/posix.so'
	no file '/usr/local/lib/lua/5.2/posix.so'
	no file '/usr/lib/x86_64-linux-gnu/lua/5.2/posix.so'
	no file '/usr/lib/lua/5.2/posix.so'
	no file '/usr/local/lib/lua/5.2/loadall.so'
	no file './posix.so'
0.063s: flux-shell[0]: ERROR: /home/grondo/git/f.git/src/shell/initrc.lua:8: source /home/grondo/git/f.git/src/shell/lua.d/mvapich.lua failed
0.063s: flux-shell[0]: FATAL: loading rc file /home/grondo/git/f.git/src/shell/initrc.lua
0.065s: job.exception type=exec severity=0 loading rc file /home/grondo/git/f.git/src/shell/initrc.lua
flux-job: task(s) exited with exit code 1

```

Actually it seemed silly to require the posix module for `dirname()`, so now the posix module is not required, except for the spectrum MPI case I think.

### Commit Message
shell: initrc: fix bad exit in mavpich rc script, add logging

 * add shell.log, shell.debug, shell.log_error and shell.die
   for use in shell rc scripts
 * avoid the use of `flux.posix` module in flux-shell rc scripts

### CODE REVIEW

**Comment by grondo** [comment]
Eh, the mvapich personality test is now failing in Travis, though I can't get it to fail locally. I'll try to fix asap.

**Comment by grondo** [comment]
Ok, fixed an error in the mvapich.lua initrc script and also a bug in the shell.log implementation (found by address-sanitizer and due to a misunderstanding by my of `struct lua_Debug` structure!)

**Comment by grondo** [comment]
```console
$ git branch | grep '\*'
* issue#2698
$ ldd ./hello | grep mvapich
	libmpi.so.12 => /usr/tce/packages/mvapich2/mvapich2-2.3-intel-18.0.1/lib/libmpi.so.12 (0x00002aaaaaccf000)
$ flux mini run -N4 -n16 ./hello 
0: completed MPI_Init in 0.489s.  There are 16 tasks
0: completed first barrier in 0.002s
0: completed MPI_Finalize in 0.030s
```

Not too surprising, there should be no functional difference in the mvapich initrc script.

**Comment by garlick** [comment]
Thanks, maybe I was being overly paranoid.  Setting merge-when-passing.

**Comment by grondo** [comment]
Oops, I didn't fix the typo yet. Hold on.

**Comment by garlick** [comment]
Right, was just noticing that.

**Comment by grondo** [comment]
> Thanks, maybe I was being overly paranoid. Setting merge-when-passing.

No it was fine, there could have been a bug in the change to how/when LD_LIBRARY_PATH was prepended. (Though hopefully the sharness tests test that well enough.)

**Comment by grondo** [comment]
Ok, force pushed with the typo fix I hope!

**Comment by SteVwonder** [comment]
Very nice! Thanks @grondo!

**Pull request merged**
