### PR TITLE
librouter: factor common code from connector-local, flux-proxy

### PR DESCRIPTION
**Pull request by garlick**
This is a very preliminary PR to factor out code that is repeated in `connector-local` and `flux-proxy` into an internal library as suggested in #2302 

This isn't ready for review yet.  Just parking here while I context switch back to our exec parity milestone.

TODO:
* [x] move `flux_msg_recvfd()`, iobuf, etc out of public message class, into private librouter
* [x] expand commit comments
* [x] make service registration code asynchronous
* [x] drop job heuristic from `flux-relay`
* [x] unit tests for router class
* [x] unit tests for subhash class
* [x] further unit tests for usock class
* [x] expand ssh:// connector sharness test
* [x] expand flux-proxy sharness test
* [x] expand msg_handler unit test coverage (handler priority, responses w/ non-empty route stack)
* [x] factor out client side code from ssh and local connectors

### CODE REVIEW

**Comment by garlick** [comment]
Rebased and squashed some incremental development.

**Comment by garlick** [comment]
Added long commit messages for librouter "classes", and rebased on #2375

**Comment by garlick** [comment]
I finally worked through everything I had planed to do in this PR so I've removed the WIP prefix and would like to do what I can to facilitate a review.

I will say this code was already pretty well covered by tests, and it now has some additional unit tests that fill in some gaps.  So I'm too worried that I've introduced any unintended side effects.  However it is quite a lot of change, the highlights of which are:
* The introduction of librouter, a toolkit for building connectors and "routers" (with unit tests)
* Significant reduction in complexity of `flux-proxy`, `connector-local`, and ssh and local connectors
* New vendored libyuarel URI parser (replacing one-off, not well tested code in ssh:// connector)
* New `flux-relay` tool used by ssh:// connector (allowed `flux-proxy` to be simplified)
* `flux-proxy` now supports dynamic service registration (as will all router tools using librouter)

FWIW I did just poke at a 64 node flux instance on fluke and didn't find anything amiss.

**Comment by grondo** [comment]
If this PR is mainly a refactor, do you have a sense of where ~4,000 added lines were? Just trying to get an idea of where to apply effort for a quick test and review. 

I don't think we need to or have the time to do a detailed review of this much new code, so my plan was just poke at it for awhile...

**Comment by garlick** [comment]
> If this PR is mainly a refactor, do you have a sense of where ~4,000 added lines were? Just trying to get an idea of where to apply effort for a quick test and review.

Where is that number coming from?  (sorry if I should know).  Some growth could be explained by:
*  Code that was compact when embedded in e.g. `connector-local` and `flux-proxy` did expand a bit as it was turned into "classes" in librouter
* There's a bout 2.2K lines of new unit tests in librouter/test
* libyuarel and its tests accounts for about 900 lines
* flux-relay is a new command (about 300 lines)
* sharness tests expanded

But there there is significant shrinkage in the connector-local, flux-proxy, ssh connector, local connector.  Hmm.

> I don't think we need to or have the time to do a detailed review of this much new code, so my plan was just poke at it for awhile...

I would say none of the algorithms or approaches in librouter are "new", but interfaces needed to be invented for some of it to make it reusable and separately testable.   I hesitate to call it a rewrite, because I just made it more encapsulated, included more defensive checks, etc..  But comparing the old code and the new code would be laborious, so maybe it is.

I'm not sure you could possibly poke at the local connector (or connector-local module) more than our tests already do, but it may be useful to try some creative stuff with the ssh:// connector and flux-proxy.  I've expanded their sharness tests, but may still have missed something.

**Comment by grondo** [comment]
> Where is that number coming from? (sorry if I should know). Some growth could be explained by:

Sorry, I was just checking the `diffstat`-like numbers on the upper right  [here](https://github.com/flux-framework/flux-core/pull/2354/files). It is possible they are off for some reason.

Thanks for the tips!

**Comment by garlick** [comment]
Maybe I ought to split out the libyuarel addition + ssh connector use of it to a separate PR.

**Comment by garlick** [comment]
Rebased on current master, and tightened up the authentication in flux-proxy and flux-relay.

**Comment by grondo** [comment]
Sorry, just started poking at this today.

Here's one minor issue I ran across (a little better error message needed):
```console
$ flux proxy foo
flux-proxy: foo: Success
```

Some of the other errors could use a more useful error message too, e.g.:
```console
$ flux proxy local:///tmp/grondo
flux-proxy: local:///tmp/grondo: No such file or directory
$ ls -ld /tmp/grondo
drwxrwxr-x 2 grondo grondo 4096 Oct 15 02:56 /tmp/grondo
```

Though I'm not sure this is critical to fix now.

I didn't find any other issues so far. Nice work!

**Comment by garlick** [comment]
Good catch!  The error handling in `flux_open()` was kind of messed up so I just pushed a fix to make sure errno is set/preserved in all the error cases, including making your first case an ENOENT error. 

I have a PR in the works that changes the local URI to make the URI path == the socket path instead of the directory containing it.    Maybe that will make the second case error more intuitive (since the URI will refer to a file (socket) instead of a directory?

I'm not sure how to do much better without changing the `flux_open()` API signature, which would definitely be a different PR.

**Comment by garlick** [comment]
Restarted a builder that failed with
```
==6157== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
Alarm clock
not ok 1 - valgrind reports no new errors on 2 broker run
```

**Comment by grondo** [comment]
Yeah, we can fix `flux_open` later. It would be nice if commands returned user readable errors in most cases instead of just `strerror (errno)`, however that is probably for the hardening/improvement phase, not for now.

**Comment by garlick** [comment]
OK, here goes!

**Comment by garlick** [comment]
Whew, nice to have that done with.  Thanks @grondo.

**Pull request merged**
