### PR TITLE
job-archive support

### PR DESCRIPTION
**Pull request by chu11**
Per #2863, part 1 first attempt at job-archival.  Instead of going into a DB, it just goes into a text file.  Just want to get the basics working and get some basic tests written up.  Some things to consider:

- how should user consider period / location of file.  I just have command line args to the module right now.  Perhaps need an equivalent to `content-backing.patch` for the file location (and eventual DB location).
- Working on #2778 (job-info list RPC restart) may be important to do to avoid huge returns from job-info

### CODE REVIEW

**Comment by garlick** [comment]
I think I've lost track of the plan here.  Would this module export a query interface to the bank/accounting subsystem and any other consumers of historical job data?

**Comment by chu11** [comment]
No, the bank/accounting system would read from the database directly.  How we might eventually have users read historical data is TBD.

**Comment by garlick** [comment]
> No, the bank/accounting system would read from the database directly. 

That being the case, were you proposing to merge the file backend format, or looking for feedback, or...?

One thought: if this is going to be a module that is loaded for the lifetime of the instance,  it might be more efficient to listen for job state transition events and take action once some threshold number of unprocessed inactive jobs has been reached than periodically querying job-info...

**Comment by chu11** [comment]
> That being the case, were you proposing to merge the file backend format, or looking for feedback, or...?

Mostly the latter, but would consider the former.  However, as I experiment putting this into an sqlite database yesterday, perhaps its not as much code as I thought it would be.  So I'll make this a [WIP].

**Comment by chu11** [comment]
> One thought: if this is going to be a module that is loaded for the lifetime of the instance, it might be more efficient to listen for job state transition events and take action once some threshold number of unprocessed inactive jobs has been reached than periodically querying job-info...

Hmmm.  I see your point.  I was working off of the `job-info.list-inactive` service since that was the original plan for when this would be done by `flux-sched` in their own module/tool.

That said, while it might be more efficient, not sure its worth the energy to implement the more efficient way right now.  As @grondo says in #2863, the number one goal is to get this into a DB so ` fairshare/accounting` can do their thing.  How this will eventually work with job-info, users querying older data, any potential caching that goes on for recently requested stuff, that is all still TBD.

**Comment by garlick** [comment]
> the number one goal is to get this into a DB so fairshare/accounting can do their thing.

Agreed!

**Comment by grondo** [comment]
> That said, while it might be more efficient, not sure its worth the energy to implement the more efficient way right now. 

On the other hand, it is a bit strange to have this facility be a module resident in the broker address space when it isn't offering any services, and basically just wakes up every N secs and does the equivalent of:
```
$ flux job list-inactive --since X >> file.txt
```

Which could be implemented by a script using services we already do provide in a Flux instance. (Didn't mean to disparage the current work in any way. If there is some reason this *needs* to be a module in C, then I may have just missed it)

**Comment by chu11** [comment]
> Which could be implemented by a script using services we already do provide in a Flux instance. 

Could we imagine this as a script (python or possibly bash) that is just run out of cron instead?

> (Didn't mean to disparage the current work in any way. If there is some reason this needs to be a module in C, then I may have just missed it)

I think you had suggested a Python script in an earlier discussion.  Some python bindings for some services were missing, so I somewhat lazily decided to implement in C instead.  In addition, there was a possibility of how this would eventually (down the road) integrate with job-info.  That's all TBD of course.

So the reasons for doing it in C were not good per se ..

**Comment by chu11** [comment]
> Which could be implemented by a script using services we already do provide in a Flux instance. 

Could we imagine this as a script (python or possibly bash) that is just run out of cron instead?

> (Didn't mean to disparage the current work in any way. If there is some reason this needs to be a module in C, then I may have just missed it)

I think you had suggested a Python script in an earlier discussion.  Some python bindings for some services were missing, so I somewhat lazily decided to implement in C instead.  In addition, there was a possibility of how this would eventually (down the road) integrate with job-info.  That's all TBD of course.

So the reasons for doing it in C were not good per se ..

**Comment by grondo** [comment]
> So the reasons for doing it in C were not good per se ..

Well if it was *easier* to develop in C then my suggestion was kind of moot. I was mainly thinking that it would be much more agile to just implement a dumb script until we had a real backend format in mind (e.g. I was looking at how easy it was to dump data into InfluxDB from Python the other day), and 2nd -- it always feels a bit strange to me to have a module loaded into the broker that doesn't provide any services, it is only a client of broker services... (I could be wrong about these though)

**Comment by chu11** [comment]
> Well if it was easier to develop in C then my suggestion was kind of moot. I was mainly thinking that it would be much more agile to just implement a dumb script until we had a real backend format in mind 

I have a good chunk of the sqlite portion of this working, so lets start with this and see where it gets us.  For all we know it may not work for @cmoussa1 and @dongahn at all, and we gotta regroup anyways.

**Comment by chu11** [comment]
just re-pushed, now the branch stores to a database instead of a file.  I think the most interesting thing is the table entries.

```
$ sqlite3 -line /tmp/achu/foo.db 'PRAGMA table_info(jobs);' | grep name
      name = id
      name = t_inactive
      name = eventlog
      name = jobspec
      name = R
```

while I only "need to" store eventlog, jobspec, and R, I added `t_inactive` b/c it's a pain to parse eventlog when the module is restarted.  vs. just a simple sql query of `SELECT MAX(t_inactive) FROM jobs;`

here's a sample line from the db (length truncated for readability).

```
$ sqlite3 -line /tmp/achu/foo.db 'select * from jobs where id=278602448896;' 
        id = 278602448896
t_inactive = 1586290375.47324
  eventlog = {"timestamp":1586290375.3700647,"name":"submit","context":{"userid":8556,"priority":16,"flags":0}}
<SNIP>
<SNIP>
   jobspec = {"resources": [{"type": "slot", "count": 1, "with": [{"type": "core", "count": 1}], "label": "task"}],
<SNIP>
<SNIP>
         R = {"version":1,"execution":{"R_lite":[{"rank":"0","children":{"core":"0"}}]}}
```

the fact that I bothered to put `t_inactive` in the DB means that perhaps this is no the right approach.  If I'm finding it annoying to parse eventlog for `t_inactive`, I imagine that it'll be 10 times more annoying for the sched team to parse it for their purposes.

So this sort of gets back to the issue I brought up in #2863 about whether there should be a database for accounting purposes and a separate database for job-info history purposes.  But of course, we not have time on our side for that.

Sooo ... perhaps I should just store both types of data in the DB for the time being.  In other words, store, jobid, eventlog, jobspec, R (which is what job-info will need long term), but also store (I think) userid, nnodes, node ranks, t_submit, t_run, t_inactive (or maybe just calculate runtime), and maybe that is enough for accounting purposes?

**Comment by grondo** [comment]
> So this sort of gets back to the issue I brought up in #2863 about whether there should be a database for accounting purposes and a separate database for job-info history purposes. But of course, we not have time on our side for that.

Would the [JSON1](https://www.sqlite.org/json1.html) extensions to sqlite be helpful here? 

It feels like it should be *possible* to create a  job database that can satisfy general type queries that work for both accounting use cases, and the job history use cases. Maybe in the near future we need to list some concrete use cases?

**Comment by chu11** [comment]
> Would the JSON1 extensions to sqlite be helpful here?

Hmmm.  it might be.  For the specific `t_inactive` case, it's a tad annoying b/c the eventlog is a newline separated list of different json objects, so dunno if the extensions would work there.

**Comment by grondo** [comment]
Not sure if I'm contradicting something I said earlier, but it seems fine to break out some common search fields in the database (like t_inactive). We might also want the other transition timestamps, since (eventual) common queries to this db might be things like query all the jobs running on rank N between time A and B, or give me the queue from 12am.

**Comment by chu11** [comment]
> Not sure if I'm contradicting something I said earlier, but it seems fine to break out some common search fields in the database (like t_inactive). We might also want the other transition timestamps, since (eventual) common queries to this db might be things like query all the jobs running on rank N between time A and B, or give me the queue from 12am.

Yeah, after this little experiment, I'm thinking we want to put a number of common things into the table.

**Comment by cmoussa1** [comment]
If it is any help, here's a list of common job attributes we gathered while looking at job history from Slurm, along with an attribute like `t_inactive`:

**JobID, User, Nodes, Submit Time, Start, End, Elapsed, Hosts**

**Comment by chu11** [comment]
> JobID, User, Nodes, Submit Time, Start Time, End Time, Elapsed Time, Hosts

We don't have an elapsed time, so I assume you can do Start Time - End Time?

Also, what is "Hosts"?  Is that different than Nodes?

**Comment by cmoussa1** [comment]
> We don't have an elapsed time, so I assume you can do Start Time - End Time?

This was my assumption too. 👍

> Also, what is "Hosts"? Is that different than Nodes?

No, those should have been the same field, sorry. So, to narrow down the fields:

**JobID, User, Nodes, Submit Time, Start Time, End Time** could be retrieved, and **Elapsed Time** could be a field calculated using the Start Time and End Time values.

**Comment by chu11** [comment]
Just re-pushed:

- Added new columns for `userid`, `ranks`, `t_submit`, `t_sched`, `t_run`, and `t_cleanup`.

So here's whats in the DB now

```
sqlite3 -line /tmp/achu/foo.db 'PRAGMA table_info(jobs);' | grep "name = "
      name = id
      name = userid
      name = ranks
      name = t_submit
      name = t_sched
      name = t_run
      name = t_cleanup
      name = t_inactive
      name = eventlog
      name = jobspec
      name = R
```

- obviously could add a bit more (`name` comes to mind) for possible user queries against the DB, but above should be good for fairshare I think.
- fixed corner case for jobs that are never run (i.e. `t_run` is 0.0, `R` is never created, etc.)
- REAL values in `sqlite` appear to be truncated to 5 decimal places, and as far as I can tell there's no way to make it more precise so there are potential corner cases where  `MAX(t_inactive)` is technically less than the "real" max `t_inactive`.
- b/c the database can be used by multiple clients, deal with some locking issues.

**Comment by chu11** [comment]
hmmm tons of travis failures, caused (presumably) by tons of:

```
2020-04-10T00:30:46.531044Z job-archive.err[0]: job_list_inactive_continuation: flux_rpc_get_unpack: Connection timed out
2020-04-10T00:30:46.532481Z job-archive.err[0]: job_list_inactive_continuation: flux_rpc_get_unpack: Connection timed out
```

My test has "spinning" to check if things have completed, and the job archive is also "spinning" and archiving jobs every 0.5 seconds.  Wondering if that's just too much for travis on its 1 virtual CPU.

Was able to emulate via `taskset 1 ./t2220-job-archive.t`, but no failures on LC machines. 

I'll have to see if there's a more creative way to do these tests.

**Comment by chu11** [comment]
ugh, I hit a corner case in my testing yesterday and as I peeled away the onion things started to get not good.

- everytime a new row of data is written to the database, there is a chance that the insert can fail b/c the database is locked.  This is b/c the database can be read by an outside reader.  This is in contrast to the content store, which data can only be read/written through its interface/service.
- AFAICT (I obviously don't know sqlite perfectly), there is no way to avoid this.  There is no way to tell sqlite to not lock the database on reads (and even if there were, can't necessarily control readers from doing so).  In mysql apparently locks are optional and at user discretion (not an expert, based on limited googling).

So how does one avoid losing records?
- retry for a bit, bad since this is a broker module.  Would be ok if this is like a cron job or something.  Obvious downside is don't know how long you'll be "spinning".  and at some point you have to error out and try one of the below anyways.
- save failed record off somewhere, try again later.  Bad if this list of failed writes starts to grow really large (i.e. reader errors).
- just fail all of the writes on this "loop", and just re-get/retry records next "loop"
  - I initially tried this approach and hit several problems, most notably that all inserts would have to be "bulk" read in one go, otherwise it is difficult to ascertain which records failed and how to retrieve records for the next "loop".  Don't like the idea of doing a composite future with possibly 1000s of futures in it.

I don't think researching a new/better database is feasible given our timeline.  So trying to think of what is the most reasonable solution that wouldn't be horrible to implement.

First thought is that maybe this implementation is simply a mistake.  By removing KVS lookups on `R`, `jobspec`, and `eventlog` this implementation would be a lot easier. That means this database would ultimately not really be usable as a job archival for `job-info` and likely no `sacct` kind of tool could be associated with it.  It's just going to be used by flux accounting for fair share.  Thus perhaps this doesn't even need to be a C based broker module anymore, just a Python based cron job.  Thus, defeating the whole point of this implementation, ugh ... can discuss at coffee meeting.

**Comment by garlick** [comment]
There is a sqlite3 scheme for prioritizing the writer so that it can't be starved out by readers.  I think it's OK for the module to block waiting for its write lock.

See also:  https://www.sqlite.org/lockingv3.html

Can the module be simplified in terms of the need to cache a lot of inbound data by a) blocking RPCs that trigger db writes until the write is complete (as a form of flow control) or even b) only allow one such RPC in at a time?

**Comment by chu11** [comment]
I saw that page before, but it was not clear to me how to "obtain" a lock (as I was thinking about it in systems programming).  It appears it just "works" behind the scenes.

After digging for awhile, I came upon a realization ... the error message from sqlite is "database is locked", which I had assumed mapped to the SQLITE_LOCKED error code.  However, it ended up I was getting the SQLITE_BUSY error code all along.

So perhaps busy waiting a little bit is more than acceptable.  At some point of busy waiting, do we just give up and accept the rare lost record?

**Comment by garlick** [comment]
Hmm, yeah it does look like busy-waiting is the way this is expected to be handled:

https://www.sqlite.org/c3ref/busy_timeout.html

> At some point of busy waiting, do we just give up and accept the rare lost record?

I'd say for the first cut, don't give up.  Wait and see if it becomes a problem?

**Comment by chu11** [comment]
re-pushed, fixing a stupid bug that was affecting travis runs.  Big change is adding a `busytimeout` configuration and busy waiting configuration into sqlite.  Then in the rare circumstances where that timeout fails (leading to SQLITE_BUSY errors), I busy wait in the module and retry until a commit succeeds.  I just hardcoded a `usleep (1000)` somewhat randomly as the sleep time during this busy wait.  Dunno if that's a decently selected time amount.

**Comment by chu11** [comment]
one question I thought of recently.  I'm not entirely sure what mechanism we would do to load this module.  Do we want to put it in the flux rc scripts?  Loading only on rank 0?  On production machines, we might only want to load it on backup management nodes.  Not sure what the right procedure would be.

**Comment by garlick** [comment]
> One question I thought of recently. I'm not entirely sure what mechanism we would do to load this module. Do we want to put it in the flux rc scripts? Loading only on rank 0? On production machines, we might only want to load it on backup management nodes. Not sure what the right procedure would be.

For now does it make sense to load it on rank 0 in the rc unconditionally?  If we want, it could be "dormant" unless a path and/or a period is configured in TOML, thereby making it easy to activate for the system instance, but otherwise effectively off?   (Or would we want it on for all instances?)

**Comment by chu11** [comment]
> For now does it make sense to load it on rank 0 in the rc unconditionally? If we want, it could be "dormant" unless a path and/or a period is configured in TOML, thereby making it easy to activate for the system instance, but otherwise effectively off? (Or would we want it on for all instances?)

Right now there's a default path for the config file out of the rundir, but yeah, perhaps it should only run if an actual path is configured and otherwise do nothing.

All my configing is via module command line parameters right now.  Should the module command line parameters be axed?  We got some modules that are still configured via that way and some (just exec?) done via toml.  Do we want everything to move over to the toml way?

**Comment by chu11** [comment]
re-pushed with some new packages for testing in travis, wasn't aware that I was missing the `sqlite` command line tool.

**Comment by chu11** [comment]
ugh ... travis installed sqlite v2, not v3, so gotta somehow make the tests portable across

**Comment by chu11** [comment]
re-pushed and removed WIP, as its approaching something that's merge-able

- if user does not configure a db path, the module does nothing when loaded
- config via toml file, with module params that can override
- tests added appropriately

**Comment by grondo** [comment]
One comment I had while experimenting with this branch is whether it would make sense to  use a small python script to drive the testing instead the `sqlite3` binary. Not only  would this remove a new dependency (afaict, the sqlite module is part of the Python standard library), but perhaps the testing script could turn into a low-level interface for querying the job archive.

**Comment by chu11** [comment]
> One comment I had while experimenting with this branch is whether it would make sense to use a small python script to drive the testing instead the sqlite3 binary. Not only would this remove a new dependency (afaict, the sqlite module is part of the Python standard library), but perhaps the testing script could turn into a low-level interface for querying the job archive.

That's a pretty good idea.  Do you think it should go into this PR?  I'm thinking that could be a step before `flux-job-history` (or something like that) is created.

**Comment by grondo** [comment]
It would be nice to go in the PR so that we don't have to pull in a new dependency

**Comment by chu11** [comment]
re-pushed, wrote up a simple `t/job-archive/query.py` python script to do the querying instead of using `sqlite3`

**Comment by chu11** [comment]
re-pushed, fixing some dinky LGTMs (already squashed)

**Comment by cmoussa1** [comment]
```
"CREATE TABLE if not exists jobs("
                                "  id CHAR(16) PRIMARY KEY,"
                                "  userid INT,"
                                "  ranks TEXT,"
                                "  t_submit REAL,"
                                "  t_sched REAL,"
                                "  t_run REAL,"
                                "  t_cleanup REAL,"
                                "  t_inactive REAL,"
                                "  eventlog TEXT,"
                                "  jobspec TEXT,"
                                "  R TEXT"
 ");";
```

This table structure looks good to me. The `ranks` field will probably used to generate those monthly job usage reports, as well as play a role in fair share calculations (how many resources the user is using to run their jobs / how many resources available in the system). And since `t_run` and `t_inactive` are in there too, we can calculate an elapsed time from these fields. Thanks for putting this together @chu11 !

**Comment by garlick** [comment]
I had left an instance running with the module loaded overnight and found my debug log filled with messages like
```
2020-05-22T12:46:34.232246Z job-archive.debug[0]: retrieved 0 jobs
```
Might want to suppress those messages when the job count is zero.

**Comment by chu11** [comment]
@garlick ahhh that's mostly for development debugging, i decided to just remove it.  

rebased and repushed

**Comment by chu11** [comment]
I completely missed that you approved this yesterday, ok that i set MWP?

**Comment by garlick** [comment]
Maybe let's see if @grondo has anything to add?

**Comment by grondo** [comment]
My only comment was regarding the new `sqlite3` dependency and that has been addressed, so I approve!

**Pull request merged**
