### PR TITLE
add reactor child watchers

### PR DESCRIPTION
**Pull request by garlick**
Not ready to merge  - here for early review:

This PR adds reactor child watchers, for capturing change in status of child processes.  It's a thin  wrapper around ev_child watchers.  Since child watchers are only supported in libev's "main loop", I had to add a flag to `flux_reactor_create()` so that one can pass in FLUX_REACTOR_MAIN flag if one wants to use child watchers.   The idea is that only a "main thread" in a multi-threaded application would install signal handlers, and it would create its reactor loop with this flag.  If you try to add a child watcher to a reactor without this flag it is an EINVAL error.

Child watchers are then integrated with libsubprocess, so that each subprocess internally adds a child watcher, and the subprocess exit handlers are called via the child watcher callback when a subprocess exits.  The EINVAL error described above will propagate to subprocess creation if a reactor with the wrong flags was handed to the subprocess manager.  One can start the reactor after creating a bunch of subprocesses, and the reactor will exit once all the child watchers have been stopped.

flux-start was retooled to be entirely reactor and subprocess based and is an example of how this comes together.

Still todo:
* child watcher man page
* consider if signal watchers should also be added
* unit tests
* convert broker to use child watchers for its subprocesses (working on this)
* decide if default behavior should be for child watcher to stop itself like a one-shot timer

### CODE REVIEW

**Comment by grondo** [comment]
This looks really cool! 

I don't think you'll want to setup the ev_child watcher as oneshot by default, as (actually I don't know this, but I assume) the child watcher can handle other process states besides just exiting, like when a process is stopped, resumed, etc. and may actually be used by the `stop-child-in-exec` functionality to collect states of tasks when they reach `exec` and are stopped by `PTRACE_TRACEME`.

Probably because I'm not all that familiar with libev, but why isn't use of the libev "default loop" the default? Isn't `FLUX_REACTOR_MAIN` going to be the common case (outside of broker modules, but they have their reactor initialized for them don't they?)

In `flux-start` the default wait period jumped from 1 to 1.5s?

Should we consider adding  `EVFLAG_SIGNALFD` to ev_loop? (Sorry if that's there or is the default)

That is all my initial comments -- oh, and I'd vote for adding signal watchers. Do libevs default signal handlers/watchers and arbitrary signal_fds added as fd watchers play well together?

**Comment by garlick** [comment]
> why isn't use of the libev "default loop" the default? Isn't FLUX_REACTOR_MAIN going to be the common case (outside of broker modules, but they have their reactor initialized for them don't they?)

Since the default loop has these characteristics:
* there is only one, and `flux_reactor_create()` is only obtaining access to it, not creating a new one
* it installs its SIGCHLD handler at the begining of `ev_run()` whether or not any child watchers have started

It seems to me like the choice should be deliberate, and is only needed when managing sub-processes.  It could use a better name though, like FLUX_REACTOR_SIGCHLD?

**Comment by dongahn** [comment]
Hi @garlick: mine is just a superficial review, but some of the @grondo's comments made me curious. 

After those processes are in the `stop-child-in-exec` state, a tool like a parallel debugger will attach to these processes through ptrace (PTRACE_ATTACH...). I don't know libev well enough to make a comment whether there is any side effect when the debugging processes become the virtual parents. Also the debugging processes will stop and continue these processes as well during a tooling session. I'm just throwing this out there so that we can ensure your scheme works well when a tool session is involved as well.

What is the plan of record to harvest the return code BTW? Perhaps, capture the large exit codes from all of the child processes when they exit? Is this a good use case of reduction?

**Comment by garlick** [comment]
Thanks @dongahn.  I was intending to respond to @grondo's comment about tracking non-terminating child state changes by saying that I had disabled that by hardwiring the ev_child 'trace' flag to zero, but that I would enable it so those changes would be visible to the child watcher, which then has to interpret the wait status and decide what to do.

The next step would be to decide how to expose that in the subprocess manager.  We have `subprocess_exited()` and `_signaled()` which can be called from the subprocess_cb_f, so maybe the logical thing is to expose `_stopped()` and `_continued()` also?

I think when the new program launching service uses the subprocess manager, it would be interested in the initial transition to `subprocess_stopped()` and after that it would want to ignore those transtions while a process is being traced.  I don't know much about this mode though!  Please correct me if I'm talking nonsense.

Regarding the aggregated return code, that's an orthogonal topic to this PR.  The subprocess manager  just deals with immediate children, one at a time.

**Comment by dongahn** [comment]
Thanks @garlick. Exposing the trace mode sounds reasonable to me. 

This also remains me of  MPIR_partial_attach_ok support in http://www.mpi-forum.org/docs/mpir-specification-10-11-2010.pdf. For this, the subprocess manager would end up needing to continue those processes in `stop-child-in-exec` that are not attached by the debugger. 

In any case, in general, wearing a tool guy's hat, I can say we will have good mileage by allowing a tool to add an action as part of some status changes of the job processes. 

Cray guys has this thing called ATP, which detects abnormal termination (SEGV...) and invokes a STAT-like capability to identify only a few processes of many, which are likely the culprit of the crash. A slightly dumb-down version of this would be simply invoke an action to convert  full binary core dumps into lightweight core dumps. BGQ does this.

I think these capability may need subprocess manager to get notified of _signaled and look at the signal number and invoke some action.  

Regarding `stopped()` and `continued()`, some of the signals (like SIGTTIN) would result in a stopped process, but I'm not sure if this will be reported as signaled or stopped in libev. 

Given your comment on the aggregated return code, most of this would be orthogonal here except for the lowest primitive like _signaled (). But I thought I would mention.

**Comment by garlick** [comment]
Good background, thanks.

libev is just calling waitpid() and returning the status integer when the watcher asks for it, so we should have all the info any other program would have about stopped state, signal causing it, etc..

**Comment by grondo** [comment]
> I think when the new program launching service uses the subprocess manager, it would be interested in the initial transition to subprocess_stopped() and after that it would want to ignore those transtions while a process is being traced. I don't know much about this mode though! Please correct me if I'm talking nonsense.

I think if a process is being traced the debugger process becomes the virtual parent and the subprocess manager will no longer receive stop/continue events. I think this might even be the case for normal and abnormal termination during tracing (though I might have to try an experiment on this one) so running every job under a ptracer is probably not a good idea.

@dongahn, do you know if Cray's ATP uses ptrace to catch deadly signals, a LD_PRELOAD library like our lightweight corefile experiment, or another approach? (For instance linux has supported a pipe in `/proc/sys/kernel/core_pattern` for awhile,  which can be used to send corefile to an arbitrary program)  But sorry this is getting off-topic from this issue. I think in general this on-demand analysis could be done out-of-band from normal exit status collection of the job shell, and we'll easily be able to provide one or more mechanisms to collect this state.

**Comment by garlick** [comment]
I just forced an update with the following changes
* rebased on current master
* FLUX_REACTOR_MAIN flag renamed to FLUX_REACTOR_SIGCHLD
* If SIGCHLD reactor, use EVFLAG_SIGNALFD; if not use EVFLAG_NOSIGMASK.
* exposed `trace` parameter in child watcher creation (if true, child watcher sees stop/continue)
* implement signal watchers
* subprocess mgr sets `trace` true and distinguishes terminating and non-terminating status changes
* added subprocess_set_status_callback()` to register callback for all  process state changes, and accessors for WIFSTOPPED/WSTOPSIG; WIFCONTINUED state.  (exit callback remains an indication that process has been reaped, including io completion)

**Comment by garlick** [comment]
@grondo I think your suggestion of using EVFLAG_SIGNALFD was right on the money.  I was able to use the broker's reactor loop to manage the initial program and cmb.exec subprocesses easily after making that change (I wasted a day trying to get it to work before and never quite got there).  Thanks for that!

**Comment by dongahn** [comment]
@grondo sorry for the late response. 

It's been awhile since Cray gave me an ATP presentation. But from http://user.cscs.ch/fileadmin/user_upload/customers/CSCS_Application_Data/Files/Presentations/Courses_Ws_2011/Cray_XE6_Workshop/07_CSCS_DebuggerSupportTools.pdf, they have a library loaded in the address space of the target, which monitors *bad* signals:  SIGQUIT, SIGILL, SIGTRAP, SIGABRT, SIGFPE, SIGBUS, SIGSEGV, SIGSYS, SIGXCPU, SIGXFSZ. Then, has a out of band MRNet overlay to merge them using the STAT filter. 

Being able to do this in an out-of-band sounds good to me.  I realized I've made a wrong comment up there when I said running this in a "trace" mode. I didn't realize this meant ptrace mode, but a mode in which you get more information like stopped without having to use ptrace.

**Comment by dongahn** [comment]
@grondo this is an off-topic as well. I heard about `/proc/sys/kernel/core_pattern` before but never closely looked into this. Do you have some pointers in hand on this? Also, as this came out recently io-watchdog type of tools can be extremely useful at large scale diagnostics. Did you capture this somewhere asto how how this can be supported under Flux. Some sort of generalized framework to hook not only io-watchdog but also other out-of-band "co-located" programs seem a way to go...

**Comment by grondo** [comment]
Let's open a new issue to track ideas and questions on "fault detection and analysis" .

But fyi, I think you can lookup `core(5)` man page on Linux to get information on `core_pattern`

**Comment by grondo** [comment]
@garlick, I will poke on this a bit when I have time tomorrow.. Seems like great improvements!

**Comment by garlick** [comment]
Thanks @grondo.  I've got  this working and queued up to push:
```
/*
 *  Set up a socketpair for communication between parent and child,
 *   and return the parent side of it, or -1 on error (errno set).
 *   Optionally return the child side in 'child_fd' if non-NULL.
 *   It is the caller's responsibility to close the parent fd.
 */
int subprocess_socketpair (struct subprocess *p, int *child_fd);
```

I'll need to get some tests written also.

**Comment by garlick** [comment]
Sorry for the rebase noise here - the shell travis provides as /bin/sh doesn't seem to handle input redirection from two digit file desctiptors :-/

This has tests now, and I would consider it a merge candidate.

**Comment by grondo** [comment]
`/bin/sh` in Travis is likely the minimalist POSIX shell [`dash`](https://wiki.ubuntu.com/DashAsBinSh). This should be the same in any Ubuntu instance though.. The shell is supposed to be a pure POSIX SuSv3 shell, but I can't tell if POSIX should allow redirection to any fd number, or if the redirection is only to a "digit" file descriptor.

http://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_07

**Comment by garlick** [comment]
Just forced an update:
* added stat watchers
* subprocess uses a small array for socketpair fd's rather than select's fd_set
* squashed some commits

**Comment by grondo** [comment]
This looks great! Merge-ready?

**Comment by garlick** [comment]
Yes please.

**Pull request merged**
