### PR TITLE
[WIP] Splash

### PR DESCRIPTION
**Pull request by trws**
Apologies for the fact this is largely undifferentiated, there are things in here we probably want to keep, and things we almost certainly don't, but this represents the version of core I'm currently using for splash.

### CODE REVIEW

**Comment by grondo** [comment]
It might make it easier to track this if it is rebased onto master instead of merging master into it (though right now nothing is in the merge commit, so probably not critical)

The ntasks/ncores thing is getting confusing for me. It seems like your addition of `--cores-per-task` should definitely go into the wreck-experimental branch (I'll try to peel off what you have an add a commit with you as author). Would it really be too hard to `s/ntasks/ncores/` for the scheduler, and keep ntasks as explicitly number of tasks requested by the user? At this point I know simpler is better but I'm worried about confusing myself in the short term.

**Comment by grondo** [comment]
@trws, does your current work depend on the new `--cores-per-task` and `jobreq.ncores` parameters? If so, the ncores isn't published in the current master wreck sumbit event like tasks, nodes and walltime.

We should open an issue to add that if you need it.

**Comment by trws** [comment]
I need some way to run less tasks than I have taken cores in the system, to avoid overscheduling.  If that's the easiest way to do it, then yes.

**Comment by trws** [comment]
Specifically, I need to be able to have sched allocate me a whole node, or half a node, and run one task on that node.

**Comment by grondo** [comment]
Ok, in #1399 I've added your new option to submit and wreckrun, and added `ncores` in the message published for submit and create events.

**Comment by trws** [comment]
Thanks @grondo, with node exclusive apparently broken, this may be the only way I can get this done.

**Comment by grondo** [comment]
Ok, your patch and some jsc-hackage is in #1399, you might check it out. I'm not sure what else needs to be done to have the scheduler pay attention to ncores instead of ntasks.

**Comment by trws** [comment]
Thanks again @grondo, I'll look at that in a bit, trying to figure out what's writing out the stuff to wreck, it seems to be pulling from the wrong thing and is preventing some of that from working.

**Comment by dongahn** [comment]
> Ok, in #1399 I've added your new option to submit and wreckrun, and added ncores in the message published for submit and create events.

> Ok, your patch and some jsc-hackage is in #1399, you might check it out. I'm not sure what else needs to be done to have the scheduler pay attention to ncores instead of ntasks.

All we need would be to change the JSC key from NTASKS to NCORES. This is actually the right key because the scheduler shouldn't even care about NTASKS just NCORES. I can do a quick PR.

**Comment by garlick** [comment]
@trws is there anything left in this PR that ought to be pulled in to flux-core, or can this be closed?

**Comment by trws** [comment]
I think this is all covered now.  Thanks for the triage @garlick, closing.

**Pull request closed without merging**
