### PR TITLE
job-manager: fix compilation error on gcc-10

### LINKED ISSUE #3482: 0.23.0 fails to compile under gcc 10.1
```
$ spack install flux-core@0.23.0 %gcc@10.1.0
<snip>
/tmp/herbein1/spack-stage/spack-stage-flux-core-0.23.0-2ac2sbdm7aolnplhwir3b2rizxk2c7px/spack-src/src/modules/job-manager/jobtap.c: In function 'jobtap_load':
/tmp/herbein1/spack-stage/spack-stage-flux-core-0.23.0-2ac2sbdm7aolnplhwir3b2rizxk2c7px/spack-src/src/modules/job-manager/jobtap.c:417:9: error: 'strncpy' specified bound 128 equals destination size [-Werror=stringop-truncation]
  417 |         strncpy (errp->text, flux_plugin_strerror (p), sizeof (errp->text));
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[3]: *** [Makefile:1095: jobtap.lo] Error 1
make[3]: *** Waiting for unfinished jobs....
make[3]: Leaving directory '/tmp/herbein1/spack-stage/spack-stage-flux-core-0.23.0-2ac2sbdm7aolnplhwir3b2rizxk2c7px/spack-src/spack-build/src/modules/job-manager'
make[2]: *** [Makefile:497: all-recursive] Error 1
make[2]: Leaving directory '/tmp/herbein1/spack-stage/spack-stage-flux-core-0.23.0-2ac2sbdm7aolnplhwir3b2rizxk2c7px/spack-src/spack-build/src/modules'
make[1]: *** [Makefile:507: all-recursive] Error 1
make[1]: Leaving directory '/tmp/herbein1/spack-stage/spack-stage-flux-core-0.23.0-2ac2sbdm7aolnplhwir3b2rizxk2c7px/spack-src/spack-build/src'
make: *** [Makefile:580: all-recursive] Error 1
```

### PR DESCRIPTION
**Pull request by grondo**
Fixes #3482

### CODE REVIEW

**Comment by grondo** [comment]
I forgot about #3378, which prevents `make check` from working on a GitHub actions runner in Fedora 33:
```
lt-flux-broker: could not bind to tcp://fe80::20d:3aff:fe7a:44b2%eth0:*: Invalid argument
lt-flux-broker: overlay_bind failed: Invalid argument
lt-flux-broker: bootstrap failed
```

May have to back out the fedora 33 addition and only fix #3482 here.

**Comment by grondo** [comment]
Ok, I've backed out the addition of FC33 checks for now. I'll see if I can get that working another time.

This is just the fix for #3482 now.

**Review by garlick — APPROVED** [review]
Looks good.

**Comment by grondo** [comment]
Thanks!

**Pull request merged**
