### PR TITLE
Make optparse_parse_args() reentrant

### PR DESCRIPTION
**Pull request by grondo**
This is an *experimental* PR at this point -- open for discussion.

I wanted to make `optparse_parse_args` reentrant so it could be used in flux modules' `main` functions, if desired, though there is no immediate use case for this.

I looked for a reentrant version of `getopt_long`, and found that the internal glibc function that implements `getopt`, `getopt_long` and `getopt_long_only` is actually reentrant, but is not exposed in the public interface.

As an experiment I copied glibc `getopt.c`, `getopt.h` and `getopt_int.h` into `src/common/liboptparse` and with a slight modification was able to use the glibc `_getopt_internal_r` directly.

The main other requirement here is that glibc `getopt` sources use gettext for internationalization. Though it would be simple to remove that requirement or work around it, I figured that eventually we'd want gettext support in flux-core at least, so I wired that in to the build system, which turned out to be a bit more trouble than expected, but once it is done it doesn't seem to be a huge burden.

### CODE REVIEW

**Comment by grondo** [comment]
Hm, I wonder if the GNU getopt sources and headers should be added to the ignore patterns for coverage checks.

**Comment by garlick** [comment]
Nice!  I think it's definitely a useful addition to make liboptparse reentrant.

I think I need to do a little reading about internationalization to understand what the next steps would be after this boiler plate stuff.

**Comment by garlick** [comment]
Ah - this is useful

[GNU Coding Standards section 5.8 Internationalization](https://www.gnu.org/prep/standards/html_node/Internationalization.html)

**Comment by grondo** [comment]
Another option would be to dump the nls support for now and either remove the requirement for `#include "gettext.h"` in GNU `getopt.c` or change `src/include/gettext.h` to define `_(x)` to `x` or something (with a big comment that this is a placeholder)

**Comment by grondo** [comment]
> Ah - this is useful 

I was also working off the [gettext manual maintainer section](https://www.gnu.org/software/gettext/manual/html_node/Maintainers.html#Maintainers)

**Comment by garlick** [comment]
Should `gettextize` be run from autogen.sh instead of checking in its products?  (I really don't know what's right here but 9af4891 is a sizeable commit and we've avoided checking in other automake/libtool products.

**Comment by grondo** [comment]
> Should gettextize be run from autogen.sh instead of checking in its products?

gettextize modified configure.ac and added the `./po` directory with templates, so I don't think that is the right thing, though I might be wrong. I don't think it is like `libtoolize` which copies in m4 macros and such, that is something called `autopoint` which is run automatically by `autoreconf` and adds a *lot* more stuff:

```
autoreconf: running: autopoint
Copying file config/codeset.m4
Copying file config/gettext.m4
Copying file config/glibc2.m4
Copying file config/glibc21.m4
Copying file config/iconv.m4
Copying file config/intdiv0.m4
Copying file config/intl.m4
Copying file config/intldir.m4
Copying file config/intlmacosx.m4
Copying file config/intmax.m4
Copying file config/inttypes-pri.m4
Copying file config/inttypes_h.m4
Copying file config/lcmessage.m4
Copying file config/lib-ld.m4
Copying file config/lib-link.m4
Copying file config/lib-prefix.m4
Copying file config/lock.m4
Copying file config/longlong.m4
Copying file config/nls.m4
Copying file config/po.m4
Copying file config/printf-posix.m4
Copying file config/progtest.m4
Copying file config/size_max.m4
Copying file config/stdint_h.m4
Copying file config/uintmax_t.m4
Copying file config/visibility.m4
Copying file config/wchar_t.m4
Copying file config/wint_t.m4
Copying file config/xsize.m4
```

Let me see if I'm wrong though....

**Comment by grondo** [comment]
I'm still confused, but from the [gettext manual](https://www.gnu.org/software/gettext/manual/gettext.html#gettextize-Invocation)

 > It is also important to understand that gettextize is not part of the GNU build system, in the sense that it should not be invoked automatically, and not be invoked by someone who doesn’t assume the responsibilities of a package maintainer. For the latter purpose, a separate tool is provided, see [autopoint invocation](https://www.gnu.org/software/gettext/manual/gettext.html#autopoint-Invocation).

**Comment by garlick** [comment]
OK, that sounds right then.

**Comment by garlick** [comment]
I'm good with this going in as is if you are @grondo.

**Comment by grondo** [comment]
I'm kind of waffling -- I'm not sure if the NLS support is worth it at this point. Should I make an alternate PR that adapts GNU getopt.c without gettext()?

**Comment by garlick** [comment]
Well that might be good from a release notes point of view I guess.  And maybe the NLS PR could also define a gettext macro and convert some messages just to establish the patterns that should be used in new code.

**Comment by grondo** [comment]
Closing. We decided to merge the version that didn't add NLS support

**Pull request closed without merging**
