### PR TITLE
Convert code to use new KVS functions and not KVS classic

### PR DESCRIPTION
**Pull request by chu11**
As discussed at the meeting, I'm not entirely convinced that this effort has more pros than cons.  Maybe it should mostly be dropped.

What were the issues in this effort.

- ```kvs_classic``` was used in more places than I think we originally assumed.  I think I originally assumed it was almost only in lua & python bindings, but there were good chunks in ```libkz```, ```wrexecd```, and ```flux-kvs```.

- There are code chunks in the lua bindings & libkz & wreck that assume they can work on the same KVS transaction as each other, but don't pass the ```kvs txn``` between each other.  Without changing any  APIs, and not sharing any code (i.e. creating new helper functions), code duplication is a result.

- The kvs classic APIs often returned allocated buffers that the user was required to free'd.  The newer kvs functions often return a value that is not required to be free'd, b/c the memory is still within a flux future.  Without rearchitecting code / APIs, it leads to more code being written than desired.  This is compounded by the fact that KVS watch API uses an in & out variables for its interface.

- There is a fair amount of cut & paste.  At some point, it's basically the code that was in ```kvs_classic.[ch]```, but now in multiple files.  I elected to do this intentionally, b/c I did not want to create any new "common" functions.

So why did I even bother to submit this given all the crap above?  Partially, it's b/c I already invested the time to bother with this ... but here are the minor pros:

- I don't want continued pollution of use of the ```kvs_classic``` interface.  Minimally @SteVWonder is going to be working on new KVS  python bindings, it's just time to move on.

- This removes a mountain of the deprecated warnings to show up in the compile logs and on travis output.

- We are moving forward in things, and getting rid of the old interfaces is a good step forward.

- I really wanted to get rid of ```kvs_classic```

Note that these are not great "pros" to accepting this PR, it's just what I could come up with :-)

Maybe it just means we keep a few of the changes and not all of them.  I think an alternate to merging this monstrosity is to merge just the python changes + some of the stupid fixes I found along the way.

Also, one other note, I did not remove ```kvs_classic``` in this PR, b/c I suddenly found out it was used in a couple of tests (did not show up when I compiled and checked for "deprecated").  I'll fix that up later, but wanted to post this for initial reaction.  

One note on the Python change.

A few functions in the past may have been flexible enough to take a python ```Flux()``` or the internal ```flux_t``` representation, but now it must take a ```Flux()``` object type b/c of the ```__aux_txn```
I added to ```Flux()```.  AFAICT, all usage out there properly passes in ```Flux()``` except for 1 internal location I changed.

### CODE REVIEW

**Comment by garlick** [comment]
> Maybe it just means we keep a few of the changes and not all of them. I think an alternate to merging this monstrosity is to merge just the python changes + some of the stupid fixes I found along the way.

I think that's the way I'm leaning right now, but let's ponder a bit more and see what other people think.

It's hard to get enthusiastic about the churn in kz and wreck, when those are going away.  :-/

**Comment by SteVwonder** [comment]
Thanks @chu11!  The python changes LGTM.

**Comment by chu11** [comment]
> I think that's the way I'm leaning right now, but let's ponder a bit more and see what other people think.

Sounds good to me.  I'll minimally also update any tests that use KVS classic, b/c that's something that will have to change later on for sure.

**Comment by chu11** [comment]
gonna just drop this PR in favor of a new PR

**Pull request closed without merging**
