### PR TITLE
kvs: prototype removal of ns prefix support & new treeobject type "nslink"

### PR DESCRIPTION
**Pull request by chu11**
This is an experimental PR to remove "ns:" prefix support in the KVS and instead use a new tree object which I call "nslink" (name can be debated).

As discussed in #1860, the addition of the kvs-watch module made the "ns:" prefix support from the past cumbersome.  As time has gone on since the original "ns:" prefix support, many exceptions and special handling had to be done.  So this was a look and see how hard it would be to move on from it.

The primary need for the "ns:" prefix was to allow lookups to "cross" namespaces, primarily via symlink.  So this PR adds a new treeobj as follows:

```
{ "ver":1,
   "type":"nslink",
   "data":{"namespace":"a", "target":"aa"},
}
```

I would have to submit an update to the KVS RFC of course, but wanted to do that after getting some initial feedback.

There's a lot of commits, as I stepped through this slowly and had multiple prototype rounds.  I may squash some commits together in a final PR later.

I will say that I like the idea of removing this support.  I had forgotten about many of the special case handling done for "ns:" prefix support.  There are a lot of oddball cases lingering the code.  I think this is a good idea in general.

Notes of interest / things to think about.

- flux_kvs_copy / flux_kvs_move - removal of "ns:" prefix support meant these functions could no longer copy / move between different namespaces, so a src & dst namespace parameter had to be added (and appropriate options in flux-kvs).

  Should the namespace parameters be placed differently in the function?  It felt better for the arguments to be after the key, but in some ways the namespace parameter should be before it?

- Generally speaking, in this PR I treat both "symlinks" and "nslinks" as both "links".  The fallout of this is:

  FLUX_KVS_READLINK - I use this flag to read either a symlink or nslink.  ok?

  flux-kvs - the link command creates a symlink by default, or a nslink if the user specifies ```--link-namespace```.  This abstracts away the fact there are two different link treeobject types below. Should be ok?

  flux-kvs - the readlink command outputs "<namespace>::<key>" for nslinks unless the user asks otherwise.  I picked this format somewhat arbitrarily, there could be other ways to do this (a new "read-nslink flux-kvs command?)

  flux-kvs - the 'ls' command marks nslinks with "@" just like a symlink.  ok?

- Consideration - after completing this prototype PR, and given my comments about how I use "READLINK" for both symlinks and nslinks, I began thinking, perhaps we should change the symlink tree object to look ilke the "nslink" one and not support a new tree object type?

  We instead make a namespace in a symlink optional.  If a namespace is not listed in the symlink, you stay in the current namespace it's just like symlinks now.  If there's a namespace, go through "nslink" like procedures.

  We'd have to change some APIs (i.e. treeobj_create_symlink() would take a namespace) and such.  Such a change would break "treeobj" ABI.  Lots of little fixes would have to be done along the way, but
  it's worth considering.  In some cases, it would be cleaner than the code I currently have.  I'm not sure how it would fall out in other parts of the code.

### CODE REVIEW

**Comment by garlick** [comment]
Wow, lot of work here.

Couple quick comments: any reason not to export the `_ns()` functions in the main API?  (Why in a private header, or if private, why the flux_ prefix which gets them exported in the installed shared library?)

Would it make sense to split this PR into multiple PR's, e.g.
* kvs: cleanup/renaming in preparation for nslink
* kvs: add explicit namespace parameters to API
* kvs: add nslink support
* kvs: drop ns: key prefix support and tests

The coverage results for each might then be a little easier to reason about.

**Comment by chu11** [comment]
> Couple quick comments: any reason not to export the _ns() functions in the main API? (Why in a private header, or if private, why the flux_ prefix which gets them exported in the installed shared library?)

In this PR I wasn't going to export them.  I was going to investigate that more with issue #1435 and possibly add a "namespace" parameter to most API functions.   But you're correct, I shouldn't have added the "flux_" prefix if they're going to be private for the time being.

> Would it make sense to split this PR into multiple PR's

Yes!  That's my intention after this round of feedback.

**Comment by garlick** [comment]
It's a bit hard to tell on the surface, but did this have the desired effect of simplifying the code?

**Comment by chu11** [comment]
Good question.  It's not as big a win as I think we originally thought it would be.  Effectively we traded "ns prefix" for another treeobj type.  The latter introduces some additional complexities b/c it's effectively a second "link type", so there's some "handle both symlink & nslink" cases as I list above.

What might be interesting is if we did the suggestion I have above about changing the symlink treeobj type to have an optional namespace.  That might remove some of the additional complexity of having a second "link type".

However, I think the code that's here is still a positive win.  Effectively, the "ns prefix" made every single key both a key and a possible "symlink".  And that introduced more complexity than was desired.  I think the code is logically a lot simpler b/c symlinks contains targets, nslinks contain namespaces & targets, and keys are keys.

**Comment by garlick** [comment]
> Should the namespace parameters be placed differently in the function? It felt better for the arguments to be after the key, but in some ways the namespace parameter should be before it?

I would have thought (ns, key, ns, key), but maybe I'm just holding on to the "prefix" concept :-)

> FLUX_KVS_READLINK - I use this flag to read either a symlink or nslink. ok?

If I use the idiom: lookup (key, READLINK), lookup_get_symlink, I'll get an error right?  

Would it be better to just letting the user wanting to lookup an nslink use: lookup (key, TREEOBJ), lookup_get_treeobj?

> flux-kvs - the 'ls' command marks nslinks with "@" just like a symlink. ok?

It seems more like a mount point than a symlink.  Leave it unmarked in ls output?

> I began thinking, perhaps we should change the symlink tree object to look ilke the "nslink" one and not support a new tree object type?

Well, it is a different thing though.   I kind of think we shouldn't get the two bound up together...

**Comment by chu11** [comment]
> I would have thought (ns, key, ns, key), but maybe I'm just holding on to the "prefix" concept :-)

Yeah, after i programmed it I thought maybe the ns should be before the key.  I'll fix that.

> If I use the idiom: lookup (key, READLINK), lookup_get_symlink, I'll get an error right?

Yes, and lookup_nslink() would fail on a symlink.

> Would it be better to just letting the user wanting to lookup an nslink use: lookup (key, TREEOBJ), lookup_get_treeobj?

Oh, you mean the code in ```readlink``` should be something more like:

```
lookup (key, TREEOBJ)
lookup_get_treeobj ();
if (treeobj_is_symlink ())
   //
else if (treeobj_is_nslink ())
  //
```

That makes sense and would probably simplify the code I have there already.

> It seems more like a mount point than a symlink. Leave it unmarked in ls output?

Then it would just look like a key.  Perhaps we need a new categorization marker?  Obviously don't want to use something normally used by ```ls --classify```.  Hmmm, hash tag, dollar sign, or exclamation?

**Comment by garlick** [comment]
> Oh, you mean the code in readlink should be something more like:

Well, no I was suggesting that readlink would return an error if the key isn't a symbolic link.  Maybe people would use flux kvs get --treeobj to get the nslink?

Possibly I'm again trying to make more of the resemblance to a "mount point" than is appropriate...

**Comment by garlick** [comment]
Thinking about this a bit more:

In the API, I think we should probably add new functions, e.g. add a READNSLINK flag, `_lookup_get_nslink()`, `_txn_put_nslink()`, and `kvsdir_isnslink()`.  Similarly, maybe new corresponding subsub (dubsub?) commands in `flux kvs`?

I suppose the treeobj design is not really visible, though I would lean towards adding a new `nslink` over an optional namespace in the `symlink` one, just to keep the concepts orthogonal even if the implementation on the back side shares significant code for both object types.

A marker in `flux kvs ls --classify` does make sense IMHO.  Maybe `+`?

My thoughts are a bit fragmented on this (sorry).  Maybe some face to face discussion next week would be beneficial?

**Comment by chu11** [comment]
> In the API, I think we should probably add new functions, e.g. add a READNSLINK flag, _lookup_get_nslink(), _txn_put_nslink(), and kvsdir_isnslink(). Similarly, maybe new corresponding subsub (dubsub?) commands in flux kvs?

The latter three are effectively already there, but to eliminate the ambiguity, I agree making a READNSLINK, ```flux kvs readnslink``` and ```flux kvs nslink``` will be better than what's there right now.  It's basically that or symlink w/ namespace.

> Similarly, maybe new corresponding subsub (dubsub?) commands in flux kvs?

I'm not quite following.

> A marker in flux kvs ls --classify does make sense IMHO. Maybe +?

I figure if it's not taken by ```ls --classify```, then any character should be fine.  Seems + is free as well.

**Comment by garlick** [comment]
> I'm not quite following.

Sorry, I meant implement sub-sub commands for nslink that parallel those for symlinks, instead of options for symlink and readlink, e.g.
```
flux kvs nslink
flux kvs readnslink
```

**Comment by chu11** [comment]
oh, do you mean possibly doing:

```flux kvs link read```
```flux kvs link create```

and nslink equivalents?

**Comment by garlick** [comment]
Not what I was suggesting, but I'm open to it...

**Comment by chu11** [comment]
spoke to @garlick and we're going to give the "symlink contains an optional namespace & a target" a development run to see how it turns on.  So I'll close this experimental PR.

**Pull request closed without merging**
