### PR TITLE
libczmqcontainers: introduce new internal library of czmq `zhashx` library

### PR DESCRIPTION
**Pull request by chu11**
Per discussion in #3591, bring in a new internal copy of `zhashx` into flux-core to deal with CZMQ issue https://github.com/zeromq/czmq/issues/2173.

- to avoid symbol collisions, renamed `zhashx` to `fzhashx` in the local copy
- to avoid search and replace everywhere, add `zhashx_int.h` which does pre-processor macros to change `zhashx` to `fzhashx` everywhere.

@garlick mentioned we may want to do tweaks later as well, to perhaps not assert on malloc errors, etc.  But I will leave those fixes for another day.  Perhaps we will want to create an issue to remember.

### CODE REVIEW

**Comment by garlick** [comment]
Thanks for this and for the upstream work!

One problem with renaming everything in the copied czmq source is that it's hard to diff later.  Could we instead leave the source mostly pristine and just include the header with the rename defines?

It might also be clearer to someone down the line if we left the source file names as they were, which I don't think will affect anything.

Finally, would it be possible to avoid all the include additions to our source by using something like [AH_BOTTOM](https://www.gnu.org/software/autoconf/manual/autoconf-2.61/html_node/Autoheader-Macros.html#Autoheader-Macros) to add our local include to config.h and then have the ability to turn it off in one place later?

**Comment by garlick** [comment]
>  using something like AH_BOTTOM to add our local include to config.h

Er, I'm not sure how great of an idea that would be since it kind of hides everything.  It might be better to just change the name of the new include to something more generic that could include multiple container classes, like `src/common/libczmqcontainers/containers.h`?  Then if we decided to drop one and go back to using the installed czmq version, we could just drop it in there.

**Comment by grondo** [comment]
> One problem with renaming everything in the copied czmq source is that it's hard to diff later. Could we instead leave the source mostly pristine and just include the header with the rename defines?

This is what I had been thinking when I suggested using preprocessor to redefine symbol names.

At first I was thinking of modifying just the czmq header files to include the preprocessor defines. You could presumably add `-I src/common/libczmqcontainers` to our includes path to force our local copy to be included first. (Now that I see @garlick's suggestion of a `containers.h`, I like that approach better though)

**Comment by garlick** [comment]
Another thought would be to add stuff we need to detach the classes from czmq to a separate include like `standalone.h` (for example the `freen()` macro).  There might be more of those over time for different classes.

Then instead of defining stuff directly in zhashx.c, it could just include standalone.h (bonus: reducing the size of the diff).

**Comment by chu11** [comment]
@garlick and @grondo, some good ideas!  I like the idea of the `standalone.h` to move the misc things I need to add to keep the diff small (like `freen()`).  Then `containers.h`can have all of our symbol renamings and be included by all internal callers.

**Comment by chu11** [comment]
re-pushed.  Now we have these files:

```
src/common/libczmqcontainers/czmq_containers.h
src/common/libczmqcontainers/czmq_internal.h
src/common/libczmqcontainers/fzhashx.c
src/common/libczmqcontainers/fzhashx.h
src/common/libczmqcontainers/zhashx_map.h
```

with callers to load `czmq_containers.h`.

The diff is pretty tiny now with it mostly being my comments on what the file is.

```>diff src/common/libczmqcontainers/fzhashx.h ~achu/code/czmq/include/zhashx.h 
14,26c14,15
< /* This is a copy of the czmq zhashx library.
<  *
<  * Due to czmq issue #2173
<  * (https://github.com/zeromq/czmq/issues/2173) performance in
<  * flux-core was extremely poor at times and flux-core could not
<  * wait for the OS distros to pick up the bug fix.
<  *
<  * This file is a verbatim copy with only minor adjustments to header
<  * guards and included headers.
<  */
< 
< #ifndef __FZHASHX_H_INCLUDED__
< #define __FZHASHX_H_INCLUDED__
---
> #ifndef __ZHASHX_H_INCLUDED__
> #define __ZHASHX_H_INCLUDED__
32,34d20
< #include <czmq.h>
< #include "czmq_internal.h"
< #include "zhashx_map.h"
286a273
> 

```


```
>diff src/common/libczmqcontainers/fzhashx.c ~achu/code/czmq/src/zhashx.c 
14,24d13
< /* This is a copy of the czmq zhashx library.
<  *
<  * Due to czmq issue #2173
<  * (https://github.com/zeromq/czmq/issues/2173) performance in
<  * flux-core was extremely poor at times and flux-core could not
<  * wait for the OS distros to pick up the bug fix.
<  *
<  * This file is a verbatim copy with only minor adjustments to
<  * included headers.
<  */
< 
38c27
< #include "fzhashx.h"
---
> #include "czmq_classes.h"
48c37
< #include "fzhash_primes.inc"
---
> #include "zhash_primes.inc"

```

**Comment by chu11** [comment]
As an side, the LGTM failure is b/c there is a "FIXME" in the zhashx implementation.  So it was copied in.  Won't be fixing that one so the code/comments will stay the same.

**Comment by garlick** [comment]
Nice!

Any reason not to just leave the source files `zhashx.c`, `zhashx.h`, `zhash_primes.h`?

The multi-include protection in `zhashx.h` would still need to be different of course.

Our commit that adds the copy of the czmq source should probably reference the foreign commit and a czmq release so we can quickly check if we're behind.  Might also be good to include a note on the czmq license and a reference to the MPL in (L)GPL discussion you referenced earlier.

**Comment by chu11** [comment]
re-pushed with tweaks per @garlick comment above

**Review by garlick — APPROVED** [review]
This looks good to me!  Thanks!

**Pull request merged**
