### PR TITLE
Issue 433: Update sharness version to upstream 1.0.0 version

### PR DESCRIPTION
**Pull request by chu11**

### CODE REVIEW

**Comment by chu11** [comment]
hmmm

```
ERROR: t0000-sharness.t - missing test plan
ERROR: t0000-sharness.t - exited with status 2
```

Error is from tap.  Guess I'm not quite setting something up correctly, or missing some earlier modification.

**Comment by grondo** [comment]
The script is exiting with exit code 2 before generating any or correct TAP
output.

**Comment by chu11** [comment]
Looks like I just missed this one for ```t0000-sharness.t```, looks all good now:

```diff
< . ./sharness.sh
---
> . `dirname $0`/sharness.sh
```

**Comment by grondo** [comment]
One change is that `trash-directory*` is now `trash directory*` (I.e. Whitespace in directory name). Might want to grep through code, scripts and makefiles auditing for globs or other uses that might break with whitespace. (or just cave and put the dash back in)

**Comment by chu11** [comment]
@grondo I think I got the trash dir one in https://github.com/flux-framework/flux-core/pull/1035/commits/226f0777edd12cf591b623d9d0e3f4358d769eb4 Are you seeing it in something that I'm not?

**Comment by grondo** [comment]
Ah, sorry. Thought I was looking at the whole diff, but probably only
viewed the first commit. Sorry about that!

**Comment by grondo** [comment]
I hate to suggest it but it would be nice if the forward ported patch stack stayed in separate commits if it is not too much trouble. I guess the squashed commit here at least references the original commits, but it would be easier to submit patches upstream and better for history (IMO) if the changes were kept separate.(reason for changes in the commit body is then kept along with each separate change)

It is a minor thing, so if it is bothersome or difficult let's skip it this time.

On the other hand it would be nice if we weren't modifying upstream sharness at all, so maybe we should try dropping the patches that would never be accepted (passing tests in green, no whitespace in trash directory) and look at submitting the other patches?

**Comment by chu11** [comment]
@grondo No worries, now that you mention it I should have done the separate commits from the start.

I did bring up an issue with the SHELL_PATH issue (https://github.com/flux-framework/flux-core/pull/1035/commits/671275c51fec6791db05aace0f9ceaa9c6d8efac).  Obviously, we could just axe a few of the patches as you said.  They are just niceties.  But I'll admit, I like them (pass is green, no space in trash dir name).  I noticed many patches from you upstream, but unsure which patches you made attempts to push upstream and which ones you didn't?

**Comment by grondo** [comment]
It was very time consuming to push patches upstream, and I didn't submit patches that changed upstream git `test-lib.sh` behavior (passing tests green, and trash-dir naming are two examples of these). I don't remember why I didn't push some of the other "fixes".

Down the road it might make sense to re-evaluate if we should use git's test-lib.sh instead of sharness and adapt it directly. The git authors took a look at sharness and decided against rebasing git's testsuite on it because sharness was missing a lot of newer functionality of the git testsuite. 

If we brought sharness up-to-date with git's more recent test-lib.sh that would be a huge service to the community (but also a huge undertaking, so I'm not sure if it is worth it)

**Pull request merged**
