### PR TITLE
small build/test/doc fixes

### PR DESCRIPTION
**Pull request by grondo**
This is a small set of minor fixes for issues found during the recent release.

### CODE REVIEW

**Comment by grondo** [comment]
Great, thanks. Forced a push with a fix for the typo you found.

**Comment by garlick** [comment]
If you're happy and you know it, MWP!

**Comment by grondo** [comment]
Found a problem after removal of manpages from the dist `make distcheck` is broken because `index.rst` is missing from `EXTRA_DIST`.

I'll push a commit to fix it here.

Unfortunately this means if someone runs `make clean` after unpacking `flux-core-0.18.0.tar.gz` they'll be stuck. Ah well.

**Comment by grondo** [comment]
Ok, there were a couple issues in `doc/Makefile.am`. Turns out some source `.rst` files were also being dropped from the dist tarball. :frowning_face: 

Should be fixed now.

**Comment by grondo** [comment]
Pushed a fix for another `make dist` issue (`man3/flux_kvs_txn_put_treeobj.3` was missing from MAN3_SECONDARY_FILES, so `make distclean` failing)

**Pull request merged**
