### PR TITLE
some minor change related to MPI support + fixes

### PR DESCRIPTION
**Pull request by garlick**
In this PR
* pmi tracing is improved, and redirected to the flux_log at LOG_DEBUG level
* a logic error in broker logging is fixed, and logging attribute docs updated
* set I_MPI_PMI_LIBRARY in environment for Intel MPI support

It seems a little wrong to always set the environment variable specific to the Intel MPI runtime, so wanted to get some feedback on that.  (Maybe it is OK for the short term, but what is the correct long term way to do this?)

### CODE REVIEW

**Comment by grondo** [comment]
> It seems a little wrong to always set the environment variable specific to the Intel MPI runtime, so wanted to get some feedback on that. (Maybe it is OK for the short term, but what is the correct long term way to do this?)

I've never been sure about this,  but site customization has always appealed to me.

For example, something like a cross between environment-modules and slurm spank plugins could be used to say up a site default task environment with per user and command line overrides. 

See the use-env spank plugin for a very rough example of what I am thinking about. 

https://github.com/grondo/slurm-spank-plugins/blob/master/README.use-env
For slurm I had a --use-env plugin that set a

**Comment by grondo** [comment]
Ugh, sorry about typos above. Working on my phone at the orthodontist, and apparently can't edit comments from the mobile ui

**Comment by garlick** [comment]
I squashed a couple of commits down.  This might be good to merge soon as it contains some critical bug fixes to the `live` module that cause moderate size sessions to fail right after launch.

**Comment by grondo** [comment]
My only question is why the `I_MPI_PMI_LIBRARY` path is set directly in the broker instead of just in the environment of parallel jobs? It works for now so I'm not complaining...

**Comment by garlick** [comment]
It's set in the environment of the initial program, not the broker.

I'm certainly open to other approaches - that just seemed like the quickest way to get it set.  Suggestions?

**Comment by grondo** [comment]
Sorry, yeah I meant set in the broker *for* the initial program. I guess it
could be set in wrexecd like the other MPI variables, but at this point it
will work fine so I don't really have an objection. Just wondering if there
was another reason besides ease of implementation.

**Comment by garlick** [comment]
Ah good point.  I had forgotten the other MPI variables were set there. 

I don't feel strongly either way.  It probably belongs in a site environment config like you suggested so let's consider this a short term thing.

**Comment by grondo** [comment]
Yeah, lets just fix it later.

**Pull request merged**
