### PR TITLE
add broker runlevels

### PR DESCRIPTION
**Pull request by garlick**
Here's an initial attempt at wiring run levels into the rank 0 broker as proposed in #518

This establishes the basic skeleton:  rc1 script runs during level 1, initial program runs during level2, rc3 script runs during level3.

Some in-tree scripts are provided.  Next I'll try moving module loading to rc1.

### CODE REVIEW

**Comment by garlick** [comment]
Just pushed an update with _most_ module loading in rc1 and some miscellaneous improvements to logging and the install target.

Temporary exceptions: `kvs` could not be loaded outside the broker because of the config loading which will be addressed in #596, and also the "getroot" during initialization which will need a barrier.  `live` also needs a barrier during initialization.

Permanent exception: `connector-local` needs to be loaded statically so that `flux module load` can work in the rc script.

**Comment by garlick** [comment]
Note that startup is a little slower with this scheme.  That is because modules are loaded serially, and each load waits until the module completes initialization and enters the reactor loop.

However, a positive consequence of this is that the initial program is not loaded until all the modules have completed initialization.  So for example, this should address #585 (resource-hwloc synchronization).

**Comment by grondo** [comment]
For modules that can be loaded in parallel you could try sending the `flux module load` to the background and then at the end of the script use `wait`.

**Comment by grondo** [comment]
This is really cool and way more powerful than what we have now. Do you think that to integrate with multiple framework projects we'll have to end up with `rcX.d` directories? I'm trying to picture how this works when you install `flux-sched` (i.e. would a flux-sched `rc` script *replace* or be run *after* a flux-core rc script -- now, what about a third framework project..)

**Comment by garlick** [comment]
Yeah, I do like this too!

Maybe `runit` glue can be leveraged as discussed in #518 or we could just wire up a very simple systemVinit like strategy.  sched would install an rc script, and it would get linked into rc1.d and rc3.d directories which would be walked by core's rc1 and rc3 scripts.

Or we could just jump straight to `flux-systemd` :-)

**Comment by garlick** [comment]
Hmm, gcc+install failed with only
```
flux-start: 1 (pid 42394) Killed
FAIL: t1005-cmddriver.t
```
I restarted that build.

**Comment by garlick** [comment]
A TODO is to redirect stdout/stderr of rc1 and rc3 to `flux_log()`, otherwise any output may be co-mingled with the initial program output.

**Comment by grondo** [comment]
> Maybe runit glue can be leveraged as discussed in #518 or we could just wire up a very simple systemVinit like strategy.

Neither of those feel like they map great to flux instance intialization because they're designed to start services and monitor them (similar idea to systemd I guess). However, I'm probably just not wrapping my brain around the problem.

Actually, this discussion probaly should go into #518 as it isn't really relevant to this PR, which is a more than incremental improvement to what we have now and should go in asap IMO.

**Comment by garlick** [comment]
Just forced a push with some cleanup and logging of rc1 and rc3 output.

**Comment by garlick** [comment]
OK, rebased on current master and now `kvs` and `live` modules are loaded via rc scripts.  There is only one hardwired module loaded by the broker:  `connector-local`, which is needed in order for rc scripts to connect to broker and load the other modules.

The runlevel class now sets `FLUX_RUNLEVEL` and `FLUX_RUNLEVEL_NODESET` in the subprocess environment of rc1 and rc3.  The idea here is that in the future, grow and shrink will need to run rc1 and rc3 respectively to initialize and finalize subsets of nodes, and so those scripts should be equipped to deal with any nodeset.

A simple utility `flux-nodeset` was added for manipulating nodesets (union, intersection, subtraction, etc), and the rc scripts use this.  In the process a nodeset bug was discovered and fixed.

I also dropped the now unused `--modopt` and `--modexclude` broker options.

**Comment by garlick** [comment]
Oops I might have blown it in the shutdown patch above.  Let me investigate.

**Comment by grondo** [comment]
This is cool, I'll try to poke the tires a bit tonight.

**Comment by garlick** [comment]
Just got a travis-ci clang failure - might need to run this down or at least improve error messages.  Nothing in the broker log:
```
expecting success: 
	ATTR_VAL=`flux start -o,--setattr=foo-test=42 flux getattr foo-test` &&
	test $ATTR_VAL -eq 42
[1457535305.956152] broker.err[0]: rc1: flux-module: flux_open: No such file or directory
[1457535305.956218] broker.err[0]: Run level 1 Exited with non-zero status (rc=1)
[1457535306.005864] broker.err[0]: rc3: flux-module: cmb.rmmod[0]: No such file or directory
[1457535306.032718] broker.err[0]: rc3: flux-module: cmb.rmmod[0]: No such file or directory
[1457535306.059413] broker.err[0]: rc3: flux-module: cmb.rmmod[0]: No such file or directory
[1457535306.086172] broker.err[0]: rc3: flux-module: cmb.rmmod[0]: No such file or directory
[1457535306.112796] broker.err[0]: rc3: flux-module: cmb.rmmod[0]: No such file or directory
[1457535306.140017] broker.err[0]: rc3: flux-module: cmb.rmmod[0]: No such file or directory
[1457535306.167411] broker.err[0]: rc3: flux-module: cmb.rmmod[0]: No such file or directory
[1457535306.195247] broker.err[0]: rc3: flux-module: cmb.rmmod[0]: No such file or directory
flux-start: 0 (pid 40655) exited with rc=1
not ok 10 - flux-start -o,--setattr ATTR=VAL can set broker attributes
```

**Comment by garlick** [comment]
Some todos for this PR:
* Add hooks so flux-sched and others can append to rc1 and rc3 (strategy TBD, see issue #508)
* Consider running with stripped down rc1/rc3 in sharness, especially the early tests
* Drop FLUX_RUNLEVEL as this was a gratuitous addition with no use case
* Add tests for stdout/stderr handling in rc1/rc3, expected runlevel transiton on errors in rc1/rc2/rc3, expected environment variables set in rc1/rc3
* Rename FLUX_RUNLEVEL_NODESET to something better (FLUX_RC_NODESET or argument to rc scripts?)

**Comment by grondo** [comment]
Ok, I'm going to ask a dumb question here. Looking at (I think) the current runlevel scripts I found them a bit confusing at first. For instance, what is this doing?:
```
rank0=$(flux nodeset -i 0 $rank_all)
rank_other=$(flux nodeset -s 0 $rank_all)
```
Hm, when I look at it further I do understand it, but it seemed strange at first glance. 
Also, why are some module loads split into "load rank0" then "load rank_other" while other modules are not?

I wonder if the script would look a bit more sane if `flux-module` and other commands that take a `--rank` took a `FLUX_NODESET_MASK` environment variable or `--mask` option so you could just do what feels like it makes sense like:
```
FLUX_NODESET_MASK=${FLUX_RC_NODESET} # Or this is implied
flux module load --rank=0 content-sqlite
flux module load --rank=all kvs
```

I am probably grossly overlooking something obvious though...

**Comment by garlick** [comment]
Yeah I'm sure we can find ways to improve readability/usability there.  The challenge is that some modules need to be loaded first on rank 0, then on the other ranks; and to support future grow/shrink, we can't assume that rank 0 is being targeted, hence the `flux nodeset` command, those variables, and the test for "empty" before using them.

I would actually like to fix the case of loading rank 0 first, then other ranks by using a barrier in the initialization phase of a module, but we weren't there yet and I wasn't sure we wanted to go there in this PR, hence the explicit loading of rank 0.

Hmm, pondering your mask idea.  Another one might be to just allow `--rank` to treat a missing optarg as an empty nodeset.  Also maybe improving `flux nodeset -i NS NS` so it's more obviously calculating an intersection.  How about `flux nodeset --eval "NS | NS"`?  I'm not feeling very creative at the moment, sorry.

**Comment by grondo** [comment]
Well I was kind of thinking ahead to other rc-file authors and I think it will be almost guaranteed to get it wrong in the current form. However, since nobody else is writing these scripts yet maybe it doesn't matter.

I like the mask idea because you could write rc scripts that do the right thing without worrying about whether you are growing or shrinking, or at least not explicitly worrying about it in the rc script
```sh
# Load module foo on rank 0 first, block for completion
flux module load -r 0 foo  # Does nothing unless rank 0 is in current FLUX_NODESET_MASK
flux module load -r all --exclude 0 # Run on all other ranks in FLUX_NODESET_MASK excluding 0
```
This would greatly simplify scripts with what seems like the least effort... but I may be oversimplifying (or overcomplicating!?)

**Comment by grondo** [comment]
The `flux nodeset` usage seems fine. I was going to say we should look back to the hostlist-based utilities to see what worked and what didn't, since we're on at least iteration 2 of those, but I'm not sure they are the same since they have to process lists and not just sets.

**Comment by garlick** [comment]
This latest update (squashed and forced) sets `FLUX_NODESET_MASK` in the rc1, rc3 subprocess environment as proposed above; modifies `flux-module` to accept an `--exclude` option and respect the mask; and simplifies the rc scripts as discussed.

I factored out the `--rank and --exclude` option handling to a libflux function `flux_get_nodeset()` described in commit d2a4897 but I only `flux-module` is using it at this point.

**Comment by grondo** [comment]
Oh, this seems nice. I guess you decided implied FLUX_NODESET_MASK was ok, or did you just grudgingly do it? :-)

**Comment by garlick** [comment]
I decided I liked it after all.

**Comment by grondo** [comment]
Playing with this a bit. There's definitely a kind of superlinear increase in time-to-initial-program as session size increases as you expected. I tried up to 1024 brokers and really the slowdown wasn't noticeable until you start getting to 256 ranks and above, so I don't think this is a problem.

**Comment by garlick** [comment]
Thanks for trying that.   Good to know that it's not too bad.  I do think that we'll be able to improve performance later on by optimizing the implementation of `flux_rpc_multi()`, like we were brainstorming the other day.

Just added a super brain dead blob of shell code to rc1 and rc3 that allows other projects to extend the startup/shutdown scripts by either installing scripts into a shared `${sysconfdir}/flux/rc1.d`  and `${sysconfdir}/flux/rc3.d`, or appending a directory to `$FLUX_RC_EXTRA` to add new directories to search for `rc1.d/*` and `rc3.d/*`.  Acceptable?

**Comment by grondo** [comment]
That seems fine for now, I'll give it a test.

Also want to say I tested out `rc1` failure and nice on job on capturing and emitting `stderr` of the script on failure -- that's great.

```
$ srun -N4 -n4 --pty src/cmd/flux broker date 
[1457647776.108461] broker.err[0]: rc1: something went wrong
[1457647776.425124] broker.err[0]: Run level 1 Exited with non-zero status (rc=1)
```

**Comment by grondo** [comment]
I'm confused by the `sh -c $rcfile`, but probably it is some arcane shell knowledge which I presently lack. :-)

Why the switch from `bash` to `sh` for sub-projects?  I'm sure you had a reason for not just running anything executable in these directories? Does this imply sub-projects scripts must be written in POSIX shell? (Sorry if these are dumb Qs)

**Comment by garlick** [comment]
That's a typo/thinko (I blame my fingers!)  I'll change it to just execute directly.

**Comment by garlick** [comment]
Ugh, yes.

**Comment by garlick** [comment]
Just squashed the typos and pushed some code that allows the path to rc1 and rc3 to be overridden with an environment variable, and the modified test_under_flux so that if a second argument is present, it selects a particular rc script in the `t/rc` directory (otherwise the default in-tree test scripts are used).

Three rc1 scripts were made
* rc-minimal (empty)
* rc-kvs (load kvs and content-sqlite)
* rc-wreck (load kvs, content-sqlite, job, and wreck)

Then I sent through the sharness tests and selected a personality where possible.  Hopefully this will speed things up and keep things simpler in the beginning of the test suite so problems with the basics are easier to track down.

For now rc3 is always empty when one of the above is selected.

(oops travis is failing - it seems I've botched something and have to leave.  Will check back later.)

**Comment by grondo** [comment]
From the changes to `sharness.d/flux-sharness.sh` it appears that now two env vars are required `FLUX_RC1_PATH` and `FLUX_RC3_PATH`? Or is that just for tests?

In `test_under_flux` should we check to ensure the `FLUX_RC*_PATH`s exist? I'm supposing it isn't an error -- you'll just unexpectedly get no rc scripts run if you typo the `$personality`? Correct me if I am wrong.

**Comment by garlick** [comment]
Yes, the two environment variables are just needed to override the config or compiled-in paths, mainly intended for testing.

Good idea checking if those paths exist.  The broker should probably fail gracefully if bad paths are specified, but it's probably better to check this in sharness to make it easier to debug typos.  I'll add that.

I was just writing tests for the broker behavior when the paths are wrong and rc1 does fail with
```
[1457718342.490209] broker.err[0]: rc1: /bin/bash: rc1-noexist: command not found
[1457718342.490332] broker.err[0]: Run level 1 Exited with non-zero status (rc=127)
flux-start: 0 (pid 2327) exited with rc=127
```
but I need to do a little work on the rc3 failure handling as it's currently ignored.

**Comment by grondo** [comment]
So there is no way to run without an `rc1` and `rc3` script? What if I want to boot in single-user mode? ;-)

**Comment by garlick** [comment]
> So there is no way to run without an `rc1` and `rc3` script? 

Would it be werid if those environment variables (or the config entries) could be set to an empty string to indicate "skip with no error"?

**Comment by grondo** [comment]
So, for the env vars
 * Unset means use internal default, overridden by config
 * Set but `null` (is an empty string what POSIX considers set to "null"?), then disable the script(s)
 * Set and non-null, run value and error if missing, not executable, or exit with non-zero status

This kind of makes sense to me. You could also have a special value "disabled" or "none" but that seems even weirder...

**Comment by garlick** [comment]
Or maybe just a broker option to skip the rc scripts?? I was toying with the idea of `--init=`_mode_ where _mode_ is
* `normal` - the default
* `failsafe` - spawn a shell on failure of rc1 or rc3
* `none` - skip rc1 and rc3

**Comment by grondo** [comment]
That actually sounds better to me. Can it be a `setattr` option -- it seemed like you were moving that direction for most broker opts.

**Comment by garlick** [comment]
Sure, say `flux start -o,-Sinit-mode=none`

**Comment by grondo** [comment]
Cool. Just like the kernel cmdline you could also pass a path to an executable! ;-)

**Comment by garlick** [comment]
OK, this update implements `-Srun-mode=none` to skip rc1, rc3, and tightens up `flux-sharness.sh` to catch rc "personality" typos, and sanitize the environment before running tests.  More tests coming.

**Comment by grondo** [comment]
I liked `init-mode` a lot better than `run-mode` -- for a resource management framework `run-mode` seems like it might be a name collision... or is that just me?

**Comment by garlick** [comment]
I guess I was half ass trying to group the two attributes that are part of the "runlevel" class in a namespace beginning with "run": `run-level` and `run-mode`.  How about I change it to `init.run-level` and `init.mode` and we'll agree right now that we'll start grouping attributes in a dotted hierarchy?

**Comment by grondo** [comment]
Ah, I see. Yeah, that sounds ok.

**Comment by garlick** [comment]
Just forced a push with some incremental development squashed, and attributes renamed.

**Comment by garlick** [comment]
OK, I feel a little better about the tests just pushed.

Some documentation should be done but given that you're heading out @grondo, perhaps it makes sense to get this in first if it looks OK, and I'll follow up later with a doc PR.

**Comment by grondo** [comment]
I pretty much ACK it as is.

It would be interesting to test the integration with sched if we haven't
already. With a proven working strategy for "srun flux broker
script-that-uses-flux-submit" merging is a no brainer.

I'll test it out later, time permitting.

**Comment by grondo** [comment]
Ok, I tried the following:
 - Install flux-core to `/tmp/flux`
 - build flux-sched against flux-core with `PKG_CONFIG_PATH=/tmp/flux/lib/pkgconfig:$PKG_CONFIG_PATH ./configure --prefix=/tmp/flux `
 - Install flux-sched
 - create script in `/tmp/flux/etc/flux/rc.d/rc1.d/sched` with the following contents: (Is that path expected?)

 ```
#!/bin/bash -e
flux module load -r 0 sched
 ```

- Start flux with `FLUX_MODULE_PATH` able to find sched plugins:

 ```
$ FLUX_MODULE_PATH=/tmp/flux/lib/flux/sched-plugin /tmp/flux/bin/flux start --size=2       
flux-start: setrlimit: could not remove core file size limit: Operation not permitted  
flux-broker: Configuration failed to load: /home/ubuntu/.flux, falling back
flux-broker: Configuration failed to load: /home/ubuntu/.flux, falling back
$ flux module list -r all | grep sched
sched                 186811 FED56A3   19  S  0    
$ flux submit -n4 hostname
submit: Submitted jobid 1 
 flux wreck attach -l 1                                                                                                                                                      
1: grondo-flux-core-1713174
2: grondo-flux-core-1713174
3: grondo-flux-core-1713174
0: grondo-flux-core-1713174
 ```

**Comment by grondo** [comment]
So, this looks good! Just one question about whether the path to extension rc scripts `$sysconfdir/flux/rc.d/rc1.d/*` is correct, or if the `rc1.d` should be one level up? Then we can add a default script for flux-sched and figure out the sched module path problem. (separate issues obviously)

**Comment by garlick** [comment]
Thanks for doing that test!  I think I did get the path wrong.  Let me fix that.

**Comment by grondo** [comment]
Is this ready after squashing the path update? I can check back in tonight but then I'm out for a week. However,  perhaps @trws, @lipari or @dongahn could do the actual merge.

**Comment by garlick** [comment]
OK, it's been squashed and if it passes travis I say merge.  No worries if you don't get to it @grondo (enjoy your vacation!)

**Comment by grondo** [comment]
Great work! I tried to give you a hooray, but for me it just looks like a rectangle.

**Comment by garlick** [comment]
thanks!

**Pull request merged**
