### PR TITLE
libflux: clean up interface for broker attributes

### PR DESCRIPTION
**Pull request by garlick**
As proposed in #1818, this PR simplifies the API support for broker attributes.  I think the main benefit, besides reducing the API surface area, is that the broker's attribute flags are no longer exposed in the API, which should reduce coupling with the broker implementation and allow it to change without affecting the API, when we have time.

After having a go at converting to future based versions of `flux_attr_get()` and `flux_attr_set()`, I concluded that the the current versions that hide synchronous RPCs were probably reasonable to keep after all, given how they are used, and the inconvenience of converting to the more complicated interface.

I ran into trouble attempting to make `flux_attr_fake()` private.  Long story, but linking the broker to a static version of `libflux` did not work out.  Instead it is just renamed to `flux_attr_set_cacheonly()` and labeled as a for testing.

Finally, `flux_get_rank()` and `flux_get_size()`, which are just wrappers for `flux_attr_get()` were folded into `attr.[ch]`, and the remaining function in `info.[ch]`, `flux_get_nodeset()`, was removed, and its one and only user, `flux module`, made to do without.

### CODE REVIEW

**Comment by grondo** [comment]
Oops, was this supposed to go in before #1844?

**Comment by garlick** [comment]
Nope - I'll rebase and squash the spelling error fix I tacked on.

**Comment by garlick** [comment]
Oops, I seem to have managed to screw up the conflict resolution.  Hang on, one more try.

**Comment by grondo** [comment]
Nice cleanup!

**Pull request merged**
