### PR TITLE
maint: remove flux spack docker

### PR DESCRIPTION
**Pull request by vsoch**
Problem: the flux + spack docker images in /etc are not commonly used and would better be maintained elsewhere anyway.
Solution: delete them from this repository (and will put elsewhere).

This will close https://github.com/flux-framework/flux-core/issues/4962

### CODE REVIEW

**Review by grondo — APPROVED** [review]
LGTM. Thanks!

**Comment by vsoch** [comment]
I'll have another repository to link here (soon) for folks that coming looking for these builds.

**Comment by vsoch** [comment]
ok - going to put the previous assets here: https://github.com/rse-ops/flux-spack-docker

**Comment by vsoch** [comment]
Also please see https://github.com/rse-ops/spack-flux-container where we have a bunch of spack container builds.

**Comment by vsoch** [comment]
Thank you mergify bot. You work so hard. :cookie:

**Pull request merged**
