### PR TITLE
Colllection of small fixes for splash project (part 2)

### PR DESCRIPTION
**Pull request by garlick**
This PR contains a couple of items from @trws's #1396 [WIP] Splash PR, and a broker error handling tweak resulting from #1451.

### CODE REVIEW

**Comment by dongahn** [comment]
@garlick: Just FYI the scheduler doesn't read rdesc through` jsc_query_jcb` interface any longer. It now gets that information from the payload of the initial `submit` event.

If the new interface is needed, I'm not opposed to commit that in, though. 

Ultimately, it seems what we will need is "getter" and "setter" interface which can avoid json to native type conversion.

**Comment by garlick** [comment]
Ah OK - @trws shall we drop this or do you need it?

**Comment by trws** [comment]
Maybe it isn't using it actively right now, but I have at least one version that is using it, it would be best from my perspective to have it if it is reasonable.

**Comment by dongahn** [comment]
Not a problem to fold this in, in that case.

**Comment by trws** [comment]
Oh my, thank you for adding the pointer checking @garlick, that was really sloppy of me.

**Comment by garlick** [comment]
I updated the commit message on the jsc change to indicate that it is a temporary workaround for splash.

**Comment by grondo** [comment]
Restarted a builder that hung after a failure in the cron-faketime tests.

**Comment by grondo** [comment]
LGTM, will merge once Travis returns

**Comment by grondo** [comment]
I merged @chu11's PR so this needs a rebase, sorry!

**Comment by garlick** [comment]
Thanks for the merge!

**Pull request merged**
