### PR TITLE
kvs: allow get_double to be called on an int

### PR DESCRIPTION
**Pull request by SteVwonder**
See: https://github.com/flux-framework/flux-sched/issues/214

### CODE REVIEW

**Comment by SteVwonder** [comment]
Doh, I got so caught up on fixing the simulator to verify this patch worked that I forgot to create tap tests.  Gimme some more time to push those before merging.  Sorry

**Comment by SteVwonder** [comment]
@grondo or @garlick what do you think is the best way to test this?

As far as I can tell, the tests in `/src/modules/kvs/` aren't run within a Flux instance.  Is it possible to run these unit tests within an instance?

I know that the tests in `/t/` are run under a flux instance, but the kvs tests there utilize the `flux-kvs` command.  The `flux-kvs` command does just a straight `kvs_put` so the values aren't put through type-specific json serialization.  I could extend the `flux-kvs` command to support something like `flux kvs put-as double "foo" 1.0`.

Thought?

**Comment by garlick** [comment]
I think the current `flux kvs put` and `flux kvs type` will let you put a double or an int (e.g. 1.0 vs 1) and test what json-c thinks it is.  Maybe what's lacking ks `flux kvs get-as`?

**Comment by grondo** [comment]
> I think the current flux kvs put and flux kvs type will let you put a double or an int (e.g. 1.0 vs 1) and test what json-c thinks it is. Maybe what's lacking is flux kvs get-as?

One thing I was seeing is that I could `flux kvs put foo=1.0` then `flux kvs get-treeobj` showed the value stored as `"1.0"`. I wonder how that is happening:

```
$ flux kvs put foo=1.0
$ flux kvs get-treeobj foo
{"FILEVAL":1.0}
```

I think `flux kvs put` just uses `kvs_put (h, key, json_str)` where above json_str is `"1.0"`.  In this case the JSON is parsed into an object and I'm guessing json-c preserves the string representation and doesn't regenerate it.

For the tests we should use `kvs_put_double()` directly. Perhaps using a little test program under `./t`?

**Comment by grondo** [comment]
Oh @garlick, I apologize as I think I misread what you were suggesting for the test. The test could put an integer and double and make sure both can be read back as double using `kvs get-as`. Sorry I think that would be sufficient here.

What if instead of adding a new one-off command to `flux kvs` we somehow allowed jansson style `unpack` format specifier to be used with both `get` and `put`. I'm not sure how the `get` would actually work, but just an idea to throw out there.

**Comment by grondo** [comment]
@SteVwonder, I don't think we necessarily need to wait for a test on this one, since the test will end up being non-trivial. I'll open an issue to track that we should check both integer and float values can be read with `kvs_get_double()`, and once travis returns (had to restart one test) I think we can merge this since it fixes a real regression/bug.

**Pull request merged**
