### PR TITLE
libidset: reject idset strings that don't conform to RFC 22

### PR DESCRIPTION
**Pull request by garlick**
This fixes the bad input cases called out in #3231 plus a few more.

### CODE REVIEW

**Comment by garlick** [comment]
asan builder failed here
```
FAIL: t4000-issues-test-driver.t 9 - t2686-shell-input-race.sh
t4000-issues-test-driver.t:  FAIL: N=11  PASS=10  FAIL=1 SKIP=0 XPASS=0 XFAIL=0
ERROR: t4000-issues-test-driver.t - exited with status 1
```
I went ahead and restarted it

**Review by grondo — APPROVED** [review]
LGTM.

One nit: In the commit message for 67f8229, the term "unbalanced parens" is used. To avoid confusion, should this be changed to "unbalanced brackets"?

**Comment by grondo** [comment]
> asan builder failed here

Hm, that is probably the same race in the Python `Ctrl-C` test. I wonder if there is just no way to get that test race-free and it should just be removed?

**Comment by garlick** [comment]
> One nit: In the commit message for 67f8229, the term "unbalanced parens" is used. To avoid confusion, should this be changed to "unbalanced brackets"?

Doh! I'll fix that and then set MWP.  Thanks for the review.

**Pull request merged**
