### PR TITLE
Fixes to a few build issues I ran into on ubuntu 14.04

### PR DESCRIPTION
**Pull request by garlick**
Maybe hold on merging until we hear from @trws on #275.  If there's a build related fix to that one then it could be tacked on to this PR.

### CODE REVIEW

**Comment by grondo** [comment]
Nice! Thanks was running into a couple of these myself. I'll wait for @trws before clicking though.

**Comment by garlick** [comment]
Incidentally I set up an [cloud 9](ide.c9.io) sandbox and began building prereqs for flux-core in ~/local.  I noted that I can set `PKG_CONFIG_PATH=~/local/lib/pkgconfig` in my .bashrc and libsodium, libzmq, and libczmq all find each other in that non-standard install prefix, but flux-core ignores it of course by virtue of the m4 we added that ignore pkg-config.

What do you think about using pkg-config to find libczmq, libzmq?  It would mean touching every Makefile.am, but then flux-core would work more like everything else.

**Comment by grondo** [comment]
Oh, yeah that sounds like a good idea to me

**Comment by garlick** [comment]
Although - it looks like this somehow works for your travis environment with libzmq installed in ~/local.  I probably need to study this a bit more.

**Comment by grondo** [comment]
In `.travis.yml` I have to:
```
  - export LD_LIBRARY_PATH=$HOME/local/lib
  - export CPPFLAGS=-I$HOME/local/include
  - export LDFLAGS=-L$HOME/local/lib
  - export PKG_CONFIG_PATH=$HOME/local/lib/pkgconfig
```

Would be nice to get rid of the forced `CPPFLAGS` & `LDFLAGS` (but this is how you had to do it before `pkgconfig` so I didn't think twice about it, Sorry!!)

**Comment by grondo** [comment]
@garlick, in my c9.io instance I was able to do
```
sudo apt-get remove python-cffi
```
and then 
```
sudo pip install cffi
```

**Comment by garlick** [comment]
@grondo - trying that (on ubuntu 14.04 lts) but pip is sad due to missing ffi.h?

**Comment by garlick** [comment]
Never mind - that was a missing libffi-dev.

**Comment by garlick** [comment]
Ok, just rebased with a new commit to use pkg-config to find libzmq and libczmq as discussed.

This squashed the earlier commit that checked for zhash_next() because we are able to check for a minimum libczmq version number.

**Comment by grondo** [comment]
Hm, sorry something must not be setup correctly in the travis environment. I'll look into it.

**Comment by grondo** [comment]
Ah, I need to update travis version of czmq to 3.0.1 at least. Do you know if this is strictly necessary? I made a PR to your branch though..

**Comment by grondo** [comment]
In addition to the travis build failures (which I'm trying to look into, seems to  be a new reproducible failure in the jsc tests), I'm also getting the following error from `make distcheck` on ubuntu 14.04: looks like perhaps the tests driver is trying to save output to logfile in srcdir instead of builddir.

```
make[5]: Entering directory `/home/ubuntu/workspace/flux-core-0.1.0/_build/doc/man1'
../../../config/test-driver: line 107: /home/ubuntu/workspace/flux-core-0.1.0/_build/../doc/test/spellcheck.log: Permission denied
FAIL: /home/ubuntu/workspace/flux-core-0.1.0/_build/../doc/test/spellcheck
../../../config/test-driver: line 126: /home/ubuntu/workspace/flux-core-0.1.0/_build/../doc/test/spellcheck.trs: Permission denied
../../../config/test-driver: line 127: /home/ubuntu/workspace/flux-core-0.1.0/_build/../doc/test/spellcheck.trs: Permission denied
../../../config/test-driver: line 128: /home/ubuntu/workspace/flux-core-0.1.0/_build/../doc/test/spellcheck.trs: Permission denied
../../../config/test-driver: line 129: /home/ubuntu/workspace/flux-core-0.1.0/_build/../doc/test/spellcheck.trs: Permission denied
make[5]: *** [/home/ubuntu/workspace/flux-core-0.1.0/_build/../doc/test/spellcheck.log] Error 1
```

**Comment by trws** [comment]
In #276, I've run into some issues with modules not re-building on updates to the core because of the way their libraries are specified.  Would you prefer that I wait and rebase against this, or try to submit a pull-request here for the changes? It's mostly just moving core and/or internal from ldflags to libadd so automake honors the dependency chain.

**Comment by garlick** [comment]
How about a pull request here.  Thanks.

**Comment by trws** [comment]
Ok. By the way, don't block anything on the file cleanup PR, there's a weird corner case I need to track down before that can be merged. You wouldn't happen to know of anywhere that we fork, then exec the parent instead of the child would you?

I'm also trying to track down where the *-event and *-req files are created, it looks like zmq creates them but the standard cleanup procedure doesn't seem to be documented with those bind functions, which makes me wonder.



Sent with Good (www.good.com)

________________________________

**Comment by garlick** [comment]
@grondo I think I addressed the check problems in doc as well as the KVS config problem in #279.

Incidentally I find I have to set LD_LIBRARY_PATH in the c9.io build with zeromq in ~/local.  pkg-config doesn't solve that one.

**Comment by trws** [comment]
What's the failure? It's odd that that should happen unless there's somewhere that we're missing a transitive dependency.



Sent with Good (www.good.com)

________________________________

**Comment by garlick** [comment]
> What's the failure? It's odd that that should happen unless there's somewhere that we're missing a transitive dependency.

I'm installing libzmq and libczmq in a location that's not in the default library path $HOME/local.  The failure I'm seeing is the AC_RUN_IFELSE() in config/x_ac_zeromq.m4.  I don't actually know if libtool would find the installed .la files and do something sensible with its wrappers for our actual build products (I assumed it wouldn't)?

libzmq is linked against libsodium in the same spot; maybe that's the transitive dependency?

**Comment by garlick** [comment]
The actual output from config.log is
```
./conftest: error while loading shared libraries: libzmq.so.5: cannot open shared object file: No such file or directory
```

**Comment by trws** [comment]
I made a bad assumption and was wrong.  That's probably because pkg-config doesn't set rpaths for libraries, and I'm betting the configure macro isn't smart enough to use libtool for linking, so it wont do it either.  That check either needs `LD_LIBRARY_PATH` set around the AC_RUN_IFELSE or something like `LIBS+=$(pkg-config --libs-only-L | sed -e 's/-L/-Wl,-rpath=/g'`.

It should be fine for the actual build products because libtool hacks in rpaths for anything that isn't in the system build path by default unless it's told not to, which I don't think we do.

**Comment by trws** [comment]
All looks good to me.  No more immediate updates from my end. (ACK)

**Comment by grondo** [comment]
@garlick, I still get the spellcheck errors, but only with `make distcheck` on the ubuntu 14.04 system. It seems like a automake/autoconf bug though, the spellcheck test driver is trying to write its log file to (read-only) srcdir (the source directory of spellcheck itself) instead of builddir in which the test should be run.

We can delay a fix for this (which will likely be a workaround) because I'd like to get the stuff in this PR merged, then merge #280.

**Comment by grondo** [comment]
@garlick: should have said, go ahead and force push here if you're ready

**Comment by trws** [comment]
In doing some quick testing with a newer automake, btw the one we have on LC has documented security vulnerabilities that have been known and affect all packages configured with it for 5 years (yay!), anyway the issue with the spellcheck test is that it points to the test in top_srcdir.  For check, and especially distcheck, this really needs to be copied to the build directory, it's not pretty, but I had to do some of this to make the python tests work properly.  The most current version of automake actually gives an error at autogen time when it sees the srcdir variable in a test specification and refuses to complete.

**Comment by garlick** [comment]
I fixed that didn't I?

**Comment by trws** [comment]
Ack! So you did, I missed the merge for that.  Apologies!

**Pull request merged**
