### PR TITLE
testsuite: remove unportable cshism

### LINKED ISSUE #4114: t2410-exec-systemd.t: 6: eval: Syntax error: Bad fd number
Just pulled down the latest master and am getting this test failure:

```
./t2410-exec-systemd.t -v
build-options:		+systemd+hwloc==2.1.0+zmq==4.3.2
  user@5588.service                                                                                                       loaded active     running   User Manager for UID 5588                                                                                  
build-options:		+systemd+hwloc==2.1.0+zmq==4.3.2
  user@5588.service                                                                                                       loaded active     running   User Manager for UID 5588                                                                                  
expecting success: 
        ${SHARNESS_TEST_DIRECTORY}/sdprocess/sim-broker \
            run-wait-exit --unitname=simtest-success \
            /bin/true >& run-wait-exitA.out &&
        grep simtest-success run-wait-exitA.out | grep exited | grep "status=0"

./t2410-exec-systemd.t: 6: eval: Syntax error: Bad fd number
FATAL: Unexpected exit with code 2
2022-02-08T20:57:44.573339Z broker.err[0]: rc2.0: /bin/bash -c sh ./t2410-exec-systemd.t  --verbose Exited (rc=1) 0.1s
flux-start: 0 (pid 719736) exited with rc=1
```

I think the  `>& filename` construct to redirect stdout and stderr to filename is not working in the version of `/bin/sh` on my Ubuntu 20.04 LTS system (dash 0.5.10.2-6)?

Maybe we need to change it to `>filename 2>&1`?

### PR DESCRIPTION
**Pull request by garlick**
Problem: t2410-exec-systemd.t fails with dash 0.5.10

Replace ">& filename" idiom with ">filename 2>&1".

Fixes #4114

### CODE REVIEW

**Review by chu11 — APPROVED** [review]
oops sorry.  LGTM

**Comment by garlick** [comment]
NP!  It was a nice shorthand that apparently works on all our test builders.  Not sure why my Ubuntu 20.04 LTS system is the party pooper.  Oh well, setting MWP.

**Comment by grondo** [comment]
Maybe we should ensure /bin/sh points to dash on at least one of the CI builders?

**Comment by chu11** [comment]
> Maybe we should ensure /bin/sh points to dash on at least one of the CI builders?

sounds good to me.  would it be worthwhile to have one point to a `csh`?

**Comment by grondo** [comment]
> would it be worthwhile to have one point to a csh too?

I think the world would break if /bin/sh -> /bin/csh, but I assume you mean SHELL=/bin/csh?

**Pull request merged**
