### PR TITLE
add start of spack base image for flux-core

### PR DESCRIPTION
**Pull request by vsoch**
Note that there is a bug in spack that must be fixed for the multistage build (the next container coming) to work.

Bug: https://github.com/spack/spack/pull/31939

Signed-off-by: vsoch <vsoch@users.noreply.github.com>

### CODE REVIEW

**Comment by vsoch** [comment]
why do the commits matter if you can squash and merge? This feels like an unnecessary barrier to contribution.

**Comment by grondo** [comment]
> why do the commits matter if you can squash and merge? This feels like an unnecessary barrier to contribution.

Sorry, I'm not sure what this question is directed at. I'll assume you mean the commit validator CI check?

We do not squash and merge on this project, we rebase + merge. Projects in flux-framework (well the main projects anyway) follow the Collective Code Construction Contract v4.1 (documented in [RFC1](https://flux-framework.readthedocs.io/projects/flux-rfc/en/latest/spec_1.html)) borrowed from the zeromq project, which encourages "patches" (or commits) to have a commit message which follow "good commit message" guidelines generally accepted by many communities (use the imperative, try to keep subject to around 50 characters wide and body at 72, etc) Many online references document the reasons for those good practices.

It is a valid point that any requirements are a barrier to contribution. We hope that the automated CI tools and our helpful dispositions can mitigate those barriers ;-)

**Comment by vsoch** [comment]
ok, so can you walk me through how to fix this?

**Comment by grondo** [comment]
Instead of merging master into your branch, use
```console
$  git rebase -i origin/master
```
to rebase your branch on top of current upstream (assuming here that `origin` is the upstream, adjust if necessary) This will avoid any merge commits in your PR.

During the interactive rebase, you can feel free to squash all your commits together into one if you'd like (It would make sense here in my opinion, but this is up to you).

Then just rework your commits to have a subject line and commit message describing what the commit is doing. In the commit body, we like to use the form:

```
Problem: This is a description of a problem this commit is
going to solve.

This is what the commit does to solve the problem at a high level.
```

E.g.

```
docker: build base image for spack container in github actions

Problem: It would be good to have a base image ready to speed up
builds of docker images for flux-core spack package testing, but no
such image exists.

Add a Dockerfile and github workflow to build this base image.
```

(Apologies if I got the descriptions wrong, I'm guessing a bit on what exactly 
we're doing here - A good reason that it is nice when the PR author writes the
commit message this way.)

**Comment by vsoch** [comment]
okay fingers crossed I didn't bork it up!

**Review by grondo — APPROVED** [review]
Looks great to me! I'm not sure how all this works, but I'm guessing we need to get this PR landed so that the base image starts being built by the scheduled Github Workflow? Or is there more to do here?

**Comment by grondo** [comment]
BTW, I did edit the PR title because we use that to generate automated release notes (and wanted the term spack in there!). Hopefully that was OK!

**Comment by vsoch** [comment]
spaaaaaaaaaaaaack!

**Pull request merged**
