### PR TITLE
job-info: support annotations (part 2)

### PR DESCRIPTION
**Pull request by chu11**
This is built upon PR #2960, part #2 in the annotations work.  Annotations are distributed from the job-manager to job-info and available via the `job-info.list` service.  

I think this is a good stopping point for part 2.  Adding the ability for users to create their own annotations could possibly go into this PR as well, but I decided to hold off and maybe that'll be part 3 (as it will introduce security checks, thus security tests).  Presumably part #4 will be the final `flux-jobs` support.

I don't think there's anything too spectacular to mention about the PR.  The biggest decision, as discussed in #2608, is that annotations should be sent via an event from the job-manager, vs many of the other options discussed/prototyped.

As an FYI, the additions in this PR are the last 7 commits in this series.

### CODE REVIEW

**Comment by chu11** [comment]
hmm hit this potentially racy fail?

```
expecting success: /usr/src/t/issues/t2686-shell-input-race.sh
{"[0-3]": {"Package": 1, "Core": 16, "PU": 16, "cpuset": "0-15"}}
2020-07-08T01:16:58.768930Z sched-simple.debug[0]: ready: 4 of 4 cores: rank[0-3]/core0
16290676736
16307453952
16324231168
16341008384
16357785600
16357785601
16374562816
16391340032
16408117248
16424894464
16441671680
16458448896
16760438784
16777216000
16793993216
16810770432
16827547648
16844324864
16944988160
17012097024
17028874240
17028874241
17028874242
17045651456
flux-start: 0 (pid 12908) Killed
not ok 9 - t2686-shell-input-race.sh
```

**Comment by grondo** [comment]
> hmm hit this potentially racy fail?

We see this error frequently in various tests:
```
flux-start: 0 (pid 12908) Killed
not ok 9 - t2686-shell-input-race.sh
```

This means one broker was slow to exit and was killed by `flux-start`. I've never seen it outside of Travis-CI so not sure how to debug.

**Comment by chu11** [comment]
just rebasing now that #2960 is in

**Comment by chu11** [comment]
So I've rebased & added the following on top of this PR:

- re-worked annotations to store "namespace" keys within an object of a key. i.e.

  `{"sched.reason_pending": "no cores"}`

  is now

  `{"sched":{"reason_pending": "no cores"}}`

- re-worked annotations updates to be "recursive". e.g.

  updating

  `{"sched": { "reason_pending": "no cores"}}`

  with

  `{"sched": { "t_estimate": 1234}}`

  should result in

  `{"sched": { "reason_pending": "no cores", "t_estimate": 1234}}`

- support initial annotations in `flux-jobs`.  `flux-jobs` requires some refactoring to allow arbitrary annotation keys to be listed by
  the user i.e. `annotations.user.foo.bar`.  So for this initial implementation I only supported the defined keys in RFC27.

  `sched.reason_pending`
  `sched.resource_summary`
  `sched.t_estimate`

  I'll follow up with generic support in a later PR (@grondo has done  some refactoring in his PR #3045)

- added tests

**Comment by grondo** [comment]
Ugh, I should have had you wait on tests. I started down reworking `t2800-jobs-cmd.t` and had to end up rewriting most tests. At least your new tests will be self-contained, so merging in either way should not be too bad.

**Comment by chu11** [comment]
> Ugh, I should have had you wait on tests. I started down reworking t2800-jobs-cmd.t and had to end up rewriting most tests. At least your new tests will be self-contained, so merging in either way should not be too bad.

No worries and good timing on your comment.  I just realized I forgot to add some tests to `t2800-jobs-cmd.t`, and went ahead and yoinked your refactoring patch for `flux-jobs`'s header output.  So this PR is now based on your PR #3045 anyways :-)

**Comment by grondo** [comment]
Ok, a *lot* more refactoring coming to flux-jobs...

**Comment by chu11** [comment]
Doh!  I just realized I got a bug here:

```
class AnnotationsInfo:                                                                                                                      
    def __init__(self, annotationsDict):                                                                                                    
        self.annotationsDict = annotationsDict                                                                                              
        self.atuple = namedtuple("X", annotationsDict.keys())(                                                                              
            *(                                                                                                                              
                AnnotationsInfo(v) if isinstance(v, dict) else v                                                                            
                for v in annotationsDict.values()                                                                                           
            )                                                                                                                               
        )                                                                                                                                   
                                                                                                                                            
    def __repr__(self):                                                                                                                     
        # Special case, empty dict return empty string                                                                                      
        if self.annotationsDict:                                                                                                            
            return json.dumps(self.annotationsDict)                                                                                         
        return ""                                                                                                                           
                                                                                                                                            
    def __getattr__(self, attr):                                                                                                            
        try:                                                                                                                                
            return object.__getattribute__(self.atuple, attr)                                                                               
        except AttributeError:                                                                                                              
            return "" 
```

the `getattr` trick works if the last field of `annotations.sched.reason_pending` doesn't exist, but it doesn't work if `annotations.sched` doesn't exist.  Perhaps I need to recursively create fake tuples in this recursive case.

**Comment by chu11** [comment]
Given PR #3060 and some other things I discovered, I'm going to re-do PR ordering.  Nixing this PR.

**Comment by grondo** [comment]
Ugh, sorry for the inconvenience @chu11! :frowning_face:

**Comment by chu11** [comment]
> Ugh, sorry for the inconvenience @chu11! frowning_face

No worries, its also due to other things I'm uncovering as I do more development!

**Pull request closed without merging**
