### PR TITLE
notify user of stopped queue in `flux job attach`

### PR DESCRIPTION
**Pull request by grondo**
This PR amends the `flux job attach` status line if a queue is stopped. That is, instead of a status of just `waiting for resources` a user will see:
```
flux-job: ƒ97BKDZ7MZ waiting for resources (default queue stopped)     00:00:14
```
where `default` would be replaced with a queue name if the job was submitted to a named queue.

### CODE REVIEW

**Review by garlick — APPROVED** [review]
Nice usability improvement.  LGTM

**Comment by grondo** [comment]
Thanks to @wihobbs for testing with actual queues, which didn't work :facepalm: 

Fixed that and added a test that uses queues in addition to the existing test with an anonymous queue.

@wihobbs - can you ensure this version works in your test environment? Thanks!

**Comment by wihobbs** [comment]
@grondo I'm still not seeing the `(batch queue stopped)` message in my test _but_ I do see it when I use `--test-size`. For reference, here's what I've been running on fluke:

```
(s=101,d=0) fluke108 ~ $ flux alloc -N1 --time=1h
(s=1,d=1) fluke89 ~ $ cd flux-core/
(s=1,d=1) fluke89 ~/flux-core ((HEAD detached at 386c5ee0d))$ ./src/cmd/flux start
(s=1,d=0,builddir) fluke89 ~/flux-core ((HEAD detached at 386c5ee0d))$ which flux
~/flux-core/src/cmd/flux
(s=1,d=0,builddir) fluke89 ~/flux-core ((HEAD detached at 386c5ee0d))$ ../reproducer.sh
flux-job: f5DBki79 waiting for resources                     00:01:33
```

and my reproducer.sh script is:

```
#!/bin/bash

setup_fake_resources() {
    export NNODES=$1
    flux module remove -f sched-fluxion-qmanager
    flux module remove -f sched-fluxion-resource
    flux module remove -f sched-simple
    flux module remove -f resource
    flux config load <<EOF
[policy]
jobspec.defaults.system.queue = "debug"

[resource]
noverify = true
norestrict = true

[[resource.config]]
hosts = "test[1-$(expr ${NNODES} / 2)]"
cores = "0-3"
properties = [ "debug" ]

[[resource.config]]
hosts = "test[$(expr $(expr ${NNODES} / 2) + 1)-${NNODES}]"
cores = "0-3"
properties = [ "batch" ]

[queues.debug]
requires = [ "debug" ]

[queues.batch]
requires = [ "batch" ]

[sched-fluxion-qmanager]
queue-policy-per-queue="batch:firstnodex debug:fcfs"
EOF
    flux module load resource noverify monitor-force-up
    flux module load sched-simple
}

setup_fake_resources 4
flux run -N1 -qbatch sleep inf
```

In this situation, it does work:
```
(s=1,d=1) fluke89 ~/flux-core ((HEAD detached at 386c5ee0d))$ ./src/cmd/flux start --test-size=4
(s=4,d=0,builddir) fluke89 ~/flux-core ((HEAD detached at 386c5ee0d))$ flux queue stop --all
Scheduling is stopped
(s=4,d=0,builddir) fluke89 ~/flux-core ((HEAD detached at 386c5ee0d))$ flux run -N1 sleep inf
flux-job: f7LGD61V waiting for resources (default queue stopped)                00:00:10
```
and FWIW I like the improvement it adds.

**Comment by grondo** [comment]
Hm, your reproducer works for me: (I added `flux resource list` and `flux queue status` output)
```console
$ src/cmd/flux start ./rep.sh
     STATE QUEUE      NNODES   NCORES    NGPUS NODELIST
      free debug           2        8        0 test[1-2]
      free batch           2        8        0 test[3-4]
 allocated                 0        0        0 
      down                 0        0        0 
batch: Job submission is enabled
batch: Scheduling is stopped
debug: Job submission is enabled
debug: Scheduling is stopped
flux-job: f27kHdpT waiting for resources (batch queue stopped)          00:00:05
```

I'm sure you did this but can you make sure you recompiled `flux-job` after updating the branch?

**Review by wihobbs — APPROVED** [review]
Sorry, user error on my part when running the previous reproducer. Looks great, @grondo!

Edit: my branch was slightly behind yours and had gotten stale. So I had a fresh compile off of a outdated commit. 🤦

**Comment by grondo** [comment]
Thanks! And thanks for catching the original error @wihobbs. I'll set MWP now.

**Pull request merged**
