### PR TITLE
module libraries and libcore built as shared libs

### PR DESCRIPTION
**Pull request by trws**
This is a partial fix for #179, dependency resolution should be fixed up more reliably in the build system, and installation paths need to be dealt with for the shared libraries.  Some more testing is also in order.

What this does include is that the libflux-core library no longer includes any module libraries, and is itself built as a shared library that the modules link in.

### CODE REVIEW

**Comment by trws** [comment]
This last commit, assuming travis agrees with my tests, should have things in a mergeable state.   It could use further testing, installed vs non for example, and a thorough review, but everything that should be linking via shared library is now I think.  The odd bit that remains is dealing with modules that need more of the API than is exposed by flux-core.  There isn't a lot of that, but the kvs for example depends on several symbols from libutil.

**Comment by grondo** [comment]
This looks like a really great direction to me. Not sure why tests are failing in Travis... If you want I can help look into that tomorrow.

Also, I might have missed this but are `flux-` commands to be built against the `libflux-*.so` shared libraries, or are they still using static convenience libs for now?

**Comment by trws** [comment]
I found out what some of the issues are, they just keep cascading into 
new ones.  Most recent one is that the message update PR that just went 
in actually breaks KAP, despite passing its own travis tests..., which 
kills check here.  Also several of the modules were not linking all 
necessary symbols at `.so` build time, passing on check on hype then 
failing on travis.  All of that is resolved in the most recent commit, 
so hopefully that addresses it.

**Comment by garlick** [comment]
@trws, sorry about breaking KAP!  It builds only if `HAVE_MPI` is set, and it's not set in my personal environment, and likely isn't set for travis builds either.

**Comment by trws** [comment]
@garlick No worries, it was a simple enough fix at least.  Getting everything to link on the travis machine is proving not to be however.  Do you happen to know what gcc version we're running on there? Something is different in the way symbols are getting resolved on hype and on the build bot.  All of the errors I'm getting are legitimate, but having it only fail on travis makes the debug loop pretty long.

**Comment by garlick** [comment]
It's displayed early in the build log:
```
$ gcc --version
gcc (Ubuntu/Linaro 4.6.3-1ubuntu5) 4.6.3
```

**Comment by garlick** [comment]
If you can get a Ubuntu vm going (virtualbox on your mac?), you may be able to work in an environment closer to the travis one.  See `.travis.yml` for a recipe of sorts for building a similar environment.

**Comment by grondo** [comment]
I used a Dockerfile to build the original `.travis.yml` in order to avoid long debug loop. 
(Unfortunately we don't have anywhere convenient to run docker on our systems,  but maybe we can set something up somewhere.

This Dockerfile might need some slight tweaking as it was from awhile ago:
```
FROM ubuntu:14.10
RUN apt-get -y update
RUN apt-get -y upgrade
RUN apt-get -y install \
        lua5.2 liblua5.2-dev lua-posix munge \
        libmunge-dev libjson-c-dev \
        libtool automake autoconf \
        aspell wget g++ make git uuid-dev
RUN useradd -m ubuntu
RUN for url in \
        https://download.libsodium.org/libsodium/releases/libsodium-1.0.0.tar.gz \
        http://download.zeromq.org/zeromq-4.1.0-rc1.tar.gz \
        http://download.zeromq.org/czmq-3.0.0-rc1.tar.gz ; do \
                f=`basename $url .tar.gz` && \
                wget ${url} && \
                tar xvfz ${f}.tar.gz && \
                (cd $(basename $f -rc1) && ./configure && make install); \
        done

RUN git clone https://github.com/grondo/lua-hostlist && \
     cd lua-hostlist && \
     make LUA_VER=5.2 && \
     make install LUA_VER=5.2
RUN apt-get -y install vim strace
RUN ldconfig
USER ubuntu
WORKDIR /home/ubuntu
RUN git clone --depth=50 --branch=master https://github.com/flux-framework/flux-core && cd flux-core && ./autogen.sh && ./configure && make check
```

**Comment by grondo** [comment]
Oops, the above Dockerfile isn't going to work -- it was used for testing with lua-5.2. The travis CI environment is actually ubuntu 12.04LTS. Let me try to dig up the *right* Dockerfile this time.

**Comment by trws** [comment]
At least it's encouraging that this last version works correctly with clang.  The only holdout for the gcc build seems to be missing symbols in the lua bindings, so hopefully this will be the last round anyway.

The only thing I'm wondering is if it might be worth turning all of this into a flux-internal shared library, so it will pull in the symbols it needs at linking rather than manually propagating them everywhere.  Or maybe there's a better way to do this in Automake, I don't know of one, but CMake for example will track the library dependencies of a static library and apply them where that library is used.  Do either of you know a good way to do that across directories for Automake?

**Comment by grondo** [comment]
Libtool does support some sort of inter-library dependencies. I thought automake was smart enough to do this if you linked a static convenience library with another?

https://sourceware.org/autobook/autobook/autobook_77.html#SEC77

**Comment by grondo** [comment]
@trws, not sure if this is helpful but here's a `Dockerfile` that more closely matches travis-ci.org build environment:

```
FROM ubuntu:12.04
RUN apt-get -y update
RUN apt-get -y upgrade
RUN apt-get -y install \
	lua5.1 liblua5.1-dev munge \
	libmunge-dev \
	libtool automake autoconf \
        aspell wget g++ make git uuid-dev \
	luarocks
RUN useradd -m ubuntu
RUN for url in \
	https://download.libsodium.org/libsodium/releases/libsodium-1.0.0.tar.gz \
	http://download.zeromq.org/zeromq-4.1.0-rc1.tar.gz \
        https://s3.amazonaws.com/json-c_releases/releases/json-c-0.11.tar.gz \
	http://download.zeromq.org/czmq-3.0.0-rc1.tar.gz ; do \
		f=`basename $url .tar.gz` && \
		wget ${url} && \
		tar xvfz ${f}.tar.gz && \
		(cd $(basename $f -rc1) && ./configure && make install); \
	done

RUN wget http://bitop.luajit.org/download/LuaBitOp-1.0.2.tar.gz && \
      tar xvfz LuaBitOp-1.0.2.tar.gz && \
      cd LuaBitOp-1.0.2 && \
      make INCLUDES=-I/usr/include/lua5.1 && \
      make INSTALL="install -p -D -v " install && \
      cp /usr/local/lib/lua/5.1/bit.so /usr/local/lib/lua/5.1/bit32.so
RUN luarocks install luaposix

RUN git clone https://github.com/grondo/lua-hostlist && \
     cd lua-hostlist && \
     make LUA_VER=5.1 && \
     make install LUA_VER=5.1
RUN apt-get -y install vim strace
RUN ldconfig
USER ubuntu
WORKDIR /home/ubuntu
RUN git clone --depth=50 --branch=master https://github.com/flux-framework/flux-core && cd flux-core && ./autogen.sh && ./configure && make clean
```

**Comment by grondo** [comment]
Nicely done, looks like this PR is passing now.
Was there anymore TODO here besides fixing parallel build? IMO the work here is good enough to merge now and fixup any other items later.

**Comment by garlick** [comment]
Yes looks good!

**Comment by trws** [comment]
Thanks for the review, and the dockerfile, may look at getting boot2docker working... anyway, I have one more update for this that splits the exports such that the flux_* symbols only exist in the libflux-core library, should help make sure that at least the API symbols are only included in the binaries once.  I'll put in another pull request for that momentarily.

**Pull request merged**
