### PR TITLE
Change flux start to only exec broker if --size is not specified

### PR DESCRIPTION
**Pull request by chu11**
Per issue #834

### CODE REVIEW

**Comment by chu11** [comment]
For discussion: Since ```--size``` only launches a local instance, should the option name be changed to make that more clear?  Looking at ```flux-start```'s history, the ```--size``` option was brought along from a long time ago when slurm stuff was originally inside ```flux-start```.

This would be a pretty sizable change, probably effecting massive amount of documentation and scripts.

**Comment by garlick** [comment]
Looks good.

One idea: maybe these tests should be run in PMI mode too?
```sh
test_expect_success 'flux-start passes through errors from command' "
	test_must_fail flux start /bin/false
"
test_expect_success 'flux-start passes exit code due to signal' "
	test_expect_code 130 flux start 'kill -INT \$\$'
"
```

> This would be a pretty sizable change, probably effecting massive amount of documentation and scripts.

Yeah, I'm thinking probably this PR should close #834 and we should open another issue to cover your and @morrone's usability observations with `flux-start`.

**Comment by chu11** [comment]
I wanted to limit "permutation" of exec vs pmi tests as we could probably do it everywhere, but I think some additional tests where you indicated are warranted.  I'll update and re-push.  I'll open a new ticket on the ```--size``` option too.

**Comment by garlick** [comment]
Thanks!  Merging.

**Pull request merged**
