### PR TITLE
pull in json-c

### PR DESCRIPTION
**Pull request by garlick**
This PR is the missing piece that would have allowed #319, an attempt to convert part of the project to the [jansson](http://www.digip.org/jansson/) JSON library, to have been completed.  It pulls in a copy of the json-c library and renames all of its public symbols to have have a `json_c_` prefix.  The library is built as part of `libflux-internal.la`.  Any part of flux-core can now dump json-c simply by dropping its include of `src/common/libjson-c/json.h` or `src/common/libutil/shortjson.h`.

If this approach is acceptable, next I'd like to revisit bringing back the really cool formatted rpc functions that were parked in #319.

Note to flux-sched: this doesn't affect external interfaces, and you can still track `shortjson.h` as the only change to it here is to include json.h via a different path.

Note on tests: I did add a small TAP test here but I did not pull in the tests that ship with json-c.  We could do that but it will take some work and I didn't feel it was justified here, given that json-c releases are pretty well tested.

### CODE REVIEW

**Comment by lipari** [comment]
> Note to flux-sched: this doesn't affect external interfaces, and you can still track shortjson.h as the only change to it here is to include json.h via a different path.

@garlick, this sounds like something sched is going to want to adopt if we are to maintain as much consistency with the flux-core as possible.  Do you agree?

**Comment by garlick** [comment]
> this sounds like something sched is going to want to adopt if we are to maintain as much consistency with the flux-core as possible. Do you agree?

Pulling in json-c was kind of a desperation move to control its namespace and I hope sched won't need that, certainly not until you want to migrate part of sched to jansson.

The specific problems are discussed in #319 where libflux was converted to use jansson.  It's a dynamic library externally where the usual transitive dep rules apply, but internally libtool through its wrapper scripts arranges for anything that links against libflux to pick up its dependencies, e.g. jansson.  We then found that the kvs module was mixing jansson and json-c APIs where they overlapped and caused segfaults.

**Comment by garlick** [comment]
I should add, we already got rid of `json_object &` in all the public flux-core interfaces, so flux-sched and flux-core can use completely different JSON implementations without conflict.  Where JSON is passed, it is passed as a string (whether that be API parameter or a message).

**Comment by lipari** [comment]
Ok thanks.  If more and more of flux-core starts to convert to jansson, then I would want to convert all of flux-sched as well.  There's no point in forcing developers to work in two different json c libraries when they could work more efficiently using just one.

**Comment by garlick** [comment]
> if more and more of flux-core starts to convert to jansson, then I would want to convert all of flux-sched as well.  There's no point in forcing developers to work in two different json c libraries when they could work more efficiently using just one.

Although that sounds like a supportable position, I'm personally not hard over on using one implementation throughout the project, if different situations call for a different one, e.g. see pr #833.

**Comment by garlick** [comment]
Hmm, possibly there is something wrong here.  It seems hard to get all of the travis-ci tests to run through without hitting some problem in a seemingly random spot.

Here's a segfault in the lua kvs test:
```
ok 125 - but key value has been updated
1..125
2016-10-07T16:08:22.091405Z broker.err[0]: Run level 2 Segmentation fault (rc=139) 1.9s
flux-start: 0 (pid 106093) exited with rc=139 (Segmentation fault)
FAIL: lua/t1002-kvs.t
```
Another travis-ci test hung in the crontab tests.

I did some poking with valgrind to see if any obvious memory problems popped up - nothing found.

**Comment by garlick** [comment]
Or it could just be travis this morning.  One of my builds hung in configure - pretty sure that's not a problem introduced here.

**Comment by garlick** [comment]
I was thinking this PR doesn't really do anything _useful_ and so brought over the `flux_rpcf()`, `flux_rpc_getf()` functions from #319.  In retrospect, maybe those belong in another PR?

**Comment by grondo** [comment]
FWIW, since the `getf()` functions require jansson to work, I don't mind them being part of this PR. They look really useful!

**Comment by garlick** [comment]
This is rebased on current master, and I weaned libflux off json-c.

**Comment by garlick** [comment]
I'd like to propose this as a merge candidate.

As discussed in our project meeting today, there is one caveat here: the new RPC functions _can_ expose `json_t` objects through the varargs interface, e.g. this example from `libflux/attr.c`:
```C
    flux_rpc_t *r;
    json_t *array;
    if (!(r = flux_rpc (ctx->h, "cmb.attrlist", NULL, FLUX_NODEID_ANY, 0)))
        goto done;
    if (flux_rpc_getf (r, NULL, "{s:o}", "names", &array) < 0)
        goto done;
```
However, this doesn't require external API users to use jansson (include it or link with it) if they are willing to avoid the `o` format specifier.  It's actually pretty useful in places where it's OK to adopt jansson, for example all over flux-core.  The fact that the `json_t` object remains owned by the `flux_rpc_t` reduces the potential for JSON leaks, especially on error paths, and generally results in more compact code.

I've convinced myself that the pragmatic benefits of this PR outweigh the slight backsliding on API design principles. Any objections?

**Comment by grondo** [comment]
> I've convinced myself that the pragmatic benefits of this PR outweigh the slight backsliding on API design principles. Any objections?

I think this seems fine, and since the format specifier to pull a `json_t` out of an rpc will be *very* useful in flux internals I think you are right that it seems worth it. This is going to remove *a lot* of annoying boilerplate code in rpc handlers.

Some quick questions, I'm assuming it is ok to call `flux_rpc_getf()` multiple times on the same `rpc_t`, correct?

In your example above
```C
if (flux_rpc_getf (r, NULL, "{s:o}", "names", &array) < 0)
        goto done;
```
Does caller add a reference to the `json_t` array, or does `rpc_t` still own the memory?

**Comment by garlick** [comment]
> I'm assuming it is ok to call flux_rpc_getf() multiple times on the same rpc_t, correct?

No, because the `flux_rpc_t` was designed to also be used with `flux_rpc_multi()` where each `flux_rpc_get()` would fetch the next response.  That is a bit annoying - should we try to address that?  Maybe add an explicit call to invalidate the current response before getting the next one in the multi case?

> Does caller add a reference to the json_t array, or does rpc_t still own the memory?

The `flux_rpc_t` still owns the memory.

**Comment by grondo** [comment]
> should we try to address that? Maybe add an explicit call to invalidate the current response before getting the next one in the multi case?

Yeah, I'm thinking that will trip users of the API up -- it may not be practical or even good programming style to always call `flux_rpc_getf()` only once per rpc object (e.g. for anything but the most trivial of messages)

**Comment by garlick** [comment]
Just pushed a change that allows `flux_rpc_get()` to be called as many times as you like on a `flux_rpc_t`.  The multi-RPC usage changes to:
```C
do {
    flux_rpc_get (rpc, ...);
} while flux_rpc_next (rpc) == 0);
```
from
```C
while (!flux_rpc_completed (rpc)) {
    flux_rpc_get (rpc, ...)
}
```

**Comment by grondo** [comment]
Oh I like it!

**Comment by garlick** [comment]
I think this might be near to a merge candidate.  It's rebased on current master, and in addition to the change to flux_rpc suggested by @grondo, I dropped the `nodeid` argument from `flux_rpc_get()` and added a `flux_rpc_get_nodeid()` function for the relatively few places that this is useful.

**Comment by grondo** [comment]
Great! I think this is really nice and should go in after Travis is green. I think any more discussion or tweaks could be future PRs (not that I can think of any at this time)

**Comment by grondo** [comment]
Ok, @garlick. Nothing else to add here? I think I'll merge this so I can move forward with rebasing my WIP.

**Comment by garlick** [comment]
Works for me!  Thanks.

**Pull request merged**
