### PR TITLE
finish removing json_object from libflux API

### PR DESCRIPTION
**Pull request by garlick**
This is a rework of the PR #204 with these changes
* rebased on current master
* Completely new RPC interface based on `flux_rpc_t` as discussed.  I think it turned out well.
* Added a new reactor interface needed for `_then()` callback registration.
* Partial fix to issue #209, `flux_recvmsg_match()` sleeping when `nonblock` true.
* Tests updated for new RPC interface

**request** (no change)
```
int flux_request_decode (zmsg_t *zmsg, const char **topic,
                         const char **json_str);
zmsg_t *flux_request_encode (const char *topic, const char *json_str);

int flux_request_send (flux_t h, uint32_t *matchtag, zmsg_t **zmsg);
int flux_request_sendto (flux_t h, uint32_t *matchtag, zmsg_t **zmsg,
                         uint32_t nodeid);
zmsg_t *flux_request_recv (flux_t h, bool nonblock);
```

**response** (no change)
```
int flux_response_decode (zmsg_t *zmsg, const char **topic,
                          const char **json_str);
zmsg_t *flux_response_encode_ok (zmsg_t *request, const char *json_str);
zmsg_t *flux_response_encode_err (zmsg_t *request, int errnum);
zmsg_t *flux_response_encode (const char *topic, int errnum,
                              const char *json_str);

int flux_response_send (flux_t h, zmsg_t **zmsg);
zmsg_t *flux_response_recv (flux_t h, uint32_t matchtag, bool nonblock);
```

**rpc** (_New_ and _Improved!_)
```
typedef struct flux_rpc_struct *flux_rpc_t;
typedef void (*flux_then_f)(flux_rpc_t rpc, void *arg);

flux_rpc_t flux_rpc (flux_t h, const char *topic, const char *json_str,
                     uint32_t nodeid, int flags);
void flux_rpc_destroy (flux_rpc_t rpc);

bool flux_rpc_check (flux_rpc_t rpc);
int flux_rpc_get (flux_rpc_t rpc, uint32_t *nodeid, const char **json_str);

int flux_rpc_then (flux_rpc_t rpc, flux_then_f cb, void *arg);
```
The "multrpc" Interface which is now less special; `flux_rpc_t` is used to retrieve results as above.  We need a special hook to know when all the responses have been received.
```
flux_rpc_t flux_multrpc (flux_t h, const char *topic, const char *json_str,
                         const char *nodeset, int flags);
bool flux_rpc_completed (flux_rpc_t rpc);
```

### CODE REVIEW

**Comment by garlick** [comment]
I should have said I posted this for review not necessarily for merging.

Here are some comments:
* Possibly the `flux_request_*` operations could be eliminated from the public API if we added a `FLUX_RPC_NORESPONSE` flag to `flux_rpc()`?
*  `flux_rpc_get()` does not free response messages; that is deferred until `flux_rpc_destroy()` so that `_get()` can return zero-copy json strings that remain valid for the RPC lifetime.  It seems like a good idea to provide a function to free the last response (invalidating the json string), mainly for `flux_multrpc()` which potentially could pile up a lot of response message inside `flux_rpc_t`.  Thoughts?  Name?
* @grondo already commented on the `flux_response_*()` functions and I haven't addressed that.  Should we maybe provide a separate object similar to `flux_rpc_t`  for the other end of an rpc, like
```
typedef struct flux_svc_struct *flux_svc_t;
flux_svc_t flux_svc_create (flux_t h, zmsg_t **zmsg);  // build flux_svc_t from request
void flux_svc_destroy (flux_svc_t svc); // sends response, if any
int flux_svc_get_payload (flux_svc_t svc, const char **json_str);   // get request payload
int flux_svc_get_sender (flux_svc_t svc, const char **uuid); // get sender uuid
int flux_svc_set_errnum (flux_svc_t svc, int errnum);  // set response errnum
int flux_svc_set_payload (flux_svc_t svc, const char *json_str);  // set response payload
```

**Comment by garlick** [comment]
On freeing the last `flux_rpc_get()` response message and invalidating the last-returned json string, maybe the next `_get()` should just do that automatically?

**Comment by grondo** [comment]
I really like this new rpc interface.

Quick comments, though I'm not done fully digesting everything here:

 * On `flux_rpc_get()`, perhaps a name like `flux_rpc_pop()` or `_shift()` would make it clear most recently returned response is to be freed?
 * For `flux_svc_t`, I'm not sure why, but I don't like a function called `destroy()` that sends a response, though I totally get that doing send & destroy in a single call will be really convenient
 * I also don't really feel there is quite as compelling an argument for a separate `flux_svc_t` interface as there is for the rpc object. Perhaps we could discuss that one further? (It would be more compelling if the `svc` end was used to create a kind of connection over which multiple request/response messages might flow.
* You probably already answered this earlier, but did we ever discuss why `flux_rpc()` doesn't take a nodeset arg? Then it could handle single rank rpc, multi-rank rpc, and rpc to "all" in a single interface? It seems like `flux_rpc_completed` would apply to a singleton rpc as well? (Sorry if this is a naive question -- coming off several days of not looking at this.

**Comment by garlick** [comment]
On combining `_rpc()` and `_multrpc()`, what held me back was the integer nodeid could be `FLUX_NODEID_UPSTREAM` or `FLUX_NODEID_ANY` in addition to an integer rank.  I guess if we used strings for those as well, e.g. "upstream", "any"?

**Comment by grondo** [comment]
One other idea (not saying it is any better/worse than converting `flux_rpc` to use strings) would be to change prototype for `flux_rpc()` to something like:
```C
flux_rpc_t flux_rpc (flux_t h, const char *topic, const char *json_str, 
        uint32_t nodeid, int flags, ...);
```
Where optional vararg is a `const char *nodeset` if `nodeid` is `FLUX_NODEID_MULTIPLE`.

The main benefit here, if any, is that you don't have to change current callers of `flux_rpc()`
(errr, though I guess you would have to anyway), and you avoid string compare for the common cases of `FLUX_NODEID_ANY` or `FLUX_NODEID_UPSTREAM`
(Unless I've made a mistake in my thinking)

**Comment by garlick** [comment]
Hmm, or
```C
enum {
    FLUX_RPC_NODEID = 2, // arg is integer nodeid
    FLUX_RPC_NODESET = 3, // arg is string nodeset
    FLUX_RPC_ANY = 4, // no arg, send to FLUX_NODEID_ANY
    FLUX_RPC_ALL = 5, // no arg, send to all ranks
    FLUX_RPC_UPSTREAM = 6, // no arg, send to FLUX_NODEID_UPSTREAM
};
flux_rpc_t flux_rpc (flux_t h, const char *topic, const char *json_str, int flags, ...)
```

**Comment by garlick** [comment]
I think actually a `flux_rpc_get()` that, in the case of multiple nodes, destroys any previously gotten request sort of works for me.  Can we leave it as is and maybe give it another look on the next PR iteration?  Quite easy to change.

**Comment by garlick** [comment]
Will the varargs interface proposed above create a nuisance for binding authors?

**Comment by grondo** [comment]
@garlick, I don't think varargs creates an issue for bindings, but might want to hear from @trws on that.
Also, I'm fine with `flux_rpc_get()` for now, thinking of `get` as a synonym for `next` kind of works for me too.

**Comment by trws** [comment]
Since varargs are pretty ubiquitous, most FFIs have a way to cope with them, but its not always cleanly.  Actually Go is the only example I can think of that just plain doesn't have a varargs adapter at all, they expect you to write cgo/C wrapper functions for any function that takes varargs because the Go calling convention is pretty severely incompatible with C-style varargs.  Even to interface with C wrappers you would want two versions, a `...` version and a `va_args` version.  

Personally, I would keep two versions, a simple and a complex, and amend the interface to take a void pointer that, depending on the flag, is interpreted as a string, or potentially a pre-built bitmap from a function that doesn't exist yet or, etc.

Something like this:

```c
flux_rpc_t flux_rpc (flux_t h, const char *topic, const char *json_str, 
        uint32_t nodeid, int flags);
flux_rpc_t flux_rpc_multi (flux_t h, const char *topic, const char *json_str, 
        uint32_t nodeid, int flags, const void *restrict node_spec);
```

Alternatively, you could go the hwloc/numactl route and just have a single version that takes a `flux_nodeset_t` object as an argument that is created by a separate call.

**Comment by garlick** [comment]
Are we thinking the Go linkage pain is enough of a reason to avoid varargs in the public API?

If that were not a big concern, I admit I like the combined varargs function that makes both `nodeid` and `nodeset` arguments optional the best.  (though we would probably need to expose a `va_list` variant to facilitate wrapping as you suggest @trws).

Come to think of it, in that proposal, `FLUX_NODEID_ANY` could be implied if no flags are provided, leaving for the common case the terse: `flux_rpc (h, topic, json_str, 0)`

**Comment by trws** [comment]
I wouldn't worry about Go all that much, but I don't really see varargs 
as being superior to a void pointer in this case.  Specifically the 
interface is only meant to accept one extra argument, it just happens to 
be of an indeterminate type of size `sizeof(ptr)` or smaller.  Making it 
vararg for just that seems like overkill.  Perhaps its just me, but 
adding the possibility of runtime stack smashing that's inherent in the 
varargs calling convention is something I like to avoid whenever 
feasible.

**Comment by grondo** [comment]
@trws makes some good points, I think.

Right now RPC takes 0 or 1 args, but if in the future there might be a `FLUX_RPC_SOMETHING` option to take more than one arg then perhaps that would recommend the varargs interface more fully. We have used 

For now I really do like combining `flux_rpc` and `flux_rpc_multi` into a single call, but I have to say I'm not sure it is worth the tradeoffs giving the arguments of @trws. (So, sorry, no help here.)

**Comment by trws** [comment]
There are also the middle ground options above, or a struct/union type for that matter.  This could work, and would remain extensible.  Admittedly it isn't as terse, but it's about as terse as C gets safely.

```c
enum {
    FLUX_RPC_NODEID = 2, // arg is integer nodeid
    FLUX_RPC_NODESET = 3, // arg is string nodeset
    FLUX_RPC_NODEBITS = 7, // arg is bitfield nodeset
    FLUX_RPC_ANY = 4, // no arg, send to FLUX_NODEID_ANY
    FLUX_RPC_ALL = 5, // no arg, send to all ranks
    FLUX_RPC_UPSTREAM = 6, // no arg, send to FLUX_NODEID_UPSTREAM
};
typedef struct{
  union{
    unsigned int nodeid;
    const char *restrict nodeset;
    flux_bitset_t *bitset;
  };
};
flux_rpc_t flux_rpc (flux_t h, const char *topic, const char *json_str, 
        int flags, flux_nodeset_t nodes);
```

Usage then becomes:
```c
//common any case
flux_rpc (h, topic, json_str, 0, {0})
//single node
flux_rpc (h, topic, json_str, FLUX_RPC_NODEID, {.nodeid = 5})
//multi-node string
flux_rpc (h, topic, json_str, FLUX_RPC_NODESET, {.nodeset = "5-47"})
//etc.
```

**Comment by grondo** [comment]
@trws, that is interesting and pretty cool! However, is this extensible without breaking API/ABI?

**Comment by trws** [comment]
@grondo: It's extensible without breaking API backwards compatibility as long as no existing fields are removed.  ABI compatibility requires that the size of the union stay the same, and if structures are employed that the order their existing fields are in does not change. Any other change would be invisible.  Changing it to a pointer would avoid the ABI issue, but the initializer list syntax creates an r-value that doesn't allow for taking a reference, so everything would have to be bound to an l-value before the call.  I suppose its worth mentioning that this also requires a C99 compliant compiler.
All trade-offs I suppose.

Writing the second to last sentence just reminded me, if we wanted to get generic with it, we could do this the C11 way.

```c
flux_rpc_t flux_rpc_nodeid (flux_t h, const char *topic, const char *json_str, 
                                            int flags, int id); 
flux_rpc_t flux_rpc_nodeset (flux_t h, const char *topic, const char *json_str, 
                                              int flags, const char*restrict nodeset);
#define flux_rpc(H, T, J, F, X) _Generic((X), \
         int: flux_rpc_nodeid, \
const int: flux_rpc_nodeid \
    char *: flux_rpc_nodeset \
const char *: flux_rpc_nodeset \
    )(H, T, J, F, X)

//usage
//common any case
flux_rpc (h, topic, json_str, 0, 0)
//single node
flux_rpc (h, topic, json_str, 0, 5)
//multi-node string
flux_rpc (h, topic, json_str, 0, "5-47")
//upstream
flux_rpc (h, topic, json_str, FLUX_NODEID_UPSTREAM, 0)
```

This does require C11 though, and sometimes causes issues with temporary array-typed values that aren't actually pointer types when passed.

**Comment by garlick** [comment]
I'm less than excited about introducing off-the-beaten-path C interfaces (I was going to say "exotic C" but that would be an oxymoron :-) if we can't drop the last arg in the common (no flags) case.  It seems like the returns are low on further tweaking here.

I will rename `flux_multrpc()` to `flux_rpc_multi()` as @trws suggested.

I think with the enhanced `flux_rpc()` interfaces, we can pare down the request/response functions.  I'll look at that and see what can be done about the awkward `flux_response_encode_ok/err()` interface that would be called heavily from comms module message handlers.  It'd be nice to construct interfaces that lead to a nice structure in those handlers.  Some of that is dictated by the way the reactor calls these message handlers; for example, an undestroyed request is assumed to be unhandled and is answered with ENOSYS in the reactor code.  That whole interface needs a review.

**Comment by grondo** [comment]
Just to throw my $0.02 I was at the same conclusion as you @garlick.

I also agree that the name `flux_rpc_multi()` is an improvement over `multrpc`

Sorry if I took us off-track with my previous comments!

**Comment by garlick** [comment]
Closing this PR and opening another.

**Pull request closed without merging**
