### PR TITLE
job-list: misc cleanup

### PR DESCRIPTION
**Pull request by chu11**
This is some misc cleanup / doc updates peeled off from another branch.  It also include cleanup in `flux-job`, testsuite, and `flux-jobs(1)`.

### CODE REVIEW

**Comment by chu11** [comment]
re-pushed with an extra commit from something I just noticed in the JobList class.  I cannot find evidence that we've ever accepted "all" as a filter name.  And "all" in the code only sets pending and running, not pending, running, and inactive.  So it doesn't make much sense.  I suspect its some left over code from development of the class?

Perhaps there is something I just can't remember or some use case I can't find.   But there's a cleanup commit in here for the time being.

**Review by garlick — APPROVED** [review]
This all looks good to me.

There was one (slightly fascist) misspelling in the add_filter commit message: "fitler".

**Comment by chu11** [comment]
Thanks.  I would like a double check on the last commit from @grondo.  https://github.com/flux-framework/flux-core/pull/5144/commits/cbc306ba58ea95fd9e7460b1625c2288ec59bab2  Just to make sure I'm not forgetting something or its used in some way I can't find.

**Review by grondo — APPROVED** [review]
Yeah, that looks good to me!

**Comment by grondo** [comment]
@chu11 I'm going to set MWP here in a bit unless I hear otherwise, we're trying to see if this mergify issue is affecting all PRs our just some...

**Comment by grondo** [comment]
Ok, we might have to ask the folks at mergify :-(

**Comment by chu11** [comment]
https://github.com/Mergifyio rebase

**Comment by chu11** [comment]
https://github.com/Mergifyio rebase

**Comment by grondo** [comment]
This is approved with MWP so I'll merge since mergify still now working.

**Pull request merged**
