### PR TITLE
experimental: add -o nokz option for wreck jobs

### PR DESCRIPTION
**Pull request by grondo**
This PR adds an option `-o nokz` for wreck jobs which results in the use of direct messages for stdout and stderr instead of using kz streams to store the output in the kvs.

When the "nokz" option is enabled, the io multiplexer will register a service for either `stdout` or `stderr`, or both, instead of watching kz streams for each task, and `wrexecd` will forward message-based i/o to this service, addressed to the service name and rank encoded in a new `ioservice` kvs key associated with the job.

If `--output` or `--error` is also supplied then the corresponding services will be registered by the first `wrexecd` for the job (i.e. the same `output.lua` plugin that handles output files now, but instead of watching kz streams, the plugin will handle incoming messages)

Unfortunately, this isn't yet a complete solution, as `nokz` option for jobs submitted with `flux submit` or with wreckrun using the `-d` option will end up dropping all output. For now, `flux submit -o nokz` is an error without also supplying an output file. We could also make `-o nokz` for "batch" jobs imply `-o job-{{id}}.out` or similar. We could also make `nokz` not applicable to `flux submit` jobs (ignore the option) and instead default them to `stdio-delay-commit`.

I also did not  make `nokz` the default yet until above problems are solved. The option can be set globally for an instance with `flux wreck setopt nokz`. To enable it "by default" then we could add this command to the default `rc1`.

 It may be that the current approach needs a rethink, but I'm not sure what we should do/have time for before the next release. I'm able to work a little bit, but slow typing for now...

### CODE REVIEW

**Comment by garlick** [comment]
I'll poke at this today.

@trws, if you have a moment, could you comment on the caveats @grondo mentions above, and give us some thoughts on what you would like us to steer towards for the release?

**Comment by trws** [comment]
Thanks a ton for working on this @grondo, I have some questions but this sounds like exactly what I was hoping for.  I hope you’re recovering well by the way, feel better!

If I’m understanding correctly:

1. Interactive jobs with -o nokz work fine
2. Jobs submitted with submit or wreckrun -d  need somewhere to dump their output (makes sense) so either a file needs to be specified or the output is dropped
3. -o nokz could reasonably replace the kz-based -o option for file output given a file

If that’s all right, and I’ll do some quick tests to see how things behave with the target workload shortly, I’d request that we make nokz the default, and for a sync jobs output to something like ‘flux-<jobid>.out/err’ unless the user specifies a file or provides an option to use KZ.  That would give us behavior much like slurm provides IIRC.  It may also be worth considering an option that uses nokz to gather output, then commits the full output into a kz stream at the end of the job for users that want to be able to use attach to inspect what happened after the fact, but what’s already here sounds like it should completely solve the splash issues.  Great stuff!

**Comment by grondo** [comment]
@trws, yes, all correct except:

> -o nokz could reasonably replace the kz-based -o option for file output given a file

In the current PR, `-o nokz -O outfile` works and bypasses kz. (Now that I reread your statement, though, perhaps that is what you meant.

My other worry, of course, is that since this is a big change and will become the default, there may be some race conditions or corner cases that aren't handled.

For example, I can't remember what the output plugin does for output files that already exist. With Slurm there is one global set of monotonically increasing jobids, so slurm-$id.out works well. For Flux, each instance restarts at 1, so there will potentially be a lot of overwritten output files, or errors...

I can look into these things once we figure out what behavior should be.

**Comment by trws** [comment]
That was kinda what I was thinking as an add on.  You make a good point about jobid conflicts, maybe it would make sense to add on something unlikely to be replicated by default, like flux-{jobid}-{receiver-pid} or maybe the flux-uri basename or some such and put the filenames on stout and/or in a known kvs key?


---
Sent from Workspace ONE Boxer<https://whatisworkspaceone.com/boxer>

On December 18, 2018 at 9:07:32 AM PST, Mark Grondona <notifications@github.com> wrote:

BTW, another approach for "submit" jobs and nokz would be to have the output plugin hold output in memory and then dump the output file as one key into the kvs, instead of by default writing to a file. This probably would not be too much work, though a bit of a kludge.

**Comment by trws** [comment]
Wow, the performance difference is just crazy.

/dev/null interactive:

```
~/flux/flux-core wreck-output-nokz* scogland@gent 10s
â¯ time ./src/cmd/flux start flux wreckrun  seq 1 100000 > /dev/null
sh: ldconfig: command not found
./src/cmd/flux start flux wreckrun seq 1 100000 > /dev/null  306.94s user 11.60s system 149% cpu 3:32.75 total

~/flux/flux-core wreck-output-nokz* scogland@gent 3m 33s
â¯ time ./src/cmd/flux start flux wreckrun -o nokz seq 1 100000 > /dev/null
sh: ldconfig: command not found
./src/cmd/flux start flux wreckrun -o nokz seq 1 100000 > /dev/null  0.81s user 0.39s system 71% cpu 1.669 total
```

Dropping that by half, using kz uses 12m of database, using nokz leaves it as the default 40k SQLite base database.  It’s so incredibly improved I’m kinda floored, it’s even visible to the eye how much faster it is watching attached output.

One thing I noticed, that I don’t think is a problem but is a difference, is that using -O/-E with nokz outputs only to the files, but without nokz it also outputs to the terminal.  I was actually surprised by the behavior without the nokz option, but either way.

**Comment by grondo** [comment]
> One thing I noticed, that I don’t think is a problem but is a difference, is that using -O/-E with nokz outputs only to the files, but without nokz it also outputs to the terminal. I was actually surprised by the behavior without the nokz option, but either way.

Yeah, that is due to the initial design of "wreck" job prototype, for which all job "state" is managed through the kvs, and `wreckrun` is only passively involved (after the initial job launch). Similarly, the "output" plugin is just passively monitoring output and copying it to where the user requested.

The message based output is a big change from the initial design, but given the way most people run their jobs, hopefully the difference in design vs new implementation won't cause any onerous issues (and given that wreck is going to be replaced soon, we can probably live with any caveats)

**Comment by trws** [comment]
That sounds really good @grondo.  I like the solution, should make it pretty easy to get after-the-fact attach working for these which would be cool.  Thanks for putting this together so fast!

By the way, I mentioned this to @garlick in person, but found another cool feature of this while doing some testing yesterday.  It turns out it pretty significantly improves the scalability of launching multiple tasks per broker (not completely sure why, some serialization in watcher setup in the kz version maybe?):

Some numbers for 5 brokers, all in seconds to run that many instances of /bin/true, so this is with no output (well, "\nEOF" I suppose):

| ranks/broker | regular | nokz |
| --- | --- | --- |
| 40 | 2.81 | 0.91 |
| 80 | 8.28 | 1.79 |
| 160 | 30.63 | 3.84 |

**Comment by grondo** [comment]
Ok, I added some sanity checks for `--output/--error=kvs://foo` and also updated the `flux-wreckrun` and `flux-submit` manpages.

**Comment by garlick** [comment]
Thanks @grondo!  What's left to do here prior to merging?

**Comment by grondo** [comment]
You could merge as is (after testing it out further of course, I didn't
have a chance to test with flux-sched yet), but "nokz" isn't the default.

A separate PR could add `flux wreck setopt nokz` to rc1 (this could be
overridden per job with `-o nokz=false`). Though, that is a huge change, so
I'm a bit worried...

**Comment by grondo** [comment]
Just rebased on current master, and made a change so that `flux-submit` writes stdout/err to `files.stdout` and `files.stderr` in the kvs instead of a single `output-file` by default for `nokz` jobs.

Also made a small change to `flux wreck attach` so that it dumps stdout and stderr output from `nokz` jobs *if* they are found in the default `files.stdout` and `files.stderr` keys.

**Comment by garlick** [comment]
I have this branch (including your most recent push) and flux-sched master installed on a test system.  When I start an instance (sched loaded) and run:
```
$ flux submit -onokz hostname
submit: Submitted jobid 1
$ flux wreck attach 1
$
```
I don't see any output.  KVS contains:
```
$ flux kvs dir -R
lwj.0.0.1.0.stdin -> lwj.0.0.1.input.files.stdin
lwj.0.0.1.R_lite = [{"children": {"core": "0"}, "node": "jimbo", "rank": 0}]
lwj.0.0.1.cmdline = ["hostname"]
lwj.0.0.1.complete-timelux wreck attach 1 = 1545419358.548033
lwj.0.0.1.completing-time = 1545419358.545980
lwj.0.0.1.create-time = 1545419358.5No output files02223
lwj.0.0.1.cwd = /home/garlick/grondo_tmp
lwj.0.0.1.environ = {"CCACHE_CPP2": "1", "DBUS_SESSION_BUS_ADDRESS": "unix:pa...
lwj.0.0.1.exit_status = {"count": 1, "entries": {"0": 0}, "max": 0, "min": 0,...
lwj.0.0.1.input.config = [{"dst": "*", "src": "stdin"}]
lwj.0.0.1.ioservice = {"stderr": {"name": "5cb4007c27e06fa3:err", "rank": 0},...
lwj.0.0.1.log.0.
lwj.0.0.1.ncores = 1
lwj.0.0.1.ngpus = 0
lwj.0.0.1.nnodes = 0
lwj.0.0.1.ntasks = 1
lwj.0.0.1.options = {"nokz": 1}
lwj.0.0.1.opts.tasks-per-node = 1
lwj.0.0.1.pmi.PMI_process_mapping = (vector,(0,1,1))
lwj.0.0.1.running-time = 1545419358.540197
lwj.0.0.1.starting-time = 1545419358.521515
lwj.0.0.1.state = complete
lwj.0.0.1.walltime = 0
lwj-complete.4.1 -> lwj.0.0.1
resource.hosts = jimbo
resource.hwloc.by_rank.0.Core = 12
resource.hwloc.by_rank.0.HostName = jimbo
resource.hwloc.by_rank.0.Machine = 1
resource.hwloc.by_rank.0.PU = 12
resource.hwloc.by_rank.0.Package = 2
resource.hwloc.loaded.0 = 1
resource.hwloc.xml.0 = <?xml version="1.0" encoding="UTF-8"?>...
```

**Comment by grondo** [comment]
I had to force push a fix for that same issue. Make sure you have the
latest.

If you do have the latest, I'll take a look at lunch. Sorry!

**Comment by grondo** [comment]
> If you do have the latest, I'll take a look at lunch. Sorry!

Oh, oops, I know what is wrong. I'll push a fix and hopefully somehow add a test.

**Comment by garlick** [comment]
So I just rebuilt the same code (I _think_ - it's v0.10.0-783-g40f7c756e) and submit produced:
```
lwj.0.0.2.0.stderr.000000 = {"data": "", "eof": true}
lwj.0.0.2.0.stdin -> lwj.0.0.2.input.files.stdin
lwj.0.0.2.0.stdout.000000 = {"data": "amltYm8K", "eof": false}
lwj.0.0.2.0.stdout.000001 = {"data": "", "eof": true}
```
and `flux wreck attach` worked.

The same run of hostname with `flux wreckrun` did not put output in the KVS.

**Comment by garlick** [comment]
@grondo just FYI I think our tag is likely going to be in the latter part of next week, so please don't feel obliged to fix this _now_.

**Comment by grondo** [comment]
Yeah, I made a dumb mistake and already have a "fix" (all of this is a bit kludgy).

I'll test with flux-sched first though...

**Comment by grondo** [comment]
Ok, fixed `flux-submit` with `-o nokz`. Attach will now nomically work in this scenario:
```
grondo@peep:/tmp/f.git$ flux submit -o nokz -n4 hostname 
submit: Submitted jobid 2
grondo@peep:/tmp/f.git$ flux wreck attach 2
peep
peep
peep
peep
```

**Comment by garlick** [comment]
LMK when you feel OK merging.  Maybe we can get this in now with the understanding that we will revisit before the release for discussion about the default I/O mode?  Then at least you won't need to keep rebasing this as we merge the remaining PR's.

**Comment by trws** [comment]
How does it wireup in the attach case? Is it pulling the result at the end, and always get the full output of the job, or something like tail -f if the job isn't done yet or..?

**Comment by grondo** [comment]
Yeah, attaching to running 'nokz' just exits immediately with no output since the `files.{stderr,stdout}` keys do not exist. To fix I'll have to augment the `attach` function to wait on the state key. I can work on that a bit later.

**Comment by trws** [comment]
I wouldn't let it hold up this PR.  We'll want some way to watch intermediate values at some point, but for our current users the majority of use by far is after the fact, so that sounds great.  Thanks again @grondo!

**Comment by grondo** [comment]
I pushed a fix for `flux wreck attach` which delays exit for `nokz` jobs until the job state is complete, then dumps ` files.stderr` and `files.stdout`. Still not perfect, but better than completely broken...

**Comment by garlick** [comment]
Just sanity checked this with sched and seems to work as advertised.  Nice!

Any further work pending in this PR @grondo, or is it OK to merge now?

**Comment by grondo** [comment]
Yeah, we can merge as is and figure out default behavior later

**Pull request merged**
