### PR TITLE
libflux/mrpc: drop the mrpc class

### PR DESCRIPTION
**Pull request by garlick**
This PR removes the outdated `flux_mrpc` class from the public API, and also internally.  It also removes support for "group matchtags".  This simplifies the code base and eliminates an outdated interface that might be an attractive nuisance for new users.  (It doesn't use futures, and it doesn't have any way to limit the amount of concurrency it initiates).

Besides removing all the mrpc functions, the following minor changes were made to the public api:
 - drop FLUX_MATCHTAG_GROUP flag
 - drop flags parameter from flux_matchtag_alloc()
 - drop flags parameter from flux_matchtag_avail()
 - drop flux_matchtag_group()
 - drop FLUX_MATCHTAG_GROUP_SHIFT constant
 - drop FLUX_MATCHTAG_GROUP_MASK constant

`flux-ping(1)` and `flux-module(1)` both had support for providing a "NODESET" target and running across a set of ranks.   For `flux-module`, I converted users to run `flux exec -r RANKS flux module ...`.  The `flux module list` output did have a nice "compressed" mode to show modules across the instance; this could be recreated if needed, but it was a lot of code for a little used feature, so I elected to remove it.

`flux ping` had a mode where it would ping muitiple ranks in parallel and show statistics on the RTT over the set.  That was neat but also little used I think.

PR's pending for flux-sched (which used `flux module load -r0` and `remove -r0` in a few places) and rfc6.

Edit: also this PR adds a --exclude option to `flux exec` to match functionality in `flux module CMD --exclude`.

### CODE REVIEW

**Comment by grondo** [comment]
One comment:

If this PR lands before our next tag, then this will require a corresponding new tag for flux-sched, since the corresponding removal of `flux module -r` won't be present in 0.8.

I don't necessarily oppose that approach, but just wanted to note it here for potential discussion.

**Comment by grondo** [comment]
>For flux-module, I converted users to run flux exec -r RANKS flux module .... The flux module list output did have a nice "compressed" mode to show modules across the instance; this could be recreated if needed, but it was a lot of code for a little used feature, so I elected to remove it.

I did think that `flux module list -r all` output was nice and informative.

Instead of replacing `flux module load -r all [MODULE]` with `flux exec flux module load [MODULE]`, did you consider replacing the internal use of `mrpc` with a for loop of regular rpcs with responses handled asynchronously? I worry slightly about the overhead of `flux exec flux module load` when loading a module across all ranks (though if that will become uncommon practice, maybe it isn't something to worry about)

However, it would let you keep `flux module list -r all` output.

**Comment by garlick** [comment]
It would be fairly easy to add back those options to the `load` and `remove` sub-commands if we think that's worth it, using regular RPC's and futures. I thought not, since it seems evident that the current strategy of loading all modules from rank 0 at instance startup isn't going to work on the system instance.  I think we'll want to have the rc scripts run on each rank independently, in which case the flux exec's will be replaced with conditional logic in the scripts.

One thought though:   adding a single rank `-r RANK` option to `load` and `store` would avoid breaking sched (thanks for pointing out the fact that this will force a sched tag when we include this in a release).

There was kind of a ridiculous amount of code to support the "compressed" `list` subcommand output. Seems like a job for a python tool?  The code already exists so it wouldn't be that hard to resurrect, but I was definitely having a "sheesh look at all this C code!" moment in there with the zlistx, zhash, and argz, just to combine some output.

**Comment by grondo** [comment]
Ah, good point about a Python use case...

**Comment by garlick** [comment]
OK, I added "legacy" support for `-r RANK` in the `load` and `remove` subcommands so this PR should no longer break older versions of sched.  Maybe that makes it feasible to merge this before our tag?

**Comment by grondo** [comment]
> Maybe that makes it feasible to merge this before our tag?

Yeah, sounds good.

> I thought not, since it seems evident that the current strategy of loading all modules from rank 0 at instance startup isn't going to work on the system instance. I think we'll want to have the rc scripts run on each rank independently, in which case the flux exec's will be replaced with conditional logic in the scripts.

Probably a question for a different issue, but is the plan to use the same strategy for non-system instances, e.g. `flux start -s` and instances started by an existing resource manager?

**Comment by garlick** [comment]
> Probably a question for a different issue, but is the plan to use the same strategy for non-system instances, e.g. flux start -s and instances started by an existing resource manager?

That's what I was thinking.  Open for discussion though!  I'll open an issue.

**Comment by grondo** [comment]
> OK, I added "legacy" support for -r RANK in the load and remove subcommands so this PR should no longer break older versions of sched. Maybe that makes it feasible to merge this before our tag?

Does the `-r RANK` option need to be added back to the manpage? Or is the option intentionally undocumented (which is fine with me, btw)

**Comment by garlick** [comment]
That was intentional, for better or worse.

**Pull request merged**
