### PR TITLE
travis-ci: Add more recent compilers, small fixes, and Caliper testing

### PR DESCRIPTION
**Pull request by grondo**
The main purpose of this PR was to get Caliper built and installed in Travis so we could at least get some sanity testing with `--enable-caliper`.

Caliper requires C++0x11 support and a pretty recent CMake, so along the way some other travis config had to be updated. In summary the total of what is done here is:

 * Add recent compilers to Travis environment gcc-4.9 and clang-3.8 via new APT sources
 * Switch to travis' `matrix.include` method for adding special case items to the build matrix. After everything, we're now up to 7 builds in the matrix, so we might have to try to consolidate a couple of them
 * Checkout and build recent enough version of Caliper to work with Flux
 * Add simple test for Flux with Caliper enabled as `t2007-caliper.t`
 * Other minor travis fixes along the way

This could also be a jumping off point for ASan and other sanitizers that need recent llvm compilers, though it does seem like we'd have to figure out how to mark the false positives first.

I'm also looking into adding automated release uploads via Travis, and will tack that on to the end of this PR unless @garlick has already done that.

### CODE REVIEW

**Comment by dongahn** [comment]
Nice @grondo! 

> This could also be a jumping off point for ASan and other sanitizers that need recent llvm compilers, though it does seem like we'd have to figure out how to mark the false positives first.

Yes, this seems the good foundation to have CI coverage for Sanitizer tools and we need to find ways to tackle false positives before being able to run make check in the CI. 

As a small first step, though, does it make sense we add simple `make` coverage (but not `make check`) at some point to ensure flux at least compiles and links with `--enable-sanitizer`?

**Comment by grondo** [comment]
for Sanitizer tools and we need to find
> As a small first step, though, does it make sense we add simple make
coverage (but not make check) at some point to ensure flux at least
compiles and links with --enable-sanitizer?

Yes, I could try coupling that with the cppcheck test

**Comment by garlick** [comment]
This is great.

> I'm also looking into adding automated release uploads via Travis, and will tack that on to the end of this PR unless @garlick has already done that.

Please feel free - I haven't even started on this.

**Comment by grondo** [comment]
@dongahn, I added a make only test with `--enable-sanitizer` after the `cppcheck`. Other "build-only" checks could go in there...

**Comment by dongahn** [comment]
@grondo: Awesome work! Thank you.

**Comment by dongahn** [comment]
> I'm also looking into adding automated release uploads via Travis, and will tack that on to the end of this PR unless @garlick has already done that.

Great. Once this is done, I will follow this pattern for sched!

**Comment by garlick** [comment]
Just scanned through these commits and it all looks good to me.  I think it's fairly essential that we at least build-check any conditionally compiled code we add to Flux!

**Comment by grondo** [comment]
Ok, I've rebased on current master and also added a first attempt at automated release uploads to GitHub on tags using the Travis `deploy` section.

There were many caveats along the way
 * GitHub API allows the Release "body" to be set at creation time, and Travis' `releases` deploy provider ostensibly allows this, however, I could not get a multiline body to work. The quoting seemed to confuse the Travis `dpl` script that does the deployment. Eventually I gave up and we now have a single line body which links to the tag-specific section of the NEWS file using a Markdown anchor.
 * It took many iterations to determine exactly how to limit the deploy to just a single job in the build matrix. Eventually I found that the current method `on.condition: $TRAVIS_JOB_NUMBER = $TRAVIS_BUILD_NUMBER.1` works, but I hope it isn't too brittle.
 * I tried to test out this scheme on a throwaway repo grondo/auto-release-testing, but there is no way to know for sure if this will work with flux-core until we try it out, so there may be some iteration when we try to tag.

**Comment by grondo** [comment]
Also, as part of this work, I reformatted the `NEWS` file to markdown, simplified the headings and changed the date format to something standard, and renamed it to `NEWS.md` for proper rendering on GitHub. This is what allows the anchors to work, though I'm pretty sure they are GitHub Flavored Markdown specific.

**Comment by garlick** [comment]
Sorry I didn't notice until just now that it looks like you've completed this work and are ready for a merge?  The only lingering thought I had was - it seems like autoconf gets unhappy when NEWS and other template files are missing?  Do we ened an empty NEWS file or am I misremembering this?

**Comment by grondo** [comment]
Hmm, yeah I *think* I left a NEWS file with one line suggesting to look at `NEWS.md` -- have to double check.

I'd also like to automate an update to the flux-framework.github.io pages, but that one could wait perhaps as this PR has taken too long already.

**Pull request merged**
