### PR TITLE
testsuite: fix spellcheck

### PR DESCRIPTION
**Pull request by garlick**
Problem: 'make check' does not fail on misspelled words.

Aspell doesn't like dictionary words that end in numbers.
The spellcheck script successfully runs an aspell "dry run" but
does so without the dictionary.  Later, when it checks for misspellings,
it is counting lines of output and ignores the return value of aspell.

Add the dictionary to the dry run so it fails there if there are problems.
Remove IPv4 and IPv6 from the dictionary.
Fix misc. spelling errors that are now caught and add some words to dictionary.

### CODE REVIEW

**Review by grondo — APPROVED** [review]
Thanks! Glad you caught this problem. There were some embarrassing typos in there!

**Comment by garlick** [comment]
Thanks!  re-pushed with a word that el7 didn't have.  I'll set MWP.

**Comment by grondo** [comment]
Looks like spellcheck may be failing in the `el7` build

```
 FAIL: spellcheck 103 - spell check man5/flux-config-access.rst failed
2022-02-01T16:35:46.5565533Z                 spellcheck:  FAIL: N=115 PASS=114 FAIL=1 SKIP=0 XPASS=0 XFAIL=0
2022-02-01T16:35:46.5566185Z ERROR: spellcheck - exited with status 1
```

Looks like maybe `multi` needs to be added to the dictionary for `el7`:
```
2022-02-01T16:35:47.0849684Z FAIL: spellcheck 103 - spell check man5/flux-config-access.rst failed
2022-02-01T16:35:47.0850075Z ---
2022-02-01T16:35:47.0850369Z flux-config-access.rst: multi
```

**Comment by grondo** [comment]
Great! (deleted comment you already handled)

**Comment by garlick** [comment]
Looks like the coverage test hit #4083 here too.  I'll restart.

**Pull request merged**
