### PR TITLE
python: add flake8/pylint checking

### PR DESCRIPTION
**Pull request by trws**
This is the start of the changes mentioned in #807 to have lints for the python bindings.  I've been using flake8 as a start, because it's less freaked out by the generated modules.  So far this reformats most of the bindings, but it's waiting for the merge of #799 rather than conflicting on code that's just going to be removed.  As soon as everything passes, I'll add another commit in here to run flake8 or pylint with make check if it's available.

### CODE REVIEW

**Comment by garlick** [comment]
The clang build failed here, which is an odd place that in any case would seem to have nothing to do with this PR.  The other builds were OK so I just restarted it.
```
not ok 71 - stat watcher invoked once for size chnage
#   Failed test 'stat watcher invoked once for size chnage'
#   at ../../../../src/common/libflux/test/reactor.c line 644.
ok 72 - stat watcher invoked once for nlink set to zero
ok 73 - destroying reactor then watcher doesn't segfault
1..73
# Looks like you failed 1 test of 73 run.
FAIL: test_reactor.t
===================
1 of 7 tests failed
===================
```

**Comment by garlick** [comment]
This PR is getting a bit crusty - if it's on hold, how about closing and resubmitting when it is ready for another pass?

**Comment by trws** [comment]
This should be complete now.  The amount of tweaking and refactoring required to make pylint pass the code was more significant than I would have expected, but it's in now, and should remain enforced by make check henceforth.  I selected pylint over flake8 because it's available by default on LC machines.

**Comment by garlick** [comment]
Great!

One suggestion: break out the "enforce" part to its own commit.  It gets lost in there with all the "refactor" changes.

Is it possible to install pylint in travis ?

**Comment by trws** [comment]
That makes sense, I'm off on something else for a bit but I'll be happy 
to rebase that out.  It should be pretty easy to add pylint on travis, 
will look into that when I do the rebase.

**Comment by garlick** [comment]
OK this looks good.  Thanks @trws!

**Pull request merged**
