### PR TITLE
job-info: split into two modules, job-info and job-list                                                                                     

### PR DESCRIPTION
**Pull request by chu11**
Per #3017, split the `job-info` module into `job-info` and `job-list`, with `job-list` handling all job listing related functions.          
                                                                                                                                            
This ended up being way easier than I had anticipated.  This was mostly a bunch of `git mv` calls and renaming/splitting the core data structures.  IIRC there were additional complexities that were refactored away when we went to job listing being done with the job-manager journal.  So the module split makes a lot of sense now since there's no dependency between the "lookup / watch" and "list" services.

After doing the split, cleaned up the testsuite, that's about it.

One thing I did not do, should we rename some of the Python classes like `JobInfo`?  Perhaps to `JobListInfo` or similar?  We obviously don't have to, but if we want to follow the module names .... ???  I went back and forth on it and ended up not doing it b/c I wasn't sure of the fallout as I think some users are already using the `JobInfo` class in scripts.

Another idea: does the `job-info` module deserve a rename?  It's only a "lookup" / "watch" module now.  `job-lookup`?  I don't think it's necessary, but just throwing it out there if someone was thinking about it.

### CODE REVIEW

**Comment by grondo** [comment]
> One thing I did not do, should we rename some of the Python classes like JobInfo? Perhaps to JobListInfo or similar? We obviously don't have to, but if we want to follow the module names 

I don't think we were necessarily following the module names with the Python class names. We can probably keep the class names the same since they still make sense for now (the JobInfo class contains information about jobs)

I don't have a strong opinion about renaming the job-info module itself. Seems like we could just keep that as well.

**Comment by chu11** [comment]
> I don't think we were necessarily following the module names with the Python class names. We can probably keep the class names the same since they still make sense for now (the JobInfo class contains information about jobs)
> I don't have a strong opinion about renaming the job-info module itself. Seems like we could just keep that as well.

This was my general feeling as well.

**Comment by garlick** [comment]
Teasing these two things apart seems like a really nice cleanup!

Should `job-info` be loaded on all ranks now?  It doesn't cache lookup data, so it should have a small memory footprint, and it is used by the job shell and flux job attach, so maybe that would help distribute some of rank 0's load a bit?

Aside: I wonder if there would be any benefit to keeping a small LRU cache of job ID => owner, to avoid the eventlog lookup on every access?  (Not sure if that would be helpful since lookups for different keys in the same job are typically batched in the same lookup request)

**Comment by grondo** [comment]
Nice work @chu11, and good ideas above @garlick.

I could easily try loading job-info on all ranks with the job throughput test and see if there is any measurable effect.

Also, your comment about using an LRU cache reminds me that we have `src/common/libutil/lru_cache.c`, which actually isn't used anywhere ATM, and should probably be removed, unless we want to use it in job-info.

**Comment by grondo** [comment]
I ran a test on fluke with size=372 (1 broker per core), and found a significant difference between `flux exec -r all flux job info ID jobspec` when job-info was only loaded on rank 0:
```
ƒ(s=372,d=0,builddir) grondo@fluke6:~/git/flux-core.git$ time flux exec -r all sh -c 'flux job info ƒem6x3YB jobspec >/dev/null'
real	0m1.371s
user	0m0.400s
sys	0m0.036s
ƒ(s=372,d=0,builddir) grondo@fluke6:~/git/flux-core.git$ time flux exec -r all sh -c 'flux job info ƒem6x3YB jobspec >/dev/null'
real	0m1.370s
user	0m0.388s
sys	0m0.043s
```

vs loaded on all ranks:
```
ƒ(s=372,d=0,builddir) grondo@fluke6:~/git/flux-core.git$ time flux exec -r all sh -c 'flux job info ƒem6x3YB jobspec >/dev/null'
real	0m0.749s
user	0m0.222s
sys	0m0.042s
ƒ(s=372,d=0,builddir) grondo@fluke6:~/git/flux-core.git$ time flux exec -r all sh -c 'flux job info ƒem6x3YB jobspec >/dev/null'
real	0m0.753s
user	0m0.214s
sys	0m0.043s
```

**Comment by grondo** [comment]
Oh wow, the impact of loading job-info across all ranks is *very* apparent when running this throughput test.
(Note: this is after rebasing this branch on current master, which contains the keepalive fix)

```
ƒ(s=93,d=0,builddir) grondo@fluke6:~/git/flux-core.git$ ./throughput.py -sxn 1024
  1024 jobs:   1024 submitted,      0 running, 1024 completed
number of jobs: 1024
script runtime: 36.620s
job runtime:    9.346 s
throughput:     109.6 job/s (script:  28.0 job/s)

ƒ(s=93,d=0,builddir) grondo@fluke6:~/git/flux-core.git$ flux exec -r 1-92 flux module load job-info
ƒ(s=93,d=0,builddir) grondo@fluke6:~/git/flux-core.git$ ./throughput.py -sxn 1024
  1024 jobs:   1024 submitted,      0 running, 1024 completed
number of jobs: 1024
script runtime: 9.860 s
job runtime:    9.681 s
throughput:     105.8 job/s (script: 103.9 job/s)
```

What should be noted here is the *actual* throughput vs the "script observed" throughput in each case. The actual throughput is measured in the test by subtracting the eventlog timestamp of the `submit` event of the first job from the eventlog timestamp of the `clean` event of the last job. The `script` throughput measures the amount of time the script was waiting for all jobs to complete.

When running this test without `job-info` on all ranks the system seems really bogged down and the dynamic status bar which shows the number of jobs in each state has long pauses. The script takes a long time to "catch up" to the system, so the perceived throughput is very low. 

After loading `job-info` across all ranks, this glitchy behavior in the script display is completely resolved, as evidenced by the script throughput being very close to the actual job throughput.

BTW, I have never seen actual job throughput numbers this high, even when running instances of this size where we should be able to run many many simultaneous jobs.

Really nice result!

**Comment by chu11** [comment]
> Should job-info be loaded on all ranks now? It doesn't cache lookup data, so it should have a small memory footprint, and it is used by the job shell and flux job attach, so maybe that would help distribute some of rank 0's load a bit?

Good idea @garlick, and thanks for looking at performance @grondo.  I'll update to load `job-info` on all ranks.

> Aside: I wonder if there would be any benefit to keeping a small LRU cache of job ID => owner, to avoid the eventlog lookup on every access? (Not sure if that would be helpful since lookups for different keys in the same job are typically batched in the same lookup request)

We've discussed this before.  Perhaps its worthwhile to experiment using the throughput tests @grondo lists above.

**Comment by grondo** [comment]
> Perhaps its worthwhile to experiment using the throughput tests @grondo lists above.

There's a copy of the script in [this gist](https://gist.github.com/grondo/681b850a42fc14d6242e3810b2edd29d), though I wonder if I should add it to `src/test`

**Comment by chu11** [comment]
rebased & re-pushed with an extra commit to load job-info on all ranks.  I'll experiment with an LRU in a follow up PR (issue #3521).

I didn't add any tests.  Basically I had tested to make sure that if I ran `flux exec -r RANKS flux job wait-event ...` there would be a watcher on each rank instead of 4 on the rank 0 rank.  I wasn't entirely sure if a unit test to verify what I setup in the rc script was really necessary.

**Comment by chu11** [comment]
@mergifyio rebase

**Comment by chu11** [comment]
@Mergifyio rebase

￼￼

**Review by garlick — APPROVED** [review]
Thanks!  Nice!

I don't see anything here that should prevent this from being merged.  Let's get it in and take it from there.

**Pull request merged**
