### PR TITLE
kvs: minor fixes/cleanup

### PR DESCRIPTION
**Pull request by chu11**
Minor things I fixed up on the way to fixing #1337.

### CODE REVIEW

**Comment by chu11** [comment]
not entirely sure why travis hasn't started this yet, is there a way to kick it?

**Comment by grondo** [comment]
You might have to make a minor change and re-push, unless the PR has already been built at least once at https://travis-ci.org/flux-framework/flux-core/pull_requests, in which case you can restart the build via the travis interface there.

**Comment by chu11** [comment]
did a tiny change and that seems to have done it.

**Comment by chu11** [comment]
hit a #1150, restarted build

**Comment by chu11** [comment]
then I hit #1077, restart build

**Comment by garlick** [comment]
Looks good, thanks!

**Pull request merged**
