### PR TITLE
resource-hwloc: reload event converted to RPC

### LINKED ISSUE #492: Can the callback for resource-hwloc.reload handle an error more gracefully?
This is just a minor enhancement request. I am trying to use fake hwloc load support with the resource-hwloc module to set up `flux-sched` tests. I mistakenly gave a wrong path to my fake xml file path, which then caused the entire flux instance to exit. It seems a simple path check within the reload handler can handle this case a bit more gracefully? 

```
cab670{dahn}51: flux event pub resource-hwloc.reload
cab670{dahn}52: [1449863488.699770] resource-hwloc.info[0]: loading hwloc from /nfs/tmp2/dahn/FLUXDEV/flux-sched/t/hwloc.0.out.xml
[1449863488.701141] resource-hwloc.info[2]: loading hwloc from /nfs/tmp2/dahn/FLUXDEV/flux-sched/t/hwloc.2.out.xml
[1449863488.701559] resource-hwloc.info[1]: loading hwloc from /nfs/tmp2/dahn/FLUXDEV/flux-sched/t/hwloc.1.out.xml
[1449863488.702388] resource-hwloc.info[3]: loading hwloc from /nfs/tmp2/dahn/FLUXDEV/flux-sched/t/hwloc.3.out.xml
[1449863488.720788] resource-hwloc.err[0]: resource.c:54:negative integer from:hwloc_topology_set_xml (ctx->topology, path):: No such file or directory
[1449863488.720767] resource-hwloc.err[1]: resource.c:54:negative integer from:hwloc_topology_set_xml (ctx->topology, path):: No such file or directory
[1449863488.720767] resource-hwloc.err[2]: resource.c:54:negative integer from:hwloc_topology_set_xml (ctx->topology, path):: No such file or directory
[1449863488.720788] resource-hwloc.err[3]: resource.c:54:negative integer from:hwloc_topology_set_xml (ctx->topology, path):: No such file or directory
flux-start: 0 (pid 85991) exited with rc=9
flux-start: 1 (pid 85992) exited with rc=9
flux-start: 2 (pid 85993) exited with rc=9
flux-start: 3 (pid 85998) exited with rc=9
```

### PR DESCRIPTION
**Pull request by trws**
The reload event has been converted into an RPC so that its results can be
waited upon, and so that reloading by path can report an error to the caller
while falling back to the initial context.  If the initial context load,
during startup, fails then it still kills the application currently.

fixes #492

### CODE REVIEW

**Comment by grondo** [comment]
This looks fine to me. @donganh, want to comment?

**Comment by dongahn** [comment]
This should allow my tests to avoid a race. 

However, I am a bit concerned about the use of `kvs_commit` in place of `kvs_fence.` Because this is now RPC-based, and I understand why `kvs_commit` is used: i.g., there is no guarantee that the ranks other than the target rank will participate in the same request.

But the common use case would be a bulk reload request (i.e., requests go to every rank via flux_rpc_multi) and I know when many ranks issue kvs_commit, there will be a scalability challenge. 

I am okay to use this as a stopgap but at some point we might need to revisit the use kvs_commit for large scale support. BTW, would mrpc allow you to use `kvs_fence`?

**Comment by trws** [comment]
If it becomes a problem, we can add an event version, or make sure that the initial load uses fence instead of commit.  I think the RPC version should always use commit, as it's a single point-to-point thing.

**Comment by dongahn** [comment]
@trws: I agree the pure RPC version should use `kvs_commit`. Perhaps we need some support within flux_rpc_multi which encodes the group and rpc instance info in the request so that the callback can use a more scalable mechanism like `kvs_fence`? Perhaps, this is what mrpc is for?

**Comment by trws** [comment]
rpc_multi is somewhat a multicast, it might be worthwhile to know that an RPC mechanism is being used that way, but it seems like something we would rather have in an actual collective of some kind.

**Comment by grondo** [comment]
Might want to take a look at mrpc. @garlick noted it was due for a redesign and now might be the time?

For now it sounds like this specific PR is ok to merge?

**Comment by dongahn** [comment]
Yes, this should be merged and I should use this mechanism to avoid a race. Thanks @trws and @grondo.

**Pull request merged**
