### PR TITLE
flux-start uses subprocess manager + zloop removal

### PR DESCRIPTION
**Pull request by garlick**
This PR ended up being a batch of cleanup only loosely related to the one substantial change, which is switching `flux-start` over to use libsubprocess, simplifying the code quite a bit.

In the process I removed zloop support from libzio and libsubprocess, and added the ability to register a zio and subprocess manager directly on a `flux_reactor_t` rather than requiring a `flux_t` handle.

Also, as discussed in #430, the `flux-zio` was stripped down and moved to `t/kz/kzutil`.

I wanted to get a bit of feedback on this especially from @grondo.  There are still some todos:
* I wasn't sure how to access FLUX_BUILD_DIR from `test/lua/t1003-iowatcher.t` so the path to kzutil is now improperly constructed.
* libsubprocess loop test needs to be converted from zloop to flux_reactor_t.
* add a sharness driver for kzutil

### CODE REVIEW

**Comment by grondo** [comment]
> I wasn't sure how to access FLUX_BUILD_DIR from test/lua/t1003-iowatcher.t so the path to kzutil is now improperly constructed.

Ah, good point. Similar to sharness there should be a way for lua scripts to determine the srcdir and builddir. This could easily be made a member of the `test` table, so `test.top_builddr` and `test.top_srcdir`? These values are hard-coded into the `fluxometer.lua` test driver by way of configure...

This seems like really good cleanup to me! I was wondering if it seems awkward to register a reactor with zio objects instead of the other way around, e.g. having watchers for zio objects. Also, were you still thinking of using "child watchers" for subprocesses instead of subprocess_reap_all()? That seemed like a great idea to me.

**Comment by grondo** [comment]
Something like this would give lua tests easy access to `top_builddir` and `top_srcdir`
```diff

```diff --git a/t/fluxometer.lua.in b/t/fluxometer.lua.in
index f737882..b90b42b 100644
--- a/t/fluxometer.lua.in
+++ b/t/fluxometer.lua.in
@@ -60,7 +60,10 @@ local posix = require 'flux.posix'
 require 'Test.More'
 
 ---------------------------------------------------------------------------
-local fluxTest = {}
+local fluxTest = {
+    top_srcdir = top_srcdir,
+    top_builddir = top_builddir
+}
 fluxTest.__index = fluxTest
 
 --  Options:

**Comment by garlick** [comment]
Thanks @grondo!  I'll pull your suggested lua change into this PR and also have another look at "zio watchers".

I do have the "child watchers" implemented but I was thinking of splitting that off into another PR?

**Comment by grondo** [comment]
> I do have the "child watchers" implemented but I was thinking of splitting that off into another PR?

Oh, that is fine with me.

> also have another look at "zio watchers".

Maybe since there is good improvement here that could also wait for a future PR? I was mainly wondering if the current usage felt awkward to you as it does to me.

**Comment by garlick** [comment]
A little bit :-)  When this was all part of the branch that became PR #431,  I felt there I was changing too much in one go, but it may be more tractable to consider that now.

**Comment by garlick** [comment]
Just pushed an update (still not done yet).
* Added `test.top_builddir`, `test.top_srcdir` to fluxometer as described above
* Fixed path to kzutil in iowatcher test
* Fixed a number of places where argz error handling was incorrect

**Comment by grondo** [comment]
Nice catch on the argz usage!

**Comment by garlick** [comment]
OK, I'm not really getting traction thinking about how to redo the zio interface as a watcher.  I'm inclined to table that one for a later date if that's OK @grondo.  On the other hand if you have a clear idea how to do it, please share and maybe it'll come together for me?

**Comment by grondo** [comment]
No, I never saw a clean way to do it, which is why *I* never made that change. Was hoping you would do some magic there...

**Comment by garlick** [comment]
Another update forced with the following updates
* updated and re-enabled libsubprocess loop test
* added kzutil sharness driver
* fixed a bug involving writing to existing stream in libkz (found by the above test)
* cleaned up/updated kzutil  (squashed in 6c7a00a)

Maybe mergeable?

**Comment by grondo** [comment]
Travis `dd` doesn't like some of the args in `kzutil` tests (Sorry)
```
dd: invalid status flag: `none'
Try `dd --help' for more information.
```

**Comment by grondo** [comment]
@garlick, this looks good to merge if you remove the `dd` `output=none` operand from the `kzutil` tests, which doesn't seem to be universally supported.

**Comment by garlick** [comment]
OK, got that fixed.  Thanks for the review @grondo.

**Pull request merged**
