### PR TITLE
modules/resource-hwloc: Fix potential corner case

### LINKED ISSUE #1010: flux-hwloc: flux_rpc_getf: Protocol error
On current master 2d3820a448ea1636df406d125cf20e9b8a264ff3 I am getting the following from hwloc:
```
$ ./flux hwloc topology
flux-hwloc: flux_rpc_getf: Protocol error
```
Running that command with FLUX_HANDLE_TRACE=1, it appears that a response containing the big XML as JSON string payload is returned, but possibly something is going wrong when jansson parses it  in flux_rpc_getf.

For fun I tried this change and it seemed to fix the problem:
```diff
index 6f75385..fd7c84b 100644
--- a/src/modules/resource-hwloc/resource.c
+++ b/src/modules/resource-hwloc/resource.c
@@ -478,7 +478,7 @@ static void topo_request_cb (flux_t *h,
         errno = EAGAIN;
         goto done;
     } else {
-        if (flux_respondf (h, msg, "{ s:s# }", "topology", buffer, buflen) < 0) {
+        if (flux_respondf (h, msg, "{ s:s }", "topology", buffer) < 0) {
             flux_log_error (h, "%s: flux_respondf", __FUNCTION__);
             goto done;
         }
```
I'm not sure if that is the right fix or why we aren't seeing this fail elsewhere.

### PR DESCRIPTION
**Pull request by chu11**
Fix potential corner case if string buffer length includes
the NUL character at the end.  We do not wish to include it
in the rpc.  Instead, just write the string to the rpc directly
without the length (i.e. "{ s:s }" instead of "{ s:s# }").

Fixes #1010

### CODE REVIEW

**Comment by grondo** [comment]
This is fine, but @chu11, in your opinion would it be safer to check first that `buffer` is NUL terminated before sending, just in case libhwloc ever changes to not return a NUL terminated string?

**Comment by chu11** [comment]
@grondo Good idea!

**Comment by chu11** [comment]
Huh ... it appears ```buffer[buflen - 1] != '\0'``` isn't always a safe check.  Wondering what's going on.

```
2017-03-22T22:15:12.564860Z resource-hwloc.err[0]: hwloc_topology_export_xmlbuffer buffer not NUL terminated
flux-hwloc: flux_rpc_getf: Protocol error
```

**Comment by chu11** [comment]
code coverage looks good, misses just one branch case (which is the case hit on opal).

**Comment by garlick** [comment]
Thanks!  Merging.

**Pull request merged**
