### PR TITLE
rework kvs fence to better support asynchronous interfaces

### LINKED ISSUE #729: kvs.err[0]: XXX encountered old commit state=4 fence_name=lwj.1.0
There appears to be a problem with kz/kvs handling of stderr from jobs launched by wreckrun on master 78980c613e7d5346f7d9581f94b3f8d60baf5169

I added a little debug to libpmi-client:
```diff
diff --git a/src/common/libpmi-client/pmi.c b/src/common/libpmi-client/pmi.c
index 9234dc5..f66961b 100644
--- a/src/common/libpmi-client/pmi.c
+++ b/src/common/libpmi-client/pmi.c
@@ -110,6 +110,7 @@ pmi_t *pmi_create_guess (void)
 
 int pmi_init (pmi_t *pmi, int *spawned)
 {
+    fprintf (stderr, "%s\n", __FUNCTION__);
     if (!pmi->init)
         return PMI_FAIL;
     return pmi->init (pmi->impl, spawned);
@@ -223,6 +224,7 @@ int pmi_kvs_get_value_length_max (pmi_t *pmi, int *length)
 int pmi_kvs_put (pmi_t *pmi,
         const char *kvsname, const char *key, const char *value)
 {
+    fprintf (stderr, "%s\n", __FUNCTION__);
     if (!pmi->kvs_put)
         return PMI_FAIL;
     return pmi->kvs_put (pmi->impl, kvsname, key, value);
@@ -231,6 +233,7 @@ int pmi_kvs_put (pmi_t *pmi,
 
 int pmi_kvs_commit (pmi_t *pmi, const char *kvsname)
 {
+    fprintf (stderr, "%s\n", __FUNCTION__);
     if (!pmi->kvs_commit)
         return PMI_FAIL;
     return pmi->kvs_commit (pmi->impl, kvsname);
@@ -239,6 +242,7 @@ int pmi_kvs_commit (pmi_t *pmi, const char *kvsname)
 int pmi_kvs_get (pmi_t *pmi,
         const char *kvsname, const char *key, char *value, int len)
 {
+    fprintf (stderr, "%s\n", __FUNCTION__);
     if (!pmi->kvs_get)
         return PMI_FAIL;
     return pmi->kvs_get (pmi->impl, kvsname, key, value, len);
```
Which seems to cause kz to go off the rails pretty reliably when launching flux with wreckrun:
```
$ ./flux wreckrun -N4 ./flux start flux getattr size
pmi_init
pmi_init
pmi_init
pmi_init
pmi_kvs_put
pmi_kvs_commit
pmi_kvs_put
2016-07-12T22:30:29.363645Z lwj.7.err[2]: kz_put (pmi_kvs_commit
): Invalid argument
2016-07-12T22:30:29.363722Z lwj.7.err[1]: kz_put (pmi_kvs_commit
): Invalid argument
pmi_kvs_put
2016-07-12T22:30:29.363965Z kvs.err[0]: XXX encountered old commit state=4 fence_name=lwj.7.0
2016-07-12T22:30:29.364063Z kvs.err[0]: XXX encountered old commit state=4 fence_name=lwj.7.0
pmi_kvs_put
pmi_kvs_commit
pmi_kvs_get
```

### PR DESCRIPTION
**Pull request by garlick**
This PR fixes #729, where PMI debug messages emitted when flux runs flux cause an internal KVS error.  I've rebased pr #713 on this and verified that we no longer see the problem.

The fix is in two parts.   The first part adds two new KVS API calls and uses them in `wrexecd` to decouple the KZ and PMI KVS updates.  This approach avoids having to change the API for non-async fence users and should be considered temporary until a KVS makeover somtime after our CTS-1 milestone.
```C
/* Operations (put, unlink, symlink, mkdir) may be associated with a named
 * fence by setting the fence context to that name before issuing them.
 * When the fence context is clear (the default), operations are anonymous.
 */
void kvs_fence_set_context (flux_t h, const char *name);
void kvs_fence_clear_context (flux_t h);
```
The second part reworks the internal commit implementation so that fences can be in progress at the same time as commit.  In fact you can have as many asynchronous fences running at the same time as you like.

There are fairly detailed commit messages that explain the changes.

### CODE REVIEW

**Comment by garlick** [comment]
Incidentally, I tried replacing the `kvs_commit()` in resource-hwloc with a fence and reran the timing test from #716.  Running it after the last kvs fix we got
* walk_topology disabled: 11s (same as before)
* walk_toplogy enabled: 23s (down from 25s)
In this experiment I got
* walk_topology disabled: 9s
* walk_topology enabled: 18s
We might want to provide some way for a fence name, nprocs to be passed in with the reload request and/or on the command line for rc1.

**Comment by grondo** [comment]
> We might want to provide some way for a fence name, nprocs to be passed in with the reload request and/or on the command line for rc1.

Yeah, I had the same thought when working on #718. The `flux-hwloc reload` command could generate a unique name and send nprocs without input from the user...

**Comment by garlick** [comment]
> at module load time could the resource-hwloc module calculate a name programmatically so each rank could agree on the name without passing it as module parameter?

I can't think of a way to do that within the module, but building it into [RFC 5](https://github.com/flux-framework/rfc/blob/master/spec_5.adoc) generically so any insmod/rmmod over a group could use fence/barrier might be possible.

**Comment by garlick** [comment]
Todo:
* more tests
* clean up pending fences in `kvs.disconnect` handler
* add a `kvs.abortfence` request and event in case the fence cannot be completed

**Comment by grondo** [comment]
> but building it into RFC 5 generically so any insmod/rmmod over a group could use fence/barrier might be possible.

That seems like a brilliant idea!

**Comment by garlick** [comment]
Handling disconnect/abort is a bit complicated:
* If a client enters the fence then disconnects before it exits, the disconnect probably should not abort the fence, since it still could complete successfully.
* If a client disconnects before entering the fence, there is really nothing we can do about it since we don't know a priori that it was planning to do that; the fence will hang
* if a fence aborts before a client enters it, the fence state might be gone and this might look like a new fence.  The new fence will hang (should "used" fence names persist forever?)
* A fence_abort call seems like something that should be generalized as `flux_rpc_abort()` as discussed in #688 

My feeling is solving this requires some research (MPI?  MrNet?) and design (establish group first, then allow collectives over it, handle group dissolution generally and propagate errors to collectives?)  and does not necessarily need to be addressed in this PR, which "does no harm" in the sense that error handling is like it was before.

**Comment by grondo** [comment]
That sounds reasonable to me as far as I can understand it.

Is this case already generalized into #688 or does it need a new issue?

**Comment by garlick** [comment]
I should have referenced #447 here.   I think between that and #688 we're good.

Working on some more tests now.

**Comment by garlick** [comment]
IMHO this is probably mergeable.

**Comment by grondo** [comment]
Sorry! Meant to merge this one earlier.

**Comment by garlick** [comment]
Thanks!

**Pull request merged**
