### PR TITLE
NEWS.md: update for 0.22.0 release

### PR DESCRIPTION
**Pull request by garlick**
Here's a start at release notes for 0.22.0.  Feel free to push updates here.

### CODE REVIEW

**Comment by grondo** [comment]
Ok, I made a pass and force-pushed some changes.

Mainly I just simplified the bullets for the intended audience, and collected some entries together that really described a larger feature.

**Comment by garlick** [comment]
Oh good thanks for that.

**Comment by garlick** [comment]
Think we should consolidate the PRIORITY stuff (at least the internals PRs) in one "prepare internals for fair share priority" entry?

**Comment by garlick** [comment]
I went ahead and did that, and also shortened some descriptions.

**Comment by grondo** [comment]
Yes, thanks. I didn't spend the time to figure out which went together...

**Review by grondo — APPROVED** [review]
LGTM! Let's tag!

**Pull request merged**
