### PR TITLE
bindings/python: change minimum python version to 3.6

### PR DESCRIPTION
**Pull request by trws**
This (should be) the absolute minimum to remove python 2 support.  Updates the config, README, and travis.  I'm not sure all of our docker images have a python 3 available, so we'll see on travis.

### CODE REVIEW

**Comment by dongahn** [comment]
Just FYI, James Corbett from UQP team said today  that he has a python 3 branch of UQP. Not ready to drop support for python2 eithin UQP but he should probably be able to make progress on integrating  using this brach.

**Comment by garlick** [comment]
The TEST_INSTALL travis build is failing with various python errors on python test scripts (but not python flux commands like `flux mini run`).  Before @trws's change, we weren't building the combination of TEST_INSTALL and python3 in travis.  TEST_INSTALL was only attempted with python2.

Maybe these scripts are using the python2 interpreter with PYTHONPATH pointing to python3 modules?

Examples
```
schedutil: set bit to hang alloc/free requests

expecting success: 
    ${REQ_AND_UNLOAD} sched-dummy

Traceback (most recent call last):
  File "/usr/src/t/schedutil/req_and_unload.py", line 44, in <module>
    main()
  File "/usr/src/t/schedutil/req_and_unload.py", line 26, in main
    h = flux.Flux()
  File "/usr/lib/flux/python3.6/flux/__init__.py", line 17, in Flux
    import flux.core.handle
  File "/usr/lib/flux/python3.6/flux/core/handle.py", line 14, in <module>
    from flux.rpc import RPC
  File "/usr/lib/flux/python3.6/flux/rpc.py", line 14, in <module>
    from flux.future import Future
  File "/usr/lib/flux/python3.6/flux/future.py", line 13, in <module>
    from flux.util import check_future_error
  File "/usr/lib/flux/python3.6/flux/util.py", line 19, in <module>
    from flux.core.inner import ffi, raw
  File "/usr/lib/flux/python3.6/flux/core/inner.py", line 11, in <module>
    from _flux._core import ffi, lib
ImportError: dynamic module does not define init function (init_core)
not ok 3 - schedutil: alloc/free fail with ENOSYS(38) after unload
```

```
job-ingest: guest cannot submit priority=17

expecting success: 
	test_valid ${JOBSPEC}/valid/*

Traceback (most recent call last):
  File "/usr/src/t/jobspec/y2j.py", line 3, in <module>
    import sys, yaml, json
  File "/usr/lib/python3/dist-packages/yaml/__init__.py", line 284
    class YAMLObject(metaclass=YAMLObjectMetaclass):
                              ^
```

**Comment by garlick** [comment]
I got this working on another branch by running those scripts under `flux python`.   I hope I'm not overstepping, but I'll go ahead and push those commits to your branch @trws for review.

**Comment by garlick** [comment]
Oh the typos in my commit messages!  Gah.  Anybody object if i force push a fix?

**Comment by trws** [comment]
Not at all.  Stephen and I found the same issue and I was planning to make pretty much exactly the same fix next week.  The problem turned out to be that the TEST_INSTALL setup actually ends up forcing `/usr/bin` onto the front of path because of the install location, which ends up overriding the Travis-selected python.  Using flux python should fix that for the general case, but we may want to keep an eye on that for our testing in case we expect other tools to be on the front of path.  Thanks for this @garlick!

**Comment by garlick** [comment]
Restarted centos builder that failed in valgrind:
```
/usr/src/t/sharness.d/flux-sharness.sh: line 9: 10117 Alarm clock             perl -e 'use Time::HiRes qw( ualarm ) ; ualarm ((shift @ARGV) * 1000000) ; exec @ARGV or die "$!"' "$@"
not ok 1 - valgrind reports no new errors on 2 broker run
```

**Comment by trws** [comment]
I'm vaguely surprised we still have a valgrind run, thought we transitioned that to sanitizers some time ago.  Guess my memory is just faulty, is that a change anyone else would like to see? I could see about getting it set up.

**Comment by grondo** [comment]
I think @dongahn made an effort long ago, but we never enabled it in Travis for some reason. IIRC there were some corner cases where it didn't work, but don't remember the details.

Since the valgrind-in-travis tests are really sketchy, it would be great if you have a spare moment to try out asan.

**Comment by dongahn** [comment]
> I think @dongahn made an effort long ago, but we never enabled it in Travis for some reason. IIRC there were some corner cases where it didn't work, but don't remember the details.

I believe the main limitation was that ASAN stop executing the program when it finds the first memory error. There was an option that let you continue after the first find, but this was "best effort" option (no guarantee.) Back then, we didn't find it useful because there were so many errors that ASAN detected (some true positives and some false positives). Now our code base has matured, maybe we can revisit this. For sched, I was planning to do this as part of future hardening phase.

**Comment by trws** [comment]
It has since grown that capability, perhaps worth another look.

**Comment by dongahn** [comment]
Sounds good! For ATS systems, sanitizers are the future anyway.

**Comment by garlick** [comment]
Should we move forward with this?   We can always back up if we hear from users in the next couple of weeks that this is a bad move, but it seems like we have strong indications that this is the right direction.

I wasn't sure if removing shebangs where they were ignored was the right thing.  Another option would be to go with `#!/usr/bin/env python3` uniformly, just to be in-your-face clear that this is a python 3 script, even though the shebang itself _should_ have no effect if the script is being used right.

**Comment by trws** [comment]
With the shebang fixes in here I’m thinking yes. If people want 2 back and can make a case, we can revisit that part but this now includes your fixes that we need either way.

**Comment by SteVwonder** [comment]
> Should we move forward with this?

My concern with this PR right now is that it completely removes CI test coverage of the bindings on py2.  If we truly want to do that, then I think we should also disable building the bindings against py2 to avoid users hitting a completely unsupported configuration/compilation path (since py2 is still the default on many OSes).

Alternatively, if we are still OK with systems/users building the bindings with py2, but it just won't be our focus, then I think we should have at least one Travis builder still checking py2.

**Comment by garlick** [comment]
> I think we should also disable building the bindings against py2 to avoid users hitting a completely unsupported configuration/compilation pat

I think we are preventing building against python2 with the autoconf min version check in c9c380be16df?

**Comment by SteVwonder** [comment]
> I think we are preventing building against python2 with the autoconf min version check in c9c380b?

:man_facepalming: Thanks for pointing that out.  Sorry I missed it.

**Comment by garlick** [comment]
I think this received the big thumbs up at todays coffee meeting so setting merge-when-passing.

**Comment by grondo** [comment]
May want to quick update the PR title or add a custom commit message for Mergify to get a slightly better merge commit message:

> One merging a pull request, it’s sometimes desirable to customize the merge message. This is possible when using the GitHub user interface, but it was not accessible when using Mergify merge action.
The merge action will now read the pull request body to look for a section named Commit Message. It will use this as the merge commit message if available.

**Pull request merged**
