### PR TITLE
libpmi: drop pmix client support and --with-pmix configure option

### PR DESCRIPTION
**Pull request by garlick**
pmix code added to flux for sierra was not especially helpful, and caused a few problems.  As discussed in #1662, this PR backs it out.

We'll need some RPM on that architecture to provide libpmix (with libpmi.so) that interoperates with spectrum MPI's built-in version, by the time we roll out the next release of Flux on sierra.

### CODE REVIEW

**Comment by grondo** [comment]
This seems wise, as I think the `--with-pmix` option also caused some confusion for users.

Thanks! I'm fine with merging, but we should probably get at least one more ack first.

**Comment by SteVwonder** [comment]
Per @trws's suggestion in #1662:
> Should we add a recommended dep or similar on an external PMIX with PMI?

Can this PR also update the readme to specify that we require either a PMI libary or a PMIx library with PMI compatibility?

**Comment by garlick** [comment]
Good idea, I'll tack on an update to README.md.

**Comment by grondo** [comment]
Thanks @garlick!

**Pull request merged**
