### PR TITLE
NEWS.md: udpate for flux-core v0.10.0

### PR DESCRIPTION
**Pull request by grondo**
Add a NEWS entry for v0.10.0 before tagging the release.

### CODE REVIEW

**Comment by grondo** [comment]
If nobody has any edits for the NEWS file, then this can be merged and v0.10.0 tagged. Feel free to sanity check master as well!

**Comment by grondo** [comment]
Not sure why coverage decreased, this should be ready to go in.

**Comment by SteVwonder** [comment]
Ok.  Is merging this and tagging supposed to be a single operation?  Or does this get merged and then a tag made? Does tagging automatically generate a release and associated tarball or is manual intervention required?

**Comment by grondo** [comment]
@SteVwonder, we have to first merge NEWS updates, then someone pushes an annotated tag. There's a stanza in the .travis.yml that then automatically creates a GitHub release.

**Comment by SteVwonder** [comment]
Ok. Merged.  I'll push the annotated tag shortly.

**Comment by grondo** [comment]
Thanks, just look at the previous examples for the format.

**Comment by grondo** [comment]
Great, we've got a release, thanks!
https://github.com/flux-framework/flux-core/releases/tag/v0.10.0

**Pull request merged**
