### PR TITLE
[WIP] shell: Support stdin via a file

### PR DESCRIPTION
**Pull request by chu11**
Just wanted to throw this up for possible after milestone if it's a high user need or if we decide to be aggressive on some of these last PRs.  Built on top of #2345 (but doesn't require #2350 or #2396).  

Nothing too special to note.  Only note is that the same file is opened for all tasks for stdin.  Didn't add a per-task input file format (atleast yet).  Perhaps not best.  Should only leader open it and write to `guest.input`?

### CODE REVIEW

**Comment by grondo** [comment]
> Nothing too special to note. Only note is that the same file is opened for all tasks for stdin. Didn't add a per-task input file format (atleast yet). Perhaps not best. Should only leader open it and write to guest.input?

Yeah, I'm kind of struggling with this, but I think it is more flexible if an input plugin on the leader shell (almost) always writes to the guest.input eventlog. In most cases, the rest of the shells can process this input and send it to local tasks to which it is addressed. This will allow front end tool like `flux job attach` to broadcast stdin to one or more tasks.

We may want to see if we can support the flexible `--input` option from `wreckrun`:
```
       --input=HOW, -i HOW
           Indicate how to deal with stdin for tasks. HOW is a list of src:dst
           pairs where src is a source FILENAME which may optionally be a
           mustache template as in --output, or the special term stdin to
           indicate the stdin from a front end program, and dst is a list of
           taskids or * or all to indicate all tasks. The default is stdin:*.
           If only one of src or dst is specified, a heuristic is used to
           determine whether a list of tasks or an input file was meant. (e.g
           --input=file.in will use file.in as input for all tasks, and
           --input=0 will send stdin to task 0 only.

```

**Comment by chu11** [comment]
> Yeah, I'm kind of struggling with this, but I think it is more flexible if an input plugin on the leader shell (almost) always writes to the guest.input eventlog. In most cases, the rest of the shells can process this input and send it to local tasks to which it is addressed. This will allow front end tool like flux job attach to broadcast stdin to one or more tasks.

yeah, I began prototyping some shell `guest.input` -> task code yesterday.  Hindsight being 20/20, this code perhaps should have come first.  I just went this path b/c I had PR #2345 done.

**Comment by grondo** [comment]
Potentially dumb idea. Should we support `redirect` events for input as well?

**Comment by chu11** [comment]
Hmmm.  I'm not sure of there's a benefit.  We're typically reading `guest.input` to begin reading `data` events and sending stdin data via `flux_subprocess_write()` calls.  If we were to hit a `redirect` event, we're already too late to `dup2()` the file descriptor for the file.  The subprocess has already started.

To solve this, we'd have to read `guest.input` BEFORE we start the subprocess.  Which I don't think we want to do?  Obviously design hasn't been fully fleshed out yet.

I'm going to go ahead and close this, organize my thoughts on pros & cons of approaches and put them in #2257.

**Comment by grondo** [comment]
>  If we were to hit a redirect event, we're already too late to dup2() the file descriptor for the file.

No I meant the shell, upon a redirect event, would begin reading from the file (or elsewhere) on behalf of the tasks, not  that a redirect would try to dup the file onto each task.

**Comment by chu11** [comment]
> No I meant the shell, upon a redirect event, would begin reading from the file (or elsewhere) on behalf of the tasks, not that a redirect would try to dup the file onto each task.

Ahh, so not using INPUT_FD.  I see.  Then it's not that bad.  I'll add it to the thoughts I'm writing up,

**Pull request closed without merging**
