### PR TITLE
NEWS.md: add release notes for v0.33.0

### PR DESCRIPTION
**Pull request by grondo**
Update release notes for flux-core v0.33.0.

I tried to summarize the usability enhancements in this release before the detailed notes.

As always, feel free to force push any updates or improvements directly to this branch.

### CODE REVIEW

**Review by garlick — APPROVED** [review]
Force pushed a small typo. LGTM!

**Comment by grondo** [comment]
Thanks @garlick!

**Comment by grondo** [comment]
Thanks! Added an entry for #4037 and force-pushed  the result. Will set MWP on this one tomorrow and tag the release.

**Comment by grondo** [comment]
Set MWP.

**Pull request merged**
