### PR TITLE
remove flux-hwloc reload and aggregator module

### PR DESCRIPTION
**Pull request by grondo**
Now that the core `resource` module provides hwloc XML, there is no need for `flux hwloc reload` so remove it.

Update `flux hwloc info` and `flux hwloc topology` to fetch XML from the resource module, and update all tests and docs. (Sorry, this and the above have to all be done under one big commit to avoid breaking tests)

`flux hwloc reload` was the last place where the hwloc "by_rank" object was used, so remove all references to by_rank (e.g. in librlist).

Also,  `flux hwloc reload` was the final user of the aggregator module, so remove that and all its components.
(yay, the code purge!)

This is based on top of #3265, so it is WIP for now.

### CODE REVIEW

**Comment by garlick** [comment]
Any thoughts on whether we should open up `resource.get-xml` RPC to guests?

**Comment by grondo** [comment]
> Any thoughts on whether we should open up resource.get-xml RPC to guests?

Good question. I had assumed the full instance topology was only accessible by instance owners, since previously the XML had to be fetched from the KVS. I hadn't really thought about a use case for guest access to this information though. It seems logical that all XML it would only be available if you *own* the resources, so maybe we keep it that way for now?

Also, for a system instance won't all brokers have to be up at least once or this RPC will block?

**Comment by garlick** [comment]
OK that approach works for me, and yes, the RPC would block on the system instance (good point!)

One quick thought: I've apparently forgotten what cool things can be done by piping say the output of `flux hwloc topology` to some of the other hwloc tools.  So far I haven''t been able to get anything to take xml on stdin even though several tools claim to accept `-i -`.  If there are some useful examples could we add them to the man page?

**Comment by grondo** [comment]
> One quick thought: I've apparently forgotten what cool things can be done by piping say the output of flux hwloc topology to some of the other hwloc tools.

Ok, this didn't work because we broke `flux hwloc topology` awhile ago when removed the resource-hwloc module. There was code in the module which concatenated all rank XML into a custom global topology, the XML of which was the output of the `flux hwloc topology` command.

I've resurrected @trws's code to do this in `flux hwloc topology` in this PR and it now works as expected, though the commandline options required on the hwloc tools is a bit cumbersome.

I added this example to the `flux-hwloc(1)` manpage.

```
ƒ(s=4,d=0,builddir) grondo@asp:~/git/flux-core.git$ flux hwloc topology  | lstopo-no-graphics --if xml -i -
System (31GB total)
  Machine L#0 (7976MB) + Package L#0
    Core L#0 + PU L#0 (P#0)
    Core L#1 + PU L#1 (P#1)
    Core L#2 + PU L#2 (P#2)
    Core L#3 + PU L#3 (P#3)
  Machine L#1 (7976MB) + Package L#1
    Core L#4 + PU L#4 (P#0)
    Core L#5 + PU L#5 (P#1)
    Core L#6 + PU L#6 (P#2)
    Core L#7 + PU L#7 (P#3)
  Machine L#2 (7976MB) + Package L#2
    Core L#8 + PU L#8 (P#0)
    Core L#9 + PU L#9 (P#1)
    Core L#10 + PU L#10 (P#2)
    Core L#11 + PU L#11 (P#3)
  Machine L#3 (7976MB) + Package L#3
    Core L#12 + PU L#12 (P#0)
    Core L#13 + PU L#13 (P#1)
    Core L#14 + PU L#14 (P#2)
    Core L#15 + PU L#15 (P#3)
```

**Review by garlick — APPROVED** [review]
Thanks!  The example is exactly the sort of thing I was hoping we could document since as you point out, the hwloc tools can be a little wonky.  Nice that we discovered that deficiency.

Based on a fairly quick pass, this LGTM!

**Comment by grondo** [comment]
Rebased and remove WIP.

**Comment by grondo** [comment]
Oops, I have some hwloc v2.x compatibility work to still do here apparently. Will get that in the AM.

**Comment by grondo** [comment]
Restarted a builder that failed here:
```
expecting success: 
	pids="" &&
	flux start ${ARGS} -s4 -o,--k-ary=1 /bin/true & pids=$!
	flux start ${ARGS} -s4 -o,--k-ary=2 /bin/true & pids="$pids $!"
	flux start ${ARGS} -s4 -o,--k-ary=3 /bin/true & pids="$pids $!"
	flux start ${ARGS} -s4 -o,--k-ary=4 /bin/true & pids="$pids $!" 
	wait $pids
flux-start: 0 (pid 5384) Killed
not ok 43 - broker --k-ary option works
```

**Pull request merged**
