### PR TITLE
kvs: Remove libkvs kvs-classic

### PR DESCRIPTION
**Pull request by chu11**
One interesting change to note of.  The old ```flux_kvs_get_dir()``` would convert an empty string key to the root directory (```"."```) key b/c it was a compatibility thing with the python kvs code.  I just changed the default key in python from ```""``` to ```"."```, which I think should be fine.  It doesn't make sense to me that the default key would be an empty string.  I assume some long ago legacy behavior?

### CODE REVIEW

**Comment by grondo** [comment]
> I just changed the default key in python from "" to ".", which I think should be fine. It doesn't make sense to me that the default key would be an empty string. I assume some long ago legacy behavior?

Yes, IIRC early on when we thought kvsdir_t was a nice interface it made sense that the default "dir" was the root directory, ".".  Probably fine to require users or bindings to use "." now

**Comment by chu11** [comment]
> Yes, IIRC early on when we thought kvsdir_t was a nice interface it made sense that the default "dir" was the root directory, ".". Probably fine to require users or bindings to use "." now

The legacy behavior I was referring to the was fact the default key was an empty string.  I changed it so the default key is now ```"."```.  Are you thinking we not have a default at all?

**Comment by grondo** [comment]
Sorry, I meant the default for flux_kvsdir_get() or what not (I think the C api call used to return the root dir if you passed an empty string? I could be mistaken though)

 I think what you did is correct.

**Comment by chu11** [comment]
Only travis error appears to be #2015, so gotta fix that first.

**Comment by chu11** [comment]
rebased

**Pull request merged**
