### PR TITLE
disable kvs config

### PR DESCRIPTION
**Pull request by grondo**
Continuation of what @garlick started in #595.

Still todo here is to disable the backdoor used by the broker to load kvs `config.` namespace using module parameters. Unfortunately, `wrexec` service still uses items under `config.wrexec`. I had forgotten how convenient that was...

### CODE REVIEW

**Comment by garlick** [comment]
We could dump the config into broker attributes instead of the KVS, then wrexecd can call `flux_attr_get()`...

**Comment by grondo** [comment]
That's not a bad idea.. though currently the `wrexec` module does `kvs_watch` on the config value so it updates an internal variable only when the value is updated... That is kind of nice for testing. But I suppose it is fine to call `flux_attr_get()` before each invocation of the service.

**Comment by grondo** [comment]
Oops `flux-config` tests still assume kvs-config:
```
expecting success: 
	flux config get general.exec_path
	if test $? != 0; then
           # XXX: May be no KVS config, we have to fake it:
           flux env sh -c "flux config put general.exec_path=\${FLUX_EXEC_PATH}"
	   flux config get general.exec_path
	fi
flux-config: /home/travis/.flux: No such file or directory
flux-config: /home/travis/.flux: No such file or directory
flux-config: /home/travis/.flux: No such file or directory
```

**Comment by grondo** [comment]
> We could dump the config into broker attributes instead of the KVS, then wrexecd can call flux_attr_get()...

Actually, I'm not so sure about this. Are attributes per-broker? This might make it awkward to update to a new wrexecd across the session all at once. That being said, the only use case I can think of is for testing and that can easily be handled with an exec or by using only a single rank.

This kind of use case might be interesting to think about in general, though.

**Comment by grondo** [comment]
BTW, I'm finding that without the file & kvs config scheme, the `flux config` command is slightly awkward. Actually it is pretty simple in what it does, but perhaps with any config in the kvs, is it no longer needed? Even trying to write a simple test for it, I'm running across issues like:
 - `flux config CMD` always returns an error if the file doesn't exist, even if you think might be able to `flux config put variable=value` to an empty config
 - `flux config save` -- does this just basically copy a file
 - It wants a config directory with a file liternally `config` -- you can't actually pass a file argument (maybe to the save command)
 - It (seems to, needs more testing) ignores the current environment and only deals with files.

I don't really see any users of `flux config` -- and since the config is going to have a rework someday, perhaps it is best to eliminate the command for now?

If we want to keep the command, I would probably try to make the following changes
 - Make `flux config` a builtin
 - `flux config` reads config file *if existing*, applies environment and reports that, i.e. the effective config not just the config file

**Comment by garlick** [comment]
> Are attributes per-broker? 

Yes, so we'd be making a change to the semantics of the config namespace (no longer global).  I could live with that.

If you agree, then I apologize in advance for the broker side attribute interface, which needs some work as briefly alluded to in #555.  It got kind of weird after the broker `--setattr` option was added and needs to be revisited.  In contrast, I think the user-facing command and libflux attribute interfaces are decent (IMHO).

On flux-config, I'm fine with killing it.

**Comment by grondo** [comment]
> Yes, so we'd be making a change to the semantics of the config namespace (no longer global). I could live with that.

As far as naming scheme, would you suggest inserting config items as `config-section-key = value`? `config` prefix to avoid potential name collisions, and replace `.` with `-` to adhere to the current attributes naming scheme. I'm not sure if there is a technical reason `.` is not allowed in attributes.

**Comment by garlick** [comment]
> As far as naming

Should we _not_ translate, and document the config file as another way to set attributes, complementary to `flux setattr` and `flux-broker --setattr`?

Then if the names need changing to not look like a mess we could do that later.

**Comment by grondo** [comment]
I guess that is what I was asking (though I didn't make the nice leap you did to realizing the config file is another way to set *all* broker attributes).

I guess I was thinking this through because there is currently no heirarchy with attributes, instead there is a kind of ad-hoc <group>-<subname> naming convention. Ok, to kind of introduce a new convention separated by dots (`.`)?

**Comment by garlick** [comment]
Well, it might be prettier if we dropped the `general.` prefix and converted both `.` and `_` to `-`, but I would vote to do it by manually changing the config file and all users rather than introducing a translation which would be confusing to users.  If that seems like a lot of grunt work in the service of pedantry, I'd be fine saving it for another time.

**Comment by grondo** [comment]
For now I'll just have brokers dump the config directly as attributes. We can then fix it up later, but eventually, for ease of setting attributes via the config file, we may want to *add* heirarchy to some of the existing attributes (e.g. `content.*`) rather than having one flat namespace (with a heirarchical naming convention).

**Comment by garlick** [comment]
Sounds good.

**Comment by grondo** [comment]
Actually pretty painless, just copied the code from `-S, --setattr` and kept KVS `config.*` namespace until users can be updated
```
$ flux lsattr -v | grep general.
general.connector_path                  /home/ubuntu/workspace/src/connectors
general.exec_path                       /home/ubuntu/workspace/src/cmd:/home/ubuntu/workspace/src/cmd:/home/ubuntu/workspace/src/broker
general.lua_cpath                       /home/ubuntu/workspace/src/bindings/lua/?.so
general.lua_path                        /home/ubuntu/workspace/src/bindings/lua/?.lua
general.man_path                        /home/ubuntu/workspace/doc
general.module_path                     /home/ubuntu/workspace/src/modules
general.program_library_path            /home/ubuntu/workspace/src/lib/libpmi/.libs:/home/ubuntu/workspace/src/common/.libs
general.python_path                     /home/ubuntu/workspace/src/bindings/python:/home/ubuntu/workspace/src/bindings/python/pycotap
```

**Comment by grondo** [comment]
Ok, I've just pushed the following updates:
 - Use `flux_attr_get` in `wrexec` and `wrexecd` to grab configured `wrexecd_path` and `lua_pattern` (previously kvs was used)
 - fixup wreck tests that used kvs `config.*` directly
 - fixup python test that checked for existence of kvs `config` dir.
 - Disable propagation of config values to kvs in broker

I haven't checked yet to see if there is any doc that needs to be updated.

**Comment by grondo** [comment]
Ok, the python kvs "dir_exists" test was still failing, but only in the install target. I gave up and had the test create a directory first, then check if it exists to verify the "exists" functionality on directories.

**Comment by garlick** [comment]
Nice cleanup!   If you think it's ready I'll give it one more review pass and click merge if all looks ok.

**Comment by grondo** [comment]
Should we add anything to `flux-broker-attributes(7)` about the config being pushed there? I'm not really sure what to say about it.

**Comment by grondo** [comment]
Other than docs, this cleanup is probably ready

**Comment by garlick** [comment]
> Should we add anything to flux-broker-attributes(7) about the config being pushed there?

I'm for holding off on that for now.

**Comment by garlick** [comment]
Did you want to squash out the changes to flux-config that is subsequently removed?

**Comment by grondo** [comment]
Oh, yeah. I thought I had done. Coming soon.

**Comment by grondo** [comment]
Ok, rebased and now should be better. Let's make sure Travis passes

**Comment by garlick** [comment]
Thanks!  Merging.

**Pull request merged**
