### PR TITLE
python: validate dependencies in Jobspec constructor

### PR DESCRIPTION
**Pull request by grondo**
This PR adds missing functionality to the `Jobspec` class to validate that the `dependencies` system attribute, if it exists, conforms to RFC 14 and RFC 26.

### CODE REVIEW

**Comment by garlick** [comment]
We should open up an issue add similar checks to `flux_jobspec1_attr_check()`.  I'll go ahead and do that.

**Comment by grondo** [comment]
> We should open up an issue add similar checks to flux_jobspec1_attr_check(). I'll go ahead and do that.

Oh, good call! Thanks.

**Comment by grondo** [comment]
Oh, oops. I'll also have to update the schema validator here so the invalid dependency inputs do not unexpectedly pass.

**Review by SteVwonder — APPROVED** [review]
Thanks @grondo! The python changes LGTM!

**Comment by garlick** [comment]
Here's a candidate change (plus whitespace fix first) for jobspec.jsonschema.

55ce1f204a0174b0cac5d3846655f74e73598ffd jobspec.jsonschema: check attributes.system.dependencies
cd2bb2c7c8e5a3379bc3f3329cb5d69fe7a04495 jobspec.jsonschema: fix whitespace

**Comment by grondo** [comment]
Ok, I pulled in @garlick's jsonschema fixes above (and additionally applied them to `jobspec_v1.jsonschema`) and a small improvement for `t/jobspec/validate.py`.

**Review by garlick — APPROVED** [review]
Looks great, thanks.

**Comment by grondo** [comment]
> Looks great, thanks.

Thank you for your help! I've set MWP.

**Pull request merged**
