### PR TITLE
KVS commit refactor

### PR DESCRIPTION
**Pull request by chu11**
This is a refactor of the "commit" side of the kvs.

There is only really one "epiphany" in this refactor.  The original ```fence_t``` data structure was split into a ```fence_t``` and a ```commit_t``` data structure.  By doing this, there is now a clear delineation between an actual "fence" that occurs when callers send RPCs and the data structures used behind the scene to actually commit data to the content store.  IMO, splitting that up eliminated a lot of the monolithic-ness.  Took me awhile to realize this.

After that, there isn't really anything magical per se, just the typical lineage of refactoring 1 tiny thing at a time: code cleanup, api change, move functions into a new file, create an API, etc.  There is now a "fence" API and a "commit" API in new files that each have their own unit tests.  The "commit" API has a "commit manager" that actually wraps around ```commit_t```.

One interesting refactor of note is the function ```commit_process()``` which processes a commit and does all the commit mods and unrolling.  It may return missing references to the user to load, or pointers to cache entries that are dirty and need to be backed up.  By removing RPCs out of the commit logic, this allows the commit API to be separately unit-testable.

Still need to valgrind test & soak test.  The introduction of the ```commit_t``` data structure adds some additional malloc() calls per fence.  Hopefully this doesn't have a noticeable impact on performance.  There are few error cases that are more optimized now which will help balance some things out.

### CODE REVIEW

**Comment by garlick** [comment]
Looks like clang is sad here:
```
In file included from ../../../../../src/modules/kvs/kvs.c:55:
../../../../../src/modules/kvs/types.h:3:14: error: redefinition of typedef 'href_t' is a C11 feature [-Werror,-Wtypedef-redefinition]
typedef char href_t[BLOBREF_MAX_STRING_SIZE];
             ^
../../../../../src/modules/kvs/types.h:3:14: note: previous definition is here
typedef char href_t[BLOBREF_MAX_STRING_SIZE];
             ^
```
while the gcc build is failing the valgrind test

**Comment by chu11** [comment]
Re-pushed with a variety of mini-fixes.  ```.h``` file header guards fixed the clang issue.  Found the mem-leak and fixed that.  Coverage looks pretty good.  I think I can add 1-2 tiny things to add a little coverage.  Will run soak tests tomorrow and hopefully will be awesome.

**Comment by chu11** [comment]
ran some soak tests out of /tmp on catalyst

```
master

   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
 0.1200  0.1200  0.1200  0.1236  0.1300  0.1400 
 0.1100  0.1200  0.1200  0.1218  0.1200  0.1400 
 0.1200  0.1200  0.1200  0.1228  0.1300  0.1300 
 0.1100  0.1200  0.1200  0.1243  0.1300  0.1700 
 0.1100  0.1200  0.1200  0.1222  0.1300  0.1300 
```

```
kvs refactor branch

   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
 0.1200  0.1200  0.1200  0.1239  0.1300  0.1300 
 0.1200  0.1200  0.1200  0.1243  0.1300  0.1300 
 0.1200  0.1200  0.1200  0.1238  0.1300  0.1400 
 0.1200  0.1200  0.1200  0.1223  0.1200  0.1300 
 0.1200  0.1200  0.1200  0.1235  0.1300  0.1300 
```

master mean .12294
kvs refactor branch mean .12356

0.5% slower

So I suspect a little bit of extra overhead from the new data structure allocation and the addition of function calling overhead.  I'll see if I can get the number down a bit, but minimally it's well within range of what it was before.

**Comment by garlick** [comment]
Wow, nice cleanup.  I've been through this at the 10,000 foot level and it seems good.

Thanks for the extra paranoia of running the soak test and analyzing the results.  I wouldn't worry about the small performance hit - it's close enough that I doubt you've introduced any new stalls or other significant problems that will balloon up at scale.

The new unit tests are great addition!

The main thing here IMHO is that you are feeling like the code is getting structured in such a way that you can work on it with confidence.  The next steps of converting to jansson and the treeobj metadata will be much easier IMHO with your help and with the new unit tests.

Anyway, awesome, and when you're done fine tuning it, let me know and I think this could go in.

**Comment by chu11** [comment]
A few tweaks, two lists in commit_t collapsed into one, removing an unnecessary branch check, a few minor cleanups/tweaks, a few more API-niceties (sp?), a few more tests for coverage.

It's closer to even now, with some normal randomness.  I've gotten anywhere from 0.19% to 0.6% slower on	this kvs refactor branch.

I just saw this when running soak with 1000 jobs on hype2 (which is empty of users and has less randomness).

master branch

```
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.
  0.100   0.110   0.110   0.111   0.110   0.160
```

kvs refactor branch

```
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.
 0.1000  0.1100  0.1100  0.1106  0.1100  0.1500
```

the kvs refactor branch was actually a tad faster for this particular run.  That's probably not going to be normal, but it's clearly very close.

**Comment by garlick** [comment]
Great!  Ready to go in?

**Comment by chu11** [comment]
Yup, it's good to go.

**Pull request merged**
