### PR TITLE
rc: load job-archive

### LINKED ISSUE #3940: add job-archive to rc1/rc3
It looks like job-archive does nothing if there is no configuration.  To simplify setup of flux-accounting in a system instance, we should probably just load it on all flux instances.  Then we would just need to add TOML configuration instructions to the flux admin guide, as opposed to rc1/rc3 script additions.

Edit: removed suggestion about a default path.  Probably this much is fine for now, and we can open separate issues for usability after we've tried this on fluke.

### PR DESCRIPTION
**Pull request by garlick**
Problem: although job-archive does nothing if not configured, it is not loaded in rc1/rc3, so a custom rc script is required if iti s needed in production.
    
Just load it in rc1/rc3 and it can be enabled with config.

(flux-accounting depends on it)
    
Fixes #3940

### CODE REVIEW

**Review by chu11 — APPROVED** [review]
LGTM, just a typo in commit message

`if iti s needed in production.`

**Comment by garlick** [comment]
thanks!  fixed the typo and forced a push.

**Comment by grondo** [comment]
This branch is now out-of-date, ok to tell mergifyio to rebase?

**Comment by grondo** [comment]
@mergifyio rebase

**Pull request merged**
