### PR TITLE
Small build fixes

### PR DESCRIPTION
**Pull request by garlick**
Another PR for small issues as I work through making RPM's for RHEL 7.

### CODE REVIEW

**Comment by grondo** [comment]
I was going to argue this kind of stuff goes in CFLAGS, but after reading your comment I agree with you. Thanks for the nice commit log message!

Is there any other small fixes coming for this branch?

**Comment by garlick** [comment]
Might be some more stuff so lets hold off a bit.

**Comment by garlick** [comment]
Rebased after merging #532 and forced a push.

**Comment by grondo** [comment]
Nice! A lot of good cleanup here. Ready to merge, or still waiting on more fixups?

**Comment by grondo** [comment]
Especially like the changes for the flux package version. However, I don't remember much about how AC_INIT works, but what happens when `./configure` is run outside of a git tree. How about `./autogen.sh`? Maybe as part of `make dist` a version file should be created like `git` source does and this becomes part of the distribution? (Actually if you already went through this thought process and it is a solved problem, I apologize)

**Comment by garlick** [comment]
PACKAGE_VERSION and PACKAGE_NAME are expanded when configure is created.  So configure can be run outside a git tree, but not autogen.sh.  That seems correct to me.  You?

I don't have more queued up as yet so I would be fine if this were merged, provided you're ok with all that's being proposed here.

**Comment by grondo** [comment]
Yeah, that seems ok to me. Wonder if `autogen.sh` should be excluded from the dist. (Maybe it is already, sorry I didn't check)

**Comment by grondo** [comment]
> Wonder if autogen.sh should be excluded from the dist. (Maybe it is already, sorry I didn't check)

Yeah, obviously it isn't in EXTRA_DIST or anything so it doesn't get added to the dist.

(sorry a bit slow today)

This seems good to merge

**Comment by grondo** [comment]
Hrm. I pressed merge button. But if PACKAGE_VERSION is only expanded when configure is created, then the version won't be updated between pulls in a working directory unless autogen.sh is manually run. i.e. I could be building tag 0.2, but if I forget to run autogen.sh (or it is unnecessary) it could seem like I'm running the same version. Not sure if this is a big problem or not...

**Comment by garlick** [comment]
Hmm, bummer.  Maybe we can think up something clever to do with [dist-hook](https://www.gnu.org/software/automake/manual/html_node/The-dist-Hook.html)?

**Comment by garlick** [comment]
I think we made things more reliable than they were before, though you're right this does still leave an opportunity for screwing things up.

Rather than playing with configure dependencies, maybe it would be better to create a script under flux-framework/distribution that can create a github release for any framework project.  E.g. `mkrelease.sh <tag>` would checkout `<tag>`, run run autogen, configure, make dist, and use the github API to upload the resulting tarball and release notes as described [here](https://developer.github.com/v3/repos/releases/#create-a-release).

If  that makes sense I could open an issue in flux-framework/distribution.

**Comment by grondo** [comment]
Let's open that issue and continue discussion there, rather than in this PR.

**Pull request merged**
