### PR TITLE
Move flux-lstopo to flux-hwloc lstopo

### PR DESCRIPTION
**Pull request by grondo**
This PR is not quite baked yet, but here for review.

A `flux hwloc lstopo` subcommand is added since `lstopo` seems to naturally fall under that subcommand anyway (doesn't make sense outside of `resource-hwloc`). 
'
Some small changes are that `flux hwloc lstopo` generates `console` output by default instead of graphical. However, extra options are passed on to `lstopo(1)` so you can use something `flux hwloc lstopo --of graphical`.

I also added a `flux hwloc topology` command to dump generated XML to stdout. This is useful to pass to other hwloc commands on stdin, or save full topology to a file.

I am seeing an occasional error:

```
****************************************************************************
* hwloc has encountered an out-of-order topology discovery.
* An object with cpuset 0x000000ff was inserted after object with 0x0000ff00
* Please check that your input topology (XML file, etc.) is valid.
****************************************************************************
``` 

I have to run this down.

### CODE REVIEW

**Comment by dongahn** [comment]
Nice consolidation!

Where does the error msg come from? From the service or the front end command? 

If this is from the tests using the fake xml files, can this be due to a version mismatch between the version of hwloc used to generate these test fake xml and the current version of hwloc used in flux? I guess not unless you guys updated hwloc recently.

Googling shows these errors are reported by others. It could be a bug within hwloc as well.

**Comment by garlick** [comment]
There might be some general inconsistency in where `flux_t` handle is closed in the subcommands.  It looks like they should not do it, because the command driver does it, but I think that all? off them are closing it except the one you just added?  Not sure why we're not segfaulting on a second close though.

**Comment by grondo** [comment]
@garlick, I think the `builtin_get_flux_handle` or whatever it is should be incrementing a reference count on the flux handle...

**Comment by grondo** [comment]
Just pushed a couple updates:
 - I was trying to compare `lstopo` output to a saved copy, but it appears different hwloc versions have different output formats (slightly). So simplify the test to avoid this
 - Add support for reloading the system topology with `flux hwloc reload` (no `DIR` arg)

**Comment by grondo** [comment]
Also, `hwloc` should be calling `flux_close` is `hwloc_topo_destroy()`? I'll look at this more later.

**Comment by garlick** [comment]
You're right, I see the refcount there, sorry.

You already have a `flux_close()` in `hwloc_topo_destroy()` to balance the `builtin_get_flux_handle()` in `hwloc_topo_create()` so never mind!

**Comment by grondo** [comment]
> Where does the error msg come from? From the service or the front end command?

@dongahn, AFAICS the error comes from the lstopo command. The error isn't reproducible, so I don't think it is version incompatibility. If I had to guess I'd guess that the concatenated hwloc xml output is being created in non-deterministic fashion between ranks, and one such combination is causing the error (?). At this point that is just a guess.

**Comment by grondo** [comment]
Travis build failed on one of the intermittent test failures (that I can't reproduce outside of travis, grr)

One last thing for this PR is that I noticed there is no `flux-hwloc(1)` manpage. Should there be? I'm fine with either writing a quick one now, or delaying that for later...

**Comment by garlick** [comment]
I'd vote for a quick one

**Comment by dongahn** [comment]
> One last thing for this PR is that I noticed there is no flux-hwloc(1) manpage. Should there be? I'm fine with either writing a quick one now, or delaying that for later...

I am sorry @grondo, I was the one who delayed this. Back then I thought we would soon populate other subcommands and that time came sooner than I anticipated :-), thanks!

It feels we won't add other subcommands for a while (until more is implemented in the service itself). I agree a quick one is good.

**Comment by grondo** [comment]
Ok, I pushed a simple manpage, but needs an editing pass

**Comment by grondo** [comment]
Hm, should I also quiet these messages from the `resource-hwloc.topo` service? 
```
[1454699332.733245] resource-hwloc.info[0]: resource-hwloc: loaded from 0
[1454699332.737355] resource-hwloc.info[0]: resource-hwloc: loaded from 2
[1454699332.741506] resource-hwloc.info[0]: resource-hwloc: loaded from 1
```

**Comment by grondo** [comment]
OK, this one is ready to merge I think, pending any comments (esp review the quickie manpage)

**Comment by lipari** [comment]
quickie man page looks fine to me.

**Comment by garlick** [comment]
Whoops this failed in the travis-ci gcc+install builder:
```
ok 1 - hwloc: save system lstopo
ok 2 - hwloc: each rank reloads a non-overlapping set of a node 
ok 3 - hwloc: every rank reloads the same xml of a node
ok 4 - hwloc: only one rank reloads an xml file
ok 5 - hwloc: return an error code on an invalid DIR
ok 6 - hwloc: return an error code on valid DIR, invalid files
ok 7 - hwloc: lstopo works
ok 8 - hwloc: lstopo subcommand passes options to lstopo
ok 9 - hwloc: topology subcommand works
not ok 10 - hwloc: reload with no args reloads system topology
#	
#	    flux hwloc reload &&
#	    flux hwloc lstopo > lstopo.out4 &&
#	    test_cmp lstopo.system lstopo.out4
#	
# failed 1 among 10 test(s)
1..10
flux-start: 1 (pid 50179) exited with rc=1
flux-start: 0 (pid 50178) exited with rc=1
FAIL: t2005-hwloc-basic.t
```
Here's the expanded output
```
ok 9 - hwloc: topology subcommand works
hwloc: topology subcommand works
expecting success: 
    flux hwloc reload &&
    flux hwloc lstopo > lstopo.out4 &&
    test_cmp lstopo.system lstopo.out4
--- lstopo.system	2016-02-05 19:28:49.045977748 +0000
+++ lstopo.out4	2016-02-05 19:28:50.069996549 +0000
@@ -1,4 +1,7 @@
-System (30GB total)
+System (59GB total)
   Machine L#0 + NUMANode L#0 (P#1 30GB) + Package L#0 + L3 L#0 (25MB)
     L2 L#0 (256KB) + L1d L#0 (32KB) + Core L#0 + PU L#0 (P#26)
     L2 L#1 (256KB) + L1d L#1 (32KB) + Core L#1 + PU L#1 (P#27)
+  Machine L#1 + NUMANode L#1 (P#1 30GB) + Package L#1 + L3 L#1 (25MB)
+    L2 L#2 (256KB) + L1d L#2 (32KB) + Core L#2 + PU L#2 (P#26)
+    L2 L#3 (256KB) + L1d L#3 (32KB) + Core L#3 + PU L#3 (P#27)
not ok 10 - hwloc: reload with no args reloads system topology
# failed 1 among 10 test(s)
1..10
```

**Comment by grondo** [comment]
Thanks @garlick, That is an actual failure so it needs to be investigated.

**Comment by grondo** [comment]
Oops I found one other thing to fix, currently `flux hwloc lstopo | head -1` causes unnecessary error message 
```
lstopo failed with status 0x000d
```

I'll fix the code to avoid an error on death by SIGPIPE.

**Comment by dongahn** [comment]
The manpage looks good. Just very minor suggests on the man page:

lstopo: Change Runs -> Run for consistency
reload: Change [RANK] -> [RANKS] for consistency?

**Comment by grondo** [comment]
@dongahn: Thanks!

**Comment by grondo** [comment]
Another problem. `lstopo(1)` seems to be segfaulting under `flux hwloc lstopo` for `flux start` sessions of size 5, 7, 8 and above (?)
```
 grondo@hype356:~/git/flux-core.git$ src/cmd/flux start --size=4 flux hwloc lstopo | wc -l
[1454711130.025435] broker.info[0]: nodeset: [0-3] (complete)
[1454711130.025488] broker.info[0]: starting initial program
[1454711130.282117] broker.info[0]: shutdown in 0.500s: Exited
273
 grondo@hype356:~/git/flux-core.git$ src/cmd/flux start --size=5 flux hwloc lstopo | wc -l
[1454711135.945697] broker.info[0]: nodeset: [0-4] (complete)
[1454711135.945765] broker.info[0]: starting initial program
flux: lstopo: Segmentation fault (core dumped)
[1454711136.299318] broker.info[0]: shutdown in 0.500s: Exited
flux-start: 4 (pid 140066) exited with rc=1
flux-start: 3 (pid 140062) exited with rc=1
flux-start: 2 (pid 140057) exited with rc=1
flux-start: 1 (pid 140056) exited with rc=1
flux-start: 0 (pid 140055) exited with rc=1
0
 grondo@hype356:~/git/flux-core.git$ src/cmd/flux start --size=6 flux hwloc lstopo | wc -l
[1454711148.531885] broker.info[0]: nodeset: [0-5] (complete)
[1454711148.531937] broker.info[0]: starting initial program
[1454711148.913537] broker.info[0]: shutdown in 0.500s: Exited
409
```

**Comment by grondo** [comment]
> Another problem. lstopo(1) seems to be segfaulting under flux hwloc lstopo for flux start sessions of size 5, 7, 8 and above (?)

Actually I went back to current master and still have the same problem, so I'm not sure this is a newly introduced issue. (Someone want to verify that for me? Try
```
flux start --size=5 flux lstopo
```

**Comment by grondo** [comment]
Ok, I forced a push with some minor updates (including @dongahn's `flux-hwloc(1)` changes)
Also added a bit of debug for Travis in case we hit the issue @garlick pointed out above.

I opened issue #547 for `lstopo` segfaults.

**Comment by grondo** [comment]
Darn, failed here in travis:
```
expecting success: 
    p=$(run_flux_jstat 15) &&
    test_must_fail run_timeout 4 flux wreckrun -i /bad/input -n4 -N4 hostname &&
    cat >expected15 <<-EOF &&
	null->null
	null->reserved
	reserved->starting
	starting->failed
	EOF
    cp output.15 output.15.cp &&
    kill -INT $p &&
    test_cmp expected15 output.15.cp
waitfile: wakeup
Error: input: /bad/input: No such file or directory
wreckrun: job 10 failed
--- expected15	2016-02-05 23:24:50.551388248 +0000
+++ output.15.cp	2016-02-05 23:24:50.551388248 +0000
@@ -1,4 +1,3 @@
 null->null
 null->reserved
 reserved->starting
-starting->failed
not ok 19 - jstat 15: jstat detects failed state
```

**Comment by garlick** [comment]
This change https://github.com/flux-framework/flux-core/commit/fa9939e2e4538e01bfc1a365fecd583eab4da538 addresses some unchecked kvs and hwloc calls, and ensures that a partial topo response cannot be returned if all the ranks haven't loaded their xml into the KVS yet (as might happen if the topo request is made first thing in the test).  It will return EAGAIN in that case.

**Comment by grondo** [comment]
Thanks! Added your commit with conflict fixups to this PR.

I'll adjust the initial `flux hwloc lstopo` to retry a couple times on failure in the t2005-hwloc-basic test.

**Comment by grondo** [comment]
I was able to verify @garlick's code via the following:
```
flux-141246) grondo@hype356:~/git/flux-core.git$ flux kvs unlink resource.hwloc.xml.2
(flux-141246) grondo@hype356:~/git/flux-core.git$ flux hwloc lstopo
[1454716754.143134] resource-hwloc.err[0]: only got 3 out of 4 ranks aggregated
flux: flux_rpc: Resource temporarily unavailable
(flux-141246) grondo@hype356:~/git/flux-core.git$ echo $?
1
```

Works as designed! Thanks!

**Comment by grondo** [comment]
OK, I pushed a first attempt at having `t2005-hwloc-basic.t` "pause" until it successfully runs `flux hwloc lstopo` It will run `flux hwloc lstopo` in a loop until successful for 5 attempts. The first test verifies a valid `lstopo.system` file.

**Comment by grondo** [comment]
I'm getting more failures in the `jstat` tests so I'll probably try to look into this weekend. Could be a wreckrun issue...

**Comment by grondo** [comment]
Ok, I shuffled some commits, squashed others, and removed the travis debug commit.

**Comment by garlick** [comment]
That looks pretty reasonable.  We'll want to revisit the hwloc synchronization but this looks good for now.  I'll merge once travis is happy.

**Comment by grondo** [comment]
Hmm, my test script needs a fix, but we did hit a case where `resource-hwloc` wasn't fully initialized at the start of the test script:
```
Found ./t/t2005-hwloc-basic.broker.log
[1454719122.445034] resource-hwloc.debug[0]: loaded
[1454719122.473039] broker.info[0]: nodeset: [0-1] (complete)
[1454719122.501616] resource-hwloc.debug[0]: 0: loaded
[1454719122.501990] resource-hwloc.err[0]: only got 1 out of 2 ranks aggregated
[1454719122.503198] broker.info[0]: shutdown in 0.500s: Exited
[1454719122.544612] resource-hwloc.debug[1]: loaded
```

**Comment by grondo** [comment]
Ok, I was apparently using a bashism in the test loop at the beginning of the script. Retrying...

**Comment by garlick** [comment]
Green!  Merge?

**Comment by grondo** [comment]
Hm, still have to implement "If not EXEC (lstopo) then TRY (lstopo-no-graphics)"

Though I was thinking, why didn't they just call `lstopo-no-graphics` `lstopo` and have it conflict with the package providing `lstopo`, or use alternatives?

**Comment by grondo** [comment]
OK, I just pushed experimental support for retrying lstopo-no-graphics if `exec ("lstopo")` returns `ENOENT`.

The work was a bit unsatisfying, as it seems the only really reliable way to determing if `lstopo` is available is to actually exec it, but I couldn't use `popen` since it uses `sh -c` and we'd get an error from the shell. So this work reimplements `popen` using `exec` directly to allow for silent retry.

I am still testing a little bit, but wanted to get feedback to ensure this appraoch is not unacceptable.

**Comment by grondo** [comment]
Latest push fixes the `t2005-hwloc-basic.t` test when `lstopo` command does not exist.

**Comment by grondo** [comment]
rebased on current master, squashed fixes for `flux-hwloc lstopo` together.

**Comment by grondo** [comment]
two more minor fixes:
 * Call `log_init ("flux-hwloc")` in `hwloc` subcommand for better error labeling
 * Add test for `flux hwloc lstopo` to ensure abnormal exit code of `lstopo` is returned to user

**Comment by garlick** [comment]
Is this one ready to go in?

**Comment by grondo** [comment]
Yes, if it is ACKed.

**Comment by garlick** [comment]
ACKed by me, does it need to wait for anybody else?

**Comment by grondo** [comment]
FYI - I just forced a rebase on current master.

It would be nice if @dongahn, @lipari, or @trws could also ack the changes here, but I don't think it is critical as I'm not sure the `lstopo` command this replaces was widely used or depended upon at this point.

**Comment by dongahn** [comment]
@grondo: I looked at some of the changes before and they were good. Are there any sub areas of this PR you want me to look at more closely?

**Comment by lipari** [comment]
Looks good to me!

**Comment by trws** [comment]
Yeah, this looks great.  Nice work @grondo!

**Comment by garlick** [comment]
Uh oh, on my TOSS 2 desktop:
```
$ ./flux hwloc lstopo
/dev/stdin:1: parser error : Document is empty

^
/dev/stdin:1: parser error : Start tag expected, '<' not found

^
Setting source XML file: Illegal seek
```

**Comment by grondo** [comment]
Curious, does `flux hwloc topology` return anything!?

**Comment by garlick** [comment]
Yes, like this (bulk of the middle snipped out):
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE topology SYSTEM "hwloc.dtd">
<topology>
  <object type="System" os_index="0">
    <object type="Machine" os_index="0" cpuset="0x00000fff" complete_cpuset="0x0
0000fff" online_cpuset="0x00000fff" allowed_cpuset="0x00000fff" local_memory="25
189249024">
      <page_type size="4096" count="6149719"/>
      <page_type size="2097152" count="0"/>
      <info name="DMIProductName" value="Precision WorkStation T5500  "/>
      <info name="DMIProductVersion" value=""/>
      <info name="DMIBoardVendor" value="Dell Inc."/>
      <info name="DMIBoardName" value="0CRH6C"/>

[snip]

set="0x00000400" online_cpuset="0x00000400" allowed_cpuset="0x00000400"/>
              </object>
            </object>
          </object>
          <object type="Cache" cpuset="0x00000800" complete_cpuset="0x00000800" 
online_cpuset="0x00000800" allowed_cpuset="0x00000800" cache_size="262144" depth
="2" cache_linesize="64" cache_associativity="8" cache_type="0">
            <object type="Cache" cpuset="0x00000800" complete_cpuset="0x00000800
" online_cpuset="0x00000800" allowed_cpuset="0x00000800" cache_size="32768" dept
h="1" cache_linesize="64" cache_associativity="8" cache_type="1">
              <object type="Core" os_index="10" cpuset="0x00000800" complete_cpu
set="0x00000800" online_cpuset="0x00000800" allowed_cpuset="0x00000800">
                <object type="PU" os_index="11" cpuset="0x00000800" complete_cpu
set="0x00000800" online_cpuset="0x00000800" allowed_cpuset="0x00000800"/>
              </object>
            </object>
          </object>
        </object>
      </object>
    </object>
  </object>
</topology>
```

**Comment by garlick** [comment]
Here's another error I am seeing:
```
$ lux hwloc lstopo
/dev/stdin:1: parser error : Start tag expected, '<' not found
e_linesize="64" cache_associativity="8" cache_type="1">
^
Setting source XML file: Illegal seek
flux-hwloc: lstopo: Exited with 1
```

**Comment by grondo** [comment]
Uhoh. Well I'll start looking for a fix, not exactly sure what is going on yet, but it appears the topology xml isn't getting sent to lstopo stdin in your cases above.

**Comment by grondo** [comment]
Or, in the 2nd example only part of the buffer is being sent?

**Comment by grondo** [comment]
Hm, `lstopo(1)` bug reading from a pipe?

```
$ flux hwloc topology > topo.xml
$ cat topo.xml | lstopo-no-graphics --if xml -i -
/dev/stdin:1: parser error : Start tag expected, '<' not found
e_linesize="64" cache_associativity="8" cache_type="1">
^
Setting source XML file: Illegal seek
$  lstopo-no-graphics --if xml -i - < topo.xml 
System (47GB)
  Machine L#0 (23GB)
    Socket L#0 + L3 L#0 (12MB)
[snip]
$ lstopo-no-graphics --if xml -i topo.xml 
System (47GB)
  Machine L#0 (23GB)
    Socket L#0 + L3 L#0 (12MB)
      L2 L#0 (256KB) + L1d L#0 (32KB) + Core L#0 + PU L#0 (P#0)
[snip]
```

**Comment by grondo** [comment]
Looks like they are trying to lseek on stdin??
```strace
open("/dev/stdin", O_RDONLY)            = 3
fstat(3, {st_mode=S_IFIFO|0600, st_size=0, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f6119690000
read(3, "<?xml version=\"1.0\" encoding=\"UT"..., 16384) = 16384
lseek(3, 0, SEEK_CUR)                   = -1 ESPIPE (Illegal seek)
lseek(3, 18446744073709531136, SEEK_SET) = -1 ESPIPE (Illegal seek)

```

**Comment by garlick** [comment]
Wow, lame.

**Comment by trws** [comment]
...
Wow...

How on earth did that work with the regular lstopo? Is this something 
they only do in the no-graphics version?

**Comment by grondo** [comment]
> Is this something they only do in the no-graphics version?

No I was only using -no-graphics version because I wanted to show output on console (and also for some reason lstopo graphical output crashes my window manager, not sure why yet but I learned quickly not to type `lstopo`)

Seems to only happen on @garlick's TOSS2 desktop. I still have to compare versions to hype where I swear it works (also it obviously works on Travis version of lstopo).

**Comment by grondo** [comment]
Apparently same version on hype and on @garlick's machine, but `lstopo` works on hype... Something else going on here. I'll keep poking.

**Comment by garlick** [comment]
I upgraded libxml2 from `libxml2-2.7.6-20.el6.x86_64` to `libxml2-2.7.6-20.el6_7.1.x86_64` and that seems to have solved the problem.  Shall we call it "not our problem"?

**Comment by grondo** [comment]
For now that works for me. If it turns out to be a problem for someone else we can always add code to write out to a file like `flux lstopo` used to do. (But for now that is probably low priority)

**Pull request merged**
