### PR TITLE
implement flux_open()

### LINKED ISSUE #178: implement generic flux_open()
Implement a generic handle create/destroy function that selects the back end handle implementation by parsing the URI argument:
```
/* Open flags
 */
enum {
    FLUX_O_TRACE        = 1,    /* send message trace to stderr */
    FLUX_O_COPROC       = 2,    /* start reactor callbacks as coprocesses */
};
/* Create/destroy a broker handle.
 * The 'uri' scheme name selects a handle implementation to dynamically load.
 * The rest of the URI is parsed in an implementation-specific manner.
 * A NULL uri selects the "local" implementation with socket path derived
 * from the FLUX_TMPDIR environment variable.
 */
flux_t flux_open (const char *uri, int flags);
void flux_close (flux_t h);
```

### PR DESCRIPTION
**Pull request by garlick**
This PR adds `flux_open()` and `flux_close()` calls that take a URI argument.  The URI _scheme_ selects a handle implementation (called a _connector_), which is dynamically loaded.

There is only one connector that is exported in this way - the API socket one.  It is selected either by passing a NULL URI or specifying a URI with the scheme `local://path`, where `path` is the directory containing the UNIX domain socket.

`FLUX_FLAGS_*` were renamed to `FLUX_O_*` and uses of `flux_api_open()` and `flux_api_close()` should be replaced by `flux_open()` and `flux_close()`.  However the old interface still exists (until we get a PR that changes this in flux-sched landed).

Note: added `flux --uri` option which sets `FLUX_URI` which is interpreted by subcommands and passed as first argument to `flux_open()`. I did not alter the `flux.new` lua function so `flux-topo`, `flux-exec` were left out.

I will commit a sharness test shortly.

Resolves #178

### CODE REVIEW

**Comment by garlick** [comment]
I thought it was a bit strange having flux_open() parse environment variables but on second thought, maybe it should take its default uri from `$FLUX_URI`.  It is already parsing `$FLUX_CONNETOR_PATH`.

I'm thinking I'll close this PR and rework but @grondo do you agree/disagree?

This change will also avoid having to change lua binding's `flux.new`.

**Comment by grondo** [comment]
@garlick -- that feels fine to me, at least for now.

**Comment by garlick** [comment]
OK, I reworked as described,  added a sharness test for the `flux` command driver, and improved robustness of the `flux_open()` URI parsing.  I forced a push - hopefully that doesn't cause anyone any probs.

**Comment by grondo** [comment]
Nice. Thanks for adding tests!

So is the basic strategy for `flux_open()` to pick off the URI *scheme* name and look for *scheme*.so in `FLUX_CONNECTOR_PATH`?

**Comment by garlick** [comment]
correct except if `FLUX_CONNETOR_PATH` is unset, it uses `$(libdir)/flux/connectors`

**Comment by grondo** [comment]
Ok, looks and tested good.

**Pull request merged**
