### PR TITLE
libsdprocess: minor fixups

### PR DESCRIPTION
**Pull request by chu11**
Pulling out some minor libsdprocess fixups from #4070 and a forthcoming branch about systemd properties.

### CODE REVIEW

**Comment by chu11** [comment]
re-pushed, fixing up a LGTM issue

**Review by grondo — APPROVED** [review]
This looks fine to me. Only suggestion would be to add a  comment about why the `sd_bus_match_signal_async()` function is not safe to use (so we don't forget), but I consider that as optional, so approving.

**Comment by chu11** [comment]
> This looks fine to me. Only suggestion would be to add a comment about why the sd_bus_match_signal_async() function is not safe to use (so we don't forget), but I consider that as optional, so approving.

Thanks!  I'll leave out a comment.  It ends up that most of `libsdprocess` is synchronous, the lingering async was more of an accidental addition (assumed cut & paste).

**Comment by grondo** [comment]
Ok, that makes sense!

**Pull request merged**
