### PR TITLE
spack: add flux-core container build

### PR DESCRIPTION
**Pull request by vsoch**
Not multi-stage build yet because we do not have copy view, only symlink! I tested running a piece of the tutorial in here and the basics worked!

Signed-off-by: vsoch <vsoch@users.noreply.github.com>

### CODE REVIEW

**Comment by grondo** [comment]
Thanks! Before merging the branch will need to be rebased to avoid the merge commit and please squash the two commits with identical messages. 

Also, for consistency we try to use the imperative for commit messages "add" instead of "adding" for example. See [RFC 1 Patch Requirements ](https://flux-framework.readthedocs.io/projects/flux-rfc/en/latest/spec_1.html#patch-requirements)

**Comment by vsoch** [comment]
Gotcha! It’s not ready for review yet but I’ll fix it up when it is.

**Comment by vsoch** [comment]
Okay this is ready for review! And I think I did the commit right this time. It looks like they are some "warning: this will deprecate with spack 0.0.19" - specifically the format for the concretizer in the spack.yaml, but we're not there yet, so my preference is to maintain the current convention (which we know works) until it's forced.

**Review by grondo — APPROVED** [review]
LGTM! You are the spack expert so we trust your judgement there!

I'm going to tweak the PR title since it will be used in the release notes, then set the MWP flag. Thanks!

**Pull request merged**
