### PR TITLE
Update NEWS.md, AUTHORS for flux-core 0.7.0

### LINKED ISSUE #1019: 0.7.0 Release Notes
Just a place holder to create 0.7.0 release notes. I'll work on this a little later if someone doesn't beat me to it.

### PR DESCRIPTION
**Pull request by grondo**
This is a placeholder PR to be merged once we are ready to tag 0.7.0 and people are happy with the NEWS file. If we merge a few more fixes onto master before 0.7.0 tag, it will be easy to add appropriate NEWS entries to this branch and rebase the result.

Fixes #1019

### CODE REVIEW

**Comment by garlick** [comment]
Looks great, thanks for putting this together.

**Comment by dongahn** [comment]
Thanks @grondo!

**Comment by grondo** [comment]
Ok, I think this is ready to go in, and then we can tag 0.7.0.

However, will we also need a new release of flux-sched to work with this release? I'll do some testing to ensure there aren't any changes that will be required in flux-core for the flux-sched package.

**Comment by garlick** [comment]
The wire protocol has changed in flux-core (userid, rolemask fields) since the last flux-sched release, so yes we should probably get a flux-sched tag soon, otherwise latest sched release won't work with latest core release.

**Comment by garlick** [comment]
I misspoke above - the problem would be if we pushed out a package of flux-core-0.7.0 without updating the flux-sched package.  We could just rebuild the current flux sched tag, or hold off building packages if for some reason it's not convenient to tag flux-sched right now...

(Which is probably obvious to all concerned, but I just noticed my statement was not quite right so I felt I'd better set the record straight!)

**Comment by grondo** [comment]
> We could just rebuild the current flux sched tag, or hold off building packages if for some reason it's not convenient to tag flux-sched right now...

> And I don't think the protocol changes would be a problem. It's the API changes that may be.

Yeah, I don't think current flux-sched tag can be built against flux-core-0.7.0 due to kvs API changes (though IIRC it only affects the simulator)

**Comment by grondo** [comment]
Ok, updated date for 0.7.0 release to today. After this is merged I'll tag and hope for the best.

**Comment by grondo** [comment]
Just realized I put the wrong date in the NEWS file. Sorry!

**Pull request merged**
