### PR TITLE
Add library versioning support

### PR DESCRIPTION
**Pull request by chu11**
This is an initial attempt at library versioning support.  A very basic one, where prior to release, the appropriate version numbers would have to be updated in configure.ac.

### CODE REVIEW

**Comment by grondo** [comment]
Yes, this is definitely a good starting point. However, it will be difficult to ensure the current, revision and age are kept up to date before I release, and are correct given the number of libraries involved -- I wonder if there is some way to automate it? (I was going to do a search to determine if anyone else had an approach or solution for that)

Also since the version information has been split per installed library, would it make more sense to move the version info into the Makefile.am that builds each library? Or do you think it is probably less confusing to keep them all together? (honestly not sure which is better, so I'm fine with the current approach)

**Comment by chu11** [comment]
rebased

**Comment by chu11** [comment]
Hit a valgrind error, which clearly isn't due to this PR.  This one looks sort of new.

```
==31289== Memcheck, a memory error detector
==31289== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==31289== Using Valgrind-3.13.0 and LibVEX; rerun with -h for copyright info
==31289== Command: /usr/src/src/broker/.libs/flux-broker --shutdown-grace=4 /usr/src/t/valgrind/valgrind-workload.sh 10
==31289== 
hwloc x86 backend cannot work under Valgrind, disabling.
FLUX_URI=local:///tmp/flux-HKDorI
==31289== 
==31289== HEAP SUMMARY:
==31289==     in use at exit: 6,346,893 bytes in 182 blocks
==31289==   total heap usage: 958,988 allocs, 958,806 frees, 223,716,181 bytes allocated
==31289== 
==31289== 6,310,060 (16 direct, 6,310,044 indirect) bytes in 1 blocks are definitely lost in loss record 102 of 102
==31289==    at 0x4C2FA3F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==31289==    by 0x4C31D84: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==31289==    by 0x4E87EE9: ev_realloc (ev.c:1741)
==31289==    by 0x4E8CA58: ev_idle_start (ev.c:4611)
==31289==    by 0x4E61630: then_context_start (future.c:180)
==31289==    by 0x4E61630: post_fulfill.isra.6 (future.c:346)
==31289==    by 0x4E5E779: response_cb (rpc.c:170)
==31289==    by 0x4E597A6: call_handler (msg_handler.c:229)
==31289==    by 0x4E59EB8: dispatch_message (msg_handler.c:246)
==31289==    by 0x4E59EB8: handle_cb (msg_handler.c:322)
==31289==    by 0x4E87D12: ev_invoke_pending (ev.c:3314)
==31289==    by 0x4E8B2D8: ev_run (ev.c:3717)
==31289==    by 0x4E58952: flux_reactor_run (reactor.c:140)
==31289==    by 0xB7C910F: mod_main (job.c:938)
==31289==    by 0x1142EB: module_thread (module.c:158)
==31289==    by 0x55BA6DA: start_thread (pthread_create.c:463)
==31289==    by 0x636188E: clone (clone.S:95)
==31289== 
{
   <insert_a_suppression_name_here>
   Memcheck:Leak
   match-leak-kinds: definite
   fun:malloc
   fun:realloc
   fun:ev_realloc
   fun:ev_idle_start
   fun:then_context_start
   fun:post_fulfill.isra.6
   fun:response_cb
   fun:call_handler
   fun:dispatch_message
   fun:handle_cb
   fun:ev_invoke_pending
   fun:ev_run
   fun:flux_reactor_run
   fun:mod_main
   fun:module_thread
   fun:start_thread
   fun:clone
}
==31289== LEAK SUMMARY:
==31289==    definitely lost: 16 bytes in 1 blocks
==31289==    indirectly lost: 6,310,036 bytes in 96 blocks
==31289==      possibly lost: 0 bytes in 0 blocks
==31289==    still reachable: 36,321 bytes in 83 blocks
==31289==         suppressed: 520 bytes in 2 blocks
==31289== Reachable blocks (those to which a pointer was found) are not shown.
==31289== To see them, rerun with: --leak-check=full --show-leak-kinds=all
==31289== 
==31289== For counts of detected and suppressed errors, rerun with: -v
==31289== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 1 from 1)
not ok 1 - valgrind reports no new errors on single broker run
```

**Comment by chu11** [comment]
rebased

**Comment by garlick** [comment]
Thanks - I'll go ahead and merge this and we can revisit if/when we come up with a more nuanced process.  Thanks @chu11!

**Pull request merged**
