### PR TITLE
fix uninterruptible hang when attached to terminated jobs with -o pty

### PR DESCRIPTION
**Pull request by grondo**
This PR fixes the issues described in #4005 with two updates to the pty client code:

 1. Terminate and detach the pty client on error response from a pty write message. It is unlikely things will get any better, and since the forced detach character `^\` requires a response from the server, trying to stay "connected" just causes the client to get stuck with no way out.
 2. Add periodic zero-length writes from the client to act as keepalives. This prevents a `flux job attach` to a job with a pty from hanging forever when there is no client activity and the remote is killed (e.g. after a timeout or other error)

Now this construct doesn't hang:
```console
$ flux mini alloc -N2 -n2 -o exit-timeout=1 sh -c 'flux overlay disconnect 1 && sleep inf'
flux-overlay: asking rank 0 to disconnect child rank 1
4.063s: flux-shell[0]: stderr: flux-shell: FATAL: doom: rank 1 exited and exit-timeout=1s has expired
                     4.063s: flux-shell[0]: FATAL: doom: rank 1 exited and exit-timeout=1s has expired
                      4.065s: job.exception type=exec severity=0 rank 1 exited and exit-timeout=1s has expired
                              flux-job: task(s) exited with exit code 1
[detached: remote pty disappeared]
$
```

### CODE REVIEW

**Comment by grondo** [comment]
Hm, looks like I broke the basic `flux terminus` tests. I'll look into that.

**Comment by grondo** [comment]
Ok, fixed the issue causing failures in the basic `flux terminus` tests.

Coverage is low because a larger than average amount of error handling code was touched.

**Review by garlick — APPROVED** [review]
LGTM!

**Comment by grondo** [comment]
Thanks!

**Pull request merged**
