### PR TITLE
job-manager: add events journaling for job-manager.events stream

### PR DESCRIPTION
**Pull request by chu11**
Per discussion in #3209, add a journal of eventlog entries that can be replayed to any new listeners that wish to stream events.  This is built on top of PR #3236 

I don't think that any of the code changes are remarkably surprising, just a few things that are interesting:

- b/c the `annotations` object of a job can change, we have to  `json_deep_copy()` job annotations that go into the journal so they can be preserved.

- i made the maximum journal length configurable.  The default is 1000 entries, which translates to 100-125 jobs on average (8 entries for a typical successful job, not counting any extra annotations that may come from the scheduler).  Dunno if this is too small?  Would we want longer?

- had to update how I test, since simply grepping in a listener stream will no longer work (i.e. i may see multiple "cleanup" events, some possibly from a prior job than the one in a specific test).

- b/c of the journaling, I don't really need to synchronize on the `job-manager.events.listeners` stat anymore.  I could remove the stat, but left it in there for the time being since it doesn't hurt to have it there.

### CODE REVIEW

**Comment by chu11** [comment]
hmmm one builder failed with `not ok 4 - quorum reached on instance with 3 TBON levels`

```
expecting success: 
	echo "[0-7]" >full3.exp &&
	flux start -s8 ${ARGS} ./qget.sh >full3.out &&
	test_cmp full3.exp full3.out

flux-start: 1 (pid 25790) Killed
flux-start: 0 (pid 25789) Killed
not ok 4 - quorum reached on instance with 3 TBON levels
```

**Comment by grondo** [comment]
> i made the maximum journal length configurable. The default is 1000 entries, which translates to 100-125 jobs on average (8 entries for a typical successful job, not counting any extra annotations that may come from the scheduler). Dunno if this is too small? Would we want longer?

1000 entries seems small, especially since bulk ingest rate is ~500-600 jobs per second. Is it ok if the journal only contains a second or so worth of entries? (Sorry I haven't been following closely enough here to understand how much time we expect job-info or other journal consumers to require to "catch up")

**Comment by chu11** [comment]
> 1000 entries seems small, especially since bulk ingest rate is ~500-600 jobs per second. Is it ok if the journal only contains a second or so worth of entries? (Sorry I haven't been following closely enough here to understand how much time we expect job-info or other journal consumers to require to "catch up")

I suppose we could add a timer watcher that'll clear any entries > time N on a regular basis.  Perhaps we can do that after this PR as an extra feature.

**Comment by garlick** [comment]
I was asking for use cases a while back but I don't think we quite got there.  One is simply loading the modules in series in rc1 (first job-manager, then job-info).  Another is reloading job-info.  What else?

Is it safe to scan the KVS to recover historical job data, then start applying events from the journal where there could be overlap?  is it sufficient to ensure that event timestamps don't go backwards?

**Comment by grondo** [comment]
Another question is if this interface could be useful by some other flux component, e.g. some kind of monitoring tool or dashboard? Or is this really just a job-manager/job-info service?

**Comment by chu11** [comment]
> I was asking for use cases a while back but I don't think we quite got there. One is simply loading the modules in series in rc1 (first job-manager, then job-info). Another is reloading job-info. What else?

To me, the biggest win so far is eliminating some raciness possibilities (err probabilities?), making things easier.  You can see this in my last commit in the series, where I remove the wait listener checks.

> Is it safe to scan the KVS to recover historical job data, then start applying events from the journal where there could be overlap?

I'm not quite following.

> is it sufficient to ensure that event timestamps don't go backwards?

Everything in the journal goes through `event_job_post_pack()`, so I believe so.

**Comment by garlick** [comment]
How does `job-info` build its hashes of jobs initially?  I was assuming it scanned the KVS like job-manager does.

**Comment by chu11** [comment]
> How does job-info build its hashes of jobs initially? I was assuming it scanned the KVS like job-manager does.

Oh, that's what you're referring to.  Yes, its just like job-manager.

Getting to your prior question.

> Is it safe to scan the KVS to recover historical job data, then start applying events from the journal where there could be overlap?

For priority & annotation changes, it is safe b/c priority / annotation changes won't be updated unless the timestamp is newer.

I haven't started on #3234, so the answer is not-yet b/c all state transitions come from the `job-state` events and data is loaded from the KVS.

**Comment by chu11** [comment]
rebased & re-pushed, tweaking for fact I can take advantage of newer jansson version

**Comment by garlick** [comment]
I left a long comment in #3209 about the journal design.  I think we need a per-job sequence number in the event envelope (where we add the job ID), to be able to reliably replay the KVS info and "merge in" the journal without duplicating events.  See what you think and let's discuss it over there, then come back here and decide what to do.

**Comment by chu11** [comment]
closing, as the "steps" to get here are going to be different as we work on the things discussed in #3209.

**Pull request closed without merging**
