### PR TITLE
job-list: split out job information into new files                                                                                          

### PR DESCRIPTION
**Pull request by chu11**
This is a general refactoring PR.                                                                                                           
                                                                                                                                            
I actually did some similar refactoring in #4336

I did some similar refactoring in a (now tabled) PR for #4404

@garlick commented on some potential refactoring in #4555                                                                                   

So thus this refactoring, and why I put it in a separate PR.
                                                                                                                                            
I could add some unit tests to capture some worst offending failure cases (e.g. like jobspec that is just a curly brace), but didn't given its limited coverage increase.  Some of this is already handled in sharness tests.

### CODE REVIEW

**Comment by grondo** [comment]
I thought the idea proposed in #4555 was to split out some of the common R and jobspec "parsing" into a reusable library (i.e. that could eventually be reused by some other facility in flux-core if necessary) Is this just a stepping stone to that goal since here it seems like all that is done so far is to move some code into a new source file?

**Comment by chu11** [comment]
yeah, this is just moving in that general direction.  The main reason I did this is b/c I sort of had the same "move data structures into new files" in two separate PRs, so I felt this refactoring was sort of necessary to avoid more conflicts going forward.

**Comment by grondo** [comment]
Ok, that seems reasonable. We should indeed try to refactor the jobspec/R parsing into 'struct job' into reusable code with unit tests at some point though.

**Review by grondo — APPROVED** [review]
Since the only purpose here is to move code to a new file, seems good to me.

**Pull request merged**
