### PR TITLE
kvs: reduce cache expiration overhead

### PR DESCRIPTION
**Pull request by chu11**
This is built on top of #3663.  I'll just cut & paste the commit message here:

```
Problem: During profiling runs the cache_expire_entries() function
is shown to be a minor bottleneck.  It appears to be busy due to a
call to zhashx_keys().  The function creates a zlistx of all keys
in the primary cache's hash.  This requires iterating through the
entire hash (all hash buckets, including empty ones), and allocating
memory for every string added to the zlistx.

Solution: Support a list 'entries_list' which maintains a list of
all current cache entries.  When cache_expire_entries() is called,
simply iterate through this list instead.  It eliminates the iteration
of the entire cache hash and eliminates the excess memory allocations.
```

After doing some benchmark tests, this was overall deemed a questionable "win" on performance.  At best it was even, at worst maybe slightly worse?  Effectively we add a little bit of list management overhead to common paths (`cache_insert()`, `cache_remove()`) for a faster uncommon path (`cache_expire_entries()`, which is called once in awhile via `sync_cb()`).

I was ready to just punt this as a possible PR, but @garlick commented in #3615 that we should atleast look at it b/c maybe it'll be a net win beyond the benchmarks we're currently playing with.

### CODE REVIEW

**Review by garlick — COMMENTED** [review]
Rather than put all entries on the list, what if you only put on entries that are eligible for purging (not dirty and valid)?

I think more or less the same algorithm for the LRU in the broker's content cache could be followed here.  E.g. set the lastused_time when item goes on the front of the list.  Purge from the back of the list until items are encountered that are younger than the expiration age threshold?

That would eliminate(?) the scanning past ineligible items.

**Comment by chu11** [comment]
> I think more or less the same algorithm for the LRU in the broker's content cache could be followed here. E.g. set the lastused_time when item goes on the front of the list. Purge from the back of the list until items are encountered that are younger than the expiration age threshold?

Ahh, I like this idea.

**Comment by chu11** [comment]
While trying to implement the LRU idea, I came to the conclusion that the original commit in this PR is the one we should consider.  Given the relatively small impact this change would have (given current benchmarks we use), I think adding all of the additional logic isn't worthwhile.  We have a dirty flag, valid flag, reference counters, and the `lastuse_time` is set for the first time either through `cache_lookup()` OR `cache_expire_entries()`.  The fact it could be set for the first time in `cache_expire_entries()` adds some extra logic as well.

We could alter logic of how `lastuse_time` is set, but given the relatively low impact `sync_cb()` is already, I think we should just consider this minor addition as it is without thinking about it too hard.

**Review by garlick — APPROVED** [review]
OK sounds good!

**Comment by chu11** [comment]
@garlick Thanks.  Before setting MWP just want to double check that we're ok with this just based on code review.  B/c I haven't been able to see a performance benefit on any benchmark we use.  But I think reducing the `sync_cb()` overhead is a good idea given it does occur every few seconds or so.

**Comment by garlick** [comment]
Yes I think it is ok to go in.

**Pull request merged**
