### PR TITLE
kvs: Misc cleanup & bug fixes

### PR DESCRIPTION
**Pull request by chu11**
Spliced out of a bigger PR for #1239.  Nothing too exciting.

### CODE REVIEW

**Comment by garlick** [comment]
LGTM

**Comment by chu11** [comment]
bad coverage on diff, unsurprising given hard to reach error paths.  hit two write errors on builds and a hang, unclear when/how builder hung.  Restarting.

**Comment by chu11** [comment]
rebased and re-pushed, couple of builds had write-errors, restarted them and seems everything has passed now

**Comment by garlick** [comment]
Great - merging.  Thanks!

**Pull request merged**
