### PR TITLE
Update NEWS for v0.17.0

### LINKED ISSUE #2978: flux-core v0.17.0 release notes
We had talked about doing a release of flux-core soon to make available some recent usability improvements.

This issue tracks generating the updated NEWS.md for this release.

### PR DESCRIPTION
**Pull request by grondo**
First cut at a NEWS.md entry for v0.17.0, quickly done. Will update again before tagging and as more PRs go in, but wanted to get a stake in the ground.

If people want to make an editing pass or change wording, feel free to push to this branch.

Fixes #2978

### CODE REVIEW

**Comment by garlick** [comment]
Wow!  This is a feature packed release!  We've made a lot of progress since the last one.

**Comment by grondo** [comment]
Ok, I've pushed an updated with recently merged PRs, and hopefully didn't forget anything.

**Comment by garlick** [comment]
The markup rendering is a bit off:   Headings are shown as bullet list items.  The entry for guest service registration is being partially eaten due to html interpretation.

https://github.com/flux-framework/flux-core/blob/abf9478638138f7a1681d8874431b875ee912d93/NEWS.md

**Comment by grondo** [comment]
Oh yeah, I didn't do the header formatting right. Will push a fix.

**Comment by grondo** [comment]
> Edit: also, buillets are double-spaced, which is inconsistent with other releases

This was due to incorrect formatting of headings, should be fixed now.

Thanks!

**Comment by grondo** [comment]
Ok, unless there is anything else that needs to go into this release, shall we set MWP?

**Comment by garlick** [comment]
Sounds good!

**Comment by grondo** [comment]
Ok, I did some extra testing on fluke and multi-user sanity check under flux-o-rama. No surprises. Setting MWP.

**Comment by grondo** [comment]
I pushed a tag for v0.17.0 after this merge. :crossed_fingers: that the auto-deploy actually works.

**Pull request merged**
