### PR TITLE
flux-comms: remove obsolete command

### PR DESCRIPTION
**Pull request by garlick**
Split off of #3207.

This PR removes `flux comms` and updates sharness tests to use `flux getattr` or the RPC test program to maintain coverage of `overlay.lspeer` and `cmb.panic` broker serviice methods.

Since monitoring is moving to the resource module, `flux resource` can take over the `flux comms up` functionality later on.

### CODE REVIEW

**Comment by grondo** [comment]
I'm getting failures in `t0001-basic.t`:
```
expecting success: 
	flux start -o,-Sbroker.rc1_path=,-Sbroker.rc3_path= --size=1 		/home/grondo/git/flux-core.git/t/request/rpc overlay.lspeer </dev/null | jq >idle.out &&
	test_must_fail grep 'idle' idle.out

jq - commandline JSON processor [version 1.5-1-a5b5cbe]
Usage: jq [options] <jq filter> [file...]

	jq is a tool for processing JSON inputs, applying the
	given filter to its JSON text inputs and producing the
	filter's results as JSON on standard output.
	The simplest filter is ., which is the identity filter,
	copying jq's input to its output unmodified (except for
	formatting).
	For more advanced filters see the jq(1) manpage ("man jq")
	and/or https://stedolan.github.io/jq

	Some of the options include:
	 -c		compact instead of pretty-printed output;
	 -n		use `null` as the single input value;
	 -e		set the exit status code based on the output;
	 -s		read (slurp) all inputs into an array; apply filter to it;
	 -r		output raw strings, not JSON texts;
	 -R		read raw strings, not JSON texts;
	 -C		colorize JSON;
	 -M		monochrome (don't colorize JSON);
	 -S		sort keys of objects on output;
	 --tab	use tabs for indentation;
	 --arg a v	set variable $a to value <v>;
	 --argjson a v	set variable $a to JSON value <v>;
	 --slurpfile a f	set variable $a to an array of JSON texts read from <f>;
	See the manpage for more options.
2020-09-15T15:29:38.256931Z broker.err[0]: rc2.0: /home/grondo/git/flux-core.git/t/request/rpc overlay.lspeer Broken pipe (rc=141) 0.0s
flux-start: 0 (pid 8459) exited with rc=141
not ok 11 - flux-start with size 1 has no peers
```

**Comment by garlick** [comment]
I pushed a couple of fixes as discussed offline
* Eliminate use of jq where it was failing just (use python oneliner instead of rpc test driver)
* Use grep -x to check for exact match where `flux comms info | grep size=N` was replaced with `flux getattr size | grep N`

**Review by grondo — APPROVED** [review]
LGTM!

Looks like `src/cmd/.gitignore` also needs an update (long before this PR though). Not sure if you just want to tack this onto your PR?

```diff
diff --git a/src/cmd/.gitignore b/src/cmd/.gitignore
index 83338367e..52a5dfdd0 100644
--- a/src/cmd/.gitignore
+++ b/src/cmd/.gitignore
@@ -1,18 +1,15 @@
 /flux
-/flux-comms
-/flux-comms-stats
-/flux-event
-/flux-jobspec-validate
 /flux-keygen
 /flux-kvs
 /flux-logger
 /flux-module
-/flux-mping
 /flux-ping
-/flux-snoop
 /flux-start
-/flux-start-screen
-/flux-start-single
-/flux-start-srun
-/flux-up
+/flux-exec
+/flux-event
+/flux-aggregate
+/flux-queue
+/flux-job
+/flux-terminus
+/python
 /builtin-cmds.c
```

**Comment by grondo** [comment]
Restarted the Ubuntu 20.04 build which timed out (hm, haven't seen that one in awhile)

**Comment by garlick** [comment]
I'll go ahead and set MWP in case this passes.  Thanks!

**Pull request merged**
