### PR TITLE
job-info: Remove t_priority, t_sched list attributes

### LINKED ISSUE #3395: job-info: remove t_priority list attribute, maybe more?
per initial discussion in https://github.com/flux-framework/rfc/pull/278

`t_priority` is ambiguous since it is a job state that can be reached multiple times.  as is `t_sched`

so the question becomes, if we're removing multiple `t_<STATE>` fields, should we remove more / all?

Edit: depends on PR #3371, as that PR is the one that introduces the `flux-restart` event and the potential for a cycle

### PR DESCRIPTION
**Pull request by chu11**
The priority and sched state can be entered multiple times, so do not store the timestamp of when we entered the states, as the
timestamp can be ambiguous.

Remove from all callers, including flux-jobs, job-archive, bindings, documentation and tests.

Fixes #3395

### CODE REVIEW

**Comment by chu11** [comment]
While somewhat independent of some PRs I'm going to post shortly, I wanted to separate out this PR because:

A) The most important change in this PR is the fact that I alter the `job-archive` database schema.  So I want to make sure this won't affect @cmoussa1's work.

B) Since I'm in the process of altering the database schema of `job-archive`, we may as well discuss if we want to add anything new in the database schema that would make life easier for the flux accounting team.

**Review by garlick — APPROVED** [review]
Looks fine!  Feel free to set MWP if @cmoussa has no prob with the schema change.

**Comment by cmoussa1** [comment]
This LGTM - I don't see any changes needed from the flux-accounting end as of now since I am not using `t_sched` or `t_sched` anywhere. Thanks for checking in with me! 

> B) Since I'm in the process of altering the database schema of job-archive, we may as well discuss if we want to add anything new in the database schema that would make life easier for the flux accounting team.

I'm not sure if we've discussed it anywhere else (I think I mentioned it a while ago in #3136), but eventually having `nnodes` in the job-archive would be helpful. For now, I have been making the assumption of 1 rank per node; not sure if this will be okay in the future?

**Comment by grondo** [comment]
> I'm not sure if we've discussed it anywhere else (I think I mentioned it a while ago in #3136), but eventually having nnodes in the job-archive would be helpful. For now, I have been making the assumption of 1 rank per node; not sure if this will be okay in the future?

Is the `R` object available in job-archive? If so, `R` represents the actual resource set allocated to the job. Soon we'll have a `ResourceSet` Python class available to ingest and query the number of nodes or cores (or any other resource) from this object, so that might be a way to go as well.

**Comment by cmoussa1** [comment]
> Soon we'll have a ResourceSet Python class available to ingest and query the number of nodes or cores (or any other resource) from this object, so that might be a way to go as well.

Ah, okay. I think I might go this route then. Thanks!

**Comment by chu11** [comment]
> Is the R object available in job-archive? 

Yes, R is in the job-archive.  We had discussed before if any new fields need to be added for convenience.  But a `ResourceSet` would make parsing R a lot easier, so fields related to R probably won't be needed.

**Comment by chu11** [comment]
Since @cmoussa1 says ok, setting MWP

**Pull request merged**
