### PR TITLE
modules/kvs: add async fence operations

### PR DESCRIPTION
**Pull request by garlick**
Here's the split kvs_fence call discussed in #707 and #706.

I'll add the libpmi-server barrier completion callback after lunch.

### CODE REVIEW

**Comment by grondo** [comment]
Any way to test? Though I suppose blocking kvs_fence() tests must exercise the nonblocking calls from which the blocking call is made up...

**Comment by garlick** [comment]
Just added the pmi server change to this PR.

Tests coming but feel free to cherry pick what's here so far since
* as you pointed out kvs_fence is now implemented in terms of the two async fence halves
* flux-start and the t/pmi/simple.c test are now using the new pmi server interface

**Comment by grondo** [comment]
Ok, sounds great.

**Comment by grondo** [comment]
Sorry for a dumb question, is `pmi_simple_server_barrier_complete` idempotent? In `flux-start` it is called once per session, but since kvs_fence continuation will trigger for each call into barrier in the wrexecd case, it would be easiest to just call `barrier_complete` for every task (but could easily be done only for one task, too)

**Comment by garlick** [comment]
Not idempotent - when called again it would complete the next barrier which might be partially started.

Pondering...

**Comment by garlick** [comment]
Adding some details to hallway discussion just now, let's
* add a `local_procs` paramter to `pmi_simple_server_create()`, a count of local processes
* make `barrier_enter()` an optional callback; if NULL, the barrier completes by itself once `local_procs` enter the barrier.
* otherwise, the `barrier_enter()` is called once `local_procs` enter the barrier, and the barrier completes when `pmi_simple_server_barrier_complete()` is called

This means wrexecd calls fence once for all the local processes, and the count for the fence should be the number of nodes not the number of procs.

**Comment by grondo** [comment]
The `kvs_fence_finish` implementation confused me for a minute. Why is local `json_str` assigned here then immediately goes out of scope? Is the `json_str` arg required to be non-NULL for `flux_rpc_get`?

```C
int kvs_fence_finish (flux_rpc_t *rpc)
{
    const char *json_str;

    return flux_rpc_get (rpc, NULL, &json_str);
}
```

**Comment by grondo** [comment]
1 more Q: If barrier fails is there some way to pass that in to the pmi_simple_server, or is the expectation that the launcher will wrest control on any failure and be responsible for job termination?

**Comment by garlick** [comment]
Ah right we need that interface.  It doesn't do too good of a job on failures right now, but I figured that's probably the next step.  I'll go ahead and add a hook to abort the barrier.

**Comment by garlick** [comment]
That fence empty json payload in the response dates back to when all messages were required to have payloads long ago.   I'll go ahead and fix that as well here.

**Comment by garlick** [comment]
I misspoke on the fence (actually `kvs.commit` with the fence flag set).  There is a response payload, we just ignore it when parsing it from the exported interface.  It is not ignored in other circumstances.

The problem is that `flux_rpc_get()` treats an "unexpected payload" (NULL json arg, but payload present) as an error.

If we do fix that it's a much bigger change than would be appropriate for this PR.

**Comment by grondo** [comment]
No problem, but perhaps a comment in the code.

**Comment by garlick** [comment]
I squashed down this down quite a bit.  I'm OK with merging once the tests pass.

**Comment by garlick** [comment]
Hang on, rebasing on current master

**Comment by grondo** [comment]
OK, ready?

**Comment by garlick** [comment]
yes.

**Pull request merged**
