### PR TITLE
content-cache: avoid linear search for dirty blobs

### PR DESCRIPTION
**Pull request by garlick**
More content-cache fixes:
* replace bespoke doubly linked, embedded-node list implementation with equivalent vendored one from CCAN
* add a new list of entries that need to be stored, to avoid repeated linear searches in "batch" implementation
* minor cleanups/bug fixes

### CODE REVIEW

**Comment by garlick** [comment]
Something's not quite right here in the coverage output, so adding WIP while I correct.

**Comment by chu11** [comment]
nothing stood out after doing a skim, but this PR is a bit all over the place.  Perhaps should split up?  The title of this PR is `content-cache: avoid linear search for dirty blobs`, but I think only 1 commit is related to it?  The rest is refactoring or cleanup or code coverage additions?

**Comment by garlick** [comment]
Yeah that's a good point. OK, I'll have a go at splitting it up.

**Comment by garlick** [comment]
Rebased on #3645.  This PR just covers the last four commits.

**Review by chu11 — APPROVED** [review]
LGTM, nothing stood out to me.

**Comment by garlick** [comment]
Thanks!

**Pull request merged**
