### PR TITLE
add spell check for news, readme, and user facing code

### PR DESCRIPTION
**Pull request by vsoch**
Problem: the NEWS.md and other user (or developer) facing messages have erroneous spelling.
Solution: add a strong spell checker to be run on CI so we catch most of them.

We would want NEWS.md (that populates release notes) to not having spelling errors, and we also want to try to avoid them in user or developer facing message. Toward this goal, I was selective in choosing to run the spell checker for specific directories (and let me know if there are other ones I missed that should be checked).

There are a lot of spelling errors across the code, and I did a quick fix for some of the developer facing ones - I started fixing tests but realized it would probably take me all day, and this is not a top priority given that nobody typically sees it.

I do know there is a spell checker with the docs, but I'm redundantly adding this one because I've compared the two, and the one currently in use (runs via the Makefile) sometimes misses stuffs!

### CODE REVIEW

**Review by chu11 — APPROVED** [review]
LGTM.  My initial concern was over false positives but it looks like crate-ci is specifically only targetting common typos (vs the spellcheck in the docs which needs a validlist of valid words), so it seems perfect for the CI.

**Comment by chu11** [comment]
@vsoch hold off on merging ... i'll try to clean up more typos and push onto this

**Comment by vsoch** [comment]
Aye aye! 🦜 🏴‍☠️

**Review by garlick — COMMENTED** [review]
Woah nice and also :facepalm: !!!

This is great.  Couple changes needed:
- libev is vendored (copied in from external) so we should drop those changes
- spilt spelling fixes out to their own commit

**Comment by chu11** [comment]
doh, and this test didn't technically do what we wanted

```
test_expect_success 'dump ignores empty kvs directories' '                                                                                  
        flux kvs mkdir emtpy &&                                                                                                             
        flux dump -v foo3.tar &&                                                                                                            
        tar tvf foo3.tar >toc &&                                                                                                            
        test_must_fail grep empty toc                                                                                                       
'
```

**Comment by vsoch** [comment]
okay that's probably the best I can do - libev fixes are undone, and the CI change is separate from the spelling fixes.

**Comment by garlick** [comment]
Thanks!  One commit doesn't have a long description and the other one has a description that no longer matches what it does.  Shall I fix that up?  (Need an ack from @vsoch and @chu11 before I force push - don't want to clobber anybody!)

Also, @chu11 could you open issues on those broken tests so we don't forget to address them?

**Comment by vsoch** [comment]
ack! But wait for @chu11 to also confirm.

**Comment by chu11** [comment]
> Also, @chu11 could you open issues on those broken tests so we don't forget to address them?

Are you thinking I shouldn't fix those typos and we resolve in a different issue?  I just went ahead and fixed the typos.

**Comment by chu11** [comment]
@vsoch go ahead and fix your branch, I'll put my typo fixes somewhere else and you can just cherry pick it

**Comment by vsoch** [comment]
@chu11 I'm done, so @garlick I think you can go ahead and tweak the messages.

**Comment by garlick** [comment]
OK I'm on it.  @chu11 I might've been confused, thought you found tests that were broken due to typos that needed further analysis.   I can cherry pick them if that's what should happen.

**Comment by chu11** [comment]
> OK I'm on it. @chu11 I might've been confused, thought you found tests that were broken due to typos that needed further analysis. I can cherry pick them if that's what should happen.

The analysis is done ;-)   The typos make sure the tests function as intended.  In one case the `test_expect_sucess` just didn't do anything, the other we wanted to make sure that we did not grep a word and the typo made sure the test always passed.

**Comment by chu11** [comment]
my commit is on top here: https://github.com/chu11/flux-core/tree/chu_fix_typos 

still running `make -j16 check` and I should re-look it over to make sure I didn't do anything dumb.

**Comment by chu11** [comment]
we should probably do a todo item to setup false-positive checks and run this over everything.  I just picked a lot of code paths and did em ... was a little obsessive compulsive about it ... once you start .. can't stop.

**Comment by chu11** [comment]
oh and a todo item is to try and fix typos in libev, sharness, and ccan files :P

**Comment by garlick** [comment]
We should not fix typos in vendored code sice it complicates keeping the code up to date.   I'd submit them upstream if you find that sort of thing enjoyable :-)  Then we'll get em eventaully.

**Comment by garlick** [comment]
@chu11 would you mind breaking the test fixes out from the spelling fixes?

I realize they are just "Typos" but actually fixing a test ought to be called out separately IMHO

**Comment by garlick** [comment]
Also, @chu11, parsedatetime is vendored so those changes should be dropped.
Also this hunk should be "added"
```patch
diff --git a/src/common/liboptparse/optparse.c b/src/common/liboptparse/optparse
.c
index 8aa7ff8c4..6b8b31d4f 100644
--- a/src/common/liboptparse/optparse.c
+++ b/src/common/liboptparse/optparse.c
@@ -73,7 +73,7 @@ struct option_info {
     struct optparse_option * p_opt;   /* Copy of program option structure  */
     zlist_t *               optargs;  /* If non-NULL, the option argument(s) */
     const char *            optarg;   /* Pointer to last element in optargs */
-    int                     seq;      /* Sequence in which option was addd  */
+    int                     seq;      /* Sequence in which option was add  */
 
     unsigned int            found;    /* number of times we saw this option */
 
```

**Comment by chu11** [comment]
ahhh whoops didn't know parsedatetime was vendored

**Comment by chu11** [comment]
pushed to my branch (squashed, hope thats ok) removing parsedatetime typo fixes, the optparse mistake found above, and split out the test typo fixes.

**Comment by garlick** [comment]
Repushed!

@chu11 want to give this a once over before we set MWP?  I'll do the same.

**Comment by garlick** [comment]
Yep all good as far as I can see.

Seeing all those typos is a little depressing!  Am I a robot that just generates misspelled words all day?   Replace me with one of those clever AI chatbots please.

Just set MWP when you're happy @chu11

And thanks @vsoch, good cleanup.

**Comment by chu11** [comment]
once over looks good to me.  @vsoch set MWP whenever you're ready.

**Comment by grondo** [comment]
Wow, this is great! thanks everyone!

**Comment by vsoch** [comment]
I stumbled on this typos tool a few years ago - and I can confirm it's gotten better as time has passed. And yes it's really addictive - when I first add to a repository I can spend an hour or so fixing all the typos! But it's really satisyfing when it's all done, and I can rest assured I'm protecting future me from spelling mistakes.

**Pull request merged**
