### PR TITLE
configure: remove --disable-python

### PR DESCRIPTION
**Pull request by grondo**
Python bindings are a first-class tool in flux-core now, and checking for HAVE_PYTHON everywhere is getting cumbersome. This PR removes the --disable-python configure flag and makes python a hard requirement.

One question, I removed the bit of code that set an rpath in the broker for the location of libpython. 
```diff
diff --git a/src/broker/Makefile.am b/src/broker/Makefile.am
index a8543c37..548a4d53 100644
--- a/src/broker/Makefile.am
+++ b/src/broker/Makefile.am
@@ -57,14 +57,7 @@ flux_broker_LDADD = \
        $(top_builddir)/src/common/libpmi/libpmi.la \
        $(LIBPMIX)
 
-broker_ldflags = 
-
-if HAVE_PYTHON
-#allow the broker to find the python library at runtime
-broker_ldflags += -rpath $(PYTHON_PREFIX)/lib
-endif
-
-flux_broker_LDFLAGS = ${broker_ldflags}
+flux_broker_LDFLAGS =
 
 TESTS = test_shutdown.t \
        test_heartbeat.t \
```
The broker doesn't link against libpython, so I didn't see how it actually accomplished anything.

Maybe this rpath needs to be set on pymod? Anyway, I didn't hit any trouble removing it, but perhaps it is something that only crops up in environments with multiple pythons..

### CODE REVIEW

**Comment by grondo** [comment]
Oops, I may have typoed something in one of the Makefiles. Let me check on it...

**Comment by grondo** [comment]
Ok, fixed that typo. It would be good if @trws reviewed this PR specifically the change to remove -rpath on the broker.

**Comment by garlick** [comment]
@trws if this looks good to you, please push the button.

**Comment by trws** [comment]
I'm good with all of this, but admittedly a bit nervous about removing the rpath.  Perhaps have it, but only have it if the user explicitly specifies a path for python or something, or just on pymod?  The worry is that it's been pretty common to use a python other than the primary python on the system, it was the standard for us on toss2 and I know at least some users are still doing it.  Maybe I'm being over cautious, but having flux load the wrong python at runtime could cause some odd problems.

**Comment by grondo** [comment]
> The worry is that it's been pretty common to use a python other than the primary python on the system, it was the standard for us on toss2 and I know at least some users are still doing it. Maybe I'm being over cautious, but having flux load the wrong python at runtime could cause some odd problems.

I guess I was wondering why the broker was linked with the -rpath. I could be missing something fundamental, but the broker doesn't load or link with any python libraries or python code. Right now `pymod` is the only thing I can think of that actually links against libpython (besides the bindings themselves). So should the rpath actually be added to pymod.so?

**Comment by grondo** [comment]
Ok, I  will move the rpath to pymod.

**Comment by grondo** [comment]
Ugh. That broke make install but I'm not at my computer now. Will check on
it in a bit

**Comment by grondo** [comment]
> Ugh. That broke make install 

Ok, I can't believe I didn't know this until now, but `libtool` has its own `-rpath` option which is not exactly the same as the linker's `-rpath` option (it behaves differently between a program and a library). libtool gets confused if you supply `-rpath` on a module, so I'm going to try `-Wl,-rpath -Wl PATH` instead.

**Comment by garlick** [comment]
One builder failed with a write error on stdout, so restarting

**Comment by garlick** [comment]
Just needs a rebase and then IMHO should be merged.

**Comment by grondo** [comment]
rebased

**Pull request merged**
