### PR TITLE
add flux job wait --all

### PR DESCRIPTION
**Pull request by garlick**
Here's an attempt to implement the `flux job wait --all` option suggested by @grondo in #2758.

### CODE REVIEW

**Comment by chu11** [comment]
One minor comment, would a verbose option be something to add here?  listing all the jobs that have completed so far as more are being waited on?  Seems only failing jobs get output for the moment.

**Comment by grondo** [comment]
Nice! this is a great improvement for the use case of `flux job wait` in scripts!

**Comment by garlick** [comment]
> One minor comment, would a verbose option be something to add here? listing all the jobs that have completed so far as more are being waited on? Seems only failing jobs get output for the moment.

Good thought.  Sure!

**Comment by grondo** [comment]
> One minor comment, would a verbose option be something to add here? listing all the jobs that have completed so far as more are being waited on? Seems only failing jobs get output for the moment.

I'd not be opposed to that, though the `flux job wait` use case is mainly for scripting where 99% of the time you'll likely want no output (like the shell `wait` builtin).

Also, the tool itself isn't going to know how many remaining jobs are waitable. The `--all` option is an alternate to calling `flux job wait` in a loop.

**Comment by grondo** [comment]
Sorry I missed intervening discussion. Removed merge-when-passing label. @garlick go ahead an set it when you're done with `--verbose` option.

**Comment by garlick** [comment]
I went ahead and added a `--verbose` option that just prints a line on stderr each time a job completes.   If this muddies the waters about what the intended use case is, we can drop those commits.  Thoughts?

**Comment by grondo** [comment]
> I went ahead and added a --verbose option that just prints a line on stderr each time a job completes. If this muddies the waters about what the intended use case is, we can drop those commits. Thoughts?

I think it will be nice to have a `--verbose` option.

**Comment by grondo** [comment]
Ok to set merge-when-passing now? We'll try to get this one into the tag.

**Comment by garlick** [comment]
Yep

**Comment by grondo** [comment]
rebase so travis tests the right thing

@mergifyio rebase

**Comment by grondo** [comment]
Grr. of course the asan builder timed out. Restarted. On the plus side now I have time to learn a foreign language while I wait.

**Pull request merged**
