### PR TITLE
0.5.0 release notes, script for generating them, configure warning change

### PR DESCRIPTION
**Pull request by garlick**
This can be tweaked as we get ready to release but wanted to get it out there.

### CODE REVIEW

**Comment by garlick** [comment]
Rebased on master and updated NEWS.md to include most recent merge commit.

**Comment by garlick** [comment]
Rebased after barrier cleanup merge, and updated NEWS.

**Comment by grondo** [comment]
Thanks! What do you think about merging and tagging this after Travis sanity check?

**Comment by garlick** [comment]
Sounds great.

**Comment by grondo** [comment]
Hm, cppcheck hung again. I restarted the build.

**Pull request merged**
