### PR TITLE
python packaging for flux

### PR DESCRIPTION
**Pull request by vsoch**
This one was a nightmare to rebase! Previous PR is #4576 

Signed-off-by: vsoch <vsoch@users.noreply.github.com>

### CODE REVIEW

**Comment by vsoch** [comment]
Just putting this here for myself to debug tomorrow! The configure.ac file didn't have a pretty result after the rebase so I manually re-created, and I messed something up - will investigate tomorrow.

```
  configure.ac:494: error: required file 'src/bindings/python/Makefile.in' not found
  doc/Makefile.am: installing 'config/depcomp'
  parallel-tests: installing 'config/test-driver'
  src/bindings/Makefile.am:1: error: WITH_PYTHON does not appear in AM_CONDITIONAL
  autoreconf: automake failed with exit status: 1
```

**Comment by vsoch** [comment]
Why was this closed?

**Comment by vsoch** [comment]
Oh I see @chu11 I think you might have targeted the wrong number in your commit message!

**Comment by vsoch** [comment]
But thank you for the reminder I forgot to debug these failed tests!

**Comment by vsoch** [comment]
Okay trying to figure out what is wrong - I see in the actions is 1. issue running ldconfig, and 2. permissions error installing to the system python. E.g.,

```console
    LN       flux.so -> .libs/flux.so
  Making all in python
  ldconfig
  /sbin/ldconfig.real: Can't create temporary cache file /etc/ld.so.cache~: Permission denied
  Makefile:619: recipe for target 'core.so-built' failed
  make[3]: *** [core.so-built] Error 1
  make[3]: *** Waiting for unfinished jobs....
  export LD_LIBRARY_PATH=../../../src/common/.libs:../../../src/common/libdebugged/.libs
  export FLUX_INSTALL_ROOT=/usr/src/workdir/workdir/workdir/workdir/workdir/workdir/workdir/workdir/workdir/workdir/workdir/workdir/workdir/workdir/workdir
    GEN      idset.so-built
  running build_ext
                search: ['/usr/src/workdir/workdir/workdir/workdir/workdir/workdir/workdir/workdir/workdir/workdir/workdir/workdir/workdir/workdir/workdir/src/common/libflux']
  Writing stage 1 clean header to /usr/src/workdir/workdir/workdir/workdir/workdir/workdir/workdir/workdir/workdir/workdir/workdir/workdir/workdir/workdir/workdir/src/bindings/python/_flux/_core_clean.h
  /usr/lib/ccache/gcc -E -D__attribute__(...)= /usr/src/workdir/workdir/workdir/workdir/workdir/workdir/workdir/workdir/workdir/workdir/workdir/workdir/workdir/workdir/workdir/src/bindings/python/_flux/_core_clean.h -o /usr/src/workdir/workdir/workdir/workdir/workdir/workdir/workdir/workdir/workdir/workdir/workdir/workdir/workdir/workdir/workdir/src/bindings/python/_flux/_core_preproc.h
                search: []
  Writing stage 1 clean header to /usr/src/workdir/workdir/workdir/workdir/workdir/workdir/workdir/workdir/workdir/workdir/workdir/workdir/workdir/workdir/workdir/src/bindings/python/_flux/_idset_clean.h
  /usr/lib/ccache/gcc -E -D__attribute__(...)= /usr/src/workdir/workdir/workdir/workdir/workdir/workdir/workdir/workdir/workdir/workdir/workdir/workdir/workdir/workdir/workdir/src/bindings/python/_flux/_idset_clean.h -o /usr/src/workdir/workdir/workdir/workdir/workdir/workdir/workdir/workdir/workdir/workdir/workdir/workdir/workdir/workdir/workdir/src/bindings/python/_flux/_idset_preproc.h`
```
and a bit later

```
/usr/local/lib/python3.7/dist-packages/setuptools/command/install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
    setuptools.SetuptoolsDeprecationWarning,
  error: could not create '/usr/lib/python3.7/site-packages': Permission denied
  Makefile:625: recipe for target 'hostlist.so-built' failed
```
it seems to create ok in the development container I'm running on:

```
root@d9ff83623163:/workspaces/core# ls /usr/lib/python3.8/site-packages/
flux-0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.1a1.egg-info
```
but maybe there is a permissions error with make install in the testing container? I think it's probably related to this in the Python Makefile.am

```
# Currently we don't install with security, since we don't know the paths
install:
	export LD_LIBRARY_PATH=$(top_builddir)/src/common/.libs:$(top_builddir)/src/common/libdebugged/.libs
	export FLUX_INSTALL_ROOT=$(realpath $(top_srcdir))
	$(AM_V_GEN)$(PYTHON) $(srcdir)/setup.py install  --hostlist --rlist --idset  # Note to Tom - if I add this it isn't found in the container with python3 --prefix=$(PREFIX)
```
and I'm wondering if we shouldn't try to be installing for the user. Maybe we should just generate the .tar.gz and have something else install it? I'm also thinking the setup.py approach is going to get stale very quickly and then we won't have a replacement, so maybe this isn't worth doing at all. Anyway, I can very confidently say that this work is not good enough to integrate into Flux. Even if we got it working, if setup.py install finally deprecates we don't have a build anymore. We can close if desired.

**Comment by chu11** [comment]
@vsoch doh!  sorry, my bad

**Pull request closed without merging**
