### PR TITLE
kvs-watch: fix read-your-writes consistency

### PR DESCRIPTION
**Pull request by chu11**
Per discussion in #1838 on fixing read-your-writes consistency in the kvs-watch module.

- add a new rpc target called ```kvs.lookup-plus``` (name changeable, couldn't think a better one) that returns the root_ref & root_seq used during a lookup.  In addition, it returns the root_ref &
  root_seq used even on ENOENT.

- for ```kvs-watch.lookup```, only lookup via ```kvs.lookup-plus```. The first lookup will always be done on the current kvs root, and latter lookups will be based on root refs & seqs from setroot events.  With info from ```kvs.lookup-plus``` (most notably the root_seq), we can ensure read-your-writes consistency because no older references will be sent to users.  A few unique corner cases had to be handled for the ENOTSUP (namespace missing) case.

- for ```kvs-watch.getroot```, a similar process is done, but a list of potential root refences & sequences have to be stored in a new list b/c such infrastructure was not yet available.

- various refactoring done along the way to get to the point that the above could be done.

  - ```kvs.lookup``` now takes an optional root_seq as well as the  optional root_ref.  The root_seq is only for convenience, so that it can be returned back to the caller of a ```kvs.lookup-plus``` call.

  - commit structures in kvs-watch now have reference counters, so they will not be deleted on destruction (commit structs are stored in namespaces and possibly watcher lists).

  - kvs-watch no longer parses raw data out of lookup responses, it instead parses out json objects.

### CODE REVIEW

**Comment by chu11** [comment]
realized i forgot to destroy a watcher on a getroot failure.  Also, travis found an unitialized variable warning.  I went ahead and squashed these fixes since they were tiny.

**Comment by chu11** [comment]
re-pushed, just added some comments

**Comment by garlick** [comment]
I've scanned through this and I think I understand it!  Nice work.  It is a little taxing trying to follow the `kvs-watch.c` code though, keeping in mind its interactions with `kvs` and the API.  Do you see any opportunities to break this up into separate C modules, sort of like what was done in `job-manager` module?

Thoughts on testing read-your-writes e.g. as suggested in #1832 ?

**Comment by chu11** [comment]
Thinking about potential cleanups. I could see putting a nice chunk of getroot handling / lookup handling in separate C files, but the common code of the main namespace monitor, watchers, etc. obviates need for shared code in other c modules.  I'm not entirely sure it's a big net win.  I see some potential to combine infrastructure of the getroot and lookup handling, but it'll be messy and maybe not a net win either.

One thought I had was perhaps having a namespace monitor for getroots and namespace monitor for lookups.  By decoupling the common code, that could make things simpler overall and we could stick lots of code in separate modules.  This would be nice especially for ```struct watcher``` (and maybe other data structures) as there are now an increasing number of fields just for getroots or just for lookups.  Hypothetically, why not even have a kvs-watch-geroot module and a kvs-watch-lookup module?

Another thought I had.  How often do you expect kvs-watch with getroot to be done?  B/c with the new ```kvs.lookup-plus```, we can completely remove all of the kvs-watch getroot handling.  A getroot watch can be done with the ```kvs-watch.lookup``` code and the key ```.```.  The problem with this is the rpc count would be way higher / noisier b/c you'd effectively be doing a lookup on every single change to the KVS.

**Comment by garlick** [comment]
I don't think we have a real use case for `flux_kvs_getroot (flags=FLUX_KVS_WATCH)`, so that option is pretty appealing!

**Comment by chu11** [comment]
> I don't think we have a real use case for flux_kvs_getroot (flags=FLUX_KVS_WATCH), so that option is pretty appealing!

You mean collapsing it into ```kvs-watch.lookup```?

If we don't have a real use case, should we just get rid of it?

**Comment by garlick** [comment]
> You mean collapsing it into kvs-watch.lookup?

Right.

> If we don't have a real use case, should we just get rid of it?

I feel like I might be missing something, but I can't think of a good reason not to at this point, and in keeping with the spirit half-baked API in this release, maybe we should nix it, especially if it would reduce complexity in the `kvs-watch` module.

**Comment by chu11** [comment]
> maybe we should nix it, especially if it would reduce complexity in the kvs-watch module.

Ok, how about we merge this PR in since it's a good "we fixed read-your-writes" stopping point, then I'll remove it in a later PR b/c it'll also involve cleaning up libkvs.  I'll rebase once I merge in #1867.

**Comment by garlick** [comment]
That sounds good, then we'll at least capture the extra work you did to make read-your-writes work with getroot+watch.

**Comment by chu11** [comment]
rebased

**Comment by garlick** [comment]
NIce work here @chu11.  As discussed, cleanup could happen in another PR and potentially after we tag 0.11.0 if we get down to the wire.

**Pull request merged**
