### PR TITLE
jsc: Fix a race caused by ignoring the new state passed to a watch callback

### PR DESCRIPTION
**Pull request by dongahn**

### CODE REVIEW

**Comment by garlick** [comment]
@dongahn I'm ready to merge this once travis passes but did you mean to leave RACY set in commit afdd1ea?

**Comment by grondo** [comment]
also, regarding commit messages, it would be nice to tweak these a bit (at least prefix with `jsc: ` for ease of quick parsing of commit history) Thanks!

**Comment by dongahn** [comment]
@grondo: good point. Will edit. 

@garlick: yes, I thought marking those subtests with RACY until we make progress to cope with watch-chaining pattern was the right way to go.

**Comment by dongahn** [comment]
@garlick: Hmmm. I actually didn't push my local change that removed that RACY. Will fix (good catch.)

**Comment by dongahn** [comment]
actually, the pull request was created from master, not from jsc branch. (I shouldn't do this at night :-) I will close this and create a new PR from the right branch.

**Pull request closed without merging**
