### PR TITLE
small experiment with cJSON

### PR DESCRIPTION
**Pull request by garlick**
The [cJSON](https://github.com/DaveGamble/cJSON) library is small, embeddable, reasonably fast (see [JSON benchmarks](https://github.com/miloyip/nativejson-benchmark)), and seems widely used.  It implements "JSON patch", as described in [RFC 6902](https://tools.ietf.org/html/rfc6902) which may have applications in the KVS, perhaps as a replacement for the ad-hoc "operation" array in the commit request.  I'm curious whether switching to cJSON might not be a useful idea in the KVS internally, particularly if "JSON patch" can be used there.  I'm also wondering if this API might be a little nicer than json-c.

In this PR, I embedded the library in flux-core and converted `flux-kvs` to use it as an experiment.  So far, well...not too bad I guess.  A couple of interesting bits relative to json-c:
* It allows malloc/free functions to be registered by the user
* it is not refcounted (I'm not sure if that as good or bad at this point!)
* it only implements the "number" type, not int, int64, and double like json-c.
* no name collisions with json-c (unlike jansson) so it doesn't require all or nothing investment

Some problems noted so far
* code is nearly unreadable (e.g. needs to be reformatted IMHO)
* malloc/free pointers are stored in globals which might not work for broker/modules (move to TLS?)
* if you don't register a "fatal" malloc/free, checking for ENOMEM is a bit tricky (e.g. checking for NULL structure members - requires peeking at source)

Not for merging - just a checkpoint.

### CODE REVIEW

**Comment by grondo** [comment]
Wow, cJSON kind of feels like the result of late night bet to get a C JSON library under 800 lines. However, it does seem like it is actually used by other projects.

Maybe we could start with cJSON and make something reasonably *safe* and fast ourselves that implements JSON patch?

**Comment by garlick** [comment]
Yeah starting with running it through `indent`!

**Comment by garlick** [comment]
Looks like code reformatting is in the queue upstream, see DaveGamble/cJSON#24

**Comment by grondo** [comment]
Just remembered that @trws had checked in rules for clang-format that follow our style guide if `indent` doesn't give you great results. Try uncommenting the clang-3.7 lines in `.clang-format` if you have a recent version.

**Comment by lipari** [comment]
We have [RFC 8](https://github.com/flux-framework/rfc/blob/master/spec_7.adoc#tools-that-modify-code-to-conform-to-c-coding-style) that provides guidance on how to make our code look uniformly pretty.  I would suggest we add to it whatever tools or options that best do the job.

**Comment by garlick** [comment]
Thanks guys, I'll probably just wait for the reformatting to come from upstream since it's any day now, and then we'll be able to stay in sync and not subvert automatic rebase of any patches we carry.  Assuming this experiment withstands the light of day that is!

**Comment by garlick** [comment]
For the record, In #301 we discussed replacing json-c at length.  For C, it sounded like jansson was the preferred option, but since there are some functions in json-c and jansson that have the same name, we ran into troubles transitioning.  As I understand it, libflux had been migrated to jansson in #319, while other parts of flux-core like the kvs module still used json-c.  The json-c users would pick up libflux's dependencies when built in-tree via the libtool scripts and get one of the duplicate symbols from the wrong lib.

It was thought that pulling json-c in and building it statically as part of libflux-internal would address this, but for some reason I didn't press ahead and just do that to get us through the transition.

**Comment by DaveGamble** [comment]
@grondo You are unbelievably close to the truth with your guess as to the origins of cJSON. ;)
If you'd guessed mid-afternoon rather than late-night, you'd have gotten full marks! :D

**Comment by grondo** [comment]
@DaveGamble, well then kudos are in order! nice job on cJSON, and thanks for the software!

**Comment by grondo** [comment]
Is this PR dead, Jim?

**Comment by garlick** [comment]
You mean...
star-trek-hes-dead-jim
Not quite.

**Comment by garlick** [comment]
Think I'll withdraw this for now - still on the back burner.

**Comment by grondo** [comment]
closed by #1988

**Pull request closed without merging**
