### PR TITLE
KVS Jansson Updates

### PR DESCRIPTION
**Pull request by chu11**
This PR converts all the code in the kvs to use jansson instead of json-c.  This PR should be done **AFTER** @garlick's #1107 PR, but wanted to throw this up here for the time being.

Still need to valgrind check and soak test too.  Maybe will add 1-2 unit tests for a code path I think should be tested.

### CODE REVIEW

**Comment by garlick** [comment]
Nice!  Do we need the proto.[ch] after this at all?

I guess this won't `git bisect` but that would be quite a bit of extra work so IMHO probably not worth it.

**Comment by chu11** [comment]
Not sure if we can remove proto.[ch] yet, wanted to see how much you did in #1107.  But it's minimally close.  I think there's one test that still uses it, so perhaps we'd have to convert that.  Also need to figure out where the ```KVS_PROTO_*``` enums would go (maybe you already did this, still need to look through your PR).

**Comment by garlick** [comment]
#1107 removes the client API users of proto.[ch].   Ah right, `t/kvs/watch_disconnect.c` uses it, but that's easily fixed.

As I needed each of the KVS_PROTO_* flags, I defined new ones (same values, different names) in API header files.  Since the KVS module includes <flux/core.h> it can pick them up and use the new names.

**Comment by chu11** [comment]
something I just thought about w/ ```json_compare()``` which uses ```json_equal()```.  It doesn't behave like the old algorithm.  If one were to pass ```json_compare (NULL, NULL)```, it would now return false.

Now under jansson, this might be what we want.  Hmmm, minimally should probably just add a comment about this.

**Comment by garlick** [comment]
Just peeked at `watch_request_cb()`, the one user of `json_compare()`, to try to figure out if NULL, NULL ever came up.  I think it can, e.g. watching a key that initially, or at some point while it is being watched, doesn't exist.

The watch handling really needs a redesign, but let's not do that here.

**Comment by chu11** [comment]
@garlick I think I protect against this in ```watch_request_cb```.  If the value isn't found in lookup, I convert to a json null.

```
    val = lookup_get_value (lh);
    /* if no value, create json null object for remainder of code */
    if (!val) {
        if (!(val = json_null ()))
            oom ();
    }
```

when unpacking the msg, I think a "null" will be converted to a json null.

```
        if (flux_request_unpack (msg, NULL, "{ s:s s:o s:i }",
                                 "key", &key,
                                 "val", &oval,
                                 "flags", &flags) < 0) {
            flux_log_error (h, "%s: flux_request_unpack", __FUNCTION__);
            goto done;
        }
```

So I think val & oval will always be non-NULL.  As a test I added an ```assert (val && oval)``` right before and the unit tests pass.

**Comment by garlick** [comment]
That seems reasonable then.

I double-checked my changes to the `kvs_watch_once()` implementation.  It passes in a JSON null for "val" if the initial json_str value is NULL, so we are consistent there.

**Comment by chu11** [comment]
Just ran some soak tests, and the numbers were a tad better than master.  So looks like jansson is having a nice positive effect :-)

**Comment by chu11** [comment]
Just pushed a branch rebased on current master (which includes #1107).  Mostly cleanup patches, adjusting for new enums in master, added more commit API unit tests, fix corner case in t1002-kvs-cmd.t tests b/c of potential ordering issues with kvs output.

Now that I've rebased, I'm sure there is some additional cleanup can be done, which I'll look into now.  Perhaps ```proto``` can go away, maybe ```json_dirent```, etc.

**Comment by chu11** [comment]
hmmmm, I'm not really sure why travis doesn't like my unit tests.  No unit tests themselves fail, but it does give up after awhile with a missing test plan error.

```
ERROR: t1002-kvs-cmd.t - missing test plan
ERROR: t1002-kvs-cmd.t - exited with status 1
```

It's around where I put a new function in in https://github.com/flux-framework/flux-core/pull/1108/commits/cff8b1f83edbd5007d630a96ccfff64475aad996  dunno if it's some subtle-bash-ism or something.  Maybe they want my helper function to return 0?

**Comment by grondo** [comment]
That error usually happens when the test script exits before `test_done` is called.

**Comment by chu11** [comment]
Hmmm, having issues passing travis.  I'm sort of at a loss for the moment.  This relatively simple change:

```
+# Output of watch_out could be unsorted/out of order compared to
+# expected output.  This function will re-order the output in each
+# appropriate section (i.e. between ====================== lines)
+sort_watch_output() {
+        i=0
+        rm -f watch_out_sorted
+        while read LINE
+        do
+            if [ "$LINE" == "======================" ]
+            then
+                IFS=$'\n'
+                arr2=($(printf "%s\n" "${arr[@]}" | sort))
+                for elem in "${arr2[@]}"
+                do
+                    echo "$elem" >> watch_out_sorted
+                done
+                echo "======================" >> watch_out_sorted
+                unset IFS
+                i=0
+            else
+                arr[$i]="$LINE"
+                i=$((i + 1))
+            fi
+        done < watch_out
+}
+
 test_expect_success 'kvs: watch a dir with -R'  '
         flux kvs unlink -R $DIR &&
         flux kvs put $DIR.a.a=0 $DIR.a.b=0 &&
@@ -572,6 +598,7 @@ test_expect_success 'kvs: watch a dir with -R'  '
         wait_watch_current "======================" &&
         flux kvs put $DIR.a.a=1 &&
         wait $watchpid
+        sort_watch_output
        cat >expected <<-EOF
        $DIR.a.a = 0
        $DIR.a.b = 0
@@ -580,7 +607,7 @@ test_expect_success 'kvs: watch a dir with -R'  '
        $DIR.a.b = 0
        ======================
        EOF
-        test_cmp watch_out expected
+        test_cmp watch_out_sorted expected
 '
```

seems to be confusing the test and giving me

```
ERROR: t1002-kvs-cmd.t - missing test plan
ERROR: t1002-kvs-cmd.t - exited with status 1
```

Which as @grondo says above, is usually indication that the test has exited early without calling ```test_done```.  I initially thought I was doing some advanced bash-ism and maybe travis's bash is old.  But arrays have been around since bash 2.0.  I thought maybe unsetting IFS was bad, but that didn't seem to change any results either.

I'm also regularly getting build failures on one of the travis clang builds, but I'm at a bit of a loss.

```
[src/modules/kvs/test/json_util.c:103]: (error) Memory pointed to by 's1' is freed twice.
[src/modules/kvs/test/json_util.c:114]: (error) Memory pointed to by 's1' is freed twice.
```

But my code seems correct.

```
    93	    obj = json_null ();
    94	
    95	    ok ((s1 = json_strdump (obj)) != NULL,
    96	        "json_strdump works");
    97	
    98	    s2 = "null";
    99	
   100	    ok (!strcmp (s1, s2),
   101	        "json_strdump works on null object");
   102	
   103	    free (s1);
   104	    json_decref (obj);
   105	
   106	    ok ((s1 = json_strdump (NULL)) != NULL,
   107	        "json_strdump works on NULL pointer");
   108	
   109	    s2 = "null";
   110	
   111	    ok (!strcmp (s1, s2),
   112	        "json_strdump works on NULL pointer");
   113	
   114	    free (s1);

```

minimally for the latter ```free (s1)```, it's not possible it is freed twice, since I set s1 on line 106 above and never use s1 again.  Unless the json object (```obj```) owns the string?  But that's not the case according to the jansson API docs, and I free the string a gazillion of other places too.  This would be a problem elsewhere if it were true.

Oh well, will mull over it, maybe will have an epiphany in my sleep.

**Comment by chu11** [comment]
Hmm, under the assumption that cppcheck was confused I just cleared the s1 values before re-using and that worked.

```diff
index 729b4d0..2d81387 100644
--- a/src/modules/kvs/test/json_util.c
+++ b/src/modules/kvs/test/json_util.c
@@ -89,6 +89,7 @@ int main (int argc, char *argv[])
 
     free (s1);
     json_decref (obj);
+    s1 = NULL;
 
     obj = json_null ();
 
@@ -102,6 +103,7 @@ int main (int argc, char *argv[])
 
     free (s1);
     json_decref (obj);
+    s1 = NULL;
 
     ok ((s1 = json_strdump (NULL)) != NULL,
         "json_strdump works on NULL pointer");
@@ -112,6 +114,7 @@ int main (int argc, char *argv[])
         "json_strdump works on NULL pointer");
 
     free (s1);
+    s1 = NULL;
 
     done_testing ();
     return (0);
```

**Comment by chu11** [comment]
It does appear the version of bash on travis is older and can't do some advanced things.  The following: 

```
sort_watch_output() {
        rm -f watch_out_sorted
        rm -f tmp_watch_file
        while read line
        do
            if [ "$line" == "======================" ]
            then
                cat tmp_watch_file | sort >> watch_out_sorted
                echo "======================" >> watch_out_sorted
                rm -f tmp_watch_file
            else
                echo "$line" >> tmp_watch_file
            fi
        done <watch_out
        return 0
}
```

gives me normal errors

```
FAIL: t1002-kvs-cmd.t 58 - kvs: watch a dir with -R
FAIL: t1002-kvs-cmd.t 59 - kvs: watch a dir with -R and -d
ERROR: t1002-kvs-cmd.t - exited with status 1
```

so atleast ```t1002-kvs-cmd.t``` doesn't bork and just exit.

**Comment by chu11** [comment]
Ugh ... i guess it's bourne behind the scenes, not bash.

```diff
-            if [ "$line" == "======================" ]
+            if [ "$line" = "======================" ]
```

I'll squash things and post additional cleanup patches tomorrow.  Sorry for all the coveralls spam.  I reached the point of just making random guesses as to what was wrong.

**Comment by chu11** [comment]
just re-pushed, squashed my fixes, a variety of cleanup patches to remove now-unused code (proto, json_dirent, some random functions).

**Comment by garlick** [comment]
Thanks!  Will poke at this now.

**Comment by garlick** [comment]
Here's a thought.  I tried to abstract the "array of operations" on the client side in `kvs_txn.[ch]`.  There's a private interface that allows access to the underlying json array, and to iterate over each element.

Would it make sense to use the `flux_kvs_txn_t` object on the server side?  Maybe instead of the "fence" with its array of ops, we could just have transactions and allow the various metadata that the server side needs to associate with one to be optionally tacked on to the `flux_kvs_txn_t`?  ("fence" is kind of a misnomer there, and resulted from an earlier consolidation of kvs.fence and kvs.commit methods).

Well maybe that's for another PR, but the tests that required `j_dirent_append()` to be reimplemented reminded me that it would be nice if we a single, tested interface for that stuff.

**Comment by garlick** [comment]
It's confusing having `json_` prefixed functions in `json_util.[ch]`.  I think actually 
* `json_object_copydir()` could be replaced with jansson `json_copy()`?
* `json_strdump()` is only used in once place that I found (content_store_request_send) so maybe not needed?
* `json_hash()` is only used twice...so needed?

At minimum I think we should rename those functions to have some other prefix like `util_json_hash()` or similar.

**Comment by chu11** [comment]
@garlick I can see what you're talking about w/ the txn abstraction.  It's got enough similarities and crossover to definitely consider (```fence_merge``` would immediately fit right in), but just enough differences that I pause (names, nprocs, etc.).  But maybe some of those differences can be refactored away in a different way to make them more similar.  Or perhaps some ```ops-array``` abstraction that both would use?

**Comment by chu11** [comment]
@garlick Yeah, it did occur to me that the ```json_util``` function names could be confusing.  You're right, it'd be a good idea to rename them.  I notice jansson doesn't have a prefix of ```json_util```, so I'll just use that.

I'd like to keep ```json_strdump()``` and ```json_hash()``` for now.  While it's not used in a lot of places in the kvs (but a nice chunk in the unit tests), I think it's import to abstract away the flags argument to ```json_dumps()```.  Without it, we would require multiple parts of the code to consistently pass the right flags to ```json_dumps()```.  That was one of the bugs I hit early in my porting and different parts of the code were getting different blobref results.

**Comment by chu11** [comment]
@garlick oh, and I think you're right.  We can probably get rid of ```json_object_copydir``` outright.  Good catch.

**Comment by garlick** [comment]
I'll open a bug to capture the `flux_kvs_txn_t` on the server side idea, for another PR.

Agreed on all other points, although I'm not super keen on `json_util_` as a prefix - seems like that still might get some people confused.  How about `kvs_util_*`?

**Comment by chu11** [comment]
oh, I like ```kvs_util```, lets go with that.

**Comment by garlick** [comment]
The `kvs.c::stats_get_cb()` and its helper `add_tstat()`, looks like it could be converted into one long `flux_respond_pack() call?

Also if it encounters an out of memory error, it should probably return ENOMEM in the RPC response rather than exiting with an `oom()` call.   It doesn't really get us off topic for the PR to do it right if the code is being rewritten anyway.

**Comment by garlick** [comment]
`json_dumps()` can return NULL on malloc failure.

Checks need to be added to the calls in `cache_get_stats()` and  `fileval_big()`.

**Comment by chu11** [comment]
Ahh, thanks for the catches on the missed checks.

Fiddling a bit this afternoon.  I think I'd like to push the ```json_object_copydir()``` -> ```json_copy()``` and maybe some other ```oom()``` cleanup to a later PR.  There's sort of this cascading ```oom()``` cleanup.  Where if a function that used to ```oom()``` now returns ENOMEM, the caller now needs to check for error, and now that function has to handle a new cleanup path, etc.  Since ```oom()``` was the pattern with json-C, how about we stick to that for atleast this PR.  ```j_dirent_create()``` also calls ```oom()```, so that needs to be cleaned up in a lot of places too.

The ```kvs.c::stats_get_cb()``` is sort of isolated, so I think I can clean that one easily without fallout.

**Comment by garlick** [comment]
Yep, I didn't mean we should do all the oom cleanup now, just where we're rewriting the code anyway and there isn't a cascade of callers to change.  Maybe `stats_get_cb()` is the only case - I didn't look too hard.

**Comment by garlick** [comment]
I've been all the way through this and man it's a lot of work!  Thanks for doing it.  No more comments for now - I think if you can address the above issues this can go in.  Great job keeping the coverage within bounds too!

**Comment by chu11** [comment]
pushed w/ a bunch of mini patches.  If this passes, then I'll squash, rebase on master, and then repush.

```stats_get_cb()``` is crazy simple now.  One of those "didn't see it at first" kinds of things, but it's so much cleaner now.

**Comment by garlick** [comment]
Looks good.

**Comment by garlick** [comment]
I'm going to press the button!  Nice work.

**Pull request merged**
