### PR TITLE
Mask cores outside the CPUSET of the spawning broker

### LINKED ISSUE #461: resource-hwloc needs better support for multiple brokers per node
As discussed as part of #460, we need better support within resource-hwloc to deal with multiple brokers per node. 

`resource.hwloc.xml.<rank>` doesn't currently distinguish the cpuset that each broker rank is pinned to. `resource.hwloc.by_rank.<rank>` doesn't restrict cores/sockets only to those available to the broker rank.

This is not a huge problem because it only affects testing under real node-hardware partitioning. But nevertheless, this can help solve a bunch of issues in `flux-sched` like [flux-sched#69](https://github.com/flux-framework/flux-sched/issues/69) whereby we need a way to map a resource allocation to the right set of broker ranks -- i.e., currently `sched` has to directly assign number of cores per rank given the resrc job allocation. 

I am wondering if hwloc has an API that lets you only select the cpuset the broker is pinned to and export that as xml. If this is the case, exporting that non-overlapping resources into both resource.hwloc.xml.<rank> and by_rank keys.

### PR DESCRIPTION
**Pull request by trws**
This patch masks off cores that are disallowed for scheduling due to a cpuset
mask from the hwloc resource list in the kvs and elsewhere, includes quite a few more checks for intermediate failure of hwloc as well.  Fixes #461.

### CODE REVIEW

**Comment by trws** [comment]
Thanks for the comments @grondo!  I've added some cleanup code, and merged the two PRs, I'll close out the other one in a moment.

Tests would not be a bad idea, but they're very difficult to make deterministic due to the module load time before results can be checked in places like the KVS.  I'll give it some thought.

**Comment by trws** [comment]
Hm, it would be relatively easy to set up a test that sets the config, uses reload, then uses the topo RPC to get the updated version.  The only problem is I'm not sure if the RPC could get re-ordered with respect to the event.  If they can it would result in occasional failures.  Same issue with loading it from a config, it will only certainly work after the module has fully loaded...

**Comment by grondo** [comment]
I checked out this PR under SLURM and it seems to work great!

```
 grondo@hype211:~/git/f$ srun -l nproc            
2: 16
1: 16
0: 16
3: 16
 grondo@hype211:~/git/f$ srun -N4 -n$((4*16)) --pty src/cmd/flux broker
[1447959514.850402] broker.info[0]: nodeset: [0-63] (complete)
[1447959514.850464] broker.info[0]: starting initial program
(flux-113640) grondo@hype211:~/git/f$ flux kvs get resource.hwloc.by_rank.0.Core 
1
(flux-113640) grondo@hype211:~/git/f$ flux kvs get resource.hwloc.by_rank.32.Core
1
```

Nice work!

I think if you're willing to fixup tense of commit messages "restricting"->"restrict", and maybe squash the `delvec` fixup into the initial "rework" commit, this one is ready to go.

**Comment by trws** [comment]
Thanks @grondo! I'll be happy to make those adjustments, hopefully I'll 
get to it this evening after my talk/meetings.

Since you have it up by the way.  One thing I could use another set of 
eyes on is how the IO infrastructure appears in the topology.  I think I 
can fix this if we're going to use it, but currently the IO devices only 
appear under brokers on the socket to which they are connected.

I'm not sure if this is a bug, or a feature, because this should cause 
it to de-duplicate itself, but then it means some brokers may not see 
resources they have access to.

Any thoughts?

**Comment by grondo** [comment]
I'll have to delve into this a little more after lunch. I'm not all that familiar with hwloc, let alone how it handles IO hierarchy.

Also, I guess hwloc enumerates Socket/NumaNode separately for each rank so when I run 16 brokers per real node, I'm seeing hwloc enumerate each broker's local NumaNode/Socket as `"NumaNode_0.Socket_0"`... (which I think is fine, I'll just have to delve a little further to understand the data in the kvs)

**Comment by grondo** [comment]
Pasting here for posterity a dump of `resource.hwloc.by_rank` for 4 nodes running 64 brokers (1 broker per core)

[hwloc.txt](https://github.com/flux-framework/flux-core/files/39373/hwloc.txt)

**Comment by trws** [comment]
The hwloc logical ids will be 0 and 0 as you say, but the os_index field of the socket or core will always be a machine-global value that numcactl or others can understand.

**Comment by trws** [comment]
After the cleanup items today, especially cleaning up old resource data from the KVS on a reload, I think I've covered the remaining issues here.  @grondo, @garlick, what do you think?

**Comment by grondo** [comment]
Looks great! 

Maybe the code formatting in the final commit could be split from the functional changes for better history?

**Comment by trws** [comment]
That should be pretty simple, let me see how the rebase comes out.

**Comment by trws** [comment]
Commit split, and moved the check functions out to a more appropriate location as a new commit while I was at it.

**Comment by grondo** [comment]
Cool! Instead of adding the `check_*` helpers in one commit then moving them within a single PR, this should be simplified by adding check functions in an initial commit, e.g.
```
libutil/log: Add helper functions for checking int and ptr return codes

Add check_int() and check_log() helper functions to return code checking
and subsequent logging of errors. 
```

Thus the intermediate state is removed from permanent history.

However, I'm also a bit befuddled by the different log facilities we currently have, but since these logs are from a broker module, shouldn't `resource-hwloc` be using `flux_log`?

**Comment by trws** [comment]
It's not a bad idea to have a flux_log version, and I could switch the module to use that I suppose.  The reasoning is that these can be used anywhere we have `if (...) err_exit`, which doesn't require a flux_t handle to work.  I'll take a look at it.  As to moving the addition of the functions around, I can certainly move that commit earlier, but getting the rebase right to remove them from the history of the resource.c file may be tricky.

**Comment by grondo** [comment]
>  these can be used anywhere we have if (...) err_exit, which doesn't require a flux_t handle to work. 

That would certainly be ok in utilities,  but should module code ever call `err_exit`?
Generally it feels like we should be moving away from `err_exit` and `oom` assisted suicide calls...
(but this stuff is probably fine for now, I'd wonder what @garlick's feedback is as well)

**Comment by trws** [comment]
Perhaps not.  How should a module respond to an unrecoverable failure?

**Comment by grondo** [comment]
> Perhaps not. How should a module respond to an unrecoverable failure?

Great question! ;-)

I think currently a module can return from its main() function, which I guess is the equivalent of exit() for a module... I think we probably need to revisit this issue.

**Comment by trws** [comment]
That's not a bad idea.  The trick is that there's no way to unwind back to the main to do that from a sub-call without a lot of manual work.  Perhaps we need a module "abort" or equivalent? This is where having module-as-process would help a lot actually, now that I think about it.

**Comment by garlick** [comment]
Most modules are structured as a reactor loop, and you can call `flux_reactor_stop_error()` to cause `flux_reactor_run()` to exit with an error.

**Comment by trws** [comment]
Ok, can we count on everything that calls a flux_log-like call to be a module?  If so that might be a good solution to this.

**Comment by garlick** [comment]
Sorry, didn't look closely at the code so I didn't know that would be implied.  No, I think any handle user might call `flux_log()`, and not all of them are reactor based.

**Comment by trws** [comment]
There are now flux_log versions of the check functions.  These work basically the same way as the others, in that they are suicidal on failure, but they use the flux_log functionality and take a handle to do so.

Also, the original check_* functions have been rebased into an earlier commit and excised from the resource-hwloc module source in all of the commits.

**Comment by grondo** [comment]
Cool!

 The only comment I have is that commit  4c8bd2c is a bit confusing as it touches not only `flog.c` but `log.h` and the `resource-hwloc.c` code. I'm not saying this is a must-fix for merging this PR, but in the future commits should do one thing where ever possible, as this really helps when traversing history, using `git blame` or `git bisect`. (really, not a big deal at this point)

Also could we just just one public `STRINGIFY` macro used in both places? (I'm really asking, not being rhetorical, since you probably have a good reason for STRINGIFY in both places -- perhaps one is part of libflux and one libflux-internal?)

**Comment by trws** [comment]
It might be good to have a common "meta-macros" header someplace.  I can throw one together and pop it in libutil perhaps? There are a number of things like that which will get repeated all over otherwise just because they're common patterns.

**Comment by trws** [comment]
Added the header mentioned above.  It's quite sparse for now, but I would imagine we'll find some other things to suck into there eventually, like x-macro support mechanisms and variadic macro handlers for things like looping over or enumerating macro arguments.

**Comment by garlick** [comment]
Ah `STRINGIFY()` I think I've already defined in a couple of places.  Good idea to factor that to a common header.

**Comment by trws** [comment]
Hmmm.... apparently libpmi doesn't like the local reference from log.h to macros.h on travis, occasionally... I'm not sure how best to make that path independent, perhaps add libutil as an include directory to the pmi library makefile so they can both be used with bare names?

**Comment by grondo** [comment]
> Hmmm.... apparently libpmi doesn't like the local reference from log.h to macros.h on travis, occasionally... 

`macros.h` is missing from `libutil_la_SOURCES` (or `EXTRA_DIST` I guess), so it won't appear in `make dist` output.

`gcc` and `clang` builds use `make distcheck`, while the `coverage` build cannot. So usually when coverage succeeds but the other builds fail, it is a `make dist` problem.

**Comment by trws** [comment]
Thanks @grondo, you saved me some pointless searching for sure.  As soon 
as my tests pass I'll upload an updated patch.

**Comment by trws** [comment]
Looking green now.  Anything else to tweak on this one?

**Comment by grondo** [comment]
@trws, I think this is ready to merge. Would you be willing to go through and wrap commit log lines to ~72? Then I'll push the button.

**Comment by trws** [comment]
Sure.  I need to fix that in my .vimrc, have it set to 78 for everything 
but the commit summary line, that highlights to 72.

**Comment by trws** [comment]
They're rewrapped, and this should keep it from happening again:

```vim
augroup git
  autocmd!
  au FileType gitcommit setlocal textwidth=72
augroup END
```

**Comment by grondo** [comment]
Ooh, thanks for the vim config snippet!

**Pull request merged**
