### PR TITLE
disable KVS configuration inheritance

### PR DESCRIPTION
**Pull request by garlick**
Not a serious PR as yet, just following up on ideas in #452.

### CODE REVIEW

**Comment by grondo** [comment]
I started poking at this because it seemed like perhaps some fixups would be simple. So far, though, I have some questions --

 * Seems like after this change the `-F, --file-config` option could be dropped? It doesn't seem to be used anymore in this branch?
 * Changes here break the test for `FLUX_URI` passed to environment because `flux_open()` is called if `FLUX_URI` set or `--uri` used, and `flux_open` failure is now a fatal error. Ok to just drop the `flux_open()` directly in `flux.c`? Builtin subcommands will call flux_open() automatically if they need it.
 * Similarly to FLUX_URI test failure, FLUX_CONNECTOR_PATH also fails, but this is because `flux_open()` is called due to `FLUX_URI` set in the current session, but `FLUX_CONNECTOR_PATH` has not been updated to full path `something:/xyz` but is instead only `/xyz` -- so `flux_open()` again fails.

Related to the last bullet above, `flux(1)` fails in the same way: `flux_open: No such file or directory` whether or not the failure is due to missing connector dso, or missing uri. That confused me for awhile.

So my suggestion here would be to:
 * Drop manual `flux_open()` call from `flux.c`. The job of `flux.c` should be restricted to reading config file and setting up environment for subcommands.
 * Ensure environment has been properly exported before invoking either builtin or other subcommands.

I think this will fix up the test failures seen in the PR. (though I have not checked on PMI test failures yet.)

**Comment by grondo** [comment]
If you'd like I could tackle the above

**Comment by grondo** [comment]
I verified all tests pass with the following commit on top of this PR:
```diff
diff --git a/src/cmd/flux.c b/src/cmd/flux.c
index 9b754a2..f8bc4df 100644
--- a/src/cmd/flux.c
+++ b/src/cmd/flux.c
@@ -186,16 +186,6 @@ int main (int argc, char *argv[])
     flux_conf_environment_unset (cf, "FLUX_CONF_USEFILE");
 
 
-    /* Get a broker handle if possible
-     * Subcommands may need this.
-     */
-    if (getenv ("FLUX_URI") && !((argc - optind) > 0
-                            && !strcmp (argv[optind], "start"))) {
-        if (!(h = flux_open (NULL, 0)))
-            err_exit ("flux_open");
-        optparse_set_data (p, "flux_t", h);
-    }
-
     /* Process configuration.
      * If not found, use compiled-in defaults.
      */
```

The side benefit is it removes that strange logic test that special cases `flux start`

**Comment by grondo** [comment]
Further cleanup could remove the use of the `"flux_t"` cached optparse data object since it isn't necessary -- remove the `-F, --file-config` option and subsequent test fixups.

I also wonder about the broker processing the config file directly.. are `flux.c` and `broker.c` the only places that load from a config file? It might simplify things to say that `flux-broker` is always run under `flux(1)` -- then we can rely solely on environment. I'm probably missing something crucial though.

**Comment by garlick** [comment]
> Seems like after this change the -F, --file-config option could be dropped? It doesn't seem to be used anymore in this branch?

I think that's right, and presumably the FLUX_CONF_USEFILE env variable too?

>  FLUX_CONNECTOR_PATH has not been updated to full path something:/xyz but is instead only /xyz

I think that's right though - this is a colon delimited search path not a URI.

Your proposed changes sound good to me.

**Comment by garlick** [comment]
Please feel free to close this PR and submit a new one.

**Comment by grondo** [comment]
> I think that's right though - this is a colon delimited search path not a URI.

I think I didn't explain it correctly. `flux.c` tries to use `flux_open()` before it has prepended internal `FLUX_CONNECTOR_PATH` to current `FLUX_CONNECTOR_PATH`. So in the test `FLUX_CONNECTOR_PATH=/xyz` (not the colon delimited path) -- so `flux_open()` necessarily fails with ambiguous `No such file or directory` error.

**Comment by garlick** [comment]
Oh I see, sorry.  I'm not really sure how to fix that ambiguous errno...

**Comment by garlick** [comment]
I'm going to close this - backref from #596 should still work if we need to see early discussion.

**Pull request closed without merging**
