### PR TITLE
kvs test cleanup

### PR DESCRIPTION
**Pull request by chu11**
Some simple kvs test cleanup I wanted to do.  Mostly put some common functions into ```kvs/kvs-helper.sh```, but some tiny things beyond that too.

### CODE REVIEW

**Comment by chu11** [comment]
oops, bourne shell uses ```.``` and not ```source```.   Re-pushed with fixes.

**Comment by chu11** [comment]
oops, forgot to add helper file to dist.  Re-pushed again.

**Comment by chu11** [comment]
Hit #731, restarted a builder

```FAIL: t0016-cron-faketime.t 3 - flux-cron tab works for set minute```

**Comment by garlick** [comment]
This looks good to me.  If you're done tweaking it, I vote we merge.

**Comment by grondo** [comment]
I'm not commenting on this PR specifically, however if someone does more cleanup in the future, you could see if the busywaiting in `wait_watch_file()` could be replaced with `t/scripts/waitfile.lua` which uses libev statwatcher to more efficiently wait for a line in a file to match a pattern. 

(I didn't look closely at what `wait_watch_file` actually does so I apologize in advance if the waitfile helper script doesn't apply here)

**Comment by chu11** [comment]
@garlick  i thought of one extra cleanup this morning, so I just pushed that.  Otherwise, it's good to go.

**Comment by chu11** [comment]
@grondo I wasn't aware of the waitfile.lua script, but it seems (glossing over the help comments) like it could probably work.  Will have to investigate in the future.

**Comment by garlick** [comment]
Hmm, any idea why that last change dropped the project coverage into the red?  Did something stop running I wonder?

**Comment by grondo** [comment]
> Hmm, any idea why that last change dropped the project coverage into the red? Did something stop running I wonder?

The coverage only changed -0.02% which is negligible (and probably caused by coverage "noise" that I don't quite understand yet). Codecov should have some tunable that indicates only a drop in coverage of X% should turn the report red (I thought we'd set that already)

**Comment by garlick** [comment]
Oh right, I guess that is not anything to worry about.  I'll go ahead and merge.

**Pull request merged**
