### PR TITLE
Hwloc import

### PR DESCRIPTION
**Pull request by trws**
This adds support to load pre-made xml files for hwloc rather than reading the configuration from the system.  For now, the main benefit of this is testing and integration with the new sched hwloc xml support, but loading from XML is also *much* faster than dynamically reading all of the information when dealing with large nodes, so it may also serve as an optimization later.  The implementation uses the existing config mechanism, and accepts either a per-rank or a default topology, which is then loaded by each rank as normal and presented just like a dynamically loaded topology.  An example config might look like this:

```
resource
    hwloc
        default_xml = /g/g12/scogland/projects/flux/bolt.xml
        xml
            2 = /g/g12/scogland/projects/flux/cab.xml
```
An easy test for correctness, the one I used and am trying to figure out how to work into our testing infrastructure (do we have config tests right now?) is to use start and lstopo together after adding a non-local topology to the config file.  For convenience, I used the hwloc topology of my laptop, which is pretty easy to distinguish from a node of cab. =P

NOTE: The files are loaded and used by ranks, flux lstopo does not preserve those ranks as machine logical IDs however.  This could be done, but requires modification of the topology after creation, which has not seemed worth it as yet.

```
$ flux start -s 4 flux lstopo --of console
[1445277287.879023] resource-hwloc.info[0]: resource_hwloc: loaded from 2
[1445277287.879700] resource-hwloc.info[0]: resource_hwloc: loaded from 1
[1445277287.880354] resource-hwloc.info[0]: resource_hwloc: loaded from 0
[1445277287.880990] resource-hwloc.info[0]: resource_hwloc: loaded from 3
[1445277287.889264] resource-hwloc.info[0]: resource_hwloc: loaded from 2
[1445277287.889917] resource-hwloc.info[0]: resource_hwloc: loaded from 1
[1445277287.890631] resource-hwloc.info[0]: resource_hwloc: loaded from 0
[1445277287.891243] resource-hwloc.info[0]: resource_hwloc: loaded from 3
ignoring invalid distance matrix with 2 objs instead of 5
System (80GB)
  Machine L#0 (32GB)
    NUMANode L#0 (P#0 16GB)
      Socket L#0 + L3 L#0 (20MB)
        L2 L#0 (256KB) + L1d L#0 (32KB) + Core L#0
          PU L#0 (P#0)
          PU L#1 (P#16)
        L2 L#1 (256KB) + L1d L#1 (32KB) + Core L#1
          PU L#2 (P#1)
          PU L#3 (P#17)
        L2 L#2 (256KB) + L1d L#2 (32KB) + Core L#2
          PU L#4 (P#2)
          PU L#5 (P#18)
        L2 L#3 (256KB) + L1d L#3 (32KB) + Core L#3
          PU L#6 (P#3)
          PU L#7 (P#19)
        L2 L#4 (256KB) + L1d L#4 (32KB) + Core L#4
          PU L#8 (P#4)
          PU L#9 (P#20)
        L2 L#5 (256KB) + L1d L#5 (32KB) + Core L#5
          PU L#10 (P#5)
          PU L#11 (P#21)
        L2 L#6 (256KB) + L1d L#6 (32KB) + Core L#6
          PU L#12 (P#6)
          PU L#13 (P#22)
        L2 L#7 (256KB) + L1d L#7 (32KB) + Core L#7
          PU L#14 (P#7)
          PU L#15 (P#23)
      HostBridge L#0
        PCIBridge
          PCI 1077:7322
            Net L#0 "ib0"
            OpenFabrics L#1 "qib0"
        PCIBridge
          PCI 8086:1d69
        PCIBridge
          PCI 8086:1521
            Net L#2 "eth0"
          PCI 8086:1521
            Net L#3 "eth1"
        PCIBridge
          PCI 102b:0522
        PCI 8086:1d02
          Block L#4 "sda"
    NUMANode L#1 (P#1 16GB) + Socket L#1 + L3 L#1 (20MB)
      L2 L#8 (256KB) + L1d L#8 (32KB) + Core L#8
        PU L#16 (P#8)
        PU L#17 (P#24)
      L2 L#9 (256KB) + L1d L#9 (32KB) + Core L#9
        PU L#18 (P#9)
        PU L#19 (P#25)
      L2 L#10 (256KB) + L1d L#10 (32KB) + Core L#10
        PU L#20 (P#10)
        PU L#21 (P#26)
      L2 L#11 (256KB) + L1d L#11 (32KB) + Core L#11
        PU L#22 (P#11)
        PU L#23 (P#27)
      L2 L#12 (256KB) + L1d L#12 (32KB) + Core L#12
        PU L#24 (P#12)
        PU L#25 (P#28)
      L2 L#13 (256KB) + L1d L#13 (32KB) + Core L#13
        PU L#26 (P#13)
        PU L#27 (P#29)
      L2 L#14 (256KB) + L1d L#14 (32KB) + Core L#14
        PU L#28 (P#14)
        PU L#29 (P#30)
      L2 L#15 (256KB) + L1d L#15 (32KB) + Core L#15
        PU L#30 (P#15)
        PU L#31 (P#31)
  Machine L#1 (16GB) + NUMANode L#2 (P#0 16GB) + L3 L#2 (6144KB)
    L2 L#16 (256KB) + L1d L#16 (32KB) + Core L#16
      PU L#32 (P#0)
      PU L#33 (P#1)
    L2 L#17 (256KB) + L1d L#17 (32KB) + Core L#17
      PU L#34 (P#2)
      PU L#35 (P#3)
    L2 L#18 (256KB) + L1d L#18 (32KB) + Core L#18
      PU L#36 (P#4)
      PU L#37 (P#5)
    L2 L#19 (256KB) + L1d L#19 (32KB) + Core L#19
      PU L#38 (P#6)
      PU L#39 (P#7)
  Machine L#2 (16GB) + NUMANode L#3 (P#0 16GB) + L3 L#3 (6144KB)
    L2 L#20 (256KB) + L1d L#20 (32KB) + Core L#20
      PU L#40 (P#0)
      PU L#41 (P#1)
    L2 L#21 (256KB) + L1d L#21 (32KB) + Core L#21
      PU L#42 (P#2)
      PU L#43 (P#3)
    L2 L#22 (256KB) + L1d L#22 (32KB) + Core L#22
      PU L#44 (P#4)
      PU L#45 (P#5)
    L2 L#23 (256KB) + L1d L#23 (32KB) + Core L#23
      PU L#46 (P#6)
      PU L#47 (P#7)
  Machine L#3 (16GB) + NUMANode L#4 (P#0 16GB) + L3 L#4 (6144KB)
    L2 L#24 (256KB) + L1d L#24 (32KB) + Core L#24
      PU L#48 (P#0)
      PU L#49 (P#1)
    L2 L#25 (256KB) + L1d L#25 (32KB) + Core L#25
      PU L#50 (P#2)
      PU L#51 (P#3)
    L2 L#26 (256KB) + L1d L#26 (32KB) + Core L#26
      PU L#52 (P#4)
      PU L#53 (P#5)
    L2 L#27 (256KB) + L1d L#27 (32KB) + Core L#27
      PU L#54 (P#6)
      PU L#55 (P#7)
[1445277287.898450] broker.info[0]: 0: shutdown in 0.500s: Exited
```

### CODE REVIEW

**Comment by trws** [comment]
Ah, this also contains #449, since I needed that to build it.  If that is accepted I'll rebase, or if this goes in I can just close #449.

**Comment by grondo** [comment]
Oops @trws, I saw the `lua LN` fix first so I went ahead and merged it

**Comment by trws** [comment]
No worries, already rebased.

**Comment by garlick** [comment]
> An easy test for correctness, the one I used and am trying to figure out how to work into our testing infrastructure (do we have config tests right now?)

Just unit tests (src/common/libflux/test/conf.c).

We need the in-tree config (etc/flux/config) to point to the in-tree paths.  It seems like we need some way to alter that config (as opposed to starting from scratch) for particular test situations.  Should we come up with a way to load the config from multiple files?

A bit off topic for this PR but the config scheme has always felt a bit off to me.  If we could agree on a sensible way to overhaul it (including getting of the oddball ZPL format), I'd be for that.

**Comment by grondo** [comment]
Don't we have a way to alter config at runtime? (Load default config, then override) I'm using this for testing wrexecd plugins from outside the configured path.  IIRC, though, I had to update config in kvs directly, `flux config` doesn't update the current config only the config on disk (?), so it does seem like the config subsystem might need a redesign.

**Comment by garlick** [comment]
Just opened #452 to discuss a config rework.

In the mean time, what about wiring up the fake hwloc data o be the default for in-tree testing (via etc/flux)?  It seems like relying on the actual hwloc data will make it difficult to expand tests that do anything with hwloc data.

To distinguish between in-tree testing and a real run that uses the in-tree config, maybe sharness `test_under_flux()` could supply an option via `-o,--modopt` to indicate that the fake data in the config file should be used, and otherwise ignore it?

**Comment by grondo** [comment]
I wouldn't want to hard code options for `resource.hwloc`, but what if we passed positional parameters past `$1` directly to `flux start` in `test_under_flux` so tests specific to `resource.hwloc` could directly load a config of their choosing (though I still think dynamically modifying config is more straightforward and flexible), e.g.

```
test_under_flux ${SIZE} -o --modopt=<something>
```

Something as simple as this could work (not tested), and would allow tests to pass arbitrary options to flux start as well:

```diff
diff --git a/t/sharness.d/flux-sharness.sh b/t/sharness.d/flux-sharness.sh
index 4a7aae6..75efec4 100644
--- a/t/sharness.d/flux-sharness.sh
+++ b/t/sharness.d/flux-sharness.sh
@@ -45,7 +45,7 @@ run_timeout() {
 #  Usage: test_under_flux <size>
 #
 test_under_flux() {
-    size=${1:-1}
+    size=shift;
     log_file="$TEST_NAME.broker.log"
     if test -n "$TEST_UNDER_FLUX_ACTIVE" ; then
         cleanup rm "${SHARNESS_TEST_DIRECTORY:-..}/$log_file"
@@ -68,7 +68,7 @@ test_under_flux() {
 
     TEST_UNDER_FLUX_ACTIVE=t \
     TERM=${ORIGINAL_TERM} \
-      exec flux start --size=${size} ${quiet} "sh $0 ${flags}"
+      exec flux start --size=${size:-1} ${quiet} "$@" "sh $0 ${flags}"
 }
 
 mock_bootstrap_instance() {
```

**Comment by trws** [comment]
These are probably good ideas.  As to doing a runtime load, it would probably have to be an extra event or command to reload the hwloc data after initial setup to support that.  If that would be useful it wouldn't be all that bad to add it, but it might invalidate users that assume the topology does not change dynamically for a given resource.

**Comment by grondo** [comment]
It might be needed even for normal use case (eventually) though,  if a job and thus its container changes size. However, I'm fine with delaying that for future work.

**Comment by trws** [comment]
That's a good point.  I can set it up as a per-rank command with a global event to hit everyone.  It's a pretty small addition really, just deallocate the original and re-load from the configuration.  May give it an option to accept a config path/buffer on the message as well I suppose.

**Comment by dongahn** [comment]
This should be very useful for sched testing as well!  If you are going to make some fake hwloc data available in flux-core, sched can test against that data as well.

**Comment by grondo** [comment]
We talked about merging this PR immediately into flux-core and delaying the in-progress stuff for later. If I can get another ACK from @dongahn and @garlick I'll merge this one, or if either of you decide to press merge consider this my ACK.

One minor nit is I think the commit title and description could be made more clear, perhaps something more like `resource-hwloc: support alternate hwloc data` or similar. However, since @trws is out, this isn't a showstopper if we want to merge this immediately.

**Comment by dongahn** [comment]
Yes, this is fine by me. This will help `sched` beef up its testing environment.

**Comment by trws** [comment]
Sorry about the commit messages, I was planning to clean that up after adding in what we discussed.  If you'd like I can go in and do a re-work on those and rebase master.  Since the merge node is the top commit this would be the time.  Otherwise, I'll add a couple of issues to track the things that remain to be done here, or at least tested.  After the comments about cab yesterday, it's possible the other things are less problematic than I thought, as I was testing on cab.

**Comment by garlick** [comment]
@trws no worries on the commit message, let's just move on.  Rebasing master could be more trouble than it's worth.

**Comment by grondo** [comment]
Agreed. Like I said it was a pretty minor nit

**Pull request merged**
