### PR TITLE
shell: fix issues with CUDA_VISIBLE_DEVICES value

### PR DESCRIPTION
**Pull request by grondo**
This PR should fix the issues described in #3315 and #3221

### CODE REVIEW

**Comment by dongahn** [comment]
Look great to me.

Does flux-core have a hwloc XML file from a system with GPUs on it like https://github.com/flux-framework/flux-sched/tree/master/t/data/hwloc-data/004N/exclusive/04-brokers-sierra2?

If so, would it possible to add the following tests?

I understand it is difficult to test actually running of GPU codes because Travis won't have such machines. But it seems we can at least add one step deeper tests using `hwloc`?

`/usr/global/tools/hwloc/blueos_3_ppc64le_ib/hwloc-1.11.10-cuda/bin/hwloc-ls --of xml | grep CoProc`

Make sure the matching line count match with the count of request GPUs?

Also `hwloc` won't report any GPU when -1 is assigned to `CUDA_VISIBLE_DEVICES`?

This way, if `hwloc` somehow changes how it behaves w/ respect to this env variable, our tests will catch it?

**Comment by grondo** [comment]
Yeah, we have a couple sierra XML files with GPUs, and some tests that ensure CUDA_VISIBLE_DEVICES is set appropriately for jobs which request GPUs.

> /usr/global/tools/hwloc/blueos_3_ppc64le_ib/hwloc-1.11.10-cuda/bin/hwloc-ls --of xml | grep CoProc
> Make sure the matching line count match with the count of request GPUs?
> Also hwloc won't report any GPU when -1 is assigned to CUDA_VISIBLE_DEVICES?
> This way, if hwloc somehow changes how it behaves w/ respect to this env variable, our tests will catch it?

Hm, we could add that though we don't change the version of hwloc in our automated CI very often, and those seem more like hwloc tests not flux tests...

**Comment by dongahn** [comment]
> Hm, we could add that though we don't change the version of hwloc in our automated CI very often, and those seem more like hwloc tests not flux tests...

This could be useful if we `make check` on actual HPC systems like Sierra or future extended CI tests?

I kind of agree this should be a partner test. However it would be our judgement call: how much we trust our partner software will keep backward compatibility. 

You call.

**Comment by grondo** [comment]
> This could be useful if we make check on actual HPC systems like Sierra or future extended CI tests?

Yeah, tests like these would be good to run when we are able to do automated CI on LC systems.

Hm, it doesn't appear that hwloc uses CUDA_VISIBLE_DEVICES when the input is from XML:
```
ƒ(s=4,d=0,builddir) grondo@asp:~/git/flux-core.git$ hwloc-ls  --if xml -i t/hwloc-data/sierra2/0.xml | grep CoProc
          CoProc L#9 "cuda0"
          CoProc L#12 "cuda1"
          CoProc L#21 "cuda2"
          CoProc L#24 "cuda3"
ƒ(s=4,d=0,builddir) grondo@asp:~/git/flux-core.git$ CUDA_VISIBLE_DEVICES=-1 hwloc-ls  --if xml -i t/hwloc-data/sierra2/0.xml | grep CoProc
          CoProc L#9 "cuda0"
          CoProc L#12 "cuda1"
          CoProc L#21 "cuda2"
          CoProc L#24 "cuda3"
ƒ(s=4,d=0,builddir) grondo@asp:~/git/flux-core.git$ CUDA_VISIBLE_DEVICES=0 hwloc-ls  --if xml -i t/hwloc-data/sierra2/0.xml | grep CoProc
          CoProc L#9 "cuda0"
          CoProc L#12 "cuda1"
          CoProc L#21 "cuda2"
          CoProc L#24 "cuda3"
```

However, we could test for locally discovered CoProcs and set a HAVE_HWLOC_COPROC prereq, then test hwloc functionality as you suggest above. I don't really like writing tests that are machine dependent, but we already do have some of those and it may be useful as you say, so I'll look at adding something.

**Review by garlick — APPROVED** [review]
This looks good.  Could we maybe merge this now and open an issue on @dongahn's suggestion of platform-specific tests?

**Comment by grondo** [comment]
Ok, I opened #3319 and set MWP. Thanks!

**Comment by grondo** [comment]
@mergifyio rebase

**Pull request merged**
