### PR TITLE
Fix --rank issues, add NODESET documentation, and minor cleanup

### PR DESCRIPTION
**Pull request by chu11**
Well, what began as noticing a doc error in the ping manpage lead to a lot more.  I should maybe split this up into multiple PRs, but I'll leave it all in as it is generally a large batch of small things.  LMK if it'd be better to split up.  

- Per discussion in #854 , support --rank="all" across all tools and add tests appropriately.  Nothing too fancy here.

- Support tests for invalid ranks in tools.  Found bugs in flux-ps and flux-ping as a result.  I'd appreciate review on the bug fixes commits 31b6c2697d815b1c6b702b17686e59e19658bfa4 and
1bd8f9393f17e76bfa8c6da81fb394d179164c57, particularly the latter.  Perhaps there is something nifty that can be done in the flux api that I don't see at the moment.

- Added misc tests I thought should be there, invalid ping targets, invalid modules, module info tests.

- Per discussion in #854, made ```--rank=NODESET``` the consistent documentation across all tools and manpages and added ```NODESET FORMAT``` section to all appropriate manpages.  Would appreciate review on the text to see if I'm missing anything.  Commit 0205fb496d1438c009038cf11eb829009f74f481.

### CODE REVIEW

**Comment by garlick** [comment]
I'll have a closer look tomorrow but this looks like really nice work @chu11!

Btw the gcc T_INSTALL travis test failed here:
```
Found ./t/lua-t0002-rpc.broker.log
2016-10-20T01:39:04.929990Z broker.info[0]: pmi: bootstrap time 0.0s
2016-10-20T01:39:04.937804Z broker.info[0]: wireup: 2/2 (complete) 0.0s
2016-10-20T01:39:04.937824Z broker.info[0]: Run level 1 starting
2016-10-20T01:39:05.444550Z broker.err[0]: rc1: flux-module: flux_open: No such file or directory
2016-10-20T01:39:05.444909Z broker.err[0]: Run level 1 Exited with non-zero status (rc=1) 0.5s
2016-10-20T01:39:05.445074Z broker.info[0]: Run level 3 starting
2016-10-20T01:39:05.445737Z broker.info[0]: shutdown in 0.500s: run level 1 Exited with non-zero status
```
I'm restarting - looks like possibly flux_open didn't wait long enough for broker socket to appear?

**Comment by grondo** [comment]
Nice work, LGTM as far as that's worth.

My only comment is it might be an interesting exercise to rewrite `flux-ping` from scratch using the most modern flux APIs, to see how much more it could be simplified (especially `flux_rpc_getf` might be helpful here). Even if nothing comes of it, you might uncover issues or have comments on the APIs and their documentation as you seem to be good at that kind of thing @chu11!

**Comment by garlick** [comment]
That's a good idea re: reworking ping especially the JSON manipulation.

**Comment by chu11** [comment]
Seems like a good idea, I need to learn the flux rpc api anyways.  We'll add it to the TODO list.

**Comment by garlick** [comment]
Sorry, forgot to get back to this.  Looks great - merging!

**Pull request merged**
