### PR TITLE
ci: consolidate python linting and formatting

### LINKED ISSUE #4631: Review Python linting strategy and possible automation

### PR DESCRIPTION
**Pull request by vsoch**
Problem: the developer experience is challenging because linting and formatting are hard to debug locally, and then the separation in the CI means 3+ clicks to see what is going on! To fix this, this changeset adds the use of pre-commit, which will always run linting/formatting (and with automated fixes for a subset of the tools) right before commit, so the developer can have some confidence that passing locally == passing in the CI. In the case that there is a bug in the CI, we will now just have one place to look instead of 3+. This should be a start of a new setup, including addition of pre-commit and consolidation of settings into a pyproject.toml (and setup.py for flake8) and we can further tweak as we establish our linting preferences. In summary:

- I've added pre-commit and a scripts/requirements.dev.txt to install all linting/ formatting deps
- I've added a developer.rst to the Python docs to show how to use this
- I've removed the custom linting shell scripts in scripts (in practice I found running them gave me different results than the CI, likely because of versioning)
- I've added a pyproject.toml with preferences for mypi, and black
- To make the developer.rst complete, I included the instructions I use to develop Python (and removed the --without-python in the container).

Note that isort and flake8 are currently not being added, as we learned in #4634 that they broke the CI! My proposal is to get this into master, and then do incremental changes to figure out what broke the testing. If it's an issue that import order is important, it's fine to leave as is, but I think we need to understand why (and document it).

And here is a previous screenshot in action! Note that isort/flake8 have since been disabled. Note that it's running the checks just before I commit, so I can fix any issues before I do.

image

And pre-commit  is super cool - it's like being in a candy store! https://github.com/pre-commit/pre-commit-hooks
I also tested with rebase to ensure it works! This will close #4631 

Signed-off-by: vsoch <vsoch@users.noreply.github.com>

### CODE REVIEW

**Comment by grondo** [comment]
In case this is helpful - you can enable github actions in your personal repo and then the actions will all run there. I do this often to ensure CI will run successfully or when I'm debugging a CI problem. This way you wouldn't have to open multiple PRs here, you can just push to new branches in your fork.

**Comment by vsoch** [comment]
HOLY COW GREEN! That means that isort / flake8 linting... broke everything? I'm equally fascinated and horrified. :scream: I don't think I've ever encountered a case where changing import order or basic linting has broken an entire project, but I can follow up here with incremental changes (likely flake8 fixes first) to see what is the straw the broke the camel's back. We will want to document / comment the heck of it that so future developers know and don't go through this same process again.

> In case this is helpful - you can enable github actions in your personal repo and then the actions will all run there.

Hmm, at least for the previous (much earlier) PRs I opened, I think I found that actions didn't work consistently there (so I disabled them). I could definitely try again! And sorry again for the multiple PRs - I hope it's OK because it's a weekend and it's likely to have more cycles free? Does anyone else have no life balance and work on the weekends like me? :laughing: Bueller... bueller... ... :eyes: 

OK going to close down the other failure PRs and this will be the main one. Thanks for being patient with me!

**Comment by vsoch** [comment]
That's kind of weird it's waiting for the (since removed) checks - I wonder if that's some kind of CI cache.

**Comment by vsoch** [comment]
@grondo (no rush, not tonight, when you can!) let me know what changes you'd like to see here. I'd like to follow up this one with testing what broke the CI before (I think it was isort!) But if it wasn't flake8, we can add some nice linting, and then I can rebase #4623 to use it!

**Comment by grondo** [comment]
Ok, this is a start after a quick look and attempt to do some development on this branch. Feel free to educate me if I'm saying anything wrong below!

`pre-commit` is kind of neat! However, this gives me a little concern:

> Run `pre-commit install` to install pre-commit into your git hooks. `pre-commit` will now run on every commit. Every time you clone a project using `pre-commit` running `pre-commit` install should always be the first thing you do.

I'm not sure all developers of flux-core will think to or remember to do this on every clone, especially since this project is 90% C and 10% Python and the pre-commit hooks only apply to Python (so they may not think to look down in `doc/python/developer.rst`). In that case, I suppose the new CI checks will catch any errors as we had before? (I admit I haven't fully understood all the changes happening here, so apologies if my question is dumb!) 

Once I got `pre-commit` working by `pip install pre-commit` and `pre-commit install`, I now can't commit any files:

```
      ERROR: Command errored out with exit status 1:
       command: /home/grondo/.cache/pre-commit/repo8rcn2z97/py_env-python3/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/grondo/.cache/pre-commit/repo8rcn2z97/setup.py'"'"'; __file__='"'"'/home/grondo/.cache/pre-commit/repo8rcn2z97/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-jnbbxzyz
           cwd: /home/grondo/.cache/pre-commit/repo8rcn2z97/
      Complete output (6 lines):
      Traceback (most recent call last):
        File "<string>", line 1, in <module>
        File "/home/grondo/.cache/pre-commit/repo8rcn2z97/setup.py", line 1
          from __future__ import annotations
          ^
      SyntaxError: future feature annotations is not defined
      ----------------------------------------
```

Any idea what is going on? Unfortunately, we don't want to break existing developers workflows with this new scheme for linting and formatting. We can probably convince people to add `pre-commit` to their environment, but only if it can work in everyone's existing environment without disruption.

Some other high level comments in no particular order:

 - It would be ideal if this PR didn't introduce any code changes, just the pre-commit hooks and new CI for running them against PRs. I'm not exactly sure why the new checks required so much change. Maybe if we start with the same formatter and linter as before, but using `pre-commit` if possible, no changes to existing code would be necessary? 
 - Probably someone can convince me otherwise, but I really don't want unrelated formatting and whitespace changes introduced in PRs. How can we ensure that without pinning the versions of the linting and formatting tools? E.g. a new version of `black` or `flake8` comes out and I try to propose a new feature -- now I have to change unrelated code to adhere to the updated tools. This makes project history confusing. It would be better if we updated tools at specific time points and then made PRs that introduced the new versions and addressed any changes (My opinion!)
 - This PR should be split into multiple commits for easier digestion. E.g. "Introduce pre-commit", "add documentation for pre-commit use", "modify python code as required for new pre-commit hooks", etc.
 - It might be best to leave the `scripts/format` and `scripts/pylint` for now since all the other developers are used to using them? Then once we've gotten everyone transitioned over to the new scheme, the scripts could be removed.
 - General comment: commit message should be wrapped at around 72 lines, good job with the Problem statement

**Comment by vsoch** [comment]
I added the hard coded scripts back, and more verbosity to the docs that the developer isn't required to use these.

**Comment by vsoch** [comment]
So…. Adding back the old lint and formatting files re-broke the tests?!

I just can’t. 😭

**Comment by grondo** [comment]
> That looks to be a Python 3.6 issue - if you use 3.7 and up it won't be an issue.

Unfortunately this is a project that is intended to be used and developed in production on systems that still run Python 3.6, so to be useful we should make sure all components of the development workflow support Python 3.6.

> I'm not sure in practice how to achieve that - running the tool with mypy, etc. changes the code, and the CI wouldn't pass.

I'm probably just being naive, but we were running pylint, black, and mypy before (I think? Not sure about mypy). Is this just because we're jumping to the latest versions?

> I don't know how to artificially split a changeset that (in my opinion is logically grouped) into different commits - to be totally honest with you this feels like it is questionably useful and is making it harder for me (or anyone) to contribute to the project (and I will be less likely).

Ok well it isn't really that big of a deal in this case, but I suggested it because it follows the established project style and the spirit of  [RFC 1 - Patch requirements](https://flux-framework.readthedocs.io/projects/flux-rfc/en/latest/spec_1.html#patch-requirements).

> at least they didn't reproduce the issues I saw in the CI.

The CI actually runs those scripts, so they should reproduce issues exactly if the correct versions of pylint and black are installed. I wonder if we should have had a nice `requirements.txt` like you've added here all along.

> In developing Flux I was nipped in the butt just about every time for trailing white spaces, and pre-commit is fixing that. Why is that an issue?

Sorry, I didn't mean that fixing formatting in code that is being added is a problem. That is exactly right and your PR fixes that nicely for developers that install the pre-commit hooks.

I was referencing an issue we had in the past (maybe 5 years ago or so?) where the `black` formatter or `pylint` upstream version was updated, and the CI pulled it in on a PR that didn't even touch Python code. So now a PR that makes changes to core code also has to include trivial formatting changes in Python to pass CI (or a precursor PR has to be submitted to `update to conform to pylint version X`. How can we prevent this from happening again?

**Comment by vsoch** [comment]
hmm ok - so where are the instructions for your Python developers for setting up the correct environment? I use Python 3.9.

**Comment by vsoch** [comment]
This isn't going to work with Python 3.6 - it's too old. I would have to go back to a version of pre-commit from almost 5 years ago and the formatting is totally different and it's confusing if you are used to working on a modern version. I also can't reliably create a 3.6 environment - when I use a container it's going to change all file permissions to run as root from the inside. Ping me when the 3.6 requirement is lifted, sorry!

**Comment by vsoch** [comment]
@grondo - @trws restored some hope because he realized that we need to also pin the version of the hooks, and unlike pre-commit (which is like, 5 years old to go back to a Python 3.6) the hooks are only about a year old that would work with Python 3.6! To get this to work I couldn't use the .pyproject.toml with mypy (it never took) but instead I added a custom entrypoint to run mypy and point to the config already in the repository. Also, note that black and mypy are pinned. So (I think?) that gets us to a point where the repository linting/formatting is the same as it is now, but running with pre-commit (and a nicer developer experience?) I also think it's important to add these developer docs alongside because a new developer (that doesn't have python 3.6 installed natively) isn't going to know how to go about doing things. And I'm not very good at reading lists of rules (obviously, lol).

**Comment by grondo** [comment]
Wow, cool! Thanks for not giving up on this! I'm all for it if it helps you and other mostly-Python devs.

**Comment by vsoch** [comment]
@grondo it's not just for Python devs - we can potentially add cppcheck and the other checks Flux does here too :)

**Comment by vsoch** [comment]
Let me know what changes you'd like to see! I think if you try this out locally it should work this time... famous last words... fingers crossed! :crossed_fingers:

**Comment by trws** [comment]
That's the hope, if we can get all the normal lints for the whole project in there it would be a nice win for local test ergonomics.  The cppcheck one is the one that came to mind, but do we have other c or lua lints or checks we can/should include here? We could include the commit message lints as well potentially though I don't recall how those are implemented.

**Comment by vsoch** [comment]
We could figure something out, but per the scope rules of doing a PR here I think that would be a separate one? And I'd want to add in flake8 checks first!

**Comment by trws** [comment]
I assume we need to rework the required checks list for this one to pass, otherwise are we in a stable spot here?

**Comment by vsoch** [comment]
yep I see that in settings:

image

But probably we'd change it after so the other PRs don't bork.

**Comment by grondo** [comment]
I tried out this branch in my development environment and now the `./scripts/format` script is broken:
```
t$ ./scripts/format 
Traceback (most recent call last):
  File "/home/grondo/.local/bin/black", line 11, in <module>
    sys.exit(patched_main())
  File "/home/grondo/.local/lib/python3.6/site-packages/black/__init__.py", line 6607, in patched_main
    main()
  File "/home/grondo/.local/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/grondo/.local/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/grondo/.local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/grondo/.local/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/grondo/.local/lib/python3.6/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/grondo/.local/lib/python3.6/site-packages/black/__init__.py", line 536, in main
    report=report,
  File "/home/grondo/.local/lib/python3.6/site-packages/black/__init__.py", line 584, in get_sources
    exclude_regex = re_compile_maybe_verbose(exclude)
  File "/home/grondo/.local/lib/python3.6/site-packages/black/__init__.py", line 6259, in re_compile_maybe_verbose
    compiled: Pattern[str] = re.compile(regex)
  File "/home/grondo/.local/lib/python3.6/site-packages/regex/regex.py", line 349, in compile
    return _compile(pattern, flags, ignore_unused, kwargs)
  File "/home/grondo/.local/lib/python3.6/site-packages/regex/regex.py", line 450, in _compile
    if _locale_sensitive.get(locale_key, True) or (flags & LOCALE) != 0:
TypeError: unhashable type: 'list'
```

Also, the PR seems to change the line length for `black` (and possibly some other options?), which results in some unnecessary changes to existing files (and thus conflicts with recent work). My goal would be to remove most of the differences  between what we had before to minimize changes to existing code in the PR (ideally, there would be no changes, but with the extra linting added here, perhaps that is not possible)

**Comment by trws** [comment]
The black thing came from a spack study that packages and core files had the least change from current going with a length of 100.  I think we were using the black default before, which is 88 IIRC, and since we don't have massive hashes all over the place might be ok.  @vsoch, what do you think about setting the length back to black default for black and flake8?

**Comment by vsoch** [comment]
Yep can definitely do that! But I'm staring at that error when the format script is run and trying to understand what is going on... whatever `_locale_sensitive` is ... is a list? :thinking:

**Comment by trws** [comment]
It's internal to black, it's like there's an incompatible option type that gets strangely deep, or it's a version mismatch? @grondo, did you update your requirements from the requirements file?

**Comment by grondo** [comment]
Yeah, I don't really understand the error from `black` on this branch either. I assumed something in my environment, but when I switch back to the main branch, `./scripts/format` runs fine! I'm a bit baffled.

**Comment by vsoch** [comment]
> It's internal to black, it's like there's an incompatible option type that gets strangely deep, or it's a version mismatch? @grondo, did you update your requirements from the requirements file?

That _should_ be the same version that is currently used in the CI, `black==20.08.b1`

**Comment by trws** [comment]
I'll try to repro, something odd is going on...  What are your locale settings?

**Comment by grondo** [comment]
```
ƒ(s=1,d=1,builddir) grondo@asp:~/git/flux-core.git$ locale
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

**Comment by grondo** [comment]
Yeah, I updated from `requirements-dev.txt` and no difference. I can't imagine what could cause this:
```
ƒ(s=1,d=1,builddir) grondo@asp:~/git/flux-core.git$ black src/cmd/flux-mini.py 
Traceback (most recent call last):
  File "/home/grondo/.local/bin/black", line 11, in <module>
    sys.exit(patched_main())
  File "/home/grondo/.local/lib/python3.6/site-packages/black/__init__.py", line 6607, in patched_main
    main()
  File "/home/grondo/.local/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/grondo/.local/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/grondo/.local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/grondo/.local/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/grondo/.local/lib/python3.6/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/grondo/.local/lib/python3.6/site-packages/black/__init__.py", line 536, in main
    report=report,
  File "/home/grondo/.local/lib/python3.6/site-packages/black/__init__.py", line 584, in get_sources
    exclude_regex = re_compile_maybe_verbose(exclude)
  File "/home/grondo/.local/lib/python3.6/site-packages/black/__init__.py", line 6259, in re_compile_maybe_verbose
    compiled: Pattern[str] = re.compile(regex)
  File "/home/grondo/.local/lib/python3.6/site-packages/regex/regex.py", line 349, in compile
    return _compile(pattern, flags, ignore_unused, kwargs)
  File "/home/grondo/.local/lib/python3.6/site-packages/regex/regex.py", line 450, in _compile
    if _locale_sensitive.get(locale_key, True) or (flags & LOCALE) != 0:
TypeError: unhashable type: 'list'
ƒ(s=1,d=1,builddir) grondo@asp:~/git/flux-core.git$ git checkout master
Switched to branch 'master'
Your branch is up to date with 'origin/master'.
ƒ(s=1,d=1,builddir) grondo@asp:~/git/flux-core.git$ black src/cmd/flux-mini.py 
All done! ✨ 🍰 ✨
1 file left unchanged.
```

`black` must be reading something in the current directory that is part of this branch? Indeed, if I cd to `src` then `black` works:

```
ƒ(s=1,d=1,builddir) grondo@asp:~/git/flux-core.git/src$ black cmd/flux-mini.py 
All done! ✨ 🍰 ✨
1 file left unchanged.
```

Unsure what that might be though...

**Comment by grondo** [comment]
Ok, I did `pip3 install --force-reinstall -r scripts/requirements-dev.txt` and the issue went away :shrug: 

I'll reserve my comments about pip for inside my own head. 

Moving on! Now I think the only remaining problem is likely the `black` options! (I get different results from `pre-commit` vs `./scripts/format`)

**Comment by trws** [comment]
Oh good, ok.  The differences are strange though, the settings should be coming from the pyproject.toml...

**Comment by vsoch** [comment]
okay I'm building a container to attempt updating the settings for black and rebasing - wish me luck because I'm expecting this to bork!

**Comment by vsoch** [comment]
The previously working container doesn't work for me anymore:

```
RuntimeError: failed to find interpreter for Builtin discover of python_spec='python3.6'
```
I'm going to reset everything and try again from within the dev containers environment.

**Comment by trws** [comment]
I've been testing with `python:3.6` just so I don't have to deal with the python version issue.

**Comment by vsoch** [comment]
okay catch -22 - can't get the .devcontainer environment without rebasing, can't rebase either...
```
Auto-merging src/bindings/python/flux/util.py
Auto-merging src/bindings/python/flux/job/info.py
CONFLICT (content): Merge conflict in src/bindings/python/flux/job/info.py
error: could not apply 611950662... consolidate python linting and formatting
Resolve all conflicts manually, mark them as resolved with
"git add/rm <conflicted_files>", then run "git rebase --continue".
You can instead skip this commit: run "git rebase --skip".
To abort and get back to the state before "git rebase", run "git rebase --abort".
Could not apply 611950662... consolidate python linting and formatting
```

**Comment by trws** [comment]
This is what I got running in a python:3.6 container:

```console
root@a5917c362f4a:/curdir# pre-commit run --all
Check for added large files..............................................Passed
Check for case conflicts.................................................Passed
Check docstring is first.................................................Passed
Check that scripts with shebangs are executable..........................Passed
Fix End of Files.........................................................Passed
Trim Trailing Whitespace.................................................Passed
Mixed line ending........................................................Passed
black....................................................................Passed
mypy.....................................................................Passed
root@a5917c362f4a:/curdir# ./scripts/format
All done! ✨ 🍰 ✨
120 files left unchanged.
```

**Comment by trws** [comment]
@vsoch you can probably resolve those conflicts, I imagine it's just formatting.

**Comment by grondo** [comment]
That is due to the conflicts from all the whitespace changes, which will be dropped anyway (if the formatting changes had been in their own commit, you could have just dropped that commit).

**Comment by vsoch** [comment]
I don't know how to resolve conflicts with a rebase?

**Comment by grondo** [comment]
https://docs.github.com/en/get-started/using-git/resolving-merge-conflicts-after-a-git-rebase

**Comment by vsoch** [comment]
oh nevermind I think I just did it, it's just like other cases just slightly more convoluted in how you continue things.

**Comment by vsoch** [comment]
okay loading the dev container - send thoughts and prayers!

**Comment by vsoch** [comment]
Nope not going to work:

```
An unexpected error has occurred: CalledProcessError: command: ('/usr/bin/python3', '-mvirtualenv', '/root/.cache/pre-commit/repoi_zxksgc/py_env-python3.6', '-p', 'python3.6')
return code: 1
expected return code: 0
stdout:
    RuntimeError: failed to find interpreter for Builtin discover of python_spec='python3.6'
    
stderr: (none)
Check the log at **/root/.cache/pre-commit/pre-commit.log**
```

**Comment by vsoch** [comment]
I built the entire devcontainer environment around this base because I thought it was correct for development, but it seems like I can't use it and need to start from scratch with python 3.6 as a base.

**Comment by grondo** [comment]
There shouldn't be a default `fluxrm/testenv` container. You have to choose the tag that matches the distro you want to test against.

```console
grondo@asp:~$ docker pull fluxrm/testenv
Using default tag: latest
Error response from daemon: manifest for fluxrm/testenv:latest not found: manifest unknown: manifest unknown
```

**Comment by vsoch** [comment]
Right I'm using focal - which one should I be using?

**Comment by grondo** [comment]
If you want python 3.6 use a distro with python3.6, try `fluxrm/testenv:bionic`. I'm a bit confused though, the checks should be able to run on all supported distros...

**Comment by grondo** [comment]
and it is fine to have the devcontainer on focal IMO. However, when you are doing development just be aware to not use features that aren't in python 3.6 or the `bionic` and `el7` CI checks would fail.

**Comment by vsoch** [comment]
> and it is fine to have the devcontainer on focal IMO. However, when you are doing development just be aware to not use features that aren't in python 3.6 or the bionic and el7 CI checks would fail.

That kind of defeats the purpose of the devcontainer? :sob:

**Comment by grondo** [comment]
Not sure what to say, sorry. This project is used in production so we have to support the OSes and therefore default Pythons used on those systems.

**Comment by vsoch** [comment]
But there aren't actually any developer docs in the repository for developing flux with Python on any system?

**Comment by vsoch** [comment]
okay got it working, but now with the correct python and black versions there seem to be more file changes?

**Comment by grondo** [comment]
You mean besides the docs in `doc/python` or [here](https://flux-framework.readthedocs.io/projects/flux-core/en/latest/python/index.html)?

**Comment by grondo** [comment]
Oh, many/most of the current changes are in the vendored paths I mentioned above. Do you know how to set a list of ignored paths for the linting/formatting tools like we currently have in `scripts/format`?

**Comment by trws** [comment]
Oh, sure we can add that to the pyproject.toml, I'll push up a recommendation for it in a second.

**Comment by vsoch** [comment]
okay I'm skipping the utils (vendored) folder now, so those files should not be changed.

**Comment by grondo** [comment]
Ok! The only other changes are changes in the docstrings like this (which seem perfectly acceptable to me)
```diff
diff --git a/src/bindings/python/flux/kvs.py b/src/bindings/python/flux/kvs.py
index 0d8246e2e..d383acfa2 100644
--- a/src/bindings/python/flux/kvs.py
+++ b/src/bindings/python/flux/kvs.py
@@ -301,7 +301,7 @@ def inner_walk(kvsdir, curr_dir, topdown=False):
 
 
 def walk(directory, topdown=False, flux_handle=None):
-    """ Walk a directory in the style of os.walk() """
+    """Walk a directory in the style of os.walk()"""
     if not isinstance(directory, KVSDir):
         if flux_handle is None:
             raise ValueError("If directory is a key, flux_handle must be specified")
```

**Comment by grondo** [comment]
Grr, we're getting some of these errors in the CI:
```
503 Egress is over the account limit.
```

Might have to try again later.

I also seem to be hitting https://github.com/OCA/pylint-odoo/issues/296 now:
```
$ ./scripts/pylint 
Traceback (most recent call last):
  File "/home/grondo/.local/bin/pylint", line 11, in <module>
    sys.exit(run_pylint())
  File "/home/grondo/.local/lib/python3.6/site-packages/pylint/__init__.py", line 23, in run_pylint
    PylintRun(sys.argv[1:])
  File "/home/grondo/.local/lib/python3.6/site-packages/pylint/lint.py", line 1731, in __init__
    linter.check(args)
  File "/home/grondo/.local/lib/python3.6/site-packages/pylint/lint.py", line 1004, in check
    self._do_check(files_or_modules)
  File "/home/grondo/.local/lib/python3.6/site-packages/pylint/lint.py", line 1165, in _do_check
    self.check_astroid_module(ast_node, walker, rawcheckers, tokencheckers)
  File "/home/grondo/.local/lib/python3.6/site-packages/pylint/lint.py", line 1252, in check_astroid_module
    walker.walk(ast_node)
  File "/home/grondo/.local/lib/python3.6/site-packages/pylint/utils/ast_walker.py", line 79, in walk
    callback(astroid)
  File "/home/grondo/.local/lib/python3.6/site-packages/pylint/checkers/imports.py", line 541, in leave_module
    std_imports, ext_imports, loc_imports = self._check_imports_order(node)
  File "/home/grondo/.local/lib/python3.6/site-packages/pylint/checkers/imports.py", line 703, in _check_imports_order
    isort_obj = isort.SortImports(
AttributeError: module 'isort' has no attribute 'SortImports'
```

BTW, does `flake8` replace `pylint`, or..? Happy to change what linter I run, but what are the instructions if `pre-commit` is not configured?

**Comment by trws** [comment]
I think that's the intention, though it looks like it's turned off currently?  As it stands, the best experience is probably to run `pre-commit run` with or without `--all`, since that is where the inclusions and exclusions are set up to match what's covered by scripts/format.  Black otherwise has limitations in that area, but that way you get all the checks, and this works *without* installing the actual pre-commit hooks, it just serves as a runner.

If you want to use the linter without it, `flake8` anywhere in the project would be pretty close but wouldn't have the same exclude set.

**Comment by trws** [comment]
Oh, I should clarify a bit also, flake8 actually *runs pylint* as well as several other things, and provides a common interface for what we include and ignore from all of them.  So we shouldn't lose any tests, other than ones that are turned off as part of say putting it in black mode or explicitly by our settings.

**Comment by trws** [comment]
@grondo, this is all green.  I have a small tweak to activate flake8 and add a couple more paths to be checked, would you be up for taking this and that being a subsequent PR?

**Comment by vsoch** [comment]
> BTW, does flake8 replace pylint, or..? Happy to change what linter I run, but what are the instructions if pre-commit is not configured?

I didn't think we are replacing flake8 yet? I have the settings for it but it isn't actually being run by pre-commit yet. I was going to get this PR in, and then add flake8 in another scoped PR.

**Comment by trws** [comment]
I actually threw together turning the flake8 stuff on, I'll throw up the PR against this so you can look at it @vsoch.

**Comment by grondo** [comment]
> @grondo, this is all green. I have a small tweak to activate flake8 and add a couple more paths to be checked, would you be up for taking this and that being a subsequent PR?

Sure! @vsoch mind if I force-push just to fixup commit message?

>  didn't think we are replacing flake8 yet? I have the settings for it but it isn't actually being run by pre-commit yet. I was going to get this PR in, and then add flake8 in another scoped PR.

Sounds fine to me! I guess my question is whether pylint is still being run after this PR? (Not that it matters too much to me). Pylint doesn't work for me anymore locally, but no big deal if the PR dumps it. (Sorry I'm too clueless to figure out what is actually being run)

**Comment by vsoch** [comment]
@grondo go for it - you are far better at git than me!

And I don't think we are currently running pylint - it needs to be added (included with flake8) via the PR that Tom linked (if that's OK with you).

**Comment by grondo** [comment]
> it needs to be added (included with flake8) via the PR that Tom linked (if that's OK with you).

￼Sounds great, thank you!

I'll force a push then manually merge this PR, then update branch protections to remove the outdated checks.

**Comment by grondo** [comment]
I don't have access to push to this branch. @vsoch, can you see if there's checkbox somewhere to "allow edits by maintainers"?

e.g.
Screenshot from 2022-10-14 14-04-55

**Comment by grondo** [comment]
Alternately, all I did was `git commit --amend` and then format the commit message like so:
```commit 474e78ed34a64398c1ccaab39545695d3cf365d0 (HEAD -> python-linting-minimal)
Author: vsoch <vsoch@users.noreply.github.com>
Date:   Sat Oct 1 13:06:34 2022 -0600

    consolidate python linting and formatting
    
    Problem: the developer experience is challenging because linting
    and formatting are hard to debug locally, and then the separation
    in the CI means 3+ clicks to see what is going on!
    
    To fix this, this changeset adds the use of pre-commit, which
    will always run linting/formatting (and with automated fixes for
    a subset of the tools) right before commit, so the developer can
    have some confidence that passing locally == passing in the CI. In
    the case that there is a bug in the CI, we will now just have one
    place to look instead of 3+. This should be a start of a new setup,
    including addition of pre-commit and consolidation of settings into
    a pyproject.toml (and setup.py for flake8) and we can further tweak
    as we establish our linting preferences.
    
    Signed-off-by: vsoch <vsoch@users.noreply.github.com>
```

**Comment by vsoch** [comment]
@grondo I don't see it, so i added you as a collaborator with write to researchapps/flux-core. I think it's likely because researchapps is an org and not a user account (I use it for all my forks / working on stuffs).

**Comment by vsoch** [comment]
@grondo do you want me to try to do that instead?

**Comment by grondo** [comment]
Yeah, I still can't push directly to this branch (hopefully I'm not doing something dumb) so if you can just reformat the commit message then I'll merge.

**Comment by grondo** [comment]
Oh, wait, maybe I am doing something wrong, one moment. Sorry!

**Comment by grondo** [comment]
Still nope:
```
ERROR: Permission to researchapps/flux-core.git denied to grondo.
fatal: Could not read from remote repository.
```
(sorry for the noise)

**Comment by vsoch** [comment]
@grondo did you accept my invitation?

**Comment by grondo** [comment]
Oh, heh. I didn't see one. Looking for it now!

**Comment by grondo** [comment]
Ok, found it and that worked :facepalm: Sorry about that! :disappointed:

**Comment by vsoch** [comment]
No need to apologize, no wrong doing! :tulip:

**Comment by trws** [comment]
@grondo, good with a MWP? Looks like we're all green over here.

**Comment by grondo** [comment]
Yes, I'll press the button since mergify config is modified. Thanks @vsoch and @trws!

**Comment by vsoch** [comment]
yaaaay!!

**Pull request merged**
