### PR TITLE
add fluxorama system instance docker image sources

### PR DESCRIPTION
**Pull request by grondo**
As discussed earlier, this adds a new Dockerfile and associated sources for the "fluxorama" system instance image, built on top of the fluxrm/flux-core:centos8 image. Not sure what else to do with this yet, thus the WIP.
For now, there is an extra rule added for the centos8 travis builder to also build and push a new fluxorama image on each new build, so `docker pull fluxrm/fluxorama` will allow experimentation and testing of the latest flux-core in a system instance setting.

I did verify that `docker exec` can also be used to enter the system instance container:
```
grondo@flux-o-rama:~$ docker exec -ti -u fluxuser 74214bfab18c bash
 [fluxuser@74214bfab18c ~]$ flux mini run id
uid=2001(fluxuser) gid=2001(fluxuser) groups=2001(fluxuser),10(wheel)
 [fluxuser@74214bfab18c ~]$ sudo runuser -u user1 flux mini run id
0.047s: flux-shell[0]: ERROR: Could not change dir to /home/fluxuser: Permission denied. Going to /tmp instead
uid=2201(user1) gid=2201(user1) groups=2201(user1)
```

This may offer a way to run a true multiuser testsuite under CI.

### CODE REVIEW

**Comment by grondo** [comment]
Ok, I've pushed a couple updates to fluxorama docker image to improve security (as suggested by @dongahn).

 * Require a password for `fluxuser` be set in a `FLUXUSER_PASSWORD` environment variable. If an empty password is set, the docker image will exit immediately with an error.
 * Run `ttyd login fluxuser` instead of just `ttyd bash`. This requires that the password be typed before getting a login to the fluxorama container, in case the ttyd port is exposed beyond localhost.


The new suggested way to run the fluxorama container would be something like:
```
$  FLUXUSER_PASSWORD=foo docker run --name=fluxorama -h fluxorama -e FLUXUSER_PASSWORD --tmpfs=/run -ti -v /sys/fs/cgroup:/sys/fs/cgroup:ro -p 8000:7681 grondo/fluxorama
```

The only required option above is `-e FLUXUSER_PASSWORD` which passes the password into the instance.
If `--name` and `-h` options are just a convenience, they set the name of the container to `fluxorama` so you can operate on it by name (`docker kill fluxorama` or `docker exec -ti fluxorama bash`), and also set the hostname to `fluxorama` instead of a checksum.

The container will fail to start without a password:
```
ERROR: No password set for fluxuser
Please set via the FLUXUSER_PASSWORD environment variable
e.g. FLUXUSER_PASSWORD=xxzzy docker run -e FLUXUSER_PASSWORD ..
```

**Comment by grondo** [comment]
I've just refreshed this PR. Still not quite sure if these docker sources belong in their own repo, but for now this seems fine.

In this PR I've also edited the centos8 Dockerfile to remove all the extra layers and reduce the image's size. The `fluxrm/testenv:centos8` image was previously 1.2G, now 880M.

Also fixes some more locale strangeness in the centos8 environment (I was seeing segfaults from bash when the glibc-langpack-en wasn't installed!??)

Finally, a `fluxrm/fluxorama` image would now be automatically deployed whenever a new flux-core:centos8 image is built. (Of course, cannot test until the PR is merged)

**Comment by grondo** [comment]
If we wait until #3115 is merged to install this one, I can "officially" pull the libs3-dev packages into centos8 and centos7 images to avoid a separate PR and conflict with the work here.

**Comment by dongahn** [comment]
If @grondo wants another quick review, I think @cmoussa1 is one candidate as he has built from this image for his work and this PR would generally be helpful for him to continue to improve on his derivative including adding that into flux-accounting. Just my $0.02.

**Comment by grondo** [comment]
Good idea @dongahn. I will push up the latest image to `grondo/fluxorama` and have @cmoussa1 review it.

**Comment by cmoussa1** [comment]
Just checked this out - built with `flux-accounting` and the job-archive and it looks to be working just fine. I'll go ahead and push an updated version of my `fluxorama-with-accounting` image to Docker Hub so it is also updated. Thanks for working on this @grondo!

**Comment by grondo** [comment]
Thanks @cmoussa1!

I've forced a push with a couple other minor changes:

 * Further reduce "layers" in the testenv:centos8 image (size down to 788MB now)
 * add `/usr/bin/less` to the centos8 image (much nicer manpage pager than `more`)
 * remove libs3-devel install in the travis Dockerfile (actually libs3-devel was already installed in both centos7 and centos8)

**Comment by grondo** [comment]
and FYI - I already pushed the updated (smaller) `fluxrm/testenv:centos8` image to Dockerhub.

**Pull request merged**
