### PR TITLE
stop using deprecated libczmq classes

### PR DESCRIPTION
**Pull request by garlick**
This PR moves flux-core off of the deprecated zsocket, zctx, and zauth_v2 libczmq classes, converting to zsock, zsys, and zauth respectively.  As discussed in #974, these classes have been removed as of czmq-4.0.2 so we ought to move forward ASAP.

zsys installs an `atexit()` handler that tries to close any open zsock sockets, and complains about them on stderr while doing it.  Since zmq sockets are not MT-safe I had to change the `exit()` call in the SIGLARM timeout handler to `_exit()` and manually invoke the (file) cleanup function, otherwise there were segfaults.  To avoid chattiness on stderr when we manage to avoid the timeout, I added rc3 files for the sharness "personality" rc1 files, and some `flux module remove` calls for modules that were loaded in sharness tests.

Finally, I tidied up the flux_sec_t class a bit and added a TAP test for it.  In the course of writing that test, I needed an unlink_recursive() function like we had in the cleanup class, so I pulled that out to a new module, exported it, and added a TAP test for that (fixing a bug in the process).

I had some problems earlier with segfaults (only) in travis so may need to run those down, but thought I'd go ahead and get this PR out there for review.

### CODE REVIEW

**Comment by garlick** [comment]
It's strange but a bunch of sharness tests are failing because the new "rc3" scripts cannot be executed.

I verified that they were committed with +x, checking with:
```
$ cd t/rc
$ git ls-tree HEAD
100755 blob 52d75f21b7aa3ae77bd947a91c3fd4e9da2dfc02	rc1-kvs
100755 blob d9949b13f87a477e62580f3304a86eaa090a8089	rc1-testenv
100755 blob ecd2ea7b2e25cd6734f68179ef7270d676230a66	rc1-wreck
100755 blob 49e323741296ec1b138a2990229d7a4886849806	rc3-kvs
100755 blob 7f615156ea784b3a472686e5c4ff8c7b91473fdf	rc3-testenv
100755 blob 65a631cd1d70b218a697c954c54d83778cb02856	rc3-wreck
```
if anybody else has any suggestions I'd appreciate it...

**Comment by grondo** [comment]
The new rc3 scripts are not in `EXTRA_DIST`.

**Comment by garlick** [comment]
Oh duh.  Thank you!

**Comment by garlick** [comment]
That fixed it (thanks again @grondo).  I just squashed down the incremental development and think this is ready for review.

**Comment by grondo** [comment]
I don't know how many times I've hit that problem with missing EXTRA_DIST.

Looks like a lot of work here!

**Comment by garlick** [comment]
This PR includes some changes to the cleanup() code and to the man page test driver that are unrelated to the main topic.  I think I'll go ahead and pull those out as separate PR's and rebase this one once those are merged.

**Comment by grondo** [comment]
I am seeing reproducible failure in security unit test on this branch, running on hype after `make clean && make && make check`

Still looking into it, perhaps something wrong with my environment? Seems like the problem is in some of the `zpoller_wait` calls. If you give me a hint of what to look for I can try debugging this so you don't have to log in to hype.

```
ok 1 - flux_sec_destroy accepts a NULL argument
ok 2 - flux_sec_create with no selected method works
ok 3 - flux_sec_errstr returns 'Success'
ok 4 - flux_sec_get_directory returns configured confdir
ok 5 - flux_sec_type_enabled FLUX_SEC_TYPE_PLAIN false
ok 6 - flux_sec_type_enabled FLUX_SEC_TYPE_CURVE false
ok 7 - flux_sec_type_enabled FLUX_SEC_TYPE_CURVE false
ok 8 - flux_sec_create with NULL confdir works
ok 9 - flux_sec_get_directory returns configured NULL
ok 10 - flux_sec_create PLAIN|CURVE returns EINVAL
ok 11 - flux_sec_create PLAIN works
ok 12 - flux_sec_type_enabled FLUX_SEC_TYPE_PLAIN true
ok 13 - flux_sec_type_enabled FLUX_SEC_TYPE_CURVE false
ok 14 - flux_sec_type_enabled FLUX_SEC_TYPE_CURVE false
ok 15 - flux_sec_create PLAIN|MUNGE works
ok 16 - flux_sec_type_enabled FLUX_SEC_TYPE_PLAIN true
ok 17 - flux_sec_type_enabled FLUX_SEC_TYPE_CURVE false
ok 18 - flux_sec_type_enabled FLUX_SEC_TYPE_CURVE false
ok 19 - flux_sec_create CURVE|MUNGE works
ok 20 - flux_sec_type_enabled FLUX_SEC_TYPE_PLAIN true
ok 21 - flux_sec_type_enabled FLUX_SEC_TYPE_CURVE false
ok 22 - flux_sec_type_enabled FLUX_SEC_TYPE_CURVE false
ok 23 - flux_sec_keygen fails with EINVAL if confdir not set
ok 24 - flux_sec_keygen fails with EACCES if confdir does not exist
ok 25 - flux_sec_keygen (force) fails with EACCES if confdir does not exist
ok 26 - flux_sec_keygen with no security modes works
ok 27 - confdir is a directory with mode 0700
ok 28 - unlinked 1 file/dir
ok 29 - flux_sec_keygen with bad mode confdir fails with EPERM
ok 30 - unlinked 1 file/dir
ok 31 - flux_sec_keygen PLAIN works
ok 32 - unlinked 2 file/dir
ok 33 - flux_sec_keygen CURVE works
ok 34 - unlinked 6 file/dir
ok 35 - flux_sec_keygen CURVE-overwrite fails with EEXIST
ok 36 - unlinked 6 file/dir
ok 37 - flux_sec_keygen (force) CURVE-overwrite works
ok 38 - unlinked 6 file/dir
ok 39 - flux_sec_keygen PLAIN-overwrite fails with EEXIST
ok 40 - unlinked 2 file/dir
ok 41 - flux_sec_keygen (force) PLAIN-overwrite works
ok 42 - unlinked 2 file/dir
ok 43 - flux_sec_create MUNGE-real works
ok 44 - flux_sec_comms_init MUNGE-real works
ok 45 - flux_sec_create MUNGE-fake works
ok 46 - flux_sec_comms_init MUNGE-fake works
ok 47 - flux_sec_csockinit MUNGE-fake works (no-op)
ok 48 - flux_sec_ssockinit MUNGE-fake works (no-op)
ok 49 - flux_sec_munge (fake) works
ok 50 - flux_sec_unmunge (fake) works
ok 51 - unmunge(munge(x))==x
Saving /var/tmp/grondo/sectest.GbvPcl/passwd
I: 17-03-28 16:12:38 zauth: API command=PLAIN
ok 52 - flux_sec_comms_init PLAIN works
ok 53 - flux_sec_ssockinit works
ok 54 - server bound to localhost on port 49152
ok 55 - flux_sec_csockinit works
ok 56 - client connected to server
ok 57 - client sent Hi
I: 17-03-28 16:12:38 zauth: ZAP request mechanism=PLAIN ipaddress=127.0.0.1
I: 17-03-28 16:12:38 zauth: - allowed (PLAIN) username=client password=77AFD409528A3835315F260EF3B2F80D
I: 17-03-28 16:12:38 zauth: - ZAP reply status_code=200 status_text=OK
ok 58 - server ready within 100ms timeout
ok 59 - server received Hi
ok 60 - rogue connected to server with no security
ok 61 - rogue sent Blimey!
ok 62 - server not ready within 100ms timeout
ok 63 - rogue connected to server using wrong password
ok 64 - rogue sent Skallywag!
I: 17-03-28 16:12:38 zauth: ZAP request mechanism=PLAIN ipaddress=127.0.0.1
I: 17-03-28 16:12:38 zauth: - denied (PLAIN) username=client password=not-the-correct-password
I: 17-03-28 16:12:38 zauth: - ZAP reply status_code=400 status_text=No access
ok 65 - server not ready within 100ms timeout
I: 17-03-28 16:12:38 zauth: API command=$TERM
Saving /var/tmp/grondo/sectest.IOXEE5/curve/client
Saving /var/tmp/grondo/sectest.IOXEE5/curve/client_private
Saving /var/tmp/grondo/sectest.IOXEE5/curve/server
Saving /var/tmp/grondo/sectest.IOXEE5/curve/server_private
I: 17-03-28 16:12:38 zauth: API command=CURVE
ok 66 - flux_sec_comms_init CURVE works
ok 67 - flux_sec_ssockinit works
ok 68 - server bound to localhost on port 49152
ok 69 - flux_sec_csockinit works
ok 70 - client connected to server
ok 71 - client sent Greetings!
not ok 72 - server ready within 100ms timeout
#   Failed test 'server ready within 100ms timeout'
#   at test/security.c line 414.
not ok 73 - server received Greetings!
#   Failed test 'server received Greetings!'
#   at test/security.c line 418.
ok 74 - rogue connected to server with no security
ok 75 - rogue sent Avast
I: 17-03-28 16:12:38 zauth: ZAP request mechanism=CURVE ipaddress=127.0.0.1
I: 17-03-28 16:12:38 zauth: - allowed (CURVE) client_key=8.v#+IEqsrf9A>*ciKVOYngk]Be[<FJFT}$Ywsz#
I: 17-03-28 16:12:38 zauth: - ZAP reply status_code=200 status_text=OK
not ok 76 - server not ready within 100ms timeout
#   Failed test 'server not ready within 100ms timeout'
#   at test/security.c line 430.
ok 77 - rogue connected to server using right server, wrong client key
ok 78 - rogue sent Haar!
not ok 79 - server not ready within 100ms timeout
#   Failed test 'server not ready within 100ms timeout'
#   at test/security.c line 457.
I: 17-03-28 16:12:38 zauth: API command=$TERM
1..79
# Looks like you failed 4 tests of 79 run.
FAIL: test_security.t

```

**Comment by garlick** [comment]
I suspect what's happening is for some reason the 100ms timeout is too small, and then a cascading failure when messages that were supposed to be consumed in a previous test are there confusing the next test.  I guess the timeouts really only come into play when a test is going to fail so it doesn't hurt to make them bigger like say 1000ms.  Maybe try that?  Meanwhile I'll have a look at how to avoid the cascading failures...  Thanks!

**Comment by grondo** [comment]
Yes, If I increase the timeout on the zpoller_wait() after client sends Greetings, all tests pass.

**Comment by garlick** [comment]
I misspoke a bit though, some of the tests actually do wait out the timeout (when they expect not to get a response), so increasing all the timeouts does slow down the test.  Let me ponder if there's a better way.  Thanks for trying that out!

**Comment by grondo** [comment]
last commit fixes the issues I was seeing on hype, thanks!

**Comment by garlick** [comment]
OK, I squashed that one down.  Thanks!

**Pull request merged**
