### PR TITLE
revise reactor API, refactor reactor internals

### PR DESCRIPTION
**Pull request by garlick**
This PR works over the Flux reactor.  I think this is not quite done but wanted to get any feedback started while I continued to work on it.

The most recent reactor API interfaces discussed in PR #168 are implemented, leaving the old interfaces available in "libcompat", which is linked into libflux-internal.  After the api is stablized we can convert everything and get rid of libcompat.  Here is a summary of the API changes, followed by a description of some cleanup of the internals.

**general reactor stuff**
Our own POLL bits instead of co-opting zeromq's.   Note that only message handlers are optionally started as co-processes.  This should probably be fixed but I'm not sure I want to do it here as it will be a fairly painful change and this PR is already pretty big.
```C
enum {
    FLUX_POLLIN = 1,
    FLUX_POLLOUT = 2,
    FLUX_POLLERR = 4,
};

int flux_reactor_start (flux_t h);
void flux_reactor_stop (flux_t h);
void flux_reactor_stop_error (flux_t h);

int flux_sleep_on (flux_t h, struct flux_match match);
```

**message watchers**
These look like reactor callbacks but they really are message dispatch callbacks.  Do we need to expose a way for an application using an external reactor to instantiate a dispatcher and drive it with messages?
```C
typedef struct flux_msg_watcher flux_msg_watcher_t;
typedef void (*flux_msg_watcher_f)(flux_t h, flux_msg_watcher_t *w,
                                   const flux_msg_t *msg, void *arg);

int flux_msg_watcher_add (flux_t h, struct flux_match match,
                          flux_msg_watcher_f cb, void *arg,
                          flux_msg_watcher_t **wp);
void flux_msg_watcher_cancel (flux_msg_watcher_t *w);

struct flux_msghandler {
    int typemask;
    char *topic_glob;
    flux_msg_watcher_f cb;
};
#define FLUX_MSGHANDLER_TABLE_END { 0, NULL, NULL }
int flux_msg_watcher_addvec (flux_t h, struct flux_msghandler htab[], void *arg);
```

**file descriptor watchers**
```C
typedef struct flux_fd_watcher flux_fd_watcher_t;
typedef void (*flux_fd_watcher_f)(flux_t h, flux_fd_watcher_t *w,
                                  int fd, int revents, void *arg);
int flux_fd_watcher_add (flux_t h, int fd, int events,
                         flux_fd_watcher_f cb, void *arg,
                         flux_fd_watcher_t **wp);
void flux_fd_watcher_cancel (flux_fd_watcher_t *w);
```

**zeromq socket watchers**
I guess zeromq is not entirely hidden in our API if we're exporting this, although it doesn't require any zeromq/czmq headers.
```C
typedef struct flux_zmq_watcher flux_zmq_watcher_t;
typedef void (*flux_zmq_watcher_f)(flux_t h, flux_zmq_watcher_t *w,
                                   void *zsock, int revents, void *arg);
int flux_zmq_watcher_add (flux_t h, void *zsock, int events,
                          flux_zmq_watcher_f cb, void *arg,
                          flux_zmq_watcher_t **wp);
void flux_zmq_watcher_cancel (flux_zmq_watcher_t *w);
```

**timer watchers**
A one shot timer is indicated by setting `repeat` to zero.  There is no way to enable/disable a timer without destroying it and that feels a bit awkward.
```C
typedef struct flux_timer_watcher flux_timer_watcher_t;
typedef void (*flux_timer_watcher_f)(flux_t h, flux_timer_watcher_t *w,
                                     int revents, void *arg);
int flux_timer_watcher_add (flux_t h, double after, double repeat,
                            flux_timer_watcher_f cb, void *arg,
                            flux_timer_watcher_t **wp);
void flux_timer_watcher_cancel (flux_timer_watcher_t *w);
```

 The reactor was re-factored as discussed in issue #124.  Instead of duplicating a libev loop and re-queue queue in each connector and exposing a large number of connector methods, an edge-triggered pollfd/pollevents interface is exported by each connector and there is only one re-queue queue in the handle with its own pollfd/pollevents interface.   The handle wraps the connector and the re-queue queue using epoll(2) and exposes the result as `flux_pollfd()` and `flux_pollevents()`. These functions are used by the internal libev reactor (using a "composite watcher" `src/libflux/ev_flux.[ch]`) and could be used to integrate a flux handle into an external reactor. In fact the internal reactor uses only this interface and no longer directly calls any connector methods which is a sort of "sufficiency proof" at least for libev.

The specialized handle implementation used by comms modules running in the same address space as the broker was converted to a regular connector called `shmem.so`.  `flux_open()` was not a sufficient interface to pass in the `zctx_t` needed to open the other end of the socket, so a new mode was added, where `flux_open()` is called with the `FLUX_O_NOCONNECT` flag, and a separate `flux_connect()` call connects the socket, after setters are called on the handle.  Rather than implement new setters, the generic `flux_aux_set()` / `flux_aux_get()` functions were used.  Keys used internally by libflux are prefixed with `flux::` to avoid collisions with user keys.  This mode may also prove useful for sharing security contexts with a connector in the future.

### CODE REVIEW

**Comment by grondo** [comment]
This looks good to me!

I'm a bit wary about the `flux_open (FLUX_O_NOCONNECT)` approach because it seems like it could be confusing that some connectors *must* delay connect on `open` and some *can't* --  and there might not really be a way to tell without cracking open code. That being said, I don't particularly have any better ideas than what you have here. (I might have followed the `socket` style and have `open()` create a connector context, then `getsockopt/setsockopt` style calls to modify the context, then all connectors have a `connect()` method. However, that seems wsay too heavy-handed here)

I think your proposal to export a message dispatch function that could be called from apps is a great idea. How do you think that will look?

**Comment by garlick** [comment]
I don't know why I didn't think of this yesterday, but if a connector can't connect without info provided by a setter, it could simply wait and perform the connect once it receives all the info.  The handle would be useless until that occurs (as it is now between `flux_open()` and `flux_connect()`.  This would require a different strategy than `flux_aux_set()` since those have no notification, i.e. connector methods for get/set.

**Comment by garlick** [comment]
It seems like reactor and dispatcher might need to be broken out from the handle as their own objects?  A `flux_t` handle is just like a file descriptor or any other event source now, so you'd register a watcher for the handle, and in the watcher callback, "send" messages to the dispatcher, where you have registered your message handler callbacks.   I don't know if it's useful, but in that scheme you could register multiple handles with the reactor, and replace either reactor or dispatcher.

I guess we would need to rethink how coprocesses are managed.  That's the one that really hurts my brain.

**Comment by garlick** [comment]
Just rebased with the following changes:
* added `flux_opt_set()`, `flux_opt_get()` with prototypes like getsockopt/setsockopt as discussed
* drop `FLUX_O_NOCONNECT` and `flux_connect()`, instead simply having shmem connector connect after zctx is set with `flux_opt_set()`.

I wonder if we should similarly fold `flux_pollfd()` and `flux_pollevents()` into `flux_opt_get()` as zeromq did since these will not be heavily used?

**Comment by garlick** [comment]
I chose to mimic the prototype for getsockopt with its awkward value-result length parameter and I'm having second thoughts about this now.  Maybe the length should not be a pointer and then if the size doesn't match it's an EINVAL.  This requires less code to call but is the "almost" match to getsockopt going to be confusing?
```
/* Get/set handle options.  Options are interpreted by connectors.
 * flux_opt_get()'s 'len' is a value-result parameter: size of 'val' buffer
 * on input, size of object copied on output.
 * Returns 0 on success, or -1 on failure with errno set (e.g. EINVAL).
 */
int flux_opt_set (flux_t h, int option, const void *val, size_t len);
int flux_opt_get (flux_t h, int option, void *val, size_t *len); // change last arg to size_t len
```
@grondo getting back to your comment about requiring code spelunking to determine special connector requirements such as shmem's need for the zctx, I think in general we could document each flux-core connector in a `flux_open(3)` man page section, and include such requirements as well as connector-specific URI path parsing rules.  In this particular case, the connector is fairly specialized for use within the broker so it's not a big deal IMHO.

**Comment by garlick** [comment]
Just forced a push with the following changes
* rebased on master  673692604ca6528e61c2c168039550f7b088e881
* changed `flux_opt_get()` prototype so size is no longer a value-result pointer
* better commit docs e.g. the reason for matchtag recycling problem in 2ba8082 is explained
* cleanup, squashed some commits

**Comment by garlick** [comment]
I'm wondering if the reactor interfaces need to change so that memory management is the callers responsibility, e.g instead of
```
typedef struct flux_timer_watcher flux_timer_watcher_t;
typedef void (*flux_timer_watcher_f)(flux_t h, flux_timer_watcher_t *w,
                                     int revents, void *arg);
int flux_timer_watcher_add (flux_t h, double after, double repeat,
                            flux_timer_watcher_f cb, void *arg,
                            flux_timer_watcher_t **wp);
void flux_timer_watcher_cancel (flux_timer_watcher_t *w);
```
where the reactor tracks all watchers that have been added and destroys them either with cancel or when the handle is closed, something like this:
```
flux_timer_watcher_t *flux_timer_watcher_create (double after, double repeat,
                                                 flux_timer_watcher_f cb, void *arg)
void flux_timer_watcher_destroy (flux_timer_watcher_t *w);
int flux_timer_watcher_start (flux_t h, flux_timer_watcher_t *w);
void flux_timer_watcher_stop (flux_t h, flux_timer_watcher_t *w);
```
This would allow a timer (for example) to be started and stopped with low overhead, and it is very clear who owns the watcher and should destroy it.

The `flux_msg_watcher_addvec()`  interface would need to be rethought...

**Comment by grondo** [comment]
I'm not ignoring your recent comments, but do not have much of value to add.

I do like the most recent versions of `flux_opt_get()`/`flux_opt_set()`. The only thing I wonder about this interface is where the definition of `item` will be made. Currently they're defined in an enum in `libflux/handle.h`. Does this mean if we have a new connector that requires its own items they will have to be added to the enum in `handle.h`? If so, should `opt_set/get` be a handle method and not a handle implementation method?

**Comment by grondo** [comment]
Also @garlick -- I see your point about `watcher_add` pattern vs `watcher_create` and `watcher_start`. 

I don't have any good advice here, except that I also prefer the second pattern (create and start), even though it is more verbose. However, your point that it doesn't fit the message dispatcher paradigm is germane. It feels like maybe if we could tease apart the message dispatcher vs message watcher,  this mismatch could be partially solved? (Sorry I don't have any better thoughts at this time)

**Comment by garlick** [comment]
Would it help if option names were strings that needn't be defined in handle.h?  So instead of getting `FLUX_OPT_ZMQ_CONTEXT`,  get "zmq_context"?  Since connectors could be built out of tree and require any arbitrary option, it does make sense to decouple this from the main flux-core package.   Option names could be documented in a man page for the connector or flux_open() for the packaged ones.

**Comment by garlick** [comment]
On the watcher patterns, I'm trying out the create/start/stop/destroy one now and I like it too.  Let's go with that.  If nothing else it follows the libev way, so internal code is concise and libev users will feel at home.

For the message watchers we could for the time being switch to that same pattern but keep `flux_msg_watcher_addvec()` as a create/start shorthand, store the watcher pointer in the `struct  flux_msghandler` and add a `_delvec()` that is a shorthand for stop/destroy.  I'm for teasing apart dispatcher and reactor but I'm not sure yet how to do that so it might be best to make that a project for another day.

**Comment by grondo** [comment]
That is probably better than the impossible task of registering all options in flux-core `handle.h`.

If the options are string names, I wonder if it would be useful for connector plugins to export the list of "options" they support, require, etc.? Then the .so is somewhat self documenting. (Not that the options should not also be in a man page)

**Comment by garlick** [comment]
Given that connectors are used programatically I'm not sure if a "modinfo" like command is all that useful.  I guess that could be added later if needed.

Ideally `flux_opt_set()`  will only be needed in exceptional cases.  I.e. a command (say) would select connection method via a URI option, and that URI would be self-contained.  It will be a bummer if special case option setting code has to accumulate in multiple commands.  If that starts to happen we will want to rethink the interface, but since anything textual can probably be tacked onto a URI as part of the path or as a &key=val option, I don't think it will.

**Comment by grondo** [comment]
Oops, sorry! I didn't mean a `modinfo` style command, but a way to programmatically check if an `open`'d connector needs or supports other options before proceeding. Otherwise, it seems like you have to know which connector you are opening and can't actually make generic `flux_open()` calls. However, if `flux_opt_set` is really only for internal use only then clearly I'm way over thinking this!

Sorry for derailing the PR.

**Comment by garlick** [comment]
I've made the proposed reactor api changes and will squash those down once we've got something we're happy with.

Regarding opt_get/set:  I think I might be having a hard time thinking outside of the one use case we have now for it.  Originally I thought supporting krb5 auth might require some option setting, but looking into that a bit, it seems that the few things such a connector might need (service principal, client principal, etc) can be represented in the URI.

Here is how the current use case for opt_get/set works:
* within a new comms module thread, broker creates handle with `flux_open ("shmem://uuid")`, sets zctx with `flux_opt_set`, then calls module main().
* a comms module may access zctx with `flux_opt_get()`.  wreck/wrexec does this so it can create new zeromq sockets utilizing the broker's I/O thread
* a get/set on an option name unsupported by the loaded connector returns  EINVAL

For zctx case, the module could create its own zctx if the connector returns EINVAL when it asks for one.  This is what wrexec should do in order to support running with a connector other than shmem, such as whatever we come up with for modules loaded as processes.  It wouldn't be particularly helpful for wrexec to get a list of supported options here.  Nor would it be all that useful for the broker end - to make it connector-agnostic, it could just set the zctx and ignore any EINVAL.

I'd vote for keeping this simple for now and just documenting this option in the flux_open man page.

**Comment by grondo** [comment]
Sorry, my fault. I think I didn't understand that `flux_opt_set` wasn't for generic use. It seems fine as is.

**Comment by garlick** [comment]
No worries, I'm open to doing what you suggest if we come up with a use case, just not feeling it yet.

@grondo if you are getting close to happy with this let me know and I'll squash/rebase, and force update of a candidate for merging.  Actually, maybe your #231 should go in before I rebase?

I'll continue to ponder the reactor/dispatcher decoupling as I think that's the right move if we can figure out how to make a clean separation and support coprocs properly.  I think that's a new PR though.

**Comment by grondo** [comment]
It looks pretty good to me!

I think the subprocess io PR can go in after this one.

**Comment by garlick** [comment]
Just forced a rebase with the following changes:
* rebased on current master ad6be8
* added loop tests for handle and reactor
* squashed down some commits
* temporarily disabled some JSC tests (issue #234)

**Comment by grondo** [comment]
This seems ready to merge IMO.

This can go in, then I'll rebase the subprocess-io stuff and we can merge that in (once I get some fixes in)

Does this sound OK?

**Comment by garlick** [comment]
OK, sounds good.

**Pull request merged**
