### PR TITLE
kvs: general refactoring and cleanup

### PR DESCRIPTION
**Pull request by chu11**
This PR has a few tiny corner case fixes, some general refactoring/abstraction fixes in the internal commit API, and some code re-organization in the core KVS file.

### CODE REVIEW

**Comment by chu11** [comment]
hit #1150, restarting a  builder

**Comment by chu11** [comment]
code coverage diff is not too good.  I re-organized so much code that effectively many of the uncoverable error paths that were not-covered before and not-covered again.

The diff coverage did make me notice one other thing that could be cleaned up.  The ```now``` variable is no longer used in ```content_store_request_send()```, so we could axe that.

**Comment by garlick** [comment]
If there's just the one "ready" flag, maybe a mask of flags should be replaced with `set_ready()`, `get_ready()`?  Or were you anticipating more flags here?

**Comment by garlick** [comment]
LGTM otherwise.

**Comment by chu11** [comment]
> If there's just the one "ready" flag, maybe a mask of flags should be replaced with set_ready(), get_ready()? Or were you anticipating more flags here?

Do you mean a ```fence_get_ready()``` and/or ```fence_set_ready()```?  I decided not to do that, since the fence doesn't really have any concept of itself being "ready" or not.  It's an abstracted concept that is only really known to the commit manager.  Thus decided to do the fence with an "aux integer" instead.

**Comment by garlick** [comment]
OK, well not a big deal to be sure.

LMK when you're done poking at it and I'll have one more spin through before merging.

**Comment by chu11** [comment]
I think I'm done with this PR.

**Comment by garlick** [comment]
OK, great!  Thanks.

**Pull request merged**
