### PR TITLE
ci: move from Travis-CI to GitHub Workflows

### PR DESCRIPTION
**Pull request by grondo**
This PR divorces the flux-core build from Travis-CI and completes all checks using GitHub workflows.

Largely the same set of checks as were done under Travis are included here, with some additional improvements:

 - The "build matrix" is generated by a new script `src/test/generate-matrix.py`. This is done to keep the `.github/workflows/main.yml` a bit cleaner, for extra sanity, and also as a way to potentially disable or modify builds based on PR/push content in the future (e.g. don't run all checks if only doc changes have been made).

 - The ASan build is split into its own "workflow" as `.github/workflows/asan.yml`. This is done because GitHub Workflows only allow you to restart the whole workflow, not individual jobs, and we seem to need to restart the asan builds more often currently.

 - To the point above, a new `--recheck` option is introduced to `docker-run-checks.sh` which will run `make recheck` once if `make check` fails, and this option is added to the asan builder. This should mitigate the issues with "racy" tests or flux-start kill timer giving false test failures in this builder (failing tests will be re-run once) (Still need to test that this one works)

 - The code to push new docker images was moved to a script to keep it out of the YAML.

 - To reduce or eliminate the need to search through the github actions web log interface on test failues, a new "after failure" script `src/test/checks-annotate.sh` is used to attempt to summarize failed tests. Action "annotations" are generated for TAP test failures (`not ok`), TAP and ASan errors and tests that appear to have been missed (e.g. after a timeout). If a test fails, scroll down in the log the `after failure` job, and the failures will hopefully be nicely summarized (the "Error" and "Warning" messages also appear in the annotations list on the main page for the actions):
  Screenshot from 2020-11-30 09-16-32

 - Along the way, I disabled some unreliable tests under ASAN, and fixed the t0000-sharness.t issues from #3368 

I still need to do a bit more testing, and I won't know for certain if the docker deployment and github releases jobs will work until after this PR is merged unfortunately...

### CODE REVIEW

**Comment by garlick** [comment]
Wow the browse-ability of the results is _dramatically_ improved.   This should be really, really awesome.  Thanks!

**Comment by grondo** [comment]
Apparently the `make recheck` support isn't quite working, and codecov.io uploads aren't working (even though you are not supposed to need a token from within a github action, codecov is asking for one). So a little more to do here...

**Comment by grondo** [comment]
Oh, and at some point we'll have to remove Travis from the required checks (just before merging this one) under branch protections.

**Comment by grondo** [comment]
Ok, I think I figured out the codecov problem. If `DOCKER_REPO` is set in the environment, then the codecov bash uploader will try to upload results as if running in a DockerHub build.

To w/a, `DOCKER_REPO` is now unset when running the codecov action.

Also, it turns out that `make recheck` is not one of the recursive automake rules by default, so `make check || make recheck` doesn't actually work from the top-level build directory.

Therefore, the `docker-run-checks.sh --recheck` option will only recheck in `./t` (which is likely where a spurious test failure would occur anyway)

**Review by garlick — APPROVED** [review]
Well, FWIW I skimmed through this PR and didn't find anything to complain about!  I really appreciate the detailed commit messages.

I'll mark approved, with the caveat that my understanding of these tools is a bit thin.  Regardless, IMHO it might be good to just get this in and see how it goes!

**Comment by grondo** [comment]
Ok, looks like code coverage is working now.

The unknowns now is whether or not docker deployment and github releases auto-uploader will work.

However, I'm not sure exactly how to test that reliably outside of just merging this PR and seeing how it goes.

BTW, this PR will have to be manually merged. Before doing that I'll update branch protections to remove the Travis-CI requirement. If we think this is ready I can do that now.

**Comment by grondo** [comment]
Ok, I removed WIP and update branch protections if someone wants to merge (assuming they approve)

**Comment by garlick** [comment]
full speed ahead!

**Comment by grondo** [comment]
Sorry, this will need to be manually merged due to modifications to mergify config and GH actions.

**Comment by garlick** [comment]
Right!  Buttons away!

**Comment by grondo** [comment]
Thanks!

**Pull request merged**
