### PR TITLE
Content service

### PR DESCRIPTION
**Pull request by garlick**
This PR is for a "content" service, split from PR #471.  It includes a broker-resident "content-cache" service which is a rewrite of the KVS distributed object cache, built for opaque content, optional persistence, and operation outside the KVS.

The cache provides the same semantics and scalability properties as the KVS object cache.  That is, a store on any rank returns only when the content can be loaded from any other rank.  Stores of identical content are "squashed".  Loads of identical content benefit from caching at each tree level.  (Somewhat embarassingly, I'm still using zhash here, despite the many other good ideas discussed in #474.  That will be changed once we have one of the other options available on all the platforms we actively use.)

Two modules that can act as backing store for the cache are added: `content-sqlite` and `content-sophia`.  By default, neither of these is loaded and the rank 0 cache must retain all entries.  The idea was that for short-lived instances (as in test), no persistence is needed, but for long running instances, it will be loaded by the initial program.  Note that both `content-sophia` and `content-sqlite` provide the "content" service, which is different from the "content-cache" service built into the broker.  The original mechanism from #471 for allowing two modules to provide the same service, but only allow one to be loaded at a time, is sufficient for this architecture.  Synchronization was added so that these modules can be loaded and unloaded without data loss (data is put back into the rank 0 cache at unload).

Unlike the KVS object cache, this service is exposed for general use.  It has command line utilities, `flux load` and `flux store` which can be used to load and store objects on stdout/stdin of the command.  I decided against adding C API functions for this, as they would merely be a thin wrapper on top of the raw RPC calls added in #487.  Instead I think we should document the (simple!) protocol in an RFC though I have not started that yet.

Also in this PR is some cleanup that allows built-in broker services to make RPC calls and continuations, and to register regular message handlers to receive requests and events.  In addition to implementing content-cache this way, I converted the heartbeat and shutdown classes, which are used by content-cache, to work this way, and completely eliminated the hardwired event distribution to services in the broker.  There is still lots of cleanup possible here though.

The content service is not yet wired into the KVS.  That will come in another PR.

This PR includes sharness tests and a `flux-cache(1)` man page.

### CODE REVIEW

**Comment by grondo** [comment]
This is impressive! 

It will take a little while to grok the entire thing, but my very first impression (which may be very misinformed) is that use of simple command names like `load` and `store` for low-level plumbing commands might be avoided if possible? I could be off base, but thought I'd bring it up. (I don't really have any idea what more user friendly `flux store` commands might be, but `flux load` especially raised a red flag for me at first, without doing further research -- `load` does the obvious when you are thinking in terms of content, but in the larger scheme of Flux as a whole, `load` could mean a lot of things)

My only idea at this point, though, would be to prefix these commands with `content-` to be explicit. If you mean these to be real user facing commands (porcelain in the `git` parlance) then probably just ignore my wordy suggestion above.

Also, since we're still early with this stuff, I would be perfectly fine with merging this PR with commands as is, and later renaming commands if needed. You have already put in so much work.

**Comment by garlick** [comment]
Would it be acceptable if instead of
```
flux load
flux store
flux cache
```
we just had
```
flux cache [--load] [--store]
```
Or maybe that plus rename "cache" to "content"?

I think this is more plumbing that porcelain.

**Comment by grondo** [comment]
I am not sure -- I was merely pointing out an early red flag for me, but I want to stress this was only my one opinion.

I do like lumping clearly related commands into a single command with subcommands, but my preference is not to use command line options for the subcommands. e.g. could it be:
```
flux content load
flux content store
```
That's just my preference (a model perhaps being `git remote`), and I guess I don't actually feel strongly enough to argue too vehemently in favor of this approach. (e.g. `flux content-load` `flux content-store` would be perfectly fine for me as well)

**Comment by garlick** [comment]
I went with
```
flux content-store
flux content-load
flux content-flush
flux content-dropcache
```
That seems like an improvement.

**Comment by garlick** [comment]
I will plan to submit a draft content service RFC today to provide some context for further review of this PR.

**Comment by grondo** [comment]
Great! This is looking spectacular to me so far though. I'll try to do do some real world testing today just to be thorough.

**Comment by garlick** [comment]
Just rebased, squashed the review commits, and filled out some of the commit comments.

Bummer, it seems the gcc+install travis test is failing with a timeout on one of the PMI tests.  I'll look into that.

**Comment by grondo** [comment]
This is similar to the other transient test failures in the install targeted tests I've seen. Looks like the failures are turning out to be pretty common though. Let me see if I can reproduce outside of travis. Sorry!

For now, you could just try restarting the `gcc+install` build.

**Comment by garlick** [comment]
In writing up an RFC I had a couple of realizations:
* EPROTO on storing zero length content is an arbitrary restriction that should be eliminated
* the reference to stored content should include the hash name like camlistore blobrefs, e.g. `sha1-DA39A3EE5E6B4B0D3255BFEF95601890AFD80709`.  This would allow content to be shared among instances that have configured different hash algorithms.  This means reworking some of the code so that content references can have an arbitrary length.

Incidentally one interesting idea for sharing content among instances is rather than returning ENOENT if the "most authoritative" store of content within an instance cannot satisfy a load request, to ask the enclosing instance for the content.  This combined with a way to link content to the KVS namespace could be an interesting way to initialize the KVS from inherited content.  (And since the data has a home in the parent it doesn't have to be held onto when no longer needed in the child, e.g. it is non-dirty cache from the time it is loaded)

**Comment by garlick** [comment]
Just pushed an update with 
* commands consolidated under one subcommand per discussion in our project meeting
* handle storing an object of size 0 (with tests)
* commands now prefix content references with hash name, e.g. 
```
./flux content store </dev/null
sha1-DA39A3EE5E6B4B0D3255BFEF95601890AFD80709
```
The protocol is still hardwired for raw SHA1 digests.  Fix coming along with RFC.

**Comment by garlick** [comment]
Just pushed some commits to
* rename services: broker-resident cache service is "content", backing stores are "content-backing"
* update protocol to match draft RFC 10, namely use "blobrefs" instead of raw SHA1 hash digests
* expose selected hash algorithm as broker attr (content-hash) and read it in "content-backing" modules and flux command driver to ensure all components use the same algorithm (only SHA1 supported at present)
* key the zhash in the content cache with blobrefs.  This makes "foreign blobrefs" easier to cache

**Comment by garlick** [comment]
I've squashed down the incremental work in this PR.

Still needed, in order to be fully synced with RFC 10, is the ability to fault in blobs from the enclosing instance.

**Comment by garlick** [comment]
Actually, maybe I could propose merging this before the enclosing instance bit is implemented, since we can proceed with the KVS work on top of this without that.

**Comment by grondo** [comment]
That works for me.

I'll take a look at this briefly today but I don't think we need a full review before merge, so I plan to push the button soon.

**Comment by grondo** [comment]
Making some comments as I go along. They are all very minor and perhaps shouldn't prevent merge of this great work.

* One early note (which shouldn't have to be resolved in this PR), is that it would be nice/interesting to have some sort of query interface for the content store. Even if it is something simple (like number of objects, number of references? or straight list of objects) I think it would be useful (If nothing else as a metric that the the thing is being used and is working in an instance. I'd be willing to admit I'm probably wrong on this one too)

* `flux-content(1)` man page references SHA1 explicitly. Should that be updated to be more generic (or maybe not yet?)

* Would it be at all useful to have a `flux-content` subcommand that listed if there exists a backend "content" service and its name? (I'm really not sure, just asking)

* Another comment: this error is a bit unsatisfying
```
$ flux module load content-sophia
flux-module: content-sophia: File exists
```

Though I'm not even sure how to provide a more useful message  here.

* Finally, it would be nice if `flux content COMMAND --help` printed individual usage for subcommands. The easiest way to do that now is to use a new `optparse_t` for each subcommand (builtin `optparse_t` is used for parsing arg of parent subcommand `flux-content`...) E.g. something like:

```diff
diff --git a/src/cmd/flux.c b/src/cmd/flux.c
index c2cc32c..c96b89c 100644
--- a/src/cmd/flux.c
+++ b/src/cmd/flux.c
@@ -572,13 +572,14 @@ void internal_lsattr (flux_conf_t cf, optparse_t *p, int a
     }
 }
 
-void internal_content_load (flux_conf_t cf, optparse_t *p, int ac, char *av[])
+void internal_content_load (flux_conf_t cf, optparse_t *orig, int ac, char *av[
 {
     struct optparse_option opts[] = {
         { .name = "bypass-cache",  .key = 'b',  .has_arg = 0,
-          .usage = "load directly from rank 0 content service", },
+          .usage = "Load directly from rank 0 content service", },
         OPTPARSE_TABLE_END,
     };
+    optparse_t *p;
     int n;
     const char *blobref;
     uint8_t *data;
@@ -587,6 +588,9 @@ void internal_content_load (flux_conf_t cf, optparse_t *p, i
     flux_rpc_t *rpc;
     const char *topic;
 
+    p = optparse_create ("flux-content load");
+    optparse_set (p, OPTPARSE_USAGE, "[OPTIONS] BLOBREF");
+    optparse_add_doc (p, "Retrieve content for digest BLOBREF", -1);
     if (optparse_add_option_table (p, opts) != OPTPARSE_SUCCESS)
         msg_exit ("optparse_add_option_table");
     if ((n = optparse_parse_args (p, ac, av)) < 0)
@@ -606,6 +610,7 @@ void internal_content_load (flux_conf_t cf, optparse_t *p, i
         err_exit ("store");
     if (write_all (STDOUT_FILENO, data, size) < 0)
         err_exit ("load: write_all");
+    optparse_destroy (p);
     flux_rpc_destroy (rpc);
     flux_close (h);
 }
```

```
$ flux content load --help
Usage: flux-content load [OPTIONS] BLOBREF
Retrieve content for digest BLOBREF
  -b, --bypass-cache     Load directly from rank 0 content service
  -h, --help             Display this message.
```

This is where we could use some higher level structure that allowed a nested command with subcommands and options to be specified directly in an optparse or other structure. (@trws talked about needing this in our last meeting)

**Comment by garlick** [comment]
Excellent suggestions!

Maybe there should be a broker attribute for the selected backing store?  There is one for the selected hash.  I have to think about that a little bit.

Side note: there is a 'stats.get' method that can be parsed by `flux comms-stats` (see examples in sharness test for content-cache).  This gets you an object count and a few other accounting numbers.

**Comment by grondo** [comment]
Oops, I was hoping to catch you before you implemented the work on `flux content COMMAND`.

I just had an idea of a better way to do it (by allowing recursive call of `handle_builtin`), but perhaps I'll save that and just do another PR after the fact.
Sorry!

**Comment by grondo** [comment]
I notice the latest build here failed with yet another transient error. I wonder if we're really seeing hangs, or if perhaps `run_timeout` needs a multiplier when running under Travis environment.

**Comment by garlick** [comment]
I think I've addressed the review comments in the above commits:
* man page formatting
* `flux content` subcommand help (if we're okay with deferring the generalized subcommand change)
* added attribute showing backing store
* fixed error message from `flux-module load`
* exposed some basic cache accounting info as broker attrs

Also while I was adding attrs, I made the purge parameters tunable and documented them.

**Comment by garlick** [comment]
By the way here are all the attributes for the content cache:
```
content-acct-dirty                      0
content-acct-entries                    0
content-acct-size                       0
content-acct-valid                      0
content-backing                         -
content-hash                            sha1
content-purge-large-entry               256
content-purge-old-entry                 5
content-purge-target-entries            1048576
content-purge-target-size               16777216
```

Also, the above commits should probably be squashed before merging.  I'll do that once we've agreed that this is on track.

**Comment by grondo** [comment]
Nice!

One more quick comment. `flux content store` writes blobref on output in uppercase, whereas most SHA1 sum tools use lowercase (e.g. `git` tools, `sha1sum(1)`, etc.). This is ok with me (though I'd slightly prefer lowercase), but `flux content load` seems to be case sensitive:

(Also: I only just noticed `flux content load` gives error `flux: store`...)

```
$ flux content store < README.md 
sha1-A99951BA5DA982DAD82D06229992BDC8D79BFB93
$ sha1sum README.md 
a99951ba5da982dad82d06229992bdc8d79bfb93  README.md
$ flux content load sha1-a99951ba5da982dad82d06229992bdc8d79bfb93
flux: store: No such file or directory
$ flux content load sha1-A99951BA5DA982DAD82D06229992BDC8D79BFB93
[![Build Status](https://travis-ci.org/flux-framework/flux-core.svg?branch=master)](https://travis-ci.org/flux-framework/flux-core)
[snip]
```

This seems ready to go in though...

**Comment by garlick** [comment]
I could fix that.  The upper case is just a holdover from zhash.

**Comment by garlick** [comment]
Fixed the blobref case and squashed down intermediate changes.

**Comment by garlick** [comment]
Yeah that was sloppy.  Just pushed a commit to clean things up.  I thought maybe prefixing every error with the subcommand was not all that useful, so most messages were shortened.  Let me know if that seems OK.

**Comment by grondo** [comment]
Yes, this looks great to me now. Thanks!
Let me just poke at a few more things but probably ready for Friday morning merge?

**Comment by garlick** [comment]
I just remembered I never added size limit enforcement to the backing stores, which would allow a user to get a giant blob in there using `flux store --bypass-cache`.  Let me fix that, and squash the last couple fixes and then it will be ready to go I think (unless you spot anything else).

**Comment by garlick** [comment]
Just pushed with incremental changes squashed.

**Comment by grondo** [comment]
Hm, should `flux content store --dry-run` check blob size?
```
(flux-147417) $ dd if=/dev/zero bs=1024 count=2000 2>/dev/null | flux content store
flux: content.store: Input/output error
(flux-147417) $ dd if=/dev/zero bs=1024 count=2000 2>/dev/null | flux content store --dry-run
sha1-df62fc58255114f6514221fa7eaeb519537c224a
```

Also, instead of `EIO` would `EFBIG` make more sense? (Maybe not just asking)

**Comment by garlick** [comment]
Both good suggestions - fix coming.

**Comment by grondo** [comment]
OK, this looks great to me!

Want to squash the latest fixes and then I think we can merge

**Comment by garlick** [comment]
Squashed.  Thanks for all the good feedback!

**Comment by grondo** [comment]
Merged!

**Pull request merged**
