### PR TITLE
[WIP] job-manager: synchronize queue priority changes to job-info via priority-update event

### PR DESCRIPTION
**Pull request by chu11**
Per discussion in #3342.  Build on top of PR #3371 

- First add appropritae FLUX_JOB_QUEUE_PRIORITY_MIN/MAX/DEFAULT enums.  I just picked the default to be the same as the ADMIN_PRIORITY_DEFAULT, since admin priority == queue priority at the moment.

- Second, a bunch of cleanup in job-manager / job-info, to differentiate between admin/queue priority in events and storing admin vs queue priority in job data structures.  This actually breaks some tests, which are solved by ...

- Three, introduce `priority-update` event to advertise new queue priority (RFC21 update for this coming as well).

### CODE REVIEW

**Comment by garlick** [comment]
Couple quick comments:

I commented over in flux-framework/rfc#278 as well, but the `priority-update` event should be a journal-only event.  We don't want loads of them in the persistent eventlog when a job sits in the queue for a while and the bank plugin is running periodically.

It seems like there really should not be a default queue priority.  The value should be considered invalid until the job transitions PRIORITY->SCHED.

**Comment by chu11** [comment]
> It seems like there really should not be a default queue priority. The value should be considered invalid until the job transitions PRIORITY->SCHED.

Seems reasonable to me, but if we put the job in the pending list, it needs something to sort on, which is why I picked a default.  We could put on an alternate list until later? Or maybe have a rule that it is listed under the assumption of a hold?

**Comment by garlick** [comment]
Oh, I don't think it should be on the alloc queue in the job manager until PRIORITY->SCHED.

The priority isn't really defined until PRIORITY state is exited so in job-info should the jobs in DEPEND and PRIORITY state just be listed in job ID order?

**Comment by chu11** [comment]
> The priority isn't really defined until PRIORITY state is exited so in job-info should the jobs in DEPEND and PRIORITY state just be listed in job ID order?

That makes sense, lets go with that.

**Comment by chu11** [comment]
oh crap, i just realized that i coded `queue_priority` with an int, where as it should be an unsigned int or a bigger int or something.  likewise need adjustments to job listing, b/c it'd have to be passed with `s:I` instead of `s:i`.

Can't add tests for these corner cases right now, but should add tests to make sure these special cases are handled when priority plugins are supported.

**Comment by garlick** [comment]
> oh crap, i just realized that i coded queue_priority with an int, where as it should be an unsigned int or a bigger int or something. likewise need adjustments to job listing, b/c it'd have to be passed with s:I instead of s:i.

The value is defined as a 32 bit unsigned, which should be fine with s:i right?   Don't we do it all over the place?

**Comment by chu11** [comment]
> The value is defined as a 32 bit unsigned, which should be fine with s:i right? Don't we do it all over the place?

hmmm, I think you're right, we do do it in a lot of places already.

**Comment by chu11** [comment]
closing per discussion in #3382

**Pull request closed without merging**
