### PR TITLE
allow stat watcher polling interval to be specified

### PR DESCRIPTION
**Pull request by garlick**
Add missing _interval_ parameter to `flux_stat_watcher_create()`.  If inotify is unavailable, this allows the interval between stat(2) calls to be tuned.

Update test and man page.

### CODE REVIEW

**Comment by grondo** [comment]
Before we merge this, I have a question about this stat watcher.. libev allows you to override the default interval when inotify is not active (i.e. apparently when file does not exist or local fs that doesn't support inotify, etc.)

The default seems to be around 5s, which is fine for casual use but not ideal for testing and my use case (which is also a testing use case). 

Any ideas how to add support for the stat watcher `interval` parameter?

**Comment by garlick** [comment]
We can add that as a paramter to the create function if you like.

**Comment by grondo** [comment]
That would be fine if you are amenable. Otherwise I would suggest a setter function to be used before *start, but that is probably not much more acceptable.

**Comment by grondo** [comment]
Then I figure you could move the typo fix to the PR with the updated functionality, and it won't be as "in the open" ;-)

**Comment by garlick** [comment]
Right, how's that?

**Comment by grondo** [comment]
Seems great to me. I had one question about documenting when interval might be used but I leave that up to you.

**Comment by garlick** [comment]
I didn't catch that - sounds worth mentioning.  Let me fix.

**Comment by garlick** [comment]
Just pushed a small clarification in the man page.  Did I capture it?

**Comment by grondo** [comment]
Looks great! Thank you!

**Pull request merged**
