### PR TITLE
streamline message I/O operations

### PR DESCRIPTION
**Pull request by garlick**
This PR contains an overhaul of the handle implementations (internal to plugin.c and libapi.c), as well as changes to the exposed low level message I/O functions.  This PR changes some key API interfaces, though not substantially.  It is primarily focused on internal cleanup, and the APIs changed are mainly low level.

Within the handle, message I/O functions are pared down to `sendmsg()`, `recvmsg()`, and `putmsg()`.
In the API these map to `flux_sendmsg()`, `flux_recvmsg()`, and `flux_putmsg()`.

To handle the problem of synchronously receiving specific messages, such as responses with specific matchtags, or only events, or only responses, without the proliferation of `recvmsg()` variants we had before, a generic message matching function was added:

```
/* Match a message.
 */
typedef struct {
    int typemask;           /* bitmask of matching message types (or 0) */
    uint32_t matchtag;      /* matchtag block begin (or FLUX_MATCHTAG_NONE) */
    int bsize;              /* size of matchtag block (or 0) */
    char *topic_glob;       /* glob matching topic string (or NULL) */
} flux_match_t;

bool flux_msg_cmp (zmsg_t *zmsg, flux_match_t match);
```

along with these helpers that call flux_recvmsg() and flux_putmsg():
```
/* Receive a message matching 'match'.
 * If 'nomatch' is NULL, put back any non-matching messages using flux_putmsg() after a match.
 * If 'nomatch' points to a list, non-matching messages will be appended to the list
 * (creating the list if it starts out NULL).
 */
zmsg_t *flux_recvmsg_match (flux_t h, flux_match_t match, zlist_t **nomatch,
                            bool nonblock);

/* This function is called after flux_recvmsg() ONLY if a nomatch list was returned.
 * The messages in the list are put back with flux_putmsg(), and the list is destroyed.
 */
int flux_putmsg_nomatch (flux_t h, zlist_t **nomatch);
```

This facilitated a reduction of the size of the API..

### CODE REVIEW

**Comment by grondo** [comment]
This looks like a big improvement.
I'm still trying to fully digest, but I'd like to just go ahead and merge since there are many improvements here.

One thing I'd like to ask is if `flux_putmsg_nomatch` be named `flux_putmsg_list`? That seems to more clearly indicate its purpose. Though these functions may not be meant to be used by the casual user so perhaps the point is moot. (In fact it seems there is only one use case for `flux_putmsg_nomatch` does it really need to be in the handle api?)

**Comment by garlick** [comment]
Thanks for the review.  You are right we may be able to get away with hiding `flux_putmsg_nomatch` (while also renaming it).  Let me have a look and resubmit.

**Comment by grondo** [comment]
I'm still struggling with the use cases for `putmsg` as a handle api user. That makes me think I'm missing some piece of of the design or use cases, etc. So I make my comments with reservations.

The cases I see for a `recvmsg` operation are
 - with no match specified, `recvmsg` returns first message recvd to caller
 - with a match specified, `recvmsg` blocks until first matching message, but before returning to caller, does a `putmsg` for all non-matching messages.

I feel like I'm missing a key case here? Sorry

**Comment by garlick** [comment]
`flux_recvmsg_match()` internally calls` flux_recvmsg()` until a match is received, then calls `flux_putmsg()` on any non-matching messages before returning (if 'nomatch' is NULL, the common case).  Messages returned to the handle are then received before new messages, whether via `recvmsg` or the reactor.

Apart from culling `recvmsg` variants from the API, this PR does not do much to advance towards a pure reactor model.  There are still synchronous RPC's.  That being the case, if a response to a request might be interleaved with any other messages on the handle such as events, requests, or asynchronous responses, `putmsg` is necessary.

A couple of concrete use cases are:

* A reactor callback in a comms module makes a`kvs_get()` RPC.  Internally `kvs.get` is sent with `flux_sendmsg()`. `flux_recvmsg()` is then called, but instead of receiving the `kvs.get` response, a request to the comms module is received.  After receiving the `kvs.get` response, the request is put back on the handle with `flux_putmsg()`, `kvs_get()` returns, then the reactor callback returns.  The handle's reactor then unblocks, reads the request just put back there, and calls a new reactor callback to handle it.

* A utility subscribes to an event then calls `flux_rank()`.  On first call to flux_rank(), the API handle implementation makes a `flux_info()` RPC call.  The `cmb.info` message is sent with `flux_sendmsg()`.  `flux_recvmsg()` is then called but an event is received instead.  After the `cmb.info` response is received, the event is put back with `flux_putmsg()` and `flux_info()` returns.   The utility then calls `flux_event_recv()` to process events.

**Comment by grondo** [comment]
Thanks, that is helpful.

I guess what I was getting at is that I wondered if `putmsg` could be hidden from handle API users behind `flux_recvmsg_match`. In the cases above it sounds like the `recvmsg` callers could use `recvmsg_match` instead and not have to deal with `putmsg` itself, as this is automatically handled
under `recvmsg_match`. (Can you tell I'm a bit worried about casual API users forgetting to `putmsg`?)

However, I seem to remember you telling me another use case for `putmsg` outside of a recv, so maybe it does need to be exported in the API, but maybe its use should be discouraged.

Maybe it doesn't matter that much either.

**Comment by garlick** [comment]
Oh I see.  I can't think of another use case.

If we do want to hide it and possibly other stuff, any thoughts on a non-exported symbol prefix?  Our version.map exports `flux_*`, `kvs_*`, `kvsitr_*`, and `kvsdir_*`.  I'd rather pick a new prefix than start exporting symbols individually, since we are linking statically internally.

**Comment by garlick** [comment]
`_flux_*`?  `core_*`?

**Comment by grondo** [comment]
I kind of feel like I am overcomplicating this PR. Sorry!  I think we can continue to export `putmsg` variants as long as `putmsg_nomatch` is renamed to `putmsg_list` and their use is not encouraged.

**Comment by garlick** [comment]
OK, just getting back after several distractions.  I'll submit a patch to rename `putmsg_nomatch`  and maybe we can put this one to bed and think of what's next.

**Comment by garlick** [comment]
The travis failure after commit 2d114bb is odd.  The clang build is getting stuck after successfully completing`lua/t1001-timeouts.t`.  The next test script is `lua/t1002-kvs.t` but we don't even get output from the first test which should be `ok 1 - require 'flux'`.

I just manually restarted failed travis build.

**Comment by grondo** [comment]
I have those failures before and it must be something specific to the Travis-CI env. Maybe limited RAM?  Difficult to debug but I don't think it is a code problem.

**Pull request merged**
