### PR TITLE
load content-sqlite by default

### PR DESCRIPTION
**Pull request by garlick**
Rather than postpone this until #508 is resolved, add `content-sqlite` to the hardwired module list in the broker so that we can avoid taking an OOM when running many jobs.

Fixes the long standing #259

### CODE REVIEW

**Comment by garlick** [comment]
Putting my review hat on, I just remembered a conversation with @grondo about the fact that the sqlite data is stored in /tmp and on all our clusters, /tmp is backed by memory, which means at LLNL we've replaced unbounded memory usage with memory use bounded by the size of the tmpfs (half of memory by default).

**Comment by grondo** [comment]
This is probably bad form, but could we use a heuristic for now?

**Comment by garlick** [comment]
Hmm, it would be nice if a job could ask the system/resource manager "where should I dump lots of storage?"   Slurm sets `SLURM_CHECKPOINT_IMAGE_DIR`.  Is that for BLCR support?

**Comment by grondo** [comment]
> Slurm sets SLURM_CHECKPOINT_IMAGE_DIR. Is that for BLCR support?

Yeah, seems to specifically be for the slurm `checkpoint/*` plugins...

**Comment by garlick** [comment]
You should be able to do something like this
```
$ SCRATCHDIR=/nfs/tmp2/garlick/myfluxtmp  # I have a 2TB quota here, whee!
$ mkdir $SCRATCHDIR
$ srun -N4 -n4 --pty flux broker --scratch-dir=$SCRATCHDIR
...
$ rmdir $SCRATCHDIR
```

That will result in IPC sockets being created there as well, under per-rank directories, but AFAIK that should work.  Is that maybe a sufficient workaround for the time being?

I think longer term we ought to be treating storage as a resource, and maybe the content backing store something like a checkpoint file for a flux instance.  But that's a bit beyond the scope of this PR.

**Comment by grondo** [comment]
Would a user have to ensure a new `SCRATCHDIR` per instance? Most temporary data seems to get cleaned up automatically between flux instances, but in the future this may be a nice way for the user to leave some data around per instance... Thinking out loud really, sorry.

**Comment by garlick** [comment]
Yes it would need to be unique per instance.

I'm thinking the same thing, but for now we wire everything we create for cleanup.

**Comment by grondo** [comment]
> Yes it would need to be unique per instance. 

Then would it be helpful for flux-broker to automatically create an instance working directory inside of `--scratch-dir`? I forsee someone running something like you have above twice with the same `SCRATCHDIR`. 

Otherwise, this seems like a good plan for now.

**Comment by garlick** [comment]
It actually does that now if you don't specify `--scratch-directory` on the broker command line, e.g. with mkdtemp `$TMPDIR/flux-<sid>-XXXXXX`.  The reason the option exists is so that `flux-start` can locate all the brokers of a single session in one mkdtemp directory.   That makes it a bit complicated to change as you suggested.

What might be better is to add a new option that overrides $TMPDIR, or maybe better yet, an option that tells the rank 0 broker to create a new directory for persistent output, leaving scratch-directory for stuff that's cleaned up (like sockets).

**Comment by grondo** [comment]
I don't feel like I'm able to give this adequate thought, but I do like the idea from your last paragraph above.

**Comment by garlick** [comment]
Just pushed an idea:  If the broker is started with the `--persist-fs=dir` option, a unique directory will be created under dir, and be assigned to the broker attribute `persist-directory`.

content-sqlite and content-sophia look for this attribute and use it to create their database files if set, and disable cleanup so the db contents are left behind after the session quits.

Just wanted to minimally get that up here to see if it seemed reasonable.  If we go with this there should be some accompanying documentation and possibly tests.

Do we need to emit the name of the directory on the log channel?  Any other feedback?

**Comment by garlick** [comment]
Hmm, I just restarted travis - the one of the tests hung for 10 minutes in the content-sophia test while flushing the rank 0 cache.   I don't think any of the changes in this PR could have caused that, but it's disconcerting.

**Comment by grondo** [comment]
Would the `--persist-fs` option be ignored by any brokers other than rank 0?

I was thinking maybe there could be a more generic option used in cases like this to set arbitrary broker attributes (perhaps modulo some forbidden attributes)? I have a feeling over time we'll end up with lots of attributes that might want to be tweaked from the cmdline, and having a full option for each might get tedious. ;-)

An example of an existing similar system would be something like the open-mpi MCA params
 * [MCA params](https://www.open-mpi.org/faq/?category=tuning#mca-params)
 * [Setting MCA params](https://www.open-mpi.org/faq/?category=tuning#setting-mca-params)

I like how the MCA param system makes it easy to add new parameters, and you can set them all in the same way via cmdline options, environment variables, or a config file.

Maybe a `flux-broker --attr key=val --attr key=val ...` type setup?

(Ugh, sorry for the tangent!)

**Comment by garlick** [comment]
Right it's ignored on ranks > 0.

I was having similar thoughts about command line settings for attributes.  Note that here the attribute is computed based on the command line option, so its possibly not a perfect fit.  I'll have a look at the full MCA documentation tomorrow though - maybe they cover that sort of thing.

**Comment by grondo** [comment]
I think it might make sense to have `persist-fs` be an attribute as well, so that other subsystems that might want to use `persist-fs` wouldn't have to try to derive it from `persist-dir` (e.g. if you want to pass it on to a child instance)

**Comment by garlick** [comment]
Good point!

**Comment by garlick** [comment]
OK, there's now `persist-filesystem`, `persist-directory`, and `rank-scratch-directory` attributes.

These attributes can be set on the command line with `broker --setattr attr=val`.

I dropped the --scratch-directory and `--sid` options and instead now require `scratch-directory` and `session-id` to be set using `--setattr`.

No docs yet and no tests, but thought I'd better get it up here for freedback.  I can certainly redo this again if it's not looking right.

**Comment by garlick** [comment]
So now you'd do something like
```
$ mkdir /nfs/tmp2/flux
$ srun -N4 -n4 --pty flux broker --setattr scratch-dir=/nfs/tmp2/flux
```
and after your run you'd find `/nfs/tmp2/flux/fluxP-<sid>-XXXXXX`

**Comment by grondo** [comment]
Nice! :+1:

**Comment by garlick** [comment]
The travis-ci gcc test hung on the "flush rank 0 cache" test of content-sophia again.  I'm going to need to run this down.

**Comment by garlick** [comment]
I converted the broker logging options to attributes with the thought that if `persist-directory` was defined, logging should be automatically rerouted from stderr to a file in there.  Now I'm not too sure if that is a good idea, as it might come as a surprise to users when stderr goes silent after they set `persist-directory` to reroute content backing storage.  Thoughts?

**Comment by grondo** [comment]
That is a good question. I don't think I have the right answer, but for me I don't think users will necessarily want to see INFO and below messages mixed in with their stderr by default, but they may want to see ERROR and EMERG type errors on stderr *and* going to a configured file.

However, I imagine when the initial program of a Flux instance is more administrative, and perhaps the stdio of the initial program and broker-0 is more like a console, broker notices will actually be desirable on stderr as part of the output stream of a child session, saved with the stdout/err of the job creating the session.

The above statements don't seem too helpful, but I guess what I'm saying is that it might be nice if the log could be delivered more than one place eventually, and for now perhaps the default would be to log save *all* log messages to `persist-directory` if set, and send a copy of ERROR or higher log messages to stderr?

I'm not proposing this is the right solution, just 1 idea for now...

**Comment by garlick** [comment]
Another idea to throw into the mix is to have errors of some configured severity and above Cc'ed to stderr on the rank that generated them.  That would ensure they get captured by the enclosing instance in case the logging instance is too borked up to capture its own logs.

**Comment by grondo** [comment]
That sounds like a good idea.

**Comment by garlick** [comment]
Just pushed a small change that renames `log-persist-file` to `log-filename` (duh), with a default of nothing.

I'll add two more bits of code here,
* set up default `log-filename` if `persist-directory` is set
* add `log-critical` attribute to control direct logging to stderr by level

Does it seem like this is on the right track?

**Comment by grondo** [comment]
Yeah, I kind of like where this is going, personally. I'll try to play around with a bit too once it's feature-complete.

**Comment by garlick** [comment]
Just a quick summary of attribute naming thus far:
```
$ ./flux lsattr -v
content-acct-dirty                      0
content-acct-entries                    64
content-acct-size                       15681
content-acct-valid                      64
content-backing                         content-sqlite
content-blob-size-limit                 1073741824
content-flush-batch-count               0
content-flush-batch-limit               256
content-hash                            sha1
content-purge-large-entry               256
content-purge-old-entry                 5
content-purge-target-entries            1048576
content-purge-target-size               16777216
event-relay-uri                         -
event-uri                               ipc:///tmp/flux-474483-7b9LSm/event
local-uri                               local:///tmp/flux-474483-7b9LSm/0
log-bufcount                            4
log-buflimit                            1024
log-count                               4
log-filename                            /tmp/fluxP-474483-4Qfr5w/log
log-level                               7
parent-uri                              -
persist-directory                       /tmp/fluxP-474483-4Qfr5w
persist-filesystem                      /tmp
rank                                    0
rank-scratch-directory                  /tmp/flux-474483-7b9LSm/0
scratch-directory                       /tmp/flux-474483-7b9LSm
session-id                              474483
size                                    1
snoop-uri                               ipc:///tmp/flux-474483-7b9LSm/0/snoop
tbon-arity                              2
tbon-parent-uri                         -
tbon-request-uri                        ipc:///tmp/flux-474483-7b9LSm/0/req
```

Just to fine tune the naming a bit, I propose we rename
* `rank-scratch-directory` to `scratch-directory-rank`
* `log-bufcount` to `log-ring-used`
* `log-buflimit` to `log-ring-size`
* `log-level` to `log-forward-level` (logs forwarded to rank 0)

Then we'll add
* add `log-critical-level` (logs CCed to stderr)

At the moment, `persist-filesystem` and `persist-directory` are not registered if not defined.  They should be registered with a nil value so `lsattr -v` can be used as a way to summarize all known attributes.

**Comment by grondo** [comment]
This seems pretty nice. I appreciate the consistent naming update.

**Comment by garlick** [comment]
I've made the above changes, but still need to update attribute documentation.

**Comment by garlick** [comment]
I think this PR is more or less feature complete.

The attribute interface within the broker needs some redesign, but not in this pr.  Opened issue #555.

A couple of changes to default logging behavior will be noted
* logs no longer go to stderr of rank 0 by default (they are thrown away)
* LOG_CRIT and below (higher severity) go directly to stderr on the rank that logs them

This means there is a "logging hole" including everything above (lower severity than) LOG_CRIT .  Would it be better to restore the old defaults (`log-filename = stderr, log-forward-level = 6`)?  One side effect of that would be that two copies of LOG_CRIT and below messages might be seen on stderr.

**Comment by grondo** [comment]
I'm still considering, but my current thinking it is going to get really annoying to see log messages twice if `log-filename = stderr`, but maybe it is ok if they are only LOG_CRIT or LOG_ERR and above? (below?).

I'm currently thinking it is ok to throw away log messages below the current log level. If I'm understanding correctly, this is how most software behaves. (We only see "verbose" logging when we ask for it). This is helped by the fact we have a log buffer in the broker we can dump if something does go wrong. (Maybe in the future we can have a "crash hook" that dumps logs to stderr on abnormal exit or something, even when the session is not running in verbose mode)

My only concern is that by default we get the most reasonable "expected" behavior. "Expected" behavior is a bit challenging to think about in the context of flux, but I think in a general sense, users will expect to see "errors" on stderr by default, but no other verbose logs.

Does any of that make sense?

**Comment by garlick** [comment]
The duplication of messages on stderr is what led me to change the defaults in the first place, but if it's only crit and below, it seems like a very small consideration.  So how about this then:
```
log-filename = stderr
log-forward-level = 3  # err and above
log-critical-level = 2 # crit and above
```

So then the noticeable changes would be
* info, notice, and warning are squelched
* crit, alert, and emerg are duplicated

**Comment by grondo** [comment]
Yeah, that seems fine to me!

**Comment by garlick** [comment]
OK, this force push changes the defaults as discussed

**Comment by garlick** [comment]
Rebased against current master.

Incidentally 128d8bc which changes the broker options in `flux-sharness.sh` will need to be replicated in sched once this PR is merged.

**Comment by garlick** [comment]
Rebased again after #546 was merged

**Comment by grondo** [comment]
I hit a hang on `make check` in `t1000-kvs-basic.t` here:
```
ok 40 - kvs: symlink: readlink on dangling link
ok 41 - kvs: symlink: readlink works on non-dangling link
ok 42 - kvs: put on rank 0, exists on all ranks
ok 43 - kvs: unlink on rank 0, does not exist all ranks
[hang]
```

This is on hype. Could be something in my environment.

Oh, wait it finally finished after 10 min or so... expected?

**Comment by garlick** [comment]
Not expected...  I'll go try to reproduce over there.

**Comment by grondo** [comment]
This seems to reproduce (sorry if you already figured that out):
```
 src/cmd/flux start --size=33 flux exec src/test/tcommit 8 100 myprefix
```
flux-broker-0 is pegged at >100% cpu time for quite awhile during this test.

**Comment by grondo** [comment]
Is this one reproducible for you on hype, or just happening to me?
```
grondo@hype347:~/git/flux-core.git/b$ srun --pty -N4 src/cmd/flux broker -S persist-directory=/nfs/tmp2/grondo/flux
lt-flux-broker: content-sqlite: mod_main returned error: Bad file descriptor
(flux-114388) grondo@hype347:~/git/flux-core.git/b$ flux lsattr -v | grep persist
persist-directory                       /nfs/tmp2/grondo/flux
persist-filesystem                      -
(flux-114388) grondo@hype347:~/git/flux-core.git/b$ flux module list | grep content
(flux-114388) grondo@hype347:~/git/flux-core.git/b$ 
```

**Comment by grondo** [comment]
Oh oops, I guess I should have tried `flux-dmesg`:
```
$ flux dmesg
[1455149166.428275] broker.info[0]: nodeset: [0-3] (complete)
[1455149166.428323] broker.info[0]: starting initial program
[1455149166.430260] content-sqlite.err[0]: mkdir /nfs/tmp2/grondo/flux/content: File exists
[1455149166.603913] resource-hwloc.debug[0]: loaded
```

User error, but this is why I thought errors should go to stderr by default, or is the logging not set up at that point in startup?

**Comment by garlick** [comment]
I'm glad you're kicking the tires here @grondo!  On the more recent comment, LOG_ERR and below should be coming to stderr.   `flux logger --priority foo.err testing` seems to come to stderr, but I was able to reproduce your test above.

**Comment by grondo** [comment]
Whoops, I'm guessing this might not actually be a new failure, but I just hit this after ~3000 jobs in a session:
```
lt-flux-broker: src/zuuid.c:82: zuuid_new: Assertion `0' failed.
Hangup
flux: could not load config from KVS: Connection reset by peer
srun: error: hype347: task 0: Aborted (core dumped)
```

This is probably just another case of an unexpected error reading from `/dev/urandom`?
Possibly hitting the `assert()` call [here](https://github.com/zeromq/czmq/blob/master/src/zuuid.c#L65)?

I put it here since I hit it on this branch, but should I open a more generic issue on it?

**Comment by garlick** [comment]
I just pushed a change to to the logging logic.    There are now three level configurations:
```
log-stderr-level  # new
log-forward-level
log-critical-level
```

Now instead of having "stderr" be a special case value of `log-filename`, it can be separately controlled with `log-stderr`.

The logic for `log-filename` is to have nothing as the default, unless `persist-directory` is defined, then it is `${persist-directory}/log`.  Since this does not affect what is seen on stderr, the odd result of no longer seeing errors on stderr when `persist-directory` is defined is avoided.

(I'm not super happy the name `log-stderr-level`.  Would  `log-console-level` be more intuitive?)

**Comment by grondo** [comment]
> (I'm not super happy the name log-stderr-level. Would log-console-level be more intuitive?)

Current name seems ok to me, but I also like `log-console-level`

**Comment by grondo** [comment]
> flux-broker-0 is pegged at >100% cpu time for quite awhile during this test.

I ran some profiling with `perf` on hype during this test and I'm still interpreting the results, however it does seem like the main broker thread is most active. However, I noticed that CPU% is reported >100 in `top(1)` so likely there is more than one thread busy during this time (makes sense).

Here's kind of the top hits from `perf report --sort symbols`, but I'm not sure I understand the result as it seems to indicate most of the samples are from `flux_reactor_run`?

```
+   92.55%     0.00%  [.] flux_reactor_run
+   92.53%     0.03%  [.] ev_run
+   92.38%     0.01%  [.] ev_invoke_pending
+   85.98%    11.77%  [.] handle_cb
+   68.25%     0.00%  [.] __libc_start_main
+   68.25%     0.00%  [.] main
+   61.33%     2.13%  [.] flux_msg_cmp
+   51.49%     0.00%  [.] flux_rpc_usecount_decr
+   47.71%     0.23%  [.] flux_matchtag_free
+   24.30%     0.00%  [.] start_thread
+   24.30%     0.00%  [.] module_thread
+   24.08%     0.00%  [.] mod_main
+   19.04%    18.97%  [.] zlist_last
+   13.95%    13.90%  [.] zframe_is
+   11.24%    11.19%  [.] zlist_next
+    9.17%     9.14%  [.] zmsg_is
+    5.86%     5.84%  [.] delete_items_zlist.clone.0
+    3.61%     0.99%  [.] flux_msg_get_route_count
+    2.81%     2.80%  [.] zlist_first
+    1.91%     1.90%  [.] 0x0000000000022875
+    1.73%     1.72%  [.] zlist_remove
+    1.60%     1.59%  [.] flux_msg_get_type
+    1.54%     1.53%  [.] zframe_size
+    1.48%     0.00%  [k] system_call_fastpath
+    1.41%     1.40%  [.] flux_msg_get_matchtag
+    1.21%     1.21%  [.] zframe_data
+    1.18%     0.00%  [.] 0x00002aaad800db60
```

Here's the same report sorted by PID:
```
-   69.89%    69.89%  lt-flux-broker:198185
   + zlist_last
   + zframe_is
   + zmsg_is
   + zlist_next
   + handle_cb
   + delete_items_zlist.clone.0
   + zlist_first
   + 0x2aaaab903875
   + flux_msg_cmp
   + flux_msg_get_type
   + zframe_size
   + zframe_data
   + flux_msg_get_matchtag
   + zlist_remove
   + flux_msg_get_route_count
   + zmsg_last
   + flux_msg_get_flags
-   27.23%    27.23%  lt-flux-broker:199038
     handle_cb
     ev_invoke_pending
     ev_run
     flux_reactor_run
     mod_main
     module_thread
     start_thread
   + zlist_next
   + delete_items_zlist.clone.0
   + zlist_remove
   + flux_msg_cmp
   + flux_msg_get_matchtag
   + zframe_is
   + zframe_size
   + zframe_data
   + flux_msg_get_type
   + flux_msg_get_route_count
   + zlist_last
   + flux_msg_get_flags
   + zmsg_last
   + zmsg_is
   + zframe_is@plt
   + zframe_data@plt
   + zlist_first
   + zmq_msg_size
   + 0x2aaaab903870
   + 0x2aaaab9038d0
   + zmsg_first
```

**Comment by grondo** [comment]
Got another error while running this test:
```
[1455217386.650336] live.err[3]: reparent : Invalid argument
[1455217386.653381] live.err[5]: reparent : Invalid argument
[1455217386.650694] live.err[4]: reparent ÀЪ*: Invalid argument
[1455217386.653687] live.err[5]: no failover candidates
[1455217386.654165] live.err[6]: reparent à¦?«ª*: Invalid argument
[1455217386.651073] live.err[3]: no failover candidates
[1455217386.651152] live.err[4]: no failover candidates
[1455217386.654453] live.err[6]: no failover candidates
```

**Comment by grondo** [comment]
Just for fun, here is a [CPU FlameGraph](http://www.brendangregg.com/FlameGraphs/cpuflamegraphs.html) of the trace. For this I had to run on a RHEL7 system, and build Flux with `CFLAGS="-fno-omit-frame-pointer -ggdb"`:

https://gist.github.com/grondo/4f41978dbf13ecb55943

The image is an interactive SVG. I could not get it to display properly here. Instead, go to the gist, the right-click the image and choose "Open Image in New Tab"

**Comment by garlick** [comment]
Ah here is a clue - value of `content-flush-batch-count` exceeding `content-flush-batch-limit` while test is running
```
content-flush-batch-count               3412
content-flush-batch-limit               256
```
We're exceeding the configured max outstanding requests from content-store (in broker) to backing-store (in module).  I think the limit is only checked during a flush, but it should also be checked when a backing request is asynchronously started as a result of new content landing in the cache.

**Comment by garlick** [comment]
@grondo, the above change fixes it for me.  Could you double check?

Thank you so much for gathering all the profiling data and suffering through the poor state of this PR.  Another win for peer reviews!

I'll follow up on the couple of other issues you raised after lunch.

**Comment by grondo** [comment]
Yes, the latest commit seems to have resolved the problem for me.

no suffering here, the PR is solid!

**Comment by grondo** [comment]
> I'll follow up on the couple of other issues you raised after lunch.

I'm guessing the `live.err` reparent errors were due to a reparent triggered by non-responsive broker. The one thing to look into is why `p->uri` in the error message appears to point to uninitialized memory.. However, I'm doubting this error has anything to do with this PR. If you want I could open a separate issue (I'm not sure how much of the reparent code is supposed to work, I'm not sure if we actually test it or not.)

**Comment by grondo** [comment]
Another comment not strictly related to this PR is that the error message when the content directory can't be created (at least for `content-sqlite`) is confusing:
```
srun --pty -N2 src/cmd/flux broker -S persist-directory=/nfs/tmp2/grondo/flux  
(flux-114389) grondo@hype349:~/git/flux-core.git/b$ lt-flux-broker: content-sqlite: mod_main returned error: Bad file descriptor
[1455228074.678200] content-sqlite.err[0]: mkdir /nfs/tmp2/grondo/flux/content: File exists
```

The `mod_main returned error` seems to come from `flux-broker` stderr, and probably isn't going to be  useful for most users. In this case the wrong `errno` is being printed too, since it seems to be shadowed by a later errno setting (from `freectx()`?) in the error exit path for `getctx()`. The actual log message is way more useful, and did also get delivered to my console. (The only thing I wonder here is if it would be more user-friendly to strip timestamps from log messages delivered to user's console?)

Perhaps we should remove the `mod_main returned error` error message or make it LOG_INFO or higher, and make it common practice to use `flux_log_error()` in modules to direct useful error messages to users?

(I could be off track here, just let me know if so)

**Comment by garlick** [comment]
Fixing up that error does seem relevant to this PR - let me have a go at it.  Good suggestions.

**Comment by garlick** [comment]
I made some small fixes to the error path you pointed out but it probably needs more work.

I'd like to defer that and also the zuuid and reparenting issues (will open bugs shortly).

**Comment by garlick** [comment]
Here's a demo of the log output for the case reported above.  I didn't trim the timestamps for logs going to rank 0 stderr because I thought maybe they still serve a useful purpose recording the timing between events and identifying those lines as log lines, however as they are now redundant I could maybe be talked out of that.
```
$  ./flux start -o,-Spersist-directory=/tmp/xyz
[1455234142.944986] content-sqlite.err[0]: mkdir /tmp/xyz/content: File exists
[1455234142.945013] content-sqlite.crit[0]: fatal error: File exists
```
The full log is a little redundant:
```
$ flux dmesg
[1455234142.942460] broker.info[0]: nodeset: 0 (complete)
[1455234142.942586] broker.info[0]: starting initial program
[1455234142.944986] content-sqlite.err[0]: mkdir /tmp/xyz/content: File exists
[1455234142.945013] content-sqlite.crit[0]: fatal error: File exists
[1455234142.945186] broker.info[0]: module content-sqlite exited
[1455234143.022185] resource-hwloc.debug[0]: loaded
```

**Comment by grondo** [comment]
Thanks! I don't have any other comments currently on this PR. Tested out good. Thanks for improved error messages.

**Comment by grondo** [comment]
Is this ready for the button?

**Comment by garlick** [comment]
let me rebase, then OK!

**Comment by grondo** [comment]
Oh, we will then need a PR for `flux-sched` due to logging cmdline changes? Is that ready to go?

**Comment by garlick** [comment]
Ah right, momentarily.

**Pull request merged**
