### PR TITLE
Switch lua scripts to use lua interpreter in PATH

### PR DESCRIPTION
**Pull request by SteVwonder**
This is instead of using the hardcoded `/usr/bin/lua` interpreter.
Brings these lua scripts in line with other scripts that already do
so (see: [src/cmd/flux-submit](https://github.com/flux-framework/flux-core/blob/04cc8277677d6725bc9fe4aadc5fee850e0af61d/src/cmd/flux-submit))

### CODE REVIEW

**Comment by grondo** [comment]
While I could go either way on this (there are some drawbacks to using lua found in PATH), probably we  should be careful not to touch the Lua scripts and tests that are pulled in from other projects like `lua-affinity` and `lua-hostlist`.

I imagine you are running on some platform without `/usr/bin/lua`, and thus the PR?

**Comment by SteVwonder** [comment]
Good point, I guess I should have opened an issue first rather than immediately submitting a PR (noted).

I actually am running on a system where /usr/bin/lua **was** Lua 5.2.   I failed to get it working after a few hours, caved in and replaced the system Lua 5.2 with 5.1.  So this isn't necessary for things to work on my system now, but it definitely was a problem.

If you want, I can remove `lua-affinity` and `lua-hostlist` from the PR.  Otherwise, feel free to close.

**Comment by grondo** [comment]
Like I said, I could go either way (and sorry about lack of Lua 5.2 compatibility) I'm fine with use of `#!/usr/bin/env lua` I think in this case, though we've run into problems doing the same for python scripts (with system python scripts breaking in bad ways when somebody loads some other software that depends on a different python version) I don't think this will be a big issue for Lua though.

Ideally, the build system would embed the correct paths to supported Lua/python/sh into the files duriing build time, but this is always a pain because you have to work on a file `script.lua.in` then do make or `configure` to build `script.lua` to test it...

If you remove lua-affinity, lua-hostlist and any other imported scripts from the PR I think I'm fine to merge it (however, maybe get one other person's ACK first.)

**Comment by SteVwonder** [comment]
Any thoughts @garlick?

I don't mind either way since I found a workaround for my machine, but I think consistency would be good.  Several lua scripts have `/usr/bin/env lua` at the top (i.e [flux-cron](https://github.com/flux-framework/flux-core/blob/master/src/cmd/flux-cron), [flux-submit](https://github.com/flux-framework/flux-core/blob/master/src/cmd/flux-submit), [flux-wreck](https://github.com/flux-framework/flux-core/blob/master/src/cmd/flux-wreck)).  So if using `/usr/bin/lua` is the decision, then maybe switching those 3 scripts to `/usr/bin/lua` should also be considered?

**Comment by garlick** [comment]
It seems like `#!/usr/bin/lua` is better when flux-core is packaged (since dependencies can sort out which /usr/bin/lua is installed), and `#!/usr/bin/env lua` is better when flux-core is unpackaged, so a user without admin privs can get things working if /usr/bin/lua is wrong.

I guess I'd vote for `#!/usr/bin/env lua` for now, but I defer to @grondo's experience if he decides it should go the other way.

**Comment by grondo** [comment]
Thanks for input @garlick!

I'm fine with `#!/usr/bin/env lua` for now, except for the scripts embedded from other projects as I mentioned above.

Thanks!

**Comment by grondo** [comment]
Thanks, @SteVwonder !

**Pull request merged**
