### PR TITLE
cleanup: fix in-tree includes for idset.h, subprocess.h and other small fixes

### PR DESCRIPTION
**Pull request by grondo**
Just a few collected cleanups: 
 - remove some leftovers from libjobspec
 - ensure in-tree code can include <flux/idset.h>
 - ensure subprocess.h is included from <flux/core.h> since it is in libflux-core.so (end result: do not include subprocess.h directly anymore)

This is still a WIP because I'm not sure if my quick fix for the python bindings is even close to correct.

### CODE REVIEW

**Comment by grondo** [comment]
I added another questionable python  binding change. See ef5c669.

Also updated `.mergify.yml` to remove codecov/project as a condition, since we've seen codecov.io delay its status updates (and fixed the test for pr titles with "wip" I think)

**Comment by SteVwonder** [comment]
>  grondo wants to merge 7 commits into flux-framework:master from grondo:konmari-puchi

konmari-puchi?

> I'm not sure if my quick fix for the python bindings is even close to correct

So the short story is: I think what you did, @grondo, is the right thing.  The logner story: the `make_binding.py` starts at `core.h` and follows all `#include`s that use double quotes (as opposed to brackets) to build a "mega_header" that includes the contents of every flux header reachable from `core.h`.  Since `#include <sys/types.h>` is ignored, it doesn't get included in the generated `_core.c`.  Seeing as including the contents of every system header would just be excessive to solve this problem, I think manually defining `pid_t` is totally fine.

Related: I noticed that `subprocess.h` has `pid_t` as a return type, but the header itself does not include `<sys/types.h>`, just the `subprocess.c` file does.  Is that correct?  Naively, it seems to me that the subprocess header should be the one to include `<sys/types.h>`.  (Note: this doesn't solve the python problem, I'm just wondering since I stumbled across it).

**Comment by grondo** [comment]
> konmari-puchi?

Sorry, a play on that "Tidying Up" show --  KonMari is the method of tidying up and I looked up "puchi" --means something like "a little bit" in Japanese.

> Related: I noticed that subprocess.h has pid_t as a return type, but the header itself does not include <sys/types.h>

You are correct this should be added to subprocess.h. I actually had a fix for this in my branch, but dropped it along the way when trying out fixes for python bindings.

**Comment by SteVwonder** [comment]
> a play on that "Tidying Up" show -- KonMari is the method of tidying up and I looked up "puchi" --means something like "a little bit" in Japanese.

That's clever. I like that. :smile:

**Comment by grondo** [comment]
Whoa something went very awry with my last push, trying again:
```
checking Major version... 0085cf4
checking Minor version... 4
checking Point version... 
```
I wonder if we hit some corner case with `git describe` output and the `AX_SPLIT_VERSION` macro?

**Comment by garlick** [comment]
I see you removed the WIP so in it goes!  Thanks!

**Comment by grondo** [comment]
:fist_oncoming:

**Comment by trws** [comment]
Looks good to me.  The python thing is exactly where it belongs, and is the "right way" to handle that kind of thing so it can be portable.  Thanks @grondo!

**Pull request merged**
