### PR TITLE
job-manager: stop publishing job-state event messages

### LINKED ISSUE #5400: pub/sub job state transition notification is little used
Problem: the job manager publishes event messages when jobs transition states.  AFACT nothing subscribes to these messages as they don't provide sufficient detail for real world use cases.

As an experiment I disabled this feature and all our tests continue to pass, except for `t2207-job-manager-bulk-state.t` which specifically ensures that the event messages are published.

### PR DESCRIPTION
**Pull request by garlick**
Problem: the job manager publishes `job-state` event messages when jobs transition states.  This feature generates background traffic on the overlay network, is undocumented, has been been overtaken by other methods of job synchronization.
    
Stop publishing `job-state` event messages.
    
Fixes #5400

This is currently based on #5432 and will need to be rebased once that is merged.

### CODE REVIEW

**Review by chu11 — APPROVED** [review]
LGTM!

**Comment by garlick** [comment]
Restarted inception builder after a failure here:
```
2023-09-08T13:03:02.1944572Z [1m[31mnot ok 11 - flux-watch: works with --since(B[m
2023-09-08T13:03:02.1944803Z 
2023-09-08T13:03:02.1957351Z #	
2023-09-08T13:03:02.1957513Z 
2023-09-08T13:03:02.1974386Z #		t_since=$(flux jobs -ac 1 -no {t_submit}) &&
2023-09-08T13:03:02.1974601Z 
2023-09-08T13:03:02.1991243Z #		test_must_fail flux watch -v --since=$t_since >since.out 2>&1 &&
2023-09-08T13:03:02.1991526Z 
2023-09-08T13:03:02.2008002Z #		test_debug "cat since.out" &&
2023-09-08T13:03:02.2008193Z 
2023-09-08T13:03:02.2024963Z #		grep "Watching [12] job" since.out
2023-09-08T13:03:02.2025163Z 
```

**Comment by vsoch** [comment]
Can we add this back? it will be hard to build anything event driven around flux and jobs without it. A manual poll, or getting ids and then having to watch each, is a less ideal approach.

**Comment by garlick** [comment]
The journal example is event driven.

**Comment by vsoch** [comment]
Yep we are good - I'll post this here for future others to find: https://github.com/flux-framework/flux-core/issues/6352#issuecomment-2398064808

**Pull request merged**
