### PR TITLE
Output appropriate error message on help failure and minor cleanups

### PR DESCRIPTION
**Pull request by chu11**

### CODE REVIEW

**Comment by chu11** [comment]
Hmmm, lots of failures in make check, it appears a2x can't be found in travis

```
checking for a2x... no
```

probably have to add asciidoc to travis.yml.  But before I do that, I don't see what could have happened between #871 and the current master.

**Comment by grondo** [comment]
We purposefully leave a2x out of Travis, it takes too long to install all
its dependencies. Why does make check fail without a2x now?

**Comment by grondo** [comment]
Ah, the problem is (at the least) with the `flux-help` tests in `t0001-basic.t`. These tests use fake manpages to ensure `flux help` properly invokes `man` even when manpages aren't built, so the `.nodocs` file breaks these tests.

A possible workaround would be some kind of environment variable to disable the `.nodocs` test, or possibly point `flux-help` to a different config dir without the `.nodocs` file, etc...

**Comment by chu11** [comment]
Ahhh.  I realized it was fake manpages in the tests, but I didn't quite get how things worked with ```a2x``` not being installed.  I now see with the commit 0e13c8347ef8647d30661d762f2a302022006819, the logic surrounding ```a2x``` being required/not required changed.

Yeah, I'll have to tweak the tests in some way.

**Comment by grondo** [comment]
I guess it would be safe if you removed `.nodocs` for the duration of those tests, if nothing else in `make check` is dependent on the `.nodocs`  file (keep in mind someday parallel-tests might work, so multiple tests could be running at the same time)

**Comment by chu11** [comment]
I elected to support a ```FLUX_IGNORE_NO_DOCS``` environment variable as a workaround.  It's not the cleanest solution, but I think it ensures the unit tests will work regardless if docs are generated or not, and should be safe for any future parallelism in the testsuite in the future.

**Comment by chu11** [comment]
because of the workaround environment variable, code coverage does go down a tad as some of the new ```.nodocs``` code won't be touched.

**Comment by grondo** [comment]
Yeah, seems fine to me. Merging this one thanks!

**Pull request merged**
