### PR TITLE
testsuite: fix shed-simple test races

### PR DESCRIPTION
**Pull request by chu11**
Per #3343 discussion.  Note that the first commit I still from @grondo's comment in the ticket, so someone other than @grondo would have to approve.

### CODE REVIEW

**Comment by grondo** [comment]
I would like to avoid the looping requirement in tests as much as possible. I think the intent is for `flux resource list` to block if `flux module load sched-simple` has returned but the scheduler has not acquired resources. I think moving the registration of message handlers before calling into schedutil should have accomplished that, but I haven't looked back at the code yet.

If there is still a race here, we should fix that instead of looping in the test.

Also remove the dead code check for NULL `ss->rlist`

**Comment by chu11** [comment]
per our discussion in #3343 I think we can get rid of the loops on `flux resource` calls, but for the remaining dmesg test, I think we have to keep it.  Unless there's some other way to test that the scheduler loaded in unlimited mode?

**Comment by grondo** [comment]
No, I can't think of an another way to do that one.

**Comment by chu11** [comment]
rebased & re-pushed, removing the `flux_msg_handler_addvec()` move and removing the `flux resource` loop checks.

**Comment by chu11** [comment]
re-pushed adding the dead-code fix, and fixed up a commit message

as an aside, the @grondo contribution is no longer in this PR, so he can approve now :-)

**Comment by grondo** [comment]
> No, I can't think of an another way to do that one.

Oh, actually since `log.dmesg` is a streaming RPC and the log can be followed, we could do something with a Python script here. E.g. the following will follow the dmesg log waiting for a matching line:

```python
import sys
import argparse
import re

import flux
from flux.rpc import RPC
from flux.core.watchers import TimerWatcher
from flux.constants import FLUX_RPC_STREAMING


parser = argparse.ArgumentParser(
    description="watch the flux dmesg log for a given pattern"
)
parser.add_argument(
    "-t",
    "--timeout",
    help="Timeout with error after some number of seconds",
    type=float,
    default=1.0,
)
parser.add_argument("pattern")
args = parser.parse_args()


def timer_cb(h, watcher, revents, _arg):
    print("Timeout!", file=sys.stderr)
    h.reactor_stop_error()


def dmesg_cb(rpc, pattern):
    buf = rpc.get()["buf"]
    match = pattern.match(buf)
    if match:
        print(buf)
        rpc.flux_handle.reactor_stop()
    rpc.reset()

pattern = re.compile(args.pattern)

h = flux.Flux()

rpc = h.rpc("log.dmesg", {"follow": True}, flags=FLUX_RPC_STREAMING)
rpc.then(dmesg_cb, pattern)

TimerWatcher(h, 5, timer_cb).start()
if h.reactor_run() < 0:
    sys.exit(1)
```

```console
ƒ(s=1,d=0,builddir) grondo@asp:~/git/f.git$ flux python dmesg.py -t 5.0 '.*ready unlimited.*'
<56>1 2020-11-20T03:57:23.497062Z 0 job-manager 10616 - - scheduler: ready unlimited
ƒ(s=1,d=0,builddir) grondo@asp:~/git/f.git$ flux python dmesg.py -t 5.0 '.*blah*'
Timeout!
ƒ(s=1,d=0,builddir) grondo@asp:~/git/f.git$ echo $?
1
```

**Review by grondo — APPROVED** [review]
Looks good. If you want, we can merge this one now since it fixes racy tests. Once the changes to dmesg RPC go in (#3359), I can submit a PR that introduces the dmesg-follow python script and remote any while loops required in tests when grepping dmesg output.

**Comment by chu11** [comment]
> Oh, actually since log.dmesg is a streaming RPC and the log can be followed, we could do something with a Python script here. E.g. the following will follow the dmesg log waiting for a matching line:

Oh good idea.  I guess I could have used `waitfile` as well if I put the dmesg into the background.

> Once the changes to dmesg RPC go in (#3359), I can submit a PR that introduces the dmesg-follow python script and remote 
> any while loops required in tests when grepping dmesg output.

instead of adding a new script, perhaps `flux dmesg` could have a timeout option, similar to the `flux job wait-event` option?

**Comment by chu11** [comment]
> Looks good. If you want, we can merge this one now since it fixes racy tests. Once the changes to dmesg RPC go in (#3359), I can submit a PR that introduces the dmesg-follow python script and remote any while loops required in tests when grepping dmesg output.

Cool, thanks.

**Comment by grondo** [comment]
> instead of adding a new script, perhaps flux dmesg could have a timeout option, similar to the flux job wait-event option?

Wouldn't it also need support for matching a log message and exiting early with success? Seems much easier to do this natively in python, and will be a good example for others. Also sending programs to the background in sharness tests is always a little icky

**Comment by chu11** [comment]
> Wouldn't it also need support for matching a log message and exiting early with success?

Oh you're right.  I was thinking just generically "quit after X seconds", but that option is sort of dumb.

**Pull request merged**
