### PR TITLE
jobspec: replace minus operator to multiplication

### PR DESCRIPTION
**Pull request by dongahn**
Make the implementation come to compliance with RFC14's JRC rule section.
Tested with resource-query and this one-liner seems enough.

### CODE REVIEW

**Comment by dongahn** [comment]
Hmmm. I don't understand why this one line change causes a valgrind-related error....

https://travis-ci.org/flux-framework/flux-core/jobs/306163007#L9029

**Comment by garlick** [comment]
Looks like an unrelated transient error in czmq shutdown:
```
==10045== Memcheck, a memory error detector
==10045== Copyright (C) 2002-2013, and GNU GPL'd, by Julian Seward et al.
==10045== Using Valgrind-3.10.1 and LibVEX; rerun with -h for copyright info
==10045== Command: /home/travis/build/flux-framework/flux-core/flux-core-0.8.0-465-g95b20d2f/_build/sub/src/broker/.libs/lt-flux-broker --shutdown-grace=4 /home/travis/build/flux-framework/flux-core/flux-core-0.8.0-465-g95b20d2f/t/valgrind/valgrind-workload.sh 10
==10045== 
FLUX_URI=local:///tmp/flux-5SBsSk
==10045== 
==10045== HEAP SUMMARY:
==10045==     in use at exit: 111,117 bytes in 102 blocks
==10045==   total heap usage: 912,236 allocs, 912,134 frees, 78,583,150 bytes allocated
==10045== 
==10045== 288 bytes in 1 blocks are possibly lost in loss record 27 of 39
==10045==    at 0x4C2CC70: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==10045==    by 0x4012FE4: allocate_dtv (dl-tls.c:296)
==10045==    by 0x4012FE4: _dl_allocate_tls (dl-tls.c:460)
==10045==    by 0x5E3ED92: allocate_stack (allocatestack.c:589)
==10045==    by 0x5E3ED92: pthread_create@@GLIBC_2.2.5 (pthread_create.c:500)
==10045==    by 0x54CD8DA: zactor_new (zactor.c:122)
==10045==    by 0x4E4826A: flux_sec_comms_init (security.c:197)
==10045==    by 0x407361: main (broker.c:411)
==10045== 
{
   <insert_a_suppression_name_here>
   Memcheck:Leak
   match-leak-kinds: possible
   fun:calloc
   fun:allocate_dtv
   fun:_dl_allocate_tls
   fun:allocate_stack
   fun:pthread_create@@GLIBC_2.2.5
   fun:zactor_new
   fun:flux_sec_comms_init
   fun:main
}
==10045== LEAK SUMMARY:
==10045==    definitely lost: 0 bytes in 0 blocks
==10045==    indirectly lost: 0 bytes in 0 blocks
==10045==      possibly lost: 288 bytes in 1 blocks
==10045==    still reachable: 110,317 bytes in 100 blocks
==10045==         suppressed: 512 bytes in 1 blocks
==10045== Reachable blocks (those to which a pointer was found) are not shown.
==10045== To see them, rerun with: --leak-check=full --show-leak-kinds=all
==10045== 
==10045== For counts of detected and suppressed errors, rerun with: -v
==10045== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 1 from 1)
not ok 1 - valgrind reports no new errors on single broker run
```

**Comment by garlick** [comment]
@dongahn:  it would be nice to have a more descriptive commit message, for those of us who have not been following the jobspec design in detail.

> jobspec: replace minus operator to multiplication

Did you mean "replace minus operator _with_ multiplcation"?

> Make the implementation come to compliance with RFC14's JRC rule section.
> Tested with resource-query and this one-liner seems enough.

What specifically is out of compliance?  Perhaps a quote from the spec would be useful here.

**Comment by dongahn** [comment]
@garlick: OK, that makes sense. I forced a push. Hopefully this works.

**Comment by garlick** [comment]
Much better, thank you!

Looks like you may need to rebase on current master?

We probably need @morrone or @grondo to give an ACK before merging.

**Comment by garlick** [comment]
> Looks like you may need to rebase on current master?

Strike that - github was saying it was out of date, but not now.

**Comment by grondo** [comment]
Nice explanation @dongahn, makes sense to me! (Was likely just a typo in the orignal)

My only suggestion is maybe we should add a test case to `t/jobspec/invalid` to ensure a jobspec input using the invalid operator `-` is rejected?

**Comment by dongahn** [comment]
ok. should be easy enough.

**Pull request merged**
