### PR TITLE
kvs: add read-your-writes consistency tests

### PR DESCRIPTION
**Pull request by chu11**
per discussion in #1832

### CODE REVIEW

**Comment by garlick** [comment]
Nice!

We could probably use a prominent block comment on the pause/unpause request handlers that this is a test hook, and maybe a reference to the test code that uses it.

Would this be a bit simpler (and just as effective) if the pause/unpause applied equally to all namespaces, and if there could be only one in effect?  (Just a thought - if this is as simple as it gets I'm OK with it!)

**Comment by chu11** [comment]
> We could probably use a prominent block comment on the pause/unpause request handlers that this is a test hook, and maybe a reference to the test code that uses it.

Good idea, will add.

> Would this be a bit simpler (and just as effective) if the pause/unpause applied equally to all namespaces, and if there could be only one in effect? (Just a thought - if this is as simple as it gets I'm OK with it!)

Hmmm.  It probably adds a small bit of complexity as I'd have to iterate through all namespaces on a pause / unpause.  Not much, but it's something.  Are you imaging a test case that would need that?

**Comment by chu11** [comment]
re-pushed with extra comments added

**Comment by garlick** [comment]
> Hmmm. It probably adds a small bit of complexity as I'd have to iterate through all namespaces on a pause / unpause. Not much, but it's something. Are you imaging a test case that would need that?

No no, I was just thinking maybe it could be done without  possibly stalling/restarting when the namespace under test isn't known yet, or adding state to the namespace (as opposed to tracking it separately) and that that might be a bit simpler to implement.  This is fine.

**Comment by garlick** [comment]
This looks fine, and please disregard my suggestion.  I see now that would probably be a mess.

Thanks!

**Pull request merged**
