### PR TITLE
implement flux_open()

### LINKED ISSUE #178: implement generic flux_open()
Implement a generic handle create/destroy function that selects the back end handle implementation by parsing the URI argument:
```
/* Open flags
 */
enum {
    FLUX_O_TRACE        = 1,    /* send message trace to stderr */
    FLUX_O_COPROC       = 2,    /* start reactor callbacks as coprocesses */
};
/* Create/destroy a broker handle.
 * The 'uri' scheme name selects a handle implementation to dynamically load.
 * The rest of the URI is parsed in an implementation-specific manner.
 * A NULL uri selects the "local" implementation with socket path derived
 * from the FLUX_TMPDIR environment variable.
 */
flux_t flux_open (const char *uri, int flags);
void flux_close (flux_t h);
```

### PR DESCRIPTION
**Pull request by garlick**
This PR adds `flux_open()` and `flux_close()` calls that take a URI argument.  The URI _scheme_ selects a handle implementation, which is dynamically loaded.

There is only one handle implementation that is exported in this way - the API socket one.  It is selected either by passing a NULL URI or specifying a URI with the scheme `local://path`, where `path` is the directory containing the UNIX domain socket.

`FLUX_FLAGS_*` were renamed to `FLUX_O_*` and uses of `flux_api_open()` and `flux_api_close()` should be replaced by `flux_open()` and `flux_close()`.  However the old interface still exists (until we get a PR that changes this in flux-sched landed).

This is a first cut, I would appreciate some review.

Resolves #178

### CODE REVIEW

**Comment by grondo** [comment]
Initial comments. I'm not sure I've fully digested this yet so feel free to correct any errors or bad assumptions I've made.

 * Should `--handle-path` maybe be `--handle-uri`?
 * I'd feel better if the symbol exported from the  handle/open DSO was named more explicitly, i.e. instead of `handle_init`, maybe `flux_handle_init` or `flux_handle_plugin_init`? (It almost even seems like it should `flux_handle_open`... :confused:

My only other comment is that the naming is a bit strange for me. It seems like the *handle* is the `flux_t` object, and the DSO implementing `flux_open`/`flux_close` is a handle implementation or handle open implementation? This is just a comment -- I'm not really advocating a change or anything.

**Comment by garlick** [comment]
The `flux --handle-path` option prepends a directory to the search path for handle implementations, not what you thought.  Maybe it should be called `--handle-searchpath`?  I don't know why I didn't add the obvious `--handle-uri` option.  That should be done.

Originally I used _connector_ instead of _handle_ but I wasn't sure about that one.  What do you think?  I like it more now...

Regarding the symbol export, I was thinking it should not be `flux_` prefixed as it's not part of the public namespace.  But it doesn't really matter as these modules don't contribute to the namespace.  Are we OK with there being a function entry point that calls a registration function to register its struct-of-operations?  I wasn't sure if it would be better to just export the struct under a known name and add an _init_ operation.

**Comment by grondo** [comment]
> The flux --handle-path option prepends a directory to the search path for handle implementations, not what you thought. Maybe it should be called --handle-searchpath? I don't know why I didn't add the obvious --handle-uri option. That should be done.

Ah, oops sorry for not-so-careful reading of the source.

I do think I like *connector* much better!

I don't feel too confident commenting on this, but if the *init* function is ever going to be optional, then could you export the *init* function and the operations struct? At least one of these symbols would be required: If no *ops* struct, then an operations struct is expected to be registered explicitly by *init* function. If somehow an *init* function is not required, then the operations struct at least would be required.

The benefit of this kind of approach is that it makes it easier to add more symbols to the DSO in the future, and you are not required to stub out unneeded symbols (and you don't have to keep updating the plugin definition structure in the future.

Oh, we might also consider having the dso export a name/author/version? (Just throwing ideas out there now)

**Comment by garlick** [comment]
I don't quite follow your comments on exporting (optionally) both the init function and the operations struct.  How does that help make it easier to add more symbols and avoid stubbing unneeded ones?  Either way there is an operations struct that creates an ABI challenge, right?  Or are you proposing making all the members of the operations struct separately exported?

This is really not a problem I've worked through in a serious way before so I am very open to guidance.

**Comment by grondo** [comment]
Sorry for the poor description. 

Yes, the operations struct will always be an ABI issue, but here you have the handle operations struct *and* a separate function to initialize the handle (or handle *connector*): `handle_init`. You could add `handle_init` into the ops struct, or it could be wrapped a `handle_connector_struct` like:
```
struct handle_connector_struct {
  handle_init_f handle_init;
  struct flux_handle_ops *ops;
}
```
However,  later if you wanted to add, say, `handle_close`, you would have to change either `handle_connector_struct` or `flux_handle_ops`.

My only point is that if you avoid the `handle_connector_struct` and instead allow DSOs to export `handle_init` (as you are now), then later you can add `handle_close` without changing any structs -- and in fact you might not even have to change the source of a handle connector/implementation that doesn't need the `handle_close`, since if the symbol isn't there your dso loader can assume it is not implemented. 

(sorry that is a really inarticulate description of a simple concept, which probably doesn't even apply here)

The drawback of this approach is longer load time as you have to call `dlsym()` on each symbol/function exported in this way. Therefore, I probably wouldn't recommend it for all the handle operations functions (and therefore it was probably a nonsensical suggestion in the first place)

**Comment by garlick** [comment]
OK, point taken, thanks!

So let's just continue to export `handle_init` (renamed to `connector_init`) and _not_ export the handle ops.  Then as you say if we want to add symbols for `connector_version`, `connector_author`, etc., we can do that later without perturbing the operations struct.

**Comment by garlick** [comment]
Closing this PR, opening another with the name changes.

**Pull request closed without merging**
