### PR TITLE
Remove JSON typedef, just use json_object *

### PR DESCRIPTION
**Pull request by morrone**
Remove the JSON typedef, and in its place use json_object * directly.
The JSON typedef proved to be more obfuscation than beneficial.

### CODE REVIEW

**Comment by morrone** [comment]
It looks like flux-sched has some JSON as well.  But there might be no interdependency because flux-sched just has a straight copy of shortjson.h.

**Comment by garlick** [comment]
Yay!  Waiting for travis.

Shouldn't affect sched.

**Comment by morrone** [comment]
Whoops.  Looks like I flubbed somewhere.

**Comment by grondo** [comment]
Thanks, wow!

One of the Travis builds hung, but I'm unsure why. I just restarted it.

**Comment by grondo** [comment]
> Whoops. Looks like I flubbed somewhere.

I don't think so... we do have some known intermittent failures of `make check` under travis-ci. Sometimes when there is a failure, one of the builds just needs to be restarted. I apologize for that.

**Comment by grondo** [comment]
Looks good now!

**Pull request merged**
