### PR TITLE
NEWS.md: add release notes for flux-core v0.29.0

### PR DESCRIPTION
**Pull request by grondo**
First draft of release notes for flux-core v0.29.0.

Feel free to directly push any changes here. I've added #3845 to the NEWS file already assuming it will be merged before we tag.

### CODE REVIEW

**Review by garlick — APPROVED** [review]
Thanks, looks great to me!

**Comment by grondo** [comment]
Pushed a final update here to rebase and add a line for #3849

**Comment by grondo** [comment]
Ok to set MWP?

**Comment by garlick** [comment]
Yep!  I'll do it.

**Pull request merged**
