### PR TITLE
github: check flux-sched@master against submitted flux-core PRs

### PR DESCRIPTION
**Pull request by grondo**
Same PR as #2677, but resubmitting to see if the issues with Travis-Ci not responding are fixed.

### CODE REVIEW

**Comment by grondo** [comment]
BTW, this PR can't be merged by mergify since it modifies mergify contif.

**Comment by grondo** [comment]
Ok, looks like travis is reporting back this time.

**Comment by garlick** [comment]
Thanks!

**Comment by grondo** [comment]
Thanks!

**Pull request merged**
