### PR TITLE
Fix racey behavior in job log test + minor cleanups

### PR DESCRIPTION
**Pull request by chu11**
Minor cleanups mostly to check for errors on strtoul() and strtod() calls, plus a typo error I found in the broker.

### CODE REVIEW

**Comment by chu11** [comment]
Code coverage does go down due to missing error paths of new checks.

**Comment by garlick** [comment]
Strike that last comment - just saw the advice in the NOTES section of the man page
```
       Since  0  can legitimately be returned on both success and failure, the
       calling program should set errno to 0 before the call, and then  deter‐
       mine if an error occurred by checking whether errno has a nonzero value
       after the call.
```

I guess let's do that then.  Meh.

**Comment by chu11** [comment]
@garlick Ahh good eye, I did miss one ```endptr``` addition.

**Comment by garlick** [comment]
Good catch on the rc1/rc3 typo!  Ok, this looks good.  Thanks!

**Pull request merged**
