### PR TITLE
broker: remove many ooms and xzmalloc/xstrdup/xasprintf calls

### PR DESCRIPTION
**Pull request by chu11**
Final cleanup/refactor before I would something big as discussed in #2182.  Can discuss if #2182 is something we want to go down the path of or if we should hold out on that work.

### CODE REVIEW

**Comment by chu11** [comment]
ugh, bad @chu11, I forgot to run `make check` before pushing.  BRB.

**Comment by chu11** [comment]
re-pushed with fixes

**Comment by garlick** [comment]
LGTM.  Needs a rebase.

> Can discuss if #2182 is something we want to go down the path of or if we should hold out on that work.

In face to face planning we decided to put this off (for the online record).

**Comment by chu11** [comment]
rebased and repushed

**Comment by garlick** [comment]
Thanks!

**Pull request merged**
