### PR TITLE
deps: switch from lzo to lz4

### PR DESCRIPTION
**Pull request by trws**
This commit switches us from lzo as a vendored dependency to lz4 as an
external dependency.  LZ4 tends to win on performance, has a similar
api and similar compression characteristics, but avoids the need to link
GPL code into libflux-core.  In support of fixing #1084.

Note that while our discussion in #1084 deemed this unnecessary, minilzo was being linked into libflux-core.so.  With this and #1667, I think the only GPL code deps in the repo are base64.c/h.

I thought that could be fixed by just updating to the current upstream, since libmunge is now LGPL, but apparently that's *just* libmunge and not munged where the base64 files come from.  So that begs the question, should we talk with folks about getting those two files LGPLed or switch to using the base64 from libsodium (it has it, and we already depend on it)? Thoughts?

### CODE REVIEW

**Comment by garlick** [comment]
lz4 sounds like a win.

Regarding base64, we were already talking with @dun about the license, although actually, it wouldn't be a bad thing to switch over to the one in libsodium. The API looks more or less similar to the one we are using:

https://libsodium.gitbook.io/doc/helpers#base64-encoding-decoding

libsodium is only a transitive dependency of flux-core though, which means we would need the "dev" package where we didn't before. 

Maybe open an issue on that one?  It may be easier to just get the license fixed for now.

**Comment by garlick** [comment]
Thanks @trws!

Would you mind splitting the removal of libminilzo out of 8961aa9b6b83d88a72e80703b3fede4b02119ba3 ?

In general, I think it makes the history easier to deal with when commits that contain substantive changes, like changing the compression alg used in `content-sqlite`, are isolated from mundane changes, like removal of a library that is no longer used.

**Comment by garlick** [comment]
Perfect, thanks @trws!

**Comment by garlick** [comment]
Ooops, should have checked - liblz4-dev is not installed on our rhel7 based clusters.  I'll open an issue to get that included in the next update.

**Comment by garlick** [comment]
I opened https://lc.llnl.gov/jira/browse/TOSS-4343

(private to LLNL)

**Comment by trws** [comment]
Crud, sorry, I saw the lib installed but missed the headers!




On October 23, 2018 at 9:58:24 AM PDT, Jim Garlick <notifications@github.com> wrote:

Ooops, should have checked - liblz4-dev is not installed on our rhel7 based clusters. I'll open an issue to get that included in the next update.

**Pull request merged**
