### PR TITLE
kvs: remove watch handlers & api

### PR DESCRIPTION
**Pull request by chu11**
With the wreck subsystem being removed, we can begin removing a lot of older stuff.  We start by removing watch.  This removes almost all of it.  There is a bit of watching code in ```modules/kvs``` that is used by ```kvs.sync```.  I have a PR that re-does how ```kvs.sync``` works, which will be a follow up to this PR.

### CODE REVIEW

**Comment by grondo** [comment]
I'm sure there is a good one, but any reason why `flux kvs watch` couldn't be redone using `flux_kvs_lookup` instead of requiring a `--watch` option for `flux kvs get`? A separate `flux kvs watch` command seems more user-friendly to me, but then again I haven't thought about it much, and also there might not be many uses cases for watch from the cmdline anyway.

Just wanted to bring itup.

**Comment by chu11** [comment]
> I'm sure there is a good one, but any reason why flux kvs watch couldn't be redone using flux_kvs_lookup instead of requiring a --watch option for flux kvs get?

I hadn't really thought about it much.  I suppose @garlick originally added it to ```flux kvs get``` b/c it goes through the "lookup" interface instead of the "watch" interface?

It's worth mentioning that it would be hard / difficult to perfectly map the old "watch" to the "get --watch".  A combination of ```--waitcreate``` and ```--pedantic``` would have to be specified by users to have similar effects.

**Comment by garlick** [comment]
That might be nice, and may simplify the code in `get` a bit, since it shouldn't need to start the reactor and wait for multiple responses.

I wouldn't worry about matching the exact semantics of the old watch.  I think we've moved on at this point.

**Comment by chu11** [comment]
hmmm.  We hit our connector.local Broken Pipe friend again (#1977, #1641, #1386, #542).  A tad concerning b/c I did modify ```watch_disconnect``` in this PR.  But I'm skeptical it's related to this.

```
2019-02-13T22:02:47.667891Z connector-local.err[0]: send kvs-watch.lookup response to client 7AFDC: Broken pipe
ok 1 - kvs watcher gets disconnected on client exit
PASS: t1103-apidisconnect.t 1 - kvs watcher gets disconnected on client exit
not ok 2 - multi-node kvs watcher gets disconnected on client exit
FAIL: t1103-apidisconnect.t 2 - multi-node kvs watcher gets disconnected on client exit
#	
#		${FLUX_BUILD_DIR}/t/kvs/watch_disconnect
#	
# failed 1 among 2 test(s)
```

Did notice a typo a log msg, so re-pushed.

**Comment by chu11** [comment]
hmmm. Hit the connector.local Broken Pipe issue three more times.  I'm guessing I screwed something up.

**Comment by chu11** [comment]
re-pushed.  I think I had to set WAITCREATE on the ```watch_disconnect``` test, otherwise the test can race with a ENOENT being sent back to the caller.  TBH, I'm shocked the test regularly passed on catalyst or that it often passed in travis.  Glad it was caught.

**Comment by garlick** [comment]
@grondo if you concur on my `flux kvs watch` point, freel free to add `merge-when-passing`.

**Comment by grondo** [comment]
>  if you concur on my flux kvs watch point, freel free to add merge-when-passing.

Yeah, I agree with your point about `flux kvs watch`.

I think we have to pause using mergify to merge our PRs because it doesn't seem to be able to auto-close issues mentioned in the PR and issues.

I'll push the merge button manually and verify it auto-closes the issues @chu11 has mentioned in his commits.

**Pull request merged**
