### PR TITLE
libutil: support "infinity" in FSD

### PR DESCRIPTION
**Pull request by grondo**
This PR updates the C and Python interfaces in flux-core to support RFC 23 "infinity" special case.

### CODE REVIEW

**Review by chu11 — DISMISSED** [review]
LGTM (assuming RFC23 update is approved, which I think we agree it will be)

**Comment by grondo** [comment]
Some changes here based on offline feedback from @garlick. It turns out `strtod()` parses case-insensitive `inf` and `infinity` and stopping at the right place. So we do not need to special case `infinity` on the parsing end, all while supporting whatever representations of infinity are supported by `strtod(3)`. I think @garlick will update the RFC 23 changes to stipulate that infinite values SHALL NOT support units, so checking for trailing characters (along with allowing `FP_INFINITE` is the only change needed in `fds_parse_duration(3)`.

On the encoding side, an infinite value is always represented as `infinity`. Let me know if you'd rather `inf`.

**Comment by grondo** [comment]
Updated the fsd unit test to add test vectors proposed in the RFC 23 update.

**Review by garlick — APPROVED** [review]
All looks good to me!

**Comment by grondo** [comment]
Thanks! I've set MWP

**Pull request merged**
