### PR TITLE
wreck enhancements to allow cpu affinity with lua and wrexec fixes along the way

### PR DESCRIPTION
**Pull request by grondo**
The main purpose of this branch was to support per-rank and per-task cpu affinity in the wreck prototype. This is complete, with some basic tests. The basic support is supplied by a new `02-affinity.lua` plugin which uses lua affinity bindings (directly added to source in `bindings/lua/lua-affinity`). The plugin checks 
```
lwj.<id>.rank.<rank>.cpumask
```
(per rank cpumask)  and 
```
lwj.<taskid>.cpumask
``` 
(per task cpumask), And if found calls `sched_setaffinity(2)` with the given mask on the appropriate rank(s) and task(s).

I called the key `cpumask` because it is literally the cpumask passed directly to `sched_setaffinity(2)`.

cpumask can be any of the masks acceptable by `taskset` or linux kernel, e.g. cpus list (0-1,3), hex mask (0xff), or kernel bitstring (00000000,00000001). The cpumask should be placed in the kvs as a string.

Other fixes along the way
 * simple fix for #411, with tests
 * fixed lua bindings always converting a number string to json number on kvs_put
 * The `flux-lua` dir was renamed to `flux`-- flux-specific bindings are now required with `flux.` prefix (the lua was a bit redundant)
 * In addition to lua-affinity bindings add lua-hostlist directly to flux-core source. 
 * In order to make `require 'flux.hostlist'` etc. work, new convenience links are created for lua modules in `.libs` to the parent directory (also required a trick with `-Wl,--defsym` you might see in Makefiles) :disappointed: 
 * various improvements in wrexecd lua plugin interface
 * For testing, added cpus-allowed.lua script, used to create  a new `cpu_set_t` from existing affinity mask to ensure we test with cpus currently in allowed mask. New prereq MULTICORE required for some tests
 * For testing, a slightly undocumented option was added to `flux-wreckrun`: `--pre-launch-hook` which allows wreckrun to be extended with a bit of lua code before launch (used for cpumask testing)

I considered also adding a version of luaposix to flux-core, but I avoided that at this point. The build of luaposix isn't nearly as simple as hostlist and affinity bindings, and recent versions do things like check out a copy of gnu portability library, etc before building. Since lua-posix is a generally available package I didn't think it was quite as important to incorporate it at this time.

### CODE REVIEW

**Comment by grondo** [comment]
BTW, this should wait to be merged until flux-framwork/flux-sched#70 is in or it will break `flux-submit` there.

**Comment by lipari** [comment]
No need to wait.  I just merged flux-sched PR 70.

**Comment by dongahn** [comment]
Wow. What a timely enhancement. 

I probably haven't followed all the discussions, but did you folks also discuss what kind of mapping/binding mechanisms (e.g., policy-based) wreckrun will implement to make use of this capability? The reason I'm asking this is that is would be what we probably want to  match in `flux-submit` as well. If policy-based, some of OpenMP thread binding policies might be interesting to look at. We can use them for process mapping instead of thread mapping, but nevertheless I found some of these polices useful. 

Intel OpenMP runtime has "compact" and "scatter" policy which takes into account the resource hierarchy in the node: https://software.intel.com/en-us/articles/openmp-thread-affinity-control

And OpenMP4 has "spread" which can be also interesting to http://openmp.org/sc13/OpenMP4.0_Intro_YonghongYan_SC13.pdf

All of them would be fairly easy to implement by using hierarchical resource ids, in fact, I recently played w/ hwloc to create a cpumask using this technique and I found hwloc provides almost all of the abstractions I needed.

**Comment by grondo** [comment]
Support for affinity was a direct enhancement requested by @trws for capacitor to allow separation of jobs by CPU affinity in one of the milestones. `flux-wreckrun` doesn't actually use this capability, and I would argue that isn't quite the correct approach long term, but nominally it seemed easy to support for wrexecd (though I found a lot of little issues along the way, thus the large PR), so we are doing it this way for now.

Also, I think @trws plan was to only use the per-rank cpumask for now, but it was easy to add per-task (see the actual [plugin](https://github.com/grondo/flux-core/blob/ec40cc251911ecc37f1433bd85da3e673ab6d746/src/modules/wreck/lua.d/02-affinity.lua)) so I went ahead and included it.

**Comment by garlick** [comment]
I have scanned through this and it looks good to me.  Would @trws like to comment viz a viz the milestone?

**Comment by trws** [comment]
This looks good to me.  The policy support for binding will happen at some point, but having this at the execution service is more than enough to implement it anywhere else in the preparation of the job, and enough for me to make sure that tasks/ranks don't tromp each other when launched with cap.  :+1:

**Comment by grondo** [comment]
BTW, only slightly off topic, but I also made some slight changes to the `env.lua` plugin which instantiates job environment and a test to ensure something like this will work:

**Comment by trws** [comment]
That's interesting, and a good idea. Question on it though, would it make sense to have that in the config namespace? Hm... Maybe not, since this is for jobs rather than instances? Just wondering if it could leverage the config env stuff.



Sent with Good (www.good.com)

________________________________

**Comment by grondo** [comment]
In general it probably could be part of the config namespace, though the `flux config` interface might need a bit of a re-think (ran into some things that didn't work how I thought it should, but pretty minor issues)

However, you'd probably still want to "override" environment at different services, e.g. the job shell might inherit from "default" environment then apply its own modifications, each job would inherit from job service default environment, per-rank environment inherits from job environment, per-task environment inherits from per-rank... I think this would give users a lot more control over their environment than they have now.

This scheme might also apply to other instance "environment" parameters, e.g. current working directory, namespace, etc.

**Pull request merged**
