### PR TITLE
deprecate some libutil classes (cleanup)

### PR DESCRIPTION
**Pull request by garlick**
Two "classes" in libutil aren't used much, depend on json-c, and call `oom()` internally on malloc failure.

**base64_json**  includes functions for encoding/decoding opaque data blobs to/from json-c objects.  It is used by zio.c, iowatcher (lua), and some tests.  `zio_json_encode()` and `zio_json_decode()` were reworked to use base64 directly.  iowatcher now just calls `zio_json_decode()`.  t/kvs/basic.c was reworked to use base64 directly.  Finally the kap test, which uses MPI, isn't driven by the test suite, and still uses deprecated Flux API calls, was dropped.

**getrusage_json** calls getrusage(2) and converts the returned struct to a json-c object.  This was called from two places in the broker, one to implement the "cmb.rusage" request hander, and two, to implement thegeneric "<service>.rusage" request handler for modules.  I combined the two request handlers and pulled in the function.

@dongahn:  on dropping KAP - I know you put a lot of work into this.  I was thinking you may wish to bring it back as part of the flux scalability project at some point.  It needs some updating, but as we were building it but not running it, I was not comfortable modifying since I might break something and never know it.  Better for it to live someplace where it gets run regularly as part of CI.

### CODE REVIEW

**Comment by grondo** [comment]
Oh, nice cleanup!

**Comment by garlick** [comment]
One build failed here
> FAIL: t2000-wreck.t 5 - wreckrun: propagates current working directory

I went ahead and restart that one.

**Comment by grondo** [comment]
Looks like after these changes `Jget_bool()` no longer has any users, maybe it could be removed as part of this PR?

**Comment by garlick** [comment]
Will do.  Yay!

**Comment by grondo** [comment]
Small code coverage drop is only due to error conditions, so merging this one...

**Comment by garlick** [comment]
Thanks!

**Pull request merged**
