### PR TITLE
implement keepalive based module status

### PR DESCRIPTION
**Pull request by garlick**
This PR implements an idea proposed in PR flux-framework/rfc#39, where comms modules send keepalive messages to the broker to communicate state.

The empty zmsg that used to signify EOF from a module is now a keepalive containing state FLUX_MODSTATE_EXITED and an errno if `mod_main()` returned -1.

The initial state of a module is FLUX_MODSTATE_INIT.  When it enters the reactor loop, it alternates between FLUX_MODSTATE_RUNNING and FLUX_MODSTATE_SLEEPING.  A module may perform initializaiton before entering the reactor loop, so it will remain in INIT state while that completes.

There is a symmetrical FLUX_MODSTATE_FINALIZING for handling module shutdown, though this is not used yet in this PR.

The module control API has been updated to pass status through, and `flux module list` now shows module state in a single character 'S' column, similar to `top(1)`.
```
$ flux start -s16 flux module list -r all
Module               Size    Digest  Idle  S  Nodeset
kvs                  2759761 E1FF710    0  R  [0-15]
resource-hwloc       2632716 FE2D6D7    0  I  [0-15]
mecho                2607587 8CADAAC    0  S  [0-15]
modctl               2646041 9E63D51    0  R  [0-15]
connector-local      2636212 16B0722    0  S  [0-15]
wrexec               2614117 51B26F3    0  S  [0-15]
content-sqlite       2622104 A9F69CB    0  S  0
barrier              2621498 849EE8B    0  S  [0-15]
job                  2615625 C815AE6    0  S  [0-15]
live                 2675621 547E780    0  S  [0-15]
$
```

Still todo:
* Have flux module load wait until module leaves init state to respond, and catch a transition directly to FLUX_MODSTATE_EXITED and corresponding errno if initialization fails.  C.f. flux-framework/flux-sched#13
* Do something with FLUX_MODSTATE_FINALIZING (perhaps wire into `flux_reactor_stop()` some way?)
* tests, documentation

### CODE REVIEW

**Comment by grondo** [comment]
Oh, this is really cool.

How is state of modules on multiple nodes handled? I.e. does "R" mean at least one module across the nodeset is running?

I gave the code a whirl and it all just seems to work.

**Comment by grondo** [comment]
Looks like the new `waitfile.lua` tests are failing now. Ugh. I'll poke at that.

**Comment by garlick** [comment]
> How is state of modules on multiple nodes handled? I.e. does "R" mean at least one module across the nodeset is running?

Yeah,  I had to use a kind of dumb heuristic, basically
* if any ranks are in INIT, show I
* else if any ranks are in FINALIZING, show F
* else if any ranks are in RUNNING, show R
* else if any ranks are in EXITED, show X
* else SLEEPING

**Comment by garlick** [comment]
Just forced a push with a small cleanup:
* Make keepalive message functions part of libflux
* Move FLUX_MODSTATE_* defs to (public) module.h.

This stuff needs to be part of the public API so that comms modules that load messaging actor modules (and so on down the hierarchy) can use keepalives for module state also.

**Comment by grondo** [comment]
Sorry, that waitfile test is failing pretty regularly in travis. I'll take a look at it, but I was unable to get a failure running it all night in a c9.io vm.

**Comment by garlick** [comment]
Just pushed some changes which causes `flux module load` to wait until the module leaves the INIT state.  If the module goes directly to EXITED state, and mod_main() returned -1, the error is returned to the command line.  Example:
```
$ flux module load sched plugin=nonexistent
[1456872991.113617] sched.err[0]: nonexistent: not found in module search path /home/garlick/local/lib/flux/modules:/home/garlick/proj/flux-sched/sched
[1456872991.113640] sched.err[0]: failed to load scheduler plugin
[1456872991.113656] sched.crit[0]: fatal error: Bad file descriptor
flux-module: sched: Bad file descriptor
$ echo $?
1
```
Sched might need to preserve its errno value here (ENOENT?), but you get the idea.  This fixes issue flux-framework/flux-sched#13 and should also address flux-framework/flux-sched#134

**Comment by grondo** [comment]
Since this fixes a couple tricky startup and testing synchronization bugs, should we merge early and often? Or would you like to wait for a little more?

**Comment by garlick** [comment]
We could do that.  I feel pretty good about this change set.

**Comment by garlick** [comment]
oops I didn't properly merge multiple status results for `flux module list` in direct mode, now the default.  Please don't merge yet.

**Comment by garlick** [comment]
Just rebased this and fixed up the tests a bit.  If it passes travis it could probably be merged.

**Comment by grondo** [comment]
Great! Merged!

**Pull request merged**
