### PR TITLE
libkz: defer kvs_watch until necessary

### LINKED ISSUE #1419: [splash] wreck loses stdio output on large jobs
From conversation with @trws:

Large (500 node?) jobs that complete successfully and do not have a kz reader (e.g. run with `flux submit` and no `-O file` option) sometimes don't get all output written to the kvs.  After completion, running `flux wreck attach` will consistently hang (even if repeated later), presumably because one or more kz streams were not terminated with an eof flag.

This problem manifests as truncation of output, not lost data in the middle.

Also this behavior predates PR #1411 libkz changes.

### PR DESCRIPTION
**Pull request by garlick**
As discussed in #1420, this PR changes libkz so that the `kz_ready_f` registration does not immediately trigger a `kvs_watch()` on the stream directory.  Instead, it uses chained KVS lookups and continuations to iterate over the stream until the available "blocks" are exhausted.  At that point if EOF is not reached, a `kvs_watch()` is installed as before.  However if EOF is reached, the `kvs_watch()` is entirely avoided.

This should allow `flux wreck attach` to process the output of a completed job without ever using `kvs_watch()`, provided that each stream has reached EOF (which might not be the case until we fix #1419).  Hopefully this is more scalable.

It might also change the timing for the "redirected" case since the `kvs_watch()` calls (with embedded synchronous RPC) will only occur during I/O processing, not during initialization, and possibly more staggered in time.

I haven't tested this yet at scale but it seems to be working in my small tests.  Will try to do some scale testing tomorrow.

### CODE REVIEW

**Comment by garlick** [comment]
I made `lua/t1003-iowatcher.t` a todo for the moment.  The test tries to create an I/O watcher watching a non-directory and expects the iowatcher creation to fail.  That used to happen at `kz_set_ready_cb()` time when `flux_kvs_watch()` was called, which caused a synchronous lookup to occur.  Now that the initial lookup result is handled in a continuation, the users callback will be called, and when it calls `kz_get()`, _that_ will fail.

It's not clear to me looking at the iowatcher implementation whether `kz_get()` errors are checked.  If not, that will need to be fixed and may help us find other reader issues.

Then the test will have to start the reactor and check for error in the reactor callback.
```

**Comment by grondo** [comment]
Sorry you had to deal with that @garlick. Your approach seems good to me

**Comment by trws** [comment]
This looks really good!  How hard would it be to have an option that says "even if it isn't done, don't establish the watchers, just stop" with this change in?

**Comment by garlick** [comment]
> This looks really good! How hard would it be to have an option that says "even if it isn't done, don't establish the watchers, just stop" with this change in?

Probably not hard.  I'll look at that.

**Comment by garlick** [comment]
@trws if you have the output of one of these completed jobs in a KVS somewhere, it would be interesting to know before and after numbers on `flux wreck attach`.

**Comment by grondo** [comment]
Just gave changes to kz iowatcher a quick look and it seems good to me. Just to be clear, new iowatcher callback denotes EOF when both `data` and `err` are `nil`, otherwise if `err` is not `nil`, then an error occurred? (I know sorry about the bad semantics of the original function.)

Just another warning that the fd iowatcher has completely different semantics (e.g. `data` parameter passed to callback is a Lua table, not just a string, etc.) This is because it was based on the old zio code, so I didn't want to bother fixing it yet. Just didn't want to you to be surprised if you went looking there (and hopefully you don't have to.)

Sorry that is all I have time for tonight.

**Comment by garlick** [comment]
Thanks @grondo!

Well that sounds right, or (what I was thinking) was you'd first check `err` and if non-nil, it's an error otherwise, proceed as before.

**Comment by trws** [comment]
Well, the timing results are pretty conclusive.  With this, over ssh, attach on a 400-line output job with 400 ranks takes 0.7 seconds.  The current master version has so far been running for five minutes, and I just got another line out of it, so it might eventually finish?  The last two lines were a minute each in coming.

For one that actually finished reasonably, the current master took about 1.5 seconds on average, this took about 0.5 (again with this version at the disadvantage of connecting over ssh).

In a possibly related note, do either of you know if it's possible we leave watchers around for cancelled or killed `wreck attach` commands? I've noticed long-running instances start to get slow, spending time processing kvs events even when the kvs isn't being actively poked from outside.  Made me wonder if we're somehow leaking watchers when a client dies an untimely death or something (but then again, I'm way past loopy at this point so... hey, another line!

**Comment by garlick** [comment]
> do either of you know if it's possible we leave watchers around for cancelled or killed wreck attach commands? 

In that case where the reactor has gone away and the broker connection dropped, the KVS should get a disconnect message and take care of cleaning out any state for that connection.   To get a count of service side watcher state for the local rank, run:
```
flux module stats --parse "namespace.primary.#watchers" kvs
```

FWIW there is a regression test for this: `t/t1103-apidisconnect.t`

**Comment by garlick** [comment]
Rebased, improved commit messages somewhat, and squashed some incremental development.
I'd vote that this goes in now and further improvements (such as a flag to avoid "following" the stream when EOF was not written) be deferred to another PR.

**Comment by trws** [comment]
We are now up to 9 hours and 46 minutes.  The old version has printed 366 lines.

**Comment by trws** [comment]
Agreed, I can even hack something in for splash short term.

The stat command is telling me there are 740 active kvs watches.   The big flux instance is currently almost unusable, and I'm trying to figure out why.  It's running, it's responding, but its spending *all* of its time in the kvs module processing transactions.  The reason this surprises me is that long-running attach and a wreck ls are the only things running, and it's pegged at 100% of one CPU continually.

**Comment by garlick** [comment]
@chu11, would you mind having a quick look at this and press the button if you find nothing amiss?

The test coverage is somewhat improved from where it was, but commensurate with how much effort I think we want to put into this old stuff (in other words, not quite par).  I think I'm OK with that.

**Comment by garlick** [comment]
Ping @chu11?

**Pull request merged**
