### PR TITLE
rework local connector to be fully nonblocking + mod_main() prototype fix

### LINKED ISSUE #83: api module can block
The API module handles clients connected to a UNIX domain socket.  When this socket becomes readable, the API module executes `zfd_recv_typemask(nonblock = true)` but as noted in zfd.h:
```
 * N.B. The nonblock flag doesn't completely eliminate blocking.
 * Once a message has begun to be read, the recv may block in order
 * to read the complete thing.
```

When a zmq message is received that needs to be sent to a client over the UNIX domain socket, the socket's readiness is not even checked.  `zfd_send_typemask ()` is called which does not have a nonblock flag.

So if a client becomes non-responsive but is still connected to the socket, it can block the API module's single thread.  This could very easily occur, for example, if a process receives a SIGSTOP, or engages in blocking behavior of its own.

### PR DESCRIPTION
**Pull request by garlick**
In this PR the "api" module is renamed to "local-connector", is updated to use new reactor/message interfaces, and is restructured to implement non-blocking management of client (unix domain socket) file descriptors.  In addition, the connector itself now honors FLUX_O_NONBLOCK if specified for its methods backing `flux_send()` and `flux_recv()`.  This fixes #83.

flux_msg_t now has some new functions with unit tests and man pages:
* `flux_msg_encode()` to be used instead of `zmsg_encode()`
* `flux_msg_decode()` to be used instead of `zmsg_decode()`
* `flux_msg_sendfd()` to be used instead of `zfd_send()`
* `flux_msg_recvfd()` to be used instead of `zfd_recv()`

The zfd functions, now removed, were a hold out user of `zmsg_t`, and were designed for blocking operation and hacked to be "a little bit non-blocking".  Gone!

A sharness test `t0007-ping.t` was added along with some enhancements to the `flux-ping` program to move messages through the connector in both directions to exercise the non-blocking client management.

Finally, an unrelated change is `mod_main()` in all in-tree comms modules was updated to use argc, argv style arguments rather than a zhash_t as specified in RFC 5.  (This will require a change to out of tree modules like those in flux-sched; I will submit a PR to flux-sched)

### CODE REVIEW

**Comment by grondo** [comment]
Oh, great improvement! Do the flood ping tests actually end up being good verification that the local-connector module doesn't ever block? Is there a test where you try doing "bad stuff" in the client and ensure you don't block the broker plugin?

I feel a bit bad about this next comment, but...

This probably isn't worth holding up this PR, but at the beginning of a new naming convention (as in `*-connector` here), it might be good to have a bit of group discussion. In this case we'll probably want all future modules of a certain class to follow a similar convention, so we should decide now what that might look like.

My input would be that in a naming schema, the most general name should come first. It isn't that important, but it does have some nice side effects (like in `lsmod | sort` all `connectors-*` would show up together) It also follows naturally that "connector" prefix is the container for all connectors -- or "connector" is the class name, etc. This same convention could apply across other classes of modules/plugins.

This most general name first convention seems to be pretty standard across various projects (think Lua/Python package names, Go packages, etc. With Go you can even have qualifiers including a domain name, e.g.
```go
import {
   "golang.org/x/net/context"
}
```
It would be neat if you could (eventually) load broker modules in this style, e.g. if both LLNL and CEA had a scheduler you could refer to them as `cea.fr/sched` and `llnl.gov/sched`.

Sorry to co-opt this PR for my diatribe, but the new convention for naming connectors got me started...

**Comment by garlick** [comment]
The flood ping tests are sort of a first order verification that we aren't losing messages while exercising the non-blocking reactor logic.  The `flux ping --batch` mode where responses are not processed until all the requests have been sent is bad behavior of a sort that would have deadlocked before.  I.e. a blocked write(2) in the api module would have prevented the api module from read(2)ing all of the requests.  I did verify (by adding some debug logging) that the flood ping "workload" does cause a lot of EWOULDBLOCKs in both directions.  More tests could be added. I would lean towards covering `flux_send()` and `flux_recv()` in nonblocking mode next; although that might be best added in conjunction with a reactor "handle watcher".

Regarding naming - the other hierarchy we might consider would reflect modules loading modules.  For example, if "sched" loads a "backfill" module, a (future) recursive `flux module list` might show that as "sched.backfill".  RFC 5 was headed in this direction, though I think there may be a few details to iron out.  RFC 5 is probably the place to put down any naming conventions we agree on.  I am fine with a general-to-specific hyphenated topical convention in parallel to the module loading one.  Should I tentatively rename "local-connector" to "connector-local"?

**Comment by grondo** [comment]
> Should I tentatively rename "local-connector" to "connector-local"?

Well I'd prefer that slightly, however it seems like a lot of work to make that change.
If however this convention will propagate to other modules it might be nice to make the change now.
If you think I'm being unreasonable I'm fine keeping it as is and delaying any name change until such time that it makes sense.

**Comment by garlick** [comment]
No it seems reasonable and it won't be a lot of work.  I'll go ahead and do that.

**Comment by garlick** [comment]
Just forced a push with local-connector renamed to connector-local.

**Comment by grondo** [comment]
Looks good! Also checked out on my c9.io image. Merging...

**Pull request merged**
