### PR TITLE
python: Several fixes for the bindings

### LINKED ISSUE #793: EAGAIN experienced when using Python KVS bindings
The python bindings are still using the json-c interface.  This is unnecessarily complicating the python bindings (by requiring a custom python interface to json-c), but it is also now breaking on the latest version of flux-core.  Many KVS operations now cause an `EnvironmentError` with `errnum == 71 (EPROTO)`.

Switching to the latest KVS interface fixes the `EPROTO` issue.  I'm still working out other issues.  Once I have those fixed, I can submit a PR.  In the meantime, any thoughts on why I'm getting `errno == 11 (EAGAIN)` from the KVS?

### PR DESCRIPTION
**Pull request by SteVwonder**
Several python binding fixes wrapped into one PR:
- Add constants for FDWatcher
- Switch kvs.py to use the latest KVS interface (remove use of json-c)
- Add interface to JSC

Fixes #793

### CODE REVIEW

**Comment by SteVwonder** [comment]
Hold off on merging this until we figure out the EAGAIN issue in #793.  Sorry, was a little too quick to push.

**Comment by trws** [comment]
This looks good to me.  I may pop in a wrapper to abstract some of this stuff and propagate it to other parts of the bindings, but I'd say LGTM.  Any concerns @garlick, @grondo?

**Comment by grondo** [comment]
No concerns here!

**Comment by garlick** [comment]
It's probably pretty safe, but is there a cleaner way to import those constants FLUX_POLLIN, FLUX_POLLOUT, FLUX_POLLERR?  As a general rule duplicating constants in the bindings is a potential source of future unhappiness.

**Comment by SteVwonder** [comment]
@garlick: that is a great point.  I had to pull in quite a few constants.  I don't think I can do anything about the preprocessor macros/defines (e.g. JSC_STATE_PAIR), but something should be able to be done for the enums (e.g. J_SUBMITTED, FLUX_POLLIN).

@trws: do you have any experience with this?  I was unsuccessful yesterday in googling how to handle enums with py-cffi. I noticed that the enums are present in the generated .c files, but I am unsure how to access them.  Taking FLUX_POLLIN for example, it appears in `_core.c` in the `_cffi_enums` struct, but it is unclear how accessing that works.

**Comment by trws** [comment]
I'll look into it.  There wasn't (to my extreme discomfort) a good way to do it when I wrote them, but the ffi interface may have grown one since.


---
Sent from Boxer | http://getboxer.com<http://bxr.io/PBI3C>

On September 7, 2016 at 10:35:17 AM PDT, Jim Garlick <notifications@github.com> wrote:

It's probably pretty safe, but is there a cleaner way to import those constants FLUX_POLLIN, FLUX_POLLOUT, FLUX_POLLERR? As a general rule duplicating constants in the bindings is a potential source of future unhappiness.

-

**Comment by trws** [comment]
There is a way, but it involved generating new externed C values, and there were issues with parsing the constant expressions in some of our enums that broke that stuff.  I'll take a look at it this afternoon, I have an idea that might work, but I'm not sure if it will work with the auto generation stuff.


---
Sent from Boxer | http://getboxer.com<http://bxr.io/PBI3C>

On September 7, 2016 at 11:26:09 AM PDT, Stephen Herbein <notifications@github.com> wrote:

@garlick<https://github.com/garlick>: that is a great point. I had to pull in quite a few constants. I don't think I can do anything about the preprocessor macros/defines (e.g. JSC_STATE_PAIR), but something should be able to be done for the enums (e.g. J_SUBMITTED, FLUX_POLLIN).

@trws<https://github.com/trws>: do you have any experience with this? I was unsuccessful yesterday in googling how to handle enums with py-cffi. I noticed that the enums are present in the generated .c files, but I am unsure how to access them. Taking FLUX_POLLIN for example, it appears in _core.c in the _cffi_enums struct, but it is unclear how accessing that works.

-

**Comment by trws** [comment]
Wow, so, if we're willing to bump the revision of cffi a few versions, I can get all of the enums (except maybe one nasty one) to be extracted automatically, and also clean up and speed up the callbacks so they don't require runtime generation of executable code regions on the heap.  I'll put up a PR with the enum part at least, and probably a separate one that has the callback rework.

**Comment by garlick** [comment]
> if we're willing to bump the revision of cffi a few versions,

Here are the versions we have around

* TOSS 3: python-cffi-1.5.0-2.ch6 (locally rolled for root)
* TOSS 2: python2.7-cffi-1.1.2-1.ch5.3  (locally rolled in /opt)
* Ubuntu 16.04.1 LTS: 1.5.2-1ubuntu1 (from canonical) my desktop - maybe others don't care

orchestrating an update may be tricky if you need > those versions.

**Comment by trws** [comment]
Actually, that should be good at least as far as toss3 is concerned.  I 
think the most recent thing I was looking at was added in 1.5, the enum 
stuff might be good on both, but I'll have to test it.

**Pull request merged**
