### PR TITLE
t2204-job-info: Fix racy tests

### LINKED ISSUE #2850: t/t2204-job-info: Some tests are racy
While adding some tests, I realized that some of the tests in `t2204-job-info` are racy:

```
        jobid=`flux mini submit -n5 hostname` &&                                                                                                                                                                   
        echo $jobid > nodecount4.id &&                                                                                                                                                                             
        flux job wait-event $jobid clean >/dev/null &&                                                                                                                                                             
        obj=$(flux job list -s inactive | grep $jobid) &&     
```

after the `flux job wait-event`, there's no guarantee that the inactive has been seen by the job-info module yet.  Should do some type of loop & wait kind of function.

Should be done after PR #2849 given conflicts that are there.

### PR DESCRIPTION
**Pull request by chu11**
Fix tests that could be racy.  It is possible for the job-info module
to have not yet seen the state change by the time "flux job list" is
called, so wait for that state change to be seen before continuing
in the test.

Fixes #2850

### CODE REVIEW

**Comment by chu11** [comment]
note to self: #2831 and #2858 likely need to be fixed if this goes in first

**Comment by grondo** [comment]
I know this has been brought up before, but this spin-and-wait we need to use with job-info is already used in various tests everywhere. Is there maybe a service job-info can provide to fix this issue in general, rather than having while-check loops sprinkled around?

**Comment by chu11** [comment]
> I know this has been brought up before, but this spin-and-wait we need to use with job-info is already used in various tests everywhere. Is there maybe a service job-info can provide to fix this issue in general, rather than having while-check loops sprinkled around?

The other day I brought up having the `list-id` service perhaps wait for a state as well as an ID being legal.  We didn't consider it high priority, but perhaps its worth adding to the todo list.  I'll create an issue.

**Comment by grondo** [comment]
Have to manually rebase since mergify config changed on master

@mergifyio rebase

**Comment by chu11** [comment]
Thanks!

**Comment by chu11** [comment]
re-run asan, it hung

**Pull request merged**
