### PR TITLE
fix GitHub project license detection

### PR DESCRIPTION
**Pull request by grondo**
#3043 was tagged in the v0.18 milestone, so here's a PR with the suggested fix.

It doesn't have to get into the release, but just in case we do want it - here you go.

### CODE REVIEW

**Comment by grondo** [comment]
I just force-pushed a change to move `COPYING` to `LICENSE`, and additionally remove the empty `NEWS` file now that #3090 is merged.

However, as @garlick noted in that issue, our license boilerplate says
>  (c.f. AUTHORS, NOTICE.LLNS, COPYING)

Do we actually need to keep the COPYING link, or should I bulk change that to LICENSE? (Would that even be allowed?)

**Comment by grondo** [comment]
Sorry for the noise. Once `NEWS` was removed, it became apparent that `NEWS.md` was never included in our release tarball. Also `NEWS` was still referenced in `configure.ac`. I've added a couple commits to fix these issues.

**Comment by garlick** [comment]
Personally I think we can ignore the copyright header ref for now.

**Comment by garlick** [comment]
Kicked off the workflow again - looks like flux-sched test had failed in setup due to downloading probs.

**Comment by grondo** [comment]
Thanks!

**Comment by grondo** [comment]
Thanks!

**Pull request merged**
