### PR TITLE
libcompat: cleanup, drop dead and little-used code

### PR DESCRIPTION
**Pull request by garlick**
In another PR I was moving some deprecated KVS functions to libcompat and noted that some libcompat code was no longer used, some had only one user and was simple to eliminate, and some headers included from compat headers were wrong.  That is cleaned up here.

In addition, the single compat.h include file is a problem if you only want one piece of libcompat, and  other pieces conflict.  The specific problem I ran into was compat.h bringing in json-c, but needing to use a libcompat KVS function from code that used jansson.  This PR drops compat.h and makes the individual headers able to be included directly

### CODE REVIEW

**Comment by grondo** [comment]
restarted a build that failed with #1169

**Comment by grondo** [comment]
Actually, maybe the `f:recvmsg()` lua function is also dead code and can be removed?

**Comment by garlick** [comment]
OK, let me see if that breaks anything.

**Comment by garlick** [comment]
It's actually used by `t/lua/t0001-sendrecv.t`, so I'd assume we want to leave it in?

**Comment by grondo** [comment]
Hm, code coverage appeared to indicate it wasn't called.
We can leave as is for now, and I'll merge this and maybe look into it later.

**Pull request merged**
