### PR TITLE
Issue1040: Update broker attribute names

### PR DESCRIPTION
**Pull request by chu11**
Update broker attribute names given recent additions of ```tbon.endpoint``` and ```mcast.endpoint```

### CODE REVIEW

**Comment by garlick** [comment]
Maybe "endpint-uri" should just be "endpoint" (since endpoints in zmq parlance are URI's?)

Were you thinking about removing the old ones in favor of expanding the new ones (tbon-request-uri vs tbon.endpoint, event-uri vs mcast.endpoint?)

**Comment by chu11** [comment]
I kept the ```-uri``` mostly out of legacy.  If we do axe the ```-uri```, we would probably want to change ```snoop-uri```, ```local-uri```, and ```parent-uri``` too.

Personally, I like the idea of being able to see what the user original input via format specifiers vs. what was eventually expanded out.  Thus having ```tbon.endpoint-uri``` vs just expanding it out and replacing ```tbon.endpoint``` with the expanded out value.  But perhaps that's just me.  I will cave based on peer pressure :-)

**Comment by garlick** [comment]
snoop-uri is gone already right (in e1e512f3f16f0455318dbe3751cbb4cc4cd1fce6)?

Maybe we need more peers to chime in here :-)  At runtime I kind of think the actual values are more interesting than the symbolic values from the command line.

I think i'd be for dropping `-uri` suffix if the word "endpoint" is there, except for `local-uri` which is a connector uri not a zeromq endpoint.

My feelings aren't too strong on these things, so if you feel like it should be the other way, I'm willing to go with it.

**Comment by chu11** [comment]
Ahhh, ```snoop-uri``` is still lingering in the documentation.  I'll just add a patch to remove it.

**Comment by chu11** [comment]
Realized this when updating the manpage to remove ```snoop-uri```.  In my mind, I see attributes that users set (e.g. ```persist-directory```) and attributes they don't set (e.g. ```session-id```).  So I guess in my mind I viewed the need to split it up ```tbon.endpoint``` and ```tbon.endpoint-uri``` to maintain that split.  But perhaps my thinking is wrong.  Maybe there are other "in & out" attributes.

**Comment by garlick** [comment]
Some attrs track dynamically changing values too, like some of the content ones.

Just thinking pragmatically, would it be better to have one attribute that represents the broker command line rather than separate attributes for the user setting versus the actual for every attribute?

FWIW I generally think about these attributes in the same way I think of kernel sysctl.  Possibly it would be worth examining that metaphor in more detail and see if there are some lessons/rules we want to carry into flux.

Also, just for reference, we have #555 which calls for a rework of the internal (broker) attribute interfaces.  I kind of like the interface from libflux but the internal interface seems excessively clunky.

**Comment by grondo** [comment]
> Just thinking pragmatically, would it be better to have one attribute that represents the broker command line rather than separate attributes for the user setting versus the actual for every attribute?

I was just going to suggest the same thing. I think having the broker cmdline available in the session would be useful in other ways as well. A good idea IMO

**Comment by grondo** [comment]
Additionally, if the attribute was reset with `flux setattr` then the "user setting" value would be out of sync with the actual value, unless you set both (?) which seems to be unnecessary and confusing. However, a cmdline attribute would still be valid, obvious, and perhaps useful.

**Comment by chu11** [comment]
I like the idea of the broker command line as a attribute.  I'll adjust this PR but make another issue for that feature.

**Comment by chu11** [comment]
fixed up with discussed changes.  codecov diff missing coverage is just missed error messages.

**Comment by garlick** [comment]
Thanks!

**Pull request merged**
