### PR TITLE
NEWS.md: add release notes for v0.51.0

### PR DESCRIPTION
**Pull request by grondo**
As always, feel free to push additions or changes directly here.

I preemptively added #5237 and #5236.

### CODE REVIEW

**Comment by grondo** [comment]
Excellent, thanks!

**Comment by grondo** [comment]
Rebased on master and removed a couple duplicate entries.

**Comment by grondo** [comment]
Ok, if someone wants to approve we can merge this PR and tag the release. @cmoussa1 or @chu11 want to have an editing pass? Thanks!

**Comment by garlick** [comment]
oops - sorry I had added some entries, then commented about them in the wrong PR.  And it sounds like I added dups.  I shouldn't do stuff before coffee!

**Comment by grondo** [comment]
Great! Setting MWP and will tag once this lands!

**Pull request merged**
