### PR TITLE
KVS more oom() fixes

### PR DESCRIPTION
**Pull request by chu11**
These are fixups for two remaining ```oom()``` paths left in the KVS.  These were trickier and required some additional logical changes, so I wanted to put them in another PR.

In ```wait_runqueue()```, the primary change that had to occur to return an error to the user is that either all of the elements would be copied off of the queue, or none of them.  We can't have an error occurring in the middle while we remove elements off one queue and put them on another.  There's no way to get back to what you had before.  Performance wise, this is effectively a change from 2 loops to 3 loops.

There are several catastrophic-like scenarios in the main KVS code if ```wait_runqueue()``` fails.  I chose not to ```assert()``` them.  But maybe I should have.  I went back and forth on it.  Dunno what others might think.

In ```fence_merge()``` there was a similar issue of how to deal with an error in the middle.  In ```fence_merge()```, originally fence names & operations were modified while iterating through fences.  So if an error occurred at some point, how do you get back to what was there before?  The function has been modified to make copies, modify those copies, and if everything succeeds, then store the result.  So there are some extra allocations now.

In ```commit_mgr_merge_ready_commits()```, there was an issue of how to deal with a commit entry on a queue that was popped off, but what if you can't push it back on due to ENOMEM.  Through use of the ```zlist``` iterators, I can just remove the pop & push altogether, which removes any chance of an ```oom()```.  I think using the iterators and removing elements on the zlist was not allowed before (which is probably why the function was written that way), but in newer zlists it is.

I ran this through ```soak.sh -j 1000``` on master and the branch on hype2, and the performance was actually faster on the branch.  So I think we can consider it basically a wash.  The numbers are comparable to what was in PR #1105.

And with that, no more ```oom()``` in the KVS.

### CODE REVIEW

**Comment by garlick** [comment]
Great!  OK, I've run through these changes once and I would like to run through them again in more detail when I get to work.  One thing to do is to walk through these paths keeping in mind the semantic guarantees we make to KVS users - see 3 items at the top of this wiki page:

https://github.com/flux-framework/flux-core/wiki/kvs

and see if any invariants are violated in the error cases.  It would be desirable to return an error to the user, or exit the module's main, or assert rather than silently violate one of these guarantees.

As @grondo noted earlier, the comments are very helpful.

**Comment by chu11** [comment]
@garlick Ahh, I had forgotten about the guarantees.  I'll go through those to think about if asserting would be better in certain error cases.

**Comment by chu11** [comment]
I'll want to go through things line by line, but going through the code, I think the current error handling maintains the guarantees (although the comments need to be clarified or outright fixed).

```setroot_event_cb()``` - for the most part, if anything cache related fails, it's not a big deal.  We have the new root and will still set the new root (via ```setroot()```).  If the new root is not cached, later lookups will have to load the root from the content store.  Perhaps that root load could fail and the user could get an error, but consistency is still maintained.

error while commiting - I think virtually any error (including where the user will never get a response or error) is safe.  ```setroot()``` is only called at the end of a successful commit, so the root would never updated.  So consistency is maintained.  Worst is some data has been stuffed in the cache, but if those entries aren't dirty, they will be reclaimed later.

error processing watchlist - again I think consistency is maintained.  While callers may miss values, they never get an older one.

**Comment by garlick** [comment]
Thanks for that @chu11 - just looked through again and didn't spot any problems.  LMK when you think this is ready.

**Comment by chu11** [comment]
Cool.  Found one additional error path that I had missed before, so trying to work it into this PR as ```wait_runqueue()``` effects it.

**Comment by chu11** [comment]
repushed, cleaned up/fixed a lot of comments on tricky parts.  Main difference from original PR set of patches is I allow an error from ```content_store_completion()``` to propagate to the caller when a synchronous call is made.

In several locations, when a cache entry is missing or invalid, I had to come up with an errno setting to propagate to a caller so they can output an error message.  I decided on ```EFAULT```, which seems like the right one to set.  But maybe there's a better one?

Also, acknowledging issue #1130 remains in this PR.  I will cleanup in a later PR everywhere in KVS.

**Comment by garlick** [comment]
On EFAULT: well,  it might be good to punt with something that doesn't imply memory problems so someone doesn't begin chasing one of those unnecessarily.  I dunno, maybe EINVAL works here?  It's hopefully not going to be a common code path so probably not worth wasting too much energy on.

Regarding #1130 IMHO we should fix those up in this PR before merging if there are any.  That will avoid some extra churn in the history.

**Comment by chu11** [comment]
I think ```EINVAL``` is used in some places in flux-core, so I wanted to avoid that one.  I think it's basically down to using a half-sensible one that could be confused for being a real problem (e.g. ```EFAULT```) or using one that makes no sense (e.g. ```ENODEV```).  Guess it'll be confusing either way.

I'll go ahead and cleanup #1130 then.

**Comment by garlick** [comment]
Yeah... hmm, how about EBADSLT (Bad Slot).  That sort of vaguely fits.

**Comment by chu11** [comment]
Ahh, I only looked in ```errno-base.h```.  ```EBADSLT``` sounds pretty good.

**Comment by grondo** [comment]
What about ENOTRECOVERABLE? You just need to be able to document what exactly went wrong for a given errno returned by function call failure (and differentiate between different failure states). Just a suggestion, I'm not advocating either way.

BTW, I did notice in this place and others a pattern of
```
if (failure) {
   errno = EBADBADNOTGOOD;
   goto fail;
...
fail:
   free_something();
   return -1;
```

If the function(s) between the `fail:` label and return reset errno then the actual errno set in the failed conditional will not actually get returned to the caller.

**Comment by garlick** [comment]
ENOTRECOVERABLE is nicely generic, yet laden with sadness.  I like it!

But EBADBADNOTGOOD would be better.

**Comment by chu11** [comment]
@grondo Doh!  You're right, I totally missed that.  Seems in most places we do ```saved_errno```.

**Comment by chu11** [comment]
Just pushed an update.  Chose ```ENOTRECOVERABLE``` over ```EFAULT```, but also used a ```ENODATA``` in one location, b/c I think it made more sense there.

Fixed up the bad assert usage per #1130.

Fixed up the potential loss of errno when calling cleanup/error paths.  There are a few locations where it may have not been 100% necessary to do a ```saved_errno``` fix, but did so for consistency with other functions.

I suspect the diff coverage will even be worse now, with a ton of extra ```saved_errno = errno``` lines all over the place now.

**Comment by garlick** [comment]
> Fixed up the potential loss of errno when calling cleanup/error paths. There are a few locations where it may have not been 100% necessary to do a saved_errno fix, but did so for consistency with other functions.

I don't mean to be nit picky, but this is not a style I would want to propagate for the sake of consistency, especially in cases where `saved_errno` has to be set in all error legs of a long function because it's unconditionally restored in a single return path.  Best to minimize and localize its use, if possible.

**Comment by chu11** [comment]
@garlick Fair enough.  I did this in only one place, and it ended up I could just remove the "goto done" path in its entirety.  Just re-pushed.

**Comment by chu11** [comment]
actually, what's people's opinions on the ```saved_errno``` usage.  I was programming under the "you can't trust any other function to not change errno" assumption.   I suppose we can trust ```free()```, so I added one more fix.  But what about something like ```json_decref()```.  It doesn't change ```errno``` today, but this isn't a posix function, I can't speak for tomorrow.

**Comment by garlick** [comment]
I'm fine with what you have here, especially if that one idiom mentioned above is avoided.  Just wanted to put in $0.02 for not going overboard.

**Comment by grondo** [comment]
Sorry if my comment had you unnecessarily running around fixing things that don't need to be fixed!

If you want to remove some code duplication, a common idiom I've seen is to set `saved_errno` or `errnum` before a set of conditionals that would all return the same errno, (e.g. for ENOMEM, you'd do

```C
saved_errno = ENOMEM;
if (alloc failed)
   goto out;
/* more code */
if (another alloc failed)
   goto out;
```

This approach could reduce total LOC and duplication in fence_create and cache_get_stats for example. It is not a big deal at all and I certainly don't have a problem with the current code.

**Comment by chu11** [comment]
hmmm, hit a stalled build after ```PASS: t0017-security.t 35 - dispatcher delivers kvs.setroot event to owner connection```. First time I've seen it on this PR.  I'm assuming the issue is as discussed in PR #1125, restarting it.

**Comment by grondo** [comment]
@chu11, sorry about that, a timeout as suggested by @garlick has been added to #1125 -- however I'm still hitting timeouts in other places in that PR, so it is stuck for now...

**Comment by chu11** [comment]
re-pushed, squashed minor fixes, rebased to master

**Pull request merged**
