### PR TITLE
job-ingest: switch to v1 schema

### PR DESCRIPTION
**Pull request by garlick**
This PR sets the default job schema to the one @SteVwonder created for RFC 25.  This ensures that jobspec not conforming to v1 constraints is rejected at ingest, rather than later by the scheduler.

It actually leaves the generalized schema in the tree, and adds schema=PATH validator=PATH options to the job-ingest module so that tests can choose a different schema or validation script.  For example, tests that validate the examples from RFC 14 need to use the generalized schema, and the sched simple has a test that ensure the sheduler rejects some jobspec that is not valid v1.

In addition, there was one last minute decision in jobspec v1 that didn't make it into `flux jobspec srun`, so that's fixed here.

I think this might be a bit too much change to propose to throw in our 0.13.0 tag.  Let's save this for the next one.

### CODE REVIEW

**Comment by dongahn** [comment]
Just curious. Are there cases where a non V1 compliant jobspec can be scheduled by flux sched and executed? Would this disallow for these jobspecs to be tested as well?

**Comment by garlick** [comment]
I don't know the answer, but if there are some in flux-sched tests,  and this lands, then they will need to use a similar trick as the one proposed above for `t2300-sched-simple` (reload ingest module with the alternate schema).

Since the shell and potentially other places like @cmoussa1's sqlite db need to parse jobspec, I think it helps us move forward to agree on the subset we are all working on and my understanding was that was v1 for now.

**Comment by grondo** [comment]
Thanks for doing this!

It would be nice if the schema could be loaded by name, `schema=name` and a search path is used. However, I guess there is more work to be done here -- allowing multiple validators (potentially multiple schemas as well), and this solves a real problem for now.

Since the validator can be shut down and restarted, I wonder if allowing validators to be added and removed at runtime is the right long term plan. This would open the door for a loaded scheduler to register a validator at runtime...

**Comment by dongahn** [comment]
> Since the shell and potentially other places like @cmoussa1's sqlite db need to parse jobspec, I think it helps us move forward to agree on the subset we are all working on and my understanding was that was v1 for now.

Yes, I agree that having the subset definitely helping us move forward. 

I am coming from the angle of testing. If someone (e.g., scheduler policy writers/researchers) wants to use a more advanced jobspec to test their scheduler-related policies, it would be good to have a way to test this with the rest of flux-core. If there is an bypass option for the schema check, it seems that can go a long way towards supporting it.

**Comment by dongahn** [comment]
> Since the shell and potentially other places like @cmoussa1's sqlite db need to parse jobspec, I think it helps us move forward to agree on the subset we are all working on and my understanding was that was v1 for now.

For @cmoussa1's sqlite db work, he can potentially use `libjobspec` in flux-sched to make it more future proof for jobspec version churns.

**Comment by garlick** [comment]
> For @cmoussa1's sqlite db work, he can potentially use libjobspec in flux-sched to make it more future proof for jobspec version churns.

We don't have access to libjobspec in flux-core, but we can do something similar in C if necessary.

**Comment by dongahn** [comment]
Yes. I think it depends on where the bank/accounting code should reside. We should discuss this once he explore this space. I think I have this codesign as a task in my plan doc.

**Comment by garlick** [comment]
Finally addressed a `make dist` issue here, so this might be ready for a look.

In addition to updating to the RFC 25 validator schema, this PR also re-syncs the RFC 14 jobspec examples used as test inputs, and brings in the new examples from RFC 25.

> It would be nice if the schema could be loaded by name, schema=name and a search path is used. However, I guess there is more work to be done here -- allowing multiple validators (potentially multiple schemas as well), and this solves a real problem for now.

Sorry, wasn't feeling very creative on the bigger picture here.   I went ahead and added #2049 to the next exec project board.

**Comment by garlick** [comment]
Thanks!

**Comment by grondo** [comment]
Ready for merge?

**Comment by garlick** [comment]
Yes please :-)

**Pull request merged**
