### PR TITLE
experimental: set UTF-8 locale if LC_ALL is empty or set to C/POSIX

### PR DESCRIPTION
**Pull request by grondo**
This is an experimental "fix" for a problem we've been running into with LC_ALL=C.
The latest result of which can't be worked around (#3124, cut and paste fails for F58 JOBIDS).

In `flux(1)` we can check for the current LC_ALL setting with `setlocale(3)`. If this value is empty, or set to "C" or "POSIX", then attempt to switch to "C.UTF-8" or "en_US.UTF-8". If either of these works, then export the setting in the environment.

At least smoke testing, this seems to work. If the approach seems ok then I can write some simple tests.

```
 grondo@asp:~/git/flux-core.git$ locale
LANG=C
LANGUAGE=
LC_CTYPE="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_COLLATE="C"
LC_MONETARY="C"
LC_MESSAGES="C"
LC_PAPER="C"
LC_NAME="C"
LC_ADDRESS="C"
LC_TELEPHONE="C"
LC_MEASUREMENT="C"
LC_IDENTIFICATION="C"
LC_ALL=C
 grondo@asp:~/git/flux-core.git$ src/cmd/flux env locale
LANG=C
LANGUAGE=
LC_CTYPE="C.UTF-8"
LC_NUMERIC="C.UTF-8"
LC_TIME="C.UTF-8"
LC_COLLATE="C.UTF-8"
LC_MONETARY="C.UTF-8"
LC_MESSAGES="C.UTF-8"
LC_PAPER="C.UTF-8"
LC_NAME="C.UTF-8"
LC_ADDRESS="C.UTF-8"
LC_TELEPHONE="C.UTF-8"
LC_MEASUREMENT="C.UTF-8"
LC_IDENTIFICATION="C.UTF-8"
LC_ALL=C.UTF-8
```

:shrug:

### CODE REVIEW

**Comment by garlick** [comment]
LC_ALL seems to be unset in Ubuntu.  Would this mean that flux will always clobber the system's configured locale?

Would the fix still work if it left LC_ALL alone if unset?

**Comment by grondo** [comment]
Hm, good point. I wonder if what we really want to set is `LC_CTYPE`?

I guess the real question is if we should mess with the locale at all?

**Comment by grondo** [comment]
After reviewing, I think you're right @garlick. We should not set `LC_ALL` if it is unset. If unset, we should try setting `LC_CTYPE`((I'll experiment to see if this is enough to fix the copy/paste issue). If LC_ALL is set and set to `C` or `POSIX`, then "update" it to `C.UTF-8` if available (maybe falling back to `en_US.UTF-8`, though I hate to be US-centric there...)

**Comment by garlick** [comment]
> That is, if we want to try to workaround the issue using flux(1)

What would be the downside of emitting f instead of ƒ in F58 job ID's if LC_CTYPE (or appropriate var) is C or POSIX?

I honestly do not know enough about this locale stuff to have an opinion.  It seems like it's one of those hard to learn through google topics.

**Comment by grondo** [comment]
I think the only downside is checking an environment variable each time a
jobid is emitted. Perhaps also a confusing difference in command output in
different environments.

At least the environment or locale check would only have to be done in one
place in the code. The performance impact of the env check will probably be
negligible compared to base58 encoding.

This would effectively make "f" the defacto prefix on TOSS due to LC_ALL
set to C on all clusters. It also sadly/(happily?) makes all the recent
changes to Python code to work in locale C superfluous.

**Comment by garlick** [comment]
> This would effectively make "f" the defacto prefix on TOSS due to LC_ALL
set to C on all clusters. It also sadly/(happily?) makes all the recent
changes to Python code to work in locale C superfluous.

I guess the question is what is good behavior for applications/middleware.  If TOSS/sys admins are setting `LC_ALL=C` for a _reason_, and we reset it to something else (not only for our tools, but for all jobs), are we being impertinent?

Also, I wonder why they do that, and if they would be open to changing it to C.UTF-8 or en_US.UTF-8?

One other data point: on raspbian (bionic),  if I set the default locale to en_US.UTF-8 in `raspi-config` and reboot, locale shows `LANG=en_US.UTF-8`, but `LC_ALL=C`.  I wonder what's up with that?

To be clear, I would like the outcome to be that we have access to a rich character set in our tools.

**Comment by dongahn** [comment]
> This would effectively make "f" the defacto prefix on TOSS due to LC_ALL
set to C on all clusters. 

We can also work with TOSS team to change LC_ALL to support this? If copy and paste are supported more nicely, I thought using ƒ gives an extra esthetic point. At least this appeared modern as a next-gen SW product when I tried it.

Anyway, while working with early users, I thought a downside with non numeric encoding would be we can easily lose ordering information. It wasn't immediately obvious where the highest priority jobs are displayed in `flux jobs` displays (top vs. bottom). If the 64bit integer FLUID, this would have been a bit more obvious.

**Comment by grondo** [comment]
> I guess the question is what is good behavior for applications/middleware. If TOSS/sys admins are setting LC_ALL=C for a reason, and we reset it to something else (not only for our tools, but for all jobs), are we being impertinent?

Oh yeah, that is correct. I had embarrassingly lost sight that this change would affect all jobs as well as the shell in which the user is interacting with Flux. (Though I'd be less concerned about the "system" default locale and more concerned about overwriting user's chosen locale -- they must have used env vars for these things for a reason)

Additionally, a change like this wouldn't even "fix" the most common case -- interacting with the system instance from a login shell.


>  It wasn't immediately obvious where the highest priority jobs are displayed in flux jobs displays (top vs. bottom). If the 64bit integer FLUID, this would have been a bit more obvious.

Agreed, though the FLUIDs do not actually encode job priority so the integer ID may be misleading (it will also be more and more difficult to "parse" by sight as the 64bit numbers get larger). It might be better to add a field to flux-jobs to display the desired information. Also, I believe the base58 digits are ordered such that a FLUID in F58 will lexicographically sort in the same order as the number it represents (at least in C and C.UTF-8 locales, other locales may sort `a` and `A` before `b` and `B`, i.e. non-case sensitive).

**Pull request closed without merging**
