### PR TITLE
implement scalable reduction for wireup protocol

### PR DESCRIPTION
**Pull request by garlick**
This PR should speed up the "hello" protocol executed during wireup a little bit.
The old protocol was for every node to send a small message directly to rank 0.
Once all the messages were received, wireup was complete.

The new protocol uses TBON topology-informed reduction to reduce a count.  Once the count reaches the target size wireup is complete.

I guess this is also another simple example of how the reduction handle works.

See long comment in ddc83ef

### CODE REVIEW

**Comment by grondo** [comment]
Nice work!

**Comment by grondo** [comment]
Is this one ready to merge, or were you still investigating the hello reduction functionality?

**Comment by garlick** [comment]
Still working on it - let's hold off a bit.

**Comment by garlick** [comment]
I had noted a problem with this PR where the timeout values were not being calculated properly in the reduction handle.  The topology information was used to scale the timeout based on the level in the TBON and the topology was read using the wrong attribute interface for broker-resident services.

I decided the scaling of timeout values was counter-intuitive for the user and ought to be the user's responsibility to set up if it is needed, and so removed it.

I also rebased on current master, and now I think it's ready for merge consideration.

**Comment by garlick** [comment]
Sorry, just pushed one last change to allow the HWM to be set via attribute.  That allows reduction to be turned off completely for performance comparisons, e.g.
```
$ srun [options] flux start -o,-Shello.hwm=0,-Shello.timeout=0,-Slog-stderr-level=6 /bin/true
```

**Comment by grondo** [comment]
ok, this all looks fine to me of course. Merging.

**Pull request merged**
