### PR TITLE
libkvs/eventlog: drop typedefs that violate RFC 7

### PR DESCRIPTION
**Pull request by garlick**
I've been sitting on this for a while, moving it around between pull requests I've been working on.  Maybe better to just submit standalone rather than keep withholding it.

### CODE REVIEW

**Comment by chu11** [comment]
looks good, but just need to update ```doc/man3/flux_kvs_eventlog_create.adoc``` too

**Comment by garlick** [comment]
Thanks, I'll fix that.

**Comment by chu11** [comment]
Looks good to me.  One nit comment now that I read the manpage entry.  Should the length macros like ```MAX_KVS_EVENT_NAME``` be renamed?  It seems weird that the name begins with MAX, it should begin with FLUX_KVS or KVS instead?

**Comment by garlick** [comment]
Good point.  I'll fix that too - hang on.

**Comment by garlick** [comment]
OK, that's fixed and squashed.  Thanks for catching that stuff @chu11.  I was being a little sloppy.

**Comment by garlick** [comment]
Thanks!

**Pull request merged**
