### PR TITLE
fix MANPATH for Ubuntu, and tidy up travis dep builder

### PR DESCRIPTION
**Pull request by garlick**

### CODE REVIEW

**Comment by grondo** [comment]
It would probably be pretty easy to test the new case by unsetting MANPATH and run under flux or `flux env`...

**Comment by grondo** [comment]
I wonder if we also have to handle set but empty MANPATH? On my simple tests an empty MANPATH and unset MANPATH seem to be handled the same (system MANPATH is used).

For testing, perhaps something simple like this would work?

```
test_expect_success 'flux appends colon to missing or unset MANPATH' '
      (unset MANPATH && flux /usr/bin/printenv | grep "MANPATH=.*:$") &&
      MANPATH= flux /usr/bin/printenv | grep "MANPATH=.*:$"
'

```

**Comment by garlick** [comment]
Sounds good!  I'll check for empty too and add that test.

**Comment by grondo** [comment]
Thanks!

**Pull request merged**
