### PR TITLE
Add Jadd_int64

### PR DESCRIPTION
**Pull request by dongahn**
This is just a simple patch to add Jadd_int64 to shortjason.h. Since Jget_int64 is already defined in this file, it seems to make sense to add Jadd_int64 here as well. And I also need this for the job status and control API I am working on. Thanks!

Dong

### CODE REVIEW

**Comment by dongahn** [comment]
BTW, I don't know if I need to create a issue in the issue tracker for a simple patch like this. The C4 says

"If the Platform implements pull requests as issues, a Contributor MAY directly send a pull request without logging a separate issue."

How do you pull requests as issue?

Dong

**Comment by dongahn** [comment]
Hmmm. I don't know why the Travis CI build failed...

**Comment by grondo** [comment]
Pull requests are a special type of issue on GitHub. So opening a PR only is fine.

The Travis build failed because it seems like luarocks server is down. I'll retry build in morning.

**Comment by grondo** [comment]
Looks like luarocks.org is still down this AM. :-(

However, this PR seems so straightforward that I don't think we need to wait for test results.

In general, though, I'd like to propose that we don't issue *individual* pull requests for new functions or code that isn't used or required by existing code or by subsequent commits in the same PR.

For example, instead of an individual PR adding `Jadd_int64`, a better history would be promoted by having this commit appear in your pull request for the job status plugin. So the history would first include a commit adding `Jadd_int64`, then subsequent commit(s) that utilize the newly added function. This keeps code dependencies and dependents closer together in history.

Does that make any sense? If you'd like we can still merge this simple PR though.

**Comment by dongahn** [comment]
Thanks Mark. This makes perfect sense! Since this doesn't block me anything, I will make this patch as part of the upcoming PR for the job status and control library.

**Pull request closed without merging**
