### PR TITLE
consolidate installed libraries and source tree cleanup

### PR DESCRIPTION
**Pull request by garlick**
As discussed in #1084, this PR moves libkvs, libkz, and libjsc from src/modules to src/common and folds libkvs and libjsc into libflux-core.so.  libkz is not publicly exported so it's folded into libflux-common.la.  There are no actual API or code changes proposed here, just moving things around internally and conslidating external libraries.

Having separate installed shared libraries for those interfaces that are all listed in flux-core.pc was a bit silly.  We got there by trying to co-locate comms modules and their APIs together in the source tree, but I think the consensus in hindsight is that this is not worth it.

The reason for kicking this off now was to make it easier to enumerate the library interfaces that are licensable under LGPL; however, I'm not sure that's actually needed.  We could just say "in addition Flux libraries may be licensed..." and not actually name them.  So just consider this cleanup.

One loose end is libflux-optparse.so.  I left that one separate because it's fairly standalone.  It seems like either it should be folded into libflux-core.so like the others, or have it's own pc file.  Thoughts?

### CODE REVIEW

**Comment by grondo** [comment]
> One loose end is libflux-optparse.so.

It probably should not go into libflux -- is it installed publicly just because other projects might want to use it? (i.e. any reason it can't also be included as convenience library only) If it needs to be installed I agree it should have its own .pc file.

**Comment by grondo** [comment]
Everything "just worked" for me testing on hype. Nice job.

**Comment by garlick** [comment]
Thanks.  optparse was exported so that projects outside of core could provide utilities that work in a uniform way.  I'll push another commit that adds a pc file.

**Comment by garlick** [comment]
Note that sched doesn't appear to use optparse, so I think this PR won't dismember any cute furry animals like before.

**Comment by grondo** [comment]
Looks good, thanks.

**Pull request merged**
