### PR TITLE
reduce legacy KVS API

### PR DESCRIPTION
**Pull request by garlick**
This PR finally gets rid of the json-c based KVS API functions that were marked deprecated, and removes a lot of the older "get" functions, updating users to `flux_kvs_lookup()`.  It also adds a man page for `flux_kvs_lookup()`.

### CODE REVIEW

**Comment by garlick** [comment]
Just fixed a commit message and forced a push.   I should have added that I'm pretty sure none of the KVS interfaces used by sched were altered here (based on examining source, not an actual test).

**Comment by grondo** [comment]
Nice. sorry about all the work required in the outdated lua bindings.

**Comment by garlick** [comment]
No worries on the lua stuff.   BTW I'm done here and hitting the road.  My intent is to continue in another PR with a cleanup of the `kvsdir_t` stuff and expanded docs.

**Comment by grondo** [comment]
Ok, so this is ready for merge? I'm kind of confused by the coverage drop but nothing looks too out of the ordinary at this point.

**Comment by garlick** [comment]
I think it would be OK to merge.  I didn't look too closely at the coverage.  The KVS API was well covered and this removes a chunk of it, so I could see overall project coverage dropping a bit.  The lookup API replaces one call with two thus there are more error paths that are probably not checked.

**Pull request merged**
