### PR TITLE
More wreck cleanup

### PR DESCRIPTION
**Pull request by grondo**
This PR contains a little more wreck cleanup:

 - remove `resrc` module in preference for `resource-hwloc` info
 - update `job` module to remove deprecated functions
 - `job` module publishes `wreck.state.reserved` on job.create, listening for its own event (hopefully got this right) before responding to caller
 - fix for the wreckrun signal test

I did not test changes in `job` that affected the sim_sched race workaround. Shortly, jsc will be ported to new events mechanism in wreck and hopefully the sim_sched hack can be removed after the simulator/emulator is ported to that new mechanism.

@SteVwonder -- if you want to test before this PR goes in I'd also be fine with that.

### CODE REVIEW

**Comment by SteVwonder** [comment]
It looks good to me.  As you mentioned, it will be removed soon anyway.

**Comment by dongahn** [comment]
Great job, @SteVwonder!

**Comment by garlick** [comment]
All this cleanup is really great.

Completely optional if you want to address this here, but one thing I had noticed when looking through broker logs after trying to launch 100 jobs in the background was that wreck is emitting at least two LOG_ERR messages on a regular basis.  My impression is at least the waitpid one is probably should LOG_INFO or even LOG_DEBUG.  The other one I'm not so sure about:
```
lt-flux-broker: [1440972081.690537] lwj.200.err[1] waitpid ()
lt-flux-broker: [1440972081.694353] lwj.200.err[1] waitpid ()
lt-flux-broker: [1440972004.986621] lwj.78.1.err[1] kvs_get_dir: No such file or directory
lt-flux-broker: [1440972008.236010] lwj.94.1.err[1] kvs_get_dir: No such file or directory
```
Anyway thought I'd throw that out in case it was a no-brainer to fix the log levels in this PR.

**Comment by garlick** [comment]
By the way the event workaround for issue #342 looks good to me.

**Comment by grondo** [comment]
>  My impression is at least the waitpid one is probably should LOG_INFO or even LOG_DEBUG. The other one I'm not so sure about:

I noticed this too (though I haven't seen the kvs_get_dir error yet), and it was on my list to investigate. (In general logs from wrexecd are a bit verbose). I haven't looped back around to this yet, but I'll try to get to it soon. Fine with me if you want to wait for it.

**Comment by garlick** [comment]
Naa, let's merge this.  I'm going to press the button.

**Comment by dongahn** [comment]
Well... I just tested this PR with JSC and I see this problem:

It turns out jsc cannot harvest the wreck.state.reserved emitted form the job module when it is loaded into the same rank. I think this is because of #233.

Also FYI -- I still see the SEGV when wreck is stressed with lots of jobs overlapped. I will debug if that's jsc or something else.

**Comment by garlick** [comment]
Oh sorry @dongahn, maybe I was too eager with the button.  I'm confused by the #233 reference - did you mean the closed "message match" behavior issue?

**Comment by dongahn** [comment]
Also sorry for my eager posting here. Let me spend a bit more time on this; this could just be a revision control issue. Stay tune.

**Comment by dongahn** [comment]
Hmmm. @garlick a question: when the message type is an event and there are two modules subscribed to that event within the same rank. Will the event be delivered to both of these modules to be matched now? At one point, this was an issue and I just don't recall what came out of that discussion.

**Comment by garlick** [comment]
No that has never been an issue that I recollect unless it was a short term bug.  Events have always been broadcast to all subscribers and that is fundamental to the design.

**Comment by dongahn** [comment]
OK. Then, this probably was a mistake on my part to rebaseing to grondo's branch.

**Comment by dongahn** [comment]
This was my bad. (Probably didn't recompile after the rebase). BTW, what a job, guys.This patch allowed me to pass all of the jsc subtests including both of the stress cases!

cab689{dahn}117: ./t2001-jsc.t --long
ok 1 - jstat 1: notification works for 1 wreckrun
ok 2 - jstat 2: jstat back-to-back works
ok 3 - jstat 3: notification works for multiple wreckruns
ok 4 - jstat 4: notification works under lock-step stress
ok 5 - jstat 5: notification works for overlapping wreckruns
ok 6 - jstat 6: notification works for overlapping stress
ok 7 - jstat 7.1: run hostname to create some state
ok 8 - jstat 7.2: basic query works: jobid
ok 9 - jstat 7.3: basic query works: state-pair
ok 10 - jstat 7.4: basic query works: rdesc
ok 11 - jstat 7.5: basic query works: pdesc
ok 12 - jstat 8: query detects bad inputs
ok 13 - jstat 9: update state-pair
ok 14 - jstat 10: update procdescs
ok 15 - jstat 11: update rdesc
ok 16 - jstat 12: update rdl
ok 17 - jstat 13: update rdl_alloc
ok 18 - jstat 14: update detects bad inputs
# passed all 18 test(s)
1..18

**Comment by garlick** [comment]
Excellent!

**Pull request merged**
