### PR TITLE
[WIP] job-manager: Part 2 - rename annotation "note" and make "note" an object

### PR DESCRIPTION
**Pull request by chu11**
So this PR is a follow up to PR #2960.

The annotation has been converted from a string to a json object in this PR.

All functions / variables / docs have been changed to rename the "note" to "metadata".  I couldn't come up with a better than this, wondering if anyone has a better name.

The json object is updated rather than being overwritten.  If the user responds with a "metadata" message without data, it indicates that the json object should be cleared.  This is debatable, but I chose this b/c I think we should have a way to clear the object (could be via a new flag too).

Now that there are so many corner cases, I will have to write a new sched-dummy to test all of these cases.

- different metadata to different jobs
- can update metadata
- can delete metadata

So that's the remaining WIP part of this PR.  But wanted to get some comments on the above first.

### CODE REVIEW

**Comment by grondo** [comment]
My opinion shouldn't matter much, but I like the name "note" or annotation. Is there no way to still call it a scheduler note but have different classes of note for different responses in the job-manager?

**Comment by chu11** [comment]
> My opinion shouldn't matter much, but I like the name "note" or annotation. Is there no way to still call it a scheduler note but have different classes of note for different responses in the job-manager?

Well, given it's a JSON object now, it just seems confusing (to me atleast) that `note` being a string in some cases and a JSON object in others seemed wrong.  I considered using the word "annotation", but that just seemed long.  But maybe that's me and others are ok with it.

We could take the opposite approach of what I did above.  Instead of changing the annotation from `note` to `metadata`, we can change the name of `note` for all of the other responses.  Although a good name is escaping me right now.

**Comment by chu11** [comment]
> Well, given it's a JSON object now, it just seems confusing (to me atleast) that note being a string in some cases and a JSON object in others seemed wrong. I considered using the word "annotation", but that just seemed long. But maybe that's me and others are ok with it.

Actually, I just had another idea.  The unpack of the alloc response is basically:

`{s?:s s?:o}` for `note` and `metadata`.

Perhaps we can simply change the above to `{s?:o}`.  For all alloc responses, it doesn't matter if it's a string or an object, "stringify" the response's note regardless.  Only for the annotation case can the "object" be updated.

**Comment by dongahn** [comment]
Just a quick note: other than backward compatibility, is there any other reasons to support both a raw string and JSON document for `note`?

**Comment by chu11** [comment]
> Just a quick note: other than backward compatibility, is there any other reasons to support both a raw string and JSON document for note?

The only reason I'm considering it is notation / convenience for users.  So that all `alloc` responses can be of any form.  If we require strings for some responses and objects for others, could be confusing.

**Comment by grondo** [comment]
BTW, I did notice that over in the other PR @garlick also called out for renaming the scheduler "note" to something else, so do not change your current renaming just because of me, I was only expressing my opinion. The underlying name may end up being hidden from end users anyway.

**Comment by chu11** [comment]
talked about this on the con-call, decision was to simply go with json objects in all "notes".  So I'm going to close this.  Next folllow up PR I'll re-add back to #2960

**Pull request closed without merging**
