### PR TITLE
suppress epilog on jobs canceled during shutdown (try no. 2)

### PR DESCRIPTION
**Pull request by garlick**
Problem: most unfortunately, a typo in rc1 rendered #5871 ineffectual.

Fix the typo and add a test this time.

### CODE REVIEW

**Review by grondo — APPROVED** [review]
LGTM. Sorry I missed that in review 😔

**Comment by garlick** [comment]
I'm sorry too, should have added a test then. :-(

**Comment by garlick** [comment]
Hmm, the `t2412-sdexec-perilog.t` is hanging in the cleanup `flux queue idle` command.  I wonder if it is because there is an in-progress epilog and removing the perilog plugin causes it to not post the `epilog-finish` event when it completes?

Adding a `flux queue drain` at the end of the script does seem to fix it.  Hmm, perhaps more thought required here.

**Comment by grondo** [comment]
Hmm, good question about unloading perilog.so when there are prologs and epilogs in progress.. Not sure off hand how to make that "safe".

**Comment by grondo** [comment]
The `epilog-finish` event? Presuming a prolog or epilog is running is that safe? I assume on shutdown the subprocesses that are running these scripts will be terminated. Could that leave nodes in an inconsistent state? (Just thinking out loud)

**Comment by garlick** [comment]
Good point.  What about having the perilog plugin watch the broker's state and when it enters cleanup, stop running new perilogs but continue servicing running ones?

**Comment by grondo** [comment]
That's a great idea!

**Comment by grondo** [comment]
My first thought would be to expose an RPC in the plugin which could adjust optional behavior at runtime?

**Pull request merged**
