### PR TITLE
NEWS.md: update for 0.27.0

### PR DESCRIPTION
**Pull request by garlick**
Here's a proposed set of release notes for our end of the month release.  As always, feel free to push here directly as needed.

### CODE REVIEW

**Comment by grondo** [comment]
Thanks for doing most of the work here!

I updated NEWS.md to include the latest 3 merged PRs, squashed, and forced a push.

**Comment by grondo** [comment]
Pushed another update assuming #3681 goes in.

**Review by grondo — APPROVED** [review]
This LGTM. I added latest merged PRs if you want to check those out @garlick.

**Review by garlick — COMMENTED** [review]
Thanks!  Looks good to me too.

**Comment by grondo** [comment]
Great, I set MWP

**Pull request merged**
