### PR TITLE
mergify: remove status check conditions from config

### PR DESCRIPTION
**Pull request by grondo**
Problem: The required status checks in the mergify config are redundant with GitHub branch protections, and keeping the list of statuses up-to-date in the mergify config is quite painful since updates require a PR and manual merge.

Remove the status checks completely from `.mergify.yml`. Mergify will still ensure that required status checks in branch protections are satified, so this should not change any behavior.

This PR will need a manual merge since `.mergify.yml` was touched. :slightly_smiling_face:

### CODE REVIEW

**Comment by grondo** [comment]
FYI - As a precursor to this I ensured all current status checks are correct in branch protections, and added 1 required review. Reviews will now also be dismissed when branches are force-pushed or updated (that one might end up being a bit of a pain though)

**Review by garlick — APPROVED** [review]
Sounds good!  ready for me to push button?

**Comment by grondo** [comment]
Sure, once the ci completes!

**Comment by grondo** [comment]
Thanks!

**Pull request merged**
