### PR TITLE
NEWS.md: add release notes for v0.34.0

### PR DESCRIPTION
**Pull request by garlick**
Notes for our next release at the end of the week.  As always, please feel free to push directly to this PR.

### CODE REVIEW

**Comment by garlick** [comment]
Updated.

I assumed that #4075 (enhanced pty support) is going in.

**Review by grondo — APPROVED** [review]
LGTM! Thanks for putting these together.

**Comment by grondo** [comment]
@mergifyio rebase

**Comment by dongahn** [comment]
Congrats!

**Pull request merged**
