### PR TITLE
Create codeql.yml

### PR DESCRIPTION
**Pull request by trws**
Initial attempt at configuring building and setup for the github version of LGTM scanning.

### CODE REVIEW

**Comment by grondo** [comment]
Accidentally closed?

**Comment by trws** [comment]
Intentional so I could move to a PR off of my fork, the workflow to create the file creates a branch on the main repo which I was not fond of.

**Comment by trws** [comment]
It actually made it protected so I have to tweak settings to delete it, will do that in a moment.

**Comment by grondo** [comment]
Oh, that was probably me. Might as well delete the other stale branch in this repo at the same time.

**Pull request closed without merging**
