### PR TITLE
correct flux library location

### PR DESCRIPTION
**Pull request by lipari**
Fixes a couple stragglers which should have been included with commit
96e97dea2556680fda03d04cd3c607091523be82
Addresses:  https://github.com/flux-framework/flux-core/issues/551

### CODE REVIEW

**Comment by grondo** [comment]
I wonder if `fluxlibdir` is even needed now (kind of seems pointless to keep it the same as `$libdir`)

It only seems to be used by the broker to prepend to `LD_LIBRARY_PATH` .. @garlick, is that needed anymore?

**Comment by garlick** [comment]
We need it for libpmi
```
fluxlib_LTLIBRARIES = libpmi.la
```

The broker prepends fluxlibdir to the LD_LIBRARY_PATH for the initial program so runtimes can find our PMI library, not slurm's.

**Comment by grondo** [comment]
> We need it for libpmi

Ah, sorry! I did a `git grep` for `fluxlibdir` and so missed the important bits. Ooops.

@lipari, you'll need to back out the change to `configure.ac` -- we still need `fluxlibdir` set to `$libdir/flux`

**Comment by lipari** [comment]
> @lipari, you'll need to back out the change to configure.ac -- we still need fluxlibdir set to $libdir/flux

Done and re-pushed.  Seeing some random test failures though:
https://travis-ci.org/lipari/flux-core/jobs/108090144
https://travis-ci.org/flux-framework/flux-core/jobs/108090151

**Comment by grondo** [comment]
> Seeing some random test failures though:

Yeah, the Travis testsuite seems to have gotten less stable this week. It seems like the vm/docker hosts are more loaded and thus tests run slower and hit timeouts, etc.

We'll have to go through the testsuite and modify timeouts (maybe add a multiplier for Travis) and also consolidate `nproc(1)` usage and restrict to some sane max...

**Comment by grondo** [comment]
Looked good though. Merged.

**Pull request merged**
