### PR TITLE
add flux overlay trace

### PR DESCRIPTION
**Pull request by garlick**
Problem: there is no way to observe the message the broker is sending and receving on the overlay network.

Solution: the broker implements a streaming RPC that sends a one line summary of each message sent/received on the overlay network to a tool, `flux overlay trace`.

The format is:
```
[tx|rx] peer-rank message-type topic-string [size]
```
where e=event, >=request, <=response, c=control

I thought I'd post this and ask for feedback on the output format before proceeding (hence WIP).

Here's an example of an instance that running a couple of jobs then shutting down.
```
$ flux overlay trace
tx 1 e heartbeat.pulse [0]
tx 1 e heartbeat.pulse [0]
tx 1 e heartbeat.pulse [0]
tx 1 e kvs.namespace-primary-setroot [209]
tx 1 e kvs.namespace-primary-setroot [177]
tx 1 e kvs.namespace-primary-setroot [170]
tx 1 e kvs.namespace-job-736687554560-created [116]
tx 1 e kvs.namespace-primary-setroot [174]
tx 1 e kvs.namespace-job-736687554560-setroot [167]
tx 1 e kvs.namespace-primary-setroot [177]
tx 1 e kvs.namespace-job-736687554560-setroot [167]
tx 1 e kvs.namespace-job-736687554560-setroot [160]
tx 1 e kvs.namespace-job-736687554560-setroot [161]
tx 1 e kvs.namespace-job-736687554560-setroot [168]
tx 1 e kvs.namespace-job-736687554560-setroot [168]
tx 1 e kvs.namespace-job-736687554560-setroot [161]
tx 1 e kvs.namespace-job-736687554560-setroot [168]
tx 1 e kvs.namespace-job-736687554560-setroot [168]
tx 1 e kvs.namespace-primary-setroot [175]
tx 1 e kvs.namespace-job-736687554560-removed [33]
tx 1 e kvs.namespace-primary-setroot [179]
tx 1 e heartbeat.pulse [0]
tx 1 e heartbeat.pulse [0]
tx 1 e heartbeat.pulse [0]
tx 1 e heartbeat.pulse [0]
tx 1 e heartbeat.pulse [0]
tx 1 e heartbeat.pulse [0]
tx 1 e heartbeat.pulse [0]
tx 1 e heartbeat.pulse [0]
tx 1 e heartbeat.pulse [0]
tx 1 e heartbeat.pulse [0]
tx 1 e kvs.namespace-primary-setroot [211]
tx 1 e kvs.namespace-primary-setroot [179]
tx 1 e kvs.namespace-primary-setroot [172]
tx 1 e kvs.namespace-job-1056629063680-created [117]
tx 1 e kvs.namespace-primary-setroot [176]
tx 1 e kvs.namespace-job-1056629063680-setroot [169]
tx 1 > rexec.exec [4.2167969K]
rx 1 < rexec.exec [33]
tx 1 e kvs.namespace-primary-setroot [179]
tx 1 e kvs.namespace-job-1056629063680-setroot [169]
rx 1 > kvs.getroot [24]
tx 1 < kvs.getroot [118]
rx 1 > kvs.getroot [24]
rx 1 > kvs.getroot [24]
tx 1 < kvs.getroot [118]
tx 1 < kvs.getroot [118]
rx 1 > content.load [20]
tx 1 < content.load [305]
rx 1 > content.load [20]
tx 1 < content.load [121]
rx 1 > content.load [20]
tx 1 < content.load [211]
rx 1 > content.load [20]
tx 1 < content.load [121]
rx 1 > content.load [20]
tx 1 < content.load [121]
tx 1 e kvs.namespace-job-1056629063680-setroot [161]
rx 1 > content.load [20]
tx 1 < content.load [721]
tx 1 e kvs.namespace-job-1056629063680-setroot [162]
rx 1 > content.load [20]
rx 1 > content.load [20]
tx 1 < content.load [6.3105469K]
rx 1 > content.load [20]
tx 1 < content.load [176]
rx 1 > content.load [20]
tx 1 < content.load [109]
rx 1 > content.load [20]
tx 1 < content.load [51]
rx 1 > content.load [20]
tx 1 < content.load [49]
rx 1 > content.load [20]
tx 1 < content.load [77]
rx 1 > content.load [20]
tx 1 < content.load [132]
tx 1 < content.load [48]
rx 1 < rexec.exec [85]
tx 1 > rexec.write [68]
tx 1 e kvs.namespace-job-1056629063680-setroot [169]
rx 1 < rexec.exec [85]
tx 1 > rexec.write [68]
rx 1 > kvs.getroot [34]
tx 1 < kvs.getroot [127]
rx 1 > 5588-shell-fUkqh9EF.write [83]
tx 1 e kvs.namespace-job-1056629063680-setroot [169]
rx 1 > 5588-shell-fUkqh9EF.write [95]
rx 1 > 5588-shell-fUkqh9EF.write [83]
rx 1 > content.load [20]
rx 1 > 5588-shell-fUkqh9EF.doom [96]
tx 1 < content.load [304]
rx 1 > 5588-shell-fUkqh9EF.write [43]
rx 1 > content.load [20]
tx 1 < content.load [135]
tx 1 < 5588-shell-fUkqh9EF.write [0]
tx 1 < 5588-shell-fUkqh9EF.write [0]
tx 1 < 5588-shell-fUkqh9EF.write [0]
tx 1 e kvs.namespace-job-1056629063680-setroot [169]
tx 1 e kvs.namespace-job-1056629063680-setroot [162]
tx 1 < 5588-shell-fUkqh9EF.write [0]
rx 1 > 5588-shell-fUkqh9EF.disconnect [0]
rx 1 < rexec.exec [79]
rx 1 < rexec.exec [79]
rx 1 < rexec.exec [31]
rx 1 < rexec.exec [0]
tx 1 e kvs.namespace-job-1056629063680-setroot [169]
tx 1 e kvs.namespace-primary-setroot [176]
tx 1 e kvs.namespace-job-1056629063680-removed [34]
tx 1 e kvs.namespace-primary-setroot [179]
tx 1 e heartbeat.pulse [0]
tx 1 e heartbeat.pulse [0]
tx 1 e heartbeat.pulse [0]
tx 1 e heartbeat.pulse [0]
tx 1 e heartbeat.pulse [0]
tx 1 e heartbeat.pulse [0]
tx 1 e heartbeat.pulse [0]
tx 1 e heartbeat.pulse [0]
tx 1 < state-machine.monitor [12]
tx 1 < state-machine.monitor [12]
tx 1 < state-machine.monitor [0]
rx 1 > log.append [86]
rx 1 > log.append [97]
rx 1 > log.append [99]
rx 1 > log.append [69]
rx 1 > resource.disconnect [0]
rx 1 > log.append [77]
rx 1 > log.append [69]
rx 1 > job-info.disconnect [0]
rx 1 > log.append [77]
rx 1 > log.append [71]
rx 1 > job-ingest.disconnect [0]
rx 1 > log.append [79]
rx 1 > log.append [68]
rx 1 > log.append [76]
rx 1 > log.append [70]
rx 1 > log.append [78]
rx 1 > log.append [64]
rx 1 > kvs.disconnect [0]
rx 1 > log.append [72]
rx 1 > log.append [68]
rx 1 > content.disconnect [0]
rx 1 > log.append [76]
rx 1 > overlay.goodbye [0]
tx 1 < overlay.goodbye [0]
```

Hmm, timestamps.

### CODE REVIEW

**Comment by garlick** [comment]
I added timestamps and moved the line formatting from the broker to the client (so the broker now sends a JSON object instead of a line).   It seems like this should evolve to work like `flux dmesg` and the eventlog commands with color and human readable timestamps, but I'm just keeping things simple for now.

**Comment by grondo** [comment]
Looks great to me!

**Comment by garlick** [comment]
Thanks!  OK I added a test and a man page update, and dropped the WIP.

It might be nice to have a `flux module trace` too, but that could be another PR I guess.

**Review by grondo — APPROVED** [review]
Nice! LGTM!

**Comment by garlick** [comment]
OK! Then I'll set MWP, thanks!

**Pull request merged**
