### PR TITLE
Python json and constant rework

### PR DESCRIPTION
**Pull request by trws**
This PR reworks constants so they are no longer doubly defined, while maintaining the same interface, removes json_c bindings, and cleans up a lurking out-of-tree build testing bug that has apparently been lurking for a while.

### CODE REVIEW

**Comment by grondo** [comment]
Thanks! Compiles on hype with cffi-1.1.x, but dies in `make check`:
```
Traceback (most recent call last):
  File "../src/bindings/python/test_commands/test_runner.t", line 53, in <module>
    run_under_dir(result_set, '../test', 'test')
  File "../src/bindings/python/test_commands/test_runner.t", line 29, in run_under_dir
    (mod_prefix, m.group(1))))
  File "/opt/python-2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/g/g0/grondo/git/f/src/bindings/python/test/wrapper.py", line 6, in <module>
    import flux.json_c
ImportError: No module named json_c

```
	
Also, perhaps commit message for 	3b6f91b needs an update? It says "rework constant handling" but it just seems to add some `import` calls. (I'm not a python guy so apologies if I missed something obvious!)

**Comment by trws** [comment]
Thanks @grondo, not sure how check succeeded for me, maybe I still had a 
dirty path or something.  Will post a fix and a rebase shortly.

**Comment by trws** [comment]
One thing to note, a few constants that used to be macros are now static constants in this PR.  This has not caused any problems for me, and wont unless they're used in a non-executable context, but it's technically a change to the exposed headers.  If this is a problem, I can special case those macros and have the binding generator create function wrappers for them, but this seemed more forward-portable.  Another alternative would be to convert them into enums if that would be preferable, which might bring back the ability to reference them in a static initializer.

**Comment by garlick** [comment]
@trws if we could have the incremental changes to C headers squashed into one (standalone) commit instead of hopping from #define to const to enum, I'd appreciate it.

Same with the out of tree install bug fix.   Is this #805 (just opened - saw this last night and was going to follow up).  Please reference that if so.

Getting rid of the json-c stuff and the doubly defined constants is good cleanup!

**Comment by trws** [comment]
I think this addresses the cleanup you mention @garlick.  The build update may help with #805, but that looks more like a permission problem than an issue with files being missed in transfer.

**Comment by trws** [comment]
Evidently there's an issue with the travis version of cffi I wasn't seeing in my environment where calculated enum values are concerned, this version should take care of it.

**Comment by garlick** [comment]
Travis is still failing, although the PR is looking nicely factored now.

**Comment by trws** [comment]
Travis is now dying on #805.  Looking into it, but it doesn't reproduce directly for me locally, so there may be a couple of rounds with travis working this out.

**Comment by trws** [comment]
Turns out my earlier solution works fine with out of tree check, but not with distcheck due to inheriting the read-only properties from the dist source directory.  Should be good to go at this point.

**Comment by garlick** [comment]
Great!   Want to squash the two message.c changes, and the two build system changes?

**Comment by trws** [comment]
Somehow this fell off my radar for a bit.  Rebased and should be good to go.

**Comment by grondo** [comment]
This one looks good to me. I did have a problem where I checked out your branch but did not run `make clean` and the python bindings didn't have the new constants, but I don't think that is a new problem, and shouldn't hold up this PR.

**Comment by grondo** [comment]
Actually, one comment: I'm not sure how strongly I feel about this, but I guess the new enum wrappers for constants will be in a public API so perhaps they should have *`flux_`* prepended or something?, e.g. `enum flux_nodeid` not just `enum nodeid`?

**Comment by trws** [comment]
I don't see why not, I can add that real quick.

By the way, the other PR, #807, should address the issue with the bindings not getting updated during a build/check.

**Comment by grondo** [comment]
> By the way, the other PR, #807, should address the issue with the bindings not getting updated during a build/check.

Oh, awesome!

**Comment by trws** [comment]
When I went to update the enum names, I noticed the others are all anonymous enums, so I made these follow that convention.

**Comment by grondo** [comment]
> When I went to update the enum names, I noticed the others are all anonymous enums, so I made these follow that convention.

That works for me, sorry I should have suggested that

**Comment by garlick** [comment]
Thanks for this work @trws - I'll merge as soon as travis turns green.

**Comment by garlick** [comment]
The clang build failed here, which is an odd place that in any case would seem to have nothing to do with this PR.  The other builds were OK so I just restarted it.
```
not ok 71 - stat watcher invoked once for size chnage
#   Failed test 'stat watcher invoked once for size chnage'
#   at ../../../../src/common/libflux/test/reactor.c line 644.
ok 72 - stat watcher invoked once for nlink set to zero
ok 73 - destroying reactor then watcher doesn't segfault
1..73
# Looks like you failed 1 test of 73 run.
FAIL: test_reactor.t
===================
1 of 7 tests failed
===================
```

**Pull request merged**
