### PR TITLE
Add --bootstrap option to flux-start

### PR DESCRIPTION
**Pull request by morrone**
Add --bootstrap option to flux-start, preceded by a number of cleanup patches.

### CODE REVIEW

**Comment by garlick** [comment]
No time to look in detail right now - just quick comments:

I see at least one functions with no paramters prototyped like `foo ()`.  I lean towards `foo (void)`.  In fact I thought c99 would complain but apparently not since travis is passing.   Thoughts?  (If it's not a c99 thing then I suppose its a matter for RFC 7 unless we don't care).

The cleanup in here looks fine in general

It looks like `flux start`  is still backwards compatible with the way we've been using it?

**Comment by morrone** [comment]
OK, I made the update to make the function declarations actual prototypes with (void).

Yes, this just implements #952.

**Comment by grondo** [comment]
In general, is the pattern of bundling program state into a context struct, and passing that around to ancillary functions considered poor form, or was this a special case in this PR?

I tend to like avoiding the "global context" because it makes it more difficult to see which functions are using or require bits of the program state, so I have made this same choice (mistake?) many times. It would help if there was some other guidance as to why its usage here was unpalatable.

**Comment by dongahn** [comment]
> In general, is the pattern of bundling program state into a context struct, and passing that around to ancillary functions considered poor form, or was this a special case in this PR?

I also think having some guidance here would be useful. At least for a C API, I tend to like the style of passing around an API-level context as the opaque object between the client and API implementation.

**Comment by garlick** [comment]
We just had a mini discussion on this in our meeting.  Let me see if I can summarize:

First we are talking about a single program context here, not an API context.  The program context is effectively global if it's passed to every function in the program.

When the program context is passed as a parameter to functions instead of the one or two things in it that they actually need, then the cues about the extent of the function's inputs and outputs normally present in the parameter list are lost.

When state is placed in the context instead of being created/destroyed at the level of abstraction that it's needed, cues about when it can change and how it is used are lost.

Finally, (and this might be less unanimously agreed upon by the group), mallocing a context that is only used once confuses the casual reader of the code about its intended use.  Can there be more than one?

Did I cover the main points?

These changes look good - merging.

**Comment by morrone** [comment]
Good summary!

**Comment by dongahn** [comment]
Makes sense!

**Comment by garlick** [comment]
A downside of making the context actually global is now you don't get any cues from a function's parameter list that it's been weened off of the context...

**Pull request merged**
